### ISSUE TITLE
Cannot Implicitly cast Int3 to Float3

### ISSUE THREAD

**Issue by H3BO3** [Frooxius/NeosPublic#1000]
I'm not sure how many other datatypes this happens with, but I was unable to perform this kind of cast. I wasn't sure if such a node exists to convert the types explicitly, so the only way I could get this to actually work was by unpacking the value, casting all three individually, then repacking it as a float3.

**Comment by shiftyscales** [comment]
I've tried the reverse, and I imagine it might also be the case with other packed nodes. I don't think it's a bug, but rather just that those specific casts haven't been implemented/there hasn't been a specific demand for them.

It could also potentially be that there might need to be a slight extension to how casting works to accommodate packed types? But I'm not entirely certain. For that, I'd need @Frooxius' input.

**Comment by Frooxius** [comment]
This is because of invalid castability detection for certain types in the underlying supporting code. I have a fix coming.

**Comment by Frooxius** [comment]
Fix is out in 2020.9.9.214 thanks!
