### ISSUE TITLE
World preview modal user list dropdown blocks scrolling when closed

### ISSUE THREAD

**Issue by H3BO3** [Frooxius/NeosPublic#1001]
When a world preview modal is opened from the browser, and the user list dropdown is closed, you cannot hover over the space where it would be if it were open - The hover events to scroll the 360 preview just stop. Based on the region where the events get blocked, it matches how large the dropdown is when it is open.

**Comment by shiftyscales** [comment]
Having investigated this, it appears to be both the buttons and the text (e.g. user names/description) that are blocking the pass-through.

I think it would also be worth preventing the user names/description from blocking pass-through even while it's open/active.

**Comment by Frooxius** [comment]
The RawGraphic wasn't properly reporting if a point was inside or not, fixed in 2020.9.9.214 which fixes this, thanks!
