### ISSUE TITLE
Swapping dynamic variable target ref does not populate target ref

### ISSUE THREAD

**Issue by Earthmark** [Frooxius/NeosPublic#1009]
Dynamic variable drivers do populate their target when the string variable id changes, but they do not update the new target property when the target property changes.

If the backing variable updates then the dynamic variable does update, but that feels strange behavior wise. It might be intended, but it also might not!

**Comment by TehTurk** [comment]
So it's only on manual field assignment it doesn't update? Or does it work when your write directly into it.

**Comment by Earthmark** [comment]
This is specifically the behavior that given a DynamicVariableDriver, if the VariableName is set but the Target is not.

When you assign Target, the field pointed to by Target is not updated with the value from the DynamicVariableSpace. Either the value in the space needs to be updated, or the VariableName of the DynamicVariableDriver needs to change for the property pointed to by Target to be updated.

**Comment by Earthmark** [comment]
Do you need more information? I attempted to provide context above.

**Comment by Frooxius** [comment]
I know what's up, I'll fix it soon, thanks!

**Comment by Frooxius** [comment]
Should be good in 2020.10.5.476!
