### ISSUE TITLE
LAN sessions in world browser

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#1012]
Saliven#6831 in Discord was confused to find that they could not discover their LAN session in the world browser. I had to clarify that they could find it on the session joiner table.

Having LAN sessions as a data source could be useful in the future.

Not a high priority since the sessions still appear properly on the session joiner.

**Comment by Frooxius** [comment]
This is odd, LAN sessions should 100 % show up in the World Browser. It doesn't need a separate data source, because LAN sessions are already part of the session data source and it's the exact same one that Session Joiner is using, so it's kinda strange that it would show up there.

Has this been replicated? Are you sure they just haven't missed the session by accident?

**Comment by Frooxius** [comment]
I just tested this and started a LAN session. It shows up in the new world browser for me as well as the session joiner.

**Comment by shiftyscales** [comment]
Oh! I think I know what it is, actually. They were running it as a headless session. It showed up for them on the world browser once one client had joined. Hmm... That being the case, I wonder if it might be good to have a "LAN" search preset?

**Comment by Frooxius** [comment]
I think LAN search preset is a bit too niche. Originally the Active Sessions would show empty headless sessions, but since that was changed they won't show up anymore under that preset. It should still show as part of Everything. We could add "All sessions" possibly or something like that.

**Comment by shiftyscales** [comment]
I feel having LAN sessions listed could be potentially beneficial for local events, and educational use too.

I feel it has much more utility/purpose than 'All Sessions' would. All sessions would be a bit confusing when there is already 'Everything', and it would be easy enough to get 'All Sessions' by doing a custom search from Active Sessions and setting the minimum user count back to 0.

**Comment by Frooxius** [comment]
Problem with that is that it would work only with that specific setting. You can have local worlds/headless that's not specifically configured to show on LAN. E.g. it could be configured to "Friends" or "Anyone" so it's accessible over internet, but empty. It would not be accessible if the filtering showed only LAN ones, even though they're accessible on LAN.

Alternatively we could do "Headless Sessions" category, which shows all headless ones, including empty ones. That might be best fit.

**Comment by shiftyscales** [comment]
I could definitely see potential utility there in the short-term for users that want a neutral/external host if their own connection can't support having many other users as a stop-gap prior to having official Neos servers in the future.

**Comment by Frooxius** [comment]
Added the "Headless Sessions" category in 2020.9.16.596, that should solve the issue I think!
