### ISSUE TITLE
Slot Children Events causing null parents on deletion

### ISSUE THREAD

**Issue by Coffee-Maker** [Frooxius/NeosPublic#1014]
If you use a slot children events node and delete the OnAdded slot immediately it causes the slot to get a null parent and makes the slot which was supposed to contain it report that it has 1 child, using a getChild reports the slot and shows that it has a null parent. This stops the world from being savable, the slot from being duplicatable, and a whole bunch of other weird stuff.
![2020-09-12 03 30 05](https://user-images.githubusercontent.com/25093209/92985214-6b4b4700-f4a8-11ea-9695-39f869d72556.jpg)

**Comment by TehTurk** [comment]
Does it crash? I remember this used too but I'm pretty sure this is by designs as the Events nodes occur before any of the parenting operations occur. I recall asking this myself

**Comment by H3BO3** [comment]
I've seen this issue before, though I'm unsure if it was a null parent. In my case I was reparenting it directly after the event and that was also causing the item to disappear. Saving the world and then opening it back up "fixed" the items, and I was able to see them and delete them, but before that I was seeing a lot of devtip inspection lag from the orphaned slots.

**Comment by shiftyscales** [comment]
As of 2020.8.10.1195, slots that are orphaned are supposed to be cleaned up/deleted automatically. Is that not occurring here then, @Coffee-Maker?
```
- Added orphaned slot cleanup mechanism when parent is destroyed, but its children are not (causing slots that separate from the scene hierarchy), which fixes variety of issues caused by those
-- E.g. the dev tooltip selection taking longer and longer due to trying to compute positions of the orphaned slots, reported by @Earthmark, @H3BO3, @Shifty | Quality Control Lead, @Napo and @Enverex)
-- Also users getting respawned when trying to grab such orphaned object (didn't keep list of reports for this one, sorry!)
-- This will also help fix high memory usage in cases of orphaned slots being constantly generated and accumulate over time
```
https://discordapp.com/channels/402159838827905024/469131434628612116/742472766833426484

**Comment by H3BO3** [comment]
It only seemed to correct the issue to the last known parent when I saved and reopened the world, it was like they were in some kind of limbo

**Comment by Hayden-da-Serg** [comment]
The slots appear to be in a strange state, they exist only to the user who performs that action and no one else, resulting in desynced children counts and broken inspector visuals.

**Comment by Zyzyl** [comment]
This sounds like it may be related to https://github.com/Frooxius/NeosPublic/issues/666 - specifically the part about:
"The index of the slot given by the ChildAdded output is reported as -1 if the check occurs in an impulse chain initiated by the OnChildAdded output (checked with Get Child Index)."

**Comment by Coffee-Maker** [comment]
@TehTurk The issue does not crash the game or world.

@shiftyscales  The orphaned slots do not get cleaned up and I am unable to fix the issue manually from what I have tested.

**Comment by Frooxius** [comment]
I've restructured how those events fire in 2020.9.14.511, so the system doesn't get messed up by changing parent or destroying during the event. It seems to work ok now.
