### ISSUE TITLE
Ignore raycasts on tutorial controller visuals

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#1015]
Reported by Duskitty#4455 on Discord, the tutorial controller visuals on his Rift S controllers can block the lasers of his avatar.

**Comment by Frooxius** [comment]
Hmm this is odd. Are you sure it's the tutorial visuals? I checked the code and they shouldn't he any colliders at all.

**Comment by shiftyscales** [comment]
This appears to happen when the tutorial visuals are overlayed right on top of the lasers. If they are out of range, the lasers don't interact with them with the hand that's generating the lasers. But they definitely have mesh colliders as the userspace lasers can walk their surfaces.

To test this out I tried using the Akita avatar (which has short limbs) so that I could easily move the controller visual around the laser.

https://cdn.discordapp.com/attachments/439422161657135106/754690515190153347/2020-09-13_06-08-42.mp4

**Comment by Frooxius** [comment]
Oh I see. I thought you were talking about the labels. I'll check the controller models and make sure they don't have colliders on them. Thanks!

**Comment by Frooxius** [comment]
Should be fixed in 2020.9.14.511 thanks!
