### ISSUE TITLE
Logix - 'Has Tag'

### ISSUE THREAD

**Issue by ukilop** [Frooxius/NeosPublic#1017]
In LogiX under 'Slots' category there exists the 'Has Tag' node, the naming of this node lead me to believe that slots could have multiple tags by use of some form of separator character. Try as I might I could not find one, so I suggest either renaming that node to 'Is Tag' if current behavior is kept. But What I would like to see is 'Has Tag' node to scan the tag field as a comma-separated-list and return true if any field in the list matched the string input.

**Comment by Frooxius** [comment]
I'm sorry for the confusion, but "Is Tag" would be incorrect, "Has Tag" is correct terminology. "Has" doesn't imply number of something, just presence. Tag is something that a Slot "has", but that doesn't mean that Slot "is" a tag. Changing this would also be inconsistent with all other terminology in-game.
