### ISSUE TITLE
Userspace lasers inaccessible when hand proxies are disabled

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#1018]
Reported by SmolCookie, if the hand proxies are disabled under an avatar, the userspace lasers are inaccessible.
This appears to be because the laser's positions are fixed to the disabled proxy slots.

Steps to replicate:
- Set either of the "Left Hand Proxy" or "Right Hand Proxy" slots as inactive and attempt to use the userspace lasers to interact with the UI
- The lasers remain fixed in place attached to the avatar's hand and pointing in whatever direction they were last facing

This specifically appears to occur for avatars that have a tooltip anchor that is parented underneath the avatar's hand.
For avatars that don't have a tooltip anchor/are using the controller-positioned lasers, this issue does not occur. It's specific to disabling the hand proxy underneath the avatar's slot if that avatar has a tooltip anchor parented under its hand.

The lasers will attempt to move with the controller, but will get dragged back to the point they were last aiming.

**Comment by Frooxius** [comment]
Should be fixed in 2020.9.13.591 thanks!
