### ISSUE TITLE
Unity SDK Ignores Detail Textures

### ISSUE THREAD

**Issue by Enverex** [Frooxius/NeosPublic#1019]
Currently when converting a material, the Unity SDK ignores the detail textures entirely (both the albedo and the normal map). These obviously also need to be included. The fix for this I've been using is adding this...

```
        pbs.DetailAlbedoTexture.Target = data.Get2D(material.GetTexture("_DetailAlbedoMap"));
        pbs.DetailTextureScale.Value = material.GetTextureScale("_DetailAlbedoMap").ToNeos();
        pbs.DetailTextureOffset.Value = material.GetTextureOffset("_DetailAlbedoMap").ToNeos();
        pbs.DetailNormalMap.Target = data.Get2D(material.GetTexture("_DetailNormalMap"), true);
```

To the bottom of the `internal static void ConvertPBSShared` function call (line 548 in UnityToNeosConverter.cs).

**Comment by Frooxius** [comment]
Made the modifications and updated the SDK, should be converting now! Thanks!
