### ISSUE TITLE
Unity SDK Imports Materials with Emission Enabled if Emission Has a Value, Even if Disabled.

### ISSUE THREAD

**Issue by Enverex** [Frooxius/NeosPublic#1020]
If a material has an emission on it, say, HDR White, but Emission is turned off. The SDK will import the material with Emission enabled despite the fact it was turned off on the material itself, resulting in scenarios such as this...

![image](https://user-images.githubusercontent.com/958670/93019935-1d326280-f5d2-11ea-9647-d99cb2e7bec5.png)

I assume this is down to the fact that you can't enable/disable Emissions in Neos, you can only "disable" them by setting them to black so while it makes sense, it's clearly not desired behaviour in this instance.

**Comment by Frooxius** [comment]
Added a check for when the material has emission enabled in the updated SDK, should be better now. Let me know if there are still issues!
