### ISSUE TITLE
Online users facet only displaying 'Online Users:' regardless of facet size

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#1021]
Reported by AdmiralSoap, on the latest build of Neos, the online users facet only displays the online user count regardless of its size instead of the user split (total/VR/screen/headless).

**Comment by Frooxius** [comment]
This is normal, the facet has never displayed anything else based on the size, it's always only been the total sum. Only user-made custom facets display the split, but not the official Neos one.
