### ISSUE TITLE
Userspace laser alignment issues

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#1022]
Little Helper has reported that with the change in how the userspace lasers are positioned as of the last build, their userspace lasers are flickering between the two positions.

https://cdn.discordapp.com/attachments/439422161657135106/754735874704539658/2020-09-13_17-09-53.mp4

This has also been an issue for me as my lasers are permanently in two separate directions and positions for world space and userspace, which means that I constantly need to keep repositioning my hand when switching between the two.

**Comment by shiftyscales** [comment]
https://youtu.be/RgZ4sTFZsf4

**Comment by H3BO3** [comment]
When using my multitool that has a rather large tip reference offset, I get the issue with having always-different userspace and global laser positions too. Is it possible userspace laser overrides could be based on a large change in the relative offset rather than just the offset itself?

**Comment by Frooxius** [comment]
It doesn't consider tools or anything like that at all, just the distance and angle offset. They are pretty low for a bunch of avatars/tools, I've increased the thresholds in 2020.9.14.511 which should help. Reopen if you're still having issues.
