### ISSUE TITLE
World search bar not working in 2020.9.13.591

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#1023]
Reported by Conduit (MIKE#4278)- on the current build, the search bar in the world browser is non-functional.

Conducting a base search in the 'custom' search works properly, so it appears as though the issue is related to passing the text from the search bar into the search query.

There is nothing in the log that pertains to this issue.

**Comment by shiftyscales** [comment]
This could perhaps be related to this in the latest update?
`- Changed linking mechanism for Facet presets for SearchBar and PagingControl - they are now setup themselves with general dynamic variable names, rather then being setup externally`

**Comment by Frooxius** [comment]
Hmm it's a bit strange. That change was made so they actually do work. I confirmed that they do work on my end, so I'm not sure what could be up.

Did you modify the worlds screen in some way or customize the search bar?

**Comment by Frooxius** [comment]
Can you check one more thing actually? If you change the locale to "cs" from English, does the search bar text change?

**Comment by shiftyscales** [comment]
"Zadejte vyhledávání..." Yes, the search bar text does change.

I've not ever touched the world's screen nor the search bar. I could try resetting my dash to see if that fixes it- but I figured I would wait on that until such point as I've done all I can to help you figure out what the issue might be.

**Comment by Frooxius** [comment]
Should be fixed in 2020.9.14.511! Reopen if the issue still persists.
