### ISSUE TITLE
Current Culture node outputs an empty string if the override locale is empty

### ISSUE THREAD

**Issue by mralext20** [Frooxius/NeosPublic#1025]
i specifically mean in the to string method of current culture.

**Comment by Frooxius** [comment]
Changed in 2020.9.14.511, thanks!

**Comment by mralext20** [comment]
wonderful! unfortunetly if the overide is set to emptystring, current culture outputs empty string aswell.

![2020-09-14 00 54 24](https://user-images.githubusercontent.com/4016295/93065152-d752ba00-f624-11ea-81a7-d3f0905654f9.jpg)

**Comment by Enkiko** [comment]
I work on Cross Universe everyday, and most of the players are Japanese. This bug means Japanese players will see English by default, and they cannot play the game if it is in English. I will instruct as many as possible to set their override locale.

**Comment by Frooxius** [comment]
Fixed in 2020.9.15.571, sorry for th inconveniece!
