### ISSUE TITLE
[Feature Request] Have local values effect PlayOneShot

### ISSUE THREAD

**Issue by Hayden-da-Serg** [Frooxius/NeosPublic#1028]
So I have a case where I want to have a sound's properties change depending on local variables, however in the current solution, PlayOneShot doesn't respect local fields, it instead uses the values for the user that sent the impulse

As seen in the screenshot below, the current setup only specializes the sound clip if the host user sends the impulse, when a user other than the host user sends the impulse then it's not spacialized.

![2020-09-14 05 24 50](https://user-images.githubusercontent.com/25524760/93080260-a1283100-f64a-11ea-8ad1-7c904823f2dd.png)

This is the case for any local value plugged into the PlayOneShot node, the sound will be using the values that the user that sends the impulse sees.

One such use case of this is having a lot of sound effects play with local settings at the desired time using PlayOneShot so that way sound effects don't count towards the audio source limit in the background.

**Comment by Frooxius** [comment]
I'm sorry, but this is fundamentally not possible. When you send an impulse as host, you perform action in the world, which generates the audio effect. That audio effect is part of shared model, with no links to how it was actually created - other users don't even know that the host did an impulse that created it. 

If you want a different sound effect for each user or different properties, you either have to set the "LocalOnly" to true and then make sure the pulse is fired for each user (with each settings evaluated locally providing given result) or you have to create a custom one shot sound template, which has driving logic on it that drives certain parameters differently depending on the user.
