### ISSUE TITLE
Multi Language Support

### ISSUE THREAD

**Issue by MR-Alex42** [Frooxius/NeosPublic#103]
I was wondering if the architecture of Neos is capable of handling multiple languages as this will be important for content creators to localize their content for their target audience. 
Not everybody is a native english speaker. 
Also texts in the same world could be different for different users depending on their preferred language.

**Comment by Frooxius** [comment]
Yeah you could do that, Neos' data model has special constructs to "diverge" parts the data model in a controlled manner, so you could change the text that way depending on the user locale or any other arbitrary rules.

Question is how and where from to load the localization data, how to handle fallbacks (missing translations) and so on. Then it's a matter of writing a few components that you could point at the text field.

Also how is the localization data modified and accessed - should it be dynamically loaded too? Or a prepackaged asset with all the keys and strings that you preload?

**Comment by MR-Alex42** [comment]
Wow, fast answer and good to see that the architecture could support it.

I imagine there is a master language in wich the content is acutally maintained by the content developer (most likely english). Then there are translation tables that have entries for all supported languages. 
The master language would also be the fallback language if the translation to a specific locale is not available. Would prefer a dynamically loading. So you would only need the translations for the users that are actually in the world. 

You could also outsource the translation work to the crowd by using a google docs spreadsheet for maintaining the translations. Another way would to use a translation service via API:
https://www.deepl.com/translator is the best of them all. Give it a try.

But internationalization goes beyond simple translations. How are objects resized if the required text is longer? Can the text we wrapped if too long? Is this a language that reads from right to left or vertical. This is a complex topic if you go into the details.

**Comment by Frooxius** [comment]
Finally added in 2020.9.13.591!
