### ISSUE TITLE
Deleting a slot in an inspector panel doesn't make it disappear from the inspector until another slot is selected

### ISSUE THREAD

**Issue by art0007i** [Frooxius/NeosPublic#1030]
Replication:
Create a slot with a child object, then delete the child object. The slot will still show in the inspector.
![bug](https://user-images.githubusercontent.com/19620451/93115689-80002880-f6bc-11ea-9512-69a1bad5070d.gif)

**Comment by Frooxius** [comment]
Fixed in 2020.9.15.571 thanks!
