### ISSUE TITLE
ICU MessageFormat.NET lacks pluraliser for Icelandic

### ISSUE THREAD

**Issue by Nammi-namm** [Frooxius/NeosPublic#1031]
I've checked over on https://github.com/Frooxius/messageformat.net/blob/master/src/Jeffijoe.MessageFormat/Formatting/Formatters/PluralFormatter.cs and there is no entry for [is]. 

I've noticed an entry for much smaller languages like [fo] Faroese which is grammatically very similar.

**Comment by Frooxius** [comment]
Added in 2020.9.15.571 thanks! I could add Faroese too if you want, but it's a separate addition, I'd recommend a separate issue for it.
