### ISSUE TITLE
Missing translation strings on "Lost password?" menu

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#1034]
"Account.Cancel" and "Lost Password" are both untranslated on the "Lost password?" menu in the login screen.
![image](https://user-images.githubusercontent.com/54213390/93282655-bf457c80-f783-11ea-99ee-166f18a86802.png)

**Comment by shiftyscales** [comment]
In English/with no language override set, `Acount.MicrosoftEmailWarning` is also visible on the account registration page.
![image](https://user-images.githubusercontent.com/54213390/93282892-3ed34b80-f784-11ea-94ad-f6f18c5bb5a3.png)

**Comment by Frooxius** [comment]
Should be good in 2020.9.16.596 thanks!
