### ISSUE TITLE
Request for solution to activate haptics continuously on the basis of local values

### ISSUE THREAD

**Issue by Zyzyl** [Frooxius/NeosPublic#1038]
I am trying to optimise / improve a system where users’ controller haptics are intended to be activated continuously while their controllers are within a volume of space. i.e. continuously activate haptics dependent on the result of a local calculation (getting hand position downstream of Local User Root and performing checks).

As far as I am aware, the only way to activate haptics in this manner is to use the Trigger Haptics On * LogiX nodes. Since these are impulse based, continuous activation requires a continuous impulse stream. I would normally consider Fire While True as appropriate for this purpose, but as far as I understand that can’t be reliably used with localised inputs in the way I intend. 

I notice there is currently no ‘Local Fire While True’ node. I think one would solve my problem, so I’d be keen to have that implemented if appropriate. An alternative solution I can think of would be to have a new node which activates haptics until a ‘stop’ signal is received – a Trigger Haptics Latch / Haptics Driver if you like. That could work in my current use case with something like a Local Fire On True to activate / deactivate haptics, though it would be useful to be able to modulate the strength of vibration during the period in which haptics were active.

I am, of course, open to other suggestions.

**Comment by H3BO3** [comment]
As it turns out Fire While True may accept Local User as an input, since it seems to have been used before successfully and it doesn't make sense for that node to have any impulse deduplication mechanism, since it's going all the time. It would be nice to hear @Frooxius 's input on this.

**Comment by ProbablePrime** [comment]
With the onset of Haptic Volumes I think we can close this. 

Creating a Haptic Volume will allow this scenario.

**Comment by Zyzyl** [comment]
Yep, a Haptic Volume seems to be a reasonable solution to what I had in mind when asking about this. Thanks for the reminder!
