### ISSUE TITLE
Set Child Index node doesn't set OrderOffset correctly

### ISSUE THREAD

**Issue by RileyGuy** [Frooxius/NeosPublic#1043]
Steps to reproduce: Get a child of an object and plug it into the Set Child Index node. Setting the child index to anything within the range of the number of children the object has yields seemingly random numbers. I entered in 2 and got 12 for example. 1 and it changed to 15.

**Comment by Frooxius** [comment]
By UpdateOrder, do you mean OrderOffset? UpdateOrder is on components and doesn't have to do anything with child indexes.

I'm not sure I fully understand the problem. Is the index of the child incorrect after setting it? OrderOffset is internal property used to handle it and the algorithm for calculating one will try to space them out to give itself room for frequent changes, so you won't necessarily see tidy changes.

**Comment by RileyGuy** [comment]
Ah, apologies. I meant orderoffset.

**Comment by Frooxius** [comment]
What about my other question though? I'm still not sure what exactly is the problem.

**Comment by RileyGuy** [comment]
I apologize, I skimmed a bit. Using that node yields an entirely incorrect OrderOffset. For instance, if I set the child index to say, 3, it'll either not change, or change to a completely random number.

**Comment by Frooxius** [comment]
Ah yeah. The SetChildIndex only cares if the child is at given index or not. It will not produce reliable OrderOffset values, but should always produce ones that put it at the index you asked it to.

Set OrderOffset is in the pipeline so should be added!

**Comment by Psychpsyo** [comment]
Since the Set Slot OrderOffset node is a thing now, shouldn't this issue be closed?

**Comment by TehTurk** [comment]
Yup! Thanks for Checking on this, I've been meaning to go through all the old issues and clean up stuff, thanks again @Psychpsyo
