### ISSUE TITLE
Settings menu cutting off the text at the bottom when leap motion is detected

### ISSUE THREAD

**Issue by Beaned2000** [Frooxius/NeosPublic#1046]
So there seems to be a slight issue with the visual of the settings menu when the leap motion part is in there,
others do not seem to have the bottom part cutting off since they don't own a leap motion
![image](https://user-images.githubusercontent.com/29598202/93621267-97e8ec80-f9db-11ea-8edf-243f2e6b19b7.png)

**Comment by shiftyscales** [comment]
I observed the same thing- but it is strictly a cosmetic issue. What you see there are the last settings in the menu. So nothing is inaccessible.

Between that, and the fact the settings menu is still in need of a UI rework/overhaul, I am going to close this issue. I hope this reasoning is acceptable, @Beaned2000. Thank you for the report, though.

**Comment by Enverex** [comment]
What happens if Froox adds even a single other option between now and the rework? Will the top/bottom option(s) become inaccessible entirely?

**Comment by TehTurk** [comment]
If it'd any consolidation @Beaned2000 you can go into the ui part that this is using and edit it to fit. It should persist over between Neos Sessions. And @Enverex most.likely, but we'd see a rework before then.
