### ISSUE TITLE
Request: Provide the ability to access the Numeric Value of a HTTP Response Code

### ISSUE THREAD

**Issue by ProbablePrime** [Frooxius/NeosPublic#1049]
I'm integrating a web server into some functionality within Neos. It uses extensive use of a lot of HTTP error codes to help with error logging and handling. 

Sometimes on the receiving end however, It can be useful to group error codes together using numeric operations.

Here are some examples:
Checking if a status code is > 199 & < 300 allows me to see if the response was accepted and handle the body
Checking if a status code is >299 & <400 lets me know I need to do some work to handle redirects
Checking if a status code is >399 & < 500 Lets me know that I've done something wrong
Checking if a status code is >499 & < 500 Lets me know that the server has done something wrong.

Or in other words:
1XX => Continue you're Cool
2XX => Cool here's what you asked for
3XX => do something please
4xx => You messed up, please try again
5xx => We messed up.

I can't do this however in game because the codes are returned as an Enum to logix, this is really really good for most handling but in cases where i want any code in the above list to be handled the same. E.g. All 400s cause message A to appear, All 5xx's cause message B to appear. I can't without complex AND and OR operations.

![2020-09-19 02 23 00](https://user-images.githubusercontent.com/8791132/93666695-19209d80-fa35-11ea-9fc6-f8a54fa68efc.jpg)

https://www.tutorialsteacher.com/csharp/csharp-enum implies I should be able to cast it. But that didn't work when i tried it in logix. I will double check with a manual cast node when i create one tommorrow and clean up here if it works.

Thank you!

**Comment by Frooxius** [comment]
Added EnumToInt node in 2020.9.23.1035 under Math/Enums which should do the trick!
