### ISSUE TITLE
French requiring Pluralizer

### ISSUE THREAD

**Issue by Archer-the-Rat** [Frooxius/NeosPublic#1055]
Following instructions on https://github.com/Frooxius/NeosLocale

> Verify that Neos' fork of ICU MessageFormat.NET has pluralizer for your language, by checking the "AddStandardPluralizers()" function in this file: > https://github.com/Frooxius/messageformat.net/blob/master/src/Jeffijoe.MessageFormat/Formatting/Formatters/PluralFormatter.cs

**Comment by Frooxius** [comment]
Added in 2020.9.21.475!
