### ISSUE TITLE
[Bug] + Logix node with too many indices causes crash

### ISSUE THREAD

**Issue by 3x1t-5tyl3** [Frooxius/NeosPublic#1056]
When adding too many children in component form to a + node (only tested with + node) causes crash upon grabbing the slot.

"11:24:14.763 ( 31 FPS)	Exception in OnTouch() event on Element: ID1C091003, Type: FrooxEngine.UIX.Canvas,"

**Comment by TehTurk** [comment]
Can you get video? What amount of number of input causes the issue to occur?

**Comment by Frooxius** [comment]
What exactly do you mean by grabbing the slot? Are you grabbing the visual representation of the node? Or reference to the slot?

Do you have the whole log? Generally snippets don't contain anything useful.

**Comment by 3x1t-5tyl3** [comment]
Grabbing the slot within the inspector (IIRC that's the reference?)
Index count at the time was at 419 (420 including 0)
Log is sent in DM's.

**Comment by shiftyscales** [comment]
Closing this issue as on discussion with @3x1t-5tyl3- he's not been able to replicate this issue since this GitHub issue was originally created/there are likely other factors responsible. This issue can be re-opened if more details are discovered on replication.
