### ISSUE TITLE
Going "back" from a Type selector of a dynamic variable component returns you to the wrong folder

### ISSUE THREAD

**Issue by ProbablePrime** [Frooxius/NeosPublic#1059]
1. Attach Component
1. Data
1. Dynamic
1. DynamicValueVariableDriver<T>
1. Press back
1. Observe you end up back at the root of the attach component menu

This is slightly frustrating, and would be better if it went back to the level of the menu that you were in before beginning to select a type.

**Comment by Frooxius** [comment]
Fixed in 2020.9.23.1035! Thanks for report!
