### ISSUE TITLE
Common Generic Node Presets should be colored the same as their type

### ISSUE THREAD

**Issue by mralext20** [Frooxius/NeosPublic#1062]
Similar to the variables/storage panel, the types in the preset should be colored the same as their type. (Yellow for color,green for int, blue with lines for float3)

**Comment by Frooxius** [comment]
I'm sorry, but I don't plan on implementing this. My goal right now is to eventually scrap the Node selector and rework it, unifying it with the planned new component browser. Adding new behaviors to it takes a lot of time and causes code duplication.
