### ISSUE TITLE
DynVariables: Allow us to Cast a Specific type within the Logix Panel

### ISSUE THREAD

**Issue by TehTurk** [Frooxius/NeosPublic#1065]
Issue: Simple Values are use-able for the Logix Panel by selecting their type, but due to the lack of overloads on DynVariable Nodes this is a bit tricky and requires manually generating the node from the Inspector. If they want to be more widely used, this being  added to it would make it alot easier.

**Comment by Frooxius** [comment]
I'm sorry, this won't get implemented for the current Node browser, it'll have to wait for the redesigned version. The current browser isn't really setup to allow any kind of editing UI like that, so adding this would consume a lot of development time for something that would be scrapped anyways. See this issue as well: https://github.com/Frooxius/NeosPublic/issues/1062

If it helps, I can add some more presets as common types in the meanwhile, but for others you'll have to use the inspector method.

**Comment by TehTurk** [comment]
Understood.thank you for your input.
