### ISSUE TITLE
Unable to tell the difference between Delete Dynamic Variable of different types

### ISSUE THREAD

**Issue by Hayden-da-Serg** [Frooxius/NeosPublic#1068]
As the title says, there's no way to tell the difference between different data types on the Delete Dynamic Variable node, as seen in the screenshot below.

![image](https://user-images.githubusercontent.com/25524760/93873644-49fc0f00-fc8f-11ea-9bc3-0dab6281c3b4.png)

The data type on the left is a bool and on the right is a color, however, there would be no way to tell this without knowing in advance or inspecting the node to see the type listed in the component.

**Comment by Frooxius** [comment]
Forgot to close, this, made the nodes display the type of the variable in their name.
