### ISSUE TITLE
Builder communication

### ISSUE THREAD

**Issue by Simulacron3** [Frooxius/NeosPublic#107]
The Web landing page touts Effortless collaboration as a major feature and the footer mentions 'forums', but I'm feeling quite isolated so far. What forums are active? How could I/we set up meetings in Neos for mutual help discussion/question sessions?

This is not an actual development issue, but I don't know of a better place to post this, which is kind of the point of it, so feel free to close it.

**Comment by sirkitree** [comment]
* discord is the best: https://discord.gg/w2F3ExE
* also the steam forums https://steamcommunity.com/app/740250/discussions/0/

**Comment by Simulacron3** [comment]
Thanks. Problem solved.
