### ISSUE TITLE
AlwaysOnFacetModule only reparents first child to AlwaysOnFacetRoot

### ISSUE THREAD

**Issue by mralext20** [Frooxius/NeosPublic#1070]
situation:

i would like to have both my Logix and Audio Output slots always on, so i have put them both under a slot with an always on facet Module component. uppon placing into the dash, only the first child gets reparented to the always on facet root. 

off dash: 
https://this-is-a.stale-me.me/i/qz0n.png

on dash: 
https://this-is-a.stale-me.me/i/2p53.png

**Comment by Frooxius** [comment]
Fixed in 2020.9.23.1035, thanks for report!
