### ISSUE TITLE
[Dynamics/Logix] Dynamic Variable Output

### ISSUE THREAD

**Issue by Earthmark** [Frooxius/NeosPublic#1072]
Can a logix node that drives a dynamic variable be added that works similarly to the Dynamic Variable Input, writes instead of reads? 

Currently I use dynamic variables to build apis, and having the ability to define the entire sub logix module in terms of logix instead of partially using components would make the modules easier to understand and debug.

This may relate to #1057 , as I'd think this would have the same behavior as the output node.

**Comment by Frooxius** [comment]
This is a bit tricky as it doesn't quite fit into how the system works. You can't drive dynamic variables themselves, only their backing storage components, which will propagate the changes to others linked to that variable.

There are a few possibilities:
- Use WriteDynamicVariable with impulse every frame to keep writing to the backing storage. This works if you need the written value synced across clients, e.g. when it's non-deterministic
- Add a new DriveDynamicVariable or something like that, which will serve as the backing storage - you will have to make sure that you don't have any other backing storage though as it might conflict or cause unnecessary network load and things like WriteDynamicVariable will no longer work with it correctly. This will effectively make the dynamic variable "local" and it'll be your responsibility to ensure correct setup.

**Comment by Earthmark** [comment]
Honestly I do that second behavior right now for API design, only I use drives against a dynamic variable value whatever-version-that-has-backing-storage.
Either way I think it has the same behavior in terms of network load and wiping out any other storage values? Both of them have the same side effects, just one has the ability to not cause network load and one does have network load.

It's kinda a stretch goal, but is it possible for a dynamic variable itself to be known internally to be a driven value? I get that on drive-end that gets really funky, but until that point. That'd resolve the extra sync problem at least?

Either way, the drive pattern seems quite useful so far even when used in component land, it's restrictive but it's great for making hot-swappable modules where logix links between values magically. Just gotta be sure to remove the old binding before adding the new bindings.

**Comment by Frooxius** [comment]
The driving system doesn't really care about dynamic variable system and vice versa, they're essentially separate systems that can be combined in variety of ways. There's not really reason for dynamic variable system to care about it either, its responsibility is only linking up the variables within the space and propagating changes between them.

If you have a single backing storage that's driven, then there's no network load at all, as with any driving - you're in control of that element. If you have multiple backing storages however, the non-driven ones will be synced, causing unnecessary load. It all depends on your setup.

**Comment by Earthmark** [comment]
I think I found a less error prone way to do this, I'll remove this for now!
