### ISSUE TITLE
DynamicReferenceVariableReset can't be defined for any type

### ISSUE THREAD

**Issue by Earthmark** [Frooxius/NeosPublic#1079]
It seems like no matter what I type, I can't get DynamicReferenceVariableReset to accept the string and allow me to create an instance.
So far I've tried:
* Slot
* User
* IElementContent`1[[System.Single]]
(I'm doing horrible things with dynamically swapping logix references, the DynamicReferenceVariableDriver creates just fine).

I stopped at this point as if it doesn't support Slot or User, I'm guessing it's not supporting anything.

![image](https://user-images.githubusercontent.com/1251609/94246180-3f7c8800-fed0-11ea-8abd-043eda7d5c23.png)

To replicate:
Try to create a DynamicReferenceVariableReset<Slot>

**Comment by Frooxius** [comment]
Fixed in 2020.9.27.1202, thanks!
