### ISSUE TITLE
Value gradient driver internally gets out of order, and chooses the wrong value.

### ISSUE THREAD

**Issue by Earthmark** [Frooxius/NeosPublic#1087]
What I expected:
Value gradient driver to smoothly blend between options of the value gradient.

Steps to replicate
Make a value gradient, populate it with two points:
position 0, value x
position .5 value y
Add a new point
position 1 value q
See that at .9, the value is y, not close to q.

To be honest, dotpeek was used. The internal list in ValueGradientDriver sorts on add, but not when modifying the position field. So, if there are fields above that have position already defined, the newly added point is added to near the front (or the true front) of the list, instead of wherever you really set the point to with position (which you can only set once the point is created and sorted as having a position of 0).

A current workaround is to add, then remove another point, as that re-sorts the internal list.

Fun note:
Also, if a user joins when the list is out of order for the host, it is populated in-order for the connected user. I went to investigate in the assembly after Alex joined my world and my value driver was working for him, but not for me.

**Comment by AMonsoonofBabies** [comment]
I also encountered this issue recently when messing with the component for the first time. Thanks for making this issue. I would prefer if the component was at least consistent with how it chooses the order of the points, as the current function is not friendly to use at all when adding and removing points.

**Comment by Frooxius** [comment]
Should be good in 2020.9.29.1115 thanks!
