### ISSUE TITLE
Adding eyes to single skinned mesh may cause a major performance issue

### ISSUE THREAD

**Issue by Reactantvr** [Frooxius/NeosPublic#1089]
My avatar currently has two skinned meshes instead of one because adding the eyes to that skinned mesh cuts performance by 50%. I test this by going to an empty world, stand 10 meters away from my avatar, then spawn as many as I can before I drop from 45 to 30 fps. I can spawn 40 with the eyes being on a separate skinned mesh and only 20 with them being on the same one. The eyes are toon outlines with a single 17 kb texture. They are 1000 tris.

I've not been able to reproduce this on other avatars, so I don't know if this is a widespread issue or unique to mine.

**Comment by Frooxius** [comment]
This is quite strange. Can you share the models with me so I could test them with profiler and measure what might be going on?

Do the eyes have any significant differences from the rest of the mesh? E.g. being affected by a lot of blendshapes?

**Comment by Reactantvr** [comment]
The eyes are just two half spheres. They have only one blendshape on them for pupil dilation.

**Comment by Reactantvr** [comment]
Frooxius told me this was related to a blend shape based optimization that will come in the future.

The issue has to do with pupil dilation for eye-tracking. The best solution for now for those that use eye-tracking is to have the eyes on a separate skinned mesh if you use pupil dilation. A planned update will fix this so you don't have to do this.
