### ISSUE TITLE
[Bug] Undo grabbing an equipped avatar breaks the avatar

### ISSUE THREAD

**Issue by Hayden-da-Serg** [Frooxius/NeosPublic#1091]

**Comment by Hayden-da-Serg** [comment]
(fat-fingered the send button)
When performing an undo grab on an avatar which is currently equipped, the avatar will be parented under the world root but still technically be equipped, causing all sorts of strange interactions.

Steps to reproduce:
-Spawn an avatar
-Grab the avatar
-Eqiup the avatar
-Undo Grabbed Objects
-After undoing avatar will be reparented to root

**Comment by Frooxius** [comment]
Should be fixed in 2020.9.29.1115 thanks!
