### ISSUE TITLE
[Bug] VRIK Avatar doesn't clear "_locomotionController" on dequip

### ISSUE THREAD

**Issue by Hayden-da-Serg** [Frooxius/NeosPublic#1092]
As the title says, the _locomotionController field on VRIK avatar doesn't get cleared when the avatar is dequipped, resulting in cases where the avatar's feet used the last user's on ground state and don't hover in the air.

Steps to reproduce:
-Spawn any IK avatar
-Equip avatar
-Dequip avatar
-Inspect the avatar root and notice that the _locomotionController field on the VRIK Avatar component still has a reference on a user root

**Comment by Frooxius** [comment]
Fixed in 2020.9.29.1115, good catch!
