### ISSUE TITLE
Materials mis-assigned after separating mesh parts unaffected by blendshapes

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#1100]
Certain models with multiple materials will have the wrong materials applied after separating the mesh by parts affected by blendshapes.

A sample model that exhibits this issue is the Da'vali in Neos Essentials > Avatars > Anthro > Avalis.

**Comment by Frooxius** [comment]
Fixed on 2020.10.1.1403, thanks!
