### ISSUE TITLE
LODGroup doesn't intialize on duplication

### ISSUE THREAD

**Issue by TehTurk** [Frooxius/NeosPublic#1101]
Result is that LODGroup component needs to be turned on and off to register and have the LODGroup Component handle LODs.

**Comment by Enverex** [comment]
That's actually already covered here - https://github.com/Frooxius/NeosPublic/issues/458 - along with the "LODs just don't work randomly" problem. They seem to have general initialisation issues.

**Comment by TehTurk** [comment]
Oh dang, thanks for the headsup @Enverex . I'm working with LODGroups in my MMC and found I had to make lgx script just intialize them :|. I did find tho however turning the component off and on in the script did help. As they persist across saves.
