### ISSUE TITLE
Request: Mechanism to add Primitives(Collider+Mesh) to a slot, preferably in a component context.

### ISSUE THREAD

**Issue by TehTurk** [Frooxius/NeosPublic#1102]
(Had alot of debug visuals in my MMC, I found it troublesome to set up Logix Nodes when I could just have a debug preset. As setting up the components were faster. The Create New Menu does this :0) EDIT:
- Discovered this during my MMC endeavours
- Ways to visualize a slot are troublesome, normally this is allieviated by adding a primitive but this in of itself is troublesome as it's extra steps to do this manually or by generating with Create New
- Somethings Preferred would be through a component preset

**Comment by Frooxius** [comment]
I'm not sure I understand what do you mean, could you elaborate a bit on this, maybe provide some examples?

**Comment by TehTurk** [comment]
Sorry I thought the FacetPresets in RadiantUI were 1 to 1 enough. I'd like to be able to generate a 3D Prim in a similar way when a component is added onto a slot.

**Comment by Frooxius** [comment]
I'm sorry, I'm still not quite sure I understand what do you mean? Could you give me some examples?

**Comment by TehTurk** [comment]
Apologies! So you know how when you make a UIX FacetPreset by adding the PresetComponent, it auto generates it yes? I would like this similarly but for Box/Sphere/Cone/Torus procedural meshes, or at least the ones that are generated from the Create New -> 3D Model with the Dev Tip. It would speed up workflow and also allow for easier debugging and setup in the inspector.

Currently we can do this, but it requires the custom events that the Create New Menu does currently, I was wondering if we could get this but basically as an addition of a component.

**Comment by Frooxius** [comment]
What would be the usecase for this? For the primitive procedural meshes you don't need it, because they're already templates for themselves. Facets need it because they're a lot more complex setups that are upgradable over time.

**Comment by TehTurk** [comment]
Which I get, but it's not just the mesh the generation would would include the collider as well similarly to how Create New -> 3D Model would work. It's usecase is to increase inspector work flow and also enable debugging as it's faster to make a child object and add a component, then Open Context -> Create New,  3D Model -> Select Object -> Open Inspector after selection, drag object over.

**Comment by TehTurk** [comment]
Updated original post as this was made in haste previously to not forget the issue.

**Comment by TehTurk** [comment]
Closing this as it's become irrelevant to my need and a tool was made with this able to be in mind.
