### ISSUE TITLE
DynamicReferenceVariableInput and Write/Read/Create References are missing

### ISSUE THREAD

**Issue by TehTurk** [Frooxius/NeosPublic#1103]
Title says it all :0

**Comment by Frooxius** [comment]
They're not missing, the LogiX nodes work with any dynamic variable type, they don't distinguish between Value, Reference and other core types.

**Comment by TehTurk** [comment]
Ah but we have DynamicReferenceVariables in Component form but can't use them in Logix Form? Like they have no form of overloading or easy way of instantiating them Logix wise.

**Comment by Frooxius** [comment]
I'm not sure what do you mean by using them in LogiX form? All LogiX nodes work with reference types. You can instantiate any reference type through the inspector as you would the other components. Common types like Slot or User are presets in the LogiX node selector.

**Comment by TehTurk** [comment]
Sry scatterbrain due to MMC, let me get back to you on this
