### ISSUE TITLE
Neos Version Indicator in World Browser

### ISSUE THREAD

**Issue by GunnarO0** [Frooxius/NeosPublic#1104]
Similarly to how the contacts list shows user icons in pink if the user is in a different version of Neos, it would also be convenient to indicate if an active session in the world browser is hosted in a different version. Maybe a label or even a pink border similar to the contacts list.

Scenario: I had just launched Neos with a very recent update, the patch notes had not even been posted yet. I start to browse active sessions in the world menu and find no easy way to know if a session was on the same/compatible version with mine other than by clicking each one by one or shuffling through the contacts list to see if anyone was already in a session of the latest version.

**Comment by GunnarO0** [comment]
> The World Browser should not show any incompatible sessions in the first place. Were any actual incompatible sessions shown at all? If so what visibility were they?
> 
> Do you have the "Show Incompatible Sessions" enabled in Settings?
Yes there were incompatible sessions in the browser where when I clicked I would be shown the error for incompatible version. I do not recall what visibility they were set to at the time this happened. As for the setting, it should be off but I will verify this as soon as I can.

**Comment by GunnarO0** [comment]
>As for the setting, it should be off but I will verify this as soon as I can.

The setting is off.

**Comment by shiftyscales** [comment]
Hmm... It does appear that some sessions somehow leak through the incompatibility check. I am on 2020.9.27.1202 right now (the android-preview branch) to test, and I see two sessions- both of which claim to be incompatible versions.

`Space Out` hosted by `Cuddlewyvern`:
lnl-nat:///S-9509f0f4-19a9-42b7-b78f-408240f7e5c1
neos-steam://76561198080921963/3/S-9509f0f4-19a9-42b7-b78f-408240f7e5c1
`romejeme's Build` hosted by `romejeme`:
lnl-nat:///S-a36dd302-352e-47e2-9443-da63c1ba3149
neos-steam://76561198027780165/2/S-a36dd302-352e-47e2-9443-da63c1ba3149

**Comment by Frooxius** [comment]
What is their access level? Are they public worlds or friends only?

**Comment by shiftyscales** [comment]
"Contacts" for Cuddlewyvern's world. But they also have another instance of Spaced Out open that is set to "Anyone".

Open/Anyone session of Spaced Out:
lnl-nat:///S-47067071-3069-4e3b-869f-eee8a533231b
neos-steam://76561198080921963/2/S-47067071-3069-4e3b-869f-eee8a533231b
![image](https://user-images.githubusercontent.com/54213390/94736596-58969600-0321-11eb-8164-c54fc3ef741e.png)


Contacts session of Spaced Out which appears on the Android world browser:
lnl-nat:///S-9509f0f4-19a9-42b7-b78f-408240f7e5c1
neos-steam://76561198080921963/3/S-9509f0f4-19a9-42b7-b78f-408240f7e5c1
![image](https://user-images.githubusercontent.com/54213390/94736497-2c7b1500-0321-11eb-80bc-1f4151b959c7.png)

The sessions were also apparently opened within forty seconds of each other based on the time node.

**Comment by Frooxius** [comment]
Should be fixed in 2020.10.1.1403 and incompatible sessions should no longer appear, thanks!
