### ISSUE TITLE
Write or create dynamic slot runs into null reference

### ISSUE THREAD

**Issue by Coffee-Maker** [Frooxius/NeosPublic#1107]
![2020-10-02 08 06 39](https://user-images.githubusercontent.com/25093209/94897004-b09add00-0486-11eb-8e4f-eb8e5fbf71a5.jpg)
Using this setup if the variable that is being written to does not exist then it will throw a null reference in the logs and fail to execute it's task. If the slot with the dynamic variable space that is being written to is opened in the inspector it locks up the host user.

If this same action is done but the variable already exists then it will run as intended. This behaviour was consistent with multiple sessions tested in.

**Comment by Frooxius** [comment]
Can you post the log of the exception it throws?

**Comment by Coffee-Maker** [comment]
[ISOR-PC_-_2020.9.30.328_-_2020-10-01_21_30_52.log](https://github.com/Frooxius/NeosPublic/files/5320455/ISOR-PC_-_2020.9.30.328_-_2020-10-01_21_30_52.log)

**Comment by Frooxius** [comment]
Thanks! Fixed in 2020.10.4.411
