### ISSUE TITLE
Decrease sensitivity for UpdateShape on procedural meshes

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#1111]
Presently, when certain procedural meshes, e.g. StripeWireMesh are moved, they recalculate their mesh collider unnecessarily on every frame, flooding the background threads, and drastically lowering performance by taking up numerous unnecessary CPU cycles.

An optimization Frooxius proposed would be to decrease the sensitivity at which they are updated, allowing them to be moved without regenerating the colliders continuously.

Issue discovered with thanks to a report by Davwyn#6433.

**Comment by Frooxius** [comment]
It's not possible to change the sensitivity for UpdateShape itself since it has no concept, but I made changes to LogiX wire updating which will preventing updating the mesh itself when it's similar enough, preventing the UpdateShape tasks in the first place. Thanks!
