### ISSUE TITLE
Duplication Tip Needs to Support Undoing

### ISSUE THREAD

**Issue by TehTurk** [Frooxius/NeosPublic#1114]
Currently using the dupe tip requires you to delete the object manually instead of having to undo the duplication.

**Comment by TehTurk** [comment]
Also could the dupe functionality be switched to secondary? Or at least an option to allow for it. Currently double tapping to reorient kinda breaks the tips flow somewhat. As it duplicates an object each time you click.

**Comment by Frooxius** [comment]
Added in 2020.10.4.411, thanks!
