### ISSUE TITLE
[Bug] Inspector not showing matrix input fields properly

### ISSUE THREAD

**Issue by 3x1t-5tyl3** [Frooxius/NeosPublic#1116]
![20201004153043_1](https://user-images.githubusercontent.com/61988002/95016951-a4657a00-0656-11eb-9898-e0f20b764c23.jpg)
3x3, 2x2, 4x4.
It doesn't care wherether it's a dynvar or normal valuefield. Same result.

Suggestion: Showing them in proper rows. (ergo 3x3 should be 3 wide and 3 tall etc.)

**Comment by Frooxius** [comment]
Added support for matrix types in 2020.10.5.476!
