### ISSUE TITLE
Increase default Laser activation/deactivation threshold to ~0.1

### ISSUE THREAD

**Issue by H3BO3** [Frooxius/NeosPublic#1122]
At least a few times now I've had to direct people to add a trigger deadzone to the configuration file because the worldspace lasers more or less lock up completely after many operations if the trigger value is unable to return to 0, present in cases where there is mild trigger drift. I think changing the default threshold to 0.1 or even 0.05 may clear up a lot of these issues.

**Comment by Frooxius** [comment]
It already is 0.1. If user has severely worn out trigger and it's going beyond that range at rest, they need to adjust their deadzone unfortunately.

**Comment by H3BO3** [comment]
Interesting, I didn't know that. Thanks!
