### ISSUE TITLE
Addition to the Play one shot nodes

### ISSUE THREAD

**Issue by candypheonixIO** [Frooxius/NeosPublic#1126]
I'm using play one shot with a facet currently, but I don't like that the audio still assumes the sound effects audio space _i.e: volume still controllable by the sound effects slider in settings, instead of UI,_

Would it be possible to add an Enum`1 option to the node to select between the different audio channels, or maybe have the play one shots know when they are in UserSpace and assume the UI audio channel?

**Comment by Frooxius** [comment]
Added in 2020.10.12.499, thanks!
