### ISSUE TITLE
New interface cards are spawned on copy, instead of using existing cards

### ISSUE THREAD

**Issue by Earthmark** [Frooxius/NeosPublic#1128]
What I did:
Had a logix sequence unpacked, including an interface card which had been manually parented as a peer to the other logix. This sequence was under an inactive slot and was to act as a template.
Copies of that template were made, and the template was moved to a new location, so the logix example could be regenerated.

What happened:
On copy, the copy of the interface card was created and stayed where expected, however instead of referencing that card, a new interface card was made under root, and was spawned at a 0,0,0 to the object the interface was representing.

What I expected:
The references to the interface card maintained connections to the copied card, pretty much the whole example copied with consistent internal references and moved as one chunk to the new home of the logix example.

The current behavior makes using interface card in examples very difficult, and as it also suffers from the duplicate spawned interfaces bug it is also quite performance impacting. As the new interfaces are under root, it's very difficult to reset the example cleanly, and means that the created examples can't show that aspect of logix (and in my opinion using interface cards is kinda one of the big points, otherwise you can't do a many behaviors that make logix powerful.)

**Comment by Frooxius** [comment]
This has been a long standing issue resulting in the Interface duplication in many cases. It's quite tricky to fix with the current design of the system, so my plan is to just wait until I redesign the whole system to be much cleaner and more powerful (e.g. so you can easily reference dynamic fields too and such).

**Comment by Earthmark** [comment]
Sweet, thanks for the response, I'll close this as it's probably a duplicate/deprecated then!
