### ISSUE TITLE
Possible Bug: Grabbables lose Scale Coherence in this setup, wondered if due to setup 

### ISSUE THREAD

**Issue by TehTurk** [Frooxius/NeosPublic#1131]
![2020-09-24 20 42 22](https://user-images.githubusercontent.com/26357446/95369615-a7a27500-08a5-11eb-9fda-bd997b443992.jpg)

So I was playing/testing this and found if I had grabbed it it would grow, but if Gourry who was next to me grabbed it, it would shrink.

**Comment by Frooxius** [comment]
- What do you mean by "scale coherence" exactly?
- How are you grabbing it, is it using Grabbable or Slider?
- Are you grabbing it with laser or hand?
- What does the hierarchy of the grabbed object look like? 
- What exactly does the setup do? Are you just releasing it immediately on grab?

**Comment by TehTurk** [comment]
- Ah it's original scale is lost in the midst of starting this initially
- Grabbable
- Hand, Laser seems to affect it too
- It's just a cube, I think on grab it's underneath my Grabber
- No, I'm grabbing it but the logix sequence causes it to ungrab right away

**Comment by Frooxius** [comment]
Generally you shouldn't be releasing grabbed object right when it's being grabbed. I've changed how are the grabbed events ran, so they run a bit after after the grab fully finishes, this should fix the issue in 2020.10.12.499
