### ISSUE TITLE
DataPresetValue with a Material type causes crashes

### ISSUE THREAD

**Issue by BlazeVR** [Frooxius/NeosPublic#1132]
Creating a DataPresetValue on an object with any material type I've tested (Xiexe, Unlit, PBS_Metallic) causes Neos to crash. 

![image](https://user-images.githubusercontent.com/65873874/95373305-2070f380-08dd-11eb-9c4a-306df7d9a11d.png)

**Comment by Frooxius** [comment]
Fixed in 2020.10.12.499, thanks!
