### ISSUE TITLE
Skinned mesh renderer bounds has issues when null bones are present.

### ISSUE THREAD

**Issue by Earthmark** [Frooxius/NeosPublic#1136]
Nammi is having his body skinned mesh renderer vanish at times part of his body is outside the render range.

What was done:
Nammi existed in the server

What happened:
When specific parts of Nammi's model was not in the view space, the skinned mesh renderer would no longer be visible.
Changing bounds compute mode from static to medium bones does not resolve the issue.

The behavior was inconsistent between session joins, and the bounds were often different between different times you joined the server and different users experienced different bounds on Nammi (for some users the point where he stops rendering is at his shoulders going outside the draw bounds, some the point is his hips being outside draw bounds, some don't stop rendering him at all).

Setting it to the slow version does work successfully.

**Cause and workaround!**
Nammi had two null bones in the skinned mesh renderer, removing the two bone slots fixed the issue for both bounds calculation styles.
It seems having null bones cause different bounds calculation styles to fail in unpredictable ways.

Nammi had null bones because the model was modified and part of the armature was deleted during the modification.

**Comment by shiftyscales** [comment]
From the sounds of it, this might fall under the purview of 'expected behavior'. As is known from having something stretched/positioned outside of the bounding boxes.

Does the issue still occur if it is set to slow/realtime calculation, @Earthmark?

**Comment by Earthmark** [comment]
The issue was the mesh was well inside the bounds, the bounds calculation seemed to not complete while there were null bones in the skinned mesh renderer list.

Slow realtime fixed the issue, however really that shouldn't be needed as no part of the mesh got too far from the armature. In the end that removing two null bone entries fixed the issue, that makes me think it's an odd check in the code or some such.

**Comment by Frooxius** [comment]
Fixed in 2020.10.12.499, thanks!
