### ISSUE TITLE
Fog volume accumulates excessively at bounding box edges with VerticalGradient ColorMode

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#1137]
Discovered by Turk, a fog volume that is set to use a vertical gradient has an issue in which the accumulated color will appear really brightly at the bounding box edges. This occurs regardless of whether the volume is adjusted for the worldspace setting.

This issue does not appear when rendering under the `Constant` color mode.

The effect as viewed in-headset is a very thin shimmering line in the shape of the cube/bounding box.
![2020-10-11 18 50 11](https://user-images.githubusercontent.com/54213390/95697594-19efbe00-0bf4-11eb-87ae-6fd6924130fc.png)

**Comment by Frooxius** [comment]
Are there any special conditions? I can't replicate this on my end. Can you send me a replicaiton case world?

**Comment by shiftyscales** [comment]
neosrec:///U-Shifty/R-c3df301c-5799-41c8-aa95-166693a28720

There aren't any specific/special conditions I'm aware of, @Frooxius- but if you set the SaturationMode to Unrestricted the effect becomes a lot more apparent.

It's entirely down to the VerticalGradient mode being set.

E.g. to replicate it you can:
- Create new > Objects > Fog Volume > Additive
- Set ColorMode to VerticalGradient
- Select and deselect the volume to remove its gizmos
- Place your head into the volume and note that along each of the edges is an increased density of fog
- The world posted above replicates the issue using the settings Turk had been using- but the issue can be seen with other combinations of settings too

Note the visible edges of the default additive volume set to VerticalGradient in the following pictures:

![2020-10-11 22 40 02](https://user-images.githubusercontent.com/54213390/95709406-72828380-0c13-11eb-99eb-9c123cffc285.png)
![2020-10-11 22 40 53](https://user-images.githubusercontent.com/54213390/95709414-76aea100-0c13-11eb-9e7e-bc16dbde9c55.png)

**Comment by Frooxius** [comment]
Fixed in 2020.10.12.499, thanks!
