### ISSUE TITLE
VR mode noclip should trigger colliders the same way screen mode noclip does.

### ISSUE THREAD

**Issue by RileyGuy** [Frooxius/NeosPublic#1143]
This would have the added benefit of colliderusertracker respecting the presence of players who are in noclip. This is the behavior in screen mode and I can't think of a reason why it shouldn't be for VR noclip as well. As it stands this breaks the "culling" use-case for this component if you're in noclip.

**Comment by ProbablePrime** [comment]
Unfortunately, its called noclip for a reason, I need noclip to avoid my colliders.

If you wish to fly please use physical flying. 

Culling also doesn't make sense with noclip as in noclip you are "editing" the map and should be seeing all areas.

In my MMC entry I hooked up the colliderusertracker to also check if the user is on the ground, if they aren't on the ground it doesn't function.

**Comment by RileyGuy** [comment]
This doesn't make sense then for screen mode noclip to respect colliders while VR noclip doesn't. I wish to make a sandbox map with culling and I can't do this if people can't use noclip without culling breaking.

**Comment by ProbablePrime** [comment]
It does, because screen mode isn't supported officially. Its just for testing. So its behaviour in regards to colliders isn't defined. Its just a quirk of its state of screen mode right now.

**Comment by RileyGuy** [comment]
Then there should be a separate noclip mode specifically that respects colliders, being able to fly through walls and have culling work is essential

**Comment by ProbablePrime** [comment]
In these cases, I would create custom culling solutions for your maps which do work in noclip then. Let's wait for Froox to comment :)

**Comment by RileyGuy** [comment]
That kind of defeats the purpose of the efficient collider detection system then if I have to use culling that is inefficient instead. :/

**Comment by ProbablePrime** [comment]
I've heard Froox talk about more general purpose culling solutions which may arise later. Those may suit your needs. Custom culling isn't inefficient though. It can be made to work basically like the component.

I need NoClip to not clip, and that needs to include culling, So we're at an impasse

**Comment by Frooxius** [comment]
This won't get implemented sorry. @ProbablePrime is correct. No-Clip mode is designed to avoid interactions with the environment for editing, for physical flying use the Fly, which will trigger collider appropriately.

Screen mode doesn't use the "No-Clip" mode, in fact it doesn't support locomotion modules at all. It's just a hacked together mode I use for debugging and you should not base anything on it.
