### ISSUE TITLE
[Bug/LogiX] Write note neither succeding or failing on any driven value

### ISSUE THREAD

**Issue by 3x1t-5tyl3** [Frooxius/NeosPublic#1145]
![image](https://user-images.githubusercontent.com/61988002/95824010-e36a8e00-0d2e-11eb-8081-ac120cc7aabc.png)
If a value is driven the write not seems to not behave at all.
It's neither succeding or failing. See screenshot.

**Comment by mralext20** [comment]
if you wish to both drive a target value and write to it ocasionally, consider using the drive logix node, you'll get a impulse out of the 'on hooked' target when something tries to write the value, along with the value being hooked.

**Comment by Frooxius** [comment]
Fixed in 2020.10.14.462, should fire OnFailed now! Thanks for report!
