### ISSUE TITLE
Has Value on DyanmicVariable Driver and Dynamic Reference driver for logic based on if exists 

### ISSUE THREAD

**Issue by mralext20** [Frooxius/NeosPublic#1147]
I am currently designing some logic such that if a texture or similar is available on the World namespace my avatar will pick that texture of value up and apply it to my avatar, otherwise get my normal texture.

**Comment by Frooxius** [comment]
There are few approaches for this. One of them would be to have explicit default value on the Drivers, which would be used to drive the value if it doesn't currently exist. That would help with this particular setup.

Another is to add a component that simply indicates the presence of the value or not. I don't think adding it to the Driver specifically would be a good choice, as there might be scenarios where you want the information about its existence without requiring the driver.

**Comment by mralext20** [comment]
well ofcource, why didn't i think that. sounds like a better solution

**Comment by Frooxius** [comment]
In 2020.10.14.462 I've added both. There's new DynamicVariableStatus which lets you know if variable exists and the drivers will now let you override the default value when variable doesn't exist.
