### ISSUE TITLE
PBS_ColorMaskSpecular material doesn't utilize the specular map

### ISSUE THREAD

**Issue by AMonsoonofBabies** [Frooxius/NeosPublic#1152]
Upon my first use of this material recently, I noticed PBS_ColorMaskSpecular didn't appear to acknowledge the existence of any specular map placed in the appropriate texture field. By comparison at least, PBS_RimSpecular showed an apparent reaction to the same specular map that wasn't present on the color mask material. As per my observations, I believe this is not intended behavior. An example of this comparison I made can be recreated through the following steps:

- In a new world, use the Dev tip to spawn out one PBS_ColorMaskSpecular material, and one PBS_RimSpecular material
- Create one empty object and attach to it two different procedural texture components (I would suggest one Simplex and one Grid). One will be the specular map, and the other will be a color mask / albedo texture. You can also optionally just grab any textures you have on hand that work with expected results
- Place your chosen textures into both materials, placing the specular map into the same slots on both materials, and placing the other texture into the PBS_RimSpecular's albedo texture and the PBS_ColorMaskSpecular's color mask
- At this point, you should observe that the specular effects present on the PBS_RimSpecular material are not present on the PBS_ColorMaskSpecular material. Additionally, changing the SpecularColor field on the PBS_ColorMaskSpecular does change how it looks while the texture is in the material, while the same action does nothing for PBS_RimSpecular

It would be appreciated if this could be addressed soon, though it is not too large of an issue for me currently.

**Comment by Frooxius** [comment]
Fixed in 2020.10.17.533, it was a missed line in the shader not activating the right variant! Thanks!
