### ISSUE TITLE
[Enahncement/Bug?] Destroyblock and Duplicateblock not respecting disabling the component

### ISSUE THREAD

**Issue by 3x1t-5tyl3** [Frooxius/NeosPublic#1153]
Destroy and Duplicateblock when the compononent is disabled still work. Therefore blocking destroy and duplicate.
When disabling the slot they are attached to *or* deleting the parent of it, it works. Thus giving questionable behaviour.

**Comment by Frooxius** [comment]
In 2020.10.17.533 the Enabled field will now be respected, thanks!
