### ISSUE TITLE
[Enhancement/Component] Add ReferenceMultiDriver

### ISSUE THREAD

**Issue by 3x1t-5tyl3** [Frooxius/NeosPublic#1154]
Same as value multidriver. Just for references. Simple really.

**Comment by TehTurk** [comment]
I don't know if you'd necessary want this as we have DynVars now and alternatively does the same thing 🤔

**Comment by 3x1t-5tyl3** [comment]
I mean it's not entirely wrong. It would create parity between them tho.

It makes sense we have ref and value copy. But not that we have a ValueMultiDriver, but not a RefMultiDriver.

I could also see plenty of moments where that would be incredibly handy. Especially for more complex reference driving where you'd wand the same ref, but instead of like a component for each copy, you'd only use one and multidrive it. You could then also RefCopy and interact with it in logix. Which would make this even more extensive.

**Comment by TehTurk** [comment]
No I agree, it's just more so I know some component design has been a bit specific or all over sometimes as there are multiple ways to do things at times. So often stuff has been added as an as needed basis but I can be wrong I'm just speaking from my experiences

**Comment by Frooxius** [comment]
Added in 2020.10.17.533!
