### ISSUE TITLE
DataPresetReference<T> [Component Request]

### ISSUE THREAD

**Issue by Toxic-Cookie** [Frooxius/NeosPublic#1155]
We have DataPresetValue<T> which is very useful for setting data types. However, having a version for setting references would be helpful as well.

Example use case: Instead of setting the index for an AssetMultiplexer<Texture2D> with an DataPresetValue<int>, you could instead directly set the reference of the Texture2D to what you were multiplexing. Which would be more flexible and dynamic overall.

**Comment by Frooxius** [comment]
Added in 2020.10.17.533, thanks!
