### ISSUE TITLE
 Undo Batch Nodes do not carry over between Update Delays

### ISSUE THREAD

**Issue by TehTurk** [Frooxius/NeosPublic#1163]
- Take an operation within a For Loop and have an update delay
- No Matter what the Batch will not create
- Can share object that does this as it just ends up creating seperate individual undo operations

**Comment by Frooxius** [comment]
They're not supposed to, Undo actions need to be "atomic", meaning that everything has to happen at once within a frame. A lot of different things can happen within the update delay. I'd recommend structuring the system in a way that you can create all the undo steps atomically.

**Comment by TehTurk** [comment]
Hmm okay, the issue is that so much happens in a frame that it kinda just "stops" so I'll see what I can do, because if it's overloaded the logix nodes break meaning the system needs to be respawned.
