### ISSUE TITLE
Controller tutorials massively outdated with Legacy actions

### ISSUE THREAD

**Issue by Hayden-da-Serg** [Frooxius/NeosPublic#1168]
When talking with a new user, I noticed that their controller tutorials still show options such as "Double Grip to release" and "Open world switcher" both of which are legacy options are disabled by default, leading to users trying to preform these actions then getting confused when they do nothing.

I suggest the controller tutorials be reworded or reworked to compensate for the legacy options being disabled.

**Comment by shiftyscales** [comment]
What build is this on, @Hayden-da-Serg? They have been as of 2020.10.14.462 they should have been already, @Hayden-da-Serg.
`- Changed contextual tutorials for grabbed items, so they no longer refer to the legacy "Double Grip" and confusing new users (requested by @Nexulan | Community Manager)`
https://canary.discord.com/channels/402159838827905024/469131434628612116/765863143259504640

**Comment by Hayden-da-Serg** [comment]
https://cdn.discordapp.com/attachments/767112569017335810/767142125002555414/unknown.png
Not according to this

**Comment by shiftyscales** [comment]
Thanks. Reported it to @Frooxius.

**Comment by Hayden-da-Serg** [comment]
Was fixed as of 2020.10.25.915
