### ISSUE TITLE
Microphone setup wizard for new users

### ISSUE THREAD

**Issue by RileyGuy** [Frooxius/NeosPublic#1169]
This is a common issue when trying to get people started in neos, wherein the default mic for new users is almost always wrong. This leads to either prompting instruction on how to navigate to settings or community-made tools to try and get their mic working.

**Comment by shiftyscales** [comment]
>It does try to use the default one. Problem is the one that system reports as default isn't always the one that the user needs to use.
>Particularly with Oculus, which has its own mechanism for forcing the default audio input device that's not actually the system default, but it only works sometimes.
>The new UI is going to have better volume indicator and switch. I'm thinking of adding a wizard for first launch that ensures they have a working audio device.
https://canary.discord.com/channels/402159838827905024/439422161657135106/699299340879003679

This is a known issue, but as Frooxius has noted, it is already using the system's default microphone/we plan to have a setup/first-use wizard for new users that has them setup everything correctly prior to getting started.

**Comment by Frooxius** [comment]
I made some improvements for the default detection in the next build. For the wizard setup we already have issue here: https://github.com/Frooxius/NeosPublic/issues/683
