### ISSUE TITLE
Dynamic FloatQ Variable default is invalid quat [0,0,0,0]

### ISSUE THREAD

**Issue by Earthmark** [Frooxius/NeosPublic#1171]
A picture is worth a thousand words
![2020-10-18 18 27 46](https://user-images.githubusercontent.com/1251609/96392147-043c4480-1170-11eb-9886-fa2925937d89.jpg)

If possible, can the default be valid?

**Comment by Earthmark** [comment]
This should be resolved as of 2020.10.25.915, I'll verify once I get back and close if needed.

**Comment by H3BO3** [comment]
@Earthmark Any updates?

**Comment by Earthmark** [comment]
I'm on vacation until Friday, so no updates until Saturday!

**Comment by mralext20** [comment]
![image](https://user-images.githubusercontent.com/4016295/97498106-6fc8a380-1920-11eb-8461-a9348394ee0b.png)
