### ISSUE TITLE
Attempting to create a dynamic variable on any slot under a dynamic variable space other than the slot the component is on fails.

### ISSUE THREAD

**Issue by RileyGuy** [Frooxius/NeosPublic#1173]
Steps to reproduce:

1: Create a dynamic variable space on a slot
2: Attempt to use one of the 'Create dynamic variable' nodes with logix on any slot under the dynamic variable space hierarchy.

Is this intended behavior? I would think that creating a dynamic variable anywhere under a dynamic variable space hierarchy would succeed, but it does not.

**Comment by Zyzyl** [comment]
I think I recally trying something similar and found that the DynVar components were being spawned on the slot where the DynamicVariableSpace component was present - is it possible that's what was happening for you?

**Comment by Frooxius** [comment]
- What are your inputs to the node?
- How are you determining that it's failing?

**Comment by Coffee-Maker** [comment]
The issue was resolved, we found that he had an invalid symbol in his Variable Space name.
