### ISSUE TITLE
Extract and Compose bits from float nodes

### ISSUE THREAD

**Issue by Coffee-Maker** [Frooxius/NeosPublic#1186]
Nodes that can extract and compose a float into its bits.

**Comment by ukilop** [comment]
and double :V

**Comment by Frooxius** [comment]
I've added nodes to reinterpret floating points datatypes as integers and vice versa, which lets you use the Extract/Compose bits nodes for this purpose now in 2020.10.26.1103, hopefully this helps!

- Added nodes to reinterpret floating point values as integers and vice versa (requested by @Coffee | Programmer and @Ukilop)
-- This can be used to extract/compose them as bits
-- They can be found in Math/Binary
-- HalfAsUShort, FloatAsUInt, DoubleAsULong, UShortAsHalf, UIntAsFloat and ULongAsDouble
