### ISSUE TITLE
Diorama Editing

### ISSUE THREAD

**Issue by MR-Alex42** [Frooxius/NeosPublic#119]
The World of Comenius Demo explored what I call 'diorama editing' meaning you edit a small world and by doing this you actually edit a mirrored world at a bigger scale. I wonder when this feature is planned to be implemented.

**Comment by Frooxius** [comment]
Hmm, I'm not too sure about this one. I didn't like it too much when I did it in World of Comenius. I think being able to scale yourself up and down to edit at different scales works better, as it's more direct, so I don't have any plans to add this.

I plan to have a way to quickly toggle between multiple instances of your avatar (or presets) within the world, so you can go back and forth between different scales quickly, which might help the iteration process.

**Comment by MR-Alex42** [comment]
I see that easy and quick switching between different avatar presets with different world scales could achieve the same effect in regards to ergonomics.

**Comment by Frooxius** [comment]
Yeah, plus it will work with everything, not just building tools made specifically to work in this mode. Should I close this issue then?

**Comment by shiftyscales** [comment]
Closing this issue. As has been observed, users can easily scale themselves to turn any world into a diorama to edit.
