### ISSUE TITLE
ToTimeString yields string with extra "0."

### ISSUE THREAD

**Issue by CuriousNicholi** [Frooxius/NeosPublic#1191]
Using Stopwatch > ToTimeString node sequence yields a string with an extra "0." between seconds and milliseconds.
I checked in with a few others in Discord and the consensus is this might be a bug?

![StopwatchExtraZero](https://user-images.githubusercontent.com/43762250/97049815-ec830880-1541-11eb-92ac-b1e158eaa25d.jpg)

**Comment by Frooxius** [comment]
Fixed in 2020.10.25.915, thanks!
