### ISSUE TITLE
Audio clip with an attached volume meter causes choppy output

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#1199]
Reported by Zane, if a sound clip has an attached VolumeMeter component that is referencing it, playback will be very choppy. Sample file sent via the messaging system.

Clearing the audio clip reference from the source of the VolumeMeter/removing the VolumeMeter will instantly resolve the playback issues.

**Comment by Frooxius** [comment]
Fixed in 2020.10.25.1005! Thanks!
