### ISSUE TITLE
Item Inventory

### ISSUE THREAD

**Issue by Frooxius** [Frooxius/NeosPublic#12]
- A special storage for arbitrary Neos objects - tools, world orbs, materials etc.
- Can be brought up anywhere to extract or store items
- Synchronized in the cloud for logged in users
- Categories/folders for better organization
- Preload it with basic tools so users don't have to hunt them around Neos

- What should it look like?
- Seen by other users? Private?
- Extract duplicate items by default? (meaning explicit delete button) Use tool shelves for temporary transfers

**Comment by sirkitree** [comment]
Are you visualizing this as a world, like how you're basically taken to a new world when you create a new world and are presented with a menu to select a template and other options? Or something that spawns in-world?

Personally I find the transition to another world a bit uncomfortable just to present the user with UI elements that could be attached to the controller, or spawned in front of them as sort of micro-space. Changing the entire world around the user is disorienting, especially for first time users who are not used to that paradigm.

**Comment by Frooxius** [comment]
It'll be an object you bring up in the world you are in. 

The idea behind the "world UI's" is that they'll be more suitable for more complex actions, but this isn't fully realized yet. For example when starting a new world, I want you to have a bunch of visual templates and you pick the one you want, configure a few more things and you could invite your friends by grabbing their avatars and dropping them into a bin. 

In the same sense I want to have a special "Warehouse" world, which is sort of like "huge inventory" of all your stuff, with UI's to search and navigate spatially (like browsing a warehouse with alleys sorted by name, date etc.)

**Comment by Frooxius** [comment]
On suggestion from aadhux: Sharing inventory with your friends (at least a category).
- Could anyone add-remove things from this shared inventory?
- Who technically owns it? Who manages who has access?
- Do friends of friends have access? 
- Base it around groups instead?

**Comment by Frooxius** [comment]
Basic inventory has been implemented and is now in nightly-patreon. It allows adding items, folders and deleting them (and of course spawning).

There's still al lot of things to do (like giving others read/write access, UI/visual polish), but they need other features first (like friends list). Going to create new issues for these later and closing this one.
