### ISSUE TITLE
"Out of memory" exception when reading audio clip

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#1200]
In Rukio's 'small vibes' world, users have been having an issue on the latest build where they will freeze for up to a minute at a time. If they wait it out, Neos can recover.

The issue can be seen from line 1793 in this log:
[SHIFTYWINDOWS - 2020.10.25.915 - 2020-10-25 09_38_52.log](https://github.com/Frooxius/NeosPublic/files/5435452/SHIFTYWINDOWS.-.2020.10.25.915.-.2020-10-25.09_38_52.log)

**Comment by shiftyscales** [comment]
It's replicable. Playing this audio clip causes the issue:
neosdb:///20ec5dbc681206c6032b9eaba2e0c26380d405e580784fdcd31e837e91e68895

**Comment by Frooxius** [comment]
Should be fixed in 2020.10.26.1103. I haven't been able to replicate it, since it seems to depend on a few conditions, but from the log the reason seemed pretty clear, the AudioBufferPool recycling queue bloated like crazy. Let me know if there are still issues!
