### ISSUE TITLE
Periodic hitching

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#1202]
In the latest build, something is causing periodic hitching. The hitches can be as soon as every ten seconds apart to a few minutes.

I've not been able to identify a specific action/cause responsible yet.

During the hitch, all audio/video will momentarily freeze/repeat the last sample for around a second.

Will update this issue if I learn any direct causes.

This issue was also observed by Rukio and others.

**Comment by Frooxius** [comment]
This definitely needs more information, I haven't encountered any hitching myself, so I can't do much without anything solid to go on.

**Comment by Frooxius** [comment]
I believe this was likely less severe case of this: https://github.com/Frooxius/NeosPublic/issues/1200

If certain conditions/clips were causing the queue to bloat in memory, that would've triggered the GC excessively, which could cause heavy stutters.

Let me know if the hitches are gone now.

**Comment by Enverex** [comment]
I'm no-longer experiencing this issue so that seems to have fixed it for me at least (and sounds aren't hitching either even with a lot playing).
