### ISSUE TITLE
Request: Update Mediawiki to latest edition

### ISSUE THREAD

**Issue by ProbablePrime** [Frooxius/NeosPublic#1204]
Hey Everyone,

In updating the wiki some users and I noticed some features in later version of MediaWiki which may prove useful when editing wiki. 

As such I'm requesting some changes to the wiki:
- Update the wiki to latest (1.35) we're on 1.33 (https://wiki.neos.com/Special:Version)
- With 1.34+ can we Add/ensure this https://www.mediawiki.org/wiki/Extension:Loops works

The use cases here are that Epsilion, is currently making a huge effort on the wiki which involves automatically creating a lot of component and logix pages. These use templates which create tables for each field within a component.

For example look at Grabbable: https://wiki.neos.com/Grabbable_(Component)

Thanks

**Comment by shiftyscales** [comment]
Hey @ProbablePrime- an update to this issue with some additional information:

Our old webhosting service did not support PHP past version 7.3.1 (Mediawiki 1.3.5 requiring PHP 7.3.19 at minimum).
Our new host will have PHP 7.4.6 available, and we are in the progress of migrating to them.
Karel will be attempting the upgrade this Wednesday if all goes well.

**Comment by ProbablePrime** [comment]
Excellent, thank you. Please let me know if I can be of any help.

**Comment by shiftyscales** [comment]
The wiki has been successfully updated to 1.3.5. Thanks for the suggestion!

New functionality and skins are available including:
https://wiki.neos.com/index.php?title=Main_Page&useskin=darkcosmos
https://wiki.neos.com/index.php?title=Main_Page&useskin=darkvector

**Comment by shadowpanther** [comment]
User pulldown menu doesn't work on DarkCosmos for some reason.

**Comment by ProbablePrime** [comment]
I'd suggest a new issue for that Shadowpanther.
