### ISSUE TITLE
Audio clip metadata component

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#1205]
A component similar to PhotoMetadata for recorded audio clips.

**Comment by mralext20** [comment]
opinion: rework photoMetadata to be generic, and ise the same component on both

**Comment by Frooxius** [comment]
This could be added, although I'm not sure how much functionality I'd build on top of this right now, so it would be mostly for data keeping for now.

@MR-Alex42 That would just cause trouble, they're effectively representing different information. Some of it is shared, so I can see if I can make basis for that, but each datatype has unique properties and functions not shared with the other. E.g. what would be Field of View of audio clip? Or audio channel configuration of an image?

**Comment by shiftyscales** [comment]
Yeah, data/record keeping was my primary interest in the request of this component. It would be nice to have a record of when a given asset was created, storing/making use of metadata for audio also has the potential added benefit (down the line) to help in sorting/organization of the data.

The short-term interest on my part was in having a way of tracking which user recorded a particular audio clip, when the audio clip was recorded, and perhaps even where it was recorded. Similar generic information that can be found on the PhotoMetadata. Thanks, @Frooxius!

**Comment by Frooxius** [comment]
Added in 2020.10.27.1173!
