### ISSUE TITLE
[Tweak] IcoSphereMesh should have a limit on Subdivision

### ISSUE THREAD

**Issue by Aerizeon** [Frooxius/NeosPublic#1206]
The IcoSphereMesh currently does not appear to have a limit on the `SubDivisions` input.
This can lead to unanticipated results when edited by new users, as the number of triangles increases at a rate of 20×4<sup>n</sup>, where n is the number of subdivisions.
For example:
Subdivision 1: 80 Tris
Subdivision 2: 320 Tris
[...]
Subdivision 8: 1,310,720 Tris
Subdivision 9: 5,242,880 Tris
Subdivision 10: 20,971,520 Tris

Through testing with Ukilop and ShadowPanther, we think that 8 is probably the largest useful value, with 9 being extremely intensive to generate and render.

**Comment by Frooxius** [comment]
Yeah 8 sounds good, I've added the clamp for now in 2020.10.26.1103. Thanks!
