### ISSUE TITLE
Negative quality breaks microphone tip

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#1208]
Discovered by Ryuvi and SmolCookie, setting a negative quality will cause the microphone tip to break (will stay red/'recording'). Adding a clamp to the accepted range should fix it.

**Comment by shiftyscales** [comment]
This issue appears to only happen when using OGG vorbis encoding. WAV and FLAC both work as intended with a negative quality (presumably they don't make use of it?)
[SHIFTYWINDOWS - 2020.10.25.1265 - 2020-10-25 20_19_59.log](https://github.com/Frooxius/NeosPublic/files/5436646/SHIFTYWINDOWS.-.2020.10.25.1265.-.2020-10-25.20_19_59.log)

**Comment by Frooxius** [comment]
Yes WAV and FLAC don't use quality setting since they're both lossless. I'll add a validation for Vorbis settings to prevent this, thanks!

**Comment by Frooxius** [comment]
Should be fixed in 2020.10.26.1103!
