### ISSUE TITLE
My microphone no longer works after last update

### ISSUE THREAD

**Issue by art0007i** [Frooxius/NeosPublic#1209]
[THORENS - 2020.10.25.1265 - 2020-10-26 18_22_35.log](https://github.com/Frooxius/NeosPublic/files/5440357/THORENS.-.2020.10.25.1265.-.2020-10-26.18_22_35.log)
I use the Kinect Microphone and that one has 4 channels and throws tons and tons of exceptions in the logs. I do not have a different microphone as of now so this is quite a big problem for me.

**Comment by Frooxius** [comment]
Should be fixed in 2020.10.26.1103 now, sorry for the inconvenience! The fix is untested, please let me know if you're still having issues.
