### ISSUE TITLE
UIX Canvas does not always order content in the same order as slots appear

### ISSUE THREAD

**Issue by mralext20** [Frooxius/NeosPublic#1211]
**The Problem**

if different people click the button, the entries may get out of order from the slot order. 

example ![image](https://user-images.githubusercontent.com/4016295/97267603-43f1d480-17df-11eb-8a69-8fc2fc9d406a.png) 

logix: 
![image](https://user-images.githubusercontent.com/4016295/97268332-98498400-17e0-11eb-871b-a598253eb6ad.png)

example object is avalibe in the following share folder: `neosrec:///U-alex-from-alaska/R-1fcaa355-15c9-46f1-9ac1-abe5601d7eb2` you will need multiple players in the session to reproduce this.

**Comment by Frooxius** [comment]
- How are you assigning the order? Is the "OrderOffset" value same for each element or is it unique?
- Do different users see different order in the inspector as well? Or only on the canvas?
- Does the order update at all when you make ordering changes, or does it get stuck completely?

**Comment by mralext20** [comment]
orderOffset is 0 for all elements. 

different uses see the same order as photo'd in both the inspector and on the canvas, i.e. a missmatch, where the canvas appears wrong.

set child index reshuffles the slots in the inspector to match the appearance in the canvas.

**Comment by Frooxius** [comment]
If order offset is 0, then the order of elements is not guaranteed. You should set the indexes or order offset explicitly if you want to ensure proper order. I'll see if I can tighten the system a bit and ensure explicit ordering, but it might not be feasible without a global performance impact.

**Comment by mralext20** [comment]
maybe a component that automatically orders children by when they get parented, like the aligners?

**Comment by TehTurk** [comment]
Would this already be feasible with SlotChildrenEvents? OnImpulse -> SetIndex

**Comment by mralext20** [comment]
closing this as duplicate, with preference toward #1297 being implemented.
