### ISSUE TITLE
Int Input node does not validate on value drop

### ISSUE THREAD

**Issue by mralext20** [Frooxius/NeosPublic#1212]
repro steps:
create a float input node
create a int input node

put the number 1.23 in the float
use your laser or shift + right click from the float input to the int input

observe as the value in an int is now a float, bringing us close to the heat death of the universe 
![image](https://cdn.discordapp.com/attachments/436018196244594688/770548972778815518/unknown.png)

**Comment by Frooxius** [comment]
Heat death of the universe averted in 2020.10.27.1173! Thanks!
