### ISSUE TITLE
World orb/session orb text should look at local user

### ISSUE THREAD

**Issue by H3BO3** [Frooxius/NeosPublic#1218]
Now that the world orb/session orb menus have been reworked to the context menu system, there is no need for the text on the orb to look at the nearest user, and all orb text should face the local user instead. This was brought up in the discord some weeks ago but no change was made.

**Comment by Frooxius** [comment]
Changed in 2020.10.28.1150 thanks! I recommend making GitHub issue right away, things from discussions get easily lost/forgotten.
