### ISSUE TITLE
Avatar importing issues, hands and blink not bound as expected

### ISSUE THREAD

**Issue by Earthmark** [Frooxius/NeosPublic#1222]
Alber released a new yote version however the hands and blink blendshapes are not getting auto configured correctly. 

Looking at the avatar the names may fall into edge cases, however I think it may be good to allow the import systems to work successfully on the layout, as others may use a similar layout. Alber's previous yote was similarly laid out (and had importing problems), although I think the eyes worked in that one as it used vrc syntax there.

**Here is the hands:**
![image](https://user-images.githubusercontent.com/1251609/97498144-a959d880-1939-11eb-8f26-4e1560e42158.png)
![image](https://user-images.githubusercontent.com/1251609/97498177-b7a7f480-1939-11eb-9766-f0e1f8d81784.png)
Previously the fix I did was reparent the thumb to be under hand instead of the index metacarpal, and renamed the palm bones after their corresponding metacarpal. Unsure which part of the fix was actually needed though.

**Here is the eyes:**
![image](https://user-images.githubusercontent.com/1251609/97498303-f0e06480-1939-11eb-9059-3fb1bcb28a02.png)
Although the blendshapes seem to contain the magic words I would think the binder is looking for, it doesn't seem to find left and right currently. Although renaming them to the vrc forms got them to work successfully. (Ex: vrc.blink_left)

So this is what the current avatar layout is, I believe it should be possible for neos to correctly figure out the bones in question and handle these cases. If not fixes exist though, although people who don't know those fixes may have an interesting time.

Special thanks to Ren Korrum and Alber for the pictures, as I'm still on my phone on vacation, yay for technology!

**Comment by Earthmark** [comment]
This may be the default naming style of metarig, so indeed this will happen to other people!

**Comment by Frooxius** [comment]
I have a fix for the eyes coming in the next build (it didn't check for "Closed",  just "Close"), but I'm not sure what is up with the hands/fingers. Is it possible to send me a sample avatar to test with?

**Comment by Frooxius** [comment]
Eyes should be fixed in 2020.10.29.1313, for the hand I think I'd need a sample to test with.

**Comment by Earthmark** [comment]
I'll get one to you once I get back from vacation, or Ren/Soap/Hayden/Alber can provide a copy (that is acceptable via the license)

**Comment by Frooxius** [comment]
Thanks for the sample model! I'm looking at the rig, but there's actually a problem with the rig itself - thumb finger is a child of the metacarpal bone of the index finger, which is incorrect. All fingers should stem from the hand/wrist bone (hand.L in this case) as they're each independent. 

I'm making some adjustments which should help, but as this is a rigging mistake, it might still misbehave to some extent.

**Comment by Frooxius** [comment]
I've improved the finger rig detection to be more tolerant of invalid rigs in 2020.11.1.1319, so it should setup mostly-correctly now (Index finger will be missing metacarpal though, while all other fingers will have one), but I really recommend fixing the rig instead.

**Comment by shiftyscales** [comment]
According to -Lime# 0001 in Discord, there are some Blender plugins such as Rigify which this incorrect rigging can be traced back to, @Frooxius. Doesn't change anything on our end- but it's interesting to note.

**Comment by Frooxius** [comment]
Yeah it might be worth reporting this issue to them, as that's likely going to produce invalid rigs for more avatars. Neos should be able to handle it gracefully now at least though.
