### ISSUE TITLE
Setting a mesh renderer bounds to Proxy itself crashes Neos

### ISSUE THREAD

**Issue by Hayden-da-Serg** [Frooxius/NeosPublic#1224]
I was working on setting up an avatar and I was going through and setting bounds sources to proxy from the main body mesh, but I accidentally set one of the bounds sources to itself, then Neos hard locked and crashed.

To recreate, get a skinned mesh renderer, set the bounding type to Proxy, then set the proxy source to itself.

Here's the log file if needed.
[LAPTOP-9P0L3G42 - 2020.10.28.1149 - 2020-10-28 19_01_58.log](https://github.com/Frooxius/NeosPublic/files/5456446/LAPTOP-9P0L3G42.-.2020.10.28.1149.-.2020-10-28.19_01_58.log)

**Comment by H3BO3** [comment]
Enverex noted in the discord a couple weeks ago that setting the bounds proxy in any capacity crashed neos. I'm unsure how replicable that was, but it may be relevant.

**Comment by Frooxius** [comment]
Fixed in 2020.10.29.1313, thanks for report!
