### ISSUE TITLE
Request: Emotion-Recognition for Existing Viseme System

### ISSUE THREAD

**Issue by dfgHiatus** [Frooxius/NeosPublic#1227]
I've been doing research and came across a real-time emotion recognition app from one's voice. Given the current viseme system can track things like laughter, we could potentially implement something similar for happiness, anger, et cetera. This would make for an interesting addition to the existing viseme system.

**Comment by Frooxius** [comment]
I'm sorry, but this is unfortunately not possible. The existing viseme system is done using OVRLipSync library, which is a 3rd party library that we don't have control over.
