### ISSUE TITLE
Request: Could WorldThumbnailItem be updated to actually contain the Session ID?

### ISSUE THREAD

**Issue by ProbablePrime** [Frooxius/NeosPublic#1235]
I use a custom created WorldThumbnailItem for my "Worlds You're In Facet"(https://youtu.be/Ugw7ffoUUj8)

I removed the click action of the thumbnail, because I don't want the large dialog that details opening/creating a session to appear. So I wanted to overtake this with custom LogIX.

Ideally I want the press action to be just to focus the world. I thought about using the LogiX node "Focus World" to do this. But for that I need a Session URL. 

The WorldItemThumbnail component has a field called "WorldOrSessionId" this always appears to be a WorldId. Even in the cases shown in the above linked video where I have a session open. 

I tried plugging in the property anyway to double check and it doesn't work because its not the correct format.

I don't seem to be able to get an active SessionId for any of the WorldThumbnailItem instances which is a little frustrating. 

To me it feels like the world browser is operating in a strange way where half of the contents of a single item in the world browser relates to the sessions I'm in and half the contents relates to ANY sessions that might exist for the world. This makes custom world browsing and navigating facets difficult.

I apologize for the overly specific focus of this issue, other solutions may include things like changes to the Focus World node so that it allows the ID format this component outputs. It would take the ID from the component and find any existing sessions and focus that. This is difficult if there are many open though.

**Comment by Frooxius** [comment]
You should be able to place Session ID in there as well, it just needs to be prefixed with "S-". The way the world browser works though is that it will use the more general ID if available, which is used to combine sessions of the same world into a single item. Most sessions will announce the World ID of the world they're hosting. If a world ID is assigned, the WorldItem will implicitly find and show active sessions of it.

What I could add however is a setting to the WorldListManager to prevent it from using the announced World ID of the session and prevent combination of the items. I believe that would resolve your issue.

**Comment by ProbablePrime** [comment]
I'll take a look and self close this if its fixed, thank you :)

**Comment by ProbablePrime** [comment]
This is good, it works how I need it to work.

There are other issues with my facet but they aren't related to this bug so i'll close it.

Thank you Froox, this will open up a path to amazing world browsing facets.
