### ISSUE TITLE
[Tweak] Squeeze grip to grab, open hand to release style gripping (Index Controllers)

### ISSUE THREAD

**Issue by InsaneGrox** [Frooxius/NeosPublic#1239]
Currently while using the valve index controllers you have constantly be squeezing the controller to hold objects, which over long periods of time can cause discomfort in the hands, my idea of a solution would be changing the behavior to have it so that you slightly squeeze the grip to pick up an object (very light to keep it comfortable and intuitive without triggering accidentally), and it will stay in your hand until you stop touching the grip, allowing your hand to relax while holding the object.

**Comment by shiftyscales** [comment]
This is something you already have the capabilities of tweaking. In the SteamVR controller bindings, you can adjust the click deactivation threshold to require you to determine how much your grip has to loosen before the grip is released.
![image](https://user-images.githubusercontent.com/54213390/97722767-3f9c1480-1a88-11eb-939e-b211e4d574e1.png)

**Comment by H3BO3** [comment]
If there are no other responses I will be closing this issue. While native neos rebinding may be a thing in the future, steam bindings can currently be used for input customization. Feel free to reopen if necessary.
