### ISSUE TITLE
Combine redundant TRS matrix nodes 

### ISSUE THREAD

**Issue by Electronus** [Frooxius/NeosPublic#1241]
![2020-10-30 17 23 00](https://user-images.githubusercontent.com/64871170/97764931-dba03d00-1ad5-11eb-9598-28b71adf3662.jpg)
The "Compose TRS Matrix" and "Transform Matrix" nodes appear to do the same ting and be able to be used in the same ways.

**Comment by Frooxius** [comment]
Should be fixed in 2020.11.1.1319
