### ISSUE TITLE
Add an option to specify the slot on which DynVars are created by LogiX nodes

### ISSUE THREAD

**Issue by Zyzyl** [Frooxius/NeosPublic#1243]
This topic was recently brought up by QueenHidi / @StarfishHidari on Discord, see here and later messages: https://discordapp.com/channels/402159838827905024/477711742001086505/769207704094113823

Frooxius responded saying that this might be implemented, but that the LogiX nodes were not intended to be used where specific slot placement was desired. See https://discordapp.com/channels/402159838827905024/477711742001086505/769218410872832031

I now have a use case where this functionality would be very helpful. I am creating a UI to install and/or modify an environmental system for worlds wherein several dynamic variables are periodically changed by a LogiX pack. I am directly binding DynVars to the World space since I want this to 'just work' in any world. On spawning the UI I want to first check whether the system is installed by checking for the presence of associated DynVars and, if they are not all found, present the option to install the system. I would also like the variables to be created in an easily human-readable slot hierarchy and for the system to be cleanly uninstallable too.

Currently my options for installing a system involving DynVars are:
1. Use the LogiX nodes for creating DynVars
2. Pre-setup DynVar components on a template slot and copy that over

Option 1 is not currently viable because I am using the World space and therefore variables created by LogiX will be placed on the Root slot. This fails the 'easily human-readable' condition because it is best not to inspect the root too often and it typically has a large number of components. It also fails the 'cleanly uninstallable' requirement because currently we cannot target specific DynVars for deletion.

Option 2 is also not viable because DynVars on the template slot would need to be fully setup and bound to the World space. That makes it difficult to properly check whether the system is installed or not (using the DynVarStatus component) since the relevant variables necessarily already exist when the UI is spawned.

I hope that makes the value of the requested feature clear. Other possibilities which would resolve some, but not all, of the issues would be:
- Ability to create/delete dynamic variable spaces (and all directly bound DynVars) via LogiX
- Ability to target specifically named DynVars for deletion

**Comment by TehTurk** [comment]
I think I brought this up originally when DynVars were first introduced but I don't know if it ever got to the point of being an issue. I do think we should have the ability to target "A Slot" for where the DynVar gets installed, because if you ever open a main space, oh man does that thing lag from copious amount of Fields/Variables.

**Comment by Enverex** [comment]
A project I'm working on at the moment relies on creating a lot of dynamic variables on the fly. The problem is, this results in literally dozens of dynamic variable slots being created on the world root. Even worse is that they're components (and thus will always be persistent) so anyone saving their world after this has happened end up with dozens of these dynvars stuck on their root without even knowing they're there.

**Comment by Frooxius** [comment]
It might help to add an option to have the created dynamic variables be non-persistent. That way it doesn't matter where you make them, they'll get cleaned up on save.

**Comment by shiftyscales** [comment]
2020.11.15.758:
```
- Added CreateDirectlyOnTarget and CreateNonPersistent inputs to CreateDynamicVariable<T> and WriteOrCrateDynamicVariable<T> nodes (based on requests by @Zyzyl, @Robyn (QueenHidi), @Turk and @Enverex)
-- CreateDirectlyOnTarget will create the component directly on the target slot, rather than the space root (I recommend only using this if really necessary and if you have full control over the target slot)
-- CreateNonPersistent will create the component as non-persistent, meaning it won't save with the world. If one already exists the persistence won't be altered
```
