### ISSUE TITLE
Pasting a text string prefaced by a forward slash creates a slot with the pasted string as the name

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#1245]
Replication steps:
- Have a string in your clipboard that is prefaced by a forward slash, e.g. `/test`
- Paste it into a text input field, e.g. the messaging window on the dashboard
- Neos will create a slot on the root using the content of the string that follows the text, e.g. `test`

Issue reported by Bitman# 0669 and Alex from Alaska# 2020.

**Comment by Frooxius** [comment]
Fixed in 2020.11.1.1319, thanks!
