### ISSUE TITLE
File Browser unusable on second spawn (nightly)

### ISSUE THREAD

**Issue by sirkitree** [Frooxius/NeosPublic#125]
## Problem/Motivation
In the nightly-patreon build, when opening the file browser for the first time, it is quite usable. But the second time it appears without materials and my hands are not animated, making it unusable. The world space is frozen, but I can still manage to close the world again using the menu in the user space, even though I can't see my controllers moving.

## Steps to reproduce
1. Open Neos
1. Open the File Browser from the main Neos menu 
    1. Note at this point everything is functional.
1. Close the File Browser using the Close option on the Neos menu
1. Re-open the File Browser from the main Neos menu 
    1. Observe that the world space is not fully loaded, controller models are unresponsive, and it is difficult to interact with the main Neos menu

Here's a short video for further illustration: http://take.ms/0Sux2p

**Comment by Frooxius** [comment]
Fixed and pushed to nightly, thanks for the report!
