### ISSUE TITLE
Rich text in world names is very abusable.

### ISSUE THREAD

**Issue by RileyGuy** [Frooxius/NeosPublic#1252]
Adding rich text size into world names makes them parse in the world orb browser at a very... different size to what it parses in UIX.

https://i.imgur.com/z1EJifN.png

**Comment by AMonsoonofBabies** [comment]
Oh wow. I always thought having the ability to format world names was odd, but this is just ridiculous. I think world titles should be exempt from formatting, and this is a good example of why.

**Comment by ProbablePrime** [comment]
I've seen world names get more and more unreadable recently due to bright unreadable colors, Long names and symbols in their names. 

Some rules in formatting them are probably in order but I don't agree that we should kill creativity completely.

**Comment by sauermon** [comment]
I feel like some creative freedom should be allowed for world names, as it can help a world stand out. However, for the size tag in specific, I feel it should have an upper bound of sort.

**Comment by H3BO3** [comment]
Neos has complete control over text rendering now so I think sizes could be clamped, at the least. @ProbablePrime Are there any other restrictions that you think would be good but wouldn't kill creativity?

**Comment by Frooxius** [comment]
This can be fixed by simply using the Bounds with AutoScaling on it, I'll add that in the next build. That will force the text to certain maximum size.

There's no reason to go overboard and forbid everything over something that's a simple fix.

**Comment by ProbablePrime** [comment]
Ahh good solution :)

**Comment by Frooxius** [comment]
Do you know the specific size tag that was used in this example? The orbs actually already do have bounds for the text, so it seems like there's some edge case when it doesn't rescale the text to the bounds.

**Comment by Frooxius** [comment]
Fixed in 2020.11.2.1161, thanks for report!
