### ISSUE TITLE
Option to join or create session without switching to it

### ISSUE THREAD

**Issue by uyjulian** [Frooxius/NeosPublic#1254]
There should be an option so that when you click on a world orb or on the world menu, you can join or create the session without switching worlds.  

This would allow you to do stuff (e.g. finish a conversation) in a loaded session while the joined session is loading.

**Comment by shiftyscales** [comment]
This is a planned UI option, but it's not a priority right now. This issue can be considered as a duplicate of #65. But thanks for the suggestion, @uyjulian!
