### ISSUE TITLE
UIX Text element Null string content to empty string content

### ISSUE THREAD

**Issue by Earthmark** [Frooxius/NeosPublic#1255]
As far as I'm aware it's not possible for a user typing into a text field to return the field to null text. So the help text is only applicable when an item is first spawned and has never been typed in.

So instead of it checking for explicitly null strings, can it also check for empty strings? That way if a user deletes all text in the ui element they then see the help text again.

**Comment by Frooxius** [comment]
That would break a lot of stuff unfortunately, as there would be no way to actually "display" empty text/string. Better solution would be to expose functionality for text fields to set the string back to null if it's empty and not actively edited.

**Comment by Earthmark** [comment]
That would work for me! Right now it's difficult to kick it back to null, so some automatic way to do that would also resolve the issue.

**Comment by Earthmark** [comment]
Ping to #1258

**Comment by Frooxius** [comment]
Added this option in 2020.11.6.439!

- Added FinishHandling to TextEditor, which determines on how is the target string updated after editing finishes (requested by @Earthmark):
-- Leave As Is (leaves it unchanged)
-- Null on Empty (sets target to null if string is empty after editing ends)
-- Null on Whitespace (sets target to null if string is just whitespaces or empty after editing ends)
