### ISSUE TITLE
Vive hand tracking SDK 0.9.4

### ISSUE THREAD

**Issue by Danyy59** [Frooxius/NeosPublic#1261]
v0.9.4 out recent patch, 2020/10/29

v0.9.4 includes following changes since v0.9.3 (important ones are highlighted):

    Update deep learning models for all platform. Improved accuracy while maintaining same latency.
    Add option to limit max raw detection fps to save computing resources. This has negative impact on latency. Only use it when VR application fps slows down due to hand tracking.

I want to let you know.

**Comment by Frooxius** [comment]
Upgraded in 2020.11.5.88, thanks!
