### ISSUE TITLE
Recategorize GeometryLineBrushTip to Tools > ToolTips instead of uncategorized.

### ISSUE THREAD

**Issue by Hayden-da-Serg** [Frooxius/NeosPublic#1263]
Pretty sure the title says it all, but GeometryLineBrushTip is under uncategorized, and I'd think it makes more sense for it to be under tools > tooltips

**Comment by Frooxius** [comment]
I've put them into Tools -> Brushes in 2020.11.5.88, since there's a bunch of them.
