### ISSUE TITLE
Set/Drive User Root Global Scale Node

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#1267]
When attempting to scale a user using gadgets/Logix, a few common problems come up.
- The resizing user is offset from their user root, causing them to slide/shift position from their centered root
- There is no means to directly set/drive the user root slot's scale, e.g. via a Tween, meaning you need to instead drive a value field
- To smoothly scale a user, you need to do it each frame/use continual impulses, e.g. via fire while true.

Having a node that can set or drive a user's scale similar to how a user can resize themselves would greatly reduce the complexity of these setups as well as providing a better/cleaner result. E.g. smoothly scaling users while they are moving, or keeping them in the proper position while standing still. Similar to how 'reset scale' looks visually.

I envision the node having a 'Start Drive', and 'Stop Drive' impulse, alongside a float input to specify the target scale, and user input to specify the affected user.

I also envision such a node having a float output to display the target's current scale, as well as passthrough impulses for OnStartDrive, and OnStopDrive, and an IsDriving bool.

https://cdn.discordapp.com/attachments/598212503666950205/773196955153072149/2020-11-03_06-41-46.mp4

**Comment by TehTurk** [comment]
I don't know if this can be added as the user is driven already, you use lerp/sets because inherently it's like so.
Them not keeping position is due to how scaling works at a system level on any engine.

**Comment by H3BO3** [comment]
I don't think it would need a drive, tbh, just a "set user scale" impulse that smoothly tweens them like, say, the "reset scale" button. I agree with Turk, having to override the regular drive like that could cause all sorts of issues.

**Comment by Frooxius** [comment]
I can add node to set the scale, but not to drive, as the User Root Global scale is inherently non-drivable. If you need that, parent the user under a slot that you can drive instead.

**Comment by shiftyscales** [comment]
Having a node to set the scale directly would still be a useful addition thanks, @Frooxius.

**Comment by TehTurk** [comment]
I mean isn't that no different from using the  UserRoot + Set Global Scale?

**Comment by H3BO3** [comment]
@TehTurk Shifty explained in the initial post why that has issues.

**Comment by TehTurk** [comment]
Ah okay, sorry I misread the comment just then.

**Comment by Frooxius** [comment]
Added the node in 2020.11.5.88, it lets you transition the scale smoothly over time too.

- Added "SetUserScale", which allows setting the global scale of the user while preserving their position in the world (requested by @Shifty | Quality Control Lead)
-- It also has optional "AnimationTime" input, which will smoothly animate the scale. Default is 0, which is instant change
