### ISSUE TITLE
Add Selective Render and Exclude Render to CameraPortal

### ISSUE THREAD

**Issue by Hayden-da-Serg** [Frooxius/NeosPublic#1274]
While @Coffee-Maker and I were working with fog volumes we found that using mirrors with fog volumes tends to break rendering with the specific settings we use. The fog volume rendering in the mirror causes some very strange stereo issues and doesn't look right at all and can even in some cases, cause eye strain.

To fix this, having Selective and Exclude render on CameraPortals would allow us to exclude the fog volume in the mirror entirely, fixing this and another issue we were having, which is what is forcing us to use these rendering settings in the first place.

I also explicitly recall requesting this two separate times on occasion, but never seems to have changed.

**Comment by shiftyscales** [comment]
Bringing this issue back (#857)- it wouldn't be implemented in that form. The solution is layers.
> 
> 
> This would be better handled by using layers, rather than selective renderers/exlcusion lists.
> 
> Using the exlclusion lists enables some problematic behaviors, and could potentially block additional optimizations down the line.
> 
> If performance is a consideration, I would suggest you utilize a camera instead with a selective render list under which users are parented to based on a collision volume near the mirror as discussed in the Discord.
> 
> Selective rendering would be very inefficient because it would need to iterate through the entire hierarchy of the world every single frame to mark each slot as active/inactive, and would actually hurt performance significantly by utilizing a lot of CPU time.
> 
> Once layer support is integrated at some point in the future, this will not be an issue as this could be made in an efficient way.

**Comment by H3BO3** [comment]
should we close this then?
