### ISSUE TITLE
Headless uptime gets converted to a local timezone

### ISSUE THREAD

**Issue by shadowpanther** [Frooxius/NeosPublic#1275]
I noticed right after a restart of the headless client that `status` command outputs uptime equal to 3 hours and several seconds:
```
Z36 - Cyber Laboratory>status
...
Uptime: 03:00:19.5158230
```
My suspicion is that it converts the uptime from GMT to Local time on output. I live in a UTC+3 timezone.

**Comment by shiftyscales** [comment]
This would also explain why some sessions have had a negative uptime before, interesting observation.

**Comment by Frooxius** [comment]
This is just the status command, it's checking local time against UTC time. It's a simple fix, but doesn't affect anything else.

**Comment by Frooxius** [comment]
Fixed in 2020.11.5.88!
