### ISSUE TITLE
RemotePressSpeed on PhysicalButton component has no effect

### ISSUE THREAD

**Issue by sirkitree** [Frooxius/NeosPublic#1276]
As seen in @ProbablePrime's video here: https://youtu.be/FM1P23pz5FY?t=330

Changing the value of RemotePressSpeed on the PhysicalButton component seemingly has no effect.

**Comment by Frooxius** [comment]
This is because this property was deprecated due to lots of issues with it (the button getting stuck or not pressing reliably or pressing multiple times due to an on-going animation), I'll remove it in the next build.

**Comment by Frooxius** [comment]
Removed in 2020.11.5.88!
