### ISSUE TITLE
Self-Respawn button sometimes not translated

### ISSUE THREAD

**Issue by H3BO3** [Frooxius/NeosPublic#1278]
Shadow Panther#5154 reported that all respawn buttons are translated except for the self-respawn button.

![unknown-1](https://user-images.githubusercontent.com/62123804/98171861-a452d700-1ead-11eb-80e1-87ac03b38d0d.png)

However, Alex from Alaska#2020 tried to replicate it with a language override and could not get the same results.

![image](https://user-images.githubusercontent.com/62123804/98172208-2fcc6800-1eae-11eb-85dd-10c7662a8b0a.png)

Any idea why this might be happening?

EDIT: Alex had the same results when switching to the Russian locale (All buttons were translated correctly).

**Comment by Frooxius** [comment]
- Were you switching the locale during the run of Neos or was it set to Russian from launch and not changed at all? 
- Are there any errors in the log?
- Does switching to another language clear the untranslated button?

**Comment by shadowpanther** [comment]
Hmm, that time I only switched locale while ingame. I tried this again in another instance and the button was properly translated. I've checked back in the instance where I saw this missing translation, and it's translated now. So probably it's the issue of locale loading on-the-fly, which is already known.
