### ISSUE TITLE
Changing HistoryLength on StandaloneRectMesh<AudioWaveformMesh> nulls any history that already exists.

### ISSUE THREAD

**Issue by RileyGuy** [Frooxius/NeosPublic#1279]
This makes it hard to sync the display to something such as frametime, as currently the waveform has no syncing whatsoever. This also makes it hard to just change it quickly with logix due to the nulling. Also makes using a smooth lerp on it impractical.

**Comment by Frooxius** [comment]
HistoryLength should only be set once depending on the effect you want, it should not be used dynamically at all, as this requires invalidating and re-allocating all the buffers.

It's not a mechanism to provide any syncing or anything like that, AudioWaveformMesh will implicitly display the latest audio data from the audio updates as soon as possible.
