### ISSUE TITLE
Getting a Users Voice Audio Stream is tricky/difficult

### ISSUE THREAD

**Issue by TehTurk** [Frooxius/NeosPublic#1285]
Currently to get a users Audio Stream, it is a bit of a task as you need to setup logix to equip/dequip an avatar to grab a users Audio Stream. This was possible prior, but was messing with it last night, and found it was a bit tricky without having some visual issues on the user due to the bug I found couple weeks back which broke this behavior #1131 By making grabbable events a bit more cleaner. 

- Wanting to grab a UsersAudioStream for effects, toys, avatars, worlds, or utilities
- Could even be tied to some sort of Grabbable only event, so the user needs to be willingly grabbing for the effect to occur in case of abuse, so giving it an opt in behavior
- With all the new voice toys due to Audio Improvements this would open up alot more creations :eyes:

**Comment by Frooxius** [comment]
There's already topic for this, in short won't happen until some extra security measures are put in place: https://github.com/Frooxius/NeosPublic/issues/915

**Comment by TehTurk** [comment]
Oops Apologies! Thanks for Directing me to that.
