### ISSUE TITLE
Eyemanager {Left,Right}EyeCloseOveride does not appear to do anything

### ISSUE THREAD

**Issue by mralext20** [Frooxius/NeosPublic#1286]
both these inputs do not appear to do anything. my understanding based on the name of these fields is that they would override the eye to be closed, when set to 1.

**Comment by Frooxius** [comment]
These normally work with just eye tracking, allowing the  eye tracked values to be overriden, but I can make them work with simulated eye movement as well.

**Comment by Frooxius** [comment]
They should now work properly even when using simulated eyes in 2020.11.15.758, thanks!
