### ISSUE TITLE
Audio input device selection issue.

### ISSUE THREAD

**Issue by orange3134** [Frooxius/NeosPublic#1287]
My system has an Input device and an Output device with the same name.
At this time, only one of them is displayed on the Neos VR setting screen.
This makes it impossible for me to select an input device.

Also, when I have a device with the same name, I will not be able to select some other device.

Please watch this video.
https://youtu.be/pkg2oVGg-As

If I change the device name in the Windows settings, all devices can be selected.

**Comment by inzanesonikku** [comment]
neos does not hear my Line 1 virtual mic in this latest build but it does perfectly fine in the last build.

**Comment by Frooxius** [comment]
Fixed in patch 2020.11.6.1124, I'm sorry for the inconvenience! Thank you for the report!
