### ISSUE TITLE
Add a label to inventory menu buttons

### ISSUE THREAD

**Issue by Earthmark** [Frooxius/NeosPublic#1288]
From what I've seen the inventory is the current front runner for most confusing system to new users. One of the top two most important panels in tutorial world is to tell users "the buttons at the top do x", and I'd like if I didn't need to have that.

To that end, can the inventory panels get text labels next to the icons? Buttons like "equip avatar", "set default avatar", and "delete item" (delete is normally not confusing, but consistency).

As a possible bonus good way to teach the saving behavior may be if the save button contextually changed from something like "make folder" to "save asset" depending on if your holding something, but that's bonus points because it's a complex behavior, and I'm requesting a duct tape level of hacky fix.

With the push to a new user experience, I think this may allow tutorials to lessen the focus they tend to have towards the inventory, where users can possibly understand the button behaviors contextually instead of through an external to the panel tutorial.

I know the ui isn't done, but for the understanding effort saved for each new user, this may be a very high value modification. Hopefully it's also low effort, but dunno that bit!

**Comment by Frooxius** [comment]
I'm sorry but I don't have plans to modify the old inventory system anymore. Changing these UI's is typically very labor intensive and this would require hacking in some new systems. It's better to wait for the redesigned version.
