### ISSUE TITLE
Camera Remains Locked to Disabled Anchors

### ISSUE THREAD

**Issue by Enverex** [Frooxius/NeosPublic#1296]
An issue Jason and co found when trying to film for the MetaMovie project, is that;

If a camera resides on an anchor which is then disabled (e.g. think world layers or zone culling) the camera basically gets stuck there and no-longer works until you delete (or reactivate) the anchor.

You cannot switch the camera to another anchor in this state. The interface seems to imply you're switching between anchors, but the camera render remains frozen and the camera doesn't physically switch to the new location so it's clearly "stuck" on the disabled anchor.

![image](https://user-images.githubusercontent.com/958670/98445753-52aa8680-2111-11eb-90eb-35b8f0dff4b8.png)

**Comment by Frooxius** [comment]
Should be fixed in 2020.11.8.605, thanks!
