### ISSUE TITLE
NREs logged from LoopbackAudioInputDriver.OnAudioFilterRead

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#1298]
Observed in my own Player.log files and others, e.g. Polaris, the loopback audio input driver is producing many NREs in the Player.log.

```
NullReferenceException: Object reference not set to an instance of an object
  at LoopbackAudioInputDriver.OnAudioFilterRead (System.Single[] buffer, System.Int32 channels) [0x00000] in <7564baf482354775be9424f51389e14a>:0 
 
(Filename: <7564baf482354775be9424f51389e14a> Line: 0)
```
[Player-prev.log](https://github.com/Frooxius/NeosPublic/files/5505812/Player-prev.log)

**Comment by Frooxius** [comment]
Fixed in 2020.11.8.605, thanks!
