### ISSUE TITLE
Slightly bump the allotted bandwidth for Steam Networking

### ISSUE THREAD

**Issue by RileyGuy** [Frooxius/NeosPublic#1299]
After about 11 people get into a session, Steam sockets start degrading and voice/actions get delayed by about 45 seconds. This is becoming an increasingly annoying issue as LNL is completely unusable for a niche amount of people - including me. As it stands I essentially get what is effectively a spectator ban whenever this happens as I can't interact or talk to anybody in any meaningful manner. I'm aware the bandwidth estimation doesn't work, but if it could be slightly bumped that would be appreciated.

**Comment by Frooxius** [comment]
I doubled the bandwidth in 2020.11.8.605, let me know how it goes!
