### ISSUE TITLE
SpawnAtPoint() on RandomObjectSpawner does not respect the position passed as parameter.

### ISSUE THREAD

**Issue by Aerizeon** [Frooxius/NeosPublic#1300]
Found this while trying to document the functionality for the wiki.

This can be reproduced by either:

1.  Calling `SpawnAtPoint()` on `RandomObjectSpawner` with a defined float3 value from a plugin

2. Attaching a `BoxCollider` and a `CharacterEventTrigger` to a slot, with one of the `TriggerEntered` entries set to the `SpawnAtPoint()` action on the `RandomObjectSpawner`

in either case, a random item from the `RandomObjectSpawner`'s `Template` list will be duplicated, but its location will be the same as the template entry, and not at the desired point.

Additionally, it would be nice if there was a way to trigger this from Logix, but that's not related to the above issue.

**Comment by Frooxius** [comment]
Fixed in 2020.11.8.605, thanks!
