### ISSUE TITLE
Importing rigs with Twist Bones have Issues, can we ignore them? 

### ISSUE THREAD

**Issue by TehTurk** [Frooxius/NeosPublic#1301]
This comes up pretty often on alot of models I've been importing, and others that have imported before as MMD bases are often used in more humanoid avatars.
- If the name of the bone has HandTwist it'll false flag because Hand Comes before Twist in the String
- If the bone name/string was checked from the end before the front you could check for Twist before Hand and ignore the bone. 
- Alot of Import issues for most new users getting them set up is related to this as MMD Bases are quite common.

**Comment by Frooxius** [comment]
Do you have any avatar samples (or at least screenshots of their hierarchies) that you could share for this? It can be tricky modifying the heuristics without breaking something else. Models come with all kinds of naming schemes, so I don't want to just flat out ignore certain key terms, as they might be legitimate bones in some avatars.

**Comment by TehTurk** [comment]
Sent!

**Comment by Frooxius** [comment]
THanks! I've made changes to heuristics in 2020.11.10.578, those should now import well without need for manual fixes!
