### ISSUE TITLE
Desktop Users are Blind as the RenderTextureProvider Texture fills their screen when Post Processing is TurnedOff on a Camera

### ISSUE THREAD

**Issue by TehTurk** [Frooxius/NeosPublic#1303]
- Found this with normal Camera objects
- The Interaction for it was on a Slot hidden by a HiddenLayer if it adds to it
- Can send object if need be, but ran this with a bunch of different situations.

**Comment by Frooxius** [comment]
We already have issue for this: https://github.com/Frooxius/NeosPublic/issues/1197

**Comment by TehTurk** [comment]
Oops Thanks, I even labeled it too xD.
