### ISSUE TITLE
[Logix Request] set grabbable and set playercollision logix nodes

### ISSUE THREAD

**Issue by Beaned2000** [Frooxius/NeosPublic#1304]
It would be handy to have nodes for setting grabbable/playercollision trough logix. i'd imagine it having similar inputs as the set active self node but then for setting those. this would help in big worldbuilding to set everything under a certain root with these.

**Comment by Frooxius** [comment]
I'm sorry, I don't plan on adding these as individual nodes, this will be implicitly enabled by LogiX Component access: https://github.com/Frooxius/NeosPublic/issues/243
