### ISSUE TITLE
DefaultUserScale on unequipped avatar throwing NRE on initialization

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#1306]
Steps to replicate:
- Have an unequipped avatar in the world with a DefaultUserScale component on it

The issue does not occur when equipping an avatar from the inventory. The avatar must have no active user.

Discovered in logs submitted by 3x1t_5tyl3# 0001 and Cyro# 5120
[SHIFTYWINDOWS - 2020.11.8.605 - 2020-11-08 12_21_46.log](https://github.com/Frooxius/NeosPublic/files/5507106/SHIFTYWINDOWS.-.2020.11.8.605.-.2020-11-08.12_21_46.log)

**Comment by Frooxius** [comment]
Fixed in 2020.11.10.578, thanks!
