### ISSUE TITLE
Neos bot near clip for oculus quest link cable users

### ISSUE THREAD

**Issue by Earthmark** [Frooxius/NeosPublic#1307]
It turns out apparently the eyes of link cable users render in front of the camera, making it very problematic to see anything.

As that's the first avatar people get with the MTC, some way not to have that issue would be very handy!

**Comment by shiftyscales** [comment]
The Neos bots in the Neos Essentials folders have been replaced with one featuring a nearclip, and the Neos bot creator in the avatar creation room has been fixed as well by Ryuvi. Thanks for the report! Hopefully this should help with new users from Oculus running on SteamVR until #828 is resolved.
