### ISSUE TITLE
"Separate parts of mesh unaffected by blendshapes" breaks the SimpleAwayIndicator

### ISSUE THREAD

**Issue by zkxs** [Frooxius/NeosPublic#1310]
Specifically, the new mesh created has its SimpleAwayIndicator component created correctly, but its user ref is not assigned to be set by any AvatarUserReferenceAssigner. Unless this is fixed manually, the non-blendshape part of the mesh will not properly transition to the away material when the user is away.

**Comment by Frooxius** [comment]
Should be good in 2020.11.10.578, thanks for report!
