### ISSUE TITLE
Request: headless log file naming consistency

### ISSUE THREAD

**Issue by shadowpanther** [Frooxius/NeosPublic#1313]
Please change the naming format of log files to locale-independent yyyy-mm-dd-hh24-mm-ss. That would make logs appear in the alphabetical order in directory instead of being all over the place.
i.e., "manul 11_2_2020_6_11_10_PM.log" should become "manul 2020_11_02_18_11_10.log"

On a related note, time format in the log itself should be the same - 24 hours, padded to 2 places.
"1:29:47 PM.392  Starting sync" -> "13:29:47.392  Starting sync"
This can already be fixed by switching from en_US to en_GB locale, but for the logs the format shouldn't depend on the locale.

**Comment by shiftyscales** [comment]
This change was already made quite a while back to the desktop builds I believe. It's interesting that headless would be treated differently. Thanks for reporting it.

**Comment by Frooxius** [comment]
Headless now uses same naming as the graphical client as of 2020.11.18.630, thanks!
