### ISSUE TITLE
Lasers always on for inactive controllers at launch

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#1316]
Reported by Ralii The Avali# 2181, if a user's controller is turned off while launching Neos, the lasers will remain always-on until they are initialized by the controller being turned on.

For users that only have use of/access to one controller it could be nice if this could be tweaked.

https://cdn.discordapp.com/attachments/439422161657135106/775796423299825684/20201108212525_1.jpg

**Comment by Frooxius** [comment]
Should be fixed in 2020.12.8.638! Thanks!
