### ISSUE TITLE
Eye Manager/setup heuristics issue

### ISSUE THREAD

**Issue by H3BO3** [Frooxius/NeosPublic#1318]
![740250_20201111000317_1](https://user-images.githubusercontent.com/62123804/98780475-0af65a00-23b2-11eb-9b07-fc2a55ef6a94.png)

Anything in the heuristics that would cause the eye manager to fail to setup on the left rig, but succeed on the right one? Both rigs are identical in hierarchy, I just did some name changes/normalizations and it worked the second time, but I'm wondering why the first revision didn't just work, especially with the recent eye heuristics changes. It also seems like it'd be prone to set something up incorrectly, but it just didn't set anything up at all, which I found interesting.

**Comment by Frooxius** [comment]
It's probably because the name has "eyeball" instead of "eye". The system isn't currently looking for that keyword.

**Comment by H3BO3** [comment]
Could that be tweaked?

**Comment by Frooxius** [comment]
Yeah I'll add that in the next build.

**Comment by Frooxius** [comment]
Hmm I checked the heuristics and it actually should handle eyeball already, so it's a bit odd that it wasn't setup. Is the eyeball an actual bone in the rig? Can you send me the model for testing?

**Comment by Frooxius** [comment]
Fixed in 2020.11.15.758! Turns out it was getting confused, because "ball" keyword is sometimes used for feet bones. Should import correctly now.
