### ISSUE TITLE
Unlisted "Contacts Only"  Results in "In Contacts Only World" Status Even When Already Friends

### ISSUE THREAD

**Issue by Enverex** [Frooxius/NeosPublic#1319]
So I ran into a weird situation last night where a headless server that I'm friends/contacts with was showing as "In a contacts only world" which makes no sense given that a headless cannot be in someone else's session and I'm already friends/contacts with the headless user.

What had actually happened was that the headless was set to Contacts Only and then had been switched to Unlisted. It should have shown "In a hidden session" but instead appeared to take the status from the contacts only status instead, which obviously doesn't make sense when the person viewing this is already friends/contacts with the headless user (as they'd have access to the contacts only session).

**Comment by TehTurk** [comment]
I responded to this in the server, but I'm unsure on why the behavior is there but I'd request that'd be leave the behavior as is, the context of Contacts, Private or Hidden in a social context is somewhat essentially/crucial. 
If it's Contacts Only, that means it's Friends but Hidden, which mean it's more of a personal situation. For Private, that means invites only, and the host is typically do something properly private, Hidden is in that case of where you want a session open, but you don't want users randomly barreling in.

**Comment by Electronus** [comment]
I thought this was a bug when I saw it yesterday, I would recommend a "Hidden, contacts only" message.

**Comment by TehTurk** [comment]
It wouldn't be bad, but it's also really wordy too.

**Comment by Enverex** [comment]
"but I'd request that'd be leave the behavior as is"

I disagree entirely. The information provided by the game as is, is wrong. That's never a good result.

**Comment by shiftyscales** [comment]
Hidden is hidden, I don't think much more context is needed other than that. If someone wishes to make their hidden session known, chances are they'll probably be doing so externally anyway, e.g. with a link, particularly when #922 gets resolved.

**Comment by Enverex** [comment]
Yeah, that's the crux of it really: I'd expect it to say hidden if it's hidden, so the fact it said "Contacts only world" made no sense, especially as I was a contact.

**Comment by TehTurk** [comment]
Hmm but it does add social context to the situation @shiftyscales. Because there's different types of hiding a session, as contacts can be more open, hidden is hidden but different rules, and private is private. Like if it's Hidden Contacts one would feel more comfortable approaching, vs a hidden general world.

**Comment by shiftyscales** [comment]
It doesn't matter a lot in either case as there isn't currently a mechanism to join a hidden session other than a direct invite at present as is.

Additional granularity could be offered once the contact list is reworked/extended to offer tagging, as it could be potentially possible to session details to only friends of a certain tag, allowing particular friend groups to drop in without the need to invite while keeping the overall session more locked down/hidden.

I believe I've actually witnessed this issue now, and just didn't realize it was an issue at the time. It left me confused wondering who's session a friend was in when it was actually probably just a hidden session.

**Comment by TehTurk** [comment]
No it matters to some degree, sure the wording is awk and should be changed, but how you present your session to those looking around on friends list is important too.

**Comment by Electronus** [comment]
My two cents are it should say "Hidden" or "hidden, Contacts only". It saying Contacts only when the host is in your contacts comes across as they are in someones else's session or a bug.

**Comment by Frooxius** [comment]
![image](https://user-images.githubusercontent.com/8838625/99128520-4e97d080-260b-11eb-93f2-19f0ae414e3b.png)

2020.11.13.1356 will now show In Hidden, Contacts Only World
