### ISSUE TITLE
Headless crash

### ISSUE THREAD

**Issue by shadowpanther** [Frooxius/NeosPublic#1320]
Tonight, my headless crashed. From the logs, I can see that noone was in the world, and the last messages in the log were `Saving World` and `World Optimized!`, i.e. the headless crashed while routinely saving the world while nothing actually changed in the world. This is what I got in the console:
```
Z36 - Cyber Laboratory>status
Name: Z36 - Cyber Laboratory
SessionID: S-d0bdec65-f678-4402-b947-40f6bdec6639
Current Users: 1
Present Users: 0
Max Users: 32
Uptime: 10:27:53.9550530
Access Level: Anyone
Mobile Friendly: False
Description:
Tags: cyber, laboratory, space
Users: Shadow Headless
Z36 - Cyber Laboratory>* Assertion at lock-free-alloc.c:145, condition `sb_header' not met, function:alloc_sb, Failed to allocate memory for the lock free allocator


=================================================================
        Native Crash Reporting
=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries
used by your application.
=================================================================

=================================================================
        Native stacktrace:
=================================================================
        0x55bae1e3deb5 - mono : (null)
        0x55bae1e3e250 - mono : (null)
        0x55bae1deb129 - mono : (null)
        0x55bae1e3d467 - mono : (null)
        0x7f98d26313c0 - /lib/x86_64-linux-gnu/libpthread.so.0 : (null)
        0x7f98d245518b - /lib/x86_64-linux-gnu/libc.so.6 : gsignal
        0x7f98d2434859 - /lib/x86_64-linux-gnu/libc.so.6 : abort
        0x55bae1dae2eb - mono : (null)
        0x55bae209b1a5 - mono : (null)
        0x55bae20b8b2e - mono : (null)
        0x55bae20b9113 - mono : monoeg_assertion_message
        0x55bae20a75eb - mono : mono_lock_free_alloc
        0x55bae206c706 - mono : (null)
        0x55bae206b0fa - mono : (null)
        0x55bae206b16c - mono : (null)
        0x55bae2063536 - mono : (null)
        0x55bae2094a81 - mono : (null)
        0x55bae2062d60 - mono : (null)
        0x55bae2064beb - mono : (null)
        0x55bae20650a3 - mono : (null)
        0x55bae20698fb - mono : (null)
        0x55bae20699db - mono : (null)
        0x55bae205983b - mono : (null)
        0x55bae203d2ba - mono : (null)
        0x55bae203add4 - mono : (null)
        0x55bae1fc3d23 - mono : (null)
        0x55bae1f72516 - mono : (null)
        0x4038955e - Unknown

=================================================================
        Telemetry Dumper:
=================================================================
Pkilling 0x7f98bd99a700 from 0x7f98bcb77700
Pkilling 0x7f9849333700 from 0x7f98bcb77700
Pkilling 0x7f98bd1fe700 from 0x7f98bcb77700
Pkilling 0x7f98bf9fc700 from 0x7f98bcb77700
Pkilling 0x7f980a208700 from 0x7f98bcb77700
Pkilling 0x7f9849534700 from 0x7f98bcb77700
Pkilling 0x7f95c8d67700 from 0x7f98bcb77700
Pkilling 0x7f98bd3ff700 from 0x7f98bcb77700
Pkilling 0x7f98bfbfd700 from 0x7f98bcb77700
Pkilling 0x7f980a409700 from 0x7f98bcb77700
Pkilling 0x7f98d240a780 from 0x7f98bcb77700
Pkilling 0x7f9849735700 from 0x7f98bcb77700
Pkilling 0x7f980a60a700 from 0x7f98bcb77700
Pkilling 0x7f98bfdfe700 from 0x7f98bcb77700
Pkilling 0x7f9849936700 from 0x7f98bcb77700
Pkilling 0x7f97003bd700 from 0x7f98bcb77700
Pkilling 0x7f98be9f4700 from 0x7f98bcb77700
Pkilling 0x7f980a80b700 from 0x7f98bcb77700
Pkilling 0x7f98bffff700 from 0x7f98bcb77700
Pkilling 0x7f98bd785700 from 0x7f98bcb77700
Pkilling 0x7f98cf487700 from 0x7f98bcb77700
Pkilling 0x7f9849b37700 from 0x7f98bcb77700
Pkilling 0x7f95c518f700 from 0x7f98bcb77700
Pkilling 0x7f98bebf5700 from 0x7f98bcb77700
Pkilling 0x7f98bddfb700 from 0x7f98bcb77700
Pkilling 0x7f97455ff700 from 0x7f98bcb77700
Pkilling 0x7f9849d38700 from 0x7f98bcb77700
Pkilling 0x7f9745917700 from 0x7f98bcb77700
Pkilling 0x7f98bedf6700 from 0x7f98bcb77700
Pkilling 0x7f98bdffc700 from 0x7f98bcb77700
Pkilling 0x7f97d3aff700 from 0x7f98bcb77700
Pkilling 0x7f9849f39700 from 0x7f98bcb77700
Pkilling 0x7f98bc775700 from 0x7f98bcb77700
Pkilling 0x7f98beff7700 from 0x7f98bcb77700
Pkilling 0x7f98be1fd700 from 0x7f98bcb77700
Pkilling 0x7f98bc976700 from 0x7f98bcb77700
Pkilling 0x7f98bf1f8700 from 0x7f98bcb77700
Pkilling 0x7f97b703b700 from 0x7f98bcb77700
Could not exec mono-hang-watchdog, expected on path '/etc/../bin/mono-hang-watchdog' (errno 2)
Pkilling 0x7f98be3fe700 from 0x7f98bcb77700
Crash reporter dumper exited due to fatal error.Pkilling 0x7f98cc23d700 from 0x7f98bcb77700
Pkilling 0x7f95c5ca3700 from 0x7f98bcb77700
Pkilling 0x7f98bf3f9700 from 0x7f98bcb77700
Pkilling 0x7f95c8153700 from 0x7f98bcb77700
Pkilling 0x7f98be5ff700 from 0x7f98bcb77700
Pkilling 0x7f98cc43e700 from 0x7f98bcb77700
Pkilling 0x7f98bcdfc700 from 0x7f98bcb77700
Pkilling 0x7f98bf5fa700 from 0x7f98bcb77700
Pkilling 0x7f9809e06700 from 0x7f98bcb77700
Pkilling 0x7f98bc36f700 from 0x7f98bcb77700
Pkilling 0x7f97a7b6f700 from 0x7f98bcb77700
Pkilling 0x7f9849132700 from 0x7f98bcb77700
Pkilling 0x7f98cc63f700 from 0x7f98bcb77700
Pkilling 0x7f95c7a5b700 from 0x7f98bcb77700
Pkilling 0x7f97b2fc7700 from 0x7f98bcb77700
Crash reporter dumper exited due to fatal error.Pkilling 0x7f98bcffd700 from 0x7f98bcb77700
Pkilling 0x7f98bf7fb700 from 0x7f98bcb77700
Pkilling 0x7f980a007700 from 0x7f98bcb77700

=================================================================
        External Debugger Dump:
=================================================================
mono_gdb_render_native_backtraces not supported on this platform, unable to find gdb or lldb

=================================================================
        Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0x7f98d245518b):0x7f98d245517b  d2 4c 89 ce bf 02 00 00 00 b8 0e 00 00 00 0f 05  .L..............
0x7f98d245518b  48 8b 84 24 08 01 00 00 64 48 33 04 25 28 00 00  H..$....dH3.%(..
0x7f98d245519b  00 75 26 44 89 c0 48 81 c4 18 01 00 00 c3 0f 1f  .u&D..H.........
0x7f98d24551ab  80 00 00 00 00 48 8b 15 b9 4c 1a 00 f7 d8 41 b8  .....H...L....A.

=================================================================
        Managed Stacktrace:
=================================================================
          at <unknown> <0xffffffff>
          at System.String:FastAllocateString <0x0007d>
          at System.Guid:ToString <0x00142>
          at System.Guid:ToString <0x0002d>
          at FrooxEngine.SaveControl:ReferenceToString <0x000aa>
          at FrooxEngine.Slot:Save <0x0067f>
          at FrooxEngine.Slot:Save <0x0035e>
          at FrooxEngine.Slot:Save <0x0035e>
          at FrooxEngine.Slot:Save <0x0035e>
          at FrooxEngine.Slot:Save <0x0035e>
          at FrooxEngine.Slot:Save <0x0035e>
          at FrooxEngine.Slot:Save <0x0035e>
          at FrooxEngine.Slot:Save <0x0035e>
          at FrooxEngine.World:Save <0x00364>
          at FrooxEngine.World:SaveWorld <0x00127>
          at <>c__DisplayClass207_0:<SaveWorldTaskIntern>b__0 <0x0012f>
          at FrooxEngine.World:RunSynchronousActions <0x001db>
          at FrooxEngine.World:NextRefreshStage <0x0009f>
          at FrooxEngine.World:Refresh <0x00263>
          at FrooxEngine.WorldManager:UpdateStep <0x01993>
          at FrooxEngine.WorldManager:RunUpdateLoop <0x0006f>
          at FrooxEngine.Engine:UpdateStep <0x0021f>
          at FrooxEngine.Engine:RunUpdateLoop <0x000e7>
          at NeosHeadless.Program:UpdateLoop <0x00457>
          at System.Threading.ThreadHelper:ThreadStart_Context <0x000ae>
          at System.Threading.ExecutionContext:RunInternal <0x0018f>
          at System.Threading.ExecutionContext:Run <0x00042>
          at System.Threading.ExecutionContext:Run <0x0006d>
          at System.Threading.ThreadHelper:ThreadStart <0x00042>
          at System.Object:runtime_invoke_void__this__ <0x00091>
=================================================================
Aborted (core dumped)
```

I have the log and the `mono_crash` files stashed in case those are useful for debug purposes.

**Comment by Frooxius** [comment]
Which version of Mono you're using? It doesn't look like the crash is coming from Neos itself, but rather from the Mono runtime in memory allocation. There's not much we can do about that one unfortunately, I'd recommend updating to the latest stable version of Mono if possible.

**Comment by shadowpanther** [comment]
root@manul:/home/panther# dpkg-query -W mono-runtime
mono-runtime    6.8.0.105+dfsg-2
root@manul:/home/panther# mono -V
Mono JIT compiler version 6.8.0.105 (Debian 6.8.0.105+dfsg-2 Wed Feb 26 23:23:50 UTC 2020)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        Interpreter:   yes
        LLVM:          supported, not enabled.
        Suspend:       hybrid
        GC:            sgen (concurrent by default)

**Comment by uyjulian** [comment]
Related issues: 
https://github.com/mono/mono/issues/12947  
https://github.com/mono/mono/issues/18617  

It is possible that the error is related to out-of-memory handling. Possibly a memory leak?

**Comment by Enverex** [comment]
Use Mono 6.10. It's been rock solid for me on many worlds on multiple servers. I've seen errors like this on earlier versions randomly.

**Comment by shadowpanther** [comment]
I've updated straight to 6.12 which is the latest one, I'll see if that helps with memory.

**Comment by shadowpanther** [comment]
Same crash on 6.12, after running just for several hours with just one world and several users. Crash dump looked exactly the same.

**Comment by Frooxius** [comment]
How much memory do you have on the system? What's the swap size? 

Here's one recommendation on which GC modes to use for this, apparently Low Latency mode can cause these problems: https://stackoverflow.com/questions/27685375/garbage-collector-could-not-allocate-16384-bytes-of-memory-for-major-heap-sectio

**Comment by shadowpanther** [comment]
```
root@manul:/home/panther# free -h
              total        used        free      shared  buff/cache   available
Mem:           15Gi       7.6Gi       143Mi       7.0Mi       7.8Gi       7.6Gi
Swap:          14Gi       731Mi        14Gi
```
Looks like just before the crash there were about 5G memory used in total. It's higher now because there are users in the world. I didn't configure mono at all, how would you advice to set it up so that there would be no/less crashes?

**Comment by shadowpanther** [comment]
Another message, this one I see for the first time:
```
Z36 - Cyber Laboratory>/mnt/d/Sync/Projects/Software/Applications/Neos/Dependencies/crunch-unity/crnlib/crn_threading_pthreads.cpp(161): Failure: ""semaphore: sem_wait() or sem_timedwait() failed""

/mnt/d/Sync/Projects/Software/Applications/Neos/Dependencies/crunch-unity/crnlib/crn_threading_pthreads.cpp(161): Failure: ""semaphore: sem_wait() or sem_timedwait() failed""
```
Looks like this happened after the headless tried (unsuccessfully, because of ongoing sync) to restart the world:
```
23:33:07.832    Resolving SessionID:
23:33:08.120    Conflicting cloud record version! Local: 2134, Global: 2159
23:33:09.702    UNDISPOSED: SyncMessage: Control, SenderStateVersion: 0, SenderSyncTick: 0, SenderUser: , Targets.Count: 1
23:33:09.702    UNDISPOSED: SyncMessage: Control, SenderStateVersion: 0, SenderSyncTick: 0, SenderUser: , Targets.Count: 1
23:33:09.702    UNDISPOSED: SyncMessage: Control, SenderStateVersion: 0, SenderSyncTick: 0, SenderUser: , Targets.Count: 1
23:33:09.702    UNDISPOSED: SyncMessage: Control, SenderStateVersion: 0, SenderSyncTick: 0, SenderUser: , Targets.Count: 1
```

**Comment by shadowpanther** [comment]
The crash seems to happen after the world save, while the sync is running, because sync started is the last message in the log usually.
What I already know:
* the crash most often (this kind of crash always?) happens on sync
* headless was running for some time before the crash (12 hours the last time it crashed)
* I'm autosaving the world every 10 minutes (crash doesn't seem to affect users who don't save and run the same copy of the world instead)
* I'm syncing to cloud storage (crash doesn't seem to affect users who save the world, but save to local storage)
Can you add some debug output to the sync to maybe help narrow down the issue?

**Comment by Frooxius** [comment]
The syncing already has extensive logging process. Generally none of what it does should ever cause crash though, there's not too many mechanisms that can happen with.

However the syncing does allocate a whole bunch of memory for processing the data. From your logs, it seems that the Mono runtime fails to allocate the memory for some reason. Unfortunately that kind of bug is in the runtime itself, which is at lower level than Neos operates and there isn't much that we can do (other than not allocating memory to trigger the issue, but then we can't really do the necessary processing).

I'd recommend trying out different Mono versions or even checking for system updates since the failures seem to stem from some core system operations. 

If you have a Windows OS/machine available, it might be worth running the headless on it with same setup using .NET Framework and see if the issue is present there as well.

**Comment by Frooxius** [comment]
One thing you could also try is switching the active GC used in the Mono runtime if possible. e.g. from SGen to Boehm if it's available. It'll worsen the performance, but might not be susceptible to same bugs.

**Comment by shadowpanther** [comment]
Okay, trying to run with
```
export MONO_ENV_OPTIONS='--gc=boehm'
export MONO_GC_DEBUG='print-allowance'
export MONO_GC_PARAMS='max-heap-size=2g'
```
Let's see if that helps.

**Comment by shadowpanther** [comment]
Running with boehm, didn't have a crash since, but memory usage is steadily climbing overtime even while there are no users in the world.
![](https://cdn.discordapp.com/attachments/619845139770376192/784419029951184907/unknown.png)
Maybe some allocated memory is not being freed internally? Someone mentioned yesterday that saving heavy worlds seems to lead to memory usage increase each time. Not noticeable for just one save, only when you work on the world and save often. As I'm saving the world every 10 minutes, that might be the case.

**Comment by shadowpanther** [comment]
Tried going back to SGen, now with the following options:
```
export MONO_GC_DEBUG='print-allowance'
export MONO_GC_PARAMS='nursery-size=64m'
```
and autosave turned up to 30mins (was 10).
It stopped crashing,  but now it runs out of memory the other way:
![](https://cdn.discordapp.com/attachments/619845139770376192/785625754057703434/unknown.png)
This session's log is available at https://www.dropbox.com/s/i4omm73xgk6xa28/manul%20-%202020.12.5.1396%20-%202020-12-07%2002_27_01.log.gz?dl=0

**Comment by Frooxius** [comment]
I'd recommend leaving the nursery size smaller, generally it's not a good idea to increase it that much, as that can degrade its performance and hurt the usefulness.

How much system memory is used when you crash with out of memory error? Is it possible to increase your system's virtual memory size? It's possible the GC is having trouble allocating a large block of memory from the system, even if enough memory is free.

**Comment by shadowpanther** [comment]
How much smaller? Default 4m cause(?) crashes, my 64m don't. What exact settings would you recommend?

Here's my memory and swap usage, was at less than 11G mem used out of total 16G. I have another 16G allocated for swap, so that would total to 32G of virtual memory.
![](https://cdn.discordapp.com/attachments/619845139770376192/785638482924142622/unknown.png)

**Comment by Frooxius** [comment]
Generally the default is good. The nursery isn't likely causing crashes by itself, but it just delays whatever does. Typically new memory gets allocated in the nursery region (generation 0) and once it fills up it gets cleared and anything still used gets moved to the eden (generation 1). If it's smaller, that will happen a lot more often (which is usually good, as most of the temporarily allocated memory gets cleared out frequently). 

Was the out of memory crash above with the default 4 MB?

**Comment by shadowpanther** [comment]
I've skimmed the docs on GSs, thanks. The nursery size is the only one that is limited by default, and as the crash was about the inability to allocate memory, I tried increasing this limit.

The *crash* that was the subject of this issue was with the default settings. I tried boehm per your advice and it just kept eating memory and became unusable. I tried sgen with above settings and that gave me the current situation - no crash, but memory limit instead.

**Comment by Frooxius** [comment]
Hmm it still seems like there's some weird issue with GC misbehaving in that case, particularly when there's memory available. The first bug (with the default nursery size) doesn't seem to be actually inability to allocate memory, but rather an internal bug in doing so. Is this is still using the same Mono version?

You could try also playing with the other GC settings, e.g. using markswee-par collector for the major heap: https://www.mono-project.com/docs/advanced/garbage-collector/sgen/working-with-sgen/

**Comment by shadowpanther** [comment]
Yes, still at mono 6.12:
```
panther@manul:~/neosvr/Logs$ mono -V
Mono JIT compiler version 6.12.0.90 (tarball Fri Sep  4 14:02:38 UTC 2020)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        Interpreter:   yes
        LLVM:          yes(610)
        Suspend:       hybrid
        GC:            sgen (concurrent by default)
```

The problems with playing with settings are long iteration cycle (several hours to a full day) and the crash itself undoing our work in the world.
Okay, this iteration would be:
```
export MONO_GC_DEBUG='print-allowance'
#export MONO_GC_PARAMS='nursery-size=64m'
export MONO_GC_PARAMS='major=marksweep-par'
```
Default nursery size, non-default major collector.

**Comment by Frooxius** [comment]
There's not too much else that could be done though. You could see if there are any Mono memory profiling tools that you could use to get more information, particularly to scan the memory usage and see what's being pinned.

On Windows there are both the official tools in Visual Studio and JetBrains dotMemory. It might work on Linux with Mono too, but unfortunately I don't have experience with that. I've profiled the Windows version with .NET Framework before during the save process, but it seems to reclaim memory properly there, so it's likely some issue specific to the Mono runtime. Given lots of configuration options, flavors and combinations there are of it, it makes it a fair bit harder to diagnose.

One thing you could try is also not use the LLVM backend. Usually that's disabled by default for Mono, so it might be less stable and have some issues when generating code that interacts with the GC.

**Comment by shadowpanther** [comment]
I'm not a developer myself, and I have next to none experience with Mono. That's why I'm asking for help instead of just doing the work myself.
Would the profiling described https://www.mono-project.com/archived/heapshot/ here give you any useful information?

As for LLVM, I don't think is uses it by default:

> Now you have an LLVM-powered Mono. By default, the mono JIT is used to compile code, to make the runtime use LLVM, pass the ‘–llvm’ command line option, or add it to the MONO_ENV_OPTIONS environment variable.
> 
> LLVM generates better code at runtime, but also takes longer to execute. This is why you need to explicitly tell Mono’s runtime to use the LLVM backend. This is achieved by either setting the environment variable MONO_USE_LLVM or by passing the –llvm command line option to Mono.

I'll try running with `--nollvm` to see if that helps, but I don't think that's the case.

**Comment by shadowpanther** [comment]
Current status:
* crashes still happen, --nollvm didn't change anything (I checked with --llvm, it just crashes straight away, so LLVM is not used by default), changing GC collector didn't help
* mono just updated to 6.12.0.107, build notes don't mention any relevant issues, probably won't fix the oom/crash
* heapshot is outdated and is not found in repos, still looking for a better way to profile the memory/heap usage

**Comment by tyronx** [comment]
Hey, different developer from a different game here. A user of mine gets the same crash on a headless server, presumably also during high ram usage, also on mono 6.12.0.107. Most likely a bug in mono, we'll try to gather the data we can and report to it the mono devs.

**Comment by shadowpanther** [comment]
@tyronx if you can give a method of gathering the relevant data, I can try to do it. In my case, the crash happens when there're a lot of free RAM available, so it's not a pure OOM.

**Comment by tyronx** [comment]
@shadowpanther it might help to verify if its really 64 bit mono, what operating system you are on and check if there is many anything with mono or the OS that caps the max ram usage. 

One of the mono devs noted that it could be OOM, so maybe something is there that denies further ram allocation. 🤷

**Comment by shadowpanther** [comment]
@tyronx it is a 64-bit mono:
```
# mono -V
Mono JIT compiler version 6.12.0.107 (tarball Thu Dec 10 05:26:45 UTC 2020)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        Interpreter:   yes
        LLVM:          yes(610)
        Suspend:       hybrid
        GC:            sgen (concurrent by default)
```
I use the latest Ubuntu:
```
# cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.1 LTS"
```
I have no limits on memory usage that I know of, and the crash itself happens on different RAM usage levels (overall and process-wise), not on some hard-capped number.

**Comment by shadowpanther** [comment]
As I have GC debug enabled, I have these memory usage numbers just before the recent crash:
```
Autosaving Z36 - Cyber Laboratory...
Saving world: Z36 - Cyber Laboratory, currently being saved: 1
World Optimized! Deduplicated Materials: 0, Deduplicated Static Providers: 5, Cleaned Up Assets: 36
2021-01-03 09:55:45 Starting collection with heap size 3059038400 bytes
2021-01-03 09:55:46 Surviving sweep: 2236286544 bytes (1683210240 major, 553076304 LOS)
2021-01-03 09:55:46 Allowance: 645952796 bytes
2021-01-03 09:55:46 Trigger size: 2882239340 bytes
2021-01-03 09:55:53 Starting collection with heap size 2887664640 bytes
2021-01-03 09:55:54 Surviving sweep: 2279692488 bytes (1728249856 major, 551442632 LOS)
2021-01-03 09:55:54 Allowance: 620819116 bytes
2021-01-03 09:55:54 Trigger size: 2900511604 bytes
World Saved! Name: Z36 - Cyber Laboratory. RecordId: U-Shadow-Headless:R-8aec10a6-571c-41a3-a3ad-f42841d6ab4e. Local: 5226, Global: 5183
Finished save world: Z36 - Cyber Laboratory, currently being saved: 0
Z36 - Cyber Laboratory saved!
Starting sync for U-Shadow-Headless:R-8aec10a6-571c-41a3-a3ad-f42841d6ab4e. Local: 5227, Global: 5183
2021-01-03 09:57:28 Starting collection with heap size 2903170968 bytes
2021-01-03 09:57:29 Surviving sweep: 2820230104 bytes (2268643328 major, 551586776 LOS)
2021-01-03 09:57:29 Allowance: 733669057 bytes
2021-01-03 09:57:29 Trigger size: 3553899161 bytes
2021-01-03 09:59:03 Starting collection with heap size 3554218088 bytes
* Assertion at lock-free-alloc.c:145, condition `sb_header' not met, function:alloc_sb, Failed to allocate memory for the lock free allocator
```
It is about 3Gb, I have 16Gb of RAM and 16Gb of swap! What OOM are you talking about, mono?

**Comment by uyjulian** [comment]
The error seems to show up in Mono source code:

https://github.com/mono/mono/blob/da11592cbea4269971f4b1f9624769a85cc10660/mono/utils/lock-free-alloc.c#L145   

https://github.com/mono/mono/blob/da11592cbea4269971f4b1f9624769a85cc10660/mono/utils/lock-free-alloc.c#L185  

`mono_valloc` could return NULL when `mmap` fails or `mono_valloc_can_alloc` check fails…  
`mono_valloc_aligned` calls `mono_valloc` but with 2x the memory at first… NULL check is same as `mono_valloc`

**Comment by shadowpanther** [comment]
As per mono devs' advice, I did increase vm.max_map_count (`sudo sysctl -w vm.max_map_count=262144`). Mono stopped crashing, but now the next issue surfaced - namely, memory usage. Without crashing for a while, Neos tends to use more and more memory. It ate my whole RAM and almost all of swap. The process used about 27G VRAM before I killed it.

Observations:
* Just running the headless with a world doesn't seem to eat much memory
* Autosave cycle on itself doesn't eat much memory (at least it releases the used memory)
* After a player joins the world, RAM/VRAM usage starts to grow continually, and doesn't stop growing when user leaves

I could setup a world autorestart to mitigate that, but restarting while still syncing leads to the world not being loaded, so that's a no-go for now.

**Comment by shadowpanther** [comment]
Closing this issue as the crash doesn't happen anymore after adjusting sysctl.

**Comment by Aerizeon** [comment]
Does it still consume an insane amount of memory, or did you find a workaround for that as well? @shadowpanther

**Comment by shadowpanther** [comment]
@Aerizeon I set up the idleRestart in the end, the restarted world doesn't consume extra memory before users join, even with constant saving, and users rarely stay in the world for extended amounts of time, so the world would restart again after users leave. The only issue with this setup now is that if restart comes when sync is runing, the world wouldn't load. I have a separate issue for this - #1649.
