### ISSUE TITLE
PBS Distance Lerp Specular Transparency not rendering

### ISSUE THREAD

**Issue by stevenazari** [Frooxius/NeosPublic#1322]
Hi,
Tried to use transparency on PBS distance Specular - click the checkbox and it goes to black/white checkers
![Photo in Universe](https://user-images.githubusercontent.com/568850/98880769-6bec6380-2480-11eb-96d8-42aea32d66cf.png)

**Comment by Frooxius** [comment]
Was typo in the shader name, should be good in 2020.11.13.1356, thanks!
