### ISSUE TITLE
Voice Message bubble does not stop Microphone tooltip from recording

### ISSUE THREAD

**Issue by H3BO3** [Frooxius/NeosPublic#1326]
Reported by Zane, a potential privacy issue, primarily linked to microphone tooltips that are able to record nearest/arbitrary users instead of the active one - Voice messages can be recorded externally while the user is recording them to the social menu, and thus should be silenced/private, however the tooltip can override that.

**Comment by Frooxius** [comment]
Fixed in 2020.11.13.1356, thanks!
