### ISSUE TITLE
InteractiveCamera without a proper timer setup throws NullReferenceException in logs and breaks camera while Photo Timer is enabled in the Stream Camera

### ISSUE THREAD

**Issue by Hayden-da-Serg** [Frooxius/NeosPublic#1330]
The title says it all, if an Interactive Camera doesn't have a proper timer setup, it breaks and floods logs with NullReferenceException, here's the following snippet from the logs

```Exception:
System.NullReferenceException: Object reference not set to an instance of an object
  at FrooxEngine.InteractiveCamera.OnCommonUpdate () [0x01766] in <02768d6631474baab629bcd8d181cd75>:0 
  at FrooxEngine.ComponentBase`1[C].InternalRunUpdate () [0x00016] in <02768d6631474baab629bcd8d181cd75>:0 
  at FrooxEngine.UpdateManager.RunUpdates () [0x0007c] in <02768d6631474baab629bcd8d181cd75>:0 
```

Lewis's EyeCam in LewiPuplic has these properties, to replicate, favorite that and then go to the Stream Camera window and enable Photo Timer, the Camera view will switch to a Null texture as long as it's enabled and the logs will have the exception mentioned above.

**Comment by shiftyscales** [comment]
[SHIFTYWINDOWS - 2020.11.13.1356 - 2020-11-14 12_13_51.log](https://github.com/Frooxius/NeosPublic/files/5541404/SHIFTYWINDOWS.-.2020.11.13.1356.-.2020-11-14.12_13_51.log)

Ideally the camera should be properly configured/setup in the first place.

**Comment by Frooxius** [comment]
As of 2020.11.15.758 the camera will now skip updating those if they're not present, making the timer display optional.
