### ISSUE TITLE
Deleting a loading video player crashes Neos

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#1333]
Reported by Shadow Panther# 5154, if a video player that is in the progress of loading is deleted, Neos will crash.
Steps:
- Copy a video URL, tested in particular with a Twitch.tv link
- Paste the video into Neos
- While the video is checkerboarded/loading, delete it

[SHIFTYWINDOWS - 2020.11.13.1356 - 2020-11-14 11_53_47.log](https://github.com/Frooxius/NeosPublic/files/5541381/SHIFTYWINDOWS.-.2020.11.13.1356.-.2020-11-14.11_53_47.log)
[error.log](https://github.com/Frooxius/NeosPublic/files/5541382/error.log)
[Player.log](https://github.com/Frooxius/NeosPublic/files/5541383/Player.log)

This is likely one of the more common scenarios/reasons for the crashing media playback libraries. Is mitigation possible?

Otherwise, this will hopefully be addressed once we can implement the official VLC library.

**Comment by Frooxius** [comment]
We already have topic for the libVLC crashes. There's not really much we can do on our end other than update the libVLC when it's ready: https://github.com/Frooxius/NeosPublic/issues/660
