### ISSUE TITLE
Dash updating stops voice message playback

### ISSUE THREAD

**Issue by RileyGuy** [Frooxius/NeosPublic#1336]
When viewing the dash screen, it will occasionally update based on information received from user statuses in worlds. This stops voice message playback and makes it essentially impossible to listen to any long voice messages.

**Comment by Frooxius** [comment]
This is a known issue, but unfortunately I don't have a plan to fix this with the old Friends list as it would be far too laborious and hacky, it'll have to wait until the reworked Friends system, sorry!
