### ISSUE TITLE
LocaleStringDriver get's added after each spawn of a tool.

### ISSUE THREAD

**Issue by 3x1t-5tyl3** [Frooxius/NeosPublic#1337]
On any tool. (Tested LogiX and Dev from the official folder) it adds a localestringdriver for each spawn out. Instead of reverting to the original. Overtime this can accumulate tons of locale string drivers for each tool.

Reproduction:
1: Spawn out any tip.
2: There's one localestringdriver
3: Save it to inventory
4: Spawn it out
5: There's 2 localestringdrivers
6: repeat 3&4 as many times as you like. It'll add a localestringdriver for each subsequent spawn and save. Resulting in hundreds if the tool in question get's save alot.

Extreme example is my multitool Where ***every*** tool underneath get's a localestringdriver and for every spawn out it accumulates more.

So if the multitool has 10 tools on it;
10 localestringdrivers are added on each spawn out.
+10 for each save and subsequent spawn out.

As such there's more and more components added for every save and spawn out.

**Comment by Frooxius** [comment]
What exactly are those locale string drivers driving?

**Comment by mralext20** [comment]
both locale string drivers drive the EquipName, of the base tool.

**Comment by Frooxius** [comment]
Thanks, fixed this in 2020.11.18.630!
