### ISSUE TITLE
OBS Websocket menu on camera/streaming panel shows blank buttons and camera control is broken after connecting OBS

### ISSUE THREAD

**Issue by kulzae** [Frooxius/NeosPublic#1339]
I am unable to move the camera left right up down or forward / back after connecting OBS via the websocket function. the buttons are also blank but still function normally. Issue was duplicated by Blaze on the discord
![image](https://user-images.githubusercontent.com/40366296/99192541-5f4a6280-2741-11eb-9aef-ab5e38dca61c.png)

**Comment by Medravr** [comment]
I can confirm this is also the case.

**Comment by Frooxius** [comment]
Do you have logs for this?

**Comment by ProbablePrime** [comment]
[ALFRED - 2020.11.13.1356 - 2020-11-14 19_33_33.log](https://github.com/Frooxius/NeosPublic/files/5543705/ALFRED.-.2020.11.13.1356.-.2020-11-14.19_33_33.log)
Here's my latest log from last night where this was occuring, It was occuring on 11.13 though as I didn't update before sleeping.

**Comment by Frooxius** [comment]
Should be fixed in 2020.11.16.430, thanks!
