### ISSUE TITLE
Tutorial Skip Request

### ISSUE THREAD

**Issue by Moorekun** [Frooxius/NeosPublic#1347]
https://discord.com/channels/402159838827905024/477711742001086505/778087104538083349

Currently there is no way to skip the newly added tutorial dialouge within Neos, I suggest being able to select a "Skip tutorial" option somewhere after initial locale, height and microphone set up.

**Comment by Frooxius** [comment]
We'll have to add this as some kind of secret option, because we don't want new users skipping the tutorial. In our experience many of them will do that given the option and then get frustrated and leave.

**Comment by Moorekun** [comment]
Absolutely agree with it being a secret option!
New user experience is more important then recovery time for Cache clearing!

**Comment by DeliriousJax** [comment]
I certainly agree with a skip, having a corrupt database recently made getting back into Neos very frustrating. And I wouldn't use the term secret. If people desire to skip the tutorial, being forced into it can be just as frustrating than not knowing what they are doing and getting frustrated from that. In this case, I believe there is simply no right answer.
I suggest making the "skip tutorial" option small and greyed out a bit, yes. But hidden or secret entirely? Eeehhhh.... Strongly disaree.

**Comment by mralext20** [comment]
Perhaps the trigger for skipping the tutorial be to enable edit mode using the head gesture?

**Comment by Frooxius** [comment]
I understand the frustration, but you're coming from perspective of experienced user. A brand new user having to go through a few basic steps to make sure they don't get completely lost far outweighs the frustration and negativity they bring by getting confused and frustrated after skipping it and we'll be back to square one. I strongly disagree that going through a short tutorial is as bad as the user getting confused.

Given our past experience and experience from a lot of other software the option will be hidden. A lot of the other software doesn't even give you that.

**Comment by TehTurk** [comment]
I agree, but the option should be there in some form. Maybe some form of checking playtime? I don't see why the option couldn't be added. We're fine if you really don't want a skip, but a skip in some form should be added, or an option to avoid starting into the MTC on Fresh Start.

**Comment by mralext20** [comment]
I don't think play time would be a good metric, what of people returning from a long hiatus? Or who never really got into neos

**Comment by Frooxius** [comment]
@TehTurk The option **is** going to be added, just as a hidden one so new users don't trigger it by accident (or on purpose, thinking they don't need tutorial and then not be able to get back).

**Comment by ohzee00** [comment]
Perhaps a param pass to the Neos.exe would be good? Would be easy for experienced users to never get it for they can either add it to a shortcut manually or do it via "Set launch options" in the steam properties window. Plus I highly doubt a new user would go searching for that if it isn't a convenient skip button.

**Comment by Frooxius** [comment]
Yes param pass can work. I was thinking of adding something in-game as well though if it has already started.

**Comment by DeliriousJax** [comment]
If the skip option is somewhere (even if hidden) then cool/fair enough, yeah.
But the tutorial experience can't be too restricting if that's the case is all. I had to rescue my roommate/landlord last night because of the tutorial world being too mundane and slow. I wound up teaching him externally by taking him to a different world once he could.

Also, as a suggestion, just add. "Already have an account? Sign in" If the account logged into via this method is old enough/already has neos experience time on it's record, Whala. All done.

**Comment by Frooxius** [comment]
I considered that, but there's not an easy metric for that to use. There are many people with really old accounts who tried Neos once briefly and left, they ideally should go through the experience themselves. I could potentially add a setting to it, but that's already over-engineering the problem, that can be solved by simply having the skip option right at the start.

The welcome guide shouldn't take more than a minute or two if you already have an account (or if you skip creating one). Why do you feel that the tutorial is too slow? You can page through it as fast as you want.

**Comment by ProbablePrime** [comment]
I think both sides of this have some merit but the best thing here should be to observe how other users go through it over a little period of time and to see what's going on and what can be improved. I'd keep an eye on youtube and twitch over the next few weeks and see where people get stuck or confused.

Based on that enhancements can be made and tweaked.

Skipping it for experienced users using whatever method is available will resolve it for us experienced folks.

Time, Patience and User Research will improve and resolve any issues that come up for new users.

**Comment by DeliriousJax** [comment]
Prime is right. I still believe hiding the skip to play functionality too much is not the best idea. As for the tutorial experience, I'll save my thoughts for later refinement.

**Comment by Frooxius** [comment]
Yes, we'll definitely have to watch what users do and make tweaks based on that. However having option to skip the tutorial visibly isn't something that'd I'd likely add exactly because all such past observations and different approaches we tried (e.g. contextual tutorials).

New users will often try to do anything *but* the tutorial or basic setup and get frustrated that things aren't working or that they don't know how to close this menu or that. It needs to be a *very* controlled experience so the user can focus just on the one thing and our efforts will go towards refining that.

Those decisions were done based on the past observations on how new users interact with Neos, they were not made on a whim.

**Comment by ProbablePrime** [comment]
I agree with your approach and am excited by the statement about tweaks, the old MTC felt static so it'll be great to see this one evolve. 

Thanks for the discussion Froox :D

**Comment by Frooxius** [comment]
Thanks! Yeah, with all the new things in Neos since the first MTC (particularly UIX, localization, dynamic variables, collider trackers) this should be much more flexible and easier to edit and update on the fly.

**Comment by shadowpanther** [comment]
What if you give the user just two options (and another two after the second one):

- Start playing (takes them to the Tutorial, maybe offers to register an account)
- Log in (takes the user to the login dialog without the option to register), after the user logs in:
  - Show me what's new, I haven't played for a while
  - That's enough for now

**Comment by Frooxius** [comment]
That was already discussed above, it's just over-complicating the system unnecessarily. I already have the skipping implemented, it'll come out soon.

**Comment by Frooxius** [comment]
Added multiple ways to skip the tutorial in 2020.11.18.630

- You can now skip the intro tutorial (based on feedback by Moorekun, @DeliriousJax, @Turk, @ohzee, @ProbablePrime and @Shadow Panther [RU/EN, UTC+3])
-- Pass -SkipIntroTutorial to Neos on startup, which will prevent the intro tutorial from starting
-- Same option was added to Neos launcher as well as persistent
-- You can also skip the tutorial by enabling Edit mode while at the "Welcome" screen (suggested by @Alex from Alaska)

Thanks for feedback everyone!
