### ISSUE TITLE
Insert/Extract Matrix Element

### ISSUE THREAD

**Issue by 3x1t-5tyl3** [Frooxius/NeosPublic#1349]
Matrix Element exists, which allows you to extract an element from a matrix but there's no node that allows you to insert an element into a matrix.
It'd be useful to have both as you wanna read and write from it.

In the same frame *if* this gets added renaming "Matrix Element" to "Extract Matrix Element" and adding the new one as "Insert Matrix Element" (or similar, these are just mock-ups.) Would be useful.

Mock-up below.

![20201117131850_1](https://user-images.githubusercontent.com/61988002/99391153-0b26b600-28da-11eb-88b3-9552fa41fde3.jpg)

**Comment by ProbablePrime** [comment]
It seems like you're trying to use matrices as collections and data storage here. I'd caution you against doing that as matrices aren't really meant for that or at least this is my understanding of them. 

I can see uses for this for mathematical applications of them but wanted to mention the data storage case.

**Comment by Frooxius** [comment]
I'm sorry, but insertion isn't really possible, as element insertion isn't something that matrices can do. They're fixed size two dimensional "tables" of numbers, you can only change the numbers that are already there.

**Comment by 3x1t-5tyl3** [comment]
I've closed the issue given as matrices should be used as datastorage.
