### ISSUE TITLE
User voice range configuration

### ISSUE THREAD

**Issue by ChrisWarner103** [Frooxius/NeosPublic#1351]
Being able to configure user audio range inside your world. That way users can't hear people from far distances. This issue is for what I spoke about in the discord: https://discordapp.com/channels/402159838827905024/477711742001086505/778333498163200031

Also being able to configure a room with a different audio range than the default map scale would be a good feature as well. This is done quite often inside VRC, where you'd have 2 rooms next to each other but you wouldn't be able to hear the users in the other room. But if you're in a different area of the map you'd be able to hear users at the same distance as what those two rooms would correlate to. 
https://discordapp.com/channels/402159838827905024/477711742001086505/778335763971571782

**Comment by Frooxius** [comment]
Added this ability in 2020.11.23.1311!

- Added AvatarAudioConfiguration component (under Users/Common Avatar System/Audio) which provides voice mode configuration if placed within user's hierarchy (based on request by @ChrisWarner103 (DelVR))
-- This allows configuring all audio settings (range, falloff, spatialization...) for Normal, Shout and Broadcast. Mute and Whisper cannot be overriden.
-- All properties are driven locally. By driving the properties on this component you can divergently drive the voice properties of the user
-- Ensure there's only one instance on the avatar, when multiple instances are present, behavior will be undefined.
-- When not present, the default/per-avatar settings are used instead
-- Note that you cannot add this dynamically to the user, it needs to be present before avatar is equipped

To use it use another new feature that was added:

- Added AutoInject reference to CommonAvatarBuilder, which will duplicate target slot and place it on each spawned user
-- It's placed right at the root of the user, at the same level as avatar and body nodes
-- You can use this to place AvatarAudioConfiguration on the users to create custom audio configuration in your worlds, as well as any custom LogiX (e.g. for game worlds)
