### ISSUE TITLE
Unavailable Resource (404 on URL) Results in Infinite Loading

### ISSUE THREAD

**Issue by Enverex** [Frooxius/NeosPublic#1354]
If an asset points to an external resource that isn't available (e.g. would 404 in a browser) Neos will get stuck in an infinite loading state and never complete, slowly and incrementally increasing the asset load count in the bottom left but with no file sizes listed. This will never go away until the objects in the world referencing the unavailable resource are deleted.

![image](https://user-images.githubusercontent.com/958670/99525634-00c7f300-2992-11eb-9b70-44fa102eb927.png)

**Comment by Frooxius** [comment]
Should be fixed in 2020.11.21.1177, thanks!
