### ISSUE TITLE
collider with GrabBlock component will still show red 'grabbable' laser when pointed at

### ISSUE THREAD

**Issue by mralext20** [Frooxius/NeosPublic#1359]
situation: 
i am building a door, with a separate handle. the hierarchy looks like this:

```
Joint
- visual (grab block, collider)
- handle (collider)
```

when pointing the laser at the pain part of the door, the red 'grabbable' laser shows up, even though you cant actually grab it, due to the grabBlock. 

what i think is happening: the new lasers dont check for a grab block, and should be updated to do so.

**Comment by Frooxius** [comment]
Should be fixed in 2020.11.21.1177, thanks!
