### ISSUE TITLE
GetObjectRoot logix node has ambigous edge cases

### ISSUE THREAD

**Issue by zkxs** [Frooxius/NeosPublic#1363]
The way the GetObjectRoot logix node handles certain edge cases can make it very difficult to detect if a slot has an ObjectRoot or not. Here are the cases:

| Case      | Has Object Root | Returns           | Description |
| --------- | --------------- | ----------------- | ----------- |
| Normal    | Yes             | The object's root | The input slot has an ObjectRoot somewhere higher up in the slot hierarchy |
| Self Root | Yes             | Input slot        | The input slot itself has an ObjectRoot component |
| No Root   | No              | Input slot        | An ObjectRoot could be not found |
| null      | N/A             | `null`            | The input slot was null |

As shown above, when GetObjectRoot returns the input slot it is ambiguous whether or not that slot has an ObjectRoot component. This can be a problem, as if you have logix that should only be run on object roots there is currently no built-in way of detecting if an arbitrary slot actually has an ObjectRoot or not.

I see two ways this can be made unambiguous:
1. Modify GetObjectRoot to return `null` if no object root can be found. This may break existing logix that relies on the current behavior, but in my opinion it makes the node behave in a more sensible way.
2. Add a new HasObjectRoot node that returns True/False if the input slot has an object root component or not.

There is a workaround for this issue, but it is rather dirty. Here's the implementation in pseudocode:
```python
def HasObjectRoot(slot, emptySlotTemplate):
    if GetObjectRoot(slot) is null:
        return False
    else:
        if GetObjectRoot(slot) != slot:
            return True # not ambiguous
        else:
            emptySlot = DuplicateSlot(emptySlotTemplate)
            ParentSlot(emptyTemplateSlot, slot)
            if GetObjectRoot(emptySlot) == emptySlot:
                # this happens when there is no object root
                DeleteSlot(emptySlot)
                return False
            else:
                # this happens when slot is an object root
                DeleteSlot(emptySlot)
                return True
```

And again in logix:
![logix-image](https://user-images.githubusercontent.com/1807509/99628191-48369980-29fb-11eb-8f2c-366925983554.jpg)

**Comment by Frooxius** [comment]
This is expected behavior, the node gives you the root of the object. The root of the object is either the nearest Slot with ObjectRoot on it, or it's the object itself if it's not present. Distinguishing whether ObjectRoot is present or not is not its function and it's not something you generally should care about.

The behavior won't get changed, as that would break huge amounts of existing behaviors in Neos and it's not how the node is supposed to work.

Adding way to check if there's object root component is possible, but unlikely to be added as separate node, that would fall under component access. What is your usecase where would you need to know if the ObjectRoot component is present or not? If feels a bit like it's misusing the system for something it wasn't made for.

**Comment by zkxs** [comment]
You raise a very good point that component access is the right way to go about this, so I'll close the issue. Thanks for your response!

As far as use cases go, my general one is detecting if an arbitrary slot has a properly configured ObjectRoot. In a perfect world this wouldn't be a concern, but unfortunately many creators don't properly set object roots in their objects.

For example, imagine some sort of alignment tool made with a RawDataTooltip that takes the object root of picked items and snaps their rotation to the nearest 90° increment. A missing object root is problematic here. For example, a Get Object Root node has no ObjectRoot, so the alignment tool would end up applying the transform to the visual instead of the entire object.
