### ISSUE TITLE
Suggestion: Rename Full body Calibrator

### ISSUE THREAD

**Issue by DeliriousJax** [Frooxius/NeosPublic#1367]
There's minor confusion at times over whether the full body calibrator works for non full body edits. Since it does have a few important uses for non full body tracking, maybe rename it to something like
"Avatar Calibrator"
"Avatar Fitter"
Or something similar?

**Comment by Frooxius** [comment]
I'm not really sure about this. The language I see predominantly used for people with tracker is "full body" (e.g. "Does Neos support full body?"), so the tool is named like that since it seems what most people will search for. The other options might make them think it's something else.

**Comment by DeliriousJax** [comment]
Hmm. Maybe a meet in the middle?
"Avatar and fully body calibrator" or something along those lines?

**Comment by Frooxius** [comment]
That might work, not sure if it won't be too long, but we can try.

**Comment by TehTurk** [comment]
I'd like to chime in if that's okay,  but the suggestion doesn't make much sense, Fullbody Calibrator Right now can only adjust Height Compensation if you have no tracking, and people really won't know Height Compensation untill they are told or find out more about it, so I don't know if that information would be critical to present.

**Comment by Frooxius** [comment]
Renamed in 2020.11.21.1177, thanks!
