### ISSUE TITLE
Changing languages breaks language selection screen in MTC

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#1368]
Initially reported by Aegis_Wolf#5227
Steps to replicate (so far 100% replication using this method):
- Starting on English, during the new user intro tutorial, select every language in the local home from left to right, and top to bottom, set language to English before proceeding
- Continue through the tutorial without creating an account and make a private MTC session
- Finish the tutorial to re-enable your dash
- Select every language from left to right, top to bottom again
- The UI will stop responding/break once Korean is selected
- The languages will continue to be changed properly when their buttons are pressed, but the UI won't visually respond to the presses
- If you continue pressing enough buttons, eventually the screen will corrupt and turn pink like the material is missing/null
![image](https://user-images.githubusercontent.com/54213390/99846741-cb570d00-2b2b-11eb-905f-51abc3530f8f.png)
A video depicting the replication steps can be found here:
https://cdn.discordapp.com/attachments/439422161657135106/779446692960534628/2020-11-20_12-39-54.mp4

Logs contain no meaningful information:
[SHIFTYWINDOWS - 2020.11.18.630 - 2020-11-20 12_38_01.log](https://github.com/Frooxius/NeosPublic/files/5575974/SHIFTYWINDOWS.-.2020.11.18.630.-.2020-11-20.12_38_01.log)
[Player.log](https://github.com/Frooxius/NeosPublic/files/5575976/Player.log)

**Comment by Frooxius** [comment]
Does this happen only in the MTC?

**Comment by shiftyscales** [comment]
From testing it so far, yes.

I couldn't replicate it just by switching languages in the local home alone.

Something about that specific sequence seems to reliably break it though- switch through every language in the local home, then switch through every language again in the MTC.

**Comment by Frooxius** [comment]
Hmm I'm having a bit of a problem replicating this on my end: https://www.youtube.com/watch?v=pu6PcsxgeDM&feature=youtu.be

Can you give it a test with the next build once it releases and see if the issue still persists?

**Comment by shiftyscales** [comment]
I will definitely try it out, yeah. 👍

**Comment by shiftyscales** [comment]
I can confirm this issue still occurs for me.

To clarify the exact replication steps since you appeared to be doing something different in the video you posted:
- In your local home when you are first prompted to select your language- start on English, click every language left to right, and top to bottom in order. E.g. Czech, German, English, etc. all the way down to Chinese (Traditional.)
- Set the language back to English before proceeding
- Go through the rest of the tutorial in the local home, and MTC until you can access your menu again
- Go to the language settings again and once more select every language left to right top to bottom- when it reaches Korean, the UI will break and stop responding
- The bright pink only occurs if you continue to then click on various random languages after the UI has already broken

In the process of this, **I discovered another way to break the settings UI** on entry into the MTC.
- Start Neos with your language set to Chinese (Traditional)
- Cycle through every language starting from Czech left to right, top to bottom, ending on Chinese (Traditional) again
- Proceed through the local home portion of the tutorial
- Finish the MTC panel tutorial and try to access your settings
- The settings page will start completely broken and can not be interacted with
![image](https://user-images.githubusercontent.com/54213390/100035965-1e42f580-2db4-11eb-9a15-3a7ec1473663.png)

**Comment by Frooxius** [comment]
Thanks for the replication steps, I was able to instrument the code and drill down into this, it should be fixed in 2020.12.30.1285 now! It probably manifested itself in lots of different ways, causing the UI to freeze, so hopefully this will improve its stability significantly.
