### ISSUE TITLE
Imperial example in tutorial is not ordered correctly

### ISSUE THREAD

**Issue by Hayden-da-Serg** [Frooxius/NeosPublic#1369]
While experiencing a database corruption, I decided to finally see what the tutorial was like, but then I found that the Imperial height example is not correct, upon placing the characters shown, it automatically corrected to a different height.

In the image below you can see that the order the Quantity editor accepts is reversed from the example.

![image](https://user-images.githubusercontent.com/25524760/99853016-6c02f800-2b3f-11eb-9cd8-299de0279325.png)

**Comment by ProbablePrime** [comment]
For additional clarity The example should be `6' 1"`

This is a locale file issue which can technically be patched by us community members here: https://github.com/Frooxius/NeosLocale/blob/master/en.json#L1078

**Comment by Frooxius** [comment]
I'm sorry, I always get those two confused. Yeah you can submit a pull request, otherwise I'll just fix it up tomorrow.

**Comment by Hayden-da-Serg** [comment]
Unfortunately, I have absolutely no idea how pull requests work, would someone be able to fix this?

**Comment by ProbablePrime** [comment]
I'll sort it shortly.

**Comment by ProbablePrime** [comment]
https://github.com/Frooxius/NeosLocale/pull/159

**Comment by Frooxius** [comment]
Thank you for the fix, merged in 2020.11.21.1177!
