### ISSUE TITLE
Component Clone Tip when cloning multiple components does not update references between components

### ISSUE THREAD

**Issue by mralext20** [Frooxius/NeosPublic#1373]
situation: i have several components i am adding to multiple slots, and wanted to make my life easier by using the component clone tip, so i could setup the logic once, then clone it into where it'll get used. so, i setup a component clone tip as such: 
![cctip](https://user-images.githubusercontent.com/4016295/99891053-3a0e9600-2c12-11eb-9d60-a76c0bacc1f3.png)

however, when i actually use the CCtip to put the components onto another slot, the targets of the components are still on the cctip's template, like this: 

![cctactual](https://user-images.githubusercontent.com/4016295/99891109-d5077000-2c12-11eb-9828-2bce607c7e68.png)

can the CCtip be updated to maintain references between components on its template?

**Comment by TehTurk** [comment]
I'd love this, when I made the Component Clone History Tip I ran into a similar issue. But I understand why this also might not be the case because maybe you want it save the references you make.

**Comment by shiftyscales** [comment]
I feel like a better solution might be in having a means to copy groups of components?

As is, there are some references that do get updated, e.g. if you have something that's driving the active state of the slot, when you apply the component to the new slot, it will update the reference to the active state of the slot you place it on.

**Comment by mralext20** [comment]
I'd hope it would fun too similarly to how duplicating a slot works now: references part of the hierarchy are maintained within the copy, while external references (e.g. to assets) still have the same reference.

**Comment by TehTurk** [comment]
@shiftyscales That'd be actually better. Maybe say taking the slot and then hitting copy while in Hand? I wouldn't be surprised if it'd be doable to copy a ComponentRoot Internal from a Slot.

**Comment by Frooxius** [comment]
Fixed in 2020.11.25.1148!
