### ISSUE TITLE
UserRespawn node request

### ISSUE THREAD

**Issue by ChrisWarner103** [Frooxius/NeosPublic#1374]
So there is UserJoined and UserLeft which obviously pluses when a user does them things, but there is no way of tracking when a user respawns. Currently, right now I'm having to do really hacky methods to detect that someone has respawned and it isn't always the best thing, so having a node that allows this would be great

**Comment by mralext20** [comment]
see also : #769

**Comment by ChrisWarner103** [comment]
Ahh didn't realize that was a thing

**Comment by TehTurk** [comment]
This has been requested before even by me I think. Lemme see id I can find the issue. If not it must have been the discord. But the main issue with this is that this is not realize too easy as there's nothing really internally to show that a user needs to be remade/rebuilt unless that mechanism of when that occurs is exposed.

**Comment by shiftyscales** [comment]
As was noted by @Frooxius on #769, there isn't such a thing as a 'respawn' event currently (and thus no event to fire for that specific thing). On that issue, he proposed the idea of a 'OnSpawn' node that would fire anytime a user spawns (initial join and respawns.)

**Comment by TehTurk** [comment]
I think that'd work then, but my question is would an OnSpawn trigger with a UserJoin? Because I figure internally both use the same event no?

**Comment by ProbablePrime** [comment]
Join is most likely the connection opening.
Spawn would most likely be the avatar and user components being created.

**Comment by Frooxius** [comment]
This could be added, but one question is whether you need actual spawn event (the user is (re)created in the world) or if you consider the user falling out of the map also "respawning" that you'd need to be informed about? 

If you need the latter, then it's a bit more complex, as the user just gets teleported. But if it's just when they get destroyed and are rebuilt, then it's much easier to add.

**Comment by shadowpanther** [comment]
At least the recreation of the user root (force respawn) is needed to make user managers work properly without scanning the root every several seconds (like the Janitor bot system does).

**Comment by TehTurk** [comment]
I think the former would be plenty fine, but for the later, hmm don't the Teleport have events built in in some form? There needs to be something to "OutOfBounds" -> ReAdjust

**Comment by Frooxius** [comment]
Ok, I've reworked Neos' internal system a bit, so now OnUserJoin is just for the network join and then OnUserSpawn fires anytime the user needs to be spawned and added appropriate node. Available in 2020.11.23.1311, thanks!
