### ISSUE TITLE
Baked reflection probes sometimes render users

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#1377]
Exact replication steps are yet to be determined, but it appears that sometimes users will be visible inside of reflection probes that are baked.

It appears a potential factor is that multiple users are inside of the session. It also seems from the times it has happened so far that the issue is more likely to occur if a non-host bakes the reflection probe.

Interestingly- it appears that the user might only be visible on certain sides of the cubemap, e.g. in the sample I provide below, June can be seen on at least three sides of the cubemap, but not every side. There is at least one side where he's not visible suggesting he might have been culled properly on one face, but not all of them.

A sample cubemap demonstrating this issue can be seen at: neosdb:///7f65317e6e1f9621ac0e4b3356e7a5f7d724efb787cc4bad214f2b228e6f8dba

**Comment by shiftyscales** [comment]
It appears gizmos can also sometimes render in the cubemap too. The rendering layers #1277 should be a definititve fix for this issue- I'm not certain if this behavior is something that can be efficiently mitigated otherwise in the meantime?

neosdb:///90d7722bbfba42a114e206a98b21070a1810cb38cc2532ee03292b2faa9e42ff

**Comment by Frooxius** [comment]
Does this issue persist if you switch the TimeSlicing mode to NoTimeSlicing? I think what might be happening is that the probe is taking a bit longer to render and something else resets the masks of the objects in the scene before it finishes.

**Comment by Frooxius** [comment]
Should be fixed in 2020.11.23.1311, reopen if it still occurs!
