### ISSUE TITLE
Recording a voice message should attenuate voices like the Whisper Bubble does

### ISSUE THREAD

**Issue by Hayden-da-Serg** [Frooxius/NeosPublic#1379]
Sometimes when I go to record a voice message, some people in the session are still a little too loud, which can cause me to stutter or trip over words, it can also cause the microphone to pick up other user's voices on headsets like the Index, Quest or Reverb G2.

As the title says, I suggest that when a voice message is being recorded that all user voices in the session are attenuated (I have no idea if this is the right term) to be quieter similar to how the Whisper Bubble already does.

**Comment by Frooxius** [comment]
Added attenuation in 2020.11.23.1311, thanks!
