### ISSUE TITLE
Logix tip issues with TooltipMultiplexer in screen mode

### ISSUE THREAD

**Issue by Hayden-da-Serg** [Frooxius/NeosPublic#1382]
While interacting with the Logix panel in Screen mode using the Logix tip through a ToolTipMultiplexer, Logix nodes are spawned in front of the panel as seen in the video below, with the increasingly common use of TooltipMultiplexers this can get *very* annoying when working in screen mode.

https://cdn.discordapp.com/attachments/439422161657135106/780571667939852319/2020-11-23_16-09-26.mp4

**Comment by Frooxius** [comment]
I'm sorry, but desktop is currently not officially supported so this won't get addressed.
