### ISSUE TITLE
Avatar creator eye for desktop

### ISSUE THREAD

**Issue by Earthmark** [Frooxius/NeosPublic#1385]
If possible can the avatar creator get a visualization for where the desktop mode camera would be, I often accidently put it inside hair because the main eyes are clear, but the desktop is not.

**Comment by Frooxius** [comment]
Sorry, desktop is not officially supported, so this won't get implemented, as this is just result of the hacky nature of current desktop mode. The proper desktop mode will use the same subsystems as VR avoid this altogether.
