### ISSUE TITLE
Adding “Slot” property to Dynamic Variable component

### ISSUE THREAD

**Issue by InnocentThief** [Frooxius/NeosPublic#1386]
I always use a hierarchical structure in the world and/or for individual areas.

Example:
Root
-World
--Puzzle 1
---Logix
---Visual
---Materials
---etc.
--Puzzle 2
---Logix
---...
...

Under "Logix"  I usually have a container for variables (incl. Dynamic Variables) and for the actual functions.
The biggest problem with this approach is, that I can’t use (with components) the Dynamic Variables defined inside “Logix” when I’m inside “Visual” because they are – of course – not in one of the parent nodes.

The "normal" Dynamic Variable Logix node allows to define a Slot on which to search for the Dynamic Variable. It would be great to have such a "Slot" property on the component too.

**Comment by Frooxius** [comment]
I'm sorry, but this won't get added, as it goes against the design of the system. Dynamic variables bind themselves to particular hierarchy, so they can be linked and unlinked very efficiently, adding this would break that efficiency.

The system is designed so you don't really need to care where exactly they are in the hierarchy as long as they're under the same variable space. You just need to structure your system accordingly.
