### ISSUE TITLE
Quikwrite text input mode, stick/touchpad and "maestro" variation

### ISSUE THREAD

**Issue by TiagoTiago** [Frooxius/NeosPublic#1387]
Demonstration of stick-based implementation: https://www.youtube.com/watch?v=hDDqO8Q1H88

The general idea is there is a pie menu where you pick a character via a combination of the direction you enter the pie menu plus the direction you return to the center from the pie menu (with no need to press any buttons for each key); the original layout has 5 "keys" per entry direction on the corners and 3 on the sides, but I don't see why you couldn't use all 8 directions if there is need for more keys, and of course, there could also be one or more "shift" keys to switch to another layout to reach less common keys.

The stick input method can easily be understood with the demonstration video above (touchpad would be similar); as for the "maestro" mode, I just mean the same thing but using hand pointing direction instead of the stick, I call it "maestro" because the motion is sorta like you're conducting an orchestra.

Here're a couple blog entries by the guy from the video above about this entry method:

http://doc-ok.org/?p=956
http://doc-ok.org/?p=932

And here the page of the original concept:

https://mrl.cs.nyu.edu/projects/quikwriting/

ps: Looks like the original concept is patented by the New York University but can be licensed; I'm not a lawyer, so I dunno if there would be some way it could be modified enough to not require licensing without sacrificing any important aspect, or even if there might be a way to distribute it while not meeting the classification of "commercial use" they mention in the page to avoid having to pay a license fee or whatever it's called. I haven't checked the actual patent filing, I wonder if perhaps the patent may be bypassable if you use a two-handed method instead of entry and recenter directions, replacing the entry with the left hand and the recenter with the right hand or vice-versa, or alternatively, a single-handed method using simultaneously the stick and maestro modes, or even a single-handed enhanced maestro mode combining hand pointing and hand motion directions; but again, I'm not a lawyer.

**Comment by Frooxius** [comment]
I'm sorry, but I don't plan on implementing this officially, especially since you mention it's covered by patents and requires licensing. Looking into ways to bypass the patent isn't something I want to get into.

It's relatively esoteric input method so it's better left for implementation by the community (you can create your own keyboards in-game), but it's the user's responsibility to make sure their implementation complies with any of the patents.
