### ISSUE TITLE
Add OnEquip and OnDequip events to RawDataTooltipEvents node

### ISSUE THREAD

**Issue by Hayden-da-Serg** [Frooxius/NeosPublic#1388]
Currently, to get these events we have to use Tooltip Equipped> Updating Relay > Fire on True (or False) and this is pretty messy (not to mention, uses an Updating Relay) to just get an OnEquip or OnDequp event. If these events would be exposed in RawDataTooltipEvents this could help with general flow and help avoid using Updating Relays.

**Comment by Frooxius** [comment]
Added in 2020.11.25.1148!
