### ISSUE TITLE
Enabling/Disabling the HiddenLayer Component does not affect it.

### ISSUE THREAD

**Issue by TehTurk** [Frooxius/NeosPublic#1391]
Was trying to do something with Joris for Hidden Objects and cameras, and found out that
- Enabling/Disabling the HiddenLayer Component does not affect it

Our original goal was to use this as a way to have differently hidden layers show up Hidden/NonHidden Is this possible at all?

**Comment by Frooxius** [comment]
The Enabled state is now respected in 2020.11.25.1148, thanks!
