### ISSUE TITLE
Smooth Lerp of type FloatQ should be called Smooth Slerp

### ISSUE THREAD

**Issue by Hayden-da-Serg** [Frooxius/NeosPublic#1392]
I was looking through some of the components and I noticed that a Smooth Lerp of type FloatQ is actually a Smooth Slerp (has the component name of SmoothSlerp_floatQ), however, the node name doesn't actually signify this, I recommend that the node is renamed to Smooth Slerp as this accurately represents the function the node performs.

**Comment by Frooxius** [comment]
Changed the name in 2020.11.25.1148, it was using the name of the node overload. Thanks for report!
