### ISSUE TITLE
AvatarNameplateVisibilityDriver does not update when reparented from non-avatar slot. 

### ISSUE THREAD

**Issue by Aerizeon** [Frooxius/NeosPublic#1401]
While working on my badge injector tool, and attempting to bring it into compliance, I noticed that copying a template containing the AvatarNameplateVisibilityDriver to an active avatar did not result in the driver updating the state of the driven element. 

The driven element will instead remain false until the avatar is reloaded - this makes it difficult to provide a good user experience.

**Comment by Aerizeon** [comment]
After a bit more inspection, it seems that this only occurs using LogiX DuplicateSlot/SetParent - Duplicating it manually in the inspector, and reparenting it works as expected.

Attached is a screenshot of a basic test setup that I'm using - It simply takes the "VisibilityDriver" slot, and duplicates it onto the nearest user's head. The "VisiblityDriver" slot has the AvatarNameplateVisibilityDriver component on it, and "VisibilityTarget" is having its Active state driven by it.

As you can see in the inspector on the left, the slots have been duplicated onto my avatar, however AvatarNameplateVisibilityDriver is still driving the Active state to false.

![20201126133406_1](https://user-images.githubusercontent.com/6015890/100383871-b4f9f700-2fec-11eb-8c13-027571996a8b.jpg)

**Comment by Frooxius** [comment]
Can you check if it's fixed in 2020.11.27.104? I made some changes to how it updates, but I'm not sure if it helps with this issue or not.

**Comment by Aerizeon** [comment]
It appears to work properly now, thanks!
