### ISSUE TITLE
Add read only Voice Mode enum to Avatar Audio Output Manager for avatar based effects based on VoiceMode

### ISSUE THREAD

**Issue by mralext20** [Frooxius/NeosPublic#1405]
situation: i wanna have effects on my avatar based on weather i am in shout, broadcast, muted, whisper, etc

*right now* i can do fun analysis of the Audio Output (volume level, fall off range, etc) to figure out what voice mode i'm in, but this is flaky, and easy to break / fails easily. 

some potential solution: 

add a read only enum to the AvatarAudioOutputManager, to see what the current voice mode is. 
add a (optional) drive target for a VoiceMode Field, for reading from
build a new bespoke component, that accepts a user and outputs their current voice mode (security?)

**Comment by RaithSphere** [comment]
I did mention something like this to Froox recently about maybe exposing that or adding a logix node just to be able to show the current voice mod of the user, I have a waveform that's used on my avatar and i was looking it being different colours depending on what my voice setting was

**Comment by Frooxius** [comment]
This output doesn't belong to AvatarAudioOutputManager. I've added it as a node instead which lets you query user's active voice mode in 2020.11.29.1371
