### ISSUE TITLE
AvatarNameTagVisibilityDriver prevents from seeing the Dequipped Label on AvatarNameTagManager

### ISSUE THREAD

**Issue by TehTurk** [Frooxius/NeosPublic#1406]
Due to the Behavior of how AvatarNameTagVisibilityDriver(ANTVD) works, it requires for it to be under a user to ever be enabled state wise. Making the De-equipped Label of AvatarNameTagManager completely pointless. These would be user as ways to indicate users that an avatar is empty. If possible can I ask that the behavior be turned into a situation where if it doesn't have a User, it just defaults to on? It makes customizing and adjusting custom nametags alot easier as well. 

Situation:
- User has Avatar with adjustments to Nametag
- Nametag isn't visible because it is not under a user
- I can't see modifications or changes I do to the nametag, or even if an avatar is a person or a dequipped avatar

**Comment by Frooxius** [comment]
I'm working on fixing this now, but for the next time use correct names of the components please. The name is AvatarNameplateVisibilityDriver not AvatarNameTagVisibilityDriver . This is not the first time it happened and it always takes me a while of searching for it, until I find that you provided wrong name in the report.

**Comment by TehTurk** [comment]
Oops! I'm so sorry Froox!!! ^^; It's a bit of a new one but then the other Components are named AvatarNameTagAssigner(I get the Difference, NamePlate is for the Object, NameTag is for the String) so that's where my context came from originally.

**Comment by Frooxius** [comment]
Changed this in 2020.11.29.1371, when dequipped the nameplate will now be visible!
