### ISSUE TITLE
Gizmos sometimes cause FPS drop

### ISSUE THREAD

**Issue by shadowpanther** [Frooxius/NeosPublic#1407]
Sometimes when there's a gizmo in the world, and you are far from it, your FPS would drop dramatically. Deselecting all to make this far gizmo disappear fixes the performance.
First noticed at Cats CJ, so this issue might be about a week old.

**Comment by Frooxius** [comment]
Which gizmos are we talking about? Slot selection gizmo? This might be normal, as they show things like the object's full bounds, which might be pretty heavy operation depending on the scenario.

**Comment by shadowpanther** [comment]
Selection ones, yes. The FPS drop is big (40 down to about 10-15) and it only happens if you are far away from the gizmo.

**Comment by Frooxius** [comment]
Does this happen in empty world? It might be the gizmo colliders interacting with the environment badly in the physics system.

**Comment by shadowpanther** [comment]
Looks like you are right, I found an active MeshCollider that was causing this. Still probably something could be done to not cause this?

**Comment by Frooxius** [comment]
Ah, I strongly discourage use of active MeshColliders, they're going to be an enormous performance sink. There's not much that can be done about that, other than just replacing them with primitive colliders.
