### ISSUE TITLE
Some images are broken (500 Internal Server Error) after wiki upgrade

### ISSUE THREAD

**Issue by Aerizeon** [Frooxius/NeosPublic#1414]
After the upgrade in #1204, some images no longer load, and return a 500 Internal Server Error instead

Example Files:
https://wiki.neos.com/File:SceneInspector.png
https://wiki.neos.com/File:CreateDynamicVariable1.png
https://wiki.neos.com/File:JointComponent.png

If necessary, these images can be re-uploaded, however it would be nice if it was easily fixable through other means :3

**Comment by JohannAmos** [comment]
Thank you very much @Aerizeon and @shiftyscales for bringing this Neos Wiki problem to our attention. Broken images folder permissions after recent Wiki upgrade 1.32 > 1.35 are now fixed (chmod 0755).

**Comment by shiftyscales** [comment]
Thanks for looking into it, and the prompt response, @JohannAmos.
