### ISSUE TITLE
Reflection Probe Wizard/Editor's Title is "Cubemap Creator"

### ISSUE THREAD

**Issue by ProbablePrime** [Frooxius/NeosPublic#1415]
1. Equip DevTooltip
1. Create New
1. Editor
1. Reflection Probes
1. Observe the title of the spawned dialog is "Cubemap Creator"

Whilst we're at it the Reflection Probes Item within the create new menu isn't that clear what its for. Perhaps "Reflection Probe Wizard" or similar would be better

**Comment by Frooxius** [comment]
Fixed in 2020.11.29.1371, thanks!
