### ISSUE TITLE
Tiny badges

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#1416]
Exact replication steps are currently unknown.

Something is causing badges to appear tiny for some users, I suspect it's related to the AvatarNameplateVisibilityDriver.

Some observations:
- The host (Tatsu) started the session with his nameplates set to Non-contacts, and kept it that way throughout prior to the issue being observed
- The issue seems to affect certain users but not all/not consistently
- When my badges were selected, Tatsu observed the gizmo's location was at the origin of my user root, for everyone else in the session the gizmo was in the proper place
- The scale of the slots of the individual badges were quite small ~0.007

I'll update if I discover any additional information related to this issue.

**Comment by shiftyscales** [comment]
An observation made by Ryuvi- it appears that this issue only affects default nameplates/badges. If a user is using a custom nameplate/custom badge setup, the issue does not seem to affect them.

**Comment by Frooxius** [comment]
Should be fixed in 2020.12.1.27, please reopen if still occurs!

**Comment by ukilop** [comment]
I saw a recent occurrence of this as well,
![2020-12-02 17 31 20](https://user-images.githubusercontent.com/1341270/100960087-35d15b00-34e5-11eb-939e-e64ea6700d7c.jpg)
3 of us saw gourry who freshly joined with tiny badges, and this wasn't them in the middle of joining they ran up to us first
but the host (3x1t) didn't even see their nameplate yet,
heard 3x1t say "oh now I see them" I look back at gourry and badges are fixed

maybe it fixed itself when gourry finished loading? not sure

**Comment by Frooxius** [comment]
Ok I'm pretty sure it's fixed in 2020.12.5.585 now, I mistakenly only made the Tween finish on Disable of the component itself, but not when the whole hierarchy is deactivated. Thanks!
