### ISSUE TITLE
Rig animation recorder - the microphone but for movement

### ISSUE THREAD

**Issue by Earthmark** [Frooxius/NeosPublic#1420]
Like the microphone tool, but for a rig instead.

With the number of full body users that have a large number of trackers, we have a good availability of motion capture data, however no way to efficiently capture it. 

It seems animations can be created and imported against a rig as well, which makes for a great npc-ish experience when paired with a viseme driver and the microphone tool. However systems to record animations are currently quite cumbersome, and don't integrate with the currently playback system. They often either create a vast amount of dynamic variables, slots, massive strings, or some combination of those.

If possible, can a tool be added like the microphone, however it records an animation of the movements of a targeted rig so the animation can be efficiently stored and played back at a later time?

**Comment by H3BO3** [comment]
Likely a derivative of #48 . I suggest posting a reply to that instead.

**Comment by Earthmark** [comment]
I understood #48 as sequencing and blending animations, instead of recording a single static animation. 

With how #48 is worded it also applies to meeting animations, voice cues, and other events.
So I understood this is related to #48 in that this would allow a primitive of #48 to be created in engine, like the microphone tool which fits the same niche as a primitive of #48

**Comment by H3BO3** [comment]
Hmm, I see. It's just possible that this issue could be delayed until Froox generalizes avatar animations, which would likely need 48 as a prerequisite.

**Comment by jeanahelver** [comment]
part of the community is working on animation recording tool as a plugin, incited by one of medra's project.
[wip recordingTool plugin](https://github.com/jeanahelver/neosPlugins/tree/main/recordingTool)
not yet fully working.

**Comment by Frooxius** [comment]
We already have a major topic for animations here: https://github.com/Frooxius/NeosPublic/issues/48

I don't plan on making one specifically for the rig, since that'll be generally handled by the system above. There's nothing that can be really shared with the microphone implementation, they're completely different systems, utilizing different subsystems.
