### ISSUE TITLE
Hide/remove session joiner from local home during tutorial

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#1424]
Reportedly, new users have accidentally joined on active sessions prior to completing the tutorial (as mentioned in #1408). Removal of the session joiner, either outright, or hiding it during the tutorial will prevent this scenario.

**Comment by Frooxius** [comment]
Made the change in 2020.12.2.583! The session joiner is still there, but it'll have no orbs during this. Thanks!
