### ISSUE TITLE
[Bug] Attempting to bake inactive reflection probes with the BakeReflectionProbes node causes problems

### ISSUE THREAD

**Issue by Zyzyl** [Frooxius/NeosPublic#1425]
Tested by opening a new (empty) world, spawning 2-3 reflection probes (different slots) under the same parent slot. Parent slot was provided as the Root input to the BakeReflectionProbes node.

Baking progress halts completely when it reaches a reflection probe on an inactive slot - output impulses stop and the inactive + later probes do not receive new cubemaps. True/False input at BakeInactive seems to make no difference. If baking fails in this way, the BakeReflectionProbes node cannot be reactivated by further impulses at Bake. Additionally the reflection probe whose slot was inactive cannot be baked using the button in the inspector (whether or not its slot is active when attempting to do so).

**Comment by Frooxius** [comment]
Should be fixed in 2020.12.2.583, thanks!
