### ISSUE TITLE
The Quest 2's Thumb Rest Sensor doesn't communicate with the Touch Controller Node

### ISSUE THREAD

**Issue by Zandario** [Frooxius/NeosPublic#1432]
As the title suggests, I've done a lot of experimentation with the controller nodes using the Quest 2's controllers, they have a little capacitive touch sensor for where you naturally rest your thumb. For further clarification for how SteamVR breaks it even more, I am not using that, I can actively move my thumbs using it but no response is given from the node, so my best guess is that maybe there is a different name for the sensor in the backend or something? I'm not really sure myself but here's a quick video showcasing it: https://youtu.be/diClI0JN5cs

**Comment by DovahDoVolom** [comment]
This through using a link cable launching with the oculus runtime?

**Comment by Frooxius** [comment]
Unfortunately Thumb Rest sensor is only mappable for the CV1 controllers through the native Oculus SDK, which Neos supports. Oculus doesn't expose its state in any of the newer controllers, so there's not really anything we can do on our end to support it, I'm sorry.

You could try reaching out to Oculus, if enough people contact them about this they might implement the support, but I wouldn't count on it.

**Comment by Zandario** [comment]
Damn that sucks, I'll have to figure out some different means for my projects then
