### ISSUE TITLE
Unlock dashboard if a world aside from the initial MTC tutorial is opened

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#1436]
An issue that's coming up on an increasing number of occasions is that users by various means are seemingly managing to break out of the MTC early leaving them stranded in other worlds without the capability to use their dashboard at all as it is locked down by the MTC tutorial panel, and isn't unlocked because they don't finish the tutorial properly prior to leaving.

Turk had reported a couple of additional cases today, one screen mode (likely just flew through the barrier since there is nothing keeping a screen mode user contained, and one Index (it is not known how they managed to skip past the barrier.)

There are a couple of potential approaches/tweaks that can be made which include off of the top of my head:

- Hardening up the mechanisms to ensure a player remains in the valid tutorial region e.g. teleporting the player back to the spawn if their coordinates exceed a set distance from the middle of the room
- Triggering the dashboard to unlock when entering the teleporter as a failsafe/backup in addition to when reaching the end of the MTC tutorial panel

**Comment by alexderpyfox** [comment]
For me a new user has tracking issues so it made him fly quickly outside the area because of lost tracking and that pretty much can have caused it other users might also be using playspace mover when trying to grab the ball with both hands which can cause them to get out of the barrier

**Comment by alexderpyfox** [comment]
Someone just told me it happens when you skip the beginner dash screen before the mtc world even so that might be the cause of it 🤔

**Comment by Frooxius** [comment]
How are people skipping the beginner setup? It's setup so it locks you out precisely so you can't skip it, so that's something that should be patched too. I can add a condition that re-activates the dash though if a different world is opened, but ideally we should just fix the actual bug with it not activating, rather than doing ad-hoc fixes to mitigate the result of the bug.

**Comment by shiftyscales** [comment]
Ryuvi has pushed a change to the MTC to strengthen the barrier (it will teleport the player back in bounds via a fade to black), and the dashboard reactivation Logix was tweaked to help ensure it fires when necessary. This should hopefully resolve some of these issues. I'll let you know if I hear of any additional cases.

There is however still #1408 which I'm trying to find a replication case for, as well as another apparent issue where the locked dash remains locked between restarts as per the logs I sent you privately, @Frooxius.
