### ISSUE TITLE
Enable lbry.tv support for youtube-dl

### ISSUE THREAD

**Issue by H3BO3** [Frooxius/NeosPublic#1443]
Madiator#2011 has requested support for loading videos from the https://lbry.tv/ site. It appears youtube-dl supports it already, and it just needs to be enabled.

**Comment by Frooxius** [comment]
We're not using youtube-dl anymore due to problems (particularly breaking YouTube support), but a fork youtube-dlc. I've tested it, but unfortunately the latest available version doesn't seem to support lbry.tv

**Comment by kodxana** [comment]
They should release it soon https://github.com/blackjack4494/yt-dlc/commit/70c5802b5d651f840b6e94fb0cdc1105d5e048e6

**Comment by Frooxius** [comment]
I've added it to the list in 2020.12.8.638, now just waiting on the updated version of youtube-dlc

**Comment by shiftyscales** [comment]
> 
> 
> I've added it to the list in 2020.12.8.638, now just waiting on the updated version of youtube-dlc

It appears that it's not working properly. It appears that youtube-dl isn't properly collecting a list of available formats from any of the available URLs that lbry provides.
```
1:09:16 PM.920 (396 FPS)	Importing files with Asset Class Video:
https://lbry.tv/@MovieGasm:d/raya-and-the-last-dragon-trailer-2-2021:8
1:09:20 PM.578 (387 FPS)	Available formats for https://lbry.tv/@MovieGasm:d/raya-and-the-last-dragon-trailer-2-2021:8:

1:09:27 PM.486 (367 FPS)	Importing files with Asset Class Unknown:
https://open.lbry.com/@MovieGasm:d/raya-and-the-last-dragon-trailer-2-2021:8
1:09:38 PM.742 (368 FPS)	Importing files with Asset Class Unknown:
lbry://@MovieGasm#d/raya-and-the-last-dragon-trailer-2-2021#8
1:09:43 PM.230 (386 FPS)	Importing files with Asset Class Video:
https://lbry.tv/$/download/raya-and-the-last-dragon-trailer-2-2021/84cae23fcbb9fc33f599ddf9e20a31f9ba830353
1:09:46 PM.860 (397 FPS)	Available formats for https://lbry.tv/$/download/raya-and-the-last-dragon-trailer-2-2021/84cae23fcbb9fc33f599ddf9e20a31f9ba830353:
```

**Comment by Frooxius** [comment]
Looks like Lbry support in youtube-dl doesn't populate the formats list and only returns a single URL instead, which Neos ignored. I've tweaked the code to use that URL if no formats are reported and I can confirm that it works now, coming in the next build.

**Comment by Frooxius** [comment]
Should work as of 2021.1.29.504 now!
