### ISSUE TITLE
Enum Input Seems cannot use in NodesMenu

### ISSUE THREAD

**Issue by kazu0617** [Frooxius/NeosPublic#1445]
日本語で失礼します。Enum InputをNodeMenuを利用して作成しようとしたところ、正常に作成できず、Inspectorを確認するとEnum Input`1 の表示のみ存在している状態です（バグかなと認識し、Discordに投げましたが特に反応がなかったのでこちらにリポートしました）。

DeepL Translate:
I tried to create an Enum Input using NodeMenu, but it did not work, and when I checked Inspector, only the display of Enum Input`1 existed (I thought it was a bug and threw it to Discord, but there was no response). (Reported here).

![NodeMenu](https://cdn.discordapp.com/attachments/439422161657135106/781790493825695754/unknown.png)
![Inspector](https://cdn.discordapp.com/attachments/490828917553496064/785368939802787860/Photo_in_HeadLess_Session.png)

**Comment by Frooxius** [comment]
Fixed in 2020.12.8.638, thanks for the report!
