### ISSUE TITLE
Ban non-present user from headless client

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#1450]
Requested by Shadow Panther#5154, a means to ban a user not presently in the session from the headless client.

**Comment by Frooxius** [comment]
Added in 2020.12.9.819!

- Added banByName and unbanByName commands to headless, which allow (un)banning user by their Neos username without them having to be present in the session (based on request by @Shadow Panther [RU/EN, UTC+3])
-- Make sure you have the correct name before using this, using their UserID is preferable (you can get it from logs)
- Added banById and unbanById commands to headless with same functionality as above, but using UserID instead (starting with U-)
