### ISSUE TITLE
User voices choppy

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#1453]
A particularly strange issue affecting Zephram/Zephyr.С#3024.

All user audio is choppy for him while everyone else can hear him just fine.

We had tried a number of potential troubleshooting steps including tweaking various Windows audio settings, reinstalling his graphics driver/audio driver, and more.

Inside of Neos, we tested various things. We removed his own user from the exclusion list so he could listen to his own microphone- as expected, it was perfectly clear. We edited the OpusStream for my voice to increase the MinimumBufferDelay, lower the bitrate, and various other changes all to no effect.

Whether he is hosting or a client, the issue persists.

**Comment by Frooxius** [comment]
I've added stream diagnostics in 2020.12.9.819. I'd need to see what the graph and values look like for person who is experiencing the stuttery voice, the graph shows the local state of the voice stream.

Watch out for the red line in particular, that can show if it's often resulting in underrun with samples missing.

You can now also increase the actual size of the buffer, which lets you set the delay to a much larger value (e.g. half a second). Set the buffer size to something large, like 48000 (1 second) or even more and then increase the delay to like 0.5 See if that removes the stutter.

**Comment by shiftyscales** [comment]
Increasing the buffer size does help, and without it, there are significantly more red lines/underruns.

**Comment by shiftyscales** [comment]
A couple of weird observations. While they are looking at my voice stream, the volume/amplitude is consistently very low for them. (Despite all of their volumes being maxed.)

![2020-12-09 15 06 46](https://user-images.githubusercontent.com/54213390/101699597-42e3d200-3a30-11eb-81b6-71ee9a559a18.png)

Additionally, I also noticed that (even locally) an underrun will always happen right at the end of speech.
![2020-12-09 15 10 31](https://user-images.githubusercontent.com/54213390/101699838-d3221700-3a30-11eb-8818-60de3038075d.png)

**Comment by Frooxius** [comment]
Just to note, the white line doesn't show volume, it shows amount of samples in the buffer that's yet to be played. The underrun after end of talk is perfectly normal too, usually the end of voice data doesn't align neatly to the audio buffer size, so it'll be missing a tiny amount of samples after the end of playback.

**Comment by Frooxius** [comment]
I've added more diagnostics in 2020.12.18.33 which track lost packets. Can you check again and see if there's a significant loss occurring?

**Comment by Frooxius** [comment]
I believe this should now be fixed in 2021.1.24.1266! Please reopen if it still occurs.
