### ISSUE TITLE
Generic gamepad/controller logix node 

### ISSUE THREAD

**Issue by alexderpyfox** [Frooxius/NeosPublic#1455]
This would be handy to connect for example the steam controller as a logic node output just like how the current vr controllers got a node that you can connect things to  or any other generic bluetooth controller to things in neosvr I know proper controller support will be a thing in the future but this is handy to have in the meantime and ofc afterwards 😅

**Comment by shiftyscales** [comment]
This issue is already covered by #643. Marking this as a duplicate, but thanks for the suggestion. For this to be implemented, it would require the controller support be implemented first, there isn't any reasonable way to just add something like this in advance of that support.
