### ISSUE TITLE
Contextual Tutorials

### ISSUE THREAD

**Issue by Karel64** [Frooxius/NeosPublic#146]
Planned feature. People tent to skip or not remember the Introductory Tutorial https://github.com/Frooxius/NeosPublic/issues/50 and get lost later on. Partly solved by better UI (Neos Dash, close button...), but still worth to do for specific operations/tools directly at time of use.

**Comment by Simulacron3** [comment]
Great idea. I think just-in-time help/training/education fits modern needs. I'd recommend a graded-depth approach, starting with a very quick reminder sort of message and continuing with progressively more in-depth presentations.

**Comment by Frooxius** [comment]
This was implemented in the 0.8 major update.
