### ISSUE TITLE
Component request - reverse destroy proxy

### ISSUE THREAD

**Issue by Earthmark** [Frooxius/NeosPublic#1465]
Can a component that works like destroy proxy be added, but instead of destroying a target slot if itself is destroyed, it destroys itself if the target is destroyed?

This came up while making asset unloading things, having slots auto destroy under a few conditions was required for extra layers of security.

So far here is what I'm trying to do, and where this component would lie in the pattern.

The goal is an instance is only around while the template manager allows it, under any other condition the instance should be destroyed 

* Template manager that manages the lifetimes of instances
* Target slot where an instance is installed

* If the target is destroyed - no issue, template manager can respawn the target (or not), but the instance isn't leaked.
* Template manager is deleted with events - destroy proxy inside the manager also destroys the instances, instance isn't leaked.
* Template manager is force deleted - **the case this component would rectify** - currently a logix bomb is installed in every instance that observes an updating relay of a slot register, waiting for it to go null which then destroys the instance.

That last case is viable, but may be costly as it currently requires an updating relay and a fire while true to be safe. It's also quite annoying to design as it's very likely to self destruct depending on how it's disarmed.

If this request is added the last bullet point becomes a wrapper slot that is watching the destroy proxy inside the template manager, and if that proxy is destroyed without firing delete events, the instance destroys itself.

**Comment by Frooxius** [comment]
I don't think this would get added, as it's redundant. If you want this behavior, you simply place the DestroyProxy on the other object and link it back to the other one. 

Doing it the other way is a lot more complicated in the engine, because then it would have to "install" something on the target object to know when it gets destroyed, which would pretty much just equate to putting the DestroyProxy on it and setting the target to itself, so you might as well just do that instead.

**Comment by Earthmark** [comment]
Akwardly you've hit the nail on the head, but in this case an issue arises during force deleted when the delete proxy isn't fired correctly.

But I understand the not wanting added subscriptions thing, I'll close this for now then as a no
