### ISSUE TITLE
Improvements to inspector tool

### ISSUE THREAD

**Issue by The-furf-of-July** [Frooxius/NeosPublic#1467]
Please note that this is in regard to the inspector tool, not the dev tool's inspector.

Due to working with the Architect I noticed some behaviors about the hard-coded inspector tooltip component that make it frustrating to use.

The main frustration is that you cannot straighten objects with the tool equipped. If you spawn an inspector, and then try to align it, it opens another inspector in the middle of it.

The solution I came up with was to ignore primary presses if an object is currently held.

I made a RawData tool to fix the issue, and in the process I added a feature I find useful. If you press secondary while holding a single object, instead of inspecting the root, it will inspect the object you're holding. I use this feature of my tool rather frequently, and it's handy for things with UIX that the inspector tip can't currently open inspectors for.

**Comment by Frooxius** [comment]
The inspector tool is old and deprecated, I don't plan on any improvements to it, sorry. I suggest using the Developer Tooltip instead.
