### ISSUE TITLE
Expose more options from Xeixe Toon Shader

### ISSUE THREAD

**Issue by SUPTEC-Gourry** [Frooxius/NeosPublic#1473]
According to the updates from Xeixe, the toon shader support MatCap masks. it's possible to expose the options from the shader so we can use the Matcap and masking features from the latest update from the shader?

**Comment by Frooxius** [comment]
Sorry, the version of Xiexe we're using is modified and I've removed a lot of the extra options to keep the shader simpler, so I don't really plan on adding those, as doing so would increase the maintenance cost and make it harder to transition to a different rendering system in the future.
