### ISSUE TITLE
Request for additional shaders

### ISSUE THREAD

**Issue by emiru-jp** [Frooxius/NeosPublic#1479]
NeosVRにUnity-Chan Toon Shader2.0を追加してほしい
これは多くのVRChatユーザーが望んでいます。

I want NeosVR to add Unity-Chan Toon Shader 2.0.
This is what many VRChat users want.

**Comment by Enverex** [comment]
Here's the licence, it's a little unconventional which may be a sticking point - https://unity-chan.com/contents/guideline_en/

**Comment by emiru-jp** [comment]
キャラクターに関係のないシェーダーは、アセットストアの利用規約に従います。
確認してほしい
https://unity3d.com/jp/legal/as_terms　

Shaders unrelated to the character follow the Asset Store Terms of Service.
I want you to confirm.
https://unity3d.com/jp/legal/as_terms

**Comment by Enverex** [comment]
They don't, not according to the GitHub page anyway. The shader uses the same licence as the model.

とにかくGitHubページによると、そうではありません。 シェーダーはモデルと同じライセンスを使用します。

> 【License】
> Unity-Chan Toon Shader 2.0 is provided under the Unity-Chan License 2.0 terms. Please refer to the following link for information regarding the Unity-Chan License. http://unity-chan.com/contents/guideline_en/

**Comment by Frooxius** [comment]
Hello.

Thank you for the request, but unfortunately we cannot add this shader. We have looked into this particular shader in the past, but its license is not compatible with Neos and our long term usage.

We want to avoid legal risk, usually we only use shaders with a standard permissive license, such as MIT, Unlicense and similar.


こんにちは。

リクエストありがとうございますが、残念ながらこのシェーダーを追加することはできません。 過去にこの特定のシェーダーを調べましたが、そのライセンスはNeosおよび当社の長期使用と互換性がありません。

法的なリスクを回避したいのですが、通常はMIT、Unlicenseなどの標準的なパーミッシブライセンスを持つシェーダーのみを使用します。
