### ISSUE TITLE
RenderTexture stops when I turn off Camera Postprocessing.

### ISSUE THREAD

**Issue by orange3134** [Frooxius/NeosPublic#1482]
Problem
If I turn off Postprocessing on the Camera, the Render Texture will stop displaying in VR.
At this time, the camera image is displayed on the desktop screen instead of the VR image.

Replication method
1.Create new-> Object-> Camera
2. Open Inspector and set Postprocessing to Flase.
3. The RenderTexture display has stopped in VR, and the camera image is displayed on the desktop screen.

Video
https://youtu.be/hjw63pskl90

I made a gadget a few months ago that uses a camera with Postprocessing turned off. I remember that this problem wasn't happening at that time.

**Comment by Aerizeon** [comment]
#1197 refers to this as well.

**Comment by orange3134** [comment]
Oh, I'm sorry for the duplication.
I close this issue.
And mention to #1197
