### ISSUE TITLE
User Permission Level Driver

### ISSUE THREAD

**Issue by LeDrascol** [Frooxius/NeosPublic#1487]
A method of determining and driving other values based on a user's permission level set in the world. Without permission to see other roles, this would only work for active/local user. This could take one or more potential forms:

* User Permission Role: Outputs string for defined user's permission role
* Get World Roles: Outputs list of world's roles, pending array support
* Value Role Override: Same as Value User Override, but for permission role rather than user

**Comment by shiftyscales** [comment]
Sorry. Similar things have been requested before, but were turned down because it is inherently unsafe/insecure. The permissions system needs to operate entirely independently of user-content.

> That won't be added. Such system would be inherently unsafe. The permission system needs to apply restrictions without any involvement from the tools and user content.

~ Frooxius
https://discord.com/channels/402159838827905024/477711742001086505/698901323097047180
