### ISSUE TITLE
Show terminal (like Command Prompt / PowerShell / bash) in-game

### ISSUE THREAD

**Issue by uyjulian** [Frooxius/NeosPublic#1489]
This could be lighter-weight than full screen sharing #144 since you are sending text and not full images, so no video encoder #142 would be needed.

This feature could be useful for the following:
* Quickly like edit a text file in `vim`
* Do some math in `bc`
* Compress a video in `ffmpeg`

all without taking off your headset.  

Others can see what you are typing inside the terminal (but they can't type in it, only you can)

**Comment by Frooxius** [comment]
I'm sorry, I don't have plans to implement anything like this as it's too niche. The desktop access and screen share will allow you to use Powershell/commandline or whatever other tools you want as well as tons of other graphical applications.
