### ISSUE TITLE
Queued packets logix node

### ISSUE THREAD

**Issue by LeDrascol** [Frooxius/NeosPublic#1490]
A major issue many people experience is queued packets, wondering if they're experiencing it, and how bad it is. There's already nodes for other performance statistics like FPS and ping, but not queueing. Currently, users must either rely on the difficult to read debug text driver, or use a parsed form of it for this information.

This could be solved by adding a node that outputs the queued packet statistics for a given user.

**Comment by TehTurk** [comment]
This was asked for in some form when I ask for it in #543 so I'm going to flag this as duplicate and close it.
