### ISSUE TITLE
Logix Interface Proxy cleaner

### ISSUE THREAD

**Issue by LeDrascol** [Frooxius/NeosPublic#1491]
Logix Interface Proxies are a highly invasive component that appear to serve no purpose once the logix has been packed. They are automatically added in large quantities, and must be located and removed manually.

This could be solved in one or more ways:
* Create proxies as non-persistent
* Create proxies under a centralized (non-persistent) slot
* Add 'Remove Interface Proxies' to Asset Optimization Wizard
* Automatically remove proxies when...
* * The interface is deleted
* * The logix is packed

**Comment by ProbablePrime** [comment]
This particular one is actually a bug, that's persisted for a huge amount of Neos' existence. All Team members who have access to the code base have attempted to fix this and not managed it, Including Froox.

Froox's current sentiment with this is that It will have to wait until Logix Interfaces and other areas of Logix are re-designed and therefore re-implemented. 

You can read about it more here: https://github.com/Frooxius/NeosPublic/issues/1128

I'd therefore suggest we close this as a duplicate, unfortunately.

**Comment by Frooxius** [comment]
Sorry this won't happen as official implementation. As a rule I'm not adding ad hoc "fixes" for bugs like this. Like ProblablePrime mentioned, the proper approach is to redesign the mechanism, which is planned along the way to address a multitude of other problems as well.

**Comment by LeDrascol** [comment]
This suggestion is specifically related to the **component** created on a slot each time an interface is spawned, and **not** the interface that visually appears in-world. The visual interface can be cleared easily using existing tools, but the **components** created in referenced slots cannot.
