### ISSUE TITLE
Add horizontal Range to Sphere Aligner

### ISSUE THREAD

**Issue by MR-Alex42** [Frooxius/NeosPublic#1494]
Adding vertical range to the Sphere Aligner with NormalizedStart and NormalizedEnd was a good addition.
To make it even better I would like to request also a horizontal Range for the Sphere Aligner.
This would enable to place objects along the surface of a sphere segment.
The goal would My use case would be to place objects for best possible non-fatiguing interaction like this:
![image](https://user-images.githubusercontent.com/15617301/102548968-b3879000-40bb-11eb-8f3a-dfe61137a5c7.png)

**Comment by Frooxius** [comment]
Added in 2020.12.18.33, thanks!
