### ISSUE TITLE
Networking - Other Users cant join Hosted Sessions

### ISSUE THREAD

**Issue by Readun** [Frooxius/NeosPublic#1502]
I ran into a Problem, that People cant join me after a couple of minutes after starting to host a world.
They keep loading until they go to another world.
I have not made out what is causing it, but got some logs aswell.

[READUN-PC - Host.log](https://github.com/Frooxius/NeosPublic/files/5718476/READUN-PC.-.Host.log)
[KASAI_-_2020.12.18.1284_Userwhocantjoin.log](https://github.com/Frooxius/NeosPublic/files/5718479/KASAI_-_2020.12.18.1284_Userwhocantjoin.log)
[Probably_the_Point_of_failure.txt](https://github.com/Frooxius/NeosPublic/files/5718485/Probably_the_Point_of_failure.txt)

PS: Need to add... I have that bug for multiple months already

**Comment by Frooxius** [comment]
I looked into this, but it seems like it's likely some issue with your connection. Are you or your ISP using a strict NAT? I checked the logs, including server-side and looks like it tried to establish connection, failed and tried to connect through the relay, but even after 10 attempts the connection to the relay could not be established. It seems the command to connect never reached your end.

I'll add a bit of extra diagnostics in the next build that might help see what's going on, but I'm not sure if this is something that we can do much about on my end.

**Comment by Readun** [comment]
Hmn.. Welp.. need to look strict NAT up, not really sure what can cause that.
I do have Dual Stack (IPv4 and IPv6)
Deactivated the Teredo-filter + Prefer IPv4 instead of IPv6 now and need to see if it helps tomorrow.
UPnP was already activated. 
Beside all that I use portforwarding to a different PC on our Network + have a DynDNS aswell. 
ISP is Unitymedia from Germany. (Cable)
(Just trying to write up everything that could be involved)

**Comment by Readun** [comment]
I sadly wasnt able to retriev any logfiles today, but we found out:
- If the user who is trying to join me uses "prefer Steam Networking sockets" they are capable to join, while the normal way fails.

Users are able to join my session normally for the first couple of minutes.
Im also fully able to host Arma 3, TS 3, Minecraft and more servers. (With Portforwarding)
I didnt knew what ports neos uses, so I shortly activated self assigning Port forwarding on my router, sadly with no success aswell.

Are the new Network Statistics included in the Logfiles now or is it a special menu inside Neos?

**Comment by Readun** [comment]
Sooo.. now we got all the log files. 
I dont really know much about it, but for me it looks like the network thingy is NOT switching to neos-steam as the last try, as there are 3 network types specified.
It gets stuck on LnL and doesnt do anything futher? As if it thinks that it got connected, while its not.

My end:
[READUN-PC - 2020.12.20.103 - 2020-12-21 18_59_44.log](https://github.com/Frooxius/NeosPublic/files/5726004/READUN-PC.-.2020.12.20.103.-.2020-12-21.18_59_44.log)

Drakys End with normal Networking:
[DRAKYPC - 2020.12.20.103 - 2020-12-21 Normal Network.log](https://github.com/Frooxius/NeosPublic/files/5726005/DRAKYPC.-.2020.12.20.103.-.2020-12-21.Normal.Network.log)
Error Timestamp is -> 19:41:31.881

We tried to connect and disconnect, until it wasnt possible anymore.

Drakys End with Steam Networking (The Session was already broken at that point, nobody with normal networking could join, would need to restart my Neos completly to get it working again)
[DRAKYPC - 2020.12.20.103 - 2020-12-21 Steam Network.log](https://github.com/Frooxius/NeosPublic/files/5726013/DRAKYPC.-.2020.12.20.103.-.2020-12-21.Steam.Network.log)


I hope that could help to tie the problem closer down.

**Comment by Frooxius** [comment]
Currently the protocol won't try to switch to neos-steam as fallback if the LNL connection is available. It will try to establish the connection and then use the Relay as fallback. That's expected behavior.

What is really strange is that no attempts at connection seem to be ever reaching your end. I see multiple attempts being sent to connect to the relay from the cloud, but nothing seems to reach your system. I might need to add some more logging to see if I can find where it's getting lost, but it might just be something odd with your connection.

Having fallback to another protocol is planned, so that can help as mitigation, but ideally the Relay should work in 100 % cases.

**Comment by Readun** [comment]
New Logfiles from today (Update 2020.12.22.259)

Draky's Log file (Again, joinging and leaving until it doesnt work anymore)
[DRAKYPC - 2020.12.22.259 - 2020-12-22 22_34_48.log](https://github.com/Frooxius/NeosPublic/files/5732220/DRAKYPC.-.2020.12.22.259.-.2020-12-22.22_34_48.log)

My log files:
[READUN-PC - 2020.12.22.259 - 2020-12-22 22_32_39.log](https://github.com/Frooxius/NeosPublic/files/5732223/READUN-PC.-.2020.12.22.259.-.2020-12-22.22_32_39.log)

Last successfull connection from Draky on my End: 22:55:35.703

At the end, nobody could rejoin my session anymore.

**Comment by Frooxius** [comment]
I'm looking at the logs, can't find anything definitive yet, but one thing I noticed - is your and/or the connecting person's system clock correct? It seems that it's a few minutes off from the server.

Or do you happen to have an ISP that ends up changing your IP periodically? Or NAT server that expires port mapping after a period of time? It's odd that it works for a while and then it doesn't.

**Comment by Readun** [comment]
My system is off by 1 Second to a atomic clock, Draky's pc is also nearly spot on

First Join of Draky in the Log: 22:35:21.699 VS 22:35:21.540 
We dont have a fixed IP, normaly it changes when we restart the Router (But not always aswell)
My ISP is Vodafone (Cable Network, previosly called Unitymedia, before it got sold).


Im using Portforwarding on a different PC for Arma 3 Server, TS3 server and so on. Dont run into issues there. Are there known Ports for Neos aswell? Maybe I can try it that way.
I see 52219 on my end and 53835 on Draky's
Going through multiple log files, it looks like Neos is using a range from 50000 to 59999 ?

Or can Portforwarding for other services to a different PC interfer with the ones Neos likes to use?
(Deleted them all now to test it, but that should not be a problem)

Overall... lnl-NAT seem to work for 5-15 Minutes, while LNL (Relay?) Doesnt work or do anything on my end at all.

Is there any duration test or routing path test I can do?

**Comment by Frooxius** [comment]
I see thanks for the info! 1 second off is perfectly fine, it'd be only problem if it's several minutes. The discrepancy is probably something else then, I think I might just be matching the wrong sections to each other. 

Neos will use random ports for each session. You could try forcing a port in the dialog that lets you customize the startup settings and see if that helps.

**Comment by Readun** [comment]
Welp. It seems like people can join over a Mobile connection (But im not 100% Sure).

Reseted our Router to factory settings again, which didnt helped.... sooo there is something going on ?
ISP: Vodafone (Unitymedia) - Cable Networking
Router: Fritzbox 6591 Cable

Im not really sure what Steam command will force the port in neos, is it just "-port" ?
Was playing around with starting my worlds as a Custom Session and disabled the Port 12100 there, portforwarded TVP and UDP... and it worked (But again not 100% Sure, as I wasnt able to run a long test yet)
