### ISSUE TITLE
Disable Discord rich presence when invisible/in a private/hidden session

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#1503]
Observed by Psychpsyo (Cameron# 7818) and others in the past, Discord rich presence can reveal when users are in a session when they are appearing as invisible, and will also show users that share a private world by grouping them together.
![image](https://user-images.githubusercontent.com/54213390/102681258-fe191300-4174-11eb-8537-b3c069aaf3c2.png)

**Comment by Frooxius** [comment]
Changed in 2020.12.20.103! Neos will now clear the rich presence in both Steam and Discord if you're set to invisible. Thanks!
