### ISSUE TITLE
Poor Quality Audio from Certain Sources (Resampler?)

### ISSUE THREAD

**Issue by Enverex** [Frooxius/NeosPublic#1505]
A long time ago there was a complaint about video audio quality where it sounded like it was using a bad resampler. I've not noticed that specific issue for some time, but I've noticed this issue on several sound sources since then. 

Here's what it should sound like (imported into Neos as an MP3 file, it's been converted to an OGG here for the sake of Discord):
https://cdn.discordapp.com/attachments/439422161657135106/782319452763062282/GoodAudio.ogg

Here's what it sounds like in Neos (recorded from Neos directly using Audacity):
https://cdn.discordapp.com/attachments/439422161657135106/782319500829392906/BadAudio.ogg

It sounds like it's been run through the worlds worst resampler, there's also a bunch of pops and clicks too.
Additionally, if I change the playback speed, it doesn't change, it just starts skipping around instead.

**Comment by Frooxius** [comment]
This is an old issue, a better resampler was implemented months ago when the issue was originally brought up.
