### ISSUE TITLE
[Request] Login as invisible startup command

### ISSUE THREAD

**Issue by 3x1t-5tyl3** [Frooxius/NeosPublic#1506]
Simple request really: Being able to login as invsible (for variety of reasons) through either a startup argument (steam or launcher argument). Or any other way that doesn't make one-self appear online upon login.

**Comment by Frooxius** [comment]
This could be added. If you know you want to be invisible next time you can also set yourself Invisible before you log off, Neos will remember the status on the next time you load.

**Comment by Frooxius** [comment]
Added in 2020.12.20.103, you can now pass -Invisible command on startup. Thanks!
