### ISSUE TITLE
Create Dynamic Variable nodes of type Slot always set persistent to True

### ISSUE THREAD

**Issue by orange3134** [Frooxius/NeosPublic#1508]
Problem
The Create Dynamic Variable node of type Slot always creates a Dynamic Variable with persistent set to True, regardless of the input of CreateNonPersistent.

Similar issues occur with the Slot type Write Or Create node.
![2020-12-20 12 31 34](https://user-images.githubusercontent.com/56525091/102704859-4abf3400-42c4-11eb-92d8-8cde0978bb9e.jpg)

**Comment by chemicalcrux** [comment]
This appears to happen with DynamicReferenceVariable in general; I tried it with User and Sync<float3>

**Comment by Frooxius** [comment]
Unfortunately I'm having problems replicating this, the dynamic variable is created correctly as non-persistent on my end. Are there any extra steps/conditions?

**Comment by Frooxius** [comment]
Nevermind, I managed to replicate it! Have a bugfix coming in the next build!

**Comment by orange3134** [comment]
Thank you Frooxius!  
We use this feature a lot in the games we are working on, so that is very helpful.

**Comment by Frooxius** [comment]
Fixed in 2020.12.22.259! Thank you!
