### ISSUE TITLE
Always crashes when opening a particular world

### ISSUE THREAD

**Issue by orange3134** [Frooxius/NeosPublic#1510]
Problem
When I open this world I get a Unity crash window and Neos VR crashes.
http://cloudx.azurewebsites.net/open/world/G-Shared-Project-rheni/R-8fbdff0d-8f48-4c04-87ea-f5da559790b3

This issue did not occur two weeks ago.
From that time until now, the world has not been updated.

I'm sending a crash log of this issue on Discord.

**Comment by chemicalcrux** [comment]
The world also crashes me -- I can load the world and look around for a bit, but then the game freezes and the crash window appears.

I see no obvious causes in the logs (but the crash is probably preventing anything from being logged by Neos).

**Comment by Frooxius** [comment]
The world seems to be triggering the same crash caused by the Steam overlay injecting itself into the desktop duplication library. I have made some mitigations in 2020.12.22.259, can you check if the world runs well now?

**Comment by orange3134** [comment]
Now I have opened this world 10 times and never crashed.
Thanks for the quick fix!
I close this issue.
