### ISSUE TITLE
Impulse Input tooltip for "Create Dynamic Variable" is incorrect

### ISSUE THREAD

**Issue by ProbablePrime** [Frooxius/NeosPublic#1512]
1. Spawn a Create Dynamic Variable Node of any data type
2. Point a logix tip at its top Impulse input on the left side
3. Observe the tooltip of your logix tip says "WriteOrCreate"

This should just be "Create" as this node can only create values with an initial value, it cannot write them after creation.

![image](https://user-images.githubusercontent.com/8791132/102829298-a90b1600-439b-11eb-9e8b-3f7349a3eb3f.png)

**Comment by Frooxius** [comment]
It's already been reported here: https://github.com/Frooxius/NeosPublic/issues/1411

Changing this is a bit tricky, as I need to add a system for backwards compatibility to not break existing setups when loaded.

**Comment by ProbablePrime** [comment]
Ahh woops, thanks!
