### ISSUE TITLE
Make the default texture filtering Anisotropic

### ISSUE THREAD

**Issue by Toxic-Cookie** [Frooxius/NeosPublic#1513]
It looks objectively better than bilinear and trilinear. See examples below.

Anisotropic:
![20201222114348_1](https://user-images.githubusercontent.com/66691163/102927180-525d1500-444b-11eb-915b-0a028371c7aa.jpg)
The grid looks very clear and easy to see.

Trilinear:
![20201222114357_1](https://user-images.githubusercontent.com/66691163/102927191-5852f600-444b-11eb-95e7-706ec3659c85.jpg)
The texture gets blurrier with distance but not as bad as bilinear.

Bilinear:
![20201222114405_1](https://user-images.githubusercontent.com/66691163/102927224-64d74e80-444b-11eb-96f9-3b7917c8c0ac.jpg)
The most awful option. It's blurry, has distortion artifacts and has obvious ranges of varying terribleness. This should **Not** be the default option.

**Comment by Enverex** [comment]
I raised this one a long time ago - https://github.com/Frooxius/NeosPublic/issues/460

**Comment by TehTurk** [comment]
I'm going to close this since it's the same request as before
