### ISSUE TITLE
Moving the Dash in Desktop too Fast and letting go Causes Interaction Laser to get "stuck"

### ISSUE THREAD

**Issue by TehTurk** [Frooxius/NeosPublic#1516]
https://discord.com/channels/402159838827905024/439422161657135106/791290407186857992 
Video and Issue reported by EpicEaston197

Was a bit confused of the issue at first, but he reported that his laser would get "stuck" on a part of the dash and it wouldn't lift off at all in Desktop Mode. He managed to replicate the issue by "yoinking" or "yeeting" his dash really fast. (I.e Just grabbing it and moving really fast and letting go). Not really a super crazy bug, but wanted it jotted down for note in the future.

**Comment by Frooxius** [comment]
I'm sorry, but desktop mode isn't currently supported. This is probably just a result of its very hacky nature. The whole system will be scrapped once proper desktop mode comes in, so I don't plan on tracing the source of this bug and fixing it. I'd just recommend avoiding this for now.

**Comment by TehTurk** [comment]
Understood, thanks for the response, wasn't expecting much from it just wanted to make sure it was doc'd in some form 👍
