### ISSUE TITLE
Dashboard Laser Behavior Tweak

### ISSUE THREAD

**Issue by AshtonSparx** [Frooxius/NeosPublic#1524]
## Is your tweak request related to a problem? Please describe.

The local laser that is associated with the dashboard has some issues regarding interacting with the world when it shouldn't.

## Describe what would you like tweaked

The dashboard Laser if moved fast enough off of your dash can interact with objects outside of your local space such as Video players which can be annoying when doing activities like watching movies. Regardless if you have lasers disabled or not.

## Describe alternatives you've considered

Altering the behavior to not be able to interact with anything outside of your local space at all.

## Additional context
Add any other context or screenshots about the tweak request here.

N/A

**Comment by shiftyscales** [comment]
This issue is most easily replicated by having an interactible element such as a audio clip or something else between yourself and the dashboard while you have your lasers disabled on the context menus.

**Comment by Frooxius** [comment]
Made a bunch of tweaks in 2020.12.30.1285, it should behave better now. Thanks for report!
