### ISSUE TITLE
Refresh Audio Devices

### ISSUE THREAD

**Issue by LeDrascol** [Frooxius/NeosPublic#1525]
Currently, audio devices added or removed after launching Neos will not be recognized until the software has been restarted. A common cause of this issue is when using third party audio software with non-persistent virtual devices, such as RTX Voice. Non-automatic methods such as a "refresh devices" button are also a viable solution.

**Comment by Frooxius** [comment]
Added in 2020.12.30.1285 thanks! There's no button, it will simply rescan the devices every 5 seconds or so while the device selection dialog is open.
