### ISSUE TITLE
AutoLookAtUser Ignore Parent User Option

### ISSUE THREAD

**Issue by LeDrascol** [Frooxius/NeosPublic#1526]
The AutoLookAtUser component is a great shortcut to avoid using logix for assigning a LookAtUser target, but is incapable of filtering out the active user in the case of attachments. This causes attached objects to always observe the active user, as they will reliably be the closest.

This can be solved by adding a checkbox for "Ignore Parent User", like what is provided for the CharacterForceField component.

**Comment by Frooxius** [comment]
Added in 2020.12.30.1285, thanks!
