### ISSUE TITLE
Option: Center Notifications On Head

### ISSUE THREAD

**Issue by LeDrascol** [Frooxius/NeosPublic#1527]
Currently, notifications such as messages and invites are centered on the dash, which does not reliably follow the user when turning in physical space or in screen mode. This issue also occurs when looking too far above or below the dash in its default position (ex. laying down). This can lead to either missed or difficult to read messages.

A simple solution is to provide the option of centering notifications on the user's viewpoint, thereby keeping them visible at all times.

**Comment by Frooxius** [comment]
This won't get implemented sorry. The current notifications is still the old UI and I don't plan on making any changes to it. The new UI will use the facet system and allow any positioning you prefer.
