### ISSUE TITLE
Easier import of YouTube videos

### ISSUE THREAD

**Issue by sirkitree** [Frooxius/NeosPublic#153]
Currently you have to create a video component, then manually enter the youtube url, or figure out how to copy/paste in 2D mode. It would be great if there was an easier way to show youtube. Perhaps the #60 would fix this though.

**Comment by Frooxius** [comment]
This is already supported, you don't have to create a video component. Simply copy the YouTube URL, switch over to Neos window and press Ctrl+V on your keyboard.
