### ISSUE TITLE
Scrolling the friends list changes the currently selected friend

### ISSUE THREAD

**Issue by mralext20** [Frooxius/NeosPublic#1531]
## Is your feature request related to a problem? Please describe.
When scrolling through the friends list, the currently selected user will change whenever you go to scroll.

## Related Issues
#1040 has a comment requesting the default of UIx buttons to be require lockin to press

## Describe the solution you'd like
the FriendItems's buttons should have "Require Lock In To Press" turned on, to prevent scrolling from triggering an item select

**Comment by Frooxius** [comment]
Changed in 2020.12.30.1285, thanks!
