### ISSUE TITLE
RectMesh<LineGraphMesh>'s First Value/Point seems incorrect.

### ISSUE THREAD

**Issue by ProbablePrime** [Frooxius/NeosPublic#1535]
## Describe the bug
UIX RectMesh<LineGraphMesh>, with a configured ValueGraphRecorder, has an awkward left hand trailing value. 

It looks like the first Line/Value on the UIX RectMesh isn't in sync with the rest of the graph. It creates an odd straight line on the edge of the graph.

See this picture here:
![20201228002043_1](https://user-images.githubusercontent.com/8791132/103200648-c3188d00-48a2-11eb-9e54-2ba3a42a031c.jpg)
![20201228002034_1](https://user-images.githubusercontent.com/8791132/103200651-c57ae700-48a2-11eb-9e34-319aa06cc605.jpg)

This video here: https://youtu.be/CL2cey1cE-0

## Relevant issues
Naw, not found

## To Reproduce
1. Setup a UIX Canvas
2. As a child add a RectMesh<LineGraphMesh>
3. Also add and configure a ValueGraphRecorder, ensure all properties are specified including the min/max drivers
4. Use a value field float for the value which the ValueGraphRecorder uses
5. Plug a basic sine wave(T -> Sine) from Logix into the valuefield
6. Watch the graph cycle for a few moments

## Expected behavior
I expect the left most column/value/linepoint to match the rest of the graph but it clearly falls behind or is weirdly offset.

## Screenshots / Video
See above videos and screenshots.

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Neos Version: 2020.12.24.35
 - Neos Platform: Windows
 - Link to reproduction World/Item: ProbablePrime's Public Folder -> Bug Repros -> LineGraphOddity -> spawn the first item

**Comment by Frooxius** [comment]
Should be good in 2020.12.30.1285 now, thanks for the report!
