### ISSUE TITLE
Worlds with High Number of Users causes world to Freeze when every User Speaks at once

### ISSUE THREAD

**Issue by TehTurk** [Frooxius/NeosPublic#1538]
## Describe the bug
So the other day I think on the 24th we did a group photo world, and we had a good number of people maybe 28-32, can't remember the exact count. We were trying to take a holiday Photo and basically ran into the issue of where if everyone literally went "Cheese" The World Froze for like a good 20 seconds, maybe it was caused by a burst of traffic, or audio stream maybe being that intense for a connection?

## Relevant issues
Thought it might be relevant to #223, but wondered if it could be something more

## To Reproduce
Get a High Number of Users on a Headless, and then cause everyone to speak at the same time

## Bug information (please complete the following information):
It happened a couple different times when everyone stopped talking, and then resumed speaking at the same time because we took a couple different photos and needed everyone to say "Cheese"
This occurred on a headless

**Comment by Frooxius** [comment]
This sounds like a networking problem of the connection not being able to handle the surge of data.

- What kind of connection was this hosted on?
- Do you have any network statistics from this event?
- Can this be replicated with any connection hosting, including ones with really high bandwidth?
- What exactly do you mean by freeze? Any voice/movement? Or did in-game rendering freeze too?

It might be just your connection, given it seems to prone to freezes when people are connecting too which causes burst of traffic, so it might not really be something that could be done much about.

I'd recommend running some network measuring utility and track what happens as you drop.

**Comment by Reactantvr** [comment]
The server was mine and was on wifi that gets around 60 Mbps up/down. I bought an ethernet cable to get the full gigabit up/down on it in the future.

**Comment by TehTurk** [comment]
It does, but I thought it odd that the session would freeze up from a large amount of Audio Data. 

- From what I was told by Reactant since it was his server, but he described it as such but I think he was using the same connection isp/router wise.
- None Currently no, this is not something you'll typically keep track of usage wise
- I want to assume yes, because it wasn't like your "typical" bug it repeated itself after the high network traffic burst so I wondered if there's too more at play.
- Hmm I want to say data model desync, but there was a moment of slight render issue for me as a client. But the instant that burst happen session locked up for 15-25 seconds as Reactant Described. It eventually resynced
- This also is not an issue with my connection, the freeze only happens when I'm hosting, I can typically host 20-28 high amounts of people, it's just the bursting that affects me when I host.

Hm okay, I wanted to at least pass this along for future as maybe this would be a constant gripe that people might run into in the future. I just figured as the Rate increases, the bit rate could maybe drop down to at least have the audio pass through, but also not desync.

**Comment by Frooxius** [comment]
This really sounds like a network problem, particularly considering that it's been hosted on WiFi. Wireless networks are particularly prone to being unstable and causing short drops in connectivity under load.

Unless this is something that happens in general on any network (particularly cable), it's not really something we can do anything about, as it has to do with quality of the network, rather than something in Neos.

The voice bitrate is already very low (typically 2-3 kB/s per person), but you can't also do any rate decreasing like that, because you don't know that the rate has increased until it's already too late to do anything.

**Comment by TehTurk** [comment]
Hmm I'll see if I can find more data because normally yeah I wouldn't think audio would cause that so I'll have to like try to find some ways to do some proper network diagnostic 🤔. If you want to close it feel free, but I'll reupdate this when I can get more. New Years is coming up and I'll attempt it then

**Comment by TehTurk** [comment]
I'm going to close this as nothing seemed to appear during all the parties last night :) So thanks for the response Froox.
