### ISSUE TITLE
User context menu stops working (or showing up) rarely.

### ISSUE THREAD

**Issue by Earthmark** [Frooxius/NeosPublic#1543]
## Describe the bug
A user's context menu stopped working, and they were unable to use their context menu (or get it to appear) until they were respawned.
Some fields in the context menu were disconnected (sadly I did not get a picture), however only a small portion of them. Of fields that were disconnected, I believe the font material was one of them.

OF NOTE: I had just done an asset cleanup via the asset optimization inspector looking for unused assets, using root as the place to start the scan.

## Relevant issues
Unknown

## To Reproduce
Unknown, have not had a repeat yet.

## Expected behavior
The context menu is always available.

## Screenshots / Video
Here is a log from the session.
[DESKTOP-5HFQ42U - 2020.12.24.35 - 2020-12-29 18_28_36.log](https://github.com/Frooxius/NeosPublic/files/5753690/DESKTOP-5HFQ42U.-.2020.12.24.35.-.2020-12-29.18_28_36.log)
There's a wide smathering of log entries related to the context menu, so that seems hopefully relevant!

## Bug information (please complete the following information):
 - How often does it happen: It happened to two people at the time, Wolpy and RagdollZombie
 - Neos Version: Beta 2020.12.24.35
 - Neos Platform: Windows
 - Link to reproduction World/Item: Unknown
 - Regression: Unknown

## Additional context
Their context menu was parenting properly, however it was just not appearing properly.

## Reporters:
RagdollZombie  U-RagdollZombie
Wolpy U-Wolpy

I'm reporting it, Earthmark U-Earthmark Earthmark#0314 but I did not encounter the bug (I did respawn them though).

**Comment by shiftyscales** [comment]
Worth noting is that a user should not ever run the asset optimization wizard on the root slot of the world as it can/will cause things to break. It is only intended to run the optimization wizard on explicitly defined/sorted hierarchies the user has configured, e.g. a slot for their world's contents, etc.

**Comment by Earthmark** [comment]
Closing as likely due to my misuse of the asset optimization wizard.
