### ISSUE TITLE
include UsersInPublicSessions on OnlineUserCount component

### ISSUE THREAD

**Issue by mralext20** [Frooxius/NeosPublic#1545]
## Describe what would you like tweaked
the OnlineUserCount component should be updated to include the amount of users in public sessions, as the discord bot was recently updated with the same data.

## Describe alternatives you've considered
doing an anon API request to `neosvr-api.com/api/sessions` and parsing the output for active users in public sessions
(existing tool that does tihs in my public folder, called `Participating Population`
## Additional context
onlineUserCount component:
![](https://this-is-a.stale-me.me/i/r5no.png)

logix that does this using API request:
![](https://this-is-a.stale-me.me/i/62w9.jpg)

**Comment by Frooxius** [comment]
Added in 2021.1.26.1308, thanks!
