### ISSUE TITLE
Default hands spawning on Handless Screen Mode avatars, Removing breaks functionality

### ISSUE THREAD

**Issue by IanCorvid** [Frooxius/NeosPublic#1546]
## Describe the bug
When equipping an avatar built for Screen Mode that does not have hands in it, Neos now automatically attaches Default VR_Gloves to the user's root, both positioned at approximately 0,0,0 of the user's root point. Even after deleting these, they will seemingly respawn any time the handless avatar is loaded.

Removing the unwanted VR_Glove hands also breaks interaction with the Neos cameras. Both the Neos 2.0 camera and the one found in Essential Tools > Aegis Folder cease to function. Holding the camera with M2 and triggering it with M1 produces no longer triggers photo taking, neither does pressing the camera's take photo button. If the timer turned on it will count down, but the camera will completely despawn at the end of it.

## To Reproduce
Run Neos in Screen Mode.
Equip avatar built without hands, such as drone or 'floating orb' type desktop avatars
Delete VR_Glove Left and Right.
Spawn Neos Camera and attempt to M2+M1 or click photo button with or without timer turned on.

## Expected behavior
Handless Desktop avatars appropriately not having attached hands, being built without them and with default VR_Gloves spawning only when worn by a VR user with VR controllers.

Neos Camera properly taking a screenshot photo when M1 is clicked while holding the camera with M2

## Screenshots / Video
Image of Drone type Screen Avatar, created by self with no hands built in, only recently having them be force spawned in at near 0,0,0 of user root
![aaaaloogis](https://user-images.githubusercontent.com/76805348/103401089-99b36780-4b15-11eb-8e89-0172dd6d62bf.png)

## Bug information (please complete the following information):
 - How often does it happen: Always, specifically on hand-less desktop avatars
 - Neos Version: 2020.13.30.1285
 - Neos Platform: Windows - Screen Mode
 - Regression: Was not an issue prior, unsure of what build however problem is decidedly recent.

## Reporters:
Reporter: Ian Corvid#8921

**Comment by Frooxius** [comment]
I'm sorry, but this is intentional change. I'm unifying the avatar spawning mechanisms and functionalities in preparation for future features and additions, so the underlying avatar constructs work the same regardless of mode.

You can put avatar hand nodes on your avatar and have them have no visible visual if you want to get rid of them, the same way you'd make a hand-less VR avatar.
