### ISSUE TITLE
LinearMapper1,2,3,4D's Clamp checkbox does not function

### ISSUE THREAD

**Issue by mralext20** [Frooxius/NeosPublic#1547]
## Describe the bug
the LinearMapper's clamp checkbox does not work

## To Reproduce
1. setup a linear mapper component
2. turn off the Clamp Feature
3. set the input beyond the allowed input range
4. the input is clamped to to the input range instead of not being clamped

## Expected behavior
Clamp checkbox to allow the range of inputs to be unbounded

## Screenshots / Video
![](https://this-is-a.stale-me.me/i/y40n.png)

## Bug information:
 - How often does it happen: Always
 - Neos Version: 2020.12.30.1285
 - Neos Platform: Windows
 - Link to reproduction World/Item: 
 - Regression: Unsure

## Reporters:
Alex from Alaska#2020

**Comment by Frooxius** [comment]
Fixed in 2021.1.11.642, thanks!
