### ISSUE TITLE
Undo spawn doesn't remove all objects spawned

### ISSUE THREAD

**Issue by Coffee-Maker** [Frooxius/NeosPublic#1552]
## Describe the bug
When you undo after spawning a save with multiple objects, it will only undo spawning 1 of the objects.

## To Reproduce
1. Hold multiple objects and save them
2. Spawn the objects
3. Undo

## Expected behavior
It should remove all objects that were spawned

## Screenshots / Video
https://user-images.githubusercontent.com/25093209/103438027-98c22900-4c2e-11eb-9628-32f2fa2dd82f.mp4

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Neos Version: 2020.12.30.1285
 - Regression: Probably not, after testing a few older builds.

## Additional context
When spawning more than 2 objects, it still only removes 1 object on undo.

## Reporters:
Coffee#1507

**Comment by Frooxius** [comment]
Fixed in 2021.1.11.642, thanks!
