### ISSUE TITLE
TooltipMultiplexer Ignores CommonToolPermissions Blacklist

### ISSUE THREAD

**Issue by LeDrascol** [Frooxius/NeosPublic#1553]
## Describe the bug
CommonToolPermissions has a setting labeled 'AllowOnlyWhitelistedTools'. By unchecking this, a user may list blacklisted tools. This setting does **not** apply to a TooltipMultiplexer.

The standalone tool will be blocked from use by the setting, while a multiplexer version of that tool will be unaffected.

Without the ability to block problematic tools, worlds can be irreparably broken on accident with a singular click, largely due to a lack of undo function on many tools.

## Relevant issues
This is the opposite of #1462

## To Reproduce
1. Set CommonToolPermissions for your rank to **not** AllowOnlyWhitelistedTools
2. Add a tooltip type (ex FrooxEngine.GlueTip)
3. Uncheck 'Allow' if checked
3. Attempt to equip the blocked tool directly
4. Attempt to equip the blocked tool as part of TooltipMultiplexer

## Expected behavior
The multiplexed tool should not be usable, but is usable.

## Bug information
 - How often does it happen: Always
 - Neos Version: Tested on Beta 2020.12.30.1285
 - Neos Platform: Tested on Windows
 - Regression: Unknown

**Comment by Frooxius** [comment]
This is same issue as https://github.com/Frooxius/NeosPublic/issues/1462, so I'll close this one as duplicate. The answer for that is pretty much the same, this would complicate the system a fair bit, so it's not likely to get prioritized now.

I recommend keeping TooltipMultiplexer usable only for Builders as is the default right now.
