### ISSUE TITLE
After enabling "Show Mask Graphic" on a mask, it cannot be disabled as expected.

### ISSUE THREAD

**Issue by ProbablePrime** [Frooxius/NeosPublic#1559]
## Describe the bug
When using UIX Masks, I sometimes use "Show Mask Graphic" for diagnostic purposes to check the shape of my mask etc.

Once "Show Mask Graphic" has been enabled, it cannot be disabled. 
You can turn off the Checkbox, but the graphic/image will still be there.

## Relevant issues
I found this previous issue:https://github.com/Frooxius/NeosPublic/issues/991 but i can't really figure out what's going on there.

## To Reproduce
Try using my reproduction canvas mentioned below, it should be faster.
1. Create a simple UIX canvas
2. Create a child slot on this canvas and add a UIX Image to it
3. Give this image a suitable mask image such as the circle with a transparent background found in Neos Essentials -> Textures & Sprites -> Particle Effects
4. Add a Child slot underneath this one and give that a UIX image of any image, a screenshot..whatever you'd like
5. Add a UIX Mask to the first slot created in step 3
6. You should now see a circular cutout of the image added in step 4
7. On the slot created in step 3, turn on the "Show Mask Graphic" checkbox
8. The mask graphic(a circle) will show
9. Turn off the show mask graphic option
10. Observe that the Mask graphic is still present

## Expected behavior
I expect the mask graphic to be hidden again when I turn off "Show Mask Graphic"

## Screenshots / Video
![image](https://user-images.githubusercontent.com/8791132/103453418-ad360e00-4c8e-11eb-936f-14e8b890e904.png)
![image](https://user-images.githubusercontent.com/8791132/103453429-c474fb80-4c8e-11eb-965c-bc67be373b5c.png)

 - https://i.probableprime.co.uk/210101-Xjb3NEIeqN92o8njhYxf.mp4
Sorry for the first few frozen frames in the video here it does clear up though and shows the issue.

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Neos Version: 2020.12.30.1285 
 - Neos Platform: Windows
 - Link to reproduction World/Item: My Public Folder -> Bug Repros -> Mask Graphic -> Spawn First Item
 - Regression: [Did this work before? I'm not sure.

## Additional context
Duplicating the canvas fixes the issue(as in if the mask is showing, but the show mask graphic checkbox is off then the mask will be invisible on the duplicate)

## Reporters:
Me :), Although i seem to remember speaking about this to other users.

Oh here's a logfile
[ALFRED - 2020.12.30.1285 - 2021-01-01 23_28_20.log](https://github.com/Frooxius/NeosPublic/files/5759925/ALFRED.-.2020.12.30.1285.-.2021-01-01.23_28_20.log)

**Comment by Frooxius** [comment]
Fixed in 2021.1.3.612, thank you for reporting!
