### ISSUE TITLE
Tool lasers no longer work when lasers are disabled

### ISSUE THREAD

**Issue by Electronus** [Frooxius/NeosPublic#1560]
## Describe the bug
Previously tool lasers would still work as normal when lasers were disabled through the context menu. 
tested with line brush, Logix tip, and Dev tip.

## Relevant issues
Shifty pointed our that #1524 may be related. 

## To Reproduce
open any world
disable your lasers
spawn a tool 
attempt to use lasers to place tools on tool shelves or interact with anything
Brush tip has no laser at all

## Expected behavior
Tools should have lasers that act as normal. Being able to place them on the tool shelf, select objects being the main points.

## Screenshots / Video
https://youtu.be/ySNo8ousc3c

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Neos Version: 2020.12.30.1285
 - Neos Platform: Tested on Windows
 - Link to reproduction World/Item: none
 - Regression: Yes, not sure when it changed but not more than a few build ago. 

## Additional context
Not sure if intended or not. 

## Reporters:
Electronus#5305

**Comment by Frooxius** [comment]
Fixed in 2021.1.3.612, thanks for report!
