### ISSUE TITLE
RectTransform - Preview occupying area

### ISSUE THREAD

**Issue by 3x1t-5tyl3** [Frooxius/NeosPublic#1566]
## Is your tweak request related to a problem? Please describe.
A big annoyance with UIX currently is when you're trying to make a certain area it's difficult to adjust the Anchor's properly.

## Describe what would you like tweaked
An extra boolean and color field to activate a "preview" mode for "RectTransform" to preview the area it's occupying.
Preferably the color mode to make sure you can choose your own color just in-case it interferes with the UI underneath it for some reason.

## Describe alternatives you've considered
Currently the only other way to do this is to add an "Image" and then delete it again which is quite a few clicks for a simple preview.

## Additional context
None I can make a mock-up if need be though.

**Comment by Frooxius** [comment]
This won't get added in this form sorry, it would add way too much overhead into RectTransform which is the backbone of all UI and it's not something it's responsible for.

This will be handled properly by UI gizmos which will allow for building UIX visually instead.
