### ISSUE TITLE
BlurMaterial doesn't respond to offset/scale settings for its SpreadMagnitudeTexture

### ISSUE THREAD

**Issue by chemicalcrux** [Frooxius/NeosPublic#1568]
## Describe the bug
BlurMaterial accepts a texture to control the intensity of the blur. This works as expected. However, it does not react to the texture scale or texture offset.

## Relevant issues
Nothing found talking about BlurMaterial here or on the Discord.

## To Reproduce
1. Create a BlurMaterial
2. Add a texture to its SpreadMagnitudeTexture slot
3. Try changing the offset and scale

## Expected behavior
The texture should be scaled and offset as usual

## Screenshots / Video
N/A

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Neos Version: 2021.1.3.1256
 - Neos Platform: Windows
 - Link to reproduction World/Item: N/A
 - Regression: Unknown

## Additional context
N/A

## Reporters:
N/A

**Comment by Frooxius** [comment]
Should be fixed in 2021.1.22.1352, thanks for the report!
