### ISSUE TITLE
Add "Strafing" option to all locomotion modules

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#1570]
## Is your tweak request related to a problem? Please describe.
Presently, noclip is the only locomotion mode which has a 'strafing' setting. As such, it is the only input method which respects the 'Allow Strafing' setting in the settings menu.

For a user wishing to use a single controller for movement and turning, they are unable to turn properly in non-noclip locomotions despite strafing being disabled.

## Describe what would you like tweaked
Allow strafing to be disabled across all locomotion methods.

## Describe alternatives you've considered
If the user switches their primary controller, they can work around this issue since the primary controller always has turning and moving forward/backward on the same stick.

**Comment by Frooxius** [comment]
This cannot be added to all locomotion modules, as it makes no sense for some of them (e.g. Grab World, Teleport), I assume you're mainly interested in adding this to PhysicalLocomotion though? That could definitely be added.

**Comment by shiftyscales** [comment]
Yes sorry, to clarify, I meant the physical locomotion module templates (physical fly, walk/run, etc.) @Frooxius 

It would be interesting if teleport could bump you from side to side in the way it can bump you backwards when you pull down on the stick- but that's outside of the scope of the initial request as I imagine it would be a more involved change to that particular locomotion method.

**Comment by Frooxius** [comment]
Added in 2021.1.13.764, thanks!
