### ISSUE TITLE
Additional Options - Reverb Component

### ISSUE THREAD

**Issue by GearBell** [Frooxius/NeosPublic#1578]
**Issue**: Reverb component in Audio affects everything. (Voice messages in a reverb zone are incomprehensible and deafening)
**Solution**: have checkbox options for it to ignore Voices, much like the volume meters in Audio Settings can differentiate between voices and multimedia/sfx.
**Additional Feature Solution**: Have a way, by component or logix, to be able to have reverb apply ONLY to a selected Audio source. Perhaps have a "Affected Audio Source" Slot for us to click and drag the audio source into. That way we can have ambient reverb or other audio sources reverb, while not affecting anything else - bypassing the main issue.

The reverb component does a wonderful job of doing reverb to the world but there are some issues. Biggest issue is it reverbs voice messages. Is there any way to give an option to exclude Voices, such as ignoring the voice volume meter? Seeing as literally the only time it affects voices is when we are in broadcast.
An additional option to the reverb component, or at least even a logix way - can we make it so that only particular things are affected by the reverb? For instance - I'd like to apply the reverb affect to the radio in my world without it affecting anything else. So if someone imports a video it is not blaring with reverb. Same for pretty much anything else that makes noise. Some worlds sound more expansive with the reverb so it is a great component - but it is problematic with pretty much all other sounds except for the ones you actually wanted to reverb.

**Comment by Frooxius** [comment]
Unfortunately it's not possible for reverb zone to have option to ignore voices, it's not aware of any of the audio sources. Rather it works the other way around - audio outputs can have option to ignore reverb zones.

I can add this option and set voice messages to ignore reverb zones by default, that should fix the issue you're having.

**Comment by GearBell** [comment]
But is there a way to set only specific audio sources to have reverb? like for ambience or radios. that way if someone spawns a new video its not blaring. or really any audio source thats not the ambience.

**Comment by Frooxius** [comment]
No, it works the other way, you have to disable the reverb for particular audio sources. I can make it default off for things like videos.

**Comment by GearBell** [comment]
that would be helpful!

**Comment by Frooxius** [comment]
I've added IgnoreReverbZones to AudioOutput in 2021.1.11.642. Voice messages and video players now also ignore it by default. Thanks for report!
