### ISSUE TITLE
User parented under tooltip relocates tooltip's parent slot when attempting to equip

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#1581]
## Describe the bug
A user parented under a tooltip will adjust the position/rotation/scale of the parent slot the tooltip is under if the user tries to equip the tooltip while parented under the tool.

## To Reproduce
1. Parent a user under a tooltip
2. Have the user attempt to equip the tooltip

## Expected behavior
The tool does not attempt to be equipped as it is the parent slot the user is under.

## Screenshots / Video
https://youtu.be/DPXMMLNj_zM

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Neos Version: 2021.1.3.1256
 - Neos Platform: Any
 - Link to reproduction World/Item: neosrec:///U-Shifty/R-4a885c12-6772-4c1e-9415-f0b0458d7e24
 - Regression: No

## Reporters:
MattyK# 8239

**Comment by shiftyscales** [comment]
The anchor is not explicitly required to replicate the issue. All that is required is that the user be parented under the tooltip in some form.

**Comment by Frooxius** [comment]
In 2021.1.11.642 the menu to equip the tooltip should no longer appear if you're its child, that should fix the issue. Thanks!
