### ISSUE TITLE
Neos bot's SimpleAwayIndicator needs User reference to be assigned

### ISSUE THREAD

**Issue by Aerizeon** [Frooxius/NeosPublic#1588]
## Describe the bug
The Neos Bot 1.0 avatar (available in the MTC Avatar Creation world) does not appear to have an `AvatarUserReferenceAssigner` targeting the user reference in its `SimpleAwayIndicator` Component

I've noticed a couple new users appearing to be frozen, but who upon closer inspection are actually away, with no obvious indicator.

## To Reproduce

1. Create a Neos Bot 1.0 avatar in the MTC Avatar Creation world
2. Equip the avatar
3. Invite another user to the world the observe
4. De-focus the session
5. The other user should observe that you do not obtain an AFK material

## Expected behavior
The avatar should equip the default AFK material when the session

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Neos Version: 2021.1.11.642
 - Neos Platform: Any
 - Link to reproduction World/Item: http://cloudx.azurewebsites.net/open/world/G-Neos-Team/R-ae347f28-2573-4c4d-9200-113739b0d49d

## Reporters:
Epsilion

**Comment by shiftyscales** [comment]
Thanks for the report. Ryuvi has patched the Neos bot creator in the MTC as well as the Neos bots found in the avatars folder in the Neos Essentials.
