### ISSUE TITLE
The settings screen is sticking out

### ISSUE THREAD

**Issue by orange3134** [Frooxius/NeosPublic#1590]
## Is your tweak request related to a problem? Please describe.
As you can see in the image, the size of the settings screen is larger than the actual display area.
This is a problem that occurs if user have both VIVE HMD and Leap Motion installed on the system.

## Describe what would you like tweaked
Can you adjust the layout so that the settings screen does not stick out?

Scroll
Folding menu
Paging
I think one or some of these features are needed in the settings screen.

## Describe alternatives you've considered
none

## Additional context
![2021-01-11 20 28 58](https://user-images.githubusercontent.com/56525091/104411431-b20f9180-55ad-11eb-8a5b-95c2d6b5d2a4.jpg)
![2021-01-11 20 29 13](https://user-images.githubusercontent.com/56525091/104411434-b340be80-55ad-11eb-9fa8-90e291d3b0ab.jpg)

**Comment by Frooxius** [comment]
The settings should now scroll in 2021.2.7.1345, thanks for the report!
