### ISSUE TITLE
Eyelid movement shape keys for Eye Manager

### ISSUE THREAD

**Issue by InsaneGrox** [Frooxius/NeosPublic#1594]
## Is your feature request related to a problem? Please describe.
Eyes on avatars looking a bit dull, avatars from VRchat & other places having unused shape keys (that are used in those places), avatars that use shape keys for eye movement instead of bones or texture scrolling, could also be used to solve eye clipping in some scenarios.

## Relevant issues
N/A

## Describe the solution you'd like
Shape keys for eye look direction, mostly for the subtle eyelid movements you'd expect from the eyeballs moving around.

## Describe alternatives you've considered
I did set this up on my own avatar using logiX technically, but I'd prefer this being built into the eye manager

## Additional context
Heurestic Detection could look for the names "Eye_Up, Eye_Down, Eye_LookUp, Eye_LookDown, Eye_LookLeft, Eye_LookRight, EyelidUp, EyelidDown, EyelidLeft, EyelidRight", this is a detail that can be seen on the Sranipal sample head as well, and on my own avatar using logiX.

**Comment by Frooxius** [comment]
The Eye Manager already has all the things to handle this, it doesn't deal with the blendshapes directly. You can use the EyeLinearManager for texture scrolling instead of rotation, but it requires manual setup as it doesn't know how the avatar is setup.

Is this something common enough for the heuristics to work well enough? I haven't seen this on too many avatars, but I've also seen ones where there are multiples of each, so setting up those together with the bones would produce incorrect results. 

I can possibly add semi-automatic setup on a button, I'd probably need a bunch of avatar samples to test with though. I'm not fully sure about fully automatic one, as it's hard to tell what exactly the blendshapes are for.

**Comment by InsaneGrox** [comment]
The effect is very subtle, but IRL your eyelids move very slightly when your eyes move to accomidate your eyeballs moving in that direction, this is something that VRchat has implemented into it's system since Avatars 3.0 for vertical movement, so avatars are likely to have shape keys for eyelid movement at least vertically, this can't really be done with weight painting either due to the way the eyelids move, I think a video showing what I mean speaks a lot more about this topic than words. https://www.youtube.com/watch?v=gGplFzms9Lk

**Comment by Frooxius** [comment]
I understand the effect, I'm just saying how common are those names for them? Is there an established naming convention used across several different avatars?

The same blendshapes on a different avatar from another source might do something else, which would break them completely. Are those names standardized for a variety of avatars from different sources?

I'd need to see a some samples to work with to get the heuristics going for it and make sure it doesn't setup something wrong.

**Comment by InsaneGrox** [comment]
I honestly don't know if there is a standardized naming convention for them, the way you'd do it elsewhere is manual assigning, so name usually doesn't matter, this seems about as niche and unstandardized as widening and pupil dilation unfortunately.

**Comment by Frooxius** [comment]
I see thanks. I'll hold off the heuristics in that case, but I'll add drivers for the specific directions so the setup is simpler. I can add the semi-manual assignment based on the SRAnipal naming, but not sure if it's worth it if other avatars don't use that naming convention.

**Comment by GearBell** [comment]
what youre asking for is a weightpainting thing in blender that takes a few seconds to do. very lightly add weightpainting to the middle of the top and bottom eyelids to thier respective eyes fixes this. adding entire blendshapes seems overkill for a weightpainting thing. Ive done this for over a dozen avatars (not my public ones yet but its an easy update) it works just fine to make the eyelids move very slightly with the eyes to give more realism.

**Comment by InsaneGrox** [comment]
Added in 2021.1.17.998 👍

**Comment by Frooxius** [comment]
I've added new drivers in 2021.1.17.998 to set this up more easily, thanks!

- Added LookLeft, LookUp, LookRight and LookDown to EyeLinearDriver, which allows driving 0...1 directional values (e.g. blendshapes) based on where the eye is currently looking (based on request by @Groxxy the Eye-Puppeteer)
-- This can be used to drive extra blendshapes that morph the eye when it looks in particular directions
-- The response of the values can be controlled using the LookMultiply and LookPower fields

**Comment by Frooxius** [comment]
Huh reopened this by accident, closing, sorry.
