### ISSUE TITLE
Tweak the values of the SSAO to prevent rippling artifacts

### ISSUE THREAD

**Issue by InsaneGrox** [Frooxius/NeosPublic#1595]
## Is your tweak request related to a problem? Please describe.
The current implementation of Screen-Space ambient occlusion causes rippling artifacts all over the place, especially in bright environments.

## Describe what would you like tweaked
Either the sample count to be raised (would cause lowered preformance so this is the least desired)
Turn down the Radius to compensate for the low number of samples (would drastically reduce the rippling, but would cause large scale ambient occlusion to cease existing, though SSAO is more meant for small crevices)
Lower the Intensity slightly to make the artifacts less noticable
OR a combination of two, or even all three of these.

## Describe alternatives you've considered
Outright disabling it and just using baked lighting, or switching to a less artifact-y implementation of SSAO, which if a less artifacty and more preformant implementation of SSAO can be used, that would be even better.

## Additional context
Relevant issue would obviously be #322 though this issue is more related to players being able to adjust this stuff themselves, this is more related to adjusting the values that are used in neos currently to prevent artifacting.

**Comment by Frooxius** [comment]
The values are already tweaked about as much as they can be for best balance of performance and visual in most worlds, I originally spent quite some time on it. Ideally it has to be tweaked/disabled per-world, as its effectiveness will depend on the particular scenery, for that we already have issue here: https://github.com/Frooxius/NeosPublic/issues/322
