### ISSUE TITLE
Hide NoClip Locomotion if "Blocked to Nonbuilders" is in place

### ISSUE THREAD

**Issue by GearBell** [Frooxius/NeosPublic#1596]
Currently, we have the ability to block noclip from nonbuilders, however the icon is still visible and causes a lot of issues with users who dont know its blocked to them so they complain endlessly.
Solution: Take away the NoClip locomotion icon from nonbuilders who are blocked in the blacklist frooxengine.nocliplocomotion thing.

**Comment by Frooxius** [comment]
The locomotion menu should gray out any of the modules that cannot be used by the given user already, is this not the case? Do you have any worlds that would demonstrate this problem? 

It's not possible to specifically remove NoClip, the modules aren't hardcoded to the menu, it scans all the modules on the user and then checks if the user can use each one of them. If they can't, the button should be disabled (grayed out). It's possible to not generate the button at all if given module cannot be used as well instead.

**Comment by GearBell** [comment]
if we could have it where just the radial menu icon for the noclip is hidden that would help us all - and no, currently it is not greyed out at all as you said its supposed to be. Here is a POV pic from Veer where he was not builder but still saw the noclip icon not greyed out. If it is not possible to hide the noclip option at all to nonbuilders, then is it possible to just make the icon itself not load so it appears blank?
![20210117_080220](https://user-images.githubusercontent.com/30758182/104846947-7ec54f00-589a-11eb-8228-7d4cd2213385.jpg)

**Comment by Frooxius** [comment]
I'm sorry, but that particular solution is not really possible and it wouldn't be desirable. The proper solution is to either gray out any locomotion items that cannot be used or not generate them in the menu in the first place.

Can you send me a world with the permissions configured so it can't be used for testing so I can check what's going on there?

**Comment by GearBell** [comment]
sorry for the late reply - check the new map Demolition Derby Track - nonbuilders have no ability to noclip. the greyout doesnt work there.

**Comment by Frooxius** [comment]
Ah thank you! I found the culprit, the check whether a given module can be used or not was incorrectly returning that it can be used, even if it couldn't, causing the UI to not gray it out. Should be fixed in 2021.1.21.1068, thanks!
