### ISSUE TITLE
"Get Slot Active" and "Get Slot Active Self" should be one node.

### ISSUE THREAD

**Issue by Psychpsyo** [Frooxius/NeosPublic#1599]
## Describe what would you like tweaked
"Get Slot Active" and "Get Slot Active Self" should be one node with an additional bool parameter that defines whether or not the hierarchy is considered or not.

## Describe alternatives you've considered
Not changing it and keeping two nodes in the already full node browser menu.

**Comment by Frooxius** [comment]
I'm sorry, but this change won't be made.

They are fundamentally different operations and as a rule LogiX doesn't group different operations into same nodes with input selectors for the type of the operation. It leads to messy design, confuses documentation and implementation, and has unnecessary performance impact.
