### ISSUE TITLE
Items have to be deleted twice in folders

### ISSUE THREAD

**Issue by chemicalcrux** [Frooxius/NeosPublic#1600]
## Describe the bug
Deleting a freshly saved item in a folder does not work. It has to be deleted again to make it go away.

## Relevant issues
None seen, but [Froox did mention that there could be issues related to the switch in cloud providers](https://discord.com/channels/402159838827905024/515553786102546442/799605983709626388)

## To Reproduce
1. Spawn a Box
2. Save the Box into a folder
3. Delete the Box
4. The Box remains. Deleting the Box again removes it.

## Expected behavior
The item should be deleted on the first attempt.

## Screenshots / Video
N/A

## Bug information (please complete the following information):
 - How often does it happen: Always (but see below for some unpredictable consequences)
 - Neos Version: 2021.1.13.764
 - Neos Platform: Windows
 - Link to reproduction World/Item: N/A
 - Regression: Yes

## Additional context
H3BO3 observed that the items are deleted after reloading.

I observed some particularly weird behavior:

1. Save a box named "1"
2. Delete the box; the box remains
3. Click the cloud icon, then navigate back to the folder
4. Observe that the box named "1" may or may not be gone
5. Save a box named "2"
6. Delete the box; the box remains
7. Click the cloud icon, then navigate back to the folder
8. Observe that a box named "1" is back in the folder. The "2" box may or may not be gone

Step 4 has been inconsistent. Originally, the box would be gone on first visit, but now it's returning for me.

The "2" box comes back a little while later, too. I don't think the resurrection is related to saving another item; this just shows that it's not *duplicating* items in some strange way.

If you save an item, hit the cloud button, navigate back to the folder, and delete the item, it is destroyed correctly.

Timing does not matter. Items will retain this "double-deletion" behavior for a significant period of time after being saved. Reloading the inventory (which I presume is what navigating to your inventory list and re-entering the Personal inventory) is what clears up the bug.

I don't recall seeing this bug more than a day or two back, so it does seem to be a new issue. I do not know if it began immediately after the latest update.

The bug occurs on older versions of the client.

## Reporters:
I ran into this yesterday and did the above testing.
H3BO3 observed this bug and did some testing as well.

**Comment by Toxic-Cookie** [comment]
I have observed this happening as well. Thanks for making a GH.

**Comment by Hayden-da-Serg** [comment]
I also have observed this happening after the switch, most notably with my method of updating an avatar, I typically delete the old copy then save over it, but sometimes it doesn't show that it was removed.

**Comment by Frooxius** [comment]
When this happens, did you wait for the item to finish syncing or not? It sounds like it might be because you delete the item while it's still being synced, so it ends up finishing syncing after you deleted it.

Does the issue still happen if you delete the item after the sync finishes? If not I could add mechanism to handle deletion while the sync is still going.

**Comment by shiftyscales** [comment]
It appears this issue may be related to the UI not updating/refreshing after the item has been deleted, @Frooxius.

If a user saves an item (e.g. a box) to their inventory, waits for it to sync, then deletes it, they will still see it listed in the inventory, and can spawn it out until they press the blue cloud button to refresh their inventory and navigate back to that folder.

I think deleting it a second time is just forcing the inventory to refresh while it was actually deleted properly the first time- just the UI wasn't updated properly to reflect that change.

**Comment by chemicalcrux** [comment]
I don't think it's just failing to refresh. If I deleted an item, hit the cloud button, and navigated back, the item could be gone -- but could then return at a later time. 

Also, it probably isn't just a matter of deletion before sync, because I was observing this behavior well after I had saved items (e.g. while cleaning up after a development session)

**Comment by Frooxius** [comment]
Are you sure it's just UI issue? Are there cases where the item would persist even after restart?

If it's just UI, I won't be fixing it in the old version and we'll just have to wait for the reworked inventory, since this is not something that'd be severe. The update mechanism for the old UI inventory is a bit ugly/hacky, so tracing this down could take a lot of time.

**Comment by shiftyscales** [comment]
> 
> 
> Are you sure it's just UI issue? Are there cases where the item would persist even after restart?
> 
> If it's just UI, I won't be fixing it in the old version and we'll just have to wait for the reworked inventory, since this is not something that'd be severe. The update mechanism for the old UI inventory is a bit ugly/hacky, so tracing this down could take a lot of time.

I'm not certain. As Crux noted, there are seemingly some cases where deleted items return to the inventory at a later time- but so far I've not been able to replicate that specific behavior.

When Fuzy Sidwell# 2331 reported the issue to me, the items would reappear between restarts. They had multiple copies of the same item they had saved, they deleted each of the three copies, but one would be persistent/would reappear.

**Comment by ProbablePrime** [comment]
Here's a video from EpicEaston: https://cdn.discordapp.com/attachments/439422161657135106/799965558148825098/2021-01-16_06-34-27.mp4

**Comment by Frooxius** [comment]
I found the issue, the new mechanism for items saved outside of the inventory caused the internal records have two of the same item (one when directly added, another one when it was detected via event as added). I've fixed it in 2021.1.21.1068 which fixes the UI. Thanks for all the info!
