### ISSUE TITLE
Add PBS Specular as an Option for Asset Importing

### ISSUE THREAD

**Issue by StarfishHidari** [Frooxius/NeosPublic#1602]
## Is your tweak request related to a problem? Please describe.
When importing assets, there isn't a way to make the material used PBS_Specular. The advanced settings currently has the following options;
pbs, pbs dual sided, pbs triplanar, pbs emissive, unlit, unlit dual sided, unlit billboard, xiexe, xiexe outline, wireframe

When selecting PBS, it is pbs_metallic by default requiring me to go and convert every material to pbs_specular.

## Describe what would you like tweaked
Add pbs_specular as a material option in the advanced settings of the asset importer

## Describe alternatives you've considered
Not really sure what alternative there is?

**Comment by Frooxius** [comment]
Added "Prefer Specular" option to the advanced import in 2021.1.17.998, it should work with all the PBS options, thanks!
