### ISSUE TITLE
Transporting references between worlds causes crash in originating world

### ISSUE THREAD

**Issue by Aerizeon** [Frooxius/NeosPublic#1605]
## Describe the bug
Transporting a grabbed `ReferenceProxy` between worlds causes the `ReferenceProxy` to be dropped in an ungrabbable state upon arrival, and if you switch back and forth between the originating and target worlds, the originating world will crash.

This appears to be caused by an NRE when saving the transported object

## To Reproduce
1. Open two worlds (Gridspace will work fine)
2. In the world you're presently in, open an inspector and grab any reference with one hand - this will attach a `ReferenceProxy` to your hand
3. Focus into the other world. The `ReferenceProxy` will be immediately dropped, and be in an un-grabbable state
4. Focus back into the originating world
5. Focus back into the other world. The originating world will now crash

## Expected behavior
It appears that the transport *mostly* works, at least for the test case I had (a `StaticTexture2D`), so if it's intended to function this way, I would expect that the `ReferenceProxy` would still be grabbable, and contain a reference to a newly spawned copy of the transported item, and not crash the world.

If it is not intended for users to carry `ReferenceProxy` objects between worlds, it should simply be excluded from the userspace transfer upon world focus.

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Neos Version: 2021.1.13.764
 - Neos Platform: Windows

## Additional context
[Relevant Log section](https://github.com/Frooxius/NeosPublic/files/5824743/GrabTransitLog.txt)

## Reporters:
Epsilion

**Comment by Frooxius** [comment]
Fixed in 2021.1.17.998, thanks!
