### ISSUE TITLE
CTAA has no effect anymore

### ISSUE THREAD

**Issue by RileyGuy** [Frooxius/NeosPublic#1610]
## Describe the bug
CTAA seems to now be broken for desktop mode, as shown here: 

## Relevant issues
Not that I'm aware of, I think this may have to do with the recent update as of the time of writing this though.

## To Reproduce
Enable CTAA in the command line, the viewport will still be aliased in desktop mode.

## Expected behavior
CTAA should function as normal.

## Screenshots / Video
![image](https://user-images.githubusercontent.com/9770110/104857274-e0a6a880-58dc-11eb-9c99-efa979a62626.png)

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Neos Version: 2021.1.17.998
 - Neos Platform: Windows
 - Link to reproduction World/Item: Not needed
 - Regression: Yes, worked in all previous builds leading up to this one.

## Additional context
N/A

## Reporters:
Just me as far as I'm aware.

**Comment by Frooxius** [comment]
I'm sorry, but as the legacy desktop mode isn't supported and with a proper one being implemented and this one slowly scrapped, little things like this will break during the process. I will try to preserve as much functionality during the transition as I can so it can be used before the proper one is ready, but I don't plan on tracing smaller bugs like this, as it will add a lot of development time for something that's going away anyway.
