### ISSUE TITLE
Motion Blur disable option

### ISSUE THREAD

**Issue by Arcticgamez** [Frooxius/NeosPublic#1612]
## Is your feature request related to a problem? Please describe.
current motion blur is to strong on desktop users

## Describe the solution you'd like
remove motion blur fully or give users option to disable it

## Describe alternatives you've considered
No alternatives

## Additional context
if this gets fixed in the upcoming desktop mode than you can ignore this but as you can see in the screenshot motion blur on fast moving objects for desktop users scramble their UI and other items in the world.

![2021 01 17-18 07](https://user-images.githubusercontent.com/77081265/104865412-c5459880-58f0-11eb-8cc6-a80f3ba8b468.png)

**Comment by Frooxius** [comment]
This will be covered by the post-processing options, we already have one for that here: https://github.com/Frooxius/NeosPublic/issues/322 Closing as duplicate.
