### ISSUE TITLE
Current Culture node breaks fire on change.

### ISSUE THREAD

**Issue by Psychpsyo** [Frooxius/NeosPublic#1613]
## Describe the bug
When plugging a Current Culture node into a fire on change node, the fire on change node breaks. (turns red)

## To Reproduce
Create both a Current Culture and a fire on change node and connect the current culture into the fire on change.
The fire on change is now red.

## Expected behavior
Fire on change shouldn't break and fire whenever Current Culture changes. (probably with a pulse from the user it changed for)

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Neos Version: Beta 2021.1.17.998
 - Neos Platform: probably any
 - Regression: don't know

## Reporters:
Cameron#7818

**Comment by Frooxius** [comment]
Do you have a log from when this happened? It should contain an exception of this.

**Comment by Frooxius** [comment]
Nevermind I found the issue, it's the CurrentCulture datatype, you can't really use that one with FireOnChange as it's not a Neos-managed type. I'll add protection so you can't create this overload in the next build.

**Comment by Frooxius** [comment]
Fixed in 2021.1.21.1068, thanks!
