### ISSUE TITLE
Offline inventory storage for items 

### ISSUE THREAD

**Issue by alexderpyfox** [Frooxius/NeosPublic#1617]
## Is your feature request related to a problem? Please describe.
Free Storage limitations is mainly the reason needing this feature 

## Relevant issues
Not sure 

## Describe the solution you'd like
Saving objects to a offline folder in the inventory I made a picture in photoshop to show kinda what I mean that I will attach below 
![sketch-1611018900130](https://user-images.githubusercontent.com/61125650/104976845-725a0700-59fe-11eb-8a93-ad163950cf57.png)

## Describe alternatives you've considered
There is not really an alternative to offload inventory items to offline in a simple way 

## Additional context
Important to have for people that can't afford extra storage for reasons

**Comment by Psychpsyo** [comment]
This seems to be very similar to issue #325, if not the same issue.

**Comment by TehTurk** [comment]
Thank you for pointing it out @Psychpsyo I'm going to mark this as duplicate.
