### ISSUE TITLE
Provide a method within UserSpace/NeosDash to get a User reference of the user who owns the Dash.

### ISSUE THREAD

**Issue by ProbablePrime** [Frooxius/NeosPublic#1625]
## Is your feature request related to a problem? Please describe.
I'm trying to build Facets that need to know the owner of the dash. This is for various reasons such as:
- World Filtering
- Information Retrieval from other components
- Information Retrieval from Outside APIs
I can't currently find a way to do this reliably. Please read the alternatives section for things I've tried.

## Relevant issues
I couldn't find anything exactly but will double check.

## Describe the solution you'd like
I'd like a Node or component that gets a regular Neos User Reference of the user who's Dash, my Facets are on/in. I think this is possible due to the profile Facet.

## Describe alternatives you've considered
- Using a Local User Node -> This gets the machine account/Steam Account and NOT the Neos Account
- Doing hacky stuff with the existing Profile Facet -> While possible I don't think this is the correct way. I parse the username out of this facet and then use that as just a username.
- Get Active User -> Dashes don't appear to be actually parented to the user.

## Additional context
This might already be possible and I might have just missed something but I wanted to open this up.

**Comment by Frooxius** [comment]
This doesn't really need any extra method, the LocalUser is the owner of the dash.

The main problem here is that the UserID doesn't get populated once the user signs, so it's not available within the userspace. That's something that can be changed though, which should fix this issue.

**Comment by ProbablePrime** [comment]
Woop, this sounds good. 

Would this also fix the username? 

When using Local User on the dash I see the User's Steam or Machine name. For example in Turk's Case.

Local User in the world: Turk
Local User in the dash: Teh_Turk (Their steam account name)

**Comment by Frooxius** [comment]
Made the changes in 2021.1.29.504, the userspace user will now always be updated with the right UserID and Username! Thanks!
