### ISSUE TITLE
The ActiveNodeType field on a LogiX tooltip does not correctly qualify BaseX types

### ISSUE THREAD

**Issue by chemicalcrux** [Frooxius/NeosPublic#1626]
## Describe the bug
Selecting a node type that's parameterized by a BaseX type results in an invalid type string. For example:

```FrooxEngine.LogiX.Data.DynamicVariableInput`1[BaseX.float3]```

The correct string would be:

```FrooxEngine.LogiX.Data.DynamicVariableInput`1[[BaseX.float3,BaseX]]```

Manually entering the first string does not work; the second one is accepted, but turns into the first one.

## Relevant issues
None found.

## To Reproduce
1. Spawn a LogiX tooltip
2. Select a `DynamicVariableInput<float3>` node from the node browser
3. Inspect the tooltip; observe the incorrect type string

## Expected behavior
The type string should be valid.

## Screenshots / Video
![image](https://user-images.githubusercontent.com/8015368/105207036-06b68d80-5b15-11eb-9ac3-6b314ad8f743.png)

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.1.17.998
 - Neos Platform: Any
 - Link to reproduction World/Item: N/A
 - Regression: No

## Additional context
This does not interfere with normal usage of the tool, and is absolutely low priority. It did not cause a breakage for me.

However, anything that attempts to use this type string will run into problems, and it's nominally incorrect, so it would be nice to have it corrected.

I don't know of any other namespaces to try, but this may occur with non-BaseX types as well. It also might occur in other places where types are validated (I presume it's parsing the type, then turning it back into a string in a context where BaseX doesn't need to be explicitly qualified).

## Reporters:
Just myself.

**Comment by Frooxius** [comment]
The first type string is still valid, it's just not a fully qualified one, which is expected by the parsing. I've changed it in 2021.1.24.1266 so it now shows the fully qualified one so it can be parsed back in all cases. Thanks for report!
