### ISSUE TITLE
AlphaCutoff/AlphaClip should start at 0.5 on all materials

### ISSUE THREAD

**Issue by chemicalcrux** [Frooxius/NeosPublic#1627]
## Is your tweak request related to a problem? Please describe.
Many materials start with an AlphaCutoff of 0 or 0.01 (e.g. UI_UnlitMaterial starts at 0.01), causing ugly borders when using Cutout mode. It took me a little while to work out what was going on the first time.

## Describe what would you like tweaked
All materials should have a default alpha cutoff of 0.5 -- it's the most reasonable value, IMO.

This would make things match the behavior of PBS_Metallic, which starts at 0.5.

## Describe alternatives you've considered
Not forgetting to set it!

## Additional context
I've seen other people also get a bit confused by this -- it's especially weird when it starts at 0, since that prevents transparency entirely in Cutout mode.

edit: the XiexeToonMaterial has a default setting of 0

**Comment by Frooxius** [comment]
The 0.01 is intentional for UI_UnlitMaterial and other UI materials. This done because those materials are typically used for masking when writing to stencil buffer and any areas that aren't fully transparent should remain visible, so for those the default value won't be changed.

Which materials are starting at 0?

**Comment by chemicalcrux** [comment]
Ah, gotcha.

The Xiexe toon material starts at 0. I had written that in the original report, but then I deleted it, whoops.

**Comment by Frooxius** [comment]
Ok I changed it in 2021.1.21.1068! I'm leaving the UI materials as they are, as the AlphaClip has a bit of different use in that context. Please reopen if you find any more materials with invalid default values. Thanks!
