### ISSUE TITLE
Spawning Public Folder breaks all UIX

### ISSUE THREAD

**Issue by marsmaantje** [Frooxius/NeosPublic#1628]
## Describe the bug
after someone opens their context menu on my public folder spawned in from my personal inventory all uix breaks for me.

## To Reproduce
1. spawn out public folder from personal inventory (yellow version of the folder)
2. open context menu and wait a bit
3. all uix is now broken and doesnt update anyome.

## Expected behavior
uix doesnt break when doing this

## Screenshots / Video
https://youtu.be/kfQPshw_x_E

Log of neos version 2021.1.21.1068
[DESKTOP-B3HHEBC - 2021.1.21.1068 - 2021-01-21 22_01_40.log](https://github.com/Frooxius/NeosPublic/files/5852198/DESKTOP-B3HHEBC.-.2021.1.21.1068.-.2021-01-21.22_01_40.log)

log of neos version 2021.1.22.1352
[DESKTOP-B3HHEBC - 2021.1.22.1352 - 2021-01-22 23_51_59.log](https://github.com/Frooxius/NeosPublic/files/5859081/DESKTOP-B3HHEBC.-.2021.1.22.1352.-.2021-01-22.23_51_59.log)

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos?  Only when redoing the steps
 - Neos Version: 2021.1.22.1352
 - Neos Platform: Windows
 - Link to reproduction World/Item: [Optional, but can speed up response for more complex reproduction cases]
 - Regression: 2021.1.17.1026

## Additional context
only appears to happen for some people, I know that me (marsmaantje) and Psychpsyo had this issue happen to us.

## Reporters:
me, marsmaantje

**Comment by chemicalcrux** [comment]
I am observing this. Existing inspector windows work (but don't highlight their buttons), and my finger camera preview is suddenly huge.

**Comment by chemicalcrux** [comment]
I tested this more carefully. Just *spawning* the folder causes the breakage to occur. Destroying it seemed to help a bit, but I was still experiencing major problems afterward.

[CRUX - 2021.1.21.1068 - 2021-01-21 16_35_06.log](https://github.com/Frooxius/NeosPublic/files/5852348/CRUX.-.2021.1.21.1068.-.2021-01-21.16_35_06.log)

I marked four points in the log by triggering an "Exception Updating ActiveToolTip" line in the log:

1. Selecting the folder
2. Spawning the folder
3. Experiencing serious lag (logix wires were dragging very slowly here)
4. About to quit

The game froze when quitting, and I had to forcibly kill it.

Spawning my own folder by pasting in a link was fine.

**Comment by Frooxius** [comment]
This seems a little bit strange, there's not really any logic that would be running on the InventoryLink or the menu item that could cause this, I think this is just a coincidence that it happens around that or very loosely related. 

I've fixed a bunch of exceptions and issues I've seen in your logs in 2021.1.22.1352 that might be potential culprit. Can you check if the issue still persists?

If so, can this be replicated even in a very simple empty world, without not much else? Would things like changing your avatar to something simple affect it too?

**Comment by chemicalcrux** [comment]
I can't reproduce this anymore, including when spawning a brand-new folder, as well as while wearing the same avatar that I was previously using (in the off chance that would somehow matter). I also cannot reproduce the bug on the previous build (1068) anymore. It doesn't happen in desktop or in VR.

This is very strange, because I ran into the problem quite a few times in a row across several restarts and worlds.

My logs don't have any of the exceptions I was seeing while the bug was happening.

**Comment by marsmaantje** [comment]
After completely reïnstalling the game the issue doesnt appear anymore.
Will close this issue now since it was probably something corrupted on my pc causing the issue.
