### ISSUE TITLE
Certain shaders broken after Asset Variance System update

### ISSUE THREAD

**Issue by H3BO3** [Frooxius/NeosPublic#1630]
Certain shaders seem to be broken after the recent update, in particular the PBS Specular and both standard variants of the PBS Triplanar materials. Logs seem to have a lot of NotFound errors when attempting to load shaders.

[DESKTOP-COAS4OS_-_2021.1.21.1068_-_2021-01-21_17_20_56.log](https://github.com/Frooxius/NeosPublic/files/5852788/DESKTOP-COAS4OS_-_2021.1.21.1068_-_2021-01-21_17_20_56.log) (Log from Lavy)

## To Reproduce
Using the material tooltip, create an orb (Triplanar was used in a replication test, seems both specular and metallic are broken). The material spawns fine, but once you add a texture to the material it turns pink.

Lavy#4181 running the replication
![image](https://user-images.githubusercontent.com/62123804/105427260-f7fdd280-5c09-11eb-9c4e-9b72b0a9214a.png)

EvawdnousCimota#2730 reporting that PBS Specular broke on their avatar. Switching the material to PBS Metallic mitigated it.
![image](https://user-images.githubusercontent.com/62123804/105427018-7ad25d80-5c09-11eb-9ba9-03123366772e.png)

Another picture of Lavy's world, which uses triplanar shaders.
![image](https://user-images.githubusercontent.com/62123804/105428054-c84fca00-5c0b-11eb-939b-64e9f8f2ec61.png)

Kulza#8623 showing misbehaving materials
![image](https://user-images.githubusercontent.com/62123804/105428306-5926a580-5c0c-11eb-901e-caf51b9b6778.png)

 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.1.21.1068

## Reporters:
Lavy#4181 EvawdnousCimota#2730 ArcticGamez#1496 Kulza#8623

**Comment by chemicalcrux** [comment]
I did not observe breakage with PBS_Specular, but I did with the triplanars.

The triplanars break a predictable amount of time after a texture is assigned. They do not break by themselves. Duplicating them results in the checkerboard pattern that unloaded materials get.

**Comment by shiftyscales** [comment]
> Cloud update
Pushed a small update to the cloud, fixing invalid shader variant descriptor comparisons, which was causing some shaders to not load and variant versions to get constantly spammed. They should now load in-game now and headless should stop spamming them indefinitely (reported by @ AshtonSparx, @ Rue Shejn | Artist 3D and others).

This should hopefully be resolved now.
