### ISSUE TITLE
seems "FLAC"(recoding format) not using i18n In microphone tip context menu

### ISSUE THREAD

**Issue by kazu0617** [Frooxius/NeosPublic#1631]
As title says. in context menu, japanese translate using "FLACファイル" but in Neos shows "FLAC".
![image](https://user-images.githubusercontent.com/6259214/105448169-21296c00-5cb9-11eb-8f23-29539666d0d9.png)

## Is your tweak request related to a problem? Please describe.
Nothing.
## Describe what would you like tweaked
just forgot to use i18n locale. apply it.

## Describe alternatives you've considered
To have a mind that doesn't care.

## Additional context
Sorry for the really small point.

**Comment by Frooxius** [comment]
Does this happen when you switch languages back and forth? I have tested this on the latest build, but the menu item is translated. It already uses the locale key:
![image](https://user-images.githubusercontent.com/8838625/105494551-43bc8480-5cbb-11eb-9dbd-9b60d9ed7ec0.png)

I'm not sure why is it still using the English one in your case, it might be a temporary problem when switching languages.

**Comment by kazu0617** [comment]
Oh...sorry, I updated to the latest version, checked the file, and started it up, and it displayed "FLACファイル" correctly. Perhaps something had changed in the file. I'll close it for now.
