### ISSUE TITLE
Cleanup Bone Colliders Deletes Child Slots

### ISSUE THREAD

**Issue by Medravr** [Frooxius/NeosPublic#1633]
## Describe the bug
Cleanup Bone Colliders Deletes Child Slots of an Avatar.

## To Reproduce
1. Using any rigged avatar. Find the Rig component in the respective slot.
2. Click on Cleanup Bone Colliders

## Bug information
It is easily repeatable.

## Reporters:
Medra

**Comment by H3BO3** [comment]
When you say child slots, are you referring to arbitrary children, like certain non-rig items, or that it deletes all children? From what I understand that option is designed to be used for basic skinned mesh processing on first import.

**Comment by Medravr** [comment]
Ever single slot underneath the parent of the slot containing the rig component is deleted: including materials, mesh, everything. Not just the bones or their colliders.

**Comment by Frooxius** [comment]
Should be fixed in 2021.1.22.1352, thanks!
