### ISSUE TITLE
Customizable default settings for the NeosUIStyle component

### ISSUE THREAD

**Issue by Psychpsyo** [Frooxius/NeosPublic#1634]
## Is your feature request related to a problem? Please describe.
Some people do not like the orange color that Neos UI elements spawn with. (Inspectors, video players, avatar creator...)

## Describe the solution you'd like
Give us the option to override the material that is used for these components when they are spawned.

## Describe alternatives you've considered
People are already making things like custom inspectors that have different colors and varying levels of transparency. But this way it'd take forever to make a custom version of every component that uses the orange UI material.
A plugin might also work (not sure) but at that point it's way too technical for the average user.

**Comment by ProbablePrime** [comment]
A component exists called Neos UI Style. When applied to UI Elements it will cause them to have different colors. You can see my video on this here: https://youtu.be/PUgZS-QndK0

What's actually more likely for the inspectors is that they will be completely re-designed when they are re-worked so I'm not sure what benefit editing the older inspectors will be.

**Comment by Frooxius** [comment]
You can use the component that @ProbablePrime has mentioned to adjust the colors on your own UI's, but I'd generally recommend not using them for any new projects, as those elements are legacy and I don't plan on adding any new functionality to them.

@ProbablePrime Is correct there as well, inspectors and other UI's will switch over to a new, more customizable system with the Facet architecture and the old mesh based one will be deprecated. For physical elements I recommend using generalized versions, like PhysicalButton, Joints, Touchable and so on to make templates.
