### ISSUE TITLE
User inspector doesn't report own packet loss properly

### ISSUE THREAD

**Issue by Psychpsyo** [Frooxius/NeosPublic#1635]
## Is your tweak request related to a problem? Please describe.
Checking your own opus stream packet loss with the user inspector is not possible.

## Describe what would you like tweaked
The user inspector should report the actual packet loss for your own opus stream instead of reporting 0 lost packets and a packet loss of -100%.

## Describe alternatives you've considered
Keeping it like this and have the info displayed be completely useless.

**Comment by Frooxius** [comment]
This is normal. You're not transmitting any packets to yourself, so this information is meaningless when you view your own data.
