### ISSUE TITLE
Attach Component dialogue is useable by guests.

### ISSUE THREAD

**Issue by Psychpsyo** [Frooxius/NeosPublic#1636]
## Is your tweak request related to a problem? Please describe.
Non-builders can click buttons in the Attach Component dialogue of an inspector, causing it to close. (the component is not added)

## Describe what would you like tweaked
The Attach Component dialogue should be tagged as developer so only builders can interact with it.

## Describe alternatives you've considered
Keeping it this way which can be mildly annoying and confusing at times.

**Comment by Frooxius** [comment]
Fixed in 2021.1.24.1266, thanks!
