### ISSUE TITLE
SmoothValue<floatQ> behaves strangely when first driving a rotation

### ISSUE THREAD

**Issue by Zyzyl** [Frooxius/NeosPublic#1640]
## Description
When a slot rotation field becomes driven by a SmoothValue<floatQ> component, the first rotation change does not happen smoothly. Instead it appears to take a variable amount of time before the rotation jumps to the target rotation. Subsequent changes result in the expected smooth rotation. Nulling the SmoothValue<floatQ> Value field and then re-entering the previously driven rotation results in the expected smooth changes. Creating a second SmoothValue<floatQ> component and repeating the steps again demonstrates the issue.

## Relevant issues
I couldn't find any obvious ones.

## To Reproduce
1. Create an empty world
2. With a developer tooltip create a new 3D object, e.g. cylinder.
3. Inspect the newly created object, reset rotation.
4. Attach a SmoothValue<floatQ> component
5. Drag and drop a reference to the rotation field of the object into the Value field of the SmoothValue<floatQ> component.
6. Change the target rotation to e.g. 40,0,0
7. The change is not applied immediately. Rotation suddenly jumps after an apparently random amount of time (usually ~5-20 seconds).

## Expected behavior
Once a rotation field becomes driven by the SmoothValue<floatQ> changes to the target rotation should result in immediate, smooth changes in the driven field.

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.1.22.1352
 - Neos Platform: Windows (VR user)
 - Regression: Unsure

## Additional context
I've taken one other user through the reproduction steps and the issue occurred as described. If there are problems reproducing this I'm happy to make a video.

## Reporters:
Zyzyl#1441
Rukio#0001 also helped test reproducibility

**Comment by Frooxius** [comment]
Should be fixed in 2021.1.24.1266, thanks for the report!
