### ISSUE TITLE
Disallowing JumpToUser permission also blocks self-respawning via the dash Session/Users page.

### ISSUE THREAD

**Issue by Zyzyl** [Frooxius/NeosPublic#1641]
## Describe the bug
If the JumpToUser field under the LocomotionPermissions component is set to `Disallow`, users with the affected role cannot use the 'Respawn' button in the dash session/users page - it is greyed out and not clickable.

## Relevant issues
Couldn't find any obvious ones.

## To Reproduce
1. Create an empty world
2. Find the LocomotionPermissions component under Roles/Spectator Permissions
3. Change the JumpToUser field to `Disallow`
4. Other users who join and are set to the Spectator role cannot respawn themselves via the dash.

## Expected behavior
I, and others who have seen this, expected that the ability for users to self-respawn should be independent from the ability to jump to other users. I assume that it is intended that they should be so, since the respawn gesture still works even though the option in the dash is unavailable.

## Bug information
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.1.22.1352
 - Neos Platform: Windows, I haven't tested on others.
 - Regression: Unsure

## Reporters:
Zyzyl#1441
Rukio#0001 mentioned the bug to me and showed me how to reproduce (@Ruikio)

**Comment by Frooxius** [comment]
Fixed in 2021.1.24.1266, thanks for report!
