### ISSUE TITLE
PBS splat shader ability to scale individual textures

### ISSUE THREAD

**Issue by Xqua** [Frooxius/NeosPublic#1642]
## Is your feature request related to a problem? Please describe.
Sort of, right now the splat shader only allows for one global scaling factor. So each texture needs to be repacked manually with a factor 2 4 8 etc. It's impossible to fine tune each seamless texture. 

## Relevant issues
None that I could find on GitHub

## Describe the solution you'd like
A simple modification of the shader code to take 4 scaling parameters instead of 1 global one. And parameter access on the UI of the material editor. 

## Describe alternatives you've considered
The alternative is to take the texture and to manually repack it, for example if I want to divide one by two, I take the texture and save it into a 2x2 square of this texture. It's quite tedious and requires to know in advance how it's going to look in World.

**Comment by Frooxius** [comment]
I'm sorry, but this is unfortunately not technically possible for this shader. It uses packed normal maps, emission map and height map, which are sampled in one operation, to get around some hardware sampler limitations (it's already hitting a limit with how much stuff it has). As such the scale/offset of all 4 textures is locked together and not separable.

The shader assumes that you have authored your textures for your splat map, so you'll unfortunately have to make the adjustments before inputting them into this. 

For more complex setups, you'll have to wait for the terrain system: https://github.com/Frooxius/NeosPublic/issues/118
