### ISSUE TITLE
Make Badge names are descriptive of badge icon

### ISSUE THREAD

**Issue by Earthmark** [Frooxius/NeosPublic#1644]
## Is your tweak request related to a problem? Please describe.
I worry that badge flaunting can lead to a culture of eliteism, so I hide all of my badges to help feel more like an average user. However, there are some badges that I should be showing (such as world host), but I don't because I can't robustly distinguish one badge from any other without visually confirming the badges.

This is coming up as I plan to apply for the mentor program, and I believe that's a badge-ish role. However with my current badge stance that badge would not be visible (as my badges all are inactive by default).

## Describe what would you like tweaked
I would like the slot names of each badge to be a name descriptive of what the badge is, for instance in the following picture these could be plausible names:

- Host
- Join Year
- Patreon
- Expendable Income
- User Badge U-CoffeeWhateverUserId
- MMC 2020
- MMC World 3rd place

![image](https://user-images.githubusercontent.com/1251609/105614165-82664380-5d7c-11eb-999d-1af617cadf4e.png)

Obviously these are just proposals, categorized names may be nice (like Join Year not being specifically 2020, but representing any join year with a generalized name), but that could also be an issue so spelling out each badge like it's a key in a table of badges would certainly be viable as well.

Even assigning a predictable hash to the name would work for me, I just need some way to know which badges to not hide.

## Describe alternatives you've considered
Counting badge slots, but it's brittle and not reusable by others. 
Making all badges on myself inactive, this works but doesn't show others that I'm the host. Granted this has never come up as an actual issue.
Waiting for more robust badge management, this is far down the line to my knowledge and my hope is bringing attention to the existing naming bug can allow a small pivot to a behavior that can be a stop gap.

## Additional context
I am fairly sure the code that generates those names has an existing bug already, as the name scheme seems to imply a name collision avoidance script is accidently incrementing in a way it should not.
So, if that bug was resolved with names that describe badges instead of an incrementing number, that would be nice for my usages!

**Comment by Earthmark** [comment]
This is possibly related to #356

**Comment by Frooxius** [comment]
They should be descriptive in 2021.1.26.1308 now, thanks!
