### ISSUE TITLE
Set primary controller to 'Right' by default

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#1645]
## Is your tweak request related to a problem? Please describe.
Reportedly, new users have been having control issues in Neos, on launching up a fresh local database, I discovered the left controller is set to the primary controller by default, a reverse of what a majority of users would expect.

## Describe what would you like tweaked
Set the primary controller to 'right' as the default option.

**Comment by Aerizeon** [comment]
Perhaps primary controller selection should be added to the initial setup (along with language settings), in addition to defaulting to right-hand control.

**Comment by shiftyscales** [comment]
It already is there, @Aerizeon.

**Comment by Aerizeon** [comment]
Are they just skipping that page somehow then?

**Comment by shiftyscales** [comment]
Possibly. Clicking through without reading, or misinterpretting it. I couldn't say as I haven't had any contact with such users. I've just been hearing reports from others about new users that have had some confusion with their control scheme, and identified that as a possible factor.

**Comment by Frooxius** [comment]
Changed in 2021.1.24.1266, thanks!
