### ISSUE TITLE
XNOR Bug

### ISSUE THREAD

**Issue by bentallea** [Frooxius/NeosPublic#1647]
## Describe the bug
XNOR logix node behave as XOR logix node with 2 inputs but behave correctly with three inputs. 

## Expected behavior
With 2 inputs to an XNOR node, Should return true when both inputs are true or false, and should return false when one node is false. 

## Screenshots / Video
https://youtu.be/Eudh_fzRnis

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.21.23
 - Neos Platform: Windows
 - Regression: Believed to be no, but is unknown.

## Reporters:
Rubik, Ballistic

**Comment by Frooxius** [comment]
Fixed in 2021.1.24.1266, thanks for reporting!
