### ISSUE TITLE
Logix does not support all http methods.

### ISSUE THREAD

**Issue by Psychpsyo** [Frooxius/NeosPublic#1650]
## Is your feature request related to a problem? Please describe.
I am trying to use logix to interface with an API which requires me to use an http PATCH request for certain things.

## Describe the solution you'd like
I'd like logix nodes for the additional http methods beyond the already supported GET and POST.
I'm mainly concerned with PUT, PATCH and DELETE but it'd be nice to have access to all of them. (That would additionally include HEAD, OPTIONS, CONNECT and TRACE)

## Describe alternatives you've considered
Using a custom websocket inbetween Neos and APIs/websites that rely on these methods, not communicating with such APIs/websites or hoping that they'll accept malformed requests and make their functions accessible through only GET and POST.

**Comment by Frooxius** [comment]
We already have topic for this here: https://github.com/Frooxius/NeosPublic/issues/1069
