### ISSUE TITLE
GLTF does not import with blendshapes

### ISSUE THREAD

**Issue by AegisTheWolf** [Frooxius/NeosPublic#1651]
## Describe the bug
Importing a GLTF that has blendshapes/shapekeys does not appear in game. 
Meshes with blendshapes are imported as static meshes, Rigged/armature weighted meshes import as skinned mesh, and rigged meshes with blendshapes import as a skinned mesh without blendshapes.

## Relevant issues
Avatar models imported as GLTF do not have blendshapes

## To Reproduce
[Steps to reproduce the behavior:

->Prepare a model file with blenshapes/shapekeys

->Export model as GLTF

->Import GLTF models into Neos

## Expected behavior
Upon checking the meshes within the model that should contain blendshapes there are none to be found and a non-rigged mesh with shapekeys does not import as a skinned mesh.

## Screenshots / Video
![image](https://user-images.githubusercontent.com/65252793/105637214-e565e200-5e31-11eb-9760-ca0e026a55b8.png)
![2021-01-24 10 49 11](https://user-images.githubusercontent.com/65252793/105637238-062e3780-5e32-11eb-925f-d9e3e579cf68.jpg)
![image](https://user-images.githubusercontent.com/65252793/105637256-2958e700-5e32-11eb-931d-b3b2434d2d54.png)
![2021-01-24 10 48 56](https://user-images.githubusercontent.com/65252793/105637265-3b3a8a00-5e32-11eb-9bea-1e59611ee5e4.jpg)

## Bug information (please complete the following information):
 - How often does it happen: [Always, Sometimes, Only Once]
 - Does the bug persist after restarting Neos? [Yes/No]
 - Neos Version: [version number]
 - Neos Platform: [Any, Windows, Linux, Android/Quest]
 - Link to reproduction World/Item: [Optional, but can speed up response for more complex reproduction cases]
 - Regression: [Did this work before? Yes (which build?) / No]

## Additional context
I have tried importing a GLTF with and without blender in the tools folder in neos' local files.  Blender 2.90 was used to test 
both states resulted in no blendshapes within the meshes that have blendshapes

## Reporters:
MattyK, Aegis_Wolf, 3x1t_5tyl3

**Comment by 3x1t-5tyl3** [comment]
So I did some testing. None of these files work properly on my end.
These can be recreated in blender by just adding a new mesh and adding a shapekey.

Some examples:
[NeosBugTest-1651.zip](https://github.com/Frooxius/NeosPublic/files/5865082/NeosBugTest-1651.zip)

**Comment by Frooxius** [comment]
Updated Assimp to latest version in 2021.1.26.1308, those models should now import correctly. Thanks for the samples and report!
