### ISSUE TITLE
Fire on change works when broken.

### ISSUE THREAD

**Issue by Psychpsyo** [Frooxius/NeosPublic#1652]
## Describe the bug
A broken (red) fire on change node still fires on change.

## Relevant issues
I didn't find any.

## To Reproduce
Create a pulse relay and connect it to itself.
Connect a fire on change to it.
Change the fire on change's input multiple times. (first one will break the node and relay, subsequent ones will still cause lag and presumably re-break the logix.)

## Expected behavior
Fire on change should not fire on change once broken.

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: Beta 2021.1.22.1352
 - Neos Platform: Probably any, known Windows
 - Regression: Don't know.

## Reporters:
Cameron#7818

**Comment by Psychpsyo** [comment]
I've just been informed that Pulse inputs also do this.

**Comment by Frooxius** [comment]
Fixed the broken nodes not being broken in 2021.1.24.1266! :D Thanks for report!

**Comment by Psychpsyo** [comment]
Reopening this as I did some more testing. Here's some other nodes that work while broken:

Button Events, Debug Line, Debug Axes, Debug Box, Debug Sphere, Debug Text, Debug Triangle, Debug Vector, Equip Avatar, Trigger Haptics On Controller, On Destroying, On Loaded, Write, Write Ref, --, Write Latch, On Destroy, On Deactivated, Boolean Latch, Delay, Delay With Value, Dynamic Impulse Trigger, Local Fire on True, Local Fire on False, Updates Delay, On Start, On Activated, One per Frame, On Duplicate, Impulse Multiplexer, Pulse Random, Local Fire on Change, Dynamic Impulse Receiver, Impulse Timeout, Sequence, Impulse Demultiplexer, Updates Delay With Value, ++, Drive, Tween, Drive Playback, Play Oneshot, Play Oneshot and Wait.
