### ISSUE TITLE
Deleting a users armature breaks cameras

### ISSUE THREAD

**Issue by du27y** [Frooxius/NeosPublic#1658]
## Describe the bug
Deleting the Armature of a player and trying to take a photo of said player will delete the player taking a photo with a Neos Camera. The Finger Photo just breaks and doesn't output an image. If that user then switches into a different, working avatar cameras break for that instance

## To Reproduce
1. Delete a users Armature
2. Take out a Neos Camera from the Neos Essentials
3. Take a photo of the user without an armature

## Expected behavior
The camera takes a photo of the user

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: Beta 2021.1.24.1327
 - Neos Platform: Windows
 - Regression: Yes (Any Prior build within January)

## Reporters:
ItsDusty

**Comment by Frooxius** [comment]
Do you have logs for the user who got deleted doing this for both the Neos Camera and the finger photo? There's likely an exception somewhere that causes this.

**Comment by du27y** [comment]
> Do you have logs for the user who got deleted doing this for both the Neos Camera and the finger photo? There's likely an exception somewhere that causes this.

Sure thing. I will attach the logs provided by U-Axel for this as he is the one who took the photo

https://drive.google.com/file/d/13RBZz_n0p0x5i5WhYvCEJKm-vGn_TUnV/view?usp=sharing

**Comment by Frooxius** [comment]
Should be fixed in 2021.1.29.504, thanks for report and log!
