### ISSUE TITLE
BooleanValueDriver<floatQ> breaks Smooth Transform (rotation) / SmoothValue<floatQ>

### ISSUE THREAD

**Issue by Zyzyl** [Frooxius/NeosPublic#1664]
## Description
Driving the TargetRotation / TargetValue fields of the SmoothTransform / SmoothValue<floatQ> components with a BooleanValueDriver<floatQ> causes the drive target of the SmoothTransform/SmoothValue component not to rotate smoothly. Instead, while the TargetRotation/TargetValue field updates correctly, the rotation of the SmoothTransform/SmoothValue component target does not.

## Relevant issues
First spotted in the context of https://github.com/Frooxius/NeosPublic/issues/1640 (which is fixed, thanks) but I initially assumed they had a common cause.

## To Reproduce
1. Create an empty world
2. With a developer tooltip create a new 3D object, e.g. cylinder.
3. Inspect the newly created object and attach a SmoothValue<floatQ>/SmoothTransform component
4. Drive the object's rotation field with the SmoothValue<floatQ>/SmoothTransform component
5. Add a BooleanValueDriver<floatQ> and drive the RotationTarget/ValueTarget field of the SmoothTransform/SmoothValue<floatQ> component. Enter a rotation in one or both of the BooleanValueDriver's True/FalseValue fields.
6. The object's rotation does not smoothly change when the State field of the BooleanValueDriver is toggled. Instead the object remains at it's previous rotation value.

## Expected behavior
Rotation of the object should change smoothly as a result of changing the 

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.1.24.1327
 - Neos Platform: Windows (tested in VR)
 - Regression: No

## Reporters:
Zyzyl#1441

**Comment by Frooxius** [comment]
I'm sorry, but I don't fully understand the setup. Which field exactly are you trying to drive with the BooleanValueDriver? I'm not sure what does "Target field of the Smooth" refer to in this case.

**Comment by Zyzyl** [comment]
Ah, sorry. I'm driving the TargetRotation/TargetValue on the SmoothTransform/SmoothValue<floatQ> component with the BooleanValueDriver. In turn I'm driving the rotation field of the object with the SmoothTransform/SmoothValue<floatQ>.

I hope that's clearer.

**Comment by Frooxius** [comment]
I'd recommend just avoid doing wildcards like that and focus on specific example, I'm having a a lot of trouble mentally parsing the description like that, sorry!

What exactly is happening to the rotation instead? Does it jump to the target value immediately?

**Comment by Zyzyl** [comment]
Totally fine, I'll be more explicit in the future. The rotation driven by the SmoothTransform/SmoothValue<floatQ> does not appear to change when the State field of the BooleanValueSwitcher is toggled. It's possible that the rotation suddenly jumps after a while, but I didn't observe that after waiting ~30 seconds when testing.

I've edited the main post too.

**Comment by Frooxius** [comment]
I found what it is, the default values weren't initialized properly, so the quaternions were degenerate. Simply assigning a rotation to both True and False would fix this, but I've fixed initialization of default values in 2021.1.26.1308, thanks!
