### ISSUE TITLE
The Interpolate setting of ValueGradientDriver<floatQ> doesn't work properly

### ISSUE THREAD

**Issue by Zyzyl** [Frooxius/NeosPublic#1665]
## Description
A rotation driven by the ValueGradientDriver<floatQ> (with the Interpolate field = True) snaps between rotation points rather than rotating between points continuously when the Progress field of the ValueGradientDriver changes.

## Relevant issues
Plausibly related to https://github.com/Frooxius/NeosPublic/issues/1640 and https://github.com/Frooxius/NeosPublic/issues/1664

## To Reproduce
1. Start empty world
2. Create a new object with dev tip (to visualise changes)
3. Add a ValueGradientDriver<floatQ> and drive the rotation of the object.
4. In the inspector window, press the Add button on the ValueGradientDriver component to add two set points to the component Points list.
5. Enter arbitrary values into the ValueGradientDriver set points (e.g. [0,0,0] and [30,0,0]) and drag the position slider of point 1 to 1.00.
6. Ensure the Interpolate field is True
7. Dragging the Progress slider of the ValueGradientDriver results in the rotation of the object snapping between the two set point values.

## Expected behavior
Interpolation by the component is expected to provide continuous rotation values between set points, analogous to the Constant S/Lerp LogiX nodes.

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.1.24.1327
 - Neos Platform: Windows (tested in VR)
 - Regression: Unclear

## Reporters:
Zyzyl#1441

**Comment by StarfishHidari** [comment]
I've been struggling with this bug for a while and usually used ValueGradientDriver<float3> in order to get around it

**Comment by Frooxius** [comment]
Should be fixed in 2021.1.29.504, same issue as others, the default values were initialized to degenerate quaternions. Thanks for report!
