### ISSUE TITLE
Adding children to a slot in response to its own activation causes it to break and become stuck active

### ISSUE THREAD

**Issue by chemicalcrux** [Frooxius/NeosPublic#1666]
## Describe the bug
If a node has children added to it in response to its own activation, an exception is triggered. The slot becomes stuck active, and cannot be deactivated by any means.

## Relevant issues
None seen.

## To Reproduce
1. Create a slot with two children: one for LogiX, one to duplicate
2. Pack LogiX that, using the `On Activated` node, duplicates the second slot, into the first slot
3. Deactivate and reactivate the parent slot
4. Try to deactivate the parent slot again

## Expected behavior
The activation should complete successfully, and the parent slot should not be broken.

## Screenshots / Video
![image](https://user-images.githubusercontent.com/8015368/105773685-496fcf80-5f32-11eb-97cc-78daca886634.png)
![image](https://user-images.githubusercontent.com/8015368/105773688-4bd22980-5f32-11eb-90bf-1ace2ca89f48.png)

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.1.24.1266
 - Neos Platform: Any
 - Link to reproduction World/Item: N/A
 - Regression: Unknown

## Additional context
Duplicating the broken slot produces a slot that works as expected. The issue also goes away on world load.

Deactivating and activating the LogiX slot does not cause any issues.

This log depicts me deactivating and activating the slot (line 223) and then trying to deactivate it again (line 276):

[CRUX - 2021.1.24.1327 - 2021-01-25 17_28_39.log](https://github.com/Frooxius/NeosPublic/files/5870040/CRUX.-.2021.1.24.1327.-.2021-01-25.17_28_39.log)

## Reporters:
Just myself.

**Comment by TehTurk** [comment]
I'm aware for some Events nodes, they happen the instance the event is triggered, like to the point where stuff is detected before parent placement can occur ( as an example). I know this has happened with a few event nodes, it also happens similarly with SlotChildrenEvents Node as well and you try to do stuff to something before it exists sometimes.

**Comment by Frooxius** [comment]
Should be fixed in 2021.1.26.1308, thanks for report!
