### ISSUE TITLE
voice mode indicator

### ISSUE THREAD

**Issue by jeanahelver** [Frooxius/NeosPublic#1671]
an indicator in users peripheral, similar to new messages indicator. if user is muted/wisper/shout/broadcast.
perhaps also one as a badge icon.

noticed a couple times people forget there muted or in broadcast, a visual indicator might help.
may also be helpfull to see the icon in sesions user tab.

**Comment by Abysmal2134** [comment]
I would actually prefer if we could have a facet holder that we can place the whole audio indicator/switcher facet, and maybe a locomotion switcher down the line.

Currently if I want to mute myself quickly I have to open the menu, and if I place a copy of the audio facet in my userspace, it doesn't follow my POV or save when e I exit Neos.

**Comment by 3x1t-5tyl3** [comment]
@Abysmal2134 I'd probably recommend a read through #586 Given you're describing something already mentioned :P

**Comment by Frooxius** [comment]
We already have issue for this here: https://github.com/Frooxius/NeosPublic/issues/808
