### ISSUE TITLE
^ node should be called XOR

### ISSUE THREAD

**Issue by Psychpsyo** [Frooxius/NeosPublic#1673]
## Is your tweak request related to a problem? Please describe.
The XOR node is labeled ^. This can lead to confusion with the exponent function. (which is the pow node)

## Describe what would you like tweaked
Relabel it to XOR, as XNOR also has its name written out. (and to reduce the potential for confusion)

## Describe alternatives you've considered
Keeping it like this. Which is fine, as ^ is the symbol for XOR but it introduces unnecessary ambiguity, especially since node names are already a mix of math and programmer spellings.

**Comment by Frooxius** [comment]
We have topic for this here already: https://github.com/Frooxius/NeosPublic/issues/795

In short, I'd like to update the nodes with simple graphic visuals, which can have both the name and a symbol where possible.
