### ISSUE TITLE
Set doppler default to 0 on user audio streams

### ISSUE THREAD

**Issue by StarfishHidari** [Frooxius/NeosPublic#1674]
## Is your tweak request related to a problem? Please describe.
Currently when a user starts an audio stream, the audio output on their stream panel has the Doppler set to 1 by default, making it so if you run around quickly it distorts the audio, which people probably don't want when they're likely streaming music or anything else

## Describe what would you like tweaked
Change the doppler level of the audio output on the audio stream panel to 0

## Describe alternatives you've considered
Don't really know any alternatives

**Comment by Frooxius** [comment]
Ooops, forgot to set this to 0. Set in 2021.1.29.504, thank you!
