### ISSUE TITLE
NewLine LogiX node (understandably) doesn't match against line endings from other platforms

### ISSUE THREAD

**Issue by Aerizeon** [Frooxius/NeosPublic#1676]
## Is your tweak request related to a problem? Please describe.
While attempting to use `NewLine` in conjunction with `IndexOfString`, I noticed that it does not match against newlines in a LogiXString created from a Linux text file (which only contain the LF character), while working as expected when provided a LogiXString from a windows-created file (which contains CR + LF).

Presumably, this would also fail when provided a LogixString from a file with "mac" line endings as well (CR only), at least when not running on the platform the file originated on (Since the node seems to provide the result of `Environment.NewLine`)

## Describe what would you like tweaked
One or more of the following:

- Provide an enum that can be passed into the Newline node, that allows selection between the various line endings (and that of the current platform)
- Provide specific nodes for each line ending type
- A logix node specific to parsing strings by line (perhaps a wrapper around [`StringReader.ReadLine`](https://docs.microsoft.com/en-us/dotnet/api/system.io.stringreader.readline?view=netframework-4.6.1) which works with all line endings) 

## Describe alternatives you've considered
It is currently possible to work around this by creating a string from the character (for LF, passing '10' into the `FromUTF16` node, and passing the resulting character into a `ToString` node)

**Comment by Frooxius** [comment]
This is normal, this node only provides the newline of the current environment, handling different formats and conventions is what you need to do on your end.

It essentially just wraps this: https://docs.microsoft.com/en-us/dotnet/api/system.environment.newline?view=net-5.0

More parsing functions that help out will be added once collections are in.
