### ISSUE TITLE
New cloud metadata generation not working (or exceedingly slow) on newly imported objects

### ISSUE THREAD

**Issue by Aerizeon** [Frooxius/NeosPublic#1678]
## Describe the bug
Importing new meshes properly displays on the local client, however all other clients in the session will not see the mesh.
If the mesh is saved to inventory, after a bit of time it can be spawned again with the metadata generated - however it never seems to complete when spawned directly in the world.

## To Reproduce
1. Start a new empty world, and invite another user
2. Have the other user import an object from their computer
3. Open an inspector. You can observe that the hierarchy of the object imported correctly, however all StaticMesh references will have invalid information, and display nothing.
4. Have the user save the object to their inventory, and wait a few moments
5. Spawn the object from inventory. Now, the metadata correctly loads.

## Expected behavior
The metadata generated by the user who spawned the mesh should be propagated to all users in the session 

## Screenshots / Video
![Example](http://files.aerizeon.net/sharex/2021/Photo_in_TheTest.png)

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.1.26.1308
 - Neos Platform: Windows
 - Regression: Yes, from 2021.1.24.1327

## Reporters:
Epsilion
Punapple
Soylent

**Comment by Frooxius** [comment]
Thanks for report!

This is just some missing code in metadata negotiation for P2P transfers that causes the transfer to just get stuck for any locally imported mesh. If you see the mesh after import, the metadata has already been generated, the cloud metadata system doesn't get involved at all.

I've got a fix coming in a bit!

**Comment by Frooxius** [comment]
Ok pushed a hotfix 2021.1.27.369 that should fix this, thanks again!
