### ISSUE TITLE
Ref Arrows have repeating, not clamped texture.

### ISSUE THREAD

**Issue by Psychpsyo** [Frooxius/NeosPublic#1681]
## Is your tweak request related to a problem? Please describe.
The texture on a ref arrow is repeating which makes its wide border show up on the thin edge.

## Describe what would you like tweaked
Change the default texture to clamp instead of repeat.

## Describe alternatives you've considered
Keeping it like this or changing it in every session manually.

**Comment by 3x1t-5tyl3** [comment]
Duplicate of #1093

**Comment by Frooxius** [comment]
Yeah this is duplicate of https://github.com/Frooxius/NeosPublic/issues/1093

**Comment by Psychpsyo** [comment]
Sorry for often not finding these before I open new ones.
