### ISSUE TITLE
VirtualMultiKey does not respect disabled state.

### ISSUE THREAD

**Issue by Psychpsyo** [Frooxius/NeosPublic#1683]
## Describe the bug
VirtualMultiKey works when it is disabled.

## Relevant issues
#1638
#1461
## To Reproduce
Disable a VirtualMultiKey component.
It still works.

## Expected behavior
It should not work.

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: Beta 2021.1.27.369
 - Neos Platform: Probably any.
 - Regression: Don't know.

## Reporters:
Cameron#7818

**Comment by Frooxius** [comment]
I've made general change in 2021.1.29.504, which will prevent any disabled component from receiving the button events sent on the same slot as the button. Thanks!
