### ISSUE TITLE
Holding multiple folders creates an arc for each

### ISSUE THREAD

**Issue by 3x1t-5tyl3** [Frooxius/NeosPublic#1686]
## Describe the bug
Holding more than 1 folder creates a "Copy Link" arc for each

## Relevant issues
-

## To Reproduce
1: Hold a folder
2: Duplicate it as many times as needed
3: Hold all at once

## Expected behavior
It shouldn't add one for each. Maybe one for each *different* one. But not one for each same one.

## Screenshots / Video
![image](https://user-images.githubusercontent.com/61988002/106189398-8e9d3700-61a8-11eb-920f-41d6e2f759cc.png)

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.1.27.369
 - Neos Platform: Any
 - Link to reproduction World/Item: Any folder
 - Regression: Happens since the "Copy Link" came out.

## Additional context
-

## Reporters:
3x1t_5tyl3#0001

**Comment by Frooxius** [comment]
Forgot to close this, was fixed in 2021.1.29.504. Thanks!
