### ISSUE TITLE
Radial menus do not open if your laser is hovering over your belt menu

### ISSUE THREAD

**Issue by Toxic-Cookie** [Frooxius/NeosPublic#1688]
## Describe the bug
Radial menus do not open if your laser is hovering over your belt menu.

## Relevant issues
None.

## To Reproduce
1. Open your belt menu.
2. Hover your laser over it.
3. Try to open your radial menu.
4. It does not open.

## Expected behavior
The radial menu should open anytime the button is pressed.

## Screenshots / Video
Not required.

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: Any
 - Neos Platform: Any
 - Link to reproduction World/Item: Not required
 - Regression: [Did this work before? As far as I know, it's always been this way. I just noticed.]

## Additional context
None.

## Reporters:
Discord: Toxic_Cookie#8064

**Comment by shiftyscales** [comment]
This is not a bug. It's by design. The context menu does not open when you are interacting with your dashboard because it keeps that input free for other uses. As an example, on the desktop view, it is what is used to call open the modal menu.
