### ISSUE TITLE
audio source selection unreadable when there is lots audio inputs.

### ISSUE THREAD

**Issue by SUPTEC-Gourry** [Frooxius/NeosPublic#1689]
Audio source selection unreadable when there is lots audio imputs.

## Describe the bug
The audio source input selection screen on the dash is unreadable when user have more than 14 sources

## Relevant issues
Cant choose the correct sound source / mic input.

## To Reproduce
[Steps to reproduce the behavior:
the machinne need to have more than 15 audio source i/o

## Expected behavior
the screen selection be readable

## Screenshots / Video
[If applicable, add screenshots or a video to help explain your problem.]
![image](https://user-images.githubusercontent.com/69479081/106272526-f2a71600-620f-11eb-8457-55206f8be6c1.png)

## Bug information (please complete the following information):
 - How often does it happen: Aways
 - Does the bug persist after restarting Neos? YES
 - Neos Version: 2021.1.29.612
 - Neos Platform: Windows
 - Link to reproduction World/Item: 
 - Regression: No

## Reporters:
Gourry

**Comment by Fleur24** [comment]
+1 Same issue here.
![20210130011700_1 (1)](https://user-images.githubusercontent.com/78280720/106369033-82eb7500-634e-11eb-8692-ff7acd5755f8.jpg)

**Comment by TehTurk** [comment]
This is a visual issue I think, ideally Froox needs to add a Scroll Rect/Mask here. I don't think he considered people have a good number of inputs.

**Comment by Frooxius** [comment]
Yeah this just needs a scroll area, I didn't think that people would have this many devices on their systems. I'll see about adding it soon.

**Comment by SUPTEC-Gourry** [comment]
maybe adding the option to hide the loopback devices would also help. since we have the streaming capabilities i don't see the usefulness of loopback.

**Comment by uyjulian** [comment]
> maybe adding the option to hide the loopback devices would also help. since we have the streaming capabilities i don't see the usefulness of loopback.

I don't think that will be very useful in other locales.

**Comment by Frooxius** [comment]
The UI should now scroll in 2021.2.7.1345, thanks for the report!
