### ISSUE TITLE
Clarify contact search capability

### ISSUE THREAD

**Issue by sirkitree** [Frooxius/NeosPublic#1690]
## Is your tweak request related to a problem? Please describe.
It is not immediately evident on the chat screen that you can type into the top left user search text field.

## Describe what would you like tweaked
I'd like some default text in there that prompts the user to search: "Search..." with perhaps a blinking cursor would be enough.
![20210129103132_1](https://user-images.githubusercontent.com/28543/106314420-90094680-621e-11eb-8886-5856e3721546.jpg)

**Comment by Frooxius** [comment]
I'm sorry, I don't plan on making changes to this old UI, as it will be scrapped and reworked completely. The new one will have this kind of prompt, similarly how the new Worlds UI does.
