### ISSUE TITLE
Mixamo Rig Hand Heuristics Incorrectly Registering Metacarpals

### ISSUE THREAD

**Issue by Medravr** [Frooxius/NeosPublic#1691]
## Describe the bug
Importing a test Mixamo rig with correct weights in blender causes the hands/fingers to look like this in Neos.
https://youtu.be/iQe0ez-cjxQ

Checking or unchecking the only option "Pose MetaCarpals" had no effect. Options Assign from Rig and the Initialize Hand buttons did nothing also.

The current solution is to set the MetaCarpal root/rotational driver refs to null and move the bone chain refs accordingly: Index1 to Proximal, Index2 to Intermediate, Index3 to Distal. 

The manual solution is far from optimal. As suggested by @H3BO3 a link to the model will be sent to help adjust the hand heuristics since it appears that import is not registering that the metacarpals exist and thus skipping the distal digit.

Rig will be sent to Frooxius

## To Reproduce
1. Import model
2. Use the Avatar Creator
3. Move fingers

## Expected behavior
The fingers would bend more naturalistically.

## Screenshots / Video
This is an manual solution where the metacarpal fields are null and the bone chain has been moved
https://cdn.discordapp.com/attachments/439421735474036738/804423290445496360/handik_20210128133519_1.jpg

## Reporters:
Medra

**Comment by Frooxius** [comment]
Improved the heuristics in 2021.2.3.616! The problem was that the rig contained two "finger tips", which made Neos think it had metacarpals, when it in fact did not. Should now setup properly. Thanks!
