### ISSUE TITLE
Add a confirmation to the "Destroy Selected" context menu item

### ISSUE THREAD

**Issue by StarfishHidari** [Frooxius/NeosPublic#1699]
## Is your tweak request related to a problem? Please describe.
I keep accidentally destroying things I don't mean to delete, when I open up the context menu and accidentally click "destroy selected" instead of the menu item I was going to click based off of muscle memory (which usually happens if a new context menu item was injected into my context menu)

## Describe what would you like tweaked
Add a confirmation to Destroy Selected, making it so I have to click it once, after which there is a second button saying something along the lines of "are you sure?" If I click again, then it will destroy selected.

## Describe alternatives you've considered
I don't know of any alternative solutions, this tweak sounds like a pretty simple one to make

**Comment by mralext20** [comment]
note that this is about the `destroy selected` entry in the dev tool's context menu, instead of the generic destroy button on the normal context menu.

**Comment by chemicalcrux** [comment]
An option that would cause "Destroy Selected" to open a single arc segment that, if clicked, confirms the delete, would be a good solution. This would keep the delete operation simple (just click twice; doesn't matter where on the context menu you click the second time).

**Comment by uyjulian** [comment]
Does the undo functionality not suit your needs?

**Comment by StarfishHidari** [comment]
the undo functionality frequently does not restore things to how I had it before, it often breaks references or logix that may have been using what i just deleted, so no it is not a suitable solution.

**Comment by Psychpsyo** [comment]
Yes. Especially since it's right next to deselect all. It's way too easy to hit the wrong one on accident.

**Comment by Toxic-Cookie** [comment]
Gonna toss this an upvote. Having delete confirmation for both destroy arcs would be an excellent design choice.

**Comment by Frooxius** [comment]
Added in 2021.2.3.616, thanks!
