### ISSUE TITLE
Ignore hover event when dragging item that cannot be accepted by the element

### ISSUE THREAD

**Issue by Frooxius** [Frooxius/NeosPublic#17]
https://steamcommunity.com/app/740250/discussions/0/3211505894145549553/

--- when you are dragging something, hovering-events still trigger (You might still want this in some cases, such as drag-and-drop to the palette, but even then: only objects that can receive a drop event of the dragged type should trigger hovering during drag)

**Comment by shiftyscales** [comment]
I don't believe this is relevant any longer.
