### ISSUE TITLE
Regression: Scaled anchor incorrectly stores _originalScale when anchoring remote user with Logix

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#1707]
## Describe the bug
A regression in the latest build, if a user is forced into an anchor with Logix (Anchor User node) they are scaled to the anchor's relative scale, but the _originalScale stores the user's original scale multiplied by the anchor's relative size. E.g. an anchor of 0.5 scale parenting a user with a scale of 1 will resize the user to 0.5x scale while under the anchor, then scale them up to 2 when releasing the user.

## To Reproduce
- Anchor a user with the Anchor User Logix node under an anchor with a global scale either greater or less than 1
- Release the user with the Release User Logix node

## Expected behavior
The user should maintain the same relative position, rotation, and scale as defined by the properties of the anchor.

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.2.3.616
 - Neos Platform: Windows
 - Regression: Yes, 2021.1.29.612

## Additional context
It appears that this issue specifically occurs when the Logix tries to anchor a non-local user. E.g. host anchoring client, or client anchoring host. In testing with Tatsu, it would change his scale every time I pulsed the anchor user / release user nodes, but would not do the same to myself if I attempted it on myself.

## Reporters:
Furf# 7691, chemicalcrux# 1298, with testing assistance from Tatsu Kimiero# 3109, and Shifty# 7944.

**Comment by Frooxius** [comment]
What is TransformRestoreMode configured as?

**Comment by shiftyscales** [comment]
> 
> 
> What is TransformRestoreMode configured as?

"RelativeTransform"

**Comment by Frooxius** [comment]
In that case the _originalScale seems to be behaving as it should, as that mode stores the user's scale relative to the anchor itself. This mode always stores the user's transform relative to the scale of the anchor itself, so if the anchor is then scaled up, down, rotated or moved, the user exits at the same relative transform to it as they entered.

What is the main underlying issue? Is the user just scaled incorrectly on exit?

**Comment by chemicalcrux** [comment]
I've observed the user getting scaled incorrectly on *entrance*, too. I had someone become very tiny when going into an anchor that allowed a minimum scale of 0 and a maximum scale of Infinity.

**Comment by shiftyscales** [comment]
They are being scaled incorrectly on entrance to the anchor as well relative to the behavior of the previous build while using Logix to perform the anchoring/unanchoring.

The previous behavior was that the user would maintain the same relative scale, which is what still happens if the local user is triggering the Logix.

Two example clips I posted in the testing channel. The first depicts what happens when I anchor and release Turk with the Logix. His position, and scale change while anchoring and being released. The second shows that if I try it to myself, I stay the same position, and scale, although rotate very slightly for some reason while exiting. @Frooxius 

https://cdn.discordapp.com/attachments/515553786102546442/806689233053286430/2021-02-03_16-52-37.mp4
https://cdn.discordapp.com/attachments/515553786102546442/806689248710623312/2021-02-03_16-53-36.mp4

![2021-02-03 16 57 06](https://user-images.githubusercontent.com/54213390/106829408-f2a87b00-6640-11eb-9813-0ef14e8420df.png)

**Comment by Frooxius** [comment]
Fixed in 2021.2.4.348, thanks!
