### ISSUE TITLE
Destroy without children does not respect Enabled Field

### ISSUE THREAD

**Issue by mralext20** [Frooxius/NeosPublic#1710]
## Describe the bug
The destroy without children component does not respect it's enabled state

## Relevant issues
None

## To Reproduce
1. attach component
2. disable the component
3. remove it's children
4. see that it still functions

## Expected behavior
for the Destroy without Children Component to not function without being enabled

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.1.2.4.348
 - Neos Platform: Any
 - Regression: No

## Reporters:
Alex from Alaska#2020, Ukilop#4463

**Comment by 3x1t-5tyl3** [comment]
Duplicate of #1461 :p

**Comment by Aerizeon** [comment]
@3x1t-5tyl3 perhaps we should have one large thread somewhere of components that don't respect their enabled/disabled state, instead of a bunch of smaller ones?

**Comment by mralext20** [comment]
i see. i'll close this.
