### ISSUE TITLE
SmoothValue<T> Component Should have a CurvePreset field

### ISSUE THREAD

**Issue by mralext20** [Frooxius/NeosPublic#1711]
## Is your feature request related to a problem? Please describe.
the SmoothValue component is useful as is, however sometimes it's nice to have a constant smoothing, or smoothing based on linier rather than smooth, or perhaps wanting smoother smoothing.

## Describe the solution you'd like
See Title. 

## Describe alternatives you've considered
using logix to start a tween instead of the smoothValue component

## Additional context
there is already a CurvePreset enum avalible, should probably use that.

**Comment by Frooxius** [comment]
This isn't possible, this function doesn't operate using curves, it's a continuous smoothing function. CurvePreset only works when you have a defined start and end of the transition, the Tween components are for that.
