### ISSUE TITLE
Enterting an anchor on another user while climbing them sends you flying

### ISSUE THREAD

**Issue by StarfishHidari** [Frooxius/NeosPublic#1719]
## Describe the bug
If there is an anchor on a user (such as a grebber), and while climbing that user you enter the anchor, your view will get sent flying in a random direction at a fast speed until you exit the anchor.

## Relevant issues
Possibly #1714 , this is related to the update that changed anchors in some way

## To Reproduce
1. Have 2 people in a world
2. parent an anchor to the other user (I know this definitely happens with the grebbers)
3. climb the other player, and while still gripping onto them, click the anchor and enter it
4. your view should now be flying away from the anchor

## Expected behavior
when entering the anchor you should not fly off into the distance

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.2.4.348
 - Neos Platform: Windows
 - Regression: Yes, I think 2021.1.29.612 because that was the build before the anchor changes?

## Reporters:
Hidi#1111

**Comment by Frooxius** [comment]
Can you check if this is fixed in 2021.2.7.1345 please?

**Comment by StarfishHidari** [comment]
It seems to be fixed! thanks
