### ISSUE TITLE
Basic button (similar in function to TouchableData) that can be connected to ButtonEvents and IButtonReceiver

### ISSUE THREAD

**Issue by Aerizeon** [Frooxius/NeosPublic#1721]
## Is your feature request related to a problem? Please describe.
There is not currently any easy-to-use generic touchable button that doesn't use physical simulation. It seems fairly common to use: 
* TouchableData with FireOnTrue (which results in issues like #1716), which can't be hooked up to the ButtonEvents Node, TouchableEvents, or IButtonReceiver
* TouchEventRelay, which can't be hooked up to ButtonEvents or IButtonReceiver (but *can* be connected to TouchableEvents)
* PhysicalButton, which requires a collider and a specific press direction (but *can* be connected to ButtonEvents and IButtonReceiver)

## Describe the solution you'd like
* A Button type that is similar in function (or a wrapper around) TouchableData, such that it doesn't require a physical depression or collider interaction. (The pressed logic for NeosCheckbox seems like a good comparison), so that it can be connected to ButtonEvents and the various components that accept IButtonReceiver
 -or-
* A way to hook TouchableData up to a logix node similar to ButtonEvents or TouchableEvents, and fire Actions directly from it (similar to ButtonAction, ButtonPlaybackAction, etc)

## Describe alternatives you've considered
* As described in the **problem** section, the alternatives have differing functionality that makes it less useful in some cases - a common use case that i've noticed is for nose-based sound effects, where a common setup is TouchableData -> FireOnTrue -> RandomAudioPlayer.Play(), which causes the PlayOneShot to stick around if the user it's attached to is not focused (since FireOnTrue uses the Active User by default)

* Another common setup is TouchEventRelay -> TouchableEvents -> RandomAudioPlayer.Play(), however it is more cumbersome to use, since you must filter the events and active user yourself . Additionally, it is not possible to make a purely component-based solution (And most new users complain about how *verbose* this method is, compared to the first method)

* PhysicalButton will work, however it requires a collider - It won't work with TouchTipSource alone, and it will only work from a single direction, and only when depressed a specified amount. It *does* allow for a purely component-based solution (and a simple logix solution), but it does not always provide the desired effect

* A UIX Button works almost exactly like the proposed component, except it requires a UIX Canvas, which is not optimal for all use cases.

**Comment by Frooxius** [comment]
It's possible to add a simple general button component that receives touch events and sends the button events based on those, but I'm not sure how exactly do you expect it to work without a collider? There needs to be some "physical" representation for it to be able to be pressed. Touchable system depends on colliders as well.

The most direct approach is to simply define a component that's another form of ITouchable, so you don't need to use other touchable components to relay the events that it can just receive directly, that would be really messy way to do it. But again, it needs a collider to work, as touchable would.

**Comment by Aerizeon** [comment]
It's not so much about it requiring a collider entirely - physical button just requires a collider to interact in a specific way with the button - 
I'd like to have a button that can be interacted with, similar to how touchable events/touchable data works (such that direction and depth don't matter)

**Comment by Frooxius** [comment]
I still don't quite understand what are you asking for. Physical Button doesn't require collider to interact in a specific way. The collider is a proxy for the interaction, but how the interaction is interpreted is handled by the physical button component itself.

I can add a button component that can be pressed and interacted from any angle and won't have any sort of physical press interaction, but it will still require a collider for those interactions.

**Comment by Aerizeon** [comment]
> I can add a button component that can be pressed and interacted from any angle and won't have any sort of physical press interaction, but it will still require a collider for those interactions.

If that's how TouchEventRelay/TouchableData handle their triggers, than yes :3

sorry for being confusing.

**Comment by Frooxius** [comment]
Added TouchButton in 2021.2.7.1345, that should fulfill the role, thanks!

**Comment by Aerizeon** [comment]
Thank you <3

**Comment by Aerizeon** [comment]
@Frooxius It seems you can't interact with it using a `TouchTipSource` that isn't on the hands. I assume this is a security feature, but it would be nice to have a toggle for this (maybe on other buttons as well?), with the default of course being enabled.

I noticed this when trying to interact with the button using an auto-click object (which `Tween`s a default VR hand back and forth into a button, with the active user set to the last person to grab it)

**Comment by Frooxius** [comment]
Yes, that's intentional, it's a security measure. Until there's a more robust system it won't change sorry, a toggle for this would just provide a security hole.

**Comment by Aerizeon** [comment]
That's fine, thanks for the information! :D
