### ISSUE TITLE
Driving the recordingVoiceMessage field in the User inspector prevents being muted while recording a voice message

### ISSUE THREAD

**Issue by DJ-Night-mares** [Frooxius/NeosPublic#1722]
## Describe the bug
Driving the recordingVoiceMessage field in the User inspector to false prevents the user with the driven field from being muted while recording a voice message

## To Reproduce
1. Open user inspector and select a user.
2. Drive the recordingVoiceMessage field with a logix drive node set to false

## Expected behavior
The user should still be muted while recording a voice message

## Screenshots / Video
![2021-02-06 19 09 27](https://user-images.githubusercontent.com/68568684/107135630-32759980-68b1-11eb-95ec-c63e7c1aee7d.jpg)

## Bug information
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.2.4.348
 - Neos Platform: Windows
 - Regression: Unknown

## Reporters:
DJNightmares#9610
xXx_swiggity_xXx#2124
Frank, PHD#2361

**Comment by Frooxius** [comment]
Fixed in 2021.2.7.1345, thanks for report!
