### ISSUE TITLE
GrabbableReceieverSurface favors trigger collider centers

### ISSUE THREAD

**Issue by Toxic-Cookie** [Frooxius/NeosPublic#1726]
## Describe the bug
When a static collider is present on a grabbable object, the GrabbableReceieverSurface component works as usual. When you add a trigger collider to the grabbable object, it instead favors that one and moves the object by the center of the trigger collider instead of the bottom of the static collider.

## Relevant issues
Found none.

## To Reproduce
1. Make a cube and add a GrabbableReceieverSurface to it.
2. Make another cube and add a trigger collider to it.
3. Notice how it gets placed halfway in when you place it on the GrabbableReceieverSurface.
4. The placement changes when you offset the trigger collider.

## Expected behavior
GrabbableReceieverSurface should ignore trigger colliders like it used to and definitely shouldn't place objects by the center of an attached trigger collider rather than the bottom of an attached static collider.

## Screenshots / Video
None

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.2.7.1345
 - Neos Platform: Any
 - Link to reproduction World/Item: None
 - Regression: Yes (Last major build)

## Additional context
I noticed this when an item that used to work fine and be placed on top now sinks inside the GrabbableReceieverSurface due to the trigger collider on it.

## Reporters:
Toxic_Cookie#8064

**Comment by Frooxius** [comment]
It should now properly ignore Trigger volumes for all calculations in 2021.2.21.1425, thanks for the report!
