### ISSUE TITLE
New Audio Message Notifications are too quiet

### ISSUE THREAD

**Issue by TehTurk** [Frooxius/NeosPublic#1728]
## Is your tweak request related to a problem? Please describe.

The new sounds are too quiet, or not able to alert me in terms of presentation.

## Describe what would you like tweaked
I love the new sounds, but there are really too subtle/quiet and I'm not alerted to them being heard. I'm talking in conversation and I literally miss messages. Would it be possible to double their output? I feel like that would be alright.

**Comment by Frooxius** [comment]
Normalized the volume in 2021.2.21.1425, thanks!
