### ISSUE TITLE
Skeletal input poses for objects

### ISSUE THREAD

**Issue by Swingly6061** [Frooxius/NeosPublic#1738]
Was playing Space Pirate Trainer the other day and noticed it is using Skeletal input but has a grip pose for the guns.
Could something similar be implemented for Neos? Where you pose the skeletal hand bones for an object.

Example of Space Pirate Trainer's finger tracking with an Index.
https://user-images.githubusercontent.com/50369014/107528203-ddd86400-6bb9-11eb-9ca8-0d9ef7348302.mp4

**Comment by Frooxius** [comment]
This is already planned: https://github.com/Frooxius/NeosPublic/issues/291

**Comment by Swingly6061** [comment]
Ah, thought this was different, looked like #291 was more of an alternative to skeletal?
