### ISSUE TITLE
Allow tipjar to be triggered via UIX

### ISSUE THREAD

**Issue by AshtonSparx** [Frooxius/NeosPublic#1744]
## Is your tweak request related to a problem? Please describe.
The tipjar seems to be only trigger able on a physical mesh, which means if you just wanted a nice, clean UIX button for it or a UIX panel that includes your tipjar, it can't be done.

## Describe what would you like tweaked
I would like the tipjar component to be triggered with the UIX Button component.

## Describe alternatives you've considered
I'm not aware at this time of any alternatives for this solution.

**Comment by Frooxius** [comment]
This has already been requested: https://github.com/Frooxius/NeosPublic/issues/1727
I've got this implemented already, it's coming in the next build.
