### ISSUE TITLE
Shader Repogitory System (As a precursor to custom shader support) 

### ISSUE THREAD

**Issue by kazu0617** [Frooxius/NeosPublic#1746]
現在、Neosのロードマップの中にカスタムシェーダのサポートが記載されています。
ロードマップの内容を確認した限りでは、現在Neos内で動的にコンパイルする際にUnityに依存した問題が原因で実装することができないと記載されています。
言い換えれば、事前にプリコンパイルしたシェーダにおいては実装が可能だという事も言うことができます。
しかし、現在Shaderに希望する機能を実装する為にはFroxxious氏に直接追加の要望を出し、その内容を確認しつつFroxxious氏自身が自前で実装しなければならず、その中で競合する機能があれば切り捨てなければなりません。人によってはShaderのコンパイル、追加する方法さえあればShaderを自分で実装できるであろうにもかかわらず。

そのため、当面の間（Unityのバグが解決し、カスタムシェーダの実装に目途がつくまで）、シェーダについて一種のリポジトリ方式で追加し、追加されていないリポジトリから引っ張ってきたマテリアル（もしくは動作しないマテリアル）があればフォールバックシェーダを適用する、という方式を追加してみるのはどうでしょうか。
この場合であればもし今後Unity側のバグが解決し、カスタムシェーダの実装にめどが立った場合でも"Static Shader"としてフォールバックさせることができ、移行のコストが(Shaderの作者が対応しないことによる一部のマテリアルが正常に動作しない可能性を除けば)そこまで高くないのではないかと感じます。また、カスタムシェーダを使用したいという要望に対しても（自前でコーディングを行う必要がありますが）一まずGLSLを十分に扱える人であれば自由に追加・更新することができます。

問題としてはShaderが自由に作成できるようになることでシステムに破壊的な動作を行わせることが可能になる点です。この点はシェーダの動作について診断機能や診断に基づいて自動でフォールバックシェーダを適用する、といった方式で解決するかもしれません。

ともかく、もしUnity側のバグがすでに解決しているのであればこのIssueは意味のないものですが、そうでないのであれば一つの案としてはどうでしょうか？

Currently, support for custom shaders is listed in the Neos roadmap.
As far as I can tell from the roadmap, it states that it is currently not possible to implement this due to Unity-dependent issues when compiling dynamically within Neos.
In other words, it can be implemented in shaders that have been precompiled.
However, in order to implement a desired feature in a shader, you have to submit a request directly to Mr. Froxxious, check the content of the request, and then implement it yourself, and if there are any conflicting features, you have to cut them out. This is despite the fact that some people would be able to implement the shaders themselves if they only had a way to compile and add them.

So, for the time being (until the Unity bugs are worked out and custom shaders are implemented), how about adding a kind of repository for shaders, and if there are materials pulled from the repository that haven't been added (or materials that don't work), apply a fallback shader.
In this case, if a bug in Unity is resolved in the future and we are able to implement a custom shader, we can still fall back to it as a "static shader" and the cost of transitioning it would not be that high (except for the possibility of some materials not working properly due to the shader author not supporting it). I feel that the cost of migration is not that high (except for the possibility that some materials may not work properly because the shader author does not support it). Also, if you want to use custom shaders, you can add or update them freely (although you will need to do the coding yourself) as long as you have a good command of GLSL.

The problem is that the ability to create shaders freely allows the system to do destructive things. This could be solved with a diagnostic function for shader behavior and automatic fallback shaders based on the diagnosis.

Anyway, if the bug in Unity has already been solved, this issue is useless, but if not, how about a suggestion?

Here is a reorganized version of the content based on the template.

## Is your feature request related to a problem? Please describe.
カスタムシェーダのサポートに対して抱えている問題に関連しています。現在Unity側のバグ修正待ちで、それを適用した場合にPhysicsが対応できないという話を聞いたためです。
This is related to an issue we're having with custom shader support. We're currently waiting for a bug fix on the Unity side, and we've heard that Physics can't handle it when it's applied.

## Describe the solution you'd like
シェーダをそれぞれが外部で作成、コンパイルし、コンパイルした内容をインポート後、インポータでシェーダを持ち込ませます。その際にフォールバックシェーダを指定します。その後、もしNeos側としてその場で読み込めないようであれば次回起動時から、直ぐ読み込めるようであれば読み込む直前に「そのShaderを使用するか」のダイアログをWebHostの確認時のダイアログと同様の形式で表示し、許可された場合は直ぐ読み込める場合は直ぐに、読み込めないようであれば次回起動時より許可したシェーダを追加して起動します。問題が発生した場合に備え、指定した引数を使用した場合にはそれら許可したShaderを読み込まずに起動するようにします。

Each shader is created and compiled externally, and after importing the compiled content, the shader is brought in by the importer. You can specify a fallback shader at that time. After that, if Neos can't load the shader on the spot, it will display a dialog asking "Do you want to use that shader?" in the same format as the WebHost confirmation dialog just before loading the shader if it can be loaded immediately. If the shader is allowed, it will be loaded immediately, if not, it will be loaded immediately, if not, it will be loaded immediately, if not, it will be loaded immediately, and if allowed, it will be loaded immediately. In case a problem occurs, if the specified arguments are used, the program will start without loading the allowed shaders.

## Describe alternatives you've considered
もしUnity側のシェーダの動的読み込みを行う場合に発生していたバグが解消しているのであれば、この方式を使用する必要は(Neos SDKを提供する、という別のロードマップの視点を考えると必要かもしれませんが、その視点を除くと)ありません。

If the bug that occurred when dynamically loading shaders on the Unity side has been resolved, then there is no need to use this method (except from the perspective of another roadmap, providing the Neos SDK, which may be necessary).

## Additional context
あくまでも軽く内容を考えただけです。実際にこの通りにそのまま実装できるかというと何かしら問題が発生する気もします。
後程手元でワークフローを書いてみて現実的かどうかをもう少し考えてみます。

This is just a light idea of the content.I'm not sure if I can actually implement it as it is, but I think there will be some problems.
I'll try to write a workflow later and see if it's realistic.

**Comment by Frooxius** [comment]
Hello.

Thank you for the request, but unfortunately this is not something that we can support. Lack of dynamic shader loading in Unity is only part of the problem. Ensuring long term compatibility of the shaders even with future changes to the rendering pipeline and also ensuring security is another and for that we need to have a higher level of control over the rendering pipeline.

Adding support for this at out current stage would either prevent us from making future improvements and transition to another pipeline or break a lot of content built with those shaders, which is against our philosophy.

For the time being I recommend two alternatives:

1) Request individual shaders in separate issues. We can evaluate each one and either accept and implement it or reject it, based on its impact on the future development

2) Wait for the implementation of the custom shader system. This is a long term goal and it requires a custom rendering pipeline first, so it will take some time, but it will provide the ability to build custom shaders without sacrificing compatibility and security: https://github.com/Frooxius/NeosPublic/issues/63
