### ISSUE TITLE
Remove the complete traversal from the logix tip context menu by default

### ISSUE THREAD

**Issue by The-furf-of-July** [Frooxius/NeosPublic#1748]
## Is your tweak request related to a problem? Please describe.
The context menu for the LogiX tip includes a toggle between Complete Traversal and Connected Nodes. The Complete Traversal setting, according to Ryuvi, is essentially a legacy feature, and in addition, it appears to cause only pain and destruction for anyone who accidentally turns the setting on.

## Describe what would you like tweaked
I would like the arc for that toggle to be removed, so it cannot destroy people's stuff anymore.

## Describe alternatives you've considered
An alternative solution that would also work is leaving the arc in, but making Complete Traversal no longer accessible. This would allow new traversal settings to be added and togglable with the same button. But as it stands now, complete traversal is the only thing it can be swapped to.

It would be fine to have the legacy option able to be added back via inspector, but for the sake of new or unaware users I think it's best that it not be available by default.

**Comment by ProbablePrime** [comment]
I use the complete traversal regularly and do not consider it legacy.

**Comment by Aerizeon** [comment]
@ProbablePrime What does it do, exactly? and under what circumstances does it improve over the Connected Nodes mode

**Comment by ProbablePrime** [comment]
I showcase it here: https://youtu.be/5Llbm4Mz37Y?t=195

But essentially, it will completely traverse the Logix Chain not breaking at Reference Nodes. The setup shown in my video is something that commonly occurs with a variable that it written several times from several places.

I pick and choose when to use it, but once you're aware of what it does and how to use it, It can save some time when compared the other traversal mode.

**Comment by The-furf-of-July** [comment]
I am sharing this at Dr Frank's request, so don't blame me for this, but
Ryuvi has informed me that @ProbablePrime is in fact not a person, and is in fact cheese, and therefore his opinion should not be counted.

That said, ProbablePrime would be one of the cases where being able to enable it through the inspector would be useful.
I still hold that the vast majority of users do not find the feature useful and it causes large amounts of damage on a regular basis.

**Comment by ProbablePrime** [comment]
I disagree that we should be hiding features behind hidden walls, that could be useful to users. I also searched the Discord and can find no mention of this option being classed as "Legacy" by the team before. 

So i'd like to understand that comment more.

**Comment by Frooxius** [comment]
Yeah @ProbablePrime is correct, this is not a legacy feature, it's designed to pack certain LogiX setups when you want to get all possible nodes. I don't have any plans to remove it, if it's causing problems with your setup, then simply don't use it.
