### ISSUE TITLE
Flash Slot Hierarchy needs to have a Alternate Mode to Flashing

### ISSUE THREAD

**Issue by TehTurk** [Frooxius/NeosPublic#1751]
## Is your feature request related to a problem? Please describe.

I'm currently trying to use the flashlight hierarchy node to highlight a collider I'm interacting with, the problem is the constant flashing is undesirable (You can only set it so low before it gets visually annoying) and I'd like for it to be a constant on/off if it's interacting or not. Would this be possible? 

## Describe the solution you'd like
Something similar to the Debug Nodes, but instead I can input a slot and the debug visual is the collider being highlighted.

**Comment by Frooxius** [comment]
This is already supported. Simply feed Infinity as the duration of the flash and store the output FlashRoot from the node in a variable. When you want to hide it, just destroy the FlashRoot slot.

**Comment by TehTurk** [comment]
Oooh okay! Thank you Froox!!! I attempted something like this but had some issues.
