### ISSUE TITLE
Changing locomotion modes while gripping onto a player makes you follow their movements

### ISSUE THREAD

**Issue by StarfishHidari** [Frooxius/NeosPublic#1752]
## Describe the bug
If you grip onto a player and change locomotion modes while still gripping (such as changing from physical to no-clip), you will start following the position and rotation of the bone you were gripping onto. For example if I grip onto someone's head, and change locomotion modes, I will be following their head rotation as if I'm parented under them, even though I'm not.

For clarification the effect is similar to being parented under a bone on a player, but I checked and I was still parented under the root of the world.

Changing locomotion modes again while not gripping fixes this and makes you stop following that bone's movement.

## Relevant issues
This seems also related to the changes made to gripping onto people recently.

## To Reproduce
1. grip onto a player to climb them
2. while still climbing them, change locomotion modes
3. you will now be following their bone's rotation and position, if they rotate or move that bone on their avatar your space will move with it

## Expected behavior
when changing locomotion modes while gripping you should not seemingly give the effect of you parenting under that bone you were gripping onto

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.2.7.1345
 - Neos Platform: Windows
 - Regression: Yes, I assume it worked in the build before changes to gripping onto people were made

## Reporters:
Hidi#1111

**Comment by H3BO3** [comment]
Interesting, this may be related to #1735

**Comment by StarfishHidari** [comment]
mm yea it does seem like it might be related, interestingly with this it doesn't send you flying, it just effectively acts like you're parented under the player

**Comment by StarfishHidari** [comment]
Upon further testing I think this may actually be a duplicate of #1735, as I realized this happens with *any* climbable object. Oddly in some worlds it acts like you're parented under the object and doesn't send you flying, in other cases it sends you flying. I'm closing this  issue and commenting on that issue instead now.
