### ISSUE TITLE
The boolean input to the SetSlotPersistentSelf node is (probably) incorrectly named 'Active'

### ISSUE THREAD

**Issue by Zyzyl** [Frooxius/NeosPublic#1753]
## Is your tweak request related to a problem? Please describe.
The bool input to the Set Slot Persistent Self node is labelled 'Active'. This is presumably cosmetic and does not affect the actual functionality of the node.

## Describe what would you like tweaked
I would expect this input to be named 'Persistent' by analogy to the bool input on the SetSlotActiveSelf node which is also labelled 'Active'.

## Related
https://github.com/Frooxius/NeosPublic/issues/1411 relates to a similar percieved mis-labelling. 

## Additional context
![SetSlotPersistentSelf name tweak - Copy](https://user-images.githubusercontent.com/66165438/107987231-91c85d80-6fc5-11eb-9fbc-0f479e8e3788.jpg)

**Comment by Frooxius** [comment]
Changed in 2021.2.22.855, thanks!
