### ISSUE TITLE
Add PatreonTier to CloudUserInfo component to display a user's tier as a string.

### ISSUE THREAD

**Issue by AshtonSparx** [Frooxius/NeosPublic#1759]
## Is your tweak request related to a problem? Please describe.
This tweak is not related to a problem.

## Describe what would you like tweaked
To add PatreonTier to the CloudUserInfo component as a string. This would be great for userinfo gadgets such as mine. Inspecting the NeosAPI, custom tiers appear public (Such as ProbablePrimess "The Great and Powerful Og" tier) - but instead of just parsing information like that with logix, just implement it into the component itself, along with default tiers such as Gunter, Blade Runner, ect.

## Describe alternatives you've considered
N/A

**Comment by Frooxius** [comment]
This could be added, but it would show this information only when used in userspace and only for yourself, as this info is normally sanitized from the public API. Is this acceptable for your workflow?

**Comment by AshtonSparx** [comment]
There's already a component that has that localized information, believed it's called SimpleLocalUserProfile however, as the name states, it only shows the local user's information, I'm requesting the CloudUserInfo to have a string that shows the Patreon tier name said user has. Similar to how this show's "Gunter, Patreon Supporter" but not be localized. 
![image](https://user-images.githubusercontent.com/53165730/108179833-0ee1f880-70d4-11eb-84f5-63e1b3c3550e.png)
The NeosAPI already shows custom patreon tiers, so figured having the default tiers show up too wouldn't be an issue. And too save logix parsing, to include it with CloudUserInfo.

**Comment by Frooxius** [comment]
Ah, the NeosAPI isn't actually supposed to provide that information, some of it wasn't sanitized properly. I've pushed a new update which removes this information from the public API, as it's private user information.

We plan for users to be able to optionally put it on their profile, but by default it's supposed to be known only to the user themselves.

I could add this once we have mechanism to opt into displaying this information publicly on the user's profile.

**Comment by AshtonSparx** [comment]
Sounds fair enough, glad I was able to help however clear that Not-Supposed-To-Be-Public information about Patreon tier information. Hope that opting-in option comes soon <3 - Guess i'll close this topic.
