### ISSUE TITLE
Request invite

### ISSUE THREAD

**Issue by 3x1t-5tyl3** [Frooxius/NeosPublic#1768]
## Is your feature request related to a problem? Please describe.
Sometimes you want to be in a more private world like C+ or C but wanna control who joins specifically to each user. Concurrently the way of doing that is by setting the user limit to 1 and putting "Ask to join" on the world title. I find that kinda .. klunky.

## Relevant issues
#1548 

## Describe the solution you'd like
A button on the Contacts list to "Request" an invite. The host of the session should see a request for an invite with the Username requesting that invite and then allowing (sending an invite as normal) or disallowing and as such ignoring it.

## Describe alternatives you've considered
Rename world to "Ask to join" and let people msg you.

## Additional context
-

**Comment by mralext20** [comment]
#1084 duplicate?

**Comment by 3x1t-5tyl3** [comment]
Yup it is whoops! Closing this one.
