### ISSUE TITLE
Use single-pass VR rendering for increased performance

### ISSUE THREAD

**Issue by Frooxius** [Frooxius/NeosPublic#177]
This will significantly decrease the CPU (and some GPU) load when rendering in VR. There were some blocking issues on this last time I tried this, but should look into it more as part of the performance update.

**Comment by Frooxius** [comment]
This is now implemented as of 0.8.4.x, the performance gains seem to be quite good from preliminary testing.

**Comment by JohannAmos** [comment]
🚀🚀🚀
