### ISSUE TITLE
Virtual Keyboard issue with new binding system

### ISSUE THREAD

**Issue by LewisSnow** [Frooxius/NeosPublic#1770]
## Describe the bug
Using WASDQE or any respective key input related to movement outputs movement.

## Expected behavior
The new key binding system should exclude virtual keyboard inputs.

**Comment by FreyarH** [comment]
Reproducible in build 2021.2.21.1425.

The movement keys WSAD do not respond if NEOS is not the active window, however SPACE using the virtual keyboard is.

**Comment by shadowpanther** [comment]
Don't even have to use the desktop view. Typing into any inspector field, text object or any other sort of input produces the same results.

**Comment by Frooxius** [comment]
Fixed in 2021.2.22.855, sorry for the inconvenience!
