### ISSUE TITLE
Regression: Context menu automatically closes when opened while aiming at the dashboard and holding an item with your laser

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#1771]
## Describe the bug
While holding an object with your laser while your dashboard is open, if you open the context menu, it instantly closes itself.

## To Reproduce
- Spawn an object from your inventory e.g. a DevToolTip
- Grab the item with your laser, and attempt to open the context menu (e.g. to destroy or equip the item)

## Expected behavior
The context menu opens properly to perform the desired action.

## Screenshots / Video
https://user-images.githubusercontent.com/54213390/108647300-27079e00-746d-11eb-997d-d261e2132d75.mp4

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.2.21.1425
 - Neos Platform: Windows
 - Regression: Yes, I believe it was last known working on 2021.2.7.1345

## Reporters:
Shifty# 7944

**Comment by Frooxius** [comment]
Fixed in 2021.2.22.855, thanks for the report!
