### ISSUE TITLE
DuplicatorTip no longer duplicates laser grabbed items.

### ISSUE THREAD

**Issue by Aerizeon** [Frooxius/NeosPublic#1772]
## Describe the bug
Cataena and Medra both report that DuplicatorTip (and user tools which rely on its functionality) no longer allows items to be duplicated by laser grab.

## To Reproduce
1. Spawn a duplicator tip (create an empty object, attach a DuplicatorTip component)
2. Laser grab an item
3. Press trigger to duplicate 
4. Observe that item does not duplicate as anticipated
5. Physically grab item
6. Press trigger to duplicate
7. Observe that item successfully duplicates as intended.

## Expected behavior
Both laser grab and physical grab should allow duplication.

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.2.21.1425
 - Neos Platform: Windows
 - Regression: Yes (from 2021.2.7.1345)

## Additional context
It seems that laser grabbed items do not contribute to `ActiveTool.Grabber.GrabbedObjects` the same way that physically grabbed items do.
## Reporters:
Medra
Cataena

**Comment by Frooxius** [comment]
Fixed in 2021.2.22.855, thanks!
