### ISSUE TITLE
Bug: Locomotion and scaling bugs - Post Danger nightly updates and pushed builds as of 2/21/021

### ISSUE THREAD

**Issue by DeliriousJax** [Frooxius/NeosPublic#1773]
Describe the bug
Issues with locomotion, scaling, avatar setup.

To Reproduce
See Video below

Expected behavior
Locomotion speed to scale with size. Scaling certain object types not to affect gripping/grabbing/climbing/scale.

Screenshots / Video
https://www.youtube.com/watch?v=Uzgn8WN2WDM

Bug information (please complete the following information):
 - How often does it happen: Always.
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.2.21.1425
 - Link to reproduction: https://www.youtube.com/watch?v=Uzgn8WN2WDM
 - Regression: Yes.

Reporters:
DeliriousJax

**Comment by Frooxius** [comment]
Should be fixed in 2021.2.22.855, thanks!
