### ISSUE TITLE
Changing your scale no longer switches the noclip speed.

### ISSUE THREAD

**Issue by RileyGuy** [Frooxius/NeosPublic#1775]
## Describe the bug
Size no longer affects noclip speed

## To Reproduce
1) Become small or large
2) Your noclip speed will remain the same, making it difficult to move while large or small.

## Expected behavior
Your speed should scale with size.

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.2.21.1425
 - Neos Platform: Any
 - Regression: Yes, last live build before the stated version number.

## Reporters:
Gareth, June and possibly others.

**Comment by mralext20** [comment]
Duplicate #1773 ?

**Comment by Frooxius** [comment]
Yeah that seems like duplicate. Fixed in 2021.2.22.855.
