### ISSUE TITLE
Headless Instance / Server

### ISSUE THREAD

**Issue by Frooxius** [Frooxius/NeosPublic#178]
Provide a headless version of Neos that can host worlds without running the graphical interface. This would allow easily setting up a server on a dedicated machine or running it as a job in the cloud and allow persistent worlds.

The command line interface should allow basic commands to load worlds, list users, kick them and so on. Feel free to add a list of features you'd like to see.

One interesting feature would also be a meta-manager, which would keep track of current Neos VR versions and download/update/restart the headless version appropriately (e.g. when all people leave the world, shut down, update and start again), as to keep up with the frequent nightly releases.

**Comment by Simulacron3** [comment]
Most excellent. Will this work more or less like a High Fidelity server, then? Can there be networking among  the headless servers?

**Comment by sirkitree** [comment]
Would this work anything like https://github.com/janusvr/janus-server ?

**Comment by Frooxius** [comment]
It'll be pretty much just another Neos instance, just without visuals and only command-line input (or maybe desktop GUI?) and some extra behaviors around that.

I'm not sure which particular behaviors of Janus server and High Fidelity you have in mind though, so I'm not quite sure how to answer that.

**Comment by MR-Alex42** [comment]
A headless server is interesting to run worlds persistantly and continously.
I see use cases for procedural content creation, simulations and AI training.

**Comment by Simulacron3** [comment]
I was thinking in the direction of a distributed Neos multiverse, with individual worlds are hosted on various headless servers, yet the links between worlds (servers) is retained. If memory serves, that's a basic concept of High Fidelity. I imagine such a network layer is far from trivial to do right.

**Comment by AdmiralGhoster** [comment]
As part of this idea, would if be possible when you implimant this to have an neos based api. That way you can send commands over the network to the headless client such as 

tp2(user,object,postition), world uptime, world id, users active, all users, save world, close world, open world(world http) shutdown headless, restart headless, headless uptime, ect

**Comment by AdmiralGhoster** [comment]
Another thing i would like to ask about this is how is the heasless going to be hooked? Do you have to login useing your credentials,  can it save stuff to your inventory, will it generate a new credential everytime it loads(to key the headless to a user) will it act just like another user(can it be kicked, deleted, moved....), can it be a normal user or will it always host.

My last thought (for today) is will there be an option ingame(say under tools) to start a headless with your credentials on the computer alongside a headless exe launcher.

**Comment by AdmiralGhoster** [comment]
One more thought, along side a windows exe, will you also port it over to a linux os.

**Comment by Frooxius** [comment]
I plan on providing list of some simple commands that you could type into the console window that would let you do things like that, but don't have plans on some network API yet, that'd be a separate feature (although something I considered too in more general sense, for the normal version of Neos too).

However you could utilize that and control it remotely by feeding the right commands.

You'll be able to login with the headless using those commands (or a config/batch file). Not sure about normal user, technically it could be, but it wouldn't be able to do much without extra features.

I'm not sure what do you mean by the in-game option. Do you mean launching headless from the normal version of Neos? What would be the use-case for that?

Porting Neos over to Linux is planned, but that's also a separate feature: 
https://github.com/Frooxius/NeosPublic/issues/149

**Comment by guillefix** [comment]
Imagine a Wolfram NeosLink (instead of UnityLink) plugin :3 https://www.wolfram.com/language/12/built-in-interface-to-unity-game-engine/create-content-for-vr-and-ar.html , so that you can make data-driven or worlds that seize the power of some really powerful programming languages / libraries. But really I'd be happy with any sort of standard API

**Comment by Frooxius** [comment]
Probably not with headless instance alone, making an entire API for network modification is a big project on itself and separate from the headless client.

One thing that I will probably add is to invoke a custom function from the command line, so if you load a custom DLL you could use it to generate world that way and save. 

In the future once there's some form of general REPL in Neos, that would likely replace the command line and would give you a lot more flexibility.

Loading in scripts and DLL's is likely the best way to use the API too, since Neos is already synchronized. You could potentially even run another headless client and connect to a session and execute the changes if you wanted to run it from a remote machine or another process, Neos already takes care of the synchronization and you can interact with its API natively that way.

That said having some general data model modification API's is a possibility too, but would be a lot more harder to work with (plus a lot of work to implement), as it would give you more generalized view. On the other hand it could be used from other languages. But like I said, that's a whole separate project.

**Comment by AdmiralGhoster** [comment]
I wouldnt know how complex it would be but what if you had the headless client, on startup request a host ip and port punchthrough creating a secure server of sorts that on the remote side you enter the same ip,punch port and a password allowing you to send commands over the network/internet to the headless client. As part of the headless linking, a custom window for the remote would be opened with buttons for basic operations along with the command line for more complexe api request. This would also allow network commands to be passed from inside neos to the headless via(either a custom node or get string) logixs.

**Comment by guillefix** [comment]
I see. Thanks for the reply. I like the idea of using neos infrastructure itself for the networking.

Basically, I need to learn to use DLLs

**Comment by Frooxius** [comment]
> I wouldnt know how complex it would be but what if you had the headless client, on startup request a host ip and port punchthrough creating a secure server of sorts that on the remote side you enter the same ip,punch port and a password allowing you to send commands over the network/internet to the headless client. As part of the headless linking, a custom window for the remote would be opened with buttons for basic operations along with the command line for more complexe api request. This would also allow network commands to be passed from inside neos to the headless via(either a custom node or get string) logixs.

I think that would be adding a lot of unnecessary complications to the client itself. There are already existing solutions for sending commands remotely, like SSH or even remote desktop, adding extra protocol for this into the client itself would require more engineering and support.

If you're inside of Neos, then you can simply have appropriate role to control the world (e.g. Admin), so all the headless would need to know is who to assign the given role or have commands for assigning roles in the first place.

**Comment by Frooxius** [comment]
This is now available as of 0.8.16.x 
It's in early preview for Patreon supporters right now. Let me know your thoughts and requests for this!

Check out the Discord for discussion, there's #headless-client channel.

**Comment by Frooxius** [comment]
The configuration options have been greatly expanded for the headless client/server, interactive commands have been added and there's now even Linux build available! I'm closing this issue now, if you have any feature requests, bugs and other issues with it, start a new one specifically for that topic.

I'll keep it in private beta for a bit and make public probably in a week or two if things seem good!

**Comment by guysoft** [comment]
Any link to how to set up a Headless server in the documentation?

**Comment by Frooxius** [comment]
I recommend checking out the #headless-client channel on our official Discord: https://discord.gg/neosvr

**Comment by guysoft** [comment]
Ok, didn't know it existed because its only accessible to Gunter patreon tiers. At least that is the answer I got on the discord.
