### ISSUE TITLE
Add Outline for UIX Text

### ISSUE THREAD

**Issue by Toxic-Cookie** [Frooxius/NeosPublic#1789]
## Is your feature request related to a problem? Please describe.
Using the DevToolTip, you can create either a basic text or an outline text. The difference being whether or not you get an extra material to change the outline when it spawns out. UIX Text should have a similar option to either make a regular text or an outline text.

## Relevant issues
Found none

## Describe the solution you'd like
The addition of options to make an outline for UIX Text.

## Describe alternatives you've considered
Making a UI without using UIX works but isn't ideal for UIX based UI.

## Additional context
None

**Comment by Aerizeon** [comment]
The OutlineThickness is a component of the UI_TextUnilitMaterial, the same as it is with non-UIX text.
![textSettings](http://files.aerizeon.net/sharex/2021/TextUnlit.png)

**Comment by Frooxius** [comment]
@Aerizeon is correct here, this is something you can already do, you just need to create a new Text material, set it up as outline and assign this. The "Create New" option does the same thing as well, creating both the text and the material for you.

For UIX, if you use the outline on multiple instances of text, I'd strongly recommend using a single material shared on all instances of Text for better performance.
