### ISSUE TITLE
Adding Convert to on the materials 

### ISSUE THREAD

**Issue by RoxyBoxxy** [Frooxius/NeosPublic#1793]
I would find it very helpful if we had a convert to on materials, e.g if a user brings in a model with pbs instead of using the material tool the user could simply press convert to and pick a different material

**Comment by RoxyBoxxy** [comment]
for example 

![dRad](https://user-images.githubusercontent.com/8870878/109434274-6a817f80-7a0c-11eb-812e-3eadb4e25ed5.png)

**Comment by shiftyscales** [comment]
This would be taken care of by #1661. Marking this issue as a duplicate.

**Comment by RoxyBoxxy** [comment]
@shiftyscales thats for batch conversion this would be singular, most people have multiple materials

**Comment by shiftyscales** [comment]
Okay, I think I understand the request. As a curiosity, then - what is it about the material tool that you don't like/why doesn't it work for you in this scenario @RoxyBoxxy?

**Comment by RoxyBoxxy** [comment]
ease of access e.g. say if pbs does not look good on my avatar instead of getting the material tip out and loading the material into the tool i can open the material and convert it to a different one without using the material tip

**Comment by RoxyBoxxy** [comment]
Veers tweak would mean i would have to convert all of my materials and that's not what i would want to do

**Comment by TehTurk** [comment]
This wouldn't make much sense as this would invalidate the use of the material tip. The point of the tools typically is to use them to modify or edit an object within the world. This would go against design sense in some form.
