### ISSUE TITLE
Auto-generated Material and Mesh tips have no colliders

### ISSUE THREAD

**Issue by Hayden-da-Serg** [Frooxius/NeosPublic#1798]
## Describe the bug
When adding the MeshTip or MaterialTip components to an object, these components automatically generate a basic tip, however these tips have no colliders, so you can't interact with or select them using raycasts.

## Relevant issues
None to be found

## To Reproduce
- Create an Empty Object
- Attach the MaterialTip or MeshTip component

## Expected behavior
The basic tips should be generated with a collider so they can be grabbed and properly used, ideally a primitive cone or sphere collider somewhere.

## Screenshots / Video
N/A

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.2.28.1210
 - Neos Platform: Any
 - Link to reproduction World/Item: N/A
 - Regression: Unknown, I feel like they did have colliders at some point but I could be wrong.

## Additional context
N/A

## Reporters:
Hayden#3180

**Comment by Frooxius** [comment]
They're not supposed to, they're templates for building the tools. Use the versions from Neos Essentials.
