### ISSUE TITLE
Transferring worlds

### ISSUE THREAD

**Issue by pushstartvr** [Frooxius/NeosPublic#187]
Transferring worlds between cloud and local machine seems to break sometimes, leaving the worlds corrupted and stuck in the "transferring" state.  I have lost multiple worlds trying to do this.
there needs to be something in place that if the user exits while transferring is taking place then it can continue once the user re opens neos.  
I think this has also led to my other worlds being corrupted.  If there was a world info panel open (the arrow next to the world orb) when this transfer bug presents itself then these worlds also cease to function correctly.  
I can elaborate on this if need be

**Comment by shiftyscales** [comment]
This mechanic had been dropped/deprecated in favor of using 'save as'/'save copy'.
