### ISSUE TITLE
Hover highlights

### ISSUE THREAD

**Issue by Frooxius** [Frooxius/NeosPublic#19]
https://steamcommunity.com/app/740250/discussions/0/3211505894145549553/

* The ability to drag multiple objects at once (inside the controller sphere) is a bit fun and neat. however I feel like in most cases it would be more useful if you interact with one object at the time (per hand) and that you can see which object via hover-highlight before you start the action.

- In general for any object when in laser mode? This could help indicate which objects can be interacted with and which cannot and in what context
- The highlight level would also be delegated to the current tooltip, so it's clear which element it'll interact with

**Comment by pushstartvr** [comment]
you could also highlight mutiple objects in succession like CTRL click for files

**Comment by Frooxius** [comment]
@pushstartvr Yeah definitely! You can do that right now with the developer tooltip, if you switch it to the "multi" selection mode, but I've been thinking about making selection independent of the tool.

Also another note, the highlight should show the label/name of the object.

**Comment by shiftyscales** [comment]
I don't believe this is relevant any longer.
