### ISSUE TITLE
Locomotion Modes shown like the Online Status menu

### ISSUE THREAD

**Issue by wel97459** [Frooxius/NeosPublic#209]
As talked about in the Discord, 
Moving the Locomotion Modes to the same type of menu system as the online status may help new users find the Locomotion switching more easily.

**Comment by Casuallynoted** [comment]
Likewise, I think it might be really helpful to have Neos give you a notification if you’ve switched a world and you’re locomotion type has been automatically changed. That way there’s less chance of a new user being disoriented! :)

**Comment by Frooxius** [comment]
Closing this one, since it's no longer relevant with the Radiant UI and the old UI is going away.
