### ISSUE TITLE
Blue orb no longer works when physical locomotion is active

### ISSUE THREAD

**Issue by pushstartvr** [Frooxius/NeosPublic#212]
the blue - line up all users - orb no longer works when physical locomotion is active

**Comment by Frooxius** [comment]
Thanks, this is a known issue, but doesn't have an easy fix right now. The physical locomotion is not compatible with this tool, as it keeps overriding the user's position every frame, so any changes via this get overwritten. 

I suggest using Fly/Teleport if you want to use this tool.

**Comment by shiftyscales** [comment]
I don't believe this issue is relevant anymore.
