### ISSUE TITLE
Provide a means of collapsing data in the menu

### ISSUE THREAD

**Issue by sirkitree** [Frooxius/NeosPublic#218]
## Problem
The data in the menu contains somewhat sensitive information that I'd rather not show on video when recording tutorials on how to use menu functionality.

## Proposed solution
1. Provide a means of collapsing this data, or allow the user to move it.
1. Or perhaps place this information into the profile window.

**Proposal 1 collapsed**
![image](https://user-images.githubusercontent.com/28543/54099487-d0375580-4376-11e9-96e1-53d9256b37c8.png)
**Proposal 1 expanded**
![image](https://user-images.githubusercontent.com/28543/54099556-1b516880-4377-11e9-8a56-27839ed7e652.png)
*green highlight suggests clickable area*

**Comment by Frooxius** [comment]
I've added a setting which lets you hide this. Will push later today.

**Comment by sirkitree** [comment]
thanks!
