### ISSUE TITLE
Provide a means for posting data

### ISSUE THREAD

**Issue by sirkitree** [Frooxius/NeosPublic#219]
Use case:
- create a form through input components
- filling out a form in Neos
- post that data to an outside system of record

**Comment by Frooxius** [comment]
You can already do the first two with the components present. The third one would require some sort of API interaction, like a HTTP POST node which will be added at some point. You could tack on the data onto a query of HTTP GET request too, although that's less elegant.

**Comment by sirkitree** [comment]
Right, the HTTP POST is the request here. 👍

**Comment by sirkitree** [comment]
closing as part of #222
