### ISSUE TITLE
Trouble importing model from Quill

### ISSUE THREAD

**Issue by sirkitree** [Frooxius/NeosPublic#228]
Quill is an Oculus app that allows for shadeless drawing in VR. It has an export feature and when I attempted to import this into Neos, it hangs on the "Converting" step. I've tried using the regular 3D model option as well as the Vertex color option on file import.

Log:
[SIRKITDOZE 4_13_2019_10_24_35_AM.log](https://github.com/Frooxius/NeosPublic/files/3076514/SIRKITDOZE.4_13_2019_10_24_35_AM.log)

sample .fbx from Quil
[orgchris.zip](https://github.com/Frooxius/NeosPublic/files/3076517/orgchris.zip)

**Comment by Frooxius** [comment]
Fixed, looks like there's a completely empty mesh in that file that was tripping it up. Will be in the next build. Thanks!
