### ISSUE TITLE
Feature Request: Add LogiX packing to Undo history

### ISSUE THREAD

**Issue by sirkitree** [Frooxius/NeosPublic#230]
After packing a large logix setup, it would be great if that could be an 'undo-able' thing.

1. Create logiX
2. Point at logiX w/logiX tool, hit secondary action to pack.
3. Open radial menu on opposite hand, click undo to unhide/unpack all LogiX that was just hidden by packing.

**Comment by Frooxius** [comment]
This is planned, closing as duplicate of this: https://github.com/Frooxius/NeosPublic/issues/203
