### ISSUE TITLE
Add datetime stamp to friend message

### ISSUE THREAD

**Issue by sirkitree** [Frooxius/NeosPublic#235]
This would be very useful for me, especially since NCR transactions happen through this system and knowing what date a particular transaction happened is important to me.

**Comment by Frooxius** [comment]
This is planned and the timestamps are already part of the message data, but are waiting for the UI redesign. I'll see if I can add it just to the NCR transactions for the time being though.

**Comment by Frooxius** [comment]
I've played with it a bit to see how it would look like with just simplistic timestamp and I've decided to add them to normal messages too, but filtered (so it only shows if the time difference between messages is too large to prevent cluttering it up too much).

Once the UI is redesigned I want to do a fancier design that has more traditional layout (the kind that chat clients usually have), but this should help a lot for now without taking up too much space.

It's going to be in the next build!

**Comment by sirkitree** [comment]
Thanks!

**Comment by Frooxius** [comment]
Oh forgot to close this one, it's already implemented!
