### ISSUE TITLE
Add sound or popup for new messages

### ISSUE THREAD

**Issue by sirkitree** [Frooxius/NeosPublic#236]
When I get a new friend request, or someone messages me, I'd like to have a sound play or a popup notification to alert me. Otherwise, if I have my menu closed, or I'm not looking at my chat window, I miss messages, and someone may be waiting for a while before I see it. This is only really a problem when trying to meet someone online and we may end up missing each other if I don't see the message in time. An alert of some sort would help this.

**Comment by Frooxius** [comment]
This is planned, but I need somebody to make a proper sound set for Neos so I can integrate them. I've had a few users try and take a crack at it, but so far it wasn't done.

**Comment by sirkitree** [comment]
Do you have a list of sounds you're looking for in regards to a sound set? I now some peeps who might be interested in helping with that :)

**Comment by Frooxius** [comment]
Yes! I got sound design document here with the general feel that I'm going for:
https://docs.google.com/document/d/1gBRouccDSveqo8xWuZ-9_iRFEhxsaSxcKonsoDfgMw4/edit?usp=sharing

And a list here:
https://docs.google.com/document/d/1qwXrDvVqNs_7guThBTa_pi3C_A5uGTqytB6wJQJLGBI/edit?usp=sharing

There's a little bit older and need some updating, but should cover a good area. I'd ideally like to get the sound design nailed first though before making the whole set.

**Comment by nadavoid** [comment]
I’m interested in helping with this. I’m a composer, play cello, and enjoy dabbling in all sorts of sound software. The ideas of sound design and music for games and film are very interesting to me. I have no experience with neos VR, and do not have VR gear or a windows machine. So I’m wondering, could someone record a video demonstrating all of the events listed in the linked doc? And would a set of small audio files work in terms of a usable deliverable?

**Comment by sirkitree** [comment]
Hi @nadavoid! 

You can get some ideas of these actions by looking through some of the existing videos on the [youtube channel](https://www.youtube.com/channel/UCxPXPA8QPbuI5FyHL9_FGwQ). Recording individual ones may take some time but I'll see what I can do. 

This really might be very hard if you can't install and run Neos though. Even through bootcamp might give you a better idea and feel.

**Comment by sirkitree** [comment]
Currently there is a facet you can grab from Hayden's public share (found in The Directory world) which, when added to your dashboard, will provide this functionality.

**Comment by Frooxius** [comment]
Added temporary sounds in 2020.11.13.1356! Once official custom ones are produced they'll get replaced, but this should work for now.
