### ISSUE TITLE
LogiX: Cast Nodes

### ISSUE THREAD

**Issue by ProbablePrime** [Frooxius/NeosPublic#249]
it would be nice to be able to spawn cast nodes on demand

int to float
double to float
float to double
string to uri

etc.

**Comment by BlaXun** [comment]
I agree. This would further improve/speed-up the (sometimes tedious) workflow with logix

**Comment by Frooxius** [comment]
It's planned but I need a type selection system for this first. Why do you need these explicitly however? Casting in most cases is handled automatically, so perhaps there could be improvements there too.

**Comment by ProbablePrime** [comment]
neos ji numeric up and down has a double data type on the value property. boom was trying to plug this into a float and it failed to automatically cast. i then tried to force a double to float cast on many other nodes and was unsuccessful

**Comment by Frooxius** [comment]
When did this happen last? Recently I made changes to the casting logic which should allow automatic downcasting from double to float.

**Comment by ProbablePrime** [comment]
today, try plugging a double into the float value of a logix interface

**Comment by Frooxius** [comment]
Oh that's a different issue, casting currently doesn't work when plugging directly into the interface. Try plugging a relay first into the interface and then the double into that.

**Comment by ProbablePrime** [comment]
ahhh thank you!!

**Comment by theboom1** [comment]
Thank you frooxius this helps me out.

**Comment by theboom1** [comment]
Ty prime for asking.

**Comment by theboom1** [comment]
relay didn't work to write a value to seed i did that another way and it worked i will post pictures in neos discord how.

**Comment by wel97459** [comment]
> relay didn't work to write a value to seed I did that another way and it worked I will post pictures in neos discord how.

Please put the image here as part of the issue so that it does not lost.
You can drag the image into the text window here when commenting.

**Comment by Frooxius** [comment]
The system is now implicitly down-casting doubles to floats and other types when it's not possible to convert otherwise. I'll have explicit prompt for this in the future, but should work now. Closing now.
