### ISSUE TITLE
Change to physical mode and gripping

### ISSUE THREAD

**Issue by DeliriousJax** [Frooxius/NeosPublic#251]
For physical mode, in addition to now no longer allowing accidental size adjustment, instead of moving locomotion controls to one hand while holding something and letting you rotate or push/pull an object, disable the push/pull or rotate feature and keep that controller for locomotion while holding objects in physical mode. It'd help tremendously for the sake of testing and setting up social/immersion based worlds and won't throw people off when simply grabbing an object and wanting to take it from one locations to another when doing something simple such as solving a maze/puzzle.

**Comment by Frooxius** [comment]
Oh that's a good idea, I'll try to get it into the next build or the one after. Thanks!

**Comment by SecretHippo1** [comment]
Oh that is a good one, I think I always subconsciously wanted this but couldn’t put my finger on it. Thanks, Jax!

**Comment by Frooxius** [comment]
> Oh that is a good one, I think I always subconsciously wanted this but couldn’t put my finger on it. Thanks, Jax!

That's because you don't have your finger tracking yet! :D

**Comment by Frooxius** [comment]
Implemented in 0.8.9.2846, thanks!
