### ISSUE TITLE
Request: UrlEncode and UrlDecode Nodes

### ISSUE THREAD

**Issue by ProbablePrime** [Frooxius/NeosPublic#253]
I saw Ghostlight and a few others struggling with Spaces and other characters within urls. 

I also saw a manual url encoder comprising of a TON of string replacement nodes. It seems like a node to do this same operation would be a lot more performant.

**Comment by ProbablePrime** [comment]
Actually maybe the GET node should just urlencode by default?

**Comment by Frooxius** [comment]
I think it's better to add these as encode nodes, otherwise all nodes that accept Uri would need to have variant which accepts strings too and then it gets really messy. I'll see about adding these. Thanks!

**Comment by Frooxius** [comment]
Implemented in 0.8.9.2846 thanks!
