### ISSUE TITLE
Bug in movement mode switching

### ISSUE THREAD

**Issue by wel97459** [Frooxius/NeosPublic#255]
The other day I notice a weird bug when switched from fly to walk / run.
I would get teleported back to the spot where I had switched to fly.

This was happening in Sabby's The Luau Life world.

**Comment by Frooxius** [comment]
Were you far below the map in the volcano? This most likely isn't a bug, the locomotion module is configured by default to teleport you back to latest known good location (where you were on a ground in Walk/Run) when you get far below the map.

If you don't want that to happen  you need to reconfigure the locomotion module to change/disable the "below map" distance.

**Comment by wel97459** [comment]
no, I was floating above the ground both time I believe.

**Comment by Frooxius** [comment]
Do you have logs from the session? Or reliable way to reproduce this?

**Comment by wel97459** [comment]
I'll have to try and reproduce it later. I'll close the issue if I can't.

**Comment by wel97459** [comment]
I'm going to go ahead and close this issue.
