### ISSUE TITLE
Relay hosting client.

### ISSUE THREAD

**Issue by AdmiralGhoster** [Frooxius/NeosPublic#259]
(Aka repeter client)

The idea is to have a secondary host below the main host that acts as a relay between the world host and many clients, reducing the amount of traffic to the world host allowing (in theroy) 1000 users in one instance.

Prerequisites 
1; transfer host protocol 
https://github.com/Frooxius/NeosPublic/issues/258
2: headless client
https://github.com/Frooxius/NeosPublic/issues/178

Recommended implemented features 
#175

The idea is that the headless client acts as a mini host, providing updates from the main host to the connected users as well as telling the world host what the connected users are doing. The way to switch between the relay host and main host would be controlled by the area of infulance set in the headless relay settings and or the hierarchy movment of the user from the root to under the relay client. 

A new user node should also be added "current local user host" or "connected relay host"

Finally  a setting/value should be placed on the relay host for each user specifying that the relay host is the first priority and if the relay host leaves or disconects suddenly(say a crash) that the secondary host(aka main world host) should now take over and transfer all users connected to that relay host back under itself and reset the host priorities to the main being primary. (Aka make the main host a known backup host location when user is under a relay host)

**Comment by Frooxius** [comment]
This has been already implemented a while ago: https://github.com/Frooxius/NeosPublic/issues/96

Relays don't really solve the issues you're proposing though, they're just relaying traffic between clients when a direct connection cannot be made. Those issues will be addressed by other features.
