### ISSUE TITLE
Move object closer/farther with a swipe of the thumbpad

### ISSUE THREAD

**Issue by sirkitree** [Frooxius/NeosPublic#26]
When lasering a target object, I'd like to be able to move it farther away from me or closer to me. I currently must move my arm back and forward a lot for this, grabbing and letting go, or rely on teleportation, teleporting closer then grabbing, teleporting again to place where I want.

It would be a great usability improvement if I could instead **swipe up** on the thumb pad to move things further **away** from me, or **swipe down** to move the object **closer** to me.

What do you think?

**Comment by Frooxius** [comment]
Oh yeah, I wanted to add this one for a while!

**Comment by pushstartvr** [comment]
In SculptrVR on daydream they had it so you twist your hand to move it forward and back while grabbed to account for the 3dof controller.  not sure if that's something you would consider but it felt ok

**Comment by Frooxius** [comment]
Done and pushed to nightly-patreon. Might require some more tweaking for speed, but pretty much working now.

**Comment by sirkitree** [comment]
Sweet! Can't wait to get my headset setup to try this!
