### ISSUE TITLE
Avatar Related Logix Nodes

### ISSUE THREAD

**Issue by ProbablePrime** [Frooxius/NeosPublic#264]
I'm creating an avatar pedestal for GearBell and others. This has a posed static model that when clicked equips an avatar of that model.

To Achieve this i'm using the `Equip Avatar` logix node with my flow looking like this.

`OnTouch -> Copy Template Avatar Slot -> Equip Avatar with Copied Slot.`

The problem here is that it leaves the users previous avatar in the world in the exact same position as them. This can cause an avatar world to quickly become a mess.

To fix this i propose a few suggestions:
- Additional options on the Equip Avatar Node to determine what happens to the previously equipped avatar. For example "Delete Previous" defaults to false
- Nodes which get the avatar slot of a user. I tried various nodes in the users folder but couldn't get consistently the actual avatar. If this exists I can store a reference to the current avatar's slot and then delete that after my equip avatar node.

**Comment by Frooxius** [comment]
Yeah I could do the one where it deletes your previous avatar.

I'm not sure about getting the current avatar slot though. There's not necessarily a single slot, so doing it properly would require collections. 

However as an alternative for now I could add a node to load and equip their default avatar.

**Comment by ProbablePrime** [comment]
Deleting the previous avatar would be perfect and unblock me. Thank you!

**Comment by Frooxius** [comment]
Added the "Destroy Previous" in 0.8.11.26359. Should I keep the issue for the other nodes for the future?

**Comment by ProbablePrime** [comment]
i think leaving it open for more ideas make sense, if you'd like to keep things tidy feel free to close it though.

**Comment by Frooxius** [comment]
Okay closing this! Thank you!
