### ISSUE TITLE
Request: Set Grabbable Node

### ISSUE THREAD

**Issue by ProbablePrime** [Frooxius/NeosPublic#265]
For some tools i'm working on preventing grabbing on demand would be useful.

Inputs:
Impulse
Slot
Boolean - Grabbable or not.
Outputs:
Impulse

Exactly like the "Set Slot Active Self" node.

**Comment by Frooxius** [comment]
I don't plan on adding this one specifically, sorry. This will be handled generally by the component access ( https://github.com/Frooxius/NeosPublic/issues/243 ) which will let you fetch the components and access all their properties.

I want to avoid scenario where there are many nodes just for accessing properties of specific components. For now you could install extra logix on the items, but that's of course limited.

**Comment by ProbablePrime** [comment]
No worries, thank you
