### ISSUE TITLE
Index Controller Related Issues

### ISSUE THREAD

**Issue by ProbablePrime** [Frooxius/NeosPublic#266]
Just a few I came across last night:

- Trigger Based actions require a full trigger press. - I've noticed other VR titles and apps only require a 50-75% press. In Neos I have to bottom out the trigger for each action, this leads to a very clickly experience. I'm not sure if this is a bug or just intentional but wanted to mention it so that the team can think about how it aligns with people's expectations of the platform.
- Grabbing - Grabbing is very unreliable, I was trying to show Nex this last night but I didn't do a good job of explaining it. I'll record a video but I'll also describe the issue. It seems that grabbing with an index controller using lasers isn't entirely reliable. From certain positions or locations I feel the vibration of the controller signifying a grab but the object is not grabbed. At first I thought this was the box collides on my individual object but i also tried with a material orb and some standard primitives. My video will help more here i'll update this issue with it once recorded.

**Comment by sirkitree** [comment]
I too have experienced both of these issues.

**Comment by Frooxius** [comment]
Thanks for the info! Video for the grabbing could definitely help.

If you don't mind poking around settings a bit, you could try going to the SteamVR Input bindings and adjust the thresholds and see if it can make it more comfortable that way.

You can for example change the trigger_click action to use a threshold. Similarly grip has a "click" binding, which determines when something grabs, playing with the thresholds can help.

It's these settings:

![image](https://user-images.githubusercontent.com/8838625/60919981-63d25180-a297-11e9-8b81-29270cb97d85.png)

![image](https://user-images.githubusercontent.com/8838625/60920063-954b1d00-a297-11e9-947a-ccfde678074b.png)

**Comment by ProbablePrime** [comment]
I will play with these values, thank you I was not aware Valve had made them this extensive. 

Thank you! Grabbing video for sure when i get home from work :)

**Comment by ProbablePrime** [comment]
@Frooxius Here's that video, its abridged but I do have a longer 3 minute video of me trying to figure this out.

It seems like an angle thing. The reason I notice it so much is that the concrete material orb in the video is about the position i place my tools in sometimes especially when they are stored. 

In the video I setup a standard controller node so you can tell when i'm grabbing you can see it flashing between false and true mostly in the mirror due to camera angles. 

https://i.probableprime.co.uk/190710-GJjd8CggpRtWwf2fILAg.mp4

Additionally, i Cannot find the settings you described in the controller binding settings: 
![image](https://user-images.githubusercontent.com/8791132/60949908-fd572e80-a2aa-11e9-9c1c-9e1b200bcd08.png)

![image](https://user-images.githubusercontent.com/8791132/60949928-03e5a600-a2ab-11e9-9993-5d501d259b0c.png)


I noticed mine looks different than yours and has different options, I also see the word "legacy". I can poke around official steam sources here but wanted to mention it.

**Comment by ProbablePrime** [comment]
Closing this and relaxing, exceptional amounts of comfort have been achieved.

**Comment by sirkitree** [comment]
I'm curious as to what exactly you may have done. The gripping not working with laser sometimes still bothers me. Was there a specific setting you found?

**Comment by Casuallynoted** [comment]
I’m equally curious! Would love to do the 50-70% trigger activation, would make my experience less clicky as well! Same with grabs. Prime, did you happen to publish bindings if you made custom ones? :o

**Comment by ProbablePrime** [comment]
For Gripping, there was no change my end. I just booted the new release, everything works well for me. If possible i found what really helped here was to try and find a reproducible case. In this instance it was distance based. Objects closer to my face didnt grab.

As for triggers, im still working on adjusting my bindings but will publish them.

**Comment by AdmiralGhoster** [comment]
Yeah ive noticed that too. That you cant really interact with anything near to your head. Such that the grip/trigger lazers disapper and dont work to about 1-1.5 feet from the head.

**Comment by Frooxius** [comment]
Do you still experience this issue with the latest version? I did a fix in a recent build and haven't been able to reproduce it myself.

**Comment by Casuallynoted** [comment]
I wanted to comment on this and say that I've tried making a custom binding for the trigger changes mentioned earlier, and can't access the "input settings" dialogue on the trigger. Typically this would be accomplished via a little settings cog, but I don't see that on mine:

![image](https://user-images.githubusercontent.com/6272557/62511857-8cd8fa00-b7e3-11e9-99a4-a969eaf314e5.png)

**Comment by Anomalous** [comment]
I'm seconding that I can't find any way to change the trigger_click action to use a threshold. Most programs, including the Steam VR interface, seem to respond to a trigger pull that stops just short of a click even with the default bindings. It would be nice if Neos had an option to do the same.

**Comment by Frooxius** [comment]
I'm sorry, but that's not unfortunately in my control, that binding interface is made by Valve. I'm not sure why is it not giving you the options to edit via the setting button, it should be there.

One thing you could try is clearing all the bindings so it starts fresh or reinstalling Steam VR. For some people the bindings were somehow corrupted, which caused the interface to misbehave.
