### ISSUE TITLE
Import 3d  model item  no bones with blendshape break when it import into neos 

### ISSUE THREAD

**Issue by Jazzneo** [Frooxius/NeosPublic#267]
When import item with no bones with blendshape and have skin mesh set it wont show up in the world like invisible.  when go in components for blendshape move the silder up the model become big mesh blob

**Comment by Jazzneo** [comment]
![image](https://user-images.githubusercontent.com/30747537/61013396-f7fbf180-a347-11e9-9185-e6b269f5d5fd.png)

this what happen when move slider on blendshape in neos

**Comment by Frooxius** [comment]
This should be fixed now in 0.8.12.6067. Let me know if you still run into the issue!
