### ISSUE TITLE
Spawn cloud asset node.

### ISSUE THREAD

**Issue by AdmiralGhoster** [Frooxius/NeosPublic#269]
Allow and expose cloud asset uid so that the node can spawn items from The Cloud instead of inventories or by dup'ing a slot.

This could be usefull for large worlds by incrementally loading assets from rhe cloud into the world and deleting others to allow bigger and more proforment worlds that dynamically load.

3 restriction should be;
Cloud assets must be in a public/shared folder or in personal inventory to be spawned. 

You can only load up to X mb assets in at a time

The world host must have at minimum builder perms and agree to load the assets.

**Comment by Frooxius** [comment]
Yeah I could add this one, all the things necessary are pretty much there. The only missing pieces are getting the items URL somehow from the inventory and making sure it's public (this can be done indirectly by creating a link to given inventory folder).

Neos does support name based lookup in the URL as well, so you could create the URL manually by providing name based path to given item. Would that work well enough for now?

**Comment by AdmiralGhoster** [comment]
yeah something like that could work, say having a public folder you can save things to in the inventory then the url could be "ghostlight/public/item1" or even something along the lines of "ghostlight/public/games/bar/beerpong" that way your not sharing the your whole inventory, just a certain part you define. part of the the output of the node should be a bool to see if it succeed/failed,

 with inputs being impulse(trigger spawn) 
cloud host(string/user)
location(string)
match case (bool)
use uid(bool)
uid (string/url)

and outputs being 
on done (impluse)
successful (bool)

**Comment by shiftyscales** [comment]
Merging this issue into #410.
