### ISSUE TITLE
Add "Auto Add Children" from Circle Aligner to Axis Aligner Component

### ISSUE THREAD

**Issue by ProbablePrime** [Frooxius/NeosPublic#270]
I love the circle aligner component, It lets me organise objects nicely around a circle.

I also love the Axis Aligner but it requires each object to be manually added, if it had the "Auto Add Children" property that the circle aligner had it would be awesome too. 

It would be great for arranging columns of items.

**Comment by Frooxius** [comment]
Oh good idea I'll add this in the next build (after a quick hotfix one)! Thank you!

**Comment by sirkitree** [comment]
Where do I find this magical circle aligner component?!

**Comment by Frooxius** [comment]
It's under Transform/Drivers!

**Comment by Frooxius** [comment]
Added in 0.8.12.8956 Thanks!
