### ISSUE TITLE
Detecting Lighting Component

### ISSUE THREAD

**Issue by AdmiralGhoster** [Frooxius/NeosPublic#271]
a component that gets the active lighting in the room for use in custom material manipulation.

 outputs the current highest intensity light mode(string{directional,point,spot}),
 light intensity on object(float), 
in shadow(bool),
 in shadow intensity(float{on shadow edge=.5, in center of shadow=1, not in shadow=0})

**Comment by AdmiralGhoster** [comment]
this can be for later on down the line as its not an important, need to have component, but could have some really cool uses in horror/darkly lit maps if a user decides to spawn a light.

**Comment by Frooxius** [comment]
Hmm. I could do a light detector component, but that wouldn't be able to give you any of the parsed information (whether you're in shadow or what the type of light is), just the light intensity (and color) at particular point.

Doing it with the extra information is a lot more complicated. It would require instrumenting all the lights with extra scripts and components (like colliders) to generate some data that can be queried and instrument all objects with mesh colliders (which is very performance heavy) so you could detect whether it's in shadow or not using the physics system.

The first approach is relatively simple to implement, although potentially somewhat performance heavy. 

The second one is significantly more complicated technically and would require you to prepare the whole scene and all objects to work with the detection.

If you don't care about it working in general case or actually detecting the light, there are things that I could add to allow for the horror games. Usually these are done through the physics system and things like visibility cones. It doesn't really have anything to do with actual light, you just setup the cone to correspond to the light. That's the usual approach that games like that take.

**Comment by AdmiralGhoster** [comment]
I was thinkinf about it and once component access is implimanted it could total replace the need for a specific node, as you could search for the light component and gets its pos/rot and calculate if the object in a lit environment or not. As for shadows you could use a raycast from the object to the light and check if there is any mesh in between those two points

**Comment by sirkitree** [comment]
Closing as I can't discern anything actionable here. Please reopen if I'm mistaken and there is.
