### ISSUE TITLE
offline textures and basic avatar

### ISSUE THREAD

**Issue by AdmiralGhoster** [Frooxius/NeosPublic#273]
I was at a friends house where i set up my vr but had no internet. when i loaded neos all of the textures didnt exist and when i tried to put on an avatar (the slot was named and there in the menu) it didnt load.

Can you set it up to permanently cache the basic user avatar and all the textures for the menus and stuff so when i go offline i can show people the game?

**Comment by Frooxius** [comment]
They should already be cached, but you need to load them at least once. Were they loaded before in Neos in online mode?

**Comment by AdmiralGhoster** [comment]
Yes? Ive always been online in neos (aka username ghostlight) unless updating clears the cache.

**Comment by Frooxius** [comment]
It shouldn't clear cache, but some other tools might. Do you have logs from the session when they wouldn't load?

**Comment by sirkitree** [comment]
Please reopen if you can provide more info
