### ISSUE TITLE
Add Private UI

### ISSUE THREAD

**Issue by Zyro1331** [Frooxius/NeosPublic#274]
I Thought Local Inspectors Would Be A Good Thing For Worlds With Many Users. This Could Help With Lag. Being Allowed To Make Local Video Players Would Be Good Too.

**Comment by Jazzneo** [comment]
frooxius said wont change much lag for local inspector panel

**Comment by Frooxius** [comment]
This is not too compatible with how Neos works and it wouldn't help that much anyway.

The lag is caused by the old UI framework, which will be replaced and resolve the issue while keeping things public, see this issue: https://github.com/Frooxius/NeosPublic/issues/167
