### ISSUE TITLE
Option to lock player scaling in settings

### ISSUE THREAD

**Issue by Casuallynoted** [Frooxius/NeosPublic#275]
I definitely think for oculus users in particular this would be very helpful- at the moment if you try to do a finger gun gesture for example and move your hands up and down your avatar grows and shrinks like crazy! XD Making it so you can effectively lock the player height and disable the scaling mechanism on demand would allow those gestures to be performed without unwanted player scaling.

**Comment by Frooxius** [comment]
This is planned with the UI rework. I'll rework the hand menus, so it's easier to add these options in without cluttering it some more.

Currently enabling Physical Mode will lock your scale as well.

**Comment by Casuallynoted** [comment]
Oooh sweet, that’s great to know! Thank you so much Froox!

**Comment by sirkitree** [comment]
Related #299

**Comment by shiftyscales** [comment]
This was taken care of a while ago with the scale lock toggle. It will soon be moved into a facet once the facet system is implemented.
