### ISSUE TITLE
Grabbable Issues

### ISSUE THREAD

**Issue by ProbablePrime** [Frooxius/NeosPublic#278]
- Deleting a slot that someone is actively grabbing will destroy their avatar
- Disabling grabbable on a slot that someone is grabbing will permanantly parent the object to their laser

In both cases a sort of "force drop" mechanic seems more suitable

**Comment by Frooxius** [comment]
Thanks for the info. How exactly are you deleting the slot that someone is actively grabbing? Is it through the inspector or hand menu or the developer tooltip? Did you manage to replicate that recently? I've made some changes with it not too long ago.

For disabling the grabbable the force drop makes sense, I'll add that, thanks!

**Comment by ProbablePrime** [comment]
I was using the Destroy Slot Node. Targeting the grabbed slot.

**Comment by Frooxius** [comment]
That's very strange, it shouldn't touch the user avatar unless you give it to the node directly. Are you doing anything like "GetObjectRoot" before passing the grabbed slot to the user?

**Comment by ProbablePrime** [comment]
Ok, i did some more looking here. I'm doing some hacky things involving the "only these users" and the simple avatar protection in this scenario. 

I'm not entirely sure what's going on but i'll try to make a reproducible object and send it to you.

**Comment by Frooxius** [comment]
If you're using simple avatar protection, then you're very likely triggering its self-destruct mechanism. It's designed to destruct the avatar at any signs of tampering.

**Comment by ProbablePrime** [comment]
Ahh, and then that's destroying me because im in its hierarchy. Got it :). 

I really just need to wait for the license stuff it seems :).
