### ISSUE TITLE
Make flying locomotion more like Google Earth

### ISSUE THREAD

**Issue by sirkitree** [Frooxius/NeosPublic#28]
While there is a flight mode within Neos, it's a bit confusing to use. The most recognized flight mode in use these days for VR is the way Google Earth uses it. Basically, point where you want to go and hit 'up' on the trackpad to fly forwards, or 'down' on the trackpad to fly backwards.

I think people would get this a bit more intuitively as it's a pretty common thing to have experienced this method of locomotion.

**Comment by Frooxius** [comment]
Okay, I've done a basic implementation of this and pushed to the nightly. I might need to adjust the default speed a bit.

You might play with default values yourself if you'd like,  open an inspector for the controller, find the "CommonTool" component and there's a property called "BaseFlySpeed".

**Comment by Frooxius** [comment]
This has been now finished with this one: https://github.com/Frooxius/NeosPublic/issues/14
