### ISSUE TITLE
Twitch Follows can be spammed

### ISSUE THREAD

**Issue by ProbablePrime** [Frooxius/NeosPublic#280]
![image](https://user-images.githubusercontent.com/8791132/62494065-700ed900-b787-11e9-9524-d7f9d7d719c0.png)

Usually Twitch bot developers will implement a short cooldown to prevent this but you can unfollow and follow repeatedly

**Comment by Frooxius** [comment]
You'd think Twitch would implement this themselves! :D I'll add some cooldown, thanks!

What do you feel is a good default? A few minutes? One per session?

**Comment by ProbablePrime** [comment]
A few minutes is enough to prevent the abuse, personally i always went with 24 hours

**Comment by Frooxius** [comment]
Added timeout to the TwitchInterface in the latest build. Thanks for the report!
