### ISSUE TITLE
Avatar Protection can destroy world objects

### ISSUE THREAD

**Issue by ProbablePrime** [Frooxius/NeosPublic#283]
Logging this formally based on our conversations so it doesnt get forgotten.

Using a SpawnPoint with the parent user option checked will sometimes result in the spawn point and its heirarchy all the way up to the nearest ObjectRoot being deleted when the avatar protection detects tampering.

This usually happens in users who lack a properly created object root component.

**Comment by Frooxius** [comment]
I've already fixed this in the upcoming build, but it's getting held up by the dynamic bone chain feature. Thanks for logging this though!

**Comment by Frooxius** [comment]
Build pushed, thanks again for the report!
