### ISSUE TITLE
Expose voice normalization settings

### ISSUE THREAD

**Issue by Anomalous** [Frooxius/NeosPublic#285]
Frooxius on 2019-08-06:
> Neos does perform voice normalization, so it could be that causing the issue. I'll expose the settings for that and you can experiment with it and see if it helps. 

This is in reference to attempting to get the microphone on my new Valve Index headset to work properly in Neos. It's picking up a large amount of background noise, enough to interfere with voice communication and sound-driven avatar actions.

I notice that the noise level is fairly low at first, but after the first time I talk the noise level rises about 4x and stays there. Looking at the mic level meter in Neos, it starts out with noise at maybe 10% and after after talking once the noise level bounces around 30-40%. Hopefully something that can be adjusted for if the voice normalization settings are exposed?

**Comment by Frooxius** [comment]
Yes, I plan on exposing this within the next build or two! Thanks for logging this.

**Comment by Frooxius** [comment]
Done and released! Thanks!
