### ISSUE TITLE
My right controller rotates laser grabbed items slower than my left

### ISSUE THREAD

**Issue by ProbablePrime** [Frooxius/NeosPublic#287]
I showed you this one last night but for a reminder. 

Grabbing an item in the world with my laser on the right controller  and using the joystick to rotate the grabbed item is noticeably slower.

**Comment by Frooxius** [comment]
Hmm this is really odd. I'm looking at the code doing the rotating and I don't really see anything that might explain it, the rotation speed is directly based on the horizontal value coming from the joystick. 

Do you know the controller diagnose tooltip? If you take that one and watch the values coming from the joystick, are they going from -1 to 1 when you fully tilt it left and right?

**Comment by ProbablePrime** [comment]
I will take a look and record some data / videos.

Thank you :)

**Comment by ProbablePrime** [comment]
Did some testing, its my avatar. Can you think of any reason? Could be tooltip anchor be scaled or tweaked somehow?

**Comment by Frooxius** [comment]
Hmm maybe. I'm not really sure, you'll have to do some digging/testing on your end to see. If you can find any inconsistency.

**Comment by ProbablePrime** [comment]
I inspected the scale, rotation and any other properties of both my hands and couldnt find any inconsistency. This is very puzzling :(

**Comment by Frooxius** [comment]
Should be fixed in 0.8.14.31025 Thanks for all the investigation on this! :D
