### ISSUE TITLE
Adding lots of audio severely reduces framerates

### ISSUE THREAD

**Issue by sirkitree** [Frooxius/NeosPublic#29]
I imported a sound file, made it loop, and then duplicated it a bunch of times and added them to a bunch of models. The intent was that eeach sphere in the scene would have a low hum that you hear as you get closer to it. But it *really* started lagging render times. So I removed them and opted for just one ambient audio sound.

I don't know if adding lots of players is what did it, or if perhaps my wav file was too large and duplicating it many times was the problem. 

Attaching the file I was using.
[low-frequency-humming-noise.zip](https://github.com/Frooxius/NeosPublic/files/1956483/low-frequency-humming-noise.zip)

**Comment by Frooxius** [comment]
How many did you make? The audio system could very likely use some significant optimizations.

**Comment by BlaXun** [comment]
I placed about 7 xm, it, mod files in my room (which created video players) and I also got regular hiccups ... became pretty annoying

**Comment by shiftyscales** [comment]
This no longer appears to be an issue.
