### ISSUE TITLE
Entered User's Invite/Private Session while Private 

### ISSUE THREAD

**Issue by TehTurk** [Frooxius/NeosPublic#290]
https://cdn.discordapp.com/attachments/439422161657135106/612157010498289674/17.8.2019_-_1-24-11.webp

**Comment by Frooxius** [comment]
Can you explain what exactly happened? Are you sure the session was Private when you entered and not changed afterwards? How exactly did you enter the session?

**Comment by TehTurk** [comment]
Host said session originally was on friends, but apparently I was able to join somewhat 30-60 minutes late after session had been turned to private and invite only.

**Comment by Frooxius** [comment]
How did you join the session exactly?

**Comment by TehTurk** [comment]
Through the world session table in my local world.

**Comment by Frooxius** [comment]
Hmm, I'm doing some investigation, but I can't find anything wrong with the process or the code. I'll need some more information to figure out what this was.

- Who was the host of the session? 
- How soon did you check if the session is private after joining? 
- Did you join the same session before when it was Friends only?

**Comment by TehTurk** [comment]
I dm'd you the host, I was immediately notified by the host and checked myself. I had not joined the session before it was Friends only. I'll let the host know.

**Comment by TehTurk** [comment]
This was fixed forever ago, so gonna go ahead and close it.
