### ISSUE TITLE
Unresolved References in worlds with Jaw Setup(Business Lawyer's Tool)

### ISSUE THREAD

**Issue by ProbablePrime** [Frooxius/NeosPublic#292]
![20190821222017_1](https://user-images.githubusercontent.com/8791132/63630853-29690d80-c5d4-11e9-8127-3d25dc5d8ed9.jpg)
![20190822000026_1](https://user-images.githubusercontent.com/8791132/63630854-2c63fe00-c5d4-11e9-959c-144b5e0eba41.jpg)
![20190821215741_1](https://user-images.githubusercontent.com/8791132/63630859-3685fc80-c5d4-11e9-870b-38d60af1caf9.jpg)

Something is up with these worlds. Avatar Setup and Build a Yeen.

I haven't edited this world in a couple of updates and now i'm a little apprehensive to do so with the hierarchy looking like this.

**Comment by Frooxius** [comment]
Fixed in 0.8.14.19307, thanks!
