### ISSUE TITLE
Adding Data Components of Certain Types Crashes Neos

### ISSUE THREAD

**Issue by ProbablePrime** [Frooxius/NeosPublic#293]
Attach Component -> Data:
- ValueNode<FrooxEngine.Slot> 
- ValueeNode<FrooxEngine.User>

**Comment by Frooxius** [comment]
Hmm that's because those aren't valid generic types for those. Can you send me crash log so I can add a guard against it?

**Comment by ProbablePrime** [comment]
Absolutely, I have a few I'm just not sure which ones which so i'll wait for my controllers to charge and then go purposefully crash myself :)

**Comment by Frooxius** [comment]
Sweet that will help a lot! By the way for Slots, Users and other things that aren't data primitives you can use Reference variants of the data components.

**Comment by ProbablePrime** [comment]
I figured that out after 3 crashes :), Gesture wheel uses them for super modularity.

**Comment by Frooxius** [comment]
Fixed in 0.8.14.18446 Thanks!
