### ISSUE TITLE
HorizontalChoiceBar is hard to use and configure

### ISSUE THREAD

**Issue by ProbablePrime** [Frooxius/NeosPublic#294]
Adding additional Items to a Horizontal Choice bar requires manually entering all of the properties into the items array. Even if you duplicate and existing item.

Additionally the top level component has no way to see what item is touched or clicked upon.

I'm working around this(see build a yeen), using touchable and manually creating the items.

But for an item present in the dev tool tip create menu it would be good to eventually make this better for users.

**Comment by Frooxius** [comment]
I would avoid using this one at the moment, I'm not happy with the way it's designed and I'll probably rework it at some point. 

A really good alternative is building your own elements using TouchValueOption<T> component with your own elements. What you do is you attach each one on an element that represents it and you point it to a data field that it should change when touched. 

It also has handy boolean drivers for when it's active and when it's hovered above. The interactive camera uses this for its resolution and mode options.

**Comment by ProbablePrime** [comment]
OOO niceeeeee!!!, 

That and a boolean switcher leads to an easy tab system. 

![](https://cdn.discordapp.com/attachments/472301183080333332/615014631060013098/20190824194644_1.jpg)

Ill rip out the horizontal choice and replace it with this setup :). Thank you!

**Comment by ProbablePrime** [comment]
TouchValueOption is amazing. I recorded a video paring it up with some other components to re-create this tab system. Thank you for pointing it out :).
