### ISSUE TITLE
[Bug/UI] Backspace on virtual keyboard fails to input if shift/caps lock is enabled.

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#298]
While the virtual keyboard is open on any field, and the character set is on capital letters- either through use of the shift key (single click) or caps lock (double click on shift)- the backspace button will not function.

If set to shift- it will act like an ordinary keypress, and change the case. But it will not delete the character, and will function normally afterward.

If set to caps lock- the case will not change, and the backspace button is non-functional until the case is lowered by pressing shift again to disable caps lock.

Physical keyboard input is unaffected, regardless of the state of the virtual shift key.

**Comment by Frooxius** [comment]
Fixed in 0.8.14.25762, thanks!
