### ISSUE TITLE
Hide/Show Keyboard

### ISSUE THREAD

**Issue by sirkitree** [Frooxius/NeosPublic#3]
Currently there is no way to hide the keyboard. You have to move it around to keep it out of your way which can be slightly awkward. It would be desirable to have a way to close the keyboard, and maybe re-summon it from a button on the main menu, or within the context menu.

Adjacent to this, it would be nice if the keyboard popped up in front of me when selecting any sort of text input, such as within the developer panel.

**Comment by Frooxius** [comment]
Done, pushed to nightly channel.

**Comment by sirkitree** [comment]
I was trying to figure out how to do this in the latest build, but I don't see a way to hide the keyboard. What did you do?
