### ISSUE TITLE
PBS Stylized Shader/More shader options for existing PBS shaders

### ISSUE THREAD

**Issue by InsaneGrox** [Frooxius/NeosPublic#300]
Shader Edit/ New Shader Idea: PBS Stylized (or it could simply be extra properties to put into the existing PBS shaders)
Properties: Identical to PBS Metallic, with the exception of having an outline property, a lightwarp property, a rim lighting property, custom specular highlight property, and possibly more toon-ish properties
Reason for this existing: Because flat lit toon isn't good for everything, there are things that should use a PBR workflow, while having partially cartoony lighting.
Examples of use: TF2 Stylized Characters (the illustrative art style of TF2 doesn't use 100% sharp flat lit shadowing, instead it uses a mixture of phong, rim lighting, and a toon ramp texture to control the lighting, while having most properties being identical to a regular shader at the time), Borderlands Characters (believe it or not, they are not flat lit, infact their shadows are actually very tf2-like with the edges being soft).
by the way, yes this shader would be very simular to rerostandard, a shader made for unity/VRchat, however there are some things that would definitely differ, I doubt fallback reflections would have any place existing in neosVR, atleast for right now, not to mention the fact it would be using a toon ramp texture, not a shader sharpness setting (unless it would be way easier to implement and or look better).
(response to someone saying flat lit toon exists) 
I'm not talking about flat binary lighting, I'm talking about a stylized PBR shader, which would have the metallic lighting, I'm highly doubtful you can get this with flat lit toon OR PBS metallic/specular
![image](https://user-images.githubusercontent.com/54233743/63992108-5461ce80-cab8-11e9-8418-9b64081d7b8d.png)
an example of a toon ramp texture would be this (left being darker, right being brighter) which would control the shadow's sharpness and color tinting simultaneously (lighting would still interact with the model like a PBR shader, just with the toon ramp tinting the model based on brightness in addition to the color and brightness of the light source, 127,127,127 grey would have no effect on the model at all)
![image](https://cdn.discordapp.com/attachments/477711742001086505/616497954076753930/unknown.png)
Suggestion posted in discord, someone else suggested putting it here due to the fact it might get lost however.

**Comment by Frooxius** [comment]
Can you paste the description of the request here as text please? It's easier to work with.

What more options do you want for the existing PBS shaders?

This could be done, but there would also be more limitations compared to the normal PBS shaders. This requires changes of how the lighting is computed and applied, which will force this into the forward rendering pipeline, which limits the lights that can affect the shader.

**Comment by sirkitree** [comment]
@InsaneGrox please reopen if you can provide the information requested from @Frooxius

**Comment by InsaneGrox** [comment]
pretty much Implemented with the Xiexe toon shader
