### ISSUE TITLE
Request: Add Auto-Add Children to BooleanSwitcher

### ISSUE THREAD

**Issue by ProbablePrime** [Frooxius/NeosPublic#301]
I'm sorry to ask, but I love the components like this being magical. 

There's already a button within the gui of this component which will setup for children but that's a button and not the automatic process that the other components in the "Aligner" series do.

This always leads to amazing returns in dynamic setups. In this case a box that can store a random item in the style of COD: Zombies which Artleck is trying to build.

**Comment by Frooxius** [comment]
Added, thanks! I've refactored the class so I have one generic one that has the auto-add children functionality and all the components that use it inherit from that now, so it's easier to add :D
