### ISSUE TITLE
Errors baking LexiChi_V4

### ISSUE THREAD

**Issue by ProbablePrime** [Frooxius/NeosPublic#304]
Just logging this as a reminder. I sent you a log with the issue. You can visit Build a Nanachi for the model. Just try to bake the meshes slot underneath the root of the model file. 

" Looks like some error when encoding the blendshapes, but I'm not sure what's causing it."

**Comment by Frooxius** [comment]
Oh thanks for the reminder, I forgot about this one! Going to look into it.

**Comment by Frooxius** [comment]
Fixed, thank you!
