### ISSUE TITLE
[UI/QOL] Prevent critical components from being deleted in scene inspector

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#305]
Neos should warn, or prevent players of all permissions, including admins from being able to remove critical components from the scene such as the User Spawner, Assets folder, Roles, etc.

As is- if critical components are deleted, Neos will respawn them as required such as the Undo Manager and Users- but deleting them can still be problematic- especially if the Asset folder is deleted from the scene.

Critical components such as the Assets folder could have protections in place to keep them from being deleted by a single button press, e.g. locking them down from being deleted from the scene and providing a warning/confirmation when a user attempts to do so.

As described in #306, visually separating critical components from the rest of the scene could also be useful.

**Comment by ProbablePrime** [comment]
For assets objects should also be prevent from being added here. One user did this not knowing what Assets was for and it ended up messing up the world after saving closing and then opening.

**Comment by shiftyscales** [comment]
Since the creation of this issue, protections have been added for cases where the user spawner, and roles are deleted, satisfying many of the concerns raised.
