### ISSUE TITLE
[UI/QOL] Organize and sort inspector view

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#306]
Categorizing/organizing the inspector's tree would improve in navigation of the scene by keeping all assets, and objects that are a part of the saved world distinctly separated from those added in by users during a session.

Critical components e.g. the Assets Folder, Users, Undo Manager, etc. could have their own folder in the root, assets/objects that are a part of the saved scene/world have another folder in the root, and anything new/created during a session/currently unsaved into the world have a third folder in the root.

This would greatly improve the creative work flow by giving players a list of unsaved/new assets, and objects that are separate from the rest of the scene, and allow them to more easily find, and modify them without scrolling through the full scene list- which is an increasingly difficult task the longer a session has been active/the more components are in a scene.

Additionally, being able to sort the inspector tree would also help with navigation. By default it is organized by the order elements were added to the scene. Sorting options for alphabetical, most recently modified/edited, and reverse chronological (newest to oldest) would also be a great QOL improvement for creators until such point as the UI overhaul milestone is shipped.

**Comment by sirkitree** [comment]
Closing as this seems invalid by the response, though something will be done to address this in a different manner (search).
