### ISSUE TITLE
Previously set world permissions are persisted and uneditable

### ISSUE THREAD

**Issue by ProbablePrime** [Frooxius/NeosPublic#308]
Scenario:
- I'm building a world and everyone is defaulted to spectator. 
- Someone asks to be builder so i give them builder
- They leave the world
- When they re-join they default back to builder and I have to manually re-set them to spectator

I can't do this on a published world easily which means that for a published locked down world its possible that there are users that I dont know about or cannot remember that can have a higher permission set.

I'd like to be able to either clear or manage previously set permission groups for users who have left somehow.

**Comment by Frooxius** [comment]
Yeah I can add a clear button for now for this.

The more detailed management would probably come together with more tools/interfaces for fine tuning the permission system.

**Comment by ProbablePrime** [comment]
Thank you!
