### ISSUE TITLE
Comfort Option to Disable Other User's Ability to Climb on You

### ISSUE THREAD

**Issue by StarfishHidari** [Frooxius/NeosPublic#311]
It would be helpful to have an option in the settings that would disable the ability of other players to climb on you. It is often very uncomfortable when others are scaled down and climbing on you, and you have no way to get them off of you or stop them from climbing on you in the first place. Often people climbing on me gives me very bad sensory input that is uncomfortable but I do not have an easy way to stop from happening.

This can be worked around in various ways, but it would be much easier to use if it was a setting that was easily accessible and didn't require the modification of your avatar, the world settings, or any other manual method.

**Comment by Frooxius** [comment]
This is already implemented, simply attach the LocomotionGrip component on the character and disable it. See here: https://github.com/Frooxius/NeosPublic/issues/310
