### ISSUE TITLE
UserHeadOutputDevice returns Vive for Index Users

### ISSUE THREAD

**Issue by ProbablePrime** [Frooxius/NeosPublic#313]
![20190911201602_1](https://user-images.githubusercontent.com/8791132/64934547-648be480-d800-11e9-9914-733ee13e83a6.jpg)

**Comment by Frooxius** [comment]
This is technically correct. The Head Output Device doesn't represent the specific headset the user has, but rather then tracking "class". Any SteamVR device will report as "Vive" right now.

I'll see if I can rename it to "SteamVR" at very least without breaking too much stuff.

**Comment by Frooxius** [comment]
It's changed to SteamVR now, should be less confusing. Thanks!
