### ISSUE TITLE
GET request on headless client

### ISSUE THREAD

**Issue by Anomalous** [Frooxius/NeosPublic#316]
Can we have a way to approve approve GET requests run as host user on a headless client instance? A way to approve any request would be ideal, but even allowing requests to localhost / 127.0.0.1 would be useful.

**Comment by Frooxius** [comment]
Currently there's not. I could add a list of allowed hosts to the config file.

**Comment by Anomalous** [comment]
That seems like a good solution! a GET request host name white list. 

The server owner would have to know ahead of time what requests they want to allow, then any objects that users bring in would have to make sure they run as user and not as host. Which is probably a good idea anyway.

**Comment by Frooxius** [comment]
Added in 0.8.17.7284, hope this helps!
