### ISSUE TITLE
Slider/Child Objects Issue with SetGlobalPosition after Introduction of Anchor Code

### ISSUE THREAD

**Issue by TehTurk** [Frooxius/NeosPublic#319]
https://streamable.com/8xdkk Was requested of you originally to make a video for this and so you could see it in action. I've been busy and hadn't had the chance, and with the new anchor update wondered if it fixed itself but it had not. There are some issues with child's adhearing to the parent slider in this case. This bug only occurred after the introduction of the anchor code.

**Comment by Frooxius** [comment]
Thanks for the report! But it seems that the streamable link doesn't work, it just shows some generic streamable video. Can you check if it's correct please?

**Comment by TehTurk** [comment]
Did a check on the fix after the update! Apparently now the parents are adhering to their children? @_@ Sorry for giving you more work Froox https://streamable.com/xgr7p

**Comment by Frooxius** [comment]
Hello. Sorry, but I still don't quite understand what the bug is even after watching the video. What o you mean by "parents adhering to their children"? What kind of result are you expecting?

If you're messing with the avatar creator, it might not work correctly with whatever you're trying to do with it, it's not designed to be interoperable as it does its own positioning of the references.

**Comment by TehTurk** [comment]
Ah sorry! On that Version when I was showing with the streamable, the Children of the slider/avatar creator reference object were affecting the position of the parent, as you can see the reference flying out into the sky. Typically for a Slider all children underneath are supposed to not affect it correct? The results of the bug changed between some of the anchor bug fixes/updates, and I checked/changed on each update because I've been meaning to make a tut video for the tool because I've been busy, and the AvatarCreator uses an anchor system of sorts. I I'm not touching anything particular on the Avatar Creator Component itself, but the objects underneath it. The objects are sliders, and aren't behaving as intended, sure by Grabbable means yes, but if I do a setglobalposition through logix, it ends up ignoring it, while some others do listen to the command. Also, I did have symmetry off to prevent any breaking.

**Comment by Frooxius** [comment]
I'm sorry, but I'm still having trouble understanding what exactly is the problem. Is this related to the sliders in general? Or do you specifically want to modify parts of the avatar creator somehow and it's not doing what you expect? Which exact object are you trying to affect and which parent is it affecting instead?

If it's specifically the avatar creator though, then it's likely that whatever you're doing is just not compatible with how the avatar creator functions, it's not really designed to be messed with.

**Comment by TehTurk** [comment]
I understand that and have heeded your words when trying to make my tool, it's not like I didn't hear it the first couple times you told me prior, so it's not like I'm not listening ^^; I've been working with what I'm able to mess with. 

The issue is that the slider object behavior (For Example Right Hand/Left Hand) underneath the Avatar Creator wasn't/isn't working correctly as intended for a Slider object to behave. When I looked at the avatar creator component when making the tool originally, the references within it were Anchors(Using the objects/children underneath the Avatar Creator in the inspector for Reference), or at least the first anchors you had made before recent additions for Character Anchors and World Anchors. At first the issue was it behaved originally in the first video, then as more anchor code/updates occurred/introduced , the children underneath the slider objects affected the parents position (Video 2), but with most recent changes to Anchor updates, the behavior changed again, the photo showing the aftermath after attempting to use a setglobalpos to affect its position. While nothing funky is currently happening with it, the object itself should be positionable through logix, which I'm doing with the tool by setglobalposition and setglobalrotation.

The behavior of the tool works, before any of the anchor updates. I've shown people how it works, and have had others use/nab it for convenience.

**Comment by TehTurk** [comment]
![20191007070905_1](https://user-images.githubusercontent.com/26357446/66310732-ef7d6d80-e8da-11e9-8225-6476070aa014.jpg)

So just trying to show, made a basic Object with Slider Component, and the object does not respond to setlocal/global positions through logix. This is issue/problem I was having. Cube is supposed to zip to a location on my hand but does not.

**Comment by Frooxius** [comment]
Can you show me what the component looks like with the Slider on when you try to position it? Does this happen when you're holding the slider object or when it's not held at all?

I've looked into the avatar creator, but I can't really find anything there, but I'm not certain about the specifics of what you're doing with it. It has more complicated setup, because there's also a mirror transform on it.

Slider and AvatarCreator don't use the anchor code at all, so I'm certain that has nothing to do with it, but I did make some changes to both recently. Just need to distill what exactly is the root issue. Thanks for your patience!

**Comment by TehTurk** [comment]
Sure will do! This happens when your not interacting/holding the slider object. It works as intended when grabbing/holding. When your using Logix to define its position, the issue occurs.  

Ah sorry! I thought the reference objects for the Left/Right Hand/Foot had some sort of weird dependency on the avatar creator since you originally said it was just straight code. Sorry if my explanation was ever bad or I was confusing! I only was mentioning contextually because of me testing the tool. I don't think the mirror transform is conflicting as I've tried it without symmetry as well. So I assure you it's nothing with the Avatar Creator, just the Slider Component in general not behaving as intended.

The behavior has changed so my assumptions also have changed with it likewise ^^; I'll try to keep my words shorter so I don't blabber/explain too much. I'll start doing something like this in the future to keep it concise and on point. 
Issue:
Assumption:
Proof/Reference Material:

**Comment by TehTurk** [comment]
Sorry for late update! But made sure this time to get enough Visual Reference so you realize what's occuring. ![20191020153118_1](https://user-images.githubusercontent.com/26357446/67165157-bf5cb280-f34f-11e9-86b1-3243526b3fff.jpg)
![20191020153129_1](https://user-images.githubusercontent.com/26357446/67165159-c1267600-f34f-11e9-96aa-298ec039264b.jpg)
So here are the pictures of the components/objects. Since then you've changed Slider objects to be driven.(Idk why, but I don't want to assume things) But both LeftHand/Right objects still react to SetGlobalPositions(I checked manually). Don't know if this is intended, or if drives allow for input while active, and not locking the transforms/rotations/scale. 

![20191020153352_1](https://user-images.githubusercontent.com/26357446/67165162-c2f03980-f34f-11e9-9b77-9724d85f9dab.jpg)
This is the result of my auto rigging tool(Which basically just Sets the Position, And Rotation Globally, for each Avatar Creator Child Reference(As in the Slots themselves)), the hands (Import Objects) are not staying in position where the parent is, (which is a slider). The feet seem to be unaffected by this as my guess is just due to the position of the pelvis, and how they are tied to the head. While I could have used a basic cube or something else to show this, I figured this would be easiest, to show since the reference orbs get very off position, and you can visually see what is occuring.
![20191020153811_1](https://user-images.githubusercontent.com/26357446/67165163-c4b9fd00-f34f-11e9-96ab-8aa25392ee93.jpg)
![20191020153820_1](https://user-images.githubusercontent.com/26357446/67165164-c683c080-f34f-11e9-9f8a-08e201d0a796.jpg)
![20191020153832_1](https://user-images.githubusercontent.com/26357446/67165167-c8e61a80-f34f-11e9-8ea4-a8b8e0fff962.jpg)
As you can see, the reference orb and import.obj(or the children in what I was saying earlier) aren't sticking to the slider, breaking the parent/child position relationship. Hence the whole reason I made this post in the first place xD.

**Comment by TehTurk** [comment]
If anything is confusing or unclear please let me know! I tried to be clear-cut as possible in explaining the issue.

**Comment by TehTurk** [comment]
Hi! So I double checked like everything and I'm going to close this issue. It seems me making an example to show helped me realize what was wrong( I hadn't had any time/patience/focus to sit down and troubleshoot it till now). I had strings from way back labeled as RightController / LeftController and it was grabbing the controller points instead of LeftHand/RightHand xD. Sorry for and unneeded headache or confusion I may have caused.
