### ISSUE TITLE
[New Tool] Line Creator

### ISSUE THREAD

**Issue by sirkitree** [Frooxius/NeosPublic#323]
Would like either a new tool or modifications made to the existing Measurement tooltip. I love how the measure tooltip will allow me to 'shoot' two different objects and it will connect them with a line.

I'd like to be able to have an option to 
1. not add in the measurement label
1. change the color of the line
1. have the point appear in the middle of the targeted object (point position [0,0,0])

I can see a way to change the material, but having the color selector would be convenient for this tool.

I cannot see a way to disallow the measurement label, or change the targeting so that the point's position moves to the center vs the exact spot that the laser is intersecting.

**Comment by ProbablePrime** [comment]
I can build this for you

**Comment by sirkitree** [comment]
Thanks @ProbablePrime! Happy to send you some NCR for this :)

**Comment by ProbablePrime** [comment]
Got some basics working today, maths is off. More tommorrow!

**Comment by ProbablePrime** [comment]
The instability we've had recently made me apprehensive to do this but I should be able to get to it this week, In the future a request in the Discord might better suit asks like this. I'm not sure if you made one. That way we wouldn't need to track it within an issue tracker.

**Comment by sirkitree** [comment]
I had and it became buried / didn't receive attention. I thought perhaps this was more of a Neos core thing rather than community, but we should allow for community type requests to be tracked and surfaced here as well IMHO.

**Comment by ProbablePrime** [comment]
You can find this in my public folder under tools, let me know what you think.

**Comment by sirkitree** [comment]
Very nice! Saw your video and this is looking great!

The adjustment of the radius of the line is a nice touch. Dropping a material orb onto the control panel is also a really nice interaction, love that. And going to the center of the selected geometry was definitely something the meter tool is missing, so thank you!

I noticed you said it doesn't stretch when you move the parents. This would be useful as I find myself moving the parent objects and the meter tool does this currently. 

Also, how do I access your public folder? I'm under the impression you have to send a folder to someone or it lives in a particular world that can then be added to my inventory. I don't have a link currently so just wondering if this is out there in a world somewhere or if there is a different means by which I can add it.

Thanks for your work on this! If you let me know how much time you've spent on it, I'll be glad to send you some NCR!

**Comment by ProbablePrime** [comment]
Public folder is available in the Box and build a yeen. i want to place it in more places to make it easier to obtain.

Working on Stretching Support.

Probably 4 hours total to make this :)

**Comment by ProbablePrime** [comment]
Sent it via Messages to you along with my public folder.

**Comment by ProbablePrime** [comment]
We should be able to close this now.
