### ISSUE TITLE
Reusable Assets

### ISSUE THREAD

**Issue by sirkitree** [Frooxius/NeosPublic#324]
I'd like a way to create an asset, place it into multiple worlds, and when one instance is updated, all instances update.

This would be most useful in a situation where you have something like a menu system that is included into multiple worlds and allows you to navigate between them (for instance).

**Comment by Frooxius** [comment]
This is definitely going to be useful. It's planned to be handled by the Prefab system. I'm closing this issue, we have a topic for that one already: https://github.com/Frooxius/NeosPublic/issues/83
