### ISSUE TITLE
Camera Roll Adjustment

### ISSUE THREAD

**Issue by Medravr** [Frooxius/NeosPublic#327]
If at all possible, adding to the camera options: first person camera roll(or rotation around the z-axis) would be much appreciated. This could fix issues when adjusting the headset is not enough to adjust the orientation of the camera.

**Comment by shiftyscales** [comment]
I know that Rezillo had similar issue before with his old Vive HMD. Wearing it properly, his head angle would be titled slightly- likely either due to miscalibration in the tracking, or hardware fault in the HMD itself.

**Comment by Medravr** [comment]
Thanks. This would be useful for more camera control altogether such as a "Dutch Angle".

**Comment by Frooxius** [comment]
This has been added in the last build. Thanks for the suggestion!
