### ISSUE TITLE
Public Folder Issues

### ISSUE THREAD

**Issue by ProbablePrime** [Frooxius/NeosPublic#328]
I have a lot of public folders in my possession.

Often when opening a public folder or saving a public folder from a world where it has been placed to be saved, the public folder will not function correctly.

Its usually blank instead.

![image](https://user-images.githubusercontent.com/8791132/67315872-4d55ac00-f4bc-11e9-8308-468178c0c860.png)

Are we doing something wrong or is there an issue here?

**Comment by Frooxius** [comment]
How old are they? There was an issue where the items in the folder wouldn't be properly marked as public. It has been fixed, but the owners of the folder need to recreate a link to it to re-run the marking process.

**Comment by ProbablePrime** [comment]
Ahh i see, I'll re-run the process and update the folder location and see if that helps.

Thank you

**Comment by Frooxius** [comment]
No problem! Let me know if that solves the issue. It might be something else.

**Comment by sirkitree** [comment]
This seems to have worked. Do you want to close this issue or leave it open, since this is technically a work around?

**Comment by Frooxius** [comment]
Let's close this. This is workaround only for old shared folders when the process was broken. It should work correctly for all new ones.

**Comment by ProbablePrime** [comment]
I feel this should be re-opened i'm having issues but I think it might be intentional or by design.

Scenario: 
1. Select Neos Essentials in your inventory
1. Use the envelope to spawn a copy of Neos Essentials
1. Spawn it in the world
1. Save it
1. Newly Saved Folder is blank

Try the same for other people's public folders too.

**Comment by shiftyscales** [comment]
As far as I know this is an intentional design decision, @ProbablePrime. The idea being that only the creator of the folder can distribute it. E.g. as you do with your folder in your Build-a-Yeen world.

This does however raise an interesting idea for the UI/UX overhaul though. It would be nice to be able to set permissions on shared folders. E.g. who can access them, if its public/private, if the folder is read-only or read-write, etc.

**Comment by ProbablePrime** [comment]
That was what I guessed too, @Frooxius can confirm :)

As for your idea, that might not be included in the UI Overhaul. Its important that we don't raise our expectations of the UI update to include everything we can think of that touches UI. One of the benefits of a UI overhaul is make touching UI later easier, containing the scope of the UI update is something I think a lot about.

**Comment by shiftyscales** [comment]
Yeah, I agree it's out of scope, but that's why I also posted it here instead of on the UI/UX issue. Just a passing thought I had prior while dealing with shared folders that I was reminded of when I saw your post.

**Comment by ProbablePrime** [comment]
This was a bug, it was fixed recently, thanks team!
