### ISSUE TITLE
DestroyOnUserLeave Issues

### ISSUE THREAD

**Issue by ProbablePrime** [Frooxius/NeosPublic#330]
Is this component working ok? I couldn't get it to work.

![20191105004427_1](https://user-images.githubusercontent.com/8791132/68197074-72432800-ff6e-11e9-8dd5-05d015437030.jpg)

In this picture we write the user who pushes a button to the "TargetUser" ref of the DestroyOnUserLeave component. The component is added to the cube that the button pictured is also parented to so:
- Cube with DestroyOnUserLeave
  - Button with username of pusher

When Bitman leaves the Cube does not remove itself, are their nuances to how this component works?

I can send you the cube in game too, just let me know. 

We unfourtunately had multiple cubes in the world and even though the "Turk" cube is in sight, the logix and inspector refer to the "bitman" cube. I apologize for the confusing screenshot.

**Comment by Frooxius** [comment]
Looks like there's a bug in this component that doesn't check the user correctly because they just left. I'll fix it in the next build, thanks!

**Comment by ProbablePrime** [comment]
Thanks!
