### ISSUE TITLE
Bake Children

### ISSUE THREAD

**Issue by sirkitree** [Frooxius/NeosPublic#331]
That's a funny title... LOL

## Motivation
Sometimes it's difficult to target specifically what you want to bake with the Glue tool.

## Solution/Request
The idea is that it would be great to have a button on an object (next to Reset Position/Rotation, etc) that would allow you to bake whatever is underneath it.

This would allow you to create a parent object, drag in and group all the meshes specifically that you want to bake together, select the parent in the inspector, and push a button to bake whatever is within it. Highly targeted and I've thought this would be convenient more than a few times.

**Comment by Frooxius** [comment]
Still better title than destroying all the children! :D

This is actually already supported with the Glue tool in combination with the inspector. Simply grab the root of what you want to bake in the inspector with the glue tool and and press secondary, which will trigger the baking process.

**Comment by shiftyscales** [comment]
Beat me to it, Froox. Was about to send:

There is already support for this in the inspector. You can create an empty parent object, drag the meshes into it with the grip button on the inspector window, and then use the grip button on the parent to select the reference to it/use the glue tip to bake them together, @sirkitree.

**Comment by sirkitree** [comment]
![image](https://user-images.githubusercontent.com/28543/68240465-d3481b80-ffc1-11e9-8965-826cef0cba8d.png)

Holy shit
