### ISSUE TITLE
Locomotion option: teleport hotspots

### ISSUE THREAD

**Issue by sirkitree** [Frooxius/NeosPublic#332]
## Motivation
One of the typical locomotion methods you see in many VR applications is the ability to teleport, but only to certain hotspots. This is a form of locomotion that allows the creator to control where intended places of interaction should be for their users, and it's much easier for new users to a system to understand.

## Solution
Provide a means for content creators to define teleport hotspots in their worlds, and for a locomotion option that restricts visitors to teleport to these hotspots only.

**Comment by Frooxius** [comment]
This could definitely be useful! I'm sort of thinking about redesigning the teleport locomotion a bit. Perhaps instead of it being a separate module, combining it with physical locomotion as a mode.

How often would this be used? Most people right now seem to be using walk/run.

**Comment by sirkitree** [comment]
Most people who use this are not being newly introduced to Neos. However, in some of our application development, we're targeting users who have never used VR in their lives.

I've seen some studies that posit that it's much easier for new users to understand and use teleporting to a hotspot to avoid confusion with having to learn  more complex forms of locomotion, which is ideal when it's intended to be a short experience with a finite set of tasks for a user to perform.

So while this may not be useful for the typical Neos user, it is (I think) important for new users.

That being said, we can replicate this fairly easily with current controls, by disabling all locomotion modules, and using logix/button hotspots for users to click and be teleported to a location. So we can get by for now, but having the curved line such as with the typical teleportation locomotion, would be icing on the cake. So, not urgent, but if it's easy to implement, would be greatly appreciated.

**Comment by sirkitree** [comment]
There are decent ways to do this with community driven solutions and I see no further need to incorporate this into the Core system itself. I'm going to close this request.
