### ISSUE TITLE
Add "Description" to ValueField and ReferenceField.

### ISSUE THREAD

**Issue by ProbablePrime** [Frooxius/NeosPublic#337]
The data components have began to be used by a whole host of people to manage complex multi-logix setups, this is an idea I believe i helped to proliferate around Neos and I love it.

Adding a description text field to these components would allow these values to have more meaning within the inspector and logix(by pulling out their interface and a display node to description)

**Comment by Frooxius** [comment]
Sorry but this is out of scope of those components and would add unintended overhead. This will be responsibility of the LogiX variable system, or you can use the name of the object they're on.

**Comment by ProbablePrime** [comment]
No worries, Froox I forgot you were going to add something global variable like in the future. Thanks!
