### ISSUE TITLE
Feature Request: HTC Vive Hand Tracking SDK Implementation/HMD camera hand tracking, LeapMotion/HandTracking Improvements

### ISSUE THREAD

**Issue by InsaneGrox** [Frooxius/NeosPublic#339]
Before this I wouldn't say it would be worth adding due to tracking quality, but the HTC cosmos has changed the equation some by having better cameras and being more capable of hand tracking than the vive pro was, both the cosmos and pro use the same SDK for hand tracking, however the cosmos has manged to show much better tracking quality according to this video https://www.youtube.com/watch?v=8Hfp3ujuih8 and it seems to be improving over time, if possible I'd love to see this be expanded to all forms of hand tracking built into headsets, including the quest's hand tracking using it's respective SDK as an eventuality.

https://developer.vive.com/resources/knowledgebase/vive-hand-tracking-sdk/

EDIT: Editing this issue to add some extra ideas, I'd suggest making the UI somewhat hand friendly, and allowing for a virtual joystick to be used in-game for locomotion, somewhat simular to this concept I came up with https://cdn.discordapp.com/attachments/477711742001086505/650243389085974549/NeosLeapTest.mp4 , possibly utilizing hand  gestures for primary and secondary tool abilities while tools are equipped, and more.

**Comment by Frooxius** [comment]
I could add it, but I'm not sure how much of a priority would that be. Currently we don't support Vive Cosmos and not that many people have it in the first place.

Neos already has a generic finger tracking interface used for all the controllers and Leap Motion, so this wouldn't help with Quest tracking (I do plan on adding that if that's good quality). It just needs a code that takes the finger data from the SDK and translates it into Neos ones.

**Comment by MR-Alex42** [comment]
The Oculus Hand Tracking SDK was published on December 20th, 2019. A quick analysis showed that it showed provide all required data for the Neos generic finger tracking interface.

**Comment by Frooxius** [comment]
I'll get the new SDK and have a look! Do you happen to know if this works only natively on Quest or also with Oculus Link?

**Comment by Casuallynoted** [comment]
> 
> 
> I'll get the new SDK and have a look! Do you happen to know if this works only natively on Quest or also with Oculus Link?

For now, just on Quest- but Oculus has said they're looking into a release of hand tracking for PC headsets like Rift S and Quest with Link!

**Comment by mralext20** [comment]
Hello, the release as of 07/30/2020 has support for Valve index added, and previous iterations have also added support for `Vive, VIVE Pro, Vive Pro Eye, VIVE Cosmos, VIVE Cosmos XR, VIVE Focus Plus, VIVE Focus and Valve Index`[2]

this list seems like the list of all steamVR native headsets, so thats pretty cool

[1] https://developer.vive.com/resources/vive-sense/sdk/vive-hand-tracking-sdk/093/
[2] https://developer.vive.com/resources/vive-sense/sdk/vive-hand-tracking-sdk/

**Comment by RileyGuy** [comment]
While *definitely* not a replacement for a leap motion, it even works on an OG vive to a usable degree.

**Comment by Hayden-da-Serg** [comment]
I would also love to see this, though as mentioned here; https://discordapp.com/channels/402159838827905024/731903736028332083/749690831635742780 I'd prefer if there was an in-game toggle for it, as it's cool to have every now and then, but if it's constantly on I could see some issues arising in the future, since at least on the Original Vive, I had some major stability issues in testing
It'd also be quite annoying to have to restart Neos to turn it on for like 5 minutes or so just to turn it off again.

**Comment by InsaneGrox** [comment]
https://www.youtube.com/watch?v=VT6f1Qalye4
https://www.youtube.com/watch?v=11hVfSveqns
bumping with some stuff from the discord server, I think the SDK is ready to be implemented fully (tracking seems to be stable and at the very least decent)

**Comment by Frooxius** [comment]
Added support in 2020.9.5.1190! It's off by default for now, please give it a test and see how it works.
