### ISSUE TITLE
Audio streaming

### ISSUE THREAD

**Issue by sirkitree** [Frooxius/NeosPublic#34]
When hanging out with MR-Alex yesterday, we noticed that video files have a streaming option, but audio files do not. Is this something that could be added in the future? I assume the option allows it to play as it downloads for the user vs having to download the full file all at once before playing, but I'm not sure. Just thought I'd log it since Alex brought it up.

**Comment by Frooxius** [comment]
You can now use the video player for streaming audio as well, so that should cover this scenario.
