### ISSUE TITLE
impulse demultiplexer is hard to pack

### ISSUE THREAD

**Issue by ProbablePrime** [Frooxius/NeosPublic#341]
given the following, 
![20191203020452_1](https://user-images.githubusercontent.com/8791132/70041060-5634a580-1571-11ea-905c-f1c7aa6374b1.jpg)

each pulse node needs to be packed before the de multiplexer will pack, regardless of traversal mode.

**Comment by Frooxius** [comment]
Fixed in 0.8.18.13916 thanks!
