### ISSUE TITLE
Launch Neos in windowed mode

### ISSUE THREAD

**Issue by sirkitree** [Frooxius/NeosPublic#343]
It would be useful to be able to launch Neos in windows mode (vs fullscreen which is default through steam) utilizeing a command line argument such as -Windowed

This would launch Neos without fullscreen and allow users looking at their desktop through other applications such as Steam Desktop, Oculus Desktop, OVRDrop, etc to be able to see other windows at the same time and switch between them.

**Comment by Frooxius** [comment]
Unity originally had dialog for this, but they removed it, so we have to make our own solution. Not sure when I get to it, probably when I work on the desktop mode: https://github.com/Frooxius/NeosPublic/issues/151

Right now you can press Alt+Enter to toggle between windowed and fullscreen though.

**Comment by Frooxius** [comment]
Actually since you're asking for command line arguments, Unity already supports that, see here: https://docs.unity3d.com/Manual/CommandLineArguments.html

You should be able to use `-scree-fullscreen 0`

**Comment by sirkitree** [comment]
Ah, I didn't realize you could use Unity command line arguments! Thank you. Tested and works!

**Comment by sirkitree** [comment]
Tried adding this info to the wiki but don't seem to have permission, thinking a new section on http://wiki.neosvr.com/subdom/wiki/index.php?title=Command_Line_Arguments which just links over to https://docs.unity3d.com/Manual/CommandLineArguments.html to say that these are also available would be useful.

**Comment by shiftyscales** [comment]
I agree. I've added the link in a [new subsection on that page](http://wiki.neosvr.com/subdom/wiki/index.php?title=Command_Line_Arguments#Unity_Standalone_Player_command_line_arguments), as well as a few of the command commands one will need. E.g. screen mode, and resolutions.

Were you signed in to your Neos account when you tried to make the edits? You can sign in via the login button at the top right corner of any page on the wiki.

**Comment by sirkitree** [comment]
Yup, signed in, but can't even create a discussion for some reason.
