### ISSUE TITLE
Paste functionality on keyboard

### ISSUE THREAD

**Issue by sirkitree** [Frooxius/NeosPublic#346]
For part of an application the user needs to input a token. This token is long and hard to remember. Currently recommending the user paste using the paste button in the Settings UI, 
![20191216154833_1](https://user-images.githubusercontent.com/28543/70952732-fbdd1f80-201b-11ea-8b49-92ca18d0e69f.jpg)

but it would be nice if I could create a button for this to place next to the field for convenience.
![issue-paste](https://user-images.githubusercontent.com/28543/70952528-575add80-201b-11ea-8fba-37d84898e293.jpg)

Is there a logix node to allow me to hit the paste function, or a corresponding component I can trigger?

**Comment by sirkitree** [comment]
Anomalous brought up an interesting point that this could be a cause for concern security-wise. I agree as it's potential for abuse would be much greater. He also suggested we perhaps put a confirmation dialog before, like we do with the Get and Post nodes.

**Comment by Frooxius** [comment]
Yes, this is definitely something that could be abused to read the clipboard's contents, so it needs to be approached carefully. 

What about putting the paste button on the virtual keyboard itself? Coffee was working on that in one of the branches, se we could see about pushing that out.

**Comment by sirkitree** [comment]
> What about putting the paste button on the virtual keyboard itself?

Ah, yes. That would be much more convenient.

**Comment by shiftyscales** [comment]
Hey @sirkitree- can this issue be closed? The agreed solution no longer matches the initial issue/request.

**Comment by TehTurk** [comment]
You could but some of them staying open can kinda keep them in mind and context as UIX is being made, ultimately it's for Froox's build context and to organize some ideas. I'm sure the input Keyboard will be touched up, but a paste Still hasn't been added. These being open also keeps the discussion in mind too. I know you've been cleaning up some of the issues but do try to keep it in mind.

**Comment by sirkitree** [comment]
The paste function on the keyboard has not yet been implemented, afaik. We could change the title to reflect the solution though.

**Comment by shiftyscales** [comment]
This was added in [2020.3.9.689](https://discordapp.com/channels/402159838827905024/469131434628612116/686537397261041762).

Thanks @TehTurk for notifying me this issue was still open.
