### ISSUE TITLE
Text

### ISSUE THREAD

**Issue by sirkitree** [Frooxius/NeosPublic#348]
How do I use the `_meshLeft` and `_meshRight` properties here?

I would expect that these would allow me to place a mesh before and after the main `_mesh` and I'm hoping to be able to create end pieces (triangles) to give my text fields a stretched hexagon shape.

I've tried dragging in objects, mesh components, other mesh references, nothing seems to work. Help?
![20191220205711_1](https://user-images.githubusercontent.com/28543/71303306-d9c10580-236b-11ea-9cbc-82d0b071fc85.jpg)

**Comment by Frooxius** [comment]
You don't, they are internal properties managed by the component. Generally anything that starts with underscore is internal and managed by the component and shouldn't be touched or touched at risk of breaking the component or causing strange behaviors.

**Comment by sirkitree** [comment]
Ok, thanks
