### ISSUE TITLE
Creating TouchValueOption with type of FrooxEngine.User crashes the game

### ISSUE THREAD

**Issue by ProbablePrime** [Frooxius/NeosPublic#349]
Similar to value field with FrooxEngine.User.

The moment i hit create on this i knew I would crash but still would be good to add guards for other users.

Thanks!

**Comment by TehTurk** [comment]
Likewise. Didn't realize when I made it, but also did this with valueuseroverride<User>. Because you really can't *create* users or at least the type, would be neat if we had some sort of dummy user, or bot user created on any type of interaction like this as a failsafe?

**Comment by Frooxius** [comment]
Thanks, I'll have a look! It's probably uncaught exception of trying to make an invalid type somewhere within t hat. It might tricky though as there are more complex validation rules.

@TehTurk I'm not sure I understand. What kind of failsafe do you mean? There's ReferenceUserOverride which works with Users.

The main problem here is that ValueUserOverride is specifically for value types. You're not creating user, but you're making a type that references them.

**Comment by TehTurk** [comment]
Ah okay! Didn't realize user types and value types would be that vastly different. When I posted the comment I thought users were an inherent type like slot or anything else.

What I originally thought and meant, was the ability to generate dummy users, (Since we can only get them from people when signed in) for testing situations or otherwise for NPCs and the like. And have that behavior be a failsafe. (But that wouldn't make sense or apply correctly type wise)

**Comment by Frooxius** [comment]
Users are sync elements, similar to Slot so they can be referenced by the reference variants of the components. ReferenceUserOverride instead of ValueUserOverride.

Generating dummy users would be covered by this: https://github.com/Frooxius/NeosPublic/issues/239

**Comment by Frooxius** [comment]
Oh also closing this issue, since there is now a protection against using unsupported generic type for this component.

**Comment by shiftyscales** [comment]
A similar issue has come up, discovered by Elektrospy. He created a `ValueMultiDrive` with a `FrooxEngine.Mesh` type, and it locked up Neos. I've replicated the issue in the log below.
[SHIFTY-PC 1_25_2020_4_06_30_PM.log](https://github.com/Frooxius/NeosPublic/files/4113045/SHIFTY-PC.1_25_2020_4_06_30_PM.log)

**Comment by TehTurk** [comment]
This is due to the Mesh not being a Value Type I'm guessing. Froox did add some protection against this but it might be due to being a different component, so it might have different depends in the code.

**Comment by Frooxius** [comment]
I'll add a type check for this component too, thanks!
