### ISSUE TITLE
Snap turning

### ISSUE THREAD

**Issue by sirkitree** [Frooxius/NeosPublic#35]
I've seen a couple of requests now for snap turning. This would ideally be a turn of the user at about 45% or less when the right or left button of the thumbpad is pressed.

**Comment by Frooxius** [comment]
Snap Turning is already implemented - hold the grip button and turn the joystick left or right. It's a little bit clumsy though (I've added it this way only as quick hack), I've created a general issue for improving the Rift integration here: https://github.com/Frooxius/NeosPublic/issues/14
