### ISSUE TITLE
Tooltip Multiplexer Issues

### ISSUE THREAD

**Issue by Kal47** [Frooxius/NeosPublic#354]
There are a few bugs I noticed with the tooltip multiplexer,
1. When a Dev tool is equipped selecting Open Inspector from the wrist menu does nothing. 
2. With the Logix tool double clicking anywhere will spawn the node. Normally if you double click in the node selection menu it will not  do this.
3. The TipReference on the Tooltip Multiplexer does not seam to work.

Let me know if you need any more information!

**Comment by shiftyscales** [comment]
These have been fixed for a while. Thanks for the initial report!
