### ISSUE TITLE
Automatic saving of snapshots/camera photos.

### ISSUE THREAD

**Issue by DanteTucker** [Frooxius/NeosPublic#357]
Edit: Aparently the camera located in the inventory already saves images automatically. Consider this a bug report that the finger pose camera does not.

I would like the option of automatic saving of snapshots to my computer. 
This would be accompanied by a settings option where you could specify which folder to save to.
The saved images filenames would be the timestamp of when they were taken.

**Comment by shiftyscales** [comment]
Screenshots that are taken by you are saved to your computer already and use the timestamp as their name too. By default they are saved to your "Pictures" folder inside of your Windows user folder. User -> Pictures -> Neos VR. If you run Neos through Steam- Steam will also save a copy of all screenshots you take.

Having a UI to specify the default directory could be useful however as an addition to the UI/UX redesign #299.

**Comment by DanteTucker** [comment]
Looks like that only works with the camera located in your inventory. Pictures taken by the "finger pose" camera are not saved. This explains why I didn't notice. I have not used that camera in months lol

**Comment by Frooxius** [comment]
This is odd, both InteractiveCamera and FingerPhotoGesture use the same code so there should be no difference in behavior. On my end the pictures taken with the finger pose are saved correctly.

Did you check if there's actual difference between the two methods? Are there any exceptions/errors in the log when you take a photo with the finger gesture?
