### ISSUE TITLE
DestroyRoot and LogiX Interface Cards / Refs

### ISSUE THREAD

**Issue by ProbablePrime** [Frooxius/NeosPublic#359]
DestroyRoot get's automatically applied to meshes with armatures. 

DestroyRoot is destroying such meshes when i delete logix interfaces or ref cards attached to armature components. For example pull a slot card for an armature bone and delete it, Attach a component to an armature bone pull its logix card and delete it. 

Could destroy root not trigger when logix interfaces or nodes within the hierarchy are deleted? 

This seems like new behaviour as it surprised me a lot.

**Comment by Frooxius** [comment]
The applying of DestroyRoot to meshes with armatures is normal, that's been done for a long time.

However it's odd that it's destroying it with logix interfaces. Where is the LogiX interface that you destroy located. Is it parented under the given object? Normally they shouldn't be part of the object at all.

Is the issue with Ref nodes happening in the latest build too? I recently did a fix for that. I will broaden it to all LogiX nodes.

**Comment by ProbablePrime** [comment]
Last night is when i saw the above issues, after patching to the latest updates.

Thanks!

**Comment by Frooxius** [comment]
Just to clarify, by LogiX interfaces do you mean the ones used to read/control properties of the slot/component? Are they parented under the object? Do you destroy them simply by grabbing and destroying?

I'm trying to replicate this, but I can't get it to happen on my end.

**Comment by ProbablePrime** [comment]
I mean general information and nodes that reference armature slots or components on those slots. They are not usually parented to these armature slots. I'll hop in and start recording some videos for you.

**Comment by Frooxius** [comment]
Ok thank you! I think that can help!

**Comment by ProbablePrime** [comment]
Video uploading, i forgot that packing logix nodes parents them to the packing root.

**Comment by ProbablePrime** [comment]
https://www.youtube.com/watch?v=XoybMGHHYDo wrong microphone was selected but you should be able to see it.

**Comment by Frooxius** [comment]
Thanks, I was able to replicate this! Fix coming!
