### ISSUE TITLE
[Bug/Feedback] Asset Optimization Wizard Issues

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#367]
- The `Ignore Nonpersistent Users` checkbox appears to be non-functional as user slots are being affected by the wizard regardless of its setting.
- Additionally- if a process root is not specified (as is the default/preferred option to affect the entire world) user avatars are broken by the `Cleanup Empty Slots` optimization. I tested a wide number of avatars including personal ones, and a random sampling of those in the Neos Essentials- and each has resulted in the avatar being broken, and sent to the origin.

- Since users are non-persistent by default, and not considered as a part of the world- perhaps they should be excluded from the optimization outright. This also applies to the `Cleanup Disabled Mesh Renderers` setting as some users will have disabled mesh renderers as a means of toggling clothing/accessories for their avatars.

- The `Deduplicate Materials` breaks the background material on inspector windows causing them to appear opaque with a visible checkerboard pattern in the background. This also affects the red X close button on the inspector- and possibly other places. (Will update if I discover more.)

- The `Set Max Texture Resolution` has a maximum value of 2047 a non-power of two value- and could also be bumped up to 4k optionally. (I am presently unsure how to verify if the texture resolution is being altered correctly. I noticed no immediately noticeable change regardless of the world I tried this setting in so far.) It would also be nice to have a dropdown to select various power of two resolution presets instead of manually entering the resolution.

- The title bar UI is still called "Light Sources" and the first line has "Scene Light Sources" in it.

Overall- this is a very welcome feature, and seems to work quite well, and as intended in most respects. Thanks.

**Comment by Frooxius** [comment]
Most of this is expected behavior. This is a pretty powerful tool, so you should be wary of what you apply it to. I strongly discourage applying most of these to the root, they are designed to be selective optimizations you apply to parts of hierarchy you know won't get messed up.

- Ignore Nonpersistent Users isn't utilized yet it's for some options I plan on adding. This is a special mode for scene asset cleanup, it doesn't mean that nonpersistent users don't get processed, but that they are ignored during search for external references.

- Users are part of the world just as everything else. There's no technical difference between them and rest of the scene.

- I fixed the max resolution and title thanks, it had max value swapped with the default

**Comment by shiftyscales** [comment]
I see. It is a powerful tool indeed. Given the term 'wizard' I figured it was at least in part intended as a user-friendly/automated way to optimize a given world.

With that in mind- I don't think it would be entirely out-of-scope to have an exclusion list by default to prevent users from accidental misuse due to a lack of understanding of its purpose/power.

A potential suggestion would be to require a user to specify the slot on which it runs prior to running it instead of defaulting to the root.

The root just happens to be the easiest/most thorough place an average user would want to optimize from as (unfortunately) not enough people prioritize organization of their world's assets into dedicated groupings the way the team has with the MTC.

Perhaps in the future some of this functionality could be rolled into an auto-optimizer sort of like how the asset cleanup already exists as a checkbox?

Either way- thank you for clarifying the functionality. This is a useful tool, and I hope we see more people making use of it. Perhaps it would be worth posting a devlog video demonstrating its uses/potential? Make it a regular part of the creative workflow when finalizing/cleaning up a world for publishing. (Or updating existing maps too.)

**Comment by Frooxius** [comment]
Yeah I can make it to just not do anything if you don't set any slot at all, you could still run it on Root if you really wanted to if you explicitly put it there.

A lot of the functionality is already in the auto-optimizer. Whenever you save world it deduplicates materials and static asset providers under Assets. If you're hosting on headless the deduplication is ran automatically during the asset cleanup.

**Comment by shiftyscales** [comment]
Ah. I see. That makes a lot more sense, then. How, and when do you envision this tool is best used? It sounds like a lot of the work is going to be done automatically for users which is a very nice thing.

**Comment by Frooxius** [comment]
It depends on what you're doing. I've added it because I needed to do those tasks myself for optimizing the MTC. It will be expanded in the future, to provide a lot more, but this is what it is now.

**Comment by shiftyscales** [comment]
Following these discussions, the tool was required to have the user specify a process root. Many of these optimizations are also ran when a world is saved/cleaned.
