### ISSUE TITLE
Keeps crashing during launch

### ISSUE THREAD

**Issue by DonoKun0** [Frooxius/NeosPublic#369]
Every time I launch NeosVR I get a flash of the logo, then a black screen for a few seconds before this window pops up:

https://imgur.com/a/q62xKo3

Then once it's done loading it crashes. In the headset the whole thing is black until it crashes and boots back to Oculus Home. 

I'm using an Oculus Rift S and launching it through my steam library, I have uninstalled and reinstalled twice so far, while clearing out the cache. The same thing still happens regardless.

Here are the logs:

[DESKTOP-GUG11FJ 1_17_2020_3_48_05_PM.log](https://github.com/Frooxius/NeosPublic/files/4079262/DESKTOP-GUG11FJ.1_17_2020_3_48_05_PM.log)
[Player-prev.log](https://github.com/Frooxius/NeosPublic/files/4079263/Player-prev.log)
[error.log](https://github.com/Frooxius/NeosPublic/files/4079264/error.log)
[Player.log](https://github.com/Frooxius/NeosPublic/files/4079265/Player.log)

**Comment by shiftyscales** [comment]
I will assume that other SteamVR titles are working without issue for you? A good troubleshooting step you can try would be running the game directly from the executable/without Steam to verify if Neos will launch properly at all.

If Neos runs successfully without Steam- you can try a couple of things to try and get it working with Steam. There are the Launch Neos VR in Steam VR Mode, and Play Neos with SteamVR runtime forced on" options that you can try.

You can also try setting `-SteamVR` as a [launch option](http://wiki.neosvr.com/subdom/wiki/index.php?title=Command_Line_Arguments) in Steam by right clicking on Neos VR -> Properties -> Set Launch Options.

Let me know if any of these things help, @DonoKun0. Sorry for the inconvenience. Thank you for posting your logs, and reporting here.

Pinging @Frooxius to have a look at those logs when he has the time. The logs abruptly end while trying to load the Metaverse Training Center introductory world.

**Comment by DonoKun0** [comment]
> I will assume that other SteamVR titles are working without issue for you? A good troubleshooting step you can try would be running the game directly from the executable/without Steam to verify if Neos will launch properly at all.
> 
> If Neos runs successfully without Steam- you can try a couple of things to try and get it working with Steam. There are the Launch Neos VR in Steam VR Mode, and Play Neos with SteamVR runtime forced on" options that you can try.
> 
> You can also try setting `-SteamVR` as a [launch option](http://wiki.neosvr.com/subdom/wiki/index.php?title=Command_Line_Arguments) in Steam by right clicking on Neos VR -> Properties -> Set Launch Options.
> 
> Let me know if any of these things help, @DonoKun0. Sorry for the inconvenience. Thank you for posting your logs, and reporting here.
> 
> Pinging @Frooxius to have a look at those logs when he has the time. The logs abruptly end while trying to load the Metaverse Training Center introductory world.

I ran the executable and the same thing happens, 

spashscreen flash on monitor > black screen > error > crash 
while in the headset it's completely black till it crashes. 

I also tried the 'Launch Neos VR in Steam VR Mode' and 'Play Neos with SteamVR runtime forced on' options and while it crashes in almost the same way, the splashscreen actually appears in both the headset and monitor, sadly that's the only thing that's different, now it's just splashscreen > error > crash. 

https://imgur.com/a/QUSisJk

**Comment by shiftyscales** [comment]
Hmm. Perhaps you might need to try uninstalling/reinstalling the Oculus software/drivers/runtime, etc? We have quite a few other users who have been using the Oculus Rift S without issue. The fact it's still crashing when running the executable directly is concerning.

It does suggest a potential driver issue. Again- sorry for the inconvenience.

**Comment by DonoKun0** [comment]
> Hmm. Perhaps you might need to try uninstalling/reinstalling the Oculus software/drivers/runtime, etc? We have quite a few other users who have been using the Oculus Rift S without issue. The fact it's still crashing when running the executable directly is concerning.
> 
> It does suggest a potential driver issue. Again- sorry for the inconvenience.

It's alright! I'll try looking into uninstalling/reinstalling drivers and see if it works, fingers crossed!

**Comment by Frooxius** [comment]
Hello!

I've taken a look at the log, it's crashing in the audio input library when it tries to connect to your microphone. Are you using any 3rd party software that might interfere there?

You could try running Neos with the legacy audio input system. It has higher latency and overhead, but could fix this issue.

To do so, create a file named "UseUnityAudioAPI" on the root of your C: drive and start Neos.

**Comment by DonoKun0** [comment]
> Hello!
> 
> I've taken a look at the log, it's crashing in the audio input library when it tries to connect to your microphone. Are you using any 3rd party software that might interfere there?
> 
> You could try running Neos with the legacy audio input system. It has higher latency and overhead, but could fix this issue.
> 
> To do so, create a file named "UseUnityAudioAPI" on the root of your C: drive and start Neos.

Not that i'm aware of, I was mainly using the rift s built in mic, but I also have another mic, I tried unplugging that and disabling the built in mic, switching which one was default, etc, and it crashed in the same way. 
By root you mean making the folder in ''Windows (C:)''?

**Comment by Frooxius** [comment]
Not in the Windows folder, but directly under the C: drive.

**Comment by DonoKun0** [comment]
> Not in the Windows folder, but directly under the C: drive.
![image](https://user-images.githubusercontent.com/60019524/72664329-84a7fc00-39ca-11ea-9d1e-3676a8646bdd.png)
In here right?
I ran it again with the file in there and it crashed.

I'll send some new logs just in case theirs anything new at all:
[DESKTOP-GUG11FJ 1_18_2020_8_12_46_AM.log](https://github.com/Frooxius/NeosPublic/files/4080722/DESKTOP-GUG11FJ.1_18_2020_8_12_46_AM.log)
[error.log](https://github.com/Frooxius/NeosPublic/files/4080723/error.log)
[Player.log](https://github.com/Frooxius/NeosPublic/files/4080724/Player.log)

**Comment by DonoKun0** [comment]
In here right?

![image](https://user-images.githubusercontent.com/60019524/72664409-8d4d0200-39cb-11ea-890a-f420b665e7a2.png)


I ran it again with the file in there and it crashed.

I'll send some new logs just in case there is anything new at all:
[DESKTOP-GUG11FJ 1_18_2020_8_12_46_AM.log](https://github.com/Frooxius/NeosPublic/files/4080728/DESKTOP-GUG11FJ.1_18_2020_8_12_46_AM.log)
[error.log](https://github.com/Frooxius/NeosPublic/files/4080729/error.log)
[Player.log](https://github.com/Frooxius/NeosPublic/files/4080730/Player.log)

**Comment by Frooxius** [comment]
Yes, but it needs to be a file, not a folder for it to take effect. You can do that by creating an empty .txt file there and removing the extension.

**Comment by DonoKun0** [comment]
> Yes, but it needs to be a file, not a folder for it to take effect. You can do that by creating an empty .txt file there and removing the extension.

That fixed it! Game is running :)
