### ISSUE TITLE
Bent Hand Laser

### ISSUE THREAD

**Issue by Vigilabo** [Frooxius/NeosPublic#371]
Hand laser becomes bent when unequiping a repositional tool that is in the process of being repositioned by the player. Once the tool is unequiped the laser is still movable until the grab button is released.

**Comment by shiftyscales** [comment]
Apparently I can't embed the video directly to GitHub- but I've reproduced this issue, and recorded a clip that can be found here: https://cdn.discordapp.com/attachments/439422161657135106/668184099013263360/2020-01-18_12-02-27.mp4

**Comment by Frooxius** [comment]
That's very helpful thank you! Fix coming in the next build

**Comment by Frooxius** [comment]
Should be fixed!
