### ISSUE TITLE
[Bug] Unable to modify or delete slots containing permission components

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#375]
Slots that contain a permission component are unable to be modified, or deleted from the scene, even after the component is removed from the slot.

This change is likely related to a previous issue regarding deleting roles from a world. Perhaps if an object has all permission components removed its protection can be removed as it would require component access/builder access to remove the components?

Footage of the issue can be found here: https://youtu.be/1XZcdG37Zfk

Fortunately- any objects affected by this/saved into a world can be removed from the world by making them non-persistent, and saving.

**Comment by Frooxius** [comment]
This is intentional, you're not supposed to remove these. It's a protection against corrupting the role system.
