### ISSUE TITLE
[Bug] World orb session splitting

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#377]
Following up from a report by Lewis earlier today- it's been observed that once a user generates a world orb, and creates a new session- it may be used by only one other user prior to diverging, and sending users into a new session for the same world.

Additionally- something about this setup caused Neos to crash for myself, Henry, peterthethinker, 
and Conduit. After I had created a world orb inside of 0utsider89's session, I started a new session set to 'Anyone'. Henry was next to join, and was added into my session.

Peter tried to join after, and was sent into his own session. Conduit, and Outsider joined Peter's session. Outsider then tried to close his session that we had all joined our respective sessions from, causing all to crash except for himself.

I've requested all involved to submit their logs to you directly, @Frooxius.

**Comment by Frooxius** [comment]
Forgot to close this one, this was fixed a few builds back.
