### ISSUE TITLE
[Feature/QoL] Height offset component

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#380]
As discussed in the #ideas channel on Discord and as an extension to already existing framework- a component can be made to allow a user to specify a height offset for use on avatars.

There are some considerations to be made for how this component could be implemented, and used by users. E.g. it could be used as a means to replace the existing seated mode setting.

- It can increase accessibility by bringing the floor up to a more reachable height.

- The height offset could be adjusted by the user's head position relative to the floor/their feet so that the floor remains accessible- even if they are standing well above it (a limitation of the existing seated mode).

- If the height offset were adjusted dynamically- what would be the best means to scale it? Linearly?

- Would the change in height offset be overly disorientating/motion sickness inducing? Or is it something that could be easy to adapt to?

**Comment by Frooxius** [comment]
This has been added in the latest build as "Avatar Tracking Offset". Thanks!
