### ISSUE TITLE
User Tagging issues

### ISSUE THREAD

**Issue by ProbablePrime** [Frooxius/NeosPublic#382]
I spoke to Froox about this one in game at the last Creator Jam.

The Locomotion Permission component allows you to require the a user has a tag on them before they can use a locomotion type. Or at least that's what the UI seems to suggest.

However all users receive the "User" tag automatically and after trying to change this a few times I've seen it randomly being set back to "User".

Additionally some tools such as the MaterialTip end up tagged as "User" when they are used.

Froox mentioned something about old grabbing code using this tag system and that this old grab code could be adjusted so this wasn't the case. This issue is to track that work

Additionally, some questions in this area too for discussion:
- Is the "RequireTag" item of the Locomotion permissions referring the tag of the User?
- As a world developer are we meant to be able to set Users to a tag that isn't "User"?

**Comment by Frooxius** [comment]
I've looked at the code, looks like nothing is using this tagging anymore, so I just removed it. Coming in the next build! Thanks!

**Comment by Frooxius** [comment]
Also the RequireTag is for the Slot that the locomotion module is on, not the user themselves.

**Comment by ProbablePrime** [comment]
Awesome!, what about my second question?

**Comment by Frooxius** [comment]
Oh sorry, I thought that was answered implicitly. Yes you can set the user to any other tag after I remove the automatic tagging as "User".

**Comment by ProbablePrime** [comment]
Its ok, its a monday :).

**Comment by ProbablePrime** [comment]
This is working great!
