### ISSUE TITLE
feature, Allow custom world preview images

### ISSUE THREAD

**Issue by RoxyBoxxy** [Frooxius/NeosPublic#386]
Insted of the world camrea users can use a custom image for it

**Comment by Frooxius** [comment]
Do you mean for the session preview or when submitting worlds? It's planned for the latter, but won't happen until the UI overhaul, as I need some UI to make it possible to set them up.

**Comment by RoxyBoxxy** [comment]
Oh okay cool, cant wait for the new UI ❤
