### ISSUE TITLE
[Bug] Leap Motion does not respect 'Leap Tracking Enabled' setting on initialization

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#389]
Steps to replicate:
- Launch Neos with a Leap Motion controller installed, and running

Result:
- Regardless of the value of the `Leap Tracking Enabled` setting, when the Leap Motion is first initialized on launch it will be active, and tracking until the settings UI is opened.

Expected outcome:
- On initialization, the Leap Motion controller's tracking will remain active, or inactive as dictated by the `Leap Tracking Enabled` setting

**Comment by Frooxius** [comment]
Fixed in 2020.2.9.629
