### ISSUE TITLE
[Bug] "Strip empty blendshapes" does not strip empty blendshapes

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#390]
`BlendShapeWeights` added to the `SkinnedMeshRenderer` component with the `Add` button are unable to be removed by the `Strip Empty Blendshapes` button on the component.

**Comment by Frooxius** [comment]
That's not what the button does. "Strip empty blendshapes" removes them from the mesh. The ones you see in the inspector are just the configuration for renderer. The Add button is more or an artifact, it needs proper UI for editing them.

**Comment by shiftyscales** [comment]
Got it. I had a feeling it might have been a placeholder for when that functionality is eventually implemented. Thanks.
