### ISSUE TITLE
[Bug/UI] "INJECTED AVATAR BUILDER" duplicates roles in session UI, and permissions

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#391]
Possibly to be made irrelevant by the UI update- but noting for posterity:
Steps to replicate:
- Remove the `User Spawner` slot from a world
- Respawn yourself

Result:
- The list of roles in the session menu, and on the permissions in the inspector will be duplicated
![2020-02-08 17 43 10](https://user-images.githubusercontent.com/54213390/74094784-9b0e1880-4a9b-11ea-890e-6fdaf61ee6ea.png)

**Comment by Frooxius** [comment]
I see! That's a good catch, that could be the reason for the duplication cases. I'll have a look, thanks!

**Comment by Frooxius** [comment]
Fixed in 2020.2.9.629
