### ISSUE TITLE
[Bug] ClearExisting on Install Locomotion Modules node deletes user root contents

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#392]
Rediscovered by Hayden#3180:
Steps to reproduce:
- Set up an `Install Locomotion Modules` Logix node with the `ClearExisting` property set to true

Outcome:
- The contents of the entire target user's root except for the installed locomotion module will be cleared, requiring them to respawn themselves with the emergency gesture.

Hayden has provided a recording of this effect in action, which can be viewed here: https://streamable.com/7md4y

**Comment by Frooxius** [comment]
Thanks! Fix coming in the next build

**Comment by Frooxius** [comment]
This has been fixed.
