### ISSUE TITLE
[Bug] Objects with PhotoMetadata displayed as favorite for home world URL

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#393]
Reported by Hayden#3180
Steps to reproduce:
- Create an object with a `PhotoMetadata` component (take a picture/or add it manually)
- Ensure the MetaData contains the `LocationURL` of your current favorited home world
- Save the object to your inventory

Results:
- The saved object is marked as a favorite (purple background)

Screenshots provided by Hayden depicting the issue:
![2020-02-10_15 28 05](https://user-images.githubusercontent.com/54213390/74197477-712c3180-4c14-11ea-9d22-20a66061c9c3.png)
![2020-02-10_15 27 42](https://user-images.githubusercontent.com/54213390/74197485-75f0e580-4c14-11ea-9e1a-55eb8c20ce8a.png)

A simplified example (empty object containing a `PhotoMetadata` component with only the `LocationURL` defined):
![2020-02-10 14 41 37](https://user-images.githubusercontent.com/54213390/74197628-aa64a180-4c14-11ea-8f96-96360b35271e.png)

**Comment by Frooxius** [comment]
This should be fixed now.
