### ISSUE TITLE
SteamVR skeletal input on WMR 

### ISSUE THREAD

**Issue by InsaneGrox** [Frooxius/NeosPublic#394]
The latest beta for WMR for SteamVR has experimental skeletal input support for Windows Mixed Reality controllers, however if I'm not mistaken this means Neos will have to do a few changes to the way WMR support is handled involving a bindings change & reverting the way offsets are handled to use skeletal input. 
![image](https://user-images.githubusercontent.com/54233743/74354270-19630700-4d89-11ea-97c9-9ad433587eea.png)

**Comment by Frooxius** [comment]
Have you tried using it yet to see how well it works? It's no problem enabling it for WMR controllers as it will use the same system as the rest, but if it's optional toggle now that makes things trickier, as Neos needs to somehow decide which version to initialize (the legacy or the Skeletal).

**Comment by shiftyscales** [comment]
Considering the system is marked as experimental, and is strictly opt-in by requiring a tweak to the settings file of the driver- I can see why that would make things tricky. It might be worth waiting until they officially implement it.

I don't presently own any software aside from Neos that utilizes skeletal input. If you have any suggestions for apps I can use to test skeletal input, I'll gladly do so.

**Comment by Frooxius** [comment]
You could try the Moondust demo from Valve to see if it works there or some of their other official demos. But yeah if I can't rely on this feature being on for all users it might be better to wait until it stabilizes. 

Unless there's a good easy way to detect if the skeletal input is available, but I'll have to poke around for that.

**Comment by shiftyscales** [comment]
Skeletal input does appear to be available. For the sake of comparison, I tried Pavlov out with the setting enabled:
https://cdn.discordapp.com/attachments/612065710465613863/677310366300110848/2020-02-12_16-24-12.mp4

And then again with it disabled:
https://cdn.discordapp.com/attachments/612065710465613863/677310459308671016/2020-02-12_16-27-48.mp4

**Comment by Frooxius** [comment]
This is supported now as of 2020.2.20.970!
