### ISSUE TITLE
[Bug] Objects not re-parenting under slots containing a SnapTarget

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#395]
Steps to replicate:
- Parent an object with a `Grabbable` component under a slot containing a `SnapTarget` component
- Grab the object and release it

Result:
- The object is parented under the root instead of re-parented under its original slot

This behavior occurs for the slot on which the `SnapTarget` is placed, as well as on any children beneath the slot on which it is placed. Slots on the same hierarchy as the `SnapTarget` as well as above it are unaffected, and will re-parent properly as expected.

**Comment by Frooxius** [comment]
This is expected behavior.  You need to use the Snapper component on the object in order for it to work with SnapTarget.

**Comment by Frooxius** [comment]
I've added a thing that allows reparenting deeper in the hierarchy in the latest build.
