### ISSUE TITLE
EmptyAvatarSlotHandler in UserSpawner appears to be unusable

### ISSUE THREAD

**Issue by ProbablePrime** [Frooxius/NeosPublic#397]
1. Open the userspawn slot or the slot with the user spawner on it
1. try to assign a slot to the empty avatar slot handler
1. Observe that avatar slots cannot be assigned to this field

Data type of the field is IEmptySlotAvatarHandler but this might be a wrapper around the actual field. 

Historically, I think in the moon landing i've assigned this to a slot but the moon landing was published a long time ago. 

![20200208184413_1](https://user-images.githubusercontent.com/8791132/74585869-7da6e600-4f96-11ea-85e9-6edb5902323c.jpg)
![20200208184434_1](https://user-images.githubusercontent.com/8791132/74585871-7f70a980-4f96-11ea-9aa9-e9f8291a4eab.jpg)

**Comment by Frooxius** [comment]
This field is a Delegate, it points to a function which is called to fill any empty slots on the avatar. Right now there's not a nice way to expose those in the inspector and there aren't really any functions other than the one used there that would provide the proper handling.

Why would you want to override/use this field? It's a fairly low level thing that you don't want to change in most cases.

**Comment by ProbablePrime** [comment]
Ok, thanks, I don't actually need it I just had a recollection of using it to do something in the moon landing map that made sense.

**Comment by Frooxius** [comment]
Ah no problem! I think you might be mixing it up with a different property, this one is not really designed to be usable just yet.
