### ISSUE TITLE
Performance and Audio issues on 2020.2.16

### ISSUE THREAD

**Issue by ProbablePrime** [Frooxius/NeosPublic#399]
2020.2.16.754

Having a lot of issues with this build and the previous one on 2.16.

1. My audio comes out Crackly regardless of microphone used, other users were talking about this.
1. Degrading performance - Hitches and stutters are regularly occuring whilst doing normal things in the world, FPS takes a nose dive and then recovers. Its similar in pattern to the Garbage Collector issues of early 2019. It gets worse until i restart Neos.

Logs have been sent to Froox :)

**Comment by ProbablePrime** [comment]
This is clearing up or at least didn't happen last night, I was just presenting and hanging out with users and not doing much intensive work so i will verify tonight once more and then close. Thanks!

**Comment by shiftyscales** [comment]
How are things working for you now, @ProbablePrime? Can this issue be closed?
