### ISSUE TITLE
Registration response looks like error

### ISSUE THREAD

**Issue by sirkitree** [Frooxius/NeosPublic#4]
![https___cloudx azurewebsites net_verify_u-sirkitree_0867e61f22adfa2b3c6e2e3166622011 - google chrome 2018-04-23 13 20 13](https://user-images.githubusercontent.com/28543/39148271-190b977e-46f9-11e8-83db-8588bf057968.png)

After registering from within Neos, I received an email. When I clicked the link, it took me to an XML document instead of an HTML document. This could be perceived as an error to someone unfamiliar with the difference.

**Comment by Frooxius** [comment]
I was lazy *cough* busy and just returned a piece of string from the API server. Now redirects to this!
http://neosvr.com/email_verified.html
