### ISSUE TITLE
Importing a model leaves an "Import" object in the inspector hierarchy

### ISSUE THREAD

**Issue by sirkitree** [Frooxius/NeosPublic#40]
Steps to reproduce:
1. open up an inspector window for the scene using the red developer tool tip and the context radial menu
1. note the hierarchy
1. use the import tool tip to open a file browser
1. browse to a model file on your hard drive with the file browser
1. grip to grab the model file you want to import (fbx)
1. place the resulting sphere where you want the model
1. click 'import here' from the sphere's radial menu 
1. go through the wizard to choose your options
1. once the model is imported, take a look at your inspector window again and note that on the same level as the "Model" object, there is also an empty "Import" object

It would be nice if these weren't left in the hierarchy. I manually delete them currently, but that's just because I'm probably a bit too anal retentive about my scene hierarchy.

I think this is a bug, but maybe there's a reason to keep these? In any case, it's really low priority.

Before import:
![20180428192258_1](https://user-images.githubusercontent.com/28543/39402389-4a0eaad4-4b1b-11e8-88f0-4bf7e23de32a.jpg)

Orb:
![20180428192313_1](https://user-images.githubusercontent.com/28543/39402390-5a04257c-4b1b-11e8-82ec-46271cac10f0.jpg)

Model and Import node:
![20180428192340_1](https://user-images.githubusercontent.com/28543/39402399-778a428e-4b1b-11e8-886c-6a2e28e1ae28.jpg)

**Comment by Frooxius** [comment]
Hmm this was just a quirk from me rewriting the old importer code during alpha version. Adjusted it a bit and made it use filenames for the root slot names now.

I don't like polluting the hierarchy with objects either :)
