### ISSUE TITLE
Option to disable empty tooltip visualization

### ISSUE THREAD

**Issue by Casuallynoted** [Frooxius/NeosPublic#401]
For immersion purposes, is there any chance we’ll see an option that disables the “you have no tooltip equipped” indicator at the end of the hand? To my knowledge there isn’t a feature like this at the moment but I might be wrong!

**Comment by shiftyscales** [comment]
Physical mode will hide your tooltips at all times except when aiming them at UI elements, @Casuallynoted.

**Comment by Casuallynoted** [comment]
> Physical mode will hide your tooltips at all times except when aiming them at UI elements, @Casuallynoted.

Ooh ok, this is good to know! In that case, one suggestion I’d make is including info about physical mode in the MTC so people know about it! :)

**Comment by shiftyscales** [comment]
Physical mode will be reworked slightly with the UI/UX overhaul. E.g. the scale lock of physical mode will be separated into its own setting. I imagine once the new UI is closer to completion, more work can resume on the MTC. There is still a lot that the team desires to do with the MTC yet including a more interactive tutorial.

Another suggested/proposed feature is contextual tooltips that can better explain what options are to users.

Can we consider this issue as resolved, @Casuallynoted? Any further suggestions, or questions?

**Comment by Casuallynoted** [comment]
I believe so!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
