### ISSUE TITLE
Weapons Equip component base on Grab Orb 

### ISSUE THREAD

**Issue by Jazzneo** [Frooxius/NeosPublic#402]
I think For Guns,sword need New component  base on Grab orb  location instead of the tool tip some people like use the joystick alot equip weapon fast. but the weapon dont fit right when look for the tool tip location. would be possible add feature or make new component base on the Grab Orb location?

**Comment by shiftyscales** [comment]
Frooxius has previously mentioned wanting to rework the grab, and equip system. He's also discussed implementing an official equippable system which may also cover this idea in its scope.

Until such a system is made, this could perhaps be a good way to approximate equippable items in an ambidextrous-friendly way as users often place their grab spheres around their palms, which would make for a good location to bind equipped objects to.

**Comment by shiftyscales** [comment]
Closing this issue as the new equip system has been implemented. Tools now equip based on the grip pose reference. Grip pose references can be adjusted through an inspector, or by entering edit mode, repositioning the tool in each hand, then saving the new version.
