### ISSUE TITLE
UIX Logix Issues

### ISSUE THREAD

**Issue by Vigilabo** [Frooxius/NeosPublic#405]
Slots that have UIX components attached to them are unable to be used with logix. They will not connect to node inputs. (Like connecting the Slot to something like Set Parent)

The Write node does not seem to work with the UIX components as well. The Write node is unable to connect to any of the values on the extracted component interface.

**Comment by Frooxius** [comment]
That's really strange, UIX components should make no difference as they're the same as any others.

What exactly are you trying to connect to what? Does this happen specifically with UIX components or is this affecting other ones as well?

**Comment by Vigilabo** [comment]
So I tested a little bit more, and it only seems to be if any slot is below the Slot containing the Canvas component (Also effects the slot with the Canvas component itself).

**Comment by shiftyscales** [comment]
I was able to confirm a related case using a project SmolCookie (Smol🍪#5247) was making. Logix packed under a slot that contains a canvas component are unable to be unpacked as the visuals don't generate/an exception is thrown.

**Comment by shiftyscales** [comment]
These issues were fixed in build 2020.3.2.249.
