### ISSUE TITLE
Attempting to log in while offline produces an endless loop of GET request exceptions

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#408]
Steps to replicate:
- Launch Neos while offline
- Enter credentials into the login panel

Result:
Many exceptions are thrown for POST and GET requests for each and every URL it has attempted to access.

Even after each URL has ran through its five retries, there is one URL that has its retries refreshed each time it hits zero. In particular for this session: https://cloudx.azurewebsites.net/api/sessions?compatibilityHash=eQBRsufnmQ95KUFb0iwhLA%3D%3D&includeEmptyHeadless=true

**Comment by Frooxius** [comment]
This is expected behavior. Neos has retry-logic for requests when they fail to deal with temporary connection loss or server issues. It logs the failed attempts into the log for potential diagnostics, but they can be safely ignored.
