### ISSUE TITLE
Make developer tooltip laser go through to hit the gizmo it's pointing at.

### ISSUE THREAD

**Issue by Frooxius** [Frooxius/NeosPublic#41]
It's a little bit tricky aiming at gizmos inside objects right now. This should work in tandem with the highlighting system too, allowing to highlight the gizmo itself.

**Comment by ProbablePrime** [comment]
@Frooxius I think the new laser system has this, so we can close :)?

**Comment by Frooxius** [comment]
Yes, we can close this, thanks!
