### ISSUE TITLE
Volume property of VideoTextureProvide not applied to Unity Native playback engine

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#413]
Steps to replicate:
- Inspect a video player using the Unity Native playback engine
- Change the volume property

Result:
- The volume will not be adjusted even when the volume is set to 0.

With the libVLC playback engine the volume property works as intended.

Issue initially observed, and reported by BlaXun | Ingo#6920.

**Comment by Frooxius** [comment]
Oh forgot to close this one, it's been fixed.
