### ISSUE TITLE
[UIX] Drive node inputs duplicate by user count

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#414]
Tested in isolation, and on a headless- during the creation of a drive node, visuals for the input will be generated for each user in a session. Visuals for the driver do not get duplicated.

The last input visual generated will be set as the active visual for the Logix node.

Strangely, when the drive node is created, it creates Logix interfaces as well for the mesh of the object for which a drive node was created from. For (what I assume to be) the headless user, the interface has different colors compared to every other user's visuals.

(Note: In the following screenshots, the visuals were manually separated using a DevToolTip to better demonstrate the issue.)

![2020-03-04 09 24 54](https://user-images.githubusercontent.com/54213390/75908232-97ea1c00-5dfe-11ea-98cc-df4d99197605.png)
![2020-03-04 09 50 59](https://user-images.githubusercontent.com/54213390/75908241-9a4c7600-5dfe-11ea-81db-228d6c3f8f47.png)

When packed, and unpacked, only one visual is generated as expected.

Issue initially reported by H3BO3#7957.

**Comment by Frooxius** [comment]
I'm not sure I quite understand this issue. What exactly is it that it's getting duplicated? You say that  the visual for the driver do not get duplicated, but that seems to contradict the whole issue. Is it just the visual slots without actual visuals?

Are there reproduction steps? How is the driver node created when this occurs?

**Comment by Frooxius** [comment]
I did some changes in 2020.3.9.689, can you check if that fixed the issue?

**Comment by shiftyscales** [comment]
To clarify- I meant that the driver itself is not being duplicated, but the inputs that are generated with it are. I can confirm the issue is not yet fixed.

I've re-named the issue to more accurately reflect the problem.

![2020-03-09 07 42 54](https://user-images.githubusercontent.com/54213390/76225468-c50d4480-61d9-11ea-8136-a61d06223b83.jpg)

**Comment by Frooxius** [comment]
Oh wait, so it doesn't have anything to do with the Drive nodes themselves, but rather the Input nodes? Is the actual node duplicated or it is just the visual for the input? 

Does this only happen if you extract the drive node using the LogiX tooltip?

**Comment by shiftyscales** [comment]
Only the visuals for the input are duplicated. The only case I've found so far where it occurs is when extracting a drive node with a Logix tip in a session with more than one user, e.g. a headless session.

**Comment by Frooxius** [comment]
Ok should be fixed in 2020.3.12.771, thanks for all the info!
