### ISSUE TITLE
[File Browser][Inventory][UI/UX] [Enhancement] [Feature] Global Search Function feature that allows the user to search all public folders available from all users. 

### ISSUE THREAD

**Issue by aguirretim** [Frooxius/NeosPublic#416]
It is hard for a new user or even an intermediate user to know about all the different public folders available and what is contained in all the public folders available. 

In order to better support users and their creation their needs to be a feature available from the main menu or inventory that allows the users to search all public creations by Type (ie: Avatar, Media, Equipable, Statue, Tootlp, etc) by Author ( ie: From Gearbell, From Turk, From lilpikachoo, etc)  

While I understand there is a user-created world dedicated to this feature a native feature would allow more discoverability from a new or intermediate user.

**Comment by Frooxius** [comment]
Unfortunately, the public folders feature isn't designed to be searchable or listable, it's mainly meant for friends/coworkers and such to easily share folders. People have taken it up to share a lot more, but that's already going past its design.

Instead, there's an upcoming feature, the Neos Store/Workshop, which will let you submit anything (worlds, items, even inventory folders like this), which is going to be indexed and listed out. See this issue: https://github.com/Frooxius/NeosPublic/issues/145

I'm closing  down this issue, as searching of the public folders won't be implemented, but I believe the Neos Workshop would actually fix the underlying issue of discoverability.
