### ISSUE TITLE
Extend Blender installation search to Steam installation directory

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#419]
As per the `EXTRACT BLENDER HERE.txt` text file found in `\NeosVR\Tools\Blender` it is stated:
```
Extract Blender installation into this folder, so the Blender.exe is in this directory.
This will make Neos use this Blender installation for import of Blend files.

If no installation is found here, Neos will search following locations:
C:\Program Files\Blender Foundation\Blender
C:\Program Files (x86)\Blender Foundation\Blender
```
It could be beneficial for Neos to also search the default Steam installation directory for Blender found at `C:\Program Files (x86)\Steam\steamapps\common\Blender`.

**Comment by Frooxius** [comment]
I can add that location to the list. Is C:\Program Files\Steam\etc... also commmon?

**Comment by shiftyscales** [comment]
I believe by default Steam will only ever install to the Program Files (x86) as it's a 32-bit application. Steam does also provide its path in the registry at `\HKEY_CURRENT_USER\SOFTWARE\Valve\Steam` which could also account for non-default installations of Steam.

**Comment by Enverex** [comment]
While a little more technical, it may be useful to see if "blender.exe" is currently assigned to the blendfile shell extension, because if it is, you could use that to locate Blender regardless of where it's been installed.

`Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Classes\blendfile\shell\open\command`

The value will be set to something like...

`"E:\Software\Blender\blender.exe" "%1"`

**Comment by Frooxius** [comment]
Unfortunately using registry is a lot more complicated, because reading registry keys is not cross platform and doesn't work from Mono embedded in Unity without some significant hackery. I'll have to skip that one, sorry.

**Comment by shiftyscales** [comment]
Yeah, I'd agree. In either case, between the default standalone Blender directories, and the default Steam directory, that should account for most users, and most installations of Blender.

**Comment by Frooxius** [comment]
Added the install location in 2020.3.11.1193, thanks!
