### ISSUE TITLE
Scroll Area resets position on user join

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#420]
Scroll areas on any objects will reset to the top anytime a user joins the world.

Steps to replicate:
- Have an object with a scroll area in the world (e.g. inspectors, Twitch chat, Logix node selector etc.)
- Have a user join the session

After the user joins, all scroll areas in the world reset to the top.
- This only appears to occur for a join event. Switching sessions while it is already open does not trigger this issue.

If the UI is generated locally for each new user, it's possible that it is propagating the scroll area's position to each user in the session instead of initially drawing with the existing scroll areas
- Supporting this point- if a world is saved with a scroll area in a particular position, on opening the world, the scroll areas will also be reset.

Issue reported by, and investigated with the help of Vigilabo#9326.

**Comment by Frooxius** [comment]
Should be fixed in 2020.3.9.689! Thanks!
