### ISSUE TITLE
Windows Mixed Reality skeletal input support.

### ISSUE THREAD

**Issue by cristian2452** [Frooxius/NeosPublic#422]
Windows Mixed Reality for SteamVR just realse a update today that adds support for exposing skeletal input data.  This should fix the problem with the wmr controllers that are unable to move fingers of characters ingame.

https://steamcommunity.com/games/719950/announcements/detail/1699484923794914530

**Comment by Frooxius** [comment]
This is already supported. Does it not work for you in Neos?

**Comment by cristian2452** [comment]
yeah it works.
