### ISSUE TITLE
[Bug] Volume Change Lag on Children When Changing Volume on Parent

### ISSUE THREAD

**Issue by Enverex** [Frooxius/NeosPublic#425]
This will make more sense if I explain the design first...

I have a screen / video player. The screen contains the original audio source component but no audio output. I then have two speakers, these contain the audio output from the source screen.

Changing the volume on the screen (on the source itself) has a lag is nearly a second before the volume actually changes. The component value is showing the change immediately, but there's a clear, significant delay before the volume of the sound actually changes.

Changing the volume on the audio outputs instead (the component on each speaker) takes effect immediately.

While this isn't a massive issue, it does have one nasty side effect. If you change the source of the source, e.g. if you're steaming and change the URL, the audio will play back *at full volume* for nearly a second (the duration of the lag) before the volume then corrects itself (with no user interaction) back to the value set on the source component.

The volume isn't being set by LogiX or anything, so there isn't anything external interfering or delaying the volume change that way.

So to clarify: Adjusting the volume on the VideoTexture component lags, altering the volume on AudioOutput components work immediately.

**Comment by Frooxius** [comment]
This is technically not a bug, but unfortunately just an inherent behavior of the libVLC wrapper library. It takes a while for the volume setting to propagate to the playback code.

However I've ended up going around it and just skipped the volume control and implemented it in the code that relays the extracted audio data, which should be much faster. Should be in effect in 2020.3.13.1158
