### ISSUE TITLE
Add option to place label above the imported model

### ISSUE THREAD

**Issue by Frooxius** [Frooxius/NeosPublic#43]
Use the model filename? With or without extension?

**Comment by sirkitree** [comment]
I'd love to see this too! You could replace the text "Model" with the file name.

**Comment by pushstartvr** [comment]
Im sure you have an idea of how to do it but maybe just on the import dialogue have the option.  just one of those text labels i think.

**Comment by pushstartvr** [comment]
also loading a directory of models in a sequential line with the text lables would be handy (model and textures in subfolders of the specified directory) then you could go along the line, see which model didn't load properly and attempt to fix it.  
I spent hours doing this in the aplha and it was really hard to keep track of where you were up to etc and some models have weird names that don't necessarily correspond to the model - although it is a bit easier with the new file importer

**Comment by Frooxius** [comment]
This has been already done a while ago, closing.
