### ISSUE TITLE
Visual artifacting on high resolution photos taken of PBS materials lit by spot light

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#431]
Steps to replicate:
- Create or spawn in a photo subject utilizing a PBS material (e.g. metallic or specular)
- Light the subject via spot light
- Take a photo using a resolution of 4K or higher

Observations:
- This appears to occur regardless of the "quality" setting used, or format (e.g. webp vs png)
- This behavior does not occur with point lights based on testing
- The issue occurs with as few as one spot light (in addition to the directional world light found on the basic empty template)
- The effect is most prominently/reliably seen on the edges of objects, although it has been observed on other faces.

![2020-03-21 07 27 53](https://user-images.githubusercontent.com/54213390/77228834-47d1c000-6b47-11ea-8165-5500f5a97e18.png)

![20200320213121_1](https://user-images.githubusercontent.com/54213390/77228868-6d5ec980-6b47-11ea-95db-bbb50ace4ca6.jpg)

**Comment by Frooxius** [comment]
Hmm if this is happening during the capture itself with only specific materials and lights, it's likely some Unity or GPU driver bug (or potentially even GPU hardware issue, since those blocks look about the size of GPU raster tile), which will make it very difficult/impossible to fix.

Did you manage to replicate this on your end? It's important to see how many people can replicate this and how reliably.

**Comment by shiftyscales** [comment]
Yes, the above screenshot on the cube was me making a simplified example of this issue, @Frooxius. It can be replicated very reliably. The requirements seem to be use of a spot light, a PBS material, and a high resolution for the capture, e.g. 4K or higher.

**Comment by Frooxius** [comment]
Hmm I can't replicate this on my end, tries this and it renders flawlessly. I've captured many 8K photos before and I don't think I've ever observed this effect.

It might be something specific to GPU/drivers or something like that.

![8K Spotlight](https://user-images.githubusercontent.com/8838625/77243514-2934fd00-6c0b-11ea-98e5-30ed7346ece7.png)

**Comment by shiftyscales** [comment]
I see you're in screen mode. That could possibly be a factor? I'm on Nvidia driver version 442.74 with a GTX 1070, and was in VR when taking the photos. It was the basic empty template world with a box, a spot light created using the light tip, and using the camera found in the Neos essentials set to 8K using the button on the side.

**Comment by Frooxius** [comment]
Yeah I was in screen mode during this, otherwise the setup was very similar. I can test it later in VR, but like I said, I never really noticed this on any of my 4K or 8K photos before on my end.

**Comment by shiftyscales** [comment]
Revisiting this issue, and I wasn't able to replicate it. My guess is that this was either a rendering issue in Unity, or a driver issue. Regardless, I'm closing this issue as it appears to no longer be relevant.
