### ISSUE TITLE
Operators do not overload when an input is added

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#432]
Steps to replicate:
- Choose an operator that supports additional inputs, e.g. |, &, +, -
- Add an input by pressing the plus button on the node
- Attempt to overload the node by connecting a different supported type

Observations:
- These nodes work properly, and will overload in their default configuration (two inputs)
- These nodes resume proper function if the additional inputs are removed, bringing the node back to its initial two input state
- Upon addition of an input, overloading breaks for all node inputs, not just the newly created one

Issue initially reported by Turk, but also confirmed by Hayden to also be affecting other nodes such as Pick Random which doesn't work even in its default two input state.

**Comment by TehTurk** [comment]
Would also like to add, if we are also fixing some overloads, could we also get Multiple Inputs for the "Divide' Node? Originally overloading issues happened with Nodes more then 2 inputs, figured that'd also get added while this is being nipped in the bud.

**Comment by Frooxius** [comment]
Multiple inputs for Divide is unrelated to the overloading system and this issue, so fixing this wouldn't add that. It needs to be implemented. It's a bit strange for divide though, because with division you get ambiguity with order of operations, but it could be added.

**Comment by TehTurk** [comment]
Ah sorry, some stuff gets lost in the discord and didn't think it warranted it's own issue when this is in the process bug wise. If anything it would work like how any of the other multiple input nodes would work. Like say your looking for a result in a formula, and you'd rather have an extra input vs an extra node. to emulate that formula.

**Comment by Frooxius** [comment]
Should be fixed now thanks!
