### ISSUE TITLE
Gizmo's enter Gimbal Lock and start rotating on their own

### ISSUE THREAD

**Issue by TehTurk** [Frooxius/NeosPublic#433]
Don't know what the exact cause of it is because I haven't been able to really repro, but I've noticed it often happens with when controllers are near death. But losing tracking information shouldn't cause a gimbal lock. Outsider and a few other have seen it once or twice. I've mentioned it but brought it here so it wasn't forgotten.

**Comment by Frooxius** [comment]
Which gizmos do you mean in particular? What exactly happens? Do they just keep rotating without any user interaction? Do you mean the gizmos themselves rotate or the object they are supposed to rotate rotates?

**Comment by TehTurk** [comment]
Rotation Gizmo, I don't think it's happen with the Translation or Scale one yet. I attempt to rotate a focused object, and it proceeds to keep rotating when I stop my hand movement or lerps when I try to rotate back. It also causes the other 2 axis to be affect hence the weird gimbal locking. It's basically both, the gizmo rotates and the object then reflects it.

**Comment by Frooxius** [comment]
Hmm do you have a video of this happening? I'm having a bit hard time imagining what exactly is going on.

**Comment by TehTurk** [comment]
It's hard to describe, I've been trying to cap it anytime it's happened but I know Outsider's seen it in action and Syri as well on his first days. It's basically the Rotation Gizmo moving on it's own when you interact with it

**Comment by Frooxius** [comment]
Hmm I'll need some way of reproducing this. I'm not sure I've seen this happen myself before.

**Comment by TehTurk** [comment]
I'll see id i can try, but it hasn't happened in awhile so maybe it was tied to SteamVR. See but I had this happening while controllers were occuring, or at least batteries were low enough to maybe affect tracking. The weird thing is that it would start affecting another axis, not the singular one I had selected even in the case.of controllers dying and input locking in while my hand zips off.

**Comment by TehTurk** [comment]
I'm going to close this as I've yet to observe this for quite sometime.
