### ISSUE TITLE
[Possible Bug] Not being able to extract fonts

### ISSUE THREAD

**Issue by LewisSnow** [Frooxius/NeosPublic#435]
I was attempting to extract the font from the "Static Font" component, I grabbed the font, and clicked trigger but it didnt pull out the font. Not sure if I may have forgotten the way to do it, or Im missing something.

**Comment by Frooxius** [comment]
Turns out this was never implemented in the first place. Added in 2020.3.26.94

**Comment by Frooxius** [comment]
Turns out this was just never implemented in the first place. Added in latest build

**Comment by LewisSnow** [comment]
Thats so odd.. kinda hurts my brain a bit.. because I swear I was able to do that before... I did it so much too.. soo weeird
