### ISSUE TITLE
UIX: Canvas breaks on new non-uix element being added.

### ISSUE THREAD

**Issue by TehTurk** [Frooxius/NeosPublic#437]
I found this happening often when making a new parent object, or making a new child object, would require a respawn after the configuration was made then it would behave properly.

**Comment by Frooxius** [comment]
Can you be a bit more specific? Making a new parent object or child object where? UIX supports adding new objects and I've added them before with inspector without any issues.

**Comment by TehTurk** [comment]
Ah underneath either a vertical or horizontal element, but it would also have a ref editor within the hiearchy too so don't know if that'll intefere. I was mainly getting it when Makin children and adding an element to a higher parent to then configure it for UIX.

**Comment by TehTurk** [comment]
Here we go sorry for delay. https://streamable.com/swipa5

**Comment by shiftyscales** [comment]
2020.4.9.1318
```
- Fixed UIX canvas breaking when a child with RectTransform is added under slot with ArcSegmentLayout that doesn't have a label setup (based on report by @ChrisWarner103 (DelVR))
- Fixed UIX canvas breaking when a child with RectTransform is added anywhere under a Slot that doesn't have RectTransform (reported by @Turk, @Coffee and others (sorry I forgot ;_;))
```
This should hopefully address these issues. This issue can be re-opened in the event that new breaks are found.
