### ISSUE TITLE
LogiX: ChildAdded ChildRemoved and ClearGizmoVisual 

### ISSUE THREAD

**Issue by TehTurk** [Frooxius/NeosPublic#441]
From the discord, putting her for remembrance. 3 Nodes that would have some major benefit.

**Comment by shiftyscales** [comment]
2020.4.9.1318
`- Added SlotChildrenEvents node, which fires OnChildAdded and OnChildRemoved impulses (requested by @Turk, @H3BO3, @Cyro, @Anomalous and others)`

A separate issue can be made for ClearGizmoVisual if it's still desired. When possible, feature requests/issues should be simple/self-contained to prevent cases where one aspect of the initial requests prevents the issue being closed.
