### ISSUE TITLE
LogiX: Add IgnoreShellUsers to NearestUserHand/Head

### ISSUE THREAD

**Issue by TehTurk** [Frooxius/NeosPublic#442]
https://discordapp.com/channels/402159838827905024/439422161657135106/694999895635132416
-Discussed by Shifty and Kal

**Comment by Frooxius** [comment]
This should be coming in the next build or the one after that!

**Comment by shiftyscales** [comment]
Implemented in 2020.4.8.1428 as `IgnoreAFK`.
