### ISSUE TITLE
Component: Scale Align or Uniform Scaler

### ISSUE THREAD

**Issue by TehTurk** [Frooxius/NeosPublic#444]
This behavior would be similar in the same vein of the Axis, Circle, and other various Aligners. Currently alot of the Scale Components require you to have a predetermined object, or require a scale manager and is from way way back and doesn't pop up to often in normal uses.
This Aligners or Scaler would:
-Allow Relative Scaling per child
-Auto Add Children
-Drive Childrens Objects to a default Local Scale from the scale they were before they were placed underneath the object
-This could also be linear, logrithmic, and exponential (Thanks H3)
If anything is missing please let me know.

**Comment by shiftyscales** [comment]
2020.4.9.1318 `- Added "Scale Aligner" component (under Transform / Drivers) - it drives the scale of child slots (requested by @Turk)`
