### ISSUE TITLE
New Context menu button should be a toggle

### ISSUE THREAD

**Issue by DanteTucker** [Frooxius/NeosPublic#445]
If the context menu is currently open, pressing the button again should close it.

Currently pressing the context menu button again while the context menu is open destroys and immediately reopens the menu. The correct behavior is that the menu should just close.

**Comment by alexderpyfox** [comment]
I think that was done on purpose so new users dont accidentally leave it open which locks down their locomotion movement and get stuck that way

**Comment by DanteTucker** [comment]
Hey alex what you are saying is not relevant to my request. This is in addition to the current behavior.

**Comment by DanteTucker** [comment]
To be more clear, currently pressing the context menu button again while the context menu is open destroys and immediately reopens the menu. The correct behavior is that the menu should just close.

**Comment by TehTurk** [comment]
Agreed, but this one releases the joystick because I don't think Froox wants anything more then 2 button presses.

**Comment by Frooxius** [comment]
I've added this behavior in 2020.4.7.1222 since it was very commonly requested.
