### ISSUE TITLE
[Bug?] Not being able to interact with the context menu in physical mode

### ISSUE THREAD

**Issue by LewisSnow** [Frooxius/NeosPublic#448]
In physical mode, you're not able to interact with the new context menu. Would be nice to be able to regardless what mode you're in.

I assume that maybe with the new laser interactions this may not be an issue?

**Comment by shiftyscales** [comment]
You can interact with the context menu in physical mode, but it requires that your tooltip be physically touching the context menu, @LewisSnow.

**Comment by Frooxius** [comment]
Fixed in 2020.4.7.1222, thanks!
