### ISSUE TITLE
Follow 301 redirects with Location header for pasted URLs

### ISSUE THREAD

**Issue by AlexanderPavlenko** [Frooxius/NeosPublic#450]
Thanks for the great software!
I would like to be able to paste URL which returns multiple 301 redirects until reaching video stream. I hope this would allow to have a screen with its source editable via DNS entry. Or maybe there is a simpler way to update stream URL without creating a new screen?

**Comment by Frooxius** [comment]
Thank you!

I'm not sure if this would be possible. The URL's are handed directly to libVLC, which handles the playback. Do you know if regular VLC supports doing this if you play a network stream? If it does support it, then it should be feasible too.

However you can update the URL easily in Neos with LogiX (the scripting language). You can write new URL to the VideoTexture and it'll load it.

**Comment by AlexanderPavlenko** [comment]
Thanks! I found "Writing a URL to a video player without a dev window open" in the [wiki](https://wiki.neosvr.com/subdom/wiki/index.php?title=Tutorials#LogiX).

**Comment by AlexanderPavlenko** [comment]
I tried to use Network/GetString node, and for some reason for any URL its outputs OnSent and OnResponse are triggered, OnError – no impulse, but Content = null and StatusCode = 0.
When triggering request I also see the confirmation dialog and click "allow".

**Comment by AlexanderPavlenko** [comment]
> Do you know if regular VLC supports doing this if you play a network stream?
Yes, VLC does open such URLs with redirects, but NeosVR seems to ignore them when trying to paste from clipboard.

**Comment by Frooxius** [comment]
Oh I see. Have you tried spawning an empty Video Player and pasting the URL there? When you're pasting the URL from clipboard, Neos tries to check what type it is, which is a separate system so it never reaches libVLC. But you can just paste the URL to a video player directly on the VideoTexture component through the inspector.

**Comment by AlexanderPavlenko** [comment]
What about Network/GetString node? I'm not sure why it does not work. Using it would allow better automation in my case.

Even more strange, in the latest NeosVR update (build id: 4881205) I can't get video streams to play at all.
For example, pasting either [youtube](https://www.youtube.com/watch?v=CuhYv-LM498) or [streamlinked](https://pwn.sh/tools/getstream.html) URLs produces a paused player.

> you can just paste the URL to a video player directly on the VideoTexture component through the inspector

I have tried this now, clicking Play button does nothing. But considering the issue with the non-redirecting URLs (I hope it's on my side),  I don't know, this could have worked before.

**Comment by Frooxius** [comment]
What is your setup with the GetString node? You usually need to write the output somewhere on the impulse on the output to store and show it, if it's plugged directly to display it won't show up, because it's only valid for the duration of the output impulse. Using a Write node and string variable works well for this.

I'm not quite sure why the video isn't playing anymore, there haven't been any changes in the build to playback. 

It's also possible it's getting stuck at the Unity Native playback. Try clicking on the "Force libVLC" to force that to handle the playback.

**Comment by AlexanderPavlenko** [comment]
> if it's plugged directly to display it won't show up

Yeah, that was the problem. Thanks!

> Try clicking on the "Force libVLC" to force that to handle the playback.

Did not help. It seems only live streams are affected. The usual Youtube videos do play via Unity Native.

Probably not related, but I also spotted not working video players with neosdb:// URLs in the "New to Neos?" world by BusinessLawyer.

**Comment by AlexanderPavlenko** [comment]
Live streams playback does work now. Not sure what was the issue.
