### ISSUE TITLE
BooleanSwitcher applies to root on undo of deleted component from a deleted object

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#451]
Steps to replicate:
- Add a BooleanSwitcher with AutoAddChildren enabled
- Remove the component from the slot
- Delete the object/slot
- Undo twice

The BooleanSwitcher appears to add everything in the scene as a child, setting the entire world, and all its objects/users as inactive.

[SHIFTY-PC 2020-04-07 15_22_44.log](https://github.com/Frooxius/NeosPublic/files/4447275/SHIFTY-PC.2020-04-07.15_22_44.log)

**Comment by Frooxius** [comment]
Which object did you add the BooleanSwitcher to? Was it just any random one in the world?

**Comment by shiftyscales** [comment]
Initially it was my avatar when I first discovered it. But I reproduced it with just a cube created by the DevToolTip. That simplified scenario is the one that log is associated to.

In the case of my avatar, quick-switching into my avatar replaced the "delete" step.

**Comment by shiftyscales** [comment]
2020.4.9.1318. `- Fixed Component destroy undo step attaching the component to the root if the original Slot was destroyed`
