### ISSUE TITLE
Adjust the naming of the LogiXTip Traversal Options

### ISSUE THREAD

**Issue by ProbablePrime** [Frooxius/NeosPublic#452]
I've never really understood the LogiXTip Traversal options. In the research process for the recently published LogiXTip Overview I had to go learn what they did and even after learning them I was still confused.

Therefore my suggestion is to change the name of the "Break at" mode to be:
"Stop at Reference Nodes"

**Comment by Frooxius** [comment]
Changed in 2020.4.9.1318 thank you!
