### ISSUE TITLE
Changing a Value Slider Fills the Undo Buffer

### ISSUE THREAD

**Issue by Enverex** [Frooxius/NeosPublic#462]
I noticed an issue last night wherein I deleted a texture from a shader and then moved the brightness slider on the emission from min to max. Trying to undo these actions, rather than undoing the whole slider movement as the first undo, then the texture deletion as the section, what instead happened was that each undo step instead moved the slider a very small amount back. I ran out of undo buffer before the slider was even back to it's original position (it got back to about 1/3 of where it should have been).

I assume this is an undo batching issue.

**Comment by TehTurk** [comment]
This might be intended , undos are supposed to be single actions as batches are usually tied to something more like a multi grab or something that affects multiple objects.

**Comment by shiftyscales** [comment]
I don't think it's intended. It's likely just that it lacks proper undo batching, so it adds an undo step for each value it is slid to before being released, @TehTurk.

**Comment by Enverex** [comment]
Keep in mind that the "swipe" I did with the slider was a single hand motion so as far as I was concerned, it was a "single" change, I didn't incrementally step it or move it multiple times (in which case I could understand it going back in steps).

**Comment by Frooxius** [comment]
Yeah this is definitely not intended, when changing the same value, all the changes should "collapse" into a single Undo step if there's no different undo step in between. 

Was this changing a color in the color dialog? I can't think of any material that has an emission slider. 

Were all the undo steps just for this change? Or were there some other undo steps in between?

**Comment by TehTurk** [comment]
Oops apologies, I didn't realize he was physically using the slider vs going from Value 0-1 in the input.

**Comment by Enverex** [comment]
It was the brightness slider (the fourth one down) in the colour select popout. All actions in a row were purely this brightness change.

**Comment by Frooxius** [comment]
I found the issue, the sliders themselves were making undo steps for their own value, causing the spam. Fix coming in the next build!

**Comment by Frooxius** [comment]
Fixed in 2020.4.19.195!
