### ISSUE TITLE
AxisPanner Object Appears Far Outside of Range

### ISSUE THREAD

**Issue by Enverex** [Frooxius/NeosPublic#464]
When using an AxisPanner on an object with a very high number, the object appears to start outside of the desired range. For example here, the range is 8000 and the centre of the component is around 0,0 on the map, so it should move between 4000 and -4000, but after loading into the world, it's already outside of that range:

![image](https://user-images.githubusercontent.com/958670/79638449-3a771800-817d-11ea-85c1-cde75d34552c.png)

But, after the first loop, it starts working correctly. The main issue with that is, in instances with large numbers like this, it can take a *very* long time to complete that first loop.

**Comment by Frooxius** [comment]
Should be fixed in 2020.4.19.195!
