### ISSUE TITLE
[Unity SDK] Play Mode Only Works Once Before Crashing

### ISSUE THREAD

**Issue by Enverex** [Frooxius/NeosPublic#465]
Being able to launch the play-mode of Unity (to start the SDK) only works once. If you stop play mode and then try to start it again, Unity will silently crash/close without any dialogue or saving.

**Comment by Frooxius** [comment]
Unfortunately this is not fixable with the current SDK, sorry. The upcoming proper Unity SDK won't have this issue: https://github.com/Frooxius/NeosPublic/issues/52
