### ISSUE TITLE
Allow Worlds to Override Far Clip Value

### ISSUE THREAD

**Issue by Enverex** [Frooxius/NeosPublic#466]
So one optimisation world makers can do is to use objects or fog to obscure distance, once you've done that, you can bring the render distance down to just a little further than the real viewable distance (as objects aren't automatically occluded), potentially greatly enhancing performance in those worlds.

Currently there isn't a way to do this on a per-world basis as it's actually configured on a per avatar basis (and 4000m when not configured I believe).

Can this please be exposed as a component so that world authors can force a far clip value, allowing use of the camera as an optimisation technique?

**Comment by TehTurk** [comment]
This is already a thing to some degree, there is far clipping option on the clipping component that's added for avatars.

**Comment by shiftyscales** [comment]
This has also already been asked for in another capacity via this issue #322. 

Being able to control the render setting on a per-world basis requires an architectural upgrade to the engine so that worlds can send their render settings to the renderer.

**Comment by RileyGuy** [comment]
I also think clients should have supreme veto power over any graphical setting the server wishes to impose.
