### ISSUE TITLE
"Hide Lasers" doesn't hide lasers from the tools of other users

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#469]
While "Hide Lasers" is enabled in the streamer cam- lasers are hidden successfully from the local user, and the local user's tools. Lasers are also successfully hidden when other users have no tool equipped.

Lasers are not hidden when other users have a tool equipped, e.g. a Logix tip or a DevToolTip.

**Comment by Frooxius** [comment]
That's intentional, certain tools force lasers on since they're part of their function.

**Comment by shiftyscales** [comment]
Those same tools have their lasers hidden for the player though, @Frooxius. So it's inconsistent. E.g. if I had a Logix tip equipped, it wouldn't show my laser if I have "Hide Lasers" enabled, but I would see your lasers. If lasers are supposed to be forced on then, shouldn't the user's lasers also remain enabled to match?

**Comment by Frooxius** [comment]
Yeah they should be on for the user as well. I'd just leave it though since the laser system is being reworked next, so it's not worth fixing before then.
