### ISSUE TITLE
Implement spawn areas

### ISSUE THREAD

**Issue by Frooxius** [Frooxius/NeosPublic#47]
Set of components for defining spawn areas and other spawn properties (such as spawning into a specific coordinate system).

The default spawn system will automatically pick one of the spawn areas and spawn the user within.

**Comment by pushstartvr** [comment]
this would be great.  I would like users to spawn into seats in a classroom (or space theatre).  or into seats in a mine cart style ride.  So having a list of spawn locations and being able to populate only 1 user to that fixed location - no teleporting.  When you are dealing with kids in education you want to have full control over them

**Comment by Frooxius** [comment]
Implemented the system for spawn areas and spawn parenting. There's new CommonSpawnArea component and some point generators (separate components) as well as items in the Create New menu. 

Pushed to nightly-patreon.
