### ISSUE TITLE
Developer mode gizmos are persistent/don't cleanup

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#472]
Gizmos created by developer mode are not marked as non-persistent, and litter worlds upon their creation.

Exiting developer mode doesn't clean up gizmos.

Issue reported by Enverex#6528.

**Comment by Enverex** [comment]
Going back into developer mode, then back out again also doesn't remove the original stuck ones (to rule it out being a fluke failure initially).

![20200422185807_1](https://user-images.githubusercontent.com/958670/80037895-692e1f00-84ec-11ea-9973-3959f7754f16.jpg)

**Comment by Frooxius** [comment]
Can you check which gizmos are these by opening one of them?

**Comment by shiftyscales** [comment]
MeshRendererGizmo, @Frooxius.
![2020-04-23 08 46 54](https://user-images.githubusercontent.com/54213390/80078959-76570800-8504-11ea-839e-b389ccbd20f1.png)

**Comment by Frooxius** [comment]
Should be fixed in 2020.4.25.491 thanks!
