### ISSUE TITLE
"Show Only Headless" on SessionOrbsController

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#474]
Suggested by Ryuvi#9094 and Hayden#3180, they wish to have more granularity over which session orbs appear in the SessionOrbsController.

The use-case is to have two separate session joiner tables in his world, one for headless, and one for user-hosted sessions.

If the component were tweaked to have "ShowUser" alongside "ShowHeadless" it would allow this additional valid configuration.

**Comment by shiftyscales** [comment]
"ShowEmpty" was also proposed to optionally filter out empty sessions.

**Comment by Enverex** [comment]
I requested this months ago but Froox said that the world/session browser will address the issue. I'm not sure if there's been any change since then.

**Comment by Frooxius** [comment]
This is a bit tricky. The "ShowHeadless" setting currently is actually "ShowEmpty", it just hides any sessions that currently don't have any active users, headless or not. Similarly it will actually show headless if there's any users in it.

I could add more settings, but question is how important that is or how to do it without it getting too convoluted over time. The new UI will have proper filtering for things and such.

I could change the "ShowHeadless" to "ShowEmpty", but the question is how to handle combination of that with show headless. Or just rework it into "Show All" "Show Active" and "Show Only Empty" as exclusive options.

**Comment by shiftyscales** [comment]
"Show active" could be a great solution, and I think it could be the default for the session joiner component.

If it replaced the existing default session joiner in the local home, cloud home, MTC, and Content Hub, it would greatly help with navigation, and discovery of worlds prior to the UI overhaul of the world/session browser as a good short-term option.

The initial request was to separate headless from user-hosted entirely- although "show active" could work well to alleviate an issue that separation was trying to solve in discoverability of active worlds/clutter.

**Comment by Frooxius** [comment]
One problem is that if it's the default, it'll make headless worlds almost non-discoverable, unless someone who already knows about them joins them. It might be acceptable for now, but it's a question.

However that's kinda redundant, because that option is there already as inverse ShowHeadless. The request as I understand it is to show only headless, rather than hiding the headless ones.

**Comment by shiftyscales** [comment]
Yeah the initial request was to be able to fully separate headless and user sessions by showing only headless. In Ryuvi's home world, he has two separate session joiners integrated into the world's layout, and was wanting to be able to split headless and non-headless into separate tables.

If the component generated orbs in a fixed pattern, or the default session joiner had aligner components on it, it could also help with readability of the component, making it more useful going forward as the tables continue to get increasingly crowded, in addition to the work being done directly on the UI to help with discovery. Although that can be made into its own issue at a later time if desired as it's out-of-scope to the initial request.

**Comment by shiftyscales** [comment]
I feel this isn't really too relevant anymore. Headless sessions can be searched for in the new world browser.
