### ISSUE TITLE
Component clone tip dequips on secondary press in screen mode

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#475]
Reported by Hayden#3180.

[SHIFTY-PC - 2020.4.24.58 - 2020-04-24 21_35_25.log](https://github.com/Frooxius/NeosPublic/files/4531647/SHIFTY-PC.-.2020.4.24.58.-.2020-04-24.21_35_25.log)

**Comment by Frooxius** [comment]
Sorry, this won't be fixed. The tool depends on proper tool system. The one in the screen mode is hacked together and doesn't have those, causing the tool to break.

Best thing is to wait for proper Desktop mode: https://github.com/Frooxius/NeosPublic/issues/151
