### ISSUE TITLE
Expose shadowmap resolution property

### ISSUE THREAD

**Issue by InsaneGrox** [Frooxius/NeosPublic#478]
so I brought this up in the discord but it got buried so I'm bringing it up here, light sources with shadows seem to be more preformance intensive then even mirrors at this point, which is strange, especially considering Neos uses deferrred rendering, and that mirrors are recursive rendering, while light source shadows are purely shadow mapping per light source, all nearby materials are PBS metallic by the way.

Tested this in a few worlds, at one point had 8 mirrors active at once with 72 fps, but then when I removed them and put in even 4 light sources with shadows my frames tanked into the 40s.

GPU: RTX 2080TI
CPU: I7 9770K
RAM: 16GB DDR4

**Comment by Frooxius** [comment]
Unfortunately this is just inherent to how they work in Unity's rendering pipeline (or in general, realtime point shadows are one of the most expensive things to render), there can't be much done about that. Mirrors only need to render the scene twice and only when you're looking at them. Point lights need to render the surrounding scene 6 times to render a cubemap shadowmap and often do even when you're not directly looking at them, making them much more expensive.

I recommend significantly decreasing their range and compensating by intensity, which will reduce how far they have to render and thus reduce the amount of surrounding geometry that needs to be processed.

I can expose ability to adjust the resolution of the shadowmap which can reduce the number of pixels that need to be processed. Depending on whether it's the drawcall or geometric complexity of the scene it might not help much though.

**Comment by shiftyscales** [comment]
Changing the issue title to "Expose shadowmap resolution property" to reflect @Frooxius's proposed solution.

**Comment by Frooxius** [comment]
Exposed in 2020.5.12.521!
