### ISSUE TITLE
PlayOneShot Not Playing AudioClipInput

### ISSUE THREAD

**Issue by Medravr** [Frooxius/NeosPublic#479]
I have used PlayOneShot multiple times in the past but this appears to be a little bug found with PlayOneShot no playing the wav file connected to the AudioClipInput. It will initially work but after saving a world or packed logix into inventory the wav file will no longer play.

Here is the process:
Add a wav file to the AudioClipInput connected to a PlayOneShot. 
Pack logix under an empty parent. 
Save world or save logix in inventory. 
Reopen world or open logix in another world. 
Wav file will be recognized by the AudioClipInput but not sound will play. This behavior is repeatable and I can show in Neos if needed.

**Comment by shiftyscales** [comment]
I noticed a few other issues regarding audio clips in general. If the sound clip is very short after playing the first time from the clip player that generates on file import, every subsequent play of the sound is silent unless the clip is set to loop.

Using a short clip in the PlayOneShot via AudioClipInput was making the audio static-y for me, as though the buffer size was too small.

As a curiosity- was this a very short sound effect, or a longer sound file, @Medravr? Was the asset still referenced anywhere in the assets folder, or in the `Clip` section of the AudioClipInput node component in the inspector?

**Comment by Frooxius** [comment]
Should be fixed in 2020.5.4.1227 Thanks for the report!
