### ISSUE TITLE
Certain advanced import settings being ignored for skinned meshes

### ISSUE THREAD

**Issue by H3BO3** [Frooxius/NeosPublic#480]
I commonly upload non-avatar skinned meshes and even when the "Generate colliders" and "Setup IK" boxes are unchecked, the import still generates a capsule collider for every bone which I have to go through and delete, because I don't need them. Also, the IK still attempts to set up, which results in an error window, which isn't as detrimental as the colliders, but still annoying to see that the system is ignoring the option.

**Comment by Frooxius** [comment]
The "Generate Colliders" is now respected for rig colliders in 2020.5.12.521!

The Setup IK is already correct respected, the dialog that you see is not IK, but it's the rig analysis, so that's correct behavior.
