### ISSUE TITLE
Particle Cone Emitter Doesn't Emit in a Cone

### ISSUE THREAD

**Issue by Enverex** [Frooxius/NeosPublic#481]
The cone particle emitter appears to simply emit in a sphere despite it's name. I've not found any combination of settings that will cause the emitter to operate as expected.

![image](https://user-images.githubusercontent.com/958670/80724386-b1a39900-8af9-11ea-9487-e63d90b4dfa6.png)

Force Direction isn't used as that would cause it to emit in a line and not in the shape of the emitter itself, regardless of emitter type in use.

**Comment by Frooxius** [comment]
Are you sure you have it setup correctly? There could be the sphere emitter still assigned perhaps.

I have tested it and it works as expected:
<img width="1920" alt="ConeEmitter" src="https://user-images.githubusercontent.com/8838625/80731286-fc79dc80-8b0a-11ea-8342-8820aa7574f5.png">

**Comment by Frooxius** [comment]
Oh, this mode isn't implemented yet for this, but that's something I can add.

**Comment by Beaned2000** [comment]
this would already enable so much more nice particle effects to be made

**Comment by Frooxius** [comment]
In 2020.5.8.141 I've added DirectionReferencePoint which allows changing the reference "center" point from which the particles move away. Setting this to [0; 1; 0] should produce desired behavior. 

New ConeEmitters are setup with this value automatically, for the old ones you have to change it (they're kept the same for compatibility reasons). 

Hope this helps!
