### ISSUE TITLE
Adjustable laser smoothing

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#487]
Posting for posterity/issue tracking- numerous users have requested a way to change the smoothing settings on their laser/make it more responsive

User-adjustable settings to override the behavior of the lasers will allow users to better customize their experience to their preferences.

**Comment by Frooxius** [comment]
This will be added after the new dash and setting system is done.

**Comment by Frooxius** [comment]
It's been added for now in the Settings due to demand in 2020.5.6.44
