### ISSUE TITLE
Pulling laser-held item back to hand starts locomotion and snaps the item inconsistently

### ISSUE THREAD

**Issue by H3BO3** [Frooxius/NeosPublic#488]
This only works with a tooltip equipped - Pulling back with the hand alone does not cause the item to snap to physical holding, I believe this is incorrect behavior as well. The item pulls back and snaps, but there is no haptic hit, and you immediately start moving backwards because the joystick is being held - Perhaps a check to not move until the joystick makes a significant magnitude/directional change? Also, the item snaps and stops when the unsmoothed position reaches the hand, causing the item to snap at varying distances from the laser base depending on how far away it initially was.

**Comment by Frooxius** [comment]
I'm not quite sure I understand the inconsistency of the snapping. Do you have any visual references for this? What is the expected snapping position vs how it actually snaps?

**Comment by Frooxius** [comment]
It should be fixed in 2020.5.6.44. I'm not sure if I  quite understood all the issues, so feel free to reopen if there's something still b roken with this.
