### ISSUE TITLE
Tool lasers are not accurate

### ISSUE THREAD

**Issue by H3BO3** [Frooxius/NeosPublic#491]
The snapping and smoothing behavior of the lasers does not accurately reflect where most basic tooltips (i.e. inspector tooltip, component clone tooltip, presumably others) are actually pointing/raycasting - This can cause misses while moving the hand quickly and thus unexpected behavior. I believe the tools are behaving as they used to, with straight raycasts.

**Comment by Frooxius** [comment]
This is a known issue, this part hasn't been implemented yet. Tools still use their own raycasts. Further integration is coming in the next build or two.

**Comment by shiftyscales** [comment]
Added in 2020.5.7.192.
