### ISSUE TITLE
Logix node menu Pin button isn't working via Laser

### ISSUE THREAD

**Issue by H3BO3** [Frooxius/NeosPublic#493]
The laser seems to be having trouble targeting/sticking to the pin button, and it stays red as well, hinting that the grabbable is perhaps somehow taking precedence over the button. Physical/fingertip touch works fine. (Experimentation done by Shifty)

**Comment by Frooxius** [comment]
Fixed in 2020.5.6.44 by adding the slight collider penetration. Should improve things overall. Thanks!
