### ISSUE TITLE
Public/worldspace lasers break on interaction with private UI for Oculus Touch controllers on SteamVR

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#495]
Steps to replicate:
- Oculus Touch controllers
- SteamVR runtime
- Equip a Logix tip
- Attempt to spawn a Logix node by double clicking the trigger

Observations:
- This bug occurs every time a tool is equipped
- This bug can be mitigated by opening and closing the Oculus dash. This will cause the tool to function normally again until the tool is re-equipped.

This issue has been reported by guillefix#5692, Cyro#5120, Jeff07734#5022, and possibly others.

**Comment by Frooxius** [comment]
Do you have logs for when this happens?

**Comment by shiftyscales** [comment]
I do, but I didn't submit them as the logs don't show anything as having occurred.
[SHIFTY-PC - 2020.5.5.819 - 2020-05-05 08_51_12.log](https://github.com/Frooxius/NeosPublic/files/4582025/SHIFTY-PC.-.2020.5.5.819.-.2020-05-05.08_51_12.log)
[Player.log](https://github.com/Frooxius/NeosPublic/files/4582030/Player.log)

**Comment by guillefix** [comment]
One thing I noticed is that it can happen on either hand, but only one one hand at a time.

**Comment by shiftyscales** [comment]
Discovered another related issue. The click to activate/deactivate the lasers also stops working after interacting with private UI e.g. the inventory, @Frooxius. It appears that the laser might not be properly transitioning from private to public after certain interactions on Oculus Touch controllers via SteamVR.

**Comment by Electronus** [comment]
I have logs form a session where I had both this happen and my lasers not working at all until I opened and closed the Oculus dash. 

In fact aside from UI "primary action" wasn't registered at all by tools unless I opened and closed the Oculus dash between every tool. (should probably be a separate issue?)
[DESKTOP-1LAFNCA - 2020.5.4.1227 - 2020-05-04 18_45_32.log](https://github.com/Frooxius/NeosPublic/files/4583778/DESKTOP-1LAFNCA.-.2020.5.4.1227.-.2020-05-04.18_45_32.log)

**Comment by Electronus** [comment]
I saw you fixed some issues from the logs I sent you, however I am still experiencing the same behavior in steam VR. log included. 
[DESKTOP-1LAFNCA - 2020.5.6.44 - 2020-05-06 17_10_11.log](https://github.com/Frooxius/NeosPublic/files/4590154/DESKTOP-1LAFNCA.-.2020.5.6.44.-.2020-05-06.17_10_11.log)

**Comment by shiftyscales** [comment]
As of the latest build, worldspace lasers now become completely unavailable after touching private UI, e.g. the tool belt. Trigger no longer reactivates the laser, and the workaround of opening the Oculus Dash no longer works either.

**Comment by Frooxius** [comment]
Should be fixed in 2020.5.9.132, thanks!
