### ISSUE TITLE
[Feature Request] Allow Pack and Unpack LogiX nodes to construct Matrices

### ISSUE THREAD

**Issue by Zegopharo** [Frooxius/NeosPublic#497]
As a method to construct float2x2, float3x3, and float4x4 matrices, I had a thought that we could add a function to the existing pack nodes to allow the creation of these matrices.

Pack xy would take 2 float2s and make a float2x2, pack xyz would take 3 float 3s, etc.

As for how to orient them, I would like to point out in my own experimentation I have found float4x4s can be directly multiplied by a float4, without generating an intermediary node, suggesting a vertical orientation. I suggest we keep this, and have the inputs as each column of the matrix.

Admittedly this may limit the dimensions of the matrices that could be created, but at present we also do not have non-square matrices available in any form. At that point a separate "Pack Matrix" node would be wise, though at this point I'm not sure whether adding this capability to the pack/unpack nodes or creating a new node would be easier to implement.

**Comment by H3BO3** [comment]
To add on to this, I also suggest coordinate-based nodes for deconstructing a matrix, one with a provided row (outputting a multi-number value), another with a provided column, and a third that accepts both row and column (giving a single value).

**Comment by Zegopharo** [comment]
I like that deconstruction idea, but I think it can be done with just an input from the matrix to be deconstructed, and a single float2 for (x, y) coordinates. If you want all of row (x) or column (y), leave the other value at 0. At that point the current unpack nodes would not need to be able to deconstruct matrices, unless values were needed en masse.

That said, I'll admit I have no idea how this would affect double _n_ x _n_ matrices. 

On that issue that was closed, I can confirm that "Multiply: Matrix -> Matrix -> Matrix" is already possible, and required for my Jacobian IK project. I am unsure if any others are available, though. Transpose could especially be useful for my project, but it would likely be a backup if node A^-1 cannot find an inverse (a very likely scenario for Jacobian Matrices).

**Comment by Frooxius** [comment]
Added in 2020.5.8.141! Thanks for suggestion! Let me know if you need more matrix nodes.
