### ISSUE TITLE
Better compression for normal maps

### ISSUE THREAD

**Issue by H3BO3** [Frooxius/NeosPublic#498]
Add compression modes designed for normal maps to reduce blocky artifacts, potentially using the normal map bool on textures. Many people are setting normal maps to uncompressed to eliminate those artifacts, which is obviously not very ideal.

**Comment by Enverex** [comment]
![20200505004450_1](https://user-images.githubusercontent.com/958670/81198122-08591900-8fb9-11ea-9baa-ef8a2b8c4b6b.jpg)

One example I'm staring at a lot lately, there shouldn't be any squares on the wall, they're purely normal map compression artifacts.

Another example in GIF format showing both significant loss of clarity as well as more squares...

![normal](https://user-images.githubusercontent.com/958670/81202703-e2367780-8fbe-11ea-88cf-c28a9dc1e543.gif)

**Comment by Frooxius** [comment]
This is a little bit more tricky. Typically normal maps use DXTnm compression, where the X is packed into RGB and Y into A and Z is recomputed in the shader. This is then compressed using DXT5/BC3 compression.

However doing this switch will require recompiling all the shaders as well as properly marking textures as normal maps. I think a heuristic can be done for this, by marking the maps that are used in the normal-map slot automatically. The only issue would be materials which for some reason use it both as normal map and as regular texture.

**Comment by H3BO3** [comment]
I think automatically marking the materials that are in the normal map slot would be good. Non-normal map assets in that slot are a nonstandard effect and should not be expected to work correctly, and that way only the ones with that strange setup would have to be corrected - Could that behavior could still be overridden with the "uncompressed" checkbox? I will gather more information on how these changes would affect existing materials

**Comment by Frooxius** [comment]
Yeah, I think being overzelaous might be the lesser evil here for the upgrade. Typically regular maps as normal maps don't really produce correct results anyway and same with normal maps elsewhere.

You'll technically be able to use "uncompressed", but the texture will still need to be marked as normal map, because the data of the texture need to be actually different.

I think best first step will be to do this marking and schedule asset variant computations. That will help seed a lot of commonly used textures with the new normal maps in the cloud, so when we actually do the switch, things won't take long to load.

**Comment by H3BO3** [comment]
Does the isnormalmap flag actually do anything currently?

Also, in quite a few of the CC0 materials there are normal maps with a seemingly different format - they look very greenish-blue rather than the regular blue-lavender neos accepts. As a result they tend to produce incorrect shading. Is there a way that these normal maps + other formats could be supported or made compatible if the correct compression options are set?

**Comment by Frooxius** [comment]
No, I've put it where when I was working on the system, but didn't make it do anything yet.

Can you send me any samples of those normal maps? I'm not sure which ones they are or what might be up with them. It's possible they might not be tangent-space normal map, but rather object space. Those would require a different shader. Might be something else though, in which case they need to be converted.

**Comment by Frooxius** [comment]
@Enverex Can you send me one of the normal maps exhibiting the significant compression artifacts? I got the system ready, but I want to test how it improves quality first.

**Comment by Frooxius** [comment]
Build 2020.5.9.132 will now start scheduling normal maps to be compressed using DXTnm/BC3nm with compressor configured to better handle normal maps. This should increase quality significantly.

All shaders need to be recompiled first though, which will take at least 2 days. In the meanwhile I recommend opening a bunch of worlds,  so all the textures get seeded.

**Comment by Frooxius** [comment]
As of 2020.5.10.1362 we have now switched to DXTnm/BC3nm compression for normal maps, which should provide a significantly higher quality. Some normal maps might still be using the old one and need to be computed - you can check if they look like typical blue-ish ones (old) or new red-ish ones.
