### ISSUE TITLE
[Feature Request] [Logix] Matrix operations support

### ISSUE THREAD

**Issue by Earthmark** [Frooxius/NeosPublic#502]
Currently the matrix types are exposed in logix, but no operators can use them (as far as I've found). Operations like multiplying a matrix by another matrix, matrix by a vector, and basic transforms on a matrix would be appreciated!

The current list of bare-bones-hoped-for operations
Multiply: Vector -> Matrix -> Vector
Multiply: Matrix -> Matrix -> Matrix
Multiply: Float -> Matrix -> Matrix
Build: VectorN (xN) -> MatrixNN
Break: MatrixNN -> VectorN (xN)
Transpose: Matrix -> Matrix
Add: Matrix -> Matrix -> Matrix

In terms of hoped-for-operations, really it could grow to anything. Even past what numerics has some mathematics libraries would be great for a research capacity (like a node to find eigenvectors and eigenvalues). In the case of higher order math systems, using an API base from an existing library is preferred, as there's a higher chance of pulling people into Neos from the research community who already know the library landscape (and so the barrier for entry is much lower), as well as a higher level of robustness from existing methods, as well as easier integration of new operations as the library is extended (probably by sleep deprived grad students, instead of possibly sleep deprived froox'es).

The least-effort way may be to bind to System.Numerics.Vectors (which is referenced already, at a minimum by BEPU), and wrapping the methods with logix handlers. It does look like the matrix types are different than the numerics types, but the operations list in numerics would be appreciated (or at least some of them). Numerics does not have extended computational operations, but some higher order linear algebra libraries use numerics internally, so construction of  Neos plugins may be more approachable over a numerics based api.

Thank you for the consideration of this request,
Earthmark

**Comment by Frooxius** [comment]
I plan on adding those soon-ish. They will be for Neos' matrix types (e.g. float4x4), I do not plan to wrap System.Numerics.Vectors, as that wouldn't play well with any other types.

However this has already been requested here, closing this one as duplicate: https://github.com/Frooxius/NeosPublic/issues/497

Feel free to add more into that one.
