### ISSUE TITLE
Lasers place items on one face of the toolshelf

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#504]
Lasers no longer place tools on either side of the toolshelf, instead favoring the top side.

Issue observed by myself, and also reported by Anomalous#0699 who recorded [this clip](https://cdn.discordapp.com/attachments/439422161657135106/707464551028752414/tool_shelf_issue.mp4).

**Comment by ProbablePrime** [comment]
This is causing tool shelves to become very unreliable for me :(

**Comment by shiftyscales** [comment]
Do you have any specific examples of when toolshelves aren't working as intended? It might be an issue elsewhere with how the laser functions, or determines where to place the tip. For me, the only observable change was that tools always just placed on the 'top' of the shelf, @ProbablePrime.

Otherwise they've been perfectly reliable so far for me. Are you using custom tools and/or tools with offset tip references perhaps?

**Comment by Frooxius** [comment]
This is because of the rewrite of the system. I will improve the placement logic so it behaves more like the old system. Don't need any examples. Thanks for the report!

**Comment by shiftyscales** [comment]
Added in 2020.5.7.192.
