### ISSUE TITLE
Clamp laser smoothing settings to sane values

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#507]
Setting both the start and end modulate angles to 0 cause lasers to break in worldspace by producing a NaN that messes up the BEPU raycasting direction.

This only appears to affect worldspace lasers, and not private ones, fortunately, so recovery is as simple as changing the values back to a sensible range that don't produce a NaN.

**Comment by shiftyscales** [comment]
Modulate speed multiplier can also be set to 0 which makes the laser nearly impossible to use to recover the laser settings to sane values.

**Comment by Frooxius** [comment]
Should be fixed in 2020.5.8.141 thanks!
