### ISSUE TITLE
Physical touch with the fingertip is inconsistent / unreliable

### ISSUE THREAD

**Issue by LewisSnow** [Frooxius/NeosPublic#510]
Im finding it incredibly difficult to properly press or trigger interactive objects with my fingertip (TouchTip Source). Either its because its looking for a specific direction to press in or its not placed properly.

Configuring the touchtip source is a little confusing seeing that there's no visual reference for where its is and what direction its facing. Sometimes I'd have to stick my entire hand into a button to get it to press, even then its not consistent. I've tested on several avatars and still its the same gamble on where it is and what direction I need to press in.

Having say a collider base touchtip or a easier way to set it up would help. Or go back to using way the old tool anchors interacted physically, or something like that. I dont quite know how it worked originally but I know it was pretty accurate with collisions/physically  interacting.

**Comment by Frooxius** [comment]
Can you send me any sample avatars that have a problem with this? I heard that it's difficult for some people to use, but without an example I can't investigate what's wrong.

**Comment by LewisSnow** [comment]
I'll send you one once Im back In Neos!

**Comment by Frooxius** [comment]
Turns out it was because of scaling of the touch distances being affected by avatar's scale. In 2020.5.18.573 the distances are now scaled from the user's space, which should make it consistent across avatars. Thanks!
