### ISSUE TITLE
Odd audio behaviors

### ISSUE THREAD

**Issue by LewisSnow** [Frooxius/NeosPublic#511]
After the new audio spatializer change. I've noticed more frequent popping and audio cutting out. 
For instance, my home world, that has only ~8 audio reads and ~50 empty, now can only play less then before. Before the update it was fine, all audio sources were being played and were audible. After, its cut down the amount that can be heard and wont allow any other sounds to be heard. 

The popping I noticed happens when theres lots of voices, general audio sources, users, lag.

**Comment by ProbablePrime** [comment]
@LewisSnow Has this been cleared up since the audio engine changes recently?

**Comment by LewisSnow** [comment]
unmmm unsure, i havent had any issues recently
