### ISSUE TITLE
[Feature Request] [Logix] Server Sent Events

### ISSUE THREAD

**Issue by Earthmark** [Frooxius/NeosPublic#512]
Similar to #430 but for server sent events, the theoretically less complicated form of websockets.

SSE is built on top of http instead of a different stack so most of the behavior is the same, it's also text based to start with (which is a pro or a con, you decide).
This would make the logix entry ports (probably) connect, disconnect, url, and justification.
The exit nodes would be on sent, on message (that fires multiple times), message, on error, and on close. This is pretty close to the http ones so there's reasonable parity. The negative is they're less featured web sockets. Binary is a problem, and it's one directional, however for real time web logix it may be a good alternative with less funky edge cases than websockets.

The big downside though is C# support for them is garbage and would likely require custom code, but the protocol is not all that complicated.

**Comment by Frooxius** [comment]
Is there a reason why would you want those over WebSockets? I think it's best to just implement those, given how well supported they are.

**Comment by Earthmark** [comment]
Less edge cases streaming wise and protocol translation wise (like dealing with protocol upgrade and all that jazz), also dealing with message delimiting, or lack of delimiting. I see SSE as very cut down versus websockets, but it's much more approachable for about the same reason.

I guess as an analogy it's like websockets are using components and adding empty nodes to the asset tree directly, where as SSE is like having a tooltip for one of the most common jobs that doesn't do everything, but makes that one time much easier.

**Comment by Frooxius** [comment]
Hmm, I'm not quite sure. We're not likely to support multiple protocols soon and it seems that WebSockets would still be best bet because of the wide support and support for binary.

**Comment by Earthmark** [comment]
Totally understand, I threw up an issue for http/2 as well just for totality, as I believe those are the main contenders, just wanted to be sure the other protocols were considered.
