### ISSUE TITLE
[Feature Request] [Logix] http/2

### ISSUE THREAD

**Issue by Earthmark** [Frooxius/NeosPublic#513]
As another alternative to #430 and #512 , http/2 supports bidirectional streams over at least a variant of http.
This would resolve the multiple protocol issue of websockets requiring more complex server routing and provide the flexibility lacking in SSE, the big downsides I see are the encryption requirement and complexity of streams, but the encryption can be opted out of most of the time for localhost or such, and at easiest it's normal http, at worst it's no worse than web sockets (although I'm not sure it includes an end of message flag like WS).

Implementation support is also less wide spread than websockets, but may be better than SSE.

**Comment by Earthmark** [comment]
Http/2 resolves a few other issues as well, but they are slightly more use case based as I understand it, where as these are the big headliner features I see.

**Comment by Frooxius** [comment]
I'm not entirely sure how would this integration look like. It seems like you want more low level access to the protocol rather than running regular web requests? That might be a possibility eventually, but it'd be very long term right now.

**Comment by Earthmark** [comment]
I'm saying with http/1.1 yes it's one to one with the server and a secondary protocol like websockets is required, but with http/2 it's built in to have that kind of support, so a secondary protocol isn't required.
API wise it'd be the same as either normal web request if it's one to one, or it would be the same API as a websocket in streaming.
A lot of the side benefits are transparent ish, like how it routes traffic through a single connection even though it looks like multiple but to consumers that doesn't look different in either case.

**Comment by Frooxius** [comment]
That's actually handled at the API level. Neos doesn't really implement those protocols by itself, but relies on the support in .NET framework and underlying network stack.

**Comment by Earthmark** [comment]
Sweetness, I'm curious how they expose the streamyness, haven't poked at the http2 support in c# too much, but I'm curious how they would handle the kind of bidirectional stream it provides. I've used grpc over c# before but that has a lot of layers under it and I think does it's own web stack

**Comment by Frooxius** [comment]
It doesn't really seem directly exposed. You just provide a different handler to the HTTPClient and it uses HTTP/2 under the hood for the requests, but you don't have access to the raw protocol.

I think this is very unlikely to be added for that reason, it's not really a protocol you use yourself at low level.

**Comment by Earthmark** [comment]
Ok, I'll need to do more research on my own here. My understanding was it provides some way to do more complex streaming systems.

Thanks for the consideration.
