### ISSUE TITLE
Using a tool on an empty avatar forces you to equip it

### ISSUE THREAD

**Issue by ProbablePrime** [Frooxius/NeosPublic#514]
1. Choose a tool that has a laser such as the InspectorTip, ComponentCloneTip etc.
1. Spawn an avatar in the world
1. Equip and Aim your chosen tool at it
1. Press primary action on your controller, instead of the tool activating you'll instead equip the avatar

**Comment by Frooxius** [comment]
Should be fixed in 2020.5.8.141 thanks for the report!

**Comment by ProbablePrime** [comment]
A 1 hour turn around on a bug is fantastic froox :D, I'm sure it was most likely just good timing on my front as you prepared this awesome build
