### ISSUE TITLE
[Feature Request] Expose Additional Anti-Aliasing Techniques

### ISSUE THREAD

**Issue by Enverex** [Frooxius/NeosPublic#517]
Currently Neos apparently uses FXAA but this is very basic and doesn't work particularly well in many situations, it's main benefit is that it's cheap.

I'd like to request that the additional AA techniques that Unity supports on the deferred rendering pipeline be exposed - especially for those of us that for some reason or another are experiencing significant aliasing issues. Perhaps in the Neos configuration window (where you can set the extra DLLs, etc).

As well as FXAA, Unity's current renderer should also support SMAA (basically FXAA but better) and TAA.

Some examples of the current aliasing issues we're looking to negate or at least make less jarring:
![image](https://user-images.githubusercontent.com/958670/81417810-ab3d9e80-9143-11ea-9380-ae3a73392368.png)
![image](https://user-images.githubusercontent.com/958670/81417856-bb557e00-9143-11ea-8980-d1239f15d15a.png)
![image](https://user-images.githubusercontent.com/958670/81418028-f8ba0b80-9143-11ea-9c8e-2022b7f2e5d0.png)
![image](https://user-images.githubusercontent.com/958670/81418314-65cda100-9144-11ea-86e5-f0b6ee19f1e6.png)

**Comment by shiftyscales** [comment]
This has already been asked for via issue #322. So I'm marking this one as a duplicate.

In order to make changes to the rendering pipeline, architectural updates need to be made to the engine to report them to worlds.

For this, we also need a UI to change these settings.
