### ISSUE TITLE
[Feature request] [logix] R/W Bitmap Image Pixels

### ISSUE THREAD

**Issue by Earthmark** [Frooxius/NeosPublic#518]
The ability to create textures with logix (slowly over time) or modify existing textures such as drawing on them with a pen would be useful for complex programmatic effects and the forementioned style of note taking.

I'm not sure how the neos pipeline handles this kind of data so this may be a horrible idea! Replication wise I'm not sure how this would be handled, but my goal is to request things that are pie in the sky!

I'm also not sure how this would apply for different formats of images, but my understanding is they're converted to bitmaps at some point (witch is the goal of this request, modifying bitmaps).

PS: this is totally not so I can make a memory buffer that's not copy on write like a string is, no sir... That being said the ability to support a high data rate would not be turned down, and preferably making sure it still works for images not currently rendered.

PPS: this would also add support for image based heightmaps! (The static terrain kind, not the character drawing fuzz kind, see World Machine, I don't believe neos has an image to model pipeline right now).

**Comment by shiftyscales** [comment]
This has already been requested in #365. Marking this as a duplicate.

**Comment by guillefix** [comment]
I think this is not exactly the same as #365. #365 Only request read functionality, while this one request both read and write. 
Perhaps it still makes sense to merge them, but we should mention in the other one that write functionality is also desired.
