### ISSUE TITLE
Spectators can grip references to slots in open inspectors

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#520]
This leaves the reference floating in the world, requiring it be manually deleted by the world creator.

Experienced by myself, and Beaned#6969 while inside of bobotron#5410's world.
![image](https://user-images.githubusercontent.com/54213390/81481064-46855100-91e2-11ea-9ff4-e7d467c8090c.png)

**Comment by Frooxius** [comment]
Can you send me log from this case please?

**Comment by Frooxius** [comment]
Should be fixed in 2020.5.9.1126, thanks for the report!
