### ISSUE TITLE
"Place Tooltip" does not appear for brushes interacting with toolshelves

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#521]
Prior to the new lasers, a dark blue "Place Tooltip" laser would appear for brushes that otherwise did not use the lasers in order to place them on the toolshelf.

This interaction is not currently possible with the new lasers, rendering it impossible to place your art brushes on the toolshelves.

Issue reported by Anomalous#0699.

**Comment by Frooxius** [comment]
Fixed in 2020.5.12.521, thanks!
