### ISSUE TITLE
Node browser pin button can't be pressed with Logix tip equipped

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#524]
Steps to replicate:
- Equip a Logix tip
- Open the node browser
- Attempt to press the pin button

Observations:
- The pin button can't be pressed
- The laser is red (grabbable)
- With no tooltip equipped, the pin button works as intended without issue

This issue was initially reported by orange#1901 and the exact replication steps were confirmed by H3BO3#7957.

**Comment by Frooxius** [comment]
Should be fixed in 2020.5.10.1362 thanks!
