### ISSUE TITLE
HTTP GET String network node should send a user Agent in its request

### ISSUE THREAD

**Issue by mralext20** [Frooxius/NeosPublic#525]
this will allow for server operators to identify that a request is coming from Neos, and block or otherwise handle it in a different way.

**Comment by AdmiralGhoster** [comment]
this would be a great way to make a webserver accept neos request and limit to block off other access to the rest of the internet

**Comment by Frooxius** [comment]
I can add this, but I would strongly advise using this as a security measure for blocking requests, it's really easy to spoof the user agent. It can be good for some statistics feedback.

**Comment by ProbablePrime** [comment]
- Handling Requests Differently: YES
- Statistical Gathering: YES
- Security: NO

Agreed :D

**Comment by shiftyscales** [comment]
Added in 2020.5.11.410.
