### ISSUE TITLE
Logix Tool placing on  tool shelves regression

### ISSUE THREAD

**Issue by mralext20** [Frooxius/NeosPublic#527]
https://cdn.discordapp.com/attachments/439422161657135106/709183583243206696/2020-05-10_15-19-44.mkv

the tool tip lazer seems to ignore the tool shelfe surface. 

  
regressing between v 2020.5.9.1126 and 2020.5.10.1362

**Comment by TehTurk** [comment]
https://streamable.com/01m4ol

**Comment by shiftyscales** [comment]
As additionally mentioned in #528, this appears to occur on other tips such as GrabbableSetter.

**Comment by shiftyscales** [comment]
Fixed in 2020.5.11.410.
