### ISSUE TITLE
Locomotion setting made persistent between locations

### ISSUE THREAD

**Issue by riftopia** [Frooxius/NeosPublic#53]
It is not inviting to explore other locations if this means you have to reselect your locomotion method of preference (such as sliding) each time when arriving at a new location. It should be persistent between locations.

**Comment by sirkitree** [comment]
I noticed this too yesterday and forgot to log it. Thanks @riftopia !

**Comment by Frooxius** [comment]
Wanted to do this one for a while, but always forget. Done, pushed to nightly channel. Thanks for report!
