### ISSUE TITLE
Request: Add a configurable distance offset to "Smooth POV" on the streaming camera

### ISSUE THREAD

**Issue by ProbablePrime** [Frooxius/NeosPublic#531]
I've recently moved around my head proxy on my avatar for personal and stylistic reasons.

Now however my "Smooth POV" camera can sometimes endup being slightly too far away from my head. I tried to manually adjust its distance so that it was closer but this doesn't work as the Camera is manually calculating its distance from my head and adjusting its own transform. 

I also tried the "Distance" slider on the camera settings but this doesn't affect Smooth POV.

Therefore I'd like to request some sort of offset option.

Note: Field of view is not suitable, it distorts things too much for Tutorials.

**Comment by Frooxius** [comment]
Added in 2020.5.12.521, hope it helps!
