### ISSUE TITLE
Normal Maps No-Longer Working on Terrain Splat Shaders

### ISSUE THREAD

**Issue by Enverex** [Frooxius/NeosPublic#532]
Likely tied into the recent Normal Map compression changes, but the normal maps on the splat shaders no longer work. They show up correctly in the material, but the terrain itself is devoid of any normal mapping. Examples below.

![image](https://user-images.githubusercontent.com/958670/81692176-e565b380-9455-11ea-967d-03fb0531ded0.png)

![image](https://user-images.githubusercontent.com/958670/81692224-fadadd80-9455-11ea-81b0-1df50367eff0.png)

![image](https://user-images.githubusercontent.com/958670/81692739-c1ef3880-9456-11ea-981c-2f8c668056da.png)

**Comment by Frooxius** [comment]
You need to unmark those textures as normal maps and have them as regular. Since they're 2 packed normal maps into one, you can't use the normal map packing/compression for a single map with these as it destroys the information present in them.

I've double checked the PBS Color Splat material and it shouldn't be marking those maps on itself, so they were likely marked either by some other material or manually before.

**Comment by Enverex** [comment]
I will have marked them as normal maps when they were set up before, because they were ;)

Does that mean though, that all splat shader normal maps in all my worlds will be broken and need to be reuploaded, or do they simply need to be unchecked and they'll fix themselves?

**Comment by Enverex** [comment]
Still nothing. Also in the most recent world, I actually attached the normal maps to the splat before enabling the normal map option (which in turn turned them pink) and they had no effect before I enabled that option as well as after.

**Comment by Frooxius** [comment]
Technically they're not actually pure normal maps, so this option doesn't fit for them. 

You don't need to reupload anything, just uncheck the "IsNormalMap" on them and resave. The original files are still kept.

That's odd though in the second case. Are they making no visual impact on the material? As in none at all, no matter what you put in there?

**Comment by Enverex** [comment]
Zero impact like the slot is dead.

**Comment by Frooxius** [comment]
Should be fixed in 2020.5.13.642, thanks for report! The "IsNormalMap" still stands though, needs to be off for those.

**Comment by Enverex** [comment]
This doesn't appear to be fixed unfortunately. Normals are assigned and "isNormal" isn't ticked (so normal maps look like the old style, not pink) but there is zero normal map effect applied to the terrain.

**Comment by Frooxius** [comment]
I cannot replicate this, normal maps work correctly for both PBS Color Splat (both Metallic and Specullar) and produce a visual effect. Are you sure you were on the latest build when you tested this?

**Comment by Enverex** [comment]
One example on a map that previously worked fine. The normal map is just making the terrain dark and not actually having the expected effect.

Without map:
![image](https://user-images.githubusercontent.com/958670/82191770-ee89d100-98ea-11ea-8dc2-a6248c1e6668.png)

With map:
![image](https://user-images.githubusercontent.com/958670/82191779-f34e8500-98ea-11ea-88fe-e9696b7ffb17.png)

As you can see it's added no depth, just made the terrain uniformly darker.

Close-up of the details:
![image](https://user-images.githubusercontent.com/958670/82191838-0b260900-98eb-11ea-81f9-4ec5b5f82dd0.png)

I do have one world where this does work though, the only difference is that it was created after the normal map change.

**Comment by Frooxius** [comment]
Hmm that's strange. Can you open the target _shader property on the PBS_ColorSplatMetallic and check if the URL on the StaticShader component says `neosshader:///NeosPBSColorSplat_v2`?

**Comment by Enverex** [comment]
Looks fine... "neosshader:///NeosPBSColorSplat_v2"
![image](https://user-images.githubusercontent.com/958670/82193280-18dc8e00-98ed-11ea-8118-19fc4e9dc63d.png)

**Comment by Frooxius** [comment]
Hmm. Is there any other difference between this world and the other one where it works? Or on the material itself? 

What if you create a blank instance of the material and apply the same textures, does it exhibit the same behaviors?

**Comment by Enverex** [comment]
I've found the problem. Changing the normal scale above 1 very quickly reduces it to nothing. At 2 or above the normal disappears entirely. Here's the material applied to a flat plane but with the texture removed to make the normal map more obvious. Here's 1,1,1,1...

![image](https://user-images.githubusercontent.com/958670/82195370-1cbddf80-98f0-11ea-9199-792e102483cf.png)

Here's 2,2,2,2...

![image](https://user-images.githubusercontent.com/958670/82195410-2e06ec00-98f0-11ea-95a3-3deffdbc7291.png)

Higher numbers (e.g. 3) continue to show nothing.

**Comment by Frooxius** [comment]
Oh I see! I'll have a look into that, thanks for the info!

**Comment by Frooxius** [comment]
Okay, pushed a fix, the scaled normal map unpacking code was wrong, should be good in 2020.5.18.573, thanks!

**Comment by Enverex** [comment]
Looks good, thanks.
![image](https://user-images.githubusercontent.com/958670/82205969-4df1dc00-98ff-11ea-865e-659f138b9b34.png)
