### ISSUE TITLE
3rd person view when VR Rift 

### ISSUE THREAD

**Issue by Ardescar** [Frooxius/NeosPublic#533]

**Comment by Ardescar** [comment]
- i pressed enter - it opened it ... aRRGggh sorry

**Comment by shiftyscales** [comment]
If you are still having this issue, and have tweaked your laser smoothing settings, try resetting them to the following defaults:

SmoothSpeed 5
SmoothModulateStartAngle 2
SmoothModulateEndAngle 45
SmoothModulateExp 0.75
SmoothModulateMultiplier 8
StickThreshold 0.2

**Comment by Ardescar** [comment]
Thank you for responding. As you can see - this is what i ended up - mostly then when the VR-HS probably did lose contact or i had to replugin the VRHS to the pc.

I use Rift S and sometimes rarely when i am going afk and i return something is wierd with the Rift Software. In some cases i did replug the whole system while neos active. Then this happened.
Everything works - but its really a 3rd person view. 

![OculusScreenshot1589230226](https://user-images.githubusercontent.com/63201013/81849811-5ccf3c00-9557-11ea-8e6e-42402870b927.jpeg)

![OculusScreenshot1589230016](https://user-images.githubusercontent.com/63201013/81849793-550f9780-9557-11ea-85d9-d7febecdca8f.jpeg)

**Comment by Ardescar** [comment]
I did not write again in this issue because i ... guess its not a problem from neos. I guess its only from rift software.

**Comment by shiftyscales** [comment]
Oh I see. Yeah. It's a really strange issue that comes up only for Oculus headsets. If they get disconnected, and reconnected, that can happen.

Restarting Neos fixes that issue, though. Either way, thanks for the report!
