### ISSUE TITLE
[Bug] Various UI elements respawn user on laser grip to physical grip

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#536]
Steps to replicate:
- Grab a UI element with a laser, e.g. the session menu (reported by Coffee), or the avatar creator proxies (reported by GearBell)
- Use the joystick to pull the object in to your hand to physically grab it

Observations:
- The user is respawned
- In the case of gripping private UI such as the session menu, the user is separated from their local space avatar

[SHIFTY-PC - 2020.5.12.521 - 2020-05-12 16_14_07.log](https://github.com/Frooxius/NeosPublic/files/4619852/SHIFTY-PC.-.2020.5.12.521.-.2020-05-12.16_14_07.log)

**Comment by shiftyscales** [comment]
Also occurs on the camera/streaming window, and likely elsewhere. Marking this issue as high priority.
[SHIFTY-PC - 2020.5.12.1285 - 2020-05-12 23_13_27.log](https://github.com/Frooxius/NeosPublic/files/4620154/SHIFTY-PC.-.2020.5.12.1285.-.2020-05-12.23_13_27.log)

**Comment by Frooxius** [comment]
Fixed in 2020.5.13.642 thanks!
