### ISSUE TITLE
Single click slot navigation in inspectors

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#538]
Single clicking on a slot could highlight, and view the contents of a slot, reserving the double click for selecting a slot/generating a gizmo.

This would allow for quick navigation between slots to view their contents (cutting down the number of clicks required to browse through inspectors by approximately half), and would also prevent gizmos from appearing at undesirable times.

Suggestion made by GearBell#5112.

**Comment by Frooxius** [comment]
Sorry, I don't plan on implementing this, it wouldn't fit with the design and the systems. Gizmos are inherently linked to the inspector and using single/double click as separation is not a good choice there.

I have plans for a proper selection system later on. Having options to decouple inspector from gizmos is a possibility for this too. Single clicks for accessibility perhaps too, but it could cause a lot of accidental clicks, but that will be a more general thing.
