### ISSUE TITLE
Import multiple files at once

### ISSUE THREAD

**Issue by sirkitree** [Frooxius/NeosPublic#54]
Motivation: I have a collection of models in a directory structure. I'd like to be able to import them all in one go. 

It would be great if I could grab a folder in the file explorer, pull it off, and hit import. I envision this giving me two options:
1.  **create import spheres**: creating a new import sphere for each file as it traverses down the directory
1. **import all as**: creates the import dialog that will import all files with a particular set of options. You could choose 'model' or 'image' and then the resulting options for either one of those, but not both.

Caveat: in case one tried importing the entire hard drive from the root (like C:) by accident or another directory that was too large, there should be a way to cancel this operation. Maybe check that all the files that are to be imported are the same extension, or check file size, or maybe even do a maximum number, like 50 or so.

**Comment by Frooxius** [comment]
I'd actually want to extend this a bit more and create a wizard for importing whole folders. Essentially it would offer you several "handlers" for the folder. 

Two of them could be the "generate import spheres", which would do it individually for each importable file and another that will import everything with the same import settings.

There could more more however. For example importing a set of image files as 3D volumetric texture, so when you have an MRI scan as discrete JPG image slices for example, it would assemble them into a 3D texture for you.

**Comment by Frooxius** [comment]
Done and pushed to nightly channel. It now has support for importing folders. You can register new folder importers in  your plugins by declaring a static method and adding the [FolderImporter("Name", "Description")] attribute.

The method needs to have void Method(Slot root, string folderPath) signature.
There are two folder importers included now, one that does batch import (same settings for multiple 3D models images or videos) and individual import (spawns an importer wizard for each file).
