### ISSUE TITLE
Toolshelf NotAllowedToEquip Wont Show when You Don't have Permissions

### ISSUE THREAD

**Issue by TehTurk** [Frooxius/NeosPublic#542]
Trying to equip from Toolshelf before grip change your have a notification appear there, having it deny/error which equipping from a toolshelf would be a nice return. You can see when equipping a tooltip in normalspace, but not from toolshelf space.

**Comment by shiftyscales** [comment]
Can you clarify what you mean? I'm having a tough time understanding what you're describing.

**Comment by TehTurk** [comment]
Try equipping a tooltip in a world where you don't have Permissions. You won't be able to and you'll be notified, this won't be the same on equipping a tooltip directly from a shelf.

**Comment by Frooxius** [comment]
I understand the issue, will fix soon! Thanks.

**Comment by Frooxius** [comment]
Fixed in 2020.5.18.573 thanks!
