### ISSUE TITLE
Haptics for TipTouchSource

### ISSUE THREAD

**Issue by H3BO3** [Frooxius/NeosPublic#544]
Recently with the laser physical tip touching being removed and fingertip touch sources taking over completely (which never had any haptics to begin with) all physical touch interaction haptics are gone, the most disappointing effect of that being the inability to feel physicalbuttons. Requesting that haptics for physical/tip touches are re-implemented.

**Comment by Frooxius** [comment]
Fixed in 2020.5.18.573, physical touch should have haptics now!
