### ISSUE TITLE
Expose Directional Light Range & Cascades

### ISSUE THREAD

**Issue by InsaneGrox** [Frooxius/NeosPublic#546]
So I have a few reasons for wanting these at some point, not just the whole "shadow cascades allow longer shadow ranges", one major thing I found was the default shadow cascading (yes neos has a single cascade) causes noticable artifacting with shadows that are a lower resolution then 1024x1024
though among this there are plenty of other reasons to want shadow cascades, generally being high preformance good looking shadows, where shadows look super sharp up close without having to have the resolution be 8192x8192, further shadow range, ect.

Fun fact: I checked, I'm actually impressed this wasn't already an issue here...
EDIT: there's no issue about reflection probes either? wow, yeah those too whenever you can get around to it.

**Comment by Frooxius** [comment]
This is planned with the render settings. We already have issue for this here, closing this one as duplicate: https://github.com/Frooxius/NeosPublic/issues/322
