### ISSUE TITLE
AvatarAnchor rotational reset option

### ISSUE THREAD

**Issue by H3BO3** [Frooxius/NeosPublic#551]
Currently all AvatarAnchor exit options seem to use a complete transform restore, which, when using a localspace anchor in fly mode and then having that anchor get rotated before leaving, results in the rotation being left on the user. I suggest a checkbox to restore an upright global rotation based on facing direction as supplement to the various restore modes.

Alternately, current restore modes could be changed to only affect the restore position, with rotation restore being split off and having its own dedicated set of modes for more flexibility.

**Comment by Frooxius** [comment]
Added PreserveUpOnExit  option (on by default) in 2020.5.18.573, thanks for logging this!
