### ISSUE TITLE
Incorrect cursor positioning on TextEditor when using ValueCopy with WriteBack

### ISSUE THREAD

**Issue by Anomalous** [Frooxius/NeosPublic#552]
I'm having some trouble with the ValueCopy component with WriteBack enabled, attached to a text editor. It works fine if you edit text by positioning the cursor using the arrow keys first, but if you clear the text and start typing, or start typing at the end of existing text without positioning the cursor, it inserts the first character, moves the cursor to the left of it, then continues typing as normal. This results in the first character you type being at the end of the string.

I'm not sure if this is a bug, or just some behavior I'm not understanding. I'd like to know how to fix it though, because for the project I'm working on I need to have the same text data displayed in multiple text fields and editable from any one of them. I could probably work something out with LogiX and dynamic impulses, but this method is so much simpler and cleaner except for this weird cursor behavior on the on the first character typed.

Video linked because it's a rather confusing issue to explain.
https://youtu.be/Tv1crD87nQU

**Comment by Anomalous** [comment]
Whoops, forgot to write specific reproduction steps for the GitHub issue. 'watch video' is not a good instruction.
1. Set up a TextRenderer, TextEditor, and TouchableTextField so you can edit the text by clicking in it.
2. Create a ValueField<string> component to act as the source of the string to display and edit.
3. Create a ValueCopy<string> component copying the data from the ValueField into the TextRenderer's Text property, with WriteBack enabled.
4. Click on the text to edit it. Observe undesirable cursor behavior.

**Comment by Frooxius** [comment]
Tweaked the behavior of ValueCopy in 2020.5.18.573. It wasn't updating the TextRenderer field immediately, which confused the TextEditor. Should work well now. thanks!
