### ISSUE TITLE
Option to not show harddisk content

### ISSUE THREAD

**Issue by riftopia** [Frooxius/NeosPublic#56]
Am I mistaken, or is there a feature where you can access the folders on your harddisk inside NeosVR in such a way that others can see it as well? If so, it may be good for reasons of privacy if there were a setting to make the folder names or the whole panel invisible to other users. At the very least, users should know beforehand what they are about to share.

**Comment by sirkitree** [comment]
I had this same concern when someone popped into my world and was able to navigate my hard drive in the file explorer.

There is an option on the main menu that you can use to quickly spawn a private world that is dedicated to just your file browser. You can pull files off of there and then teleport back to the world you want to import it into, carrying the import orb with you.

However, I agree that it would still be a good idea to let uses know when using the Import tool tip that others may be able to browse their hard drive if in a public space.

**Comment by Frooxius** [comment]
What do you think would be adequate warning? Just ask them the first time they're about to use it? Or do that every single time they want to open it?

**Comment by Frooxius** [comment]
Hmm actually there's another idea I've been thinking about, make certain GUI's "Userspace" by default. Meaning it'll be private. But they will have option to make them public, by clicking a button on the UI, which will transfer them from Userspace to the world you're in, so you can show it to other users.

This would make it implicitly private, even if you're in a public world.

**Comment by sirkitree** [comment]
> This would make it implicitly private, even if you're in a public world.

This would be most excellent 👍

**Comment by Frooxius** [comment]
This is now implemented and available in the public channel.
