### ISSUE TITLE
[Tweek] More control over "Play One Shot"s

### ISSUE THREAD

**Issue by LewisSnow** [Frooxius/NeosPublic#563]
Being able to change: 
Min/Max
Doppler
Falloff type
priority
Would be nice to have, Im running into a case where the min/max and doppler would be really handy.
This will avoid having to create your own play one shot system with said settings changed when a one node can do the same thing.

**Comment by Frooxius** [comment]
Hmm I can add a few of these, but generally this needs component access, because there are more properties an more to come and the node would get unwieldy. I could add priority and doppler to the node itself for now if that would help?

**Comment by Frooxius** [comment]
Ok I've added all of them in 2020.5.21.377!
