### ISSUE TITLE
Exception on deleting world using world orb

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#567]
Attempting to delete a world orb will generate an exception, and will not delete the world.
Reported by ChrisWarner103#8178 and Enverex#6528.

[SHIFTY-PC - 2020.5.21.377 - 2020-05-21 11_31_04.log](https://github.com/Frooxius/NeosPublic/files/4664116/SHIFTY-PC.-.2020.5.21.377.-.2020-05-21.11_31_04.log)

**Comment by Frooxius** [comment]
Fixed in 2020.5.22.993, thanks!
