### ISSUE TITLE
Additional protection against accidental world deletion

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#568]
Requested by PeterTheThinker (KG6LSE#0881).

With the new context menu on world orbs, deletion of worlds has become considerably easier. There is no longer a timeout for the deletion as there was with the previous system.

Peter's concern was primarily on the number of clicks required (3 total- two from the time the context menu is open). I (Shifty) believe that having a pop-up prompt with a few second timer like with outgoing links could be a preferable means to signify intent.

Being on a context menu, there is the potential for mistaking the deletion as being related to the way you remove an object from the world by gripping it. Additionally, with flicks enabled by holding the trigger when clicking on the world orb- the world deletion is actually only one click away (plus two flicks.)

Perhaps it might also be worth reconsidering how worlds are managed going forward into the new UI, as requiring the world orb to delete the world could also be seen as redundant/unnecessary if you can manage the worlds more effectively from a UI panel.

**Comment by Frooxius** [comment]
Flicks are disabled for this operation already. I can add extra confirmation step with the button in a different spot if that helps for now.

Having UI for world management is planned.

**Comment by shiftyscales** [comment]
If it's a quick/easy change to make, and you are personally satisfied with the solution you come up with, then by all means, feel free.

I don't think there is any specific immediacy/urgency for this issue, as I can't say I've personally heard of any cases of anyone accidentally deleting a world yet. The nearest I've heard is Peter saying he almost had the once.

World management UI will be much appreciated in the future once we get there, thank you!

**Comment by Frooxius** [comment]
Yes. One thing I'm also planning in the future will be a "Trash Bin" functionality. Where things don't actually get deleted until let's say 14 days later (would be configurable).

**Comment by Frooxius** [comment]
Oh also I should note, since we now have record audit system, if anyone accidentally deletes something important, let us know ASAP, so we can restore it. It takes a bit of work, but can be done in emergencies.

**Comment by patrice-rey** [comment]
Hello Frooxius, this is Neosmotic. Last night I lost a world. From Worlds -> My World, I spawned its orb. From there, a trigger pull on the orb puts you on the path to "Destroy" the orb (not the world). However, I did a grasp squeeze which put me on the path to "Delete" the entire world. For half a second I did found the confirmation to delete unusual, but I executed the Delete anyway. Deleting a world and deleting an orb should not be so close to one another. 
Is there a way to recover a deleted world? The deletion happened during the education meeting hosted by Hamish (SHRF). The world I deleted is called "Geological Mapping". Deletion occurred around 15:00 UTC (around 1 am Sydney time). I have been working on this world for about 3-4 weeks, a virtual geological mapping exercise for our undergrads. Hope you can help. 

1

**Comment by shiftyscales** [comment]
This was added in 2020.6.5.201.
