### ISSUE TITLE
"AlwaysPromptUser (bool)" on Request Host Access node

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#569]
Requested by Ghoster#2597: a bool added to the request host access node to always prompt the user of an outgoing connection regardless of if they have previously allowed the web host.

**Comment by Frooxius** [comment]
Sorry, but this won't be added. There's not much point to this, since the requests are already allowed to go through and this could lead to some really bad/confusing patterns, where user is prompted for certain requests to the host, but not others (since they can just go through silently already).
