### ISSUE TITLE
[Bug?] Trajectory node resetting after an amount of time.

### ISSUE THREAD

**Issue by LewisSnow** [Frooxius/NeosPublic#573]
I've noticed when simply plugging in an elapse time/stopwatch (and the other values needed), after 20 or so seconds it hits "Infinity" then "Nan".

Mind you these values were

InitialVelocity: 0, -200, 0
Gravity: 0, 0, -20
Drag: 8
Time: Both a Elapse time and Stopwatch were attached here.

It may have to do with negative numbers, I'd have to test more.

**Comment by Frooxius** [comment]
That's technically not a bug, it's just accelerating so fast that it reaches positions so far away, that it gets out of range of the floating point numbers.

I suggest using lower acceleration values or clamping it after certain amount of time.
