### ISSUE TITLE
Shadows Wrong on Terrain Splat Shader in Mirror with Directional Lights

### ISSUE THREAD

**Issue by Enverex** [Frooxius/NeosPublic#574]
Bare with me on the title as it's a chain of requirements:

If you go to a world using the terrain splat shader and open a mirror, if that world has any directional lights, the shadows from those lights appears to be in screenspace as it moves around based on your head in a completely crazy fashion. That obviously makes it hard to screenshot, but here's an example:

Here's how it should look (PBR Metallic):
![image](https://user-images.githubusercontent.com/958670/82714047-fe0b7000-9c84-11ea-843c-c1f58f90911c.png)

Here you can see the entire shadowmap moving where I turn my head (PBR Splat):
![image](https://user-images.githubusercontent.com/958670/82714105-2b581e00-9c85-11ea-805e-4679f26040a1.png)

**Comment by Frooxius** [comment]
When did this start happening? Was it behaving correctly before?

**Comment by Enverex** [comment]
I honestly couldn't say when it broke unfortunately, as I personally rarely use mirrors. I can narrow it down to saying it worked fine months ago, but nothing more specific than that. If anyone's used mirrors in any of my worlds (with landscapes) could chime in with a better timeframe then that would be appreciated.

**Comment by Enverex** [comment]
This was fixed as part of another bug regarding reflections on PBR shaders.
