### ISSUE TITLE
Set "Normal" audio when Joining Session/World.

### ISSUE THREAD

**Issue by Reiko9** [Frooxius/NeosPublic#578]
Frequently I and other players are using Broadcast mode in one world/session and then forgetting to shut it off Before joining a different session/world.

   This has both annoyed other players and been overall embarrassing...
Hopefully this is an extremely simple tweak to Not save Broadcast mode when leaving a session/world...

**Comment by ohzee00** [comment]
I'd say a simple solution would be to simply make it so voice settings(broadcast/normal/whisper) do not transfer between active sessions, making each session have their own independent setting for being broadcast, normal or a whisper. 

So for example if switching to a session where I was on the Normal voice setting but had Broadcast enabled in the previous session, it would simply use the Normal voice setting as soon as I enter that session.

**Comment by Frooxius** [comment]
This is not a simple tweak unfortunately. If we did this, it would also mean the user gets unmuted when they switch a world, which is not a desirable behavior.

The voice system will be reworked pretty soon to improve the behavior, where the actual voice mode is per-world, while mute is a global setting.

**Comment by ohzee00** [comment]
Ah, shoot, I didn't consider that, alright. I also didn't know voice was gonna get reworked but that sounds like somethin' to look forward to, thanks!

**Comment by Reiko9** [comment]
At the moment Global Mute + Set "normal" when joining a world may be a simple work-around for the moment.   
   Since if Global mute is enabled, it will block the microphone at a lower level than the current voice settings.

Kinda like how physically unplugging the Microphone prevents voice audio, when "Normal, broadcast, and whisper" modes are selected.

Just this accidental "Broadcast" mode when joining worlds keeps happening frequently enough. that if this work-around is fast and easy to do I know the community would appreciate it.  :)

**Comment by shiftyscales** [comment]
There's not really a lot of point in investing developmental time on a temporary workaround when there is a proper fix planned to be implemented later, @Reiko9. For now, it's best to just remind someone they left themselves in broadcast.

Or for the person to remember to switch their voice mode before changing worlds if necessary.

**Comment by shiftyscales** [comment]
This issue was taken care of by changing the way microphone settings are handled. Muting is now a global toggle, and normal is the default voice mode for all new sessions.

Thanks for the suggestion!
