### ISSUE TITLE
Many DAE models from the 3DWarehouse import with offset/reversed components.

### ISSUE THREAD

**Issue by SHFRH** [Frooxius/NeosPublic#581]
Many DAE models from the 3DWarehouse import with offset/reversed components. On simple models this can sometimes be fixed by manually rotating of flipping the misaligned components (i.e. using a scale of -1 on one axis) but this is not feasible with complex models. 

Possible diagnostically useful information: Sometimes I see very small scale values on import.
Sometimes manually rotating a part with the gizmos make it jump around randomly (similar to gimbal lock). Recently I saw the gizmo rotation axes were not orthogonal.

Attached an example model, import picture and strange gizmo axis picture. Thanks ^H^
[6ftTableand10Chairs.zip](https://github.com/Frooxius/NeosPublic/files/4672760/6ftTableand10Chairs.zip)
![Import](https://user-images.githubusercontent.com/65836538/82743289-994b3500-9dac-11ea-9346-42bda6c95713.jpg)
![gizmo](https://user-images.githubusercontent.com/65836538/82743290-9a7c6200-9dac-11ea-8de0-22220fc0efbc.jpg)

**Comment by Frooxius** [comment]
Fixed in 2020.5.24.1361, it should import correctly now! Thank you!

**Comment by SHFRH** [comment]
Wow - that seems to have fixed import for several million free models! - Thanks, ^H^
