### ISSUE TITLE
Integration of bHaptics TactSuit

### ISSUE THREAD

**Issue by MR-Alex42** [Frooxius/NeosPublic#584]
https://www.bhaptics.com/tactsuit/ is a full body haptics solution gaining momentum  (support for VRChat, Half-Life Alyx, etc.). It runs wirelessly with on all the platforms that NeosVR supports and works nicely together with vive trackers for full body tracking. They are offering a C# SDK and Unity integration.

**Comment by Frooxius** [comment]
This could be added, but we'd need to get a dev-kit for integration to be efficient and well done. Do you know if they offer any dev-kits to developers?

**Comment by MR-Alex42** [comment]
Sure. I'll ask them if they can provide dev -kits to developers.

**Comment by Enverex** [comment]
This is a duplicate of a much older request - https://github.com/Frooxius/NeosPublic/issues/404

**Comment by shiftyscales** [comment]
So it is, thanks, @Enverex. Closing this issue. Please let us know what you find on #404, @MR-Alex42.
