### ISSUE TITLE
Model all jumbled

### ISSUE THREAD

**Issue by sirkitree** [Frooxius/NeosPublic#59]
Here's a screenshot, I'll tap Nexulan to upload the model he was using, but after import some of his models are getting all jumped together. Built in Blender, exported as .dae

![20180501154758_1](https://user-images.githubusercontent.com/28543/39496975-326703fa-4d5e-11e8-9bcd-b8e3fd419304.jpg)

**Comment by Frooxius** [comment]
Oh I forgot to close this one, it's fixed.
