### ISSUE TITLE
Decoupling viewpoint / hearing from the head

### ISSUE THREAD

**Issue by Frooxius** [Frooxius/NeosPublic#592]
Based on discussion with GearBell on the Discord and then others, this addition would open up lots of new options.

Essentially it would let you override where the user sees from and where they hear from (each is independent, but if hearing isn't overridden, then it's same as the seeing point). 

Not only would this allow for some really interesting avatars (e.g. GearBell wants to make a zombie one where you can take the head off), but would open several other options as well:
- Third person view in VR - e.g. briefly when playing animation on an own avatar or for games
- Third person view in desktop mode - this would be necessary to implement the third person view when playing in the screen mode, which is something that's planned for the proper desktop mode rework, so this would provide the framework to implement this nicely
- Changing the audio listener position for the interactive camera - would be useful for streaming and recording, making the spatial audio be relative to the actual camera and not the user.

**Comment by Abysmal2134** [comment]
Something to take into account is how this would affect access to your private UI. I know it can be really hard to access it from a 3rd person perspective, by fooling with anchors and moving my body while in them, or when Oculus disconnect messes up my POV. 
Maybe having an invisible backup avatar that is linked to the viewpoint and where the private UI spawns.

**Comment by Frooxius** [comment]
Private UI would still render at same relative position to you, so that wouldn't be affected. It would actually also show overlay hands, so you can exit the world if you mess up (or get messed up).

**Comment by TehTurk** [comment]
I thought this was also something that would be a very much down the line issue due to being tied to the renderer no? But anything to improve camera controls/setup would be divine.

**Comment by Frooxius** [comment]
I've actually thought of a very simple way to achieve this. It does require modification to the Renderer, but not as complicated one as I thought, so it should come soon!

**Comment by ProbablePrime** [comment]
Thank you!, You have no idea how cool my avatar is going to become with this.

**Comment by Frooxius** [comment]
Hmm there's an important question though. When overriding the user's head viewpoint and rotation, what exactly is actually being overriden? Is the head position/rotation fully fixed? Or can the user still move around from a center point?

If it's fully fixed, this will mean that the user can't look around or move their head, which can be potentially disorienting, but necessary for some effects. Maybe it could be finegrained. E.g. you can override position, but the user can still look around rotationaly.

**Comment by shiftyscales** [comment]
I could see both use-cases as being preferable in certain circumstances, and I think ultimately both styles should be supported.

E.g. "Moss VR" is a platforming game in which you spectate your character moving through the world while also directly interacting with the environment using your hands. So you are free to look, and move (in the confines of your playspace) as you wish.

Constraining the view/locking down the rotation will also be necessary in the context of screen mode/more conventional games/cinematic scenes as that platform wouldn't have head-tracking to freely look around the scene anyway.

Particular to GearBell's proposed use-case, because she wants to look and hear through her disembodied head, it wouldn't make sense if she could move it on its own while it's disconnected from her body.

**Comment by Frooxius** [comment]
Yeah that's what I'm thinking. If the head is grabbed, then the user can't move it. Although this can be a bit disorienting to the user in VR.

It's a bit different with the mode that doesn't restrict the user head motion. It needs a way of specifying the offset, so there's a question of what exactly does the anchor represent there.

**Comment by ProbablePrime** [comment]
Someone just mentioned Whisper mode to me. They had concerns about eavesdropping. How would that be handled?

**Comment by Frooxius** [comment]
You can eavesdrop in different ways already. E.g. setting yourself small and flying in. I would not recommend whisper mode for secure conversations in general, as the audio data has to go through the host (and right now it's not culled), start a private world for that.

Although adding the culling based on actual avatar head position would help in this case. Still, lots of different ways to eavesdrop. 

An alternative would also be another more explicit mode where you select which users can join and hear you. But that's a different feature.

**Comment by ProbablePrime** [comment]
Understood and agree with your sentiment just wanted to ensure it was voiced here.

**Comment by Frooxius** [comment]
Yeah I understand. Technically it wouldn't work anyway with current implementation actually, since it doesn't change the actual head position in the world, so it will still think you're outside of the whisper bubble.

**Comment by Reiko9** [comment]
Great now someone can make a weapon, which makes a players heads spin at high speeds.... Unless this has a permission system, it will be used for trolling and as-is smooth-turning is an awful experience for many...

Although it would make a Guillotine simulator easier, so I guess that is a plus...

**Comment by Hayden-da-Serg** [comment]
Can't believe I didn't see this thread sooner, I tried messing with this idea a while back with camera portals, and while it does work it's quite laggy because camera portals, and the audio is still stuck at my head position. I'd love for my audio specialization to also accurate match my avatar (so I receive audio where my ears are instead of the center of my viewpoint) and it'd be interesting to be able to parent the viewpoint to different places.
I really like the idea, and it could serve for some really interesting creations, can't wait to see where it'll go!

**Comment by TehTurk** [comment]
@Reiko9 Please stay on objective topic instead of rambling in the git threads. I've noticed this the past few weeks you've been picking a thread and then just saying what's on your mind, (without regard to others in the thread or not keeping in mind of the previous said considerations in the thread)

Yeah agreed :)

**Comment by GearBell** [comment]
I had no idea this github existed but this would be SUPER useful for avatars with strange necks or heads that pop off or even if you are in an anchor and want the vehicle/mech/whatever to have a first person viewpoint. GASP! you could even trick your viewpoint into being 3rd person! YES! we need this!

**Comment by ohzee00** [comment]
Hey @GearBell ya should check the latest devlogs! There is something in the works about this:
https://youtu.be/JAaD73E2bAM

**Comment by Frooxius** [comment]
This is now finally implemented in 2021.1.17.998! You can override the root, view and ears in this build, either by directly assigning references or using the new AvatarUserRootOverrideAssigner component:

- Added a mechanism to override the transform of user's root, view and "ears" for audio-visual output, while preserving their actual UserRoot in the world by assigning Slot references on the UserRoot component
-- Note that view should be used sparingly for VR users (if at all) as it will negate any actual head movement which will be dizzying to a lot of users. If you want to create "out of body" experience, override the root instead.
-- The view override can be put on the avatar's head so the view still moves with the head, but using the avatar's motions, but be careful with this as well, as the motion not being 1:1 can cause nausea as well. I STRONGLY discourage using this as standard feature of avatars for adjusting the view (even if subtle) and only recommend it for gimmick avatars and personal use
- Added AvatarUserRootOverrideAssigner (under Users/Common Avatar System) which allows overriding the root, view and ears from equipped avatar (requested by @GearBell, @Abysmal, @ProbablePrime, @Shifty | Quality Control Lead and @Hayden)
-- The component updates in realtime. You can set the Override target to null to disable or change it to a target object to dynamically assign a new target
- Added "Audio from camera viewpoint" setting to Interactive Camera dialog, which will render the audio from the camera's viewpoint (requested by @Nexulan | Community Manager and many users before (sorry I didn't keep a list! ;_;))
