### ISSUE TITLE
[Bug][UIX] Grabbing Canvas with Infinity Properties will make the user Delete themselves

### ISSUE THREAD

**Issue by TehTurk** [Frooxius/NeosPublic#594]
Repro: Set Canvas to Infnity, try to grab anything and you'll respawn due to Infinity/NaN cleanup from a few patches ago.

**Comment by Frooxius** [comment]
What do you mean by "set canvas to Infinity"? Which properties are you exactly setting? Do you have a log from when this happened?

**Comment by TehTurk** [comment]
Ah just the Canvas size. I do not have proper logs put it's completely reproducable.

**Comment by Frooxius** [comment]
I see. I'll try to have a look later. Providing log can help things get faster though, because it can save me a bunch of steps. Sometimes the bugs are obvious from the log alone, so I don't have to go and gather them myself.

**Comment by shiftyscales** [comment]
Reproduced, @Frooxius.

[SHIFTY-PC - 2020.5.24.1361 - 2020-05-26 11_59_59.log](https://github.com/Frooxius/NeosPublic/files/4684448/SHIFTY-PC.-.2020.5.24.1361.-.2020-05-26.11_59_59.log)

Opened a new world, spawned a DevToolTip, created a UIX canvas object, inspected it, and set the X size to "Infinity" then grabbed the inspector.

**Comment by TehTurk** [comment]
Thanks Shifty! And Noted @Frooxius

**Comment by Frooxius** [comment]
Wait, you grabbed the inspector and not the resized canvas?

**Comment by TehTurk** [comment]
It becomes so big if you grab anything within the Colliders range it makes you just *poof* at least from me finding my repro steps.

**Comment by Frooxius** [comment]
Added clamps to the collider sizes in 2020.5.26.1183 that should fix it. Thanks!
