### ISSUE TITLE
Request: Is User Anchored & Get User Anchor Nodes

### ISSUE THREAD

**Issue by ProbablePrime** [Frooxius/NeosPublic#596]
Anchors can sometimes get confusing for users.

In a class Hamish and I taught last night we had a Boat which we used to take the whole class to various points of interest on our map.

For some reason some of the students got stuck in the Avatar Anchors we had placed on the boat and I had to manually remove them from the anchor using some hastily thrown together logix in the middle of a class.

An idea to rectify this would be a system for de-anchoring a user irrespective of what anchor they are actually in. 

I'm aware I could make this for the boat itself but wanted to request these two logix nodes for other scenarios.

These should be viewed as the Anchor equivalents of "Has Tooltip" and "Get Tooltip"

Thank you!

**Comment by Beaned2000** [comment]
These nodes are already available under the node menu Avatar -> anchor
![20200526204816_1](https://user-images.githubusercontent.com/29598202/82938668-74b0b200-9f92-11ea-9195-ba141c6a1706.jpg)

**Comment by ProbablePrime** [comment]
Those nodes take a known anchor and return the status of that known anchor. This request is to get an arbitrary anchor based on a user.

**Comment by H3BO3** [comment]
@Beaned2000 Those are anchor-specific, not user-specific.

**Comment by Beaned2000** [comment]
oh i see my bad sorry

**Comment by Frooxius** [comment]
Coming in the next build!

**Comment by Frooxius** [comment]
Added in 2020.5.26.1183, hope they help!
