### ISSUE TITLE
Grabbable Avatar Pose Filter and Slider integration

### ISSUE THREAD

**Issue by H3BO3** [Frooxius/NeosPublic#597]
Noticed this behavior yesterday - GrabbableAvatarPoseFilter for the purposes of smoothing motion via AvatarPoseSmoothLerp works with grabbable items, but not with Sliders. Or at least the issue was that it did not work with a slider already underneath a grabbable, a tool (bow) specifically. There was already a posefilter on the tool root as well, at this point. The goal was to smooth the motion of the string you pull back, which operates on a slider somewhere underneath the tool root. I'm not sure if this is just a case of the component not working with sliders or if this is a bug with multiple posefilters. If the former, having it cover more grabbable-type components would allow more flexibility.

**Comment by Frooxius** [comment]
Fixed in 2020.5.26.1183 should work now
