### ISSUE TITLE
Hide laser interactions for spectator

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#599]
Hiding laser interactions (e.g. red grabbable laser) for spectators will reduce a potential source of confusion, and also match more closely to the behavior of the old lasers.

**Comment by Frooxius** [comment]
What do you mean by this exactly? Are they showing up as red/blue on items they can't interact with?

**Comment by shiftyscales** [comment]
Correct. I noticed it in particular with grabbables while I was a spectator. My laser was red indicating I should be able to grab it, but I couldn't- which was when I realized I was a spectator.

**Comment by Frooxius** [comment]
Fixed in 2020.5.28.1239 thanks!
