### ISSUE TITLE
Multiple Roots

### ISSUE THREAD

**Issue by sirkitree** [Frooxius/NeosPublic#6]
I'm honestly not sure how this happened, or how to reproduce it, but I noticed that on my Local home there are multiple roots showing. Deleting one deletes everything.
![20180423132750_1](https://user-images.githubusercontent.com/28543/39149758-6e2d151c-46fd-11e8-8296-94984c2216cc.jpg)

**Comment by sirkitree** [comment]
It grows! 😄 
![20180425134754_1](https://user-images.githubusercontent.com/28543/39269220-82364900-488f-11e8-821f-567b644fd27d.jpg)

**Comment by sirkitree** [comment]
Noticed that if I open a new inspector window, that these are not duplicated. So I think this is happening each time I start up a new session.

First window is the one I've kept in-world session to session, and the second window on the right is the newly opened scene inspector.
![20180426112813_1](https://user-images.githubusercontent.com/28543/39323897-34fbc23e-494b-11e8-8451-9ab997e45862.jpg)

**Comment by Frooxius** [comment]
There was an issue with an old UI cleanup when generating new one, duplicating every time on the load. Should be fixed now, pushed a build to nightly.
