### ISSUE TITLE
Hand Target Lasers Go Through Popup Keyboard Onto Inspector

### ISSUE THREAD

**Issue by Enverex** [Frooxius/NeosPublic#605]
When clicking an entry field in the inspector, the keyboard will pop-up, but I've noticed a lot of the time that trying to type on the keyboard will result in your laser going through it and clicking items in the inspector instead.

Example, the lasers should actually be hitting the keyboard here but are going straight through (though it's hard to tell due to perspective):
![20200526005845_1](https://user-images.githubusercontent.com/958670/83078397-72715500-a071-11ea-87fe-5ef560d0b75a.jpg)

**Comment by Frooxius** [comment]
Hmm that's odd. How often does this happen? I tried replicating this, but I can't seem to make this happen on my end.

**Comment by shiftyscales** [comment]
A Monsoon of Babies#9991 made an interesting discovery. This appears to be an issue that affects certain avatars. One such avatar being `Temporal Spirit 2.fbx` in the Neos Essentials > Avatars > Anthro folder. It's particularly easy to replicate with this avatar.

**Comment by shiftyscales** [comment]
It seems to be related to avatars that have a tooltip anchor (e.g. legacy avatars) from my testing so far.

**Comment by Hayden-da-Serg** [comment]
Hmm, I haven't seen this myself, however, I'm using a custom keyboard using mesh and primitive colliders, I personally can't deal with the default keyboard, if it does help I am still using avatars made before the laser interaction update.

One thing I have noticed is that the inspector quite annoyingly takes priority of some dialogues when I'm trying to use them, resulting in misclicks or grabbing the wrong thing. One primary example is the Color Picker dialogue

**Comment by Frooxius** [comment]
I see, that's a good find, it's just not compensating for scale. Will fix, thanks!

**Comment by Frooxius** [comment]
Fixed in 2020.5.28.1239!
