### ISSUE TITLE
AutoOptimizeAvatars on CommonAvatarBuilder ejects user from cloud avatar

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#606]
Steps to replicate:
- create a new world
- enable `AutoOptimizeAvatars` on `CommonAvatarBuilder`
- respawn

Observations:
- User is removed from their avatar, which is left empty and equippable in the world

Issue reported by Enverex, and the cause isolated by myself.

**Comment by Frooxius** [comment]
This is an old deprecated function, I'll just remove it in the next build.

**Comment by Frooxius** [comment]
Removed in 2020.5.28.1239
