### ISSUE TITLE
[Bug] Text accents of underline and italics do not respect close symbols (although it does do something)

### ISSUE THREAD

**Issue by Earthmark** [Frooxius/NeosPublic#609]
Underline and italics do not seem to correctly stop underlining and italicizing when a close symbol for the two is inserted.

Instead, in inspectors all characters before the starting element get the specific font attribute applied (including non-existent text) and the text in the environment gets the element applied to all symbols up to and past the current end of the string (only detectable with underline, but it goes past the text written in the box).

See attached image for this in practice, the string in the text field is `aaaa<u>Tc</u>ss`. This is only showing underline but the same effect happens with italics, bold seems to work as expected.
![image](https://user-images.githubusercontent.com/1251609/83117732-4ad6b880-a082-11ea-97a9-bc0a8ec377b5.png)

**Comment by Frooxius** [comment]
I replicated this for underling and have a fix coming, but I can't replicate this for italicizing. Do you have an example that reproduces this bug with italics?

**Comment by Earthmark** [comment]
After work I'll try to add one, should be around 6 hours from time of posting.

**Comment by Frooxius** [comment]
Fixed the underline, strikethrough, mark and other highlights in 2020.5.28.1239. Can't replicate the italics still. Let me know once you have repro-case.

**Comment by Earthmark** [comment]
Unable to repro italics, my bad there. Thanks for fixing the others!
