### ISSUE TITLE
Display user joins/leaves in all local user logs

### ISSUE THREAD

**Issue by H3BO3** [Frooxius/NeosPublic#610]
Currently it seems only host logs show the names and IDs of users who join a session - This can make it difficult to track down problematic users who can join a world and break or otherwise disrupt it before leaving quickly - In such cases host logs are required, and others who were in the world at the time cannot corroborate involved users. I would request userID and name on user join/leave are entered in the logs of all users loaded in a session, along with text specifying the name of the session for clarity.

**Comment by Frooxius** [comment]
Added in 2020.5.28.1239, hopefully it helps!
