### ISSUE TITLE
Menu Anchor on the Avatar Creator

### ISSUE THREAD

**Issue by Hayden-da-Serg** [Frooxius/NeosPublic#613]
I noticed that the menu anchor for the old hand menus still exists on the avatar creator, seeing as Context Menus relies on the ToolTip position now I feel this should be removed as to not confuse other users.

**Comment by shiftyscales** [comment]
This will be addressed once the avatar creator/creation process is converted to the Radiant UI system, for now, everyone can tell new users that the functionality is deprecated.

**Comment by Hayden-da-Serg** [comment]
I don't remember when this was changed, but apparently it was, so I'll close this.
