### ISSUE TITLE
Default SaveCopyPermission to "OnlyOwners"

### ISSUE THREAD

**Issue by ProbablePrime** [Frooxius/NeosPublic#614]
Many users are unaware that the default WorldPermissions "SaveCopyPermission" setting allows for users to save a copy of the world when it is published. 

I believe this option should be opt-in as it has potentially damaging consequences if it is not understood or thought about by users who may not know it exists. 

I'm not entirely sure on the defaults here for a new world but all permission groups should probably be set to OnlyOnwers by default.

Changing this to allow copies then becomes an Opt-In process.

**Comment by Frooxius** [comment]
Changed in 2020.6.2.95, thanks! Only affects new worlds though, existing worlds remain the same.
