### ISSUE TITLE
[LogiX Node Request] GetUserLocomotionModule

### ISSUE THREAD

**Issue by Hayden-da-Serg** [Frooxius/NeosPublic#615]
I was playing around with a concept of a locomotion module to lock my movement so I could still use tools but also use something else on the avatar that requires my thumbstick input, then I found that I have no way of reliably getting what locomotion module I currently have active so I can't dynamically switch between two of them if the world settings differ from my search terms.

Not only would this node fix this but this does open up other possibilities of Locomotion control via LogiX.

**Comment by TehTurk** [comment]
Just checked, it really is tricky to check what CharacterController would be active, yes you could find the actually controller slot, but the information just isn't there.

**Comment by Hayden-da-Serg** [comment]
Yup, I was experimenting with thisa few days ago, not only is it hard but if there's multiple Fly modules for some reason in the world then it'd actually be impossible, not only that but it's really hard to differentiate between Teleport, Grab World and Physical without component access.

**Comment by Frooxius** [comment]
Hmm this can be added, but it's a bit tricky now, as there aren't other nodes to really do anything with the current locomotion module it would return. To really do much with it you'd need component access. If it helps to just get the slot of it though, that could help for now.

**Comment by Hayden-da-Serg** [comment]
Ya in my particular use case I'd pretty much just use it to get the slot reference and name so I could switch back to it after I'm done with something instead of always switching to a specific locomotion module when the action is finished.

**Comment by TehTurk** [comment]
Would it be possible to get a setLocomotion node with this too? There can be times where you want to have this be needed in a game world.

**Comment by Frooxius** [comment]
Added in 2020.6.2.95!
