### ISSUE TITLE
Logix tool shows `greater than or equal` and `less than or equal` nodes as @ and A characters respectivly

### ISSUE THREAD

**Issue by mralext20** [Frooxius/NeosPublic#616]
https://this-is-a.stale-me.me/i/7oop.webp

functionally everything is fine, however this is not visually the case.

**Comment by TehTurk** [comment]
Interesting! I wonder how long it's been there.

**Comment by Frooxius** [comment]
Fixed in 2020.7.29.725! Sorry this one took a while, I didn't have a good way to narrow this down until recently.
