### ISSUE TITLE
[UIX/Interaction] Please Return Wrist Movements affecting object Rotation

### ISSUE THREAD

**Issue by TehTurk** [Frooxius/NeosPublic#617]
As mentioned in the discord. Old feature/unintended effect, having it back would be swell.

**Comment by Frooxius** [comment]
I can't return the old behavior exactly the way it was before, but I can reimplement similar functionality.

**Comment by TehTurk** [comment]
Yeah that's fine! I'm not defining it by it's technical aspects but it's visual/workflow aspects.

**Comment by sirkitree** [comment]
I too miss this functionality.

**Comment by shiftyscales** [comment]
After getting used to it, I've been okay without it- but rotating around an axis would feel really nice.

I noticed the other day when I tried to reposition my tool belt that I couldn't rotate it with the laser anymore which was a pain. Looking forward to seeing this reimplemented in some capacity. 👍

**Comment by Frooxius** [comment]
Implemented this as proper feature in 2020.6.2.95!
