### ISSUE TITLE
Expose information about Twitch chat polls

### ISSUE THREAD

**Issue by Zyzyl** [Frooxius/NeosPublic#618]
Twitch chat polls allow users to vote for preferred options from a pre-specified list of 2-5 alternatives.

**Minimum desired functionality** 
On poll completion, fire an impulse and provide the string corresponding to the most popular option.

**Other desired functionality**
Fire an impulse on poll start
On poll completion, provide strings and vote counts for all options
Get strings and vote counts for all options for an ongoing poll on demand (e.g. after an impuse from a timer within Neos)
Enable initiation of chat polls from within Neos

**Example use case**
A teacher is streaming content from Neos to students watching the stream. The teacher asks a question and students can indicate their preferred answer via a chat poll. An event occurs in Neos upon poll completion dependent upon the most popular selection using LogiX.

**Comment by Frooxius** [comment]
Which exact poll functionality do you have in mind? I have checked Twitch's API, but I cannot find anything about polls. Typically this is something that's implemented as part of the bot or as extension, so that's probably something you'd have to implement yourself inside of Neos.

**Comment by Zyzyl** [comment]
Thanks for taking a look at that Froox. I believe these are an 'official' Twitch feature (e.g. going by this page https://help.twitch.tv/s/article/how-to-use-polls?language=en_US&sf222407025=1). If the API doesn't provide the required information though I'll check what may be doable with chat bots.

**Comment by Frooxius** [comment]
I see thanks! Unfortunately I can't find any way to access this information through the API. It would likely have to be done through a poll implemented inside of Neos.

**Comment by ProbablePrime** [comment]
I can't find anything about this feature on the twitch dev docs too.

**Comment by shiftyscales** [comment]
For the information I found on it- it sounds like this feature is also only available for Twitch Affiliates, and Partners- which wouldn't serve the general userbase at large very well. So overall it would be better to just implement a polling system in Neos itself, perhaps using chat commands.

That would also offer some potentially cool visualization options to show the results in the session too as they're collected live.

Can this issue be closed/considered as resolved, @Zyzyl?

Alternatively, we could keep this issue open, and change the topic to extending the current default chat command list with polling functionality at some point?

**Comment by Zyzyl** [comment]
Thanks all for following this up and for the suggested alternatives. I don't think implementing those inside Neos would require Froox-level work so I'll close this issue for now.
