### ISSUE TITLE
Laser penetration works through the back face of inspectors

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#622]
Reported by Peter The Thinker, this issue can result in unintended inputs, moving refs/slots around, etc. while attempting to grip an inspector from its back face.

**Comment by Frooxius** [comment]
This is not actually the laser penetration, because there's nothing blocking it from reaching the canvas, it's just that the canvas doesn't ignore interactions coming from the other side. I have a fix coming int he next build.

**Comment by Frooxius** [comment]
Fixed in 2020.6.2.95! Canvases by default now ignore interactions from behind, can be re-enabled per-canvas if necessary.
