### ISSUE TITLE
Microphone noise gate

### ISSUE THREAD

**Issue by Ruikio** [Frooxius/NeosPublic#625]
One thing you notice when hanging out with people is you'll hear their fan, breathing, mic will continuously go off and you'll see the characters lips moving.

Having a microphone bar showing the noise level / sensitivity which you can then drag a slider over to cancel the background noise. Similar to Discord's voice system for voice activation.

**Comment by ohzee00** [comment]
I know there is infact a noise gate in Neosvr however it seems to be in the User inspector, perhaps with the new UI coming it could be planned to have that feature? Plus having it be a setting overall would be nice

**Comment by Ruikio** [comment]
> I know there is infact a noise gate in Neosvr however it seems to be in the User inspector, perhaps with the new UI coming it could be planned to have that feature? Plus having it be a setting overall would be nice

We have something that barely works in the settings for audio. I'm pretty sure disabling the normalization helps but also makes you extremely quiet for whatever reason. If there is some sort of noise gate hidden somewhere else, literally nobody would ever know unless they delved deep for it as it should be in the settings. If it's a thing I've heard absolutely nobody use it. Just nonstop breathing :(

Something simple has been around for a long time so hopefully this is considered. Heavy breathing is a little scary

**Comment by Ruikio** [comment]
Just going to throw this back up on the board for discussion. A lot of people are coming in wondering how to fix their background noise. Breathing, fans, background pets are all things I've forced to listen to in Neos at the moment.

**Comment by ohzee00** [comment]
I agree, especially since audio controls got touched a bit in the recent updates. Maybe the facet system could make a easy way to have a "slider" for the noise gate on top of the user volume facet, similar to how Discord settings handle it?(Just a suggestion on one way to go about it, there is possibly a better way) Along with of course this being a user setting that stays persistent through worlds and logins/logouts.

**Comment by Ruikio** [comment]
Discord's system is exactly how I was figuring aswell. It shows the user their background noise and they can counteract it by adjusting the slider. Neo's normalization and even the disabling of it does not work well. There is a lot of fans, breathing and pets that can be heard in the background of nearly everybody you encounter.

**Comment by Frooxius** [comment]
2020.7.5.788 now has proper noise gating, hopefully it helps! Let me know if it needs any tweaks to the defaults.
