### ISSUE TITLE
Object stops push/pull functionality from oculus stick forward/back, after being pulled to hand

### ISSUE THREAD

**Issue by shiltin2** [Frooxius/NeosPublic#627]
You must detach and attach object again for push/pull to function.
bug or feature?

**Comment by H3BO3** [comment]
This is intended behavior, pulling an item towards you switches it to be "attached" to your hand, so to speak, like you grabbed it directly with your palm. Locomotion control is avaliable in that mode.

**Comment by shiltin2** [comment]
That makes sense,thanks

**Comment by Frooxius** [comment]
Yes this is intended feature, pulling the object towards your hand transitions it to a physical grip.
