### ISSUE TITLE
UI interrupts draw tool

### ISSUE THREAD

**Issue by shiltin2** [Frooxius/NeosPublic#628]
In VR, the brush stroke stops if a UI is detected as being pointed at by the draw tool.

**Comment by H3BO3** [comment]
This is a private UI priority switch issue and also breaks the logix tool when dragging a ribbon, I expect similar things happen on other tools too

**Comment by shiftyscales** [comment]
This works in reverse as well. Objects that block the laser in the world can prevent interactions with private UI, e.g. scrolling, and once the scrolling is interrupted, it requires the user the click again.

I'm not sure on the technical aspect of it- but could it be possible to modify, or extend the laser system to handle private and public interactions fully separately, @Frooxius?

**Comment by Frooxius** [comment]
Fixed in 2020.6.3.391 thanks!
