### ISSUE TITLE
Friendlink for UIX

### ISSUE THREAD

**Issue by Vigilabo** [Frooxius/NeosPublic#630]
Would it be possible to modify the Friendlink component to work with UIX buttons? Currently if you wanted to put a friendlink on something that uses UIX you would have to make a separate collider and position it at the place where you want it to be. Maybe the Friendlink component can have a trigger that can be used by the ButtonActionTrigger component?

**Comment by Frooxius** [comment]
Yeah this is quick modification,  coming in the next build.

**Comment by Frooxius** [comment]
Added in 2020.6.2.95!
