### ISSUE TITLE
Neos crashes with UIX and nested canvas

### ISSUE THREAD

**Issue by Ardescar** [Frooxius/NeosPublic#631]
Hello,

With UIX Canvas and Nested Canvas - the Laser does cause a _"System.StackOverflowException"_
With _" at FrooxEngine.NestedCanvas.ProcessEvent (FrooxEngine.UIX.Canvas+InteractionData eventData) [0x00057] in <86556071e05b4c7b840fdd89fe339c79>:0 
  at FrooxEngine.UIX.Canvas.OnTouch (FrooxEngine.TouchEventInfo& eventInfo) [0x00222] in <86556071e05b4c7b840fdd89fe339c79>:0 "_

This can be reproduced all the time. I have attached the logfile.
[ARDI - 2020.5.28.1239 - 2020-06-01 22_47_15.zip](https://github.com/Frooxius/NeosPublic/files/4713467/ARDI.-.2020.5.28.1239.-.2020-06-01.22_47_15.zip)

Greetings :D

**Comment by Frooxius** [comment]
What was your setup for this? It looks like you might've set the nested the canvas into itself, which caused infinite recursion.

I can add guard to prevent this from crashing, but you'll need to fix your setup if that's the case.

**Comment by Ardescar** [comment]
i did set the nested canvas in another normal canvas.  I did kind of expect that it should work.

**Comment by Frooxius** [comment]
Hmm that's odd, I don't see how an infinite recursion would happen in that case. Do you have a replication case for that? 

It should work normally for other nested canvases.

**Comment by Ardescar** [comment]
I can give/handover the said canvas - i saved it. 
And i try it now in another world.

**Comment by Ardescar** [comment]
Yeah tested in another world. Still does chrash my Neos.

**Comment by Frooxius** [comment]
What is the canvas structured like? Where are you putting the nested canvas in relation to the parent one?

**Comment by Ardescar** [comment]
![nestedcanvas](https://user-images.githubusercontent.com/63201013/83460816-99f86100-a467-11ea-92b9-8b690fbd67b4.png)
There is the Setup. I did not much with UIX till these days. So just while testing around what does work and how does it work i did crash and tried to find out why. 

The lower part of the canvas - that with "jgds" is with nested canvas and does cause the error.
The upper part is a normal canvas.

**Comment by Frooxius** [comment]
Is the nested canvas shown in the hiearchy in that screenshot? What is the name of the object that the nested canvas is on?

**Comment by Ardescar** [comment]
Yes the Canvas in that screenshot is the nested one that did cause the problem.
The Canvas was there in the root without a extra object.

**Comment by Frooxius** [comment]
I think you misunderstood my question. I need to know two things:

1) Is the canvas that's being referenced by the NestedCanvas component shown anywhere in the inspector on that screenshot?
2) What is the name of the object that has UIX canvas that's being nested?

In that screenshot, the NestedCanvas references canvas named "canvas". This seems to be the same canvas as the one the NestedCanvas is under, which would explain the crash due to infinite recursion.

However I don't know if the "jgds" canvas is also named "canvas".

**Comment by Ardescar** [comment]
Sorry for beeing unlcear - i have not done much with canvas and UIX  ;) i thought it was clear when i did write that i put the nested canvas under another normal canvas. 

This image shows the canvas wich is refered from nested canvas. 
![cvrtbrj6](https://user-images.githubusercontent.com/63201013/83462685-23119700-a46c-11ea-8e82-007786f044dd.png)

The 2. i dont understand fully. Sorry :(

**Comment by Frooxius** [comment]
Did you rename the canvas to "crashwas" or is this a different one? The structure looks the same as with the first one.

Essentially what I'm asking is, can you show me both the parent canvas and the one that's being nested at the same time, both opened in the inspector?

**Comment by Ardescar** [comment]
Yes i did rename the "canvas" to "crashwas" to find it in my inventory again.
it is the same one even with the other name.

There is a screenshot of both. 
![ertjrtzjertjm](https://user-images.githubusercontent.com/63201013/83463478-6967f580-a46e-11ea-97ae-a1376e8c2e31.png)

Hope this helps.

**Comment by Frooxius** [comment]
Hmm, it's still hard to tell since they're both named the same. But it does seem like you're nesting the canvas into itself. 

Can you rename the canvas that's being nested to "nested canvas" and then check the "NestedCanvas" component to see if says "crashwas" or "nested canvas" under "TargetCanvas"?

**Comment by Frooxius** [comment]
If it's indeed the nesting issue, should be fixed in 2020.6.2.95. Please reopen if the issue still persists.
