### ISSUE TITLE
[Enhancement] A way to adjust grip pose without edit mode

### ISSUE THREAD

**Issue by Hayden-da-Serg** [Frooxius/NeosPublic#633]
I've come across a few situations in which a pose for an equippable item is just a bit unbearable, but I don't have permissions to go into edit mode to change the pose so I'll either have to suck it up or ask for builder permissions, both of which are pretty undesirable.
I'm personally not entirely sure how this would be done, but as long as I can do it without builder permissions I'll be happy.

**Comment by shiftyscales** [comment]
Other users have noted that the grip pose references can get in the way when trying to use edit mode for its other purposes.

And even in its intended use, I've noted that the grip pose visuals can be distracting/hard to see through when trying to position the tool relative to your avatar's hand as it visually noisy.

I think a proper toggle could be made for this in the form of a facet once the UI is being actively overhauled. The current edit mode solution was a good fix for some issues in the moment, but has its share of limitations, and frustrations.

As far as that goes- if the grip pose visuals are hidden, such a toggle could be used to enable the old behavior some users prefer in being able to always be able to adjust the tool's position while gripped/equipped.

They could then disable the toggle if they need to lock the tool's position. Perhaps the facet/toggle could be "Lock/Unlock Tool Positioning".

**Comment by Hayden-da-Serg** [comment]
Was migrated to UI Edit Mode as of build 2020.7.11.1366, this allows adjustment of items without the need of Builder or higher.
