### ISSUE TITLE
Laser triggers multiple clicks on moving UI

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#634]
When a UI panel moves after a click event (e.g. the buttons on the 'create new' dialog) while the trigger is still held, it will send out an additional click each time the panel moves.

E.g. pressing and holding the trigger on "3D Model" will keep sending click events in a loop.

Issue reported by H3BO3.

**Comment by TehTurk** [comment]
While this is a bug, it would be nice if this would be a feature.

**Comment by H3BO3** [comment]
Why would this be nice as a feature? It does extra clicks on unpredictable elements and is extremely disruptive

**Comment by TehTurk** [comment]
Edited, apologies.

**Comment by Frooxius** [comment]
Fixed in 2020.6.3.391 thanks!
