### ISSUE TITLE
Soft-equipped tooltips save to inventory

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#635]
Tools soft-equipped by physically grabbing will save to the inventory. This also happens after the tool has subsequently been equipped via the context menu.

Steps to replicate:
- Physically grab a tool to soft-equip
- Press the green plus to try and create a new directory (with either hand)

Notes:
- The tooltip is then still also saved if you grab a different/unrelated object (e.g. a box) and try to save it
- E.g. soft-equip tooltip > equip tooltip > grab box with off-hand > try to save box

**Comment by Frooxius** [comment]
Fixed in 2020.6.3.391, should cover all bases and cleanup the reference to the soft-equipped tool when it's released or equipped through the option. Thanks!
