### ISSUE TITLE
Grabbed objects in the wrong position for remote users on headless

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#637]
Reported by Beaned and Gourry, while on a headless session, objects will visually shift in position, and rotate on the wrong axis (or on no axis for joystick rotation) for grabbed objects (physical or laser).

Another interesting note. Techy89 is on screen mode, and while he sees the same issue when others laser grab, he doesn't experience the same issue when other users physically grab.

**Comment by Frooxius** [comment]
Fixed in 2020.6.3.391 thanks!
