### ISSUE TITLE
Default lasers latching to other people's toolshelves and becoming globally visible

### ISSUE THREAD

**Issue by H3BO3** [Frooxius/NeosPublic#640]
The default lasers (with no tool equipped), when pointed at another user's toolshelf, turn blue and latch to it as if you would be able to use it. They also become visible globally. When a tooltip is equipped this issue is not present, the laser just stays white and only latches to your own toolshelf, what I consider to be correct behavior. I think the default laser should work the same as there's no way to use someone else's toolshelves remotely.

**Comment by Frooxius** [comment]
Ah this will be easy fix to just make the laser ignore other people's itemshelves.

**Comment by shiftyscales** [comment]
I believe this was fixed in 2020.6.5.201.
