### ISSUE TITLE
flipping images/fotos etc. when started dragging the item by hand or laser

### ISSUE THREAD

**Issue by Ardescar** [Frooxius/NeosPublic#648]
Noticed in the last several days that Pictures/Fotos does change rotation when i start to drag them around. It seems to affect not all pictures but some of them. And it is always the case with pictures that i spawn from my inventory. And before - when the pictures have been created they where behaving normal. 

By inspecting some pictures i have seen that:
- the rotation of the image is not coverted from global to local space - so the rotation seems to change optical and does snap back wenn released.
- the reason of that might be that there is a Tween<floatQ> Component attached to those 
- and when i delete the component the picture behave like it should

So either there is a Tween-Component by a unknown reason attached to the picture when saved or when loaded. But as far as i can asume ... i guess its while saving the picture. Because when i spawn the images then those wierd behaving ones are always the same. And those normal ones stay normal no matter how often i spawn them from inventory.

Sadly i cant reproduce the reason why one image is with tween and the next image after that is without a tween. 

![rotation_fixed](https://user-images.githubusercontent.com/63201013/83765215-321a6400-a67b-11ea-91f1-cfd938e93cc7.png)
![sidebyside](https://user-images.githubusercontent.com/63201013/83765238-38104500-a67b-11ea-8646-63877badb78c.png)
![tween](https://user-images.githubusercontent.com/63201013/83765244-3a729f00-a67b-11ea-98fd-e852c266a720.png)

Video with the tween inspected - http://strzl.de/video/tween.mp4
Video that shows the behavior - http://strzl.de/video/stiller.mp4

**Comment by Frooxius** [comment]
Hmm this is technically normal with the Tween component attached on those components, as it's taking over the rotation. You probably saved the photos while they were still animated. 

I made a tweak in 2020.6.5.201 that makes Tweens non-persistent so they won't get saved like that. But you'll have to remove them from your existing saved photos manually and resave. 

Thanks!
