### ISSUE TITLE
Dynamic bones breaking

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#649]
Exact replication steps haven't been confirmed yet. What has been confirmed:
- When the issue occurs, dynamic bones across all users all freeze/pause
- If an affected user respawns, their dynamic bones resume working
- If one disables "dynamic player collisions" on the dynamic bone chain, it begins working
- It is thought (not confirmed) that this occurs when a user joins the world.

Kal has provided this log:
[AMMOCAN_-_2020.6.2.125_-_2020-06-02_18_30_06.log](https://github.com/Frooxius/NeosPublic/files/4730827/AMMOCAN_-_2020.6.2.125_-_2020-06-02_18_30_06.log)

In this log, at line 162 shortly after the world is opened, numerous users join. Immediately after, we see exceptions on all of the dynamic bone chains in the world.

**Comment by shiftyscales** [comment]
Issue was reported by Canadian Git, Kal, Cyro, and others that have been affected by it.

**Comment by Frooxius** [comment]
This log got the actual error, thanks! That's the one I was looking for. Fix coming in the next build, thanks!

**Comment by Frooxius** [comment]
Ok should be fixed in 2020.6.5.201! Thanks!

**Comment by shiftyscales** [comment]
CanadianGit has reportedly seen this issue on the current build, although smaller in scale: `Small note: dynamic bones are still producing weird behaviour. Where previously the entire session's dynamic bones would break, now only a few (sometimes a single chain?) will, but in the same way - the 'enable' box unchecks itself, and keeps unchecking itself if reenabled.`

He intends on adding logs as he collects them.

**Comment by Frooxius** [comment]
Yeah this will definitely need more logs of this occurring to fix. It's throwing some exception, which is disabling the dynamic bone component, but I need to know what that exception is.

**Comment by shiftyscales** [comment]
I haven't heard any reports of this issue reoccurring in the past few weeks. Closing this issue.
