### ISSUE TITLE
Cameras Portals don't scale to their Target Properly

### ISSUE THREAD

**Issue by TehTurk** [Frooxius/NeosPublic#650]
Went in to fix my Snowglobe world and found out why the portals in it broke. Apparently you can scale up a portal to large numbers, but for some reason you can't scale a Target past say something like x10 of it's original scale of 1 (The required amount was 100 so I could achieve the affect) There are also some exceptions I found in the log while testing trying to debug why. If you'd like to see it in effect, look at the Snowglobe world I have published and you can see the state I at least left it in until it can be looked at. 
[PROMETHEUS - 2020.6.5.201 - 2020-06-05 00_20_06.log](https://github.com/Frooxius/NeosPublic/files/4735589/PROMETHEUS.-.2020.6.5.201.-.2020-06-05.00_20_06.log)

**Comment by shiftyscales** [comment]
Should be improved in 2020.7.1.26.
