### ISSUE TITLE
Laser corrupts on a slot with an axis scale set to 0

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#655]
Reported by GearBell, users are being respawned when they attempt to modify the scale of their avatar's limbs.

This is because of the protection put in place that respawns a user when the laser is corrupted.

The laser is corrupted because while modifying the slot size, it is momentarily set to zero when entering the scale since values entered on the keyboard are instantly applied.

There are many potential valid use-cases to modify a slot the lasers will be under. E.g. on my personal avatar, I've rescaled my hands so they are a better fit/more comfortable. It is also a common prank/joke to goof around with the size of one's limbs.

I confirmed in a session with GearBell that the issue does not occur if explicit care is taken to make sure "0" is never inside of the axis scale.

I also confirmed the issue sometimes only occurs when the lasers are activated (trigger pull) and not the instant the scale is changed- in particular when modifying someone else's scale.

GearBell has also reported loss of work on her avatar on other occasions because the user respawning mechanism can be overly aggressive/disruptive (although because of that, it has been useful at catching cases like these.)

A clean log demonstrating the laser being corrupted on setting the scale of an axis to 0 on a slot above the laser:
[SHIFTY-PC - 2020.6.5.201 - 2020-06-06 08_35_18.log](https://github.com/Frooxius/NeosPublic/files/4740554/SHIFTY-PC.-.2020.6.5.201.-.2020-06-06.08_35_18.log)

**Comment by Frooxius** [comment]
Fixed in 2020.6.8.483, shouldn't cause respawn anymore. Thanks!
