### ISSUE TITLE
[BUG] Height setting units seem to mismatch real-world

### ISSUE THREAD

**Issue by TiagoTiago** [Frooxius/NeosPublic#658]
I am 170cm tall, but if I set that in the interface, the avatar stands half-crouching, I need to change it to a much lower value (I forgot exactly, I think it was something like 157cm) to make it so the avatar stands straight when I stand straight and starts tip-toeing exactly when I do.

**Comment by shiftyscales** [comment]
Hey @TiagoTiago. You should still use your real-life height in the settings. There is a value called 'height compensation' available per avatar which will allow you to adjust the avatar's scale to better fit your body.

If you open the full-body calibrator found under the tools (this applies even if you don't have full-body trackers) you can access an interface that will let you adjust the height compensation slider. Usually a value around 0.92 works well, but you can adjust it to your comfort.
