### ISSUE TITLE
Layer transparency

### ISSUE THREAD

**Issue by sirkitree** [Frooxius/NeosPublic#661]
I'd like to request a component that when placed upon an object would make all of it's children a certain opacity, from 0 to 100%. This would give finite control to opacity settings per 'layer'.

The use case would be a complex hierarchy of objects and let's say I want to duplicate that, but the duplicate layer I'd like to be 30% less opaque than the original one.

If there is a better recommended way of achieving this, I'd be grateful to learn of it :)

**Comment by Frooxius** [comment]
I'm sorry, but unfortunately this is not possible to implement in any reasonable way. It doesn't quite fit with the way rendering works - things aren't really rendered in layers in the first place and many materials don't necessarily support fade transparency or are not configured to support it.

What I would recommend doing is create all the necessary materials you need for the hierarchy and then driving the tint color (or other property) either with LogiX or ValueCopy from one central value. 

By sharing materials, you can easily affect lots of objects at once, but it requires things to be setup in advance to achieve the effect.
