### ISSUE TITLE
MultiValueTextFormatDriver Component

### ISSUE THREAD

**Issue by Zyzyl** [Frooxius/NeosPublic#662]
Change the source field of this component (Utility > ValueTextFormatDriver<T>) to take a list of inputs, rather than just one, to allow formatting of multiple bits of data.

Would be even better to be able to provide different datatypes (ints, floats, strings etc) to the same component, but the Format LogiX node is fine for now if that would involve significant backend work.

Change requested because there are situations where it's cleaner to use a single component than a bunch of LogiX.

**Comment by Frooxius** [comment]
I'm sorry, but these tweaks are unfortunately not possible for this component. It is purposefully designed to be a single Value format component (similar to the other ValueXYZ components) so it would break the convention and its existing uses. It's also based around a strongly typed datatype, so it can only process one particular datatype.

What's possible however is to add a new component, something like MultiValueTextFormatDriver, which would accept a list of different values and a formatting string, but it's a bit trickier on how to provide those datatypes. Although a list of general field references can work.

**Comment by Zyzyl** [comment]
New component is fine by me - I'm after the functionality, not that it be specifically linked to ValueTextFormatDriver.

My current use case would be when making UI and wanting to format multiple pieces of information (possibly stored in ValueFields etc.) into a single piece of displayed text e.g. "This is {0}, page {1} of {2}" where 0 is a string, 1 & 2 are ints. A compact, component-based solution would be nice here.

**Comment by Frooxius** [comment]
Added in 2020.6.12.785, hopefully it serves well!
