### ISSUE TITLE
Equipping Tools through Laser + Context menu Ignores Grabbable ActiveUserFilter

### ISSUE THREAD

**Issue by H3BO3** [Frooxius/NeosPublic#663]
Most people have tools on their avatars under snap points, with the ActiveUserFilter on the grabbable set to an option that will prevent others from simply grabbing it off their avatar - However, with the laser and context menu now able to equip tools without having to grab them, the tool can be taken and equipped anyway. Is it possible the laser/menu equip could check for grabbable permissions as well?

**Comment by Frooxius** [comment]
Should be fixed in 2020.6.10.647 thanks!
