### ISSUE TITLE
Option to hide LogiX Nodes

### ISSUE THREAD

**Issue by MR-Alex42** [Frooxius/NeosPublic#67]
After finishing the visual LogiX programming I'm usually scaling down the LogiX nodes in order to hide them inside their objects. However this does not work for transparent objects or objects without volume, so that is why I request this feature. I now that I can use the developer tooltip do hide the LogiX nodes but I consider LogiX and the developer tooltip as two separate skill levels.

**Comment by Frooxius** [comment]
There's actually supporting logic for this already, just not exposed via the LogiX tooltip, so this should be pretty quick to do.

**Comment by Frooxius** [comment]
It has been mostly added and pushed to nightly-patreon.

It mostly works, there are still some issues though. Reference wires aren't always properly restored or deleted. Only visuals are affected, all behavior is preserved.
Here's new controls:

- Spawn Node - Double press trigger (same as before)
- Disconnect wire - Drag with trigger (same as before)
- Open/Close node selection - Use the contextual radial menu
- Open LogiX interface - short secondary press while holding a reference - need to use it with inspector now to open interfaces
- Long secondary press - show/hide LogiX nodes for the targeted object(

**Comment by Frooxius** [comment]
This is now done and should work for majority of cases. If there are issues, open an issue with particular problem.
