### ISSUE TITLE
New session orbs not updating properly

### ISSUE THREAD

**Issue by H3BO3** [Frooxius/NeosPublic#671]
This seems to happen quite often, and came to a breaking point last night with the influx of new users - They were hopping worlds quite often, and when bringing out a world orb and creating a new session with it, the Join Session button often told them the session had ended, or did nothing at all. I think this might have been related to cloud slowness issues, as there was one time where everyone was double clicking an orb and nothing was happening, not even a popup or the context menu opening, and a few minutes later everyone suddenly got shoved into the new session. Another time bringing a session orb back from the new session was broken, there was a checkerboard thumbnail in it and trying to join would also indicate the session had ended.

Are there any mitigations that could fix this, perhaps (if the new session is public) sending session data from a world orb session directly to the users in a world or similar?

**Comment by sirkitree** [comment]
I noticed this today as well. To replicate:
1. start a new session from an orb
2. close the session from the menu
3. notice the orb is still actively highlighted
4. try to join and get message stating that it's already ended

**Comment by H3BO3** [comment]
@sirkitree Wait, what's up with step two? This is happening with sessions that remain open and people are trying to join, but can't

**Comment by Frooxius** [comment]
@H3BO3 This sounds like correct behavior. The session orb will lock on the first person starting the session and will only initiate the join when it actually loads for them. If the host takes a while to load it will take a bit for everyone before they can join.

There's not much that can be done about that if the person take a while to load things (other than optimizing loading). 

It certainly wasn't cloud slowness, it was responding quickly even at peak load and it wasn't anywhere near enough the capacity.

For the session thumbnail being checkerboard that's a bit odd, but I'd need more information. Is this something replicable? Normally the texture is hosted on the cloud, so it should still load. How exactly was the orb obtained? 

@sirkitree Is that issue essentially starting a session from a world orb and it not clearing up the link? That could be fixed. Normally it should clear itself, but it's likely some link got broken.

**Comment by H3BO3** [comment]
@Frooxius It seemed to be happening with lighter worlds too. They were gone in the other session for quite some time and people still couldn't join.

It still doesn't explain the case of no message at all occurring in that one case, or even the context menu not popping up for the world orb, and suddenly everyone who double-clicked joining the session at once.

In the case of the checkerboard orb, they had gone to their homeworld and brought back a session orb, spawned from the session menu there so people could join.

**Comment by Frooxius** [comment]
@H3BO3 The world you're doesn't mattter, it's the loading of the new one that does. If the user takes a while to load it, it will take a while for everyone to join.

When you double click the orb, it registers the request to join, but it waits until the session itself actually starts. This is done all by the host (the first person opening it) and doesn't actually touch cloud at all. Once the session starts on the host, the world orb is updated with the session info by the starting person, which is picked up by everyone who clicked on it, making them actually join.

Some slowness is unfortunate and will happen sometimes.

For the checkerboard, is that something that can be replicated?

**Comment by H3BO3** [comment]
That's what I meant, the new world wouldn't have taken a while to load. They were obviously in the session for a while but people still couldn't join.

I still find it odd that no loading message appeared in that one case and the context menu wouldn't open on the orb either. Yet people still joined the world once it was ready.

The checkerboard thing seems to happen fairly often when bringing out and moving session orbs between worlds to let people join them. Would the world being set to invite-only have anything to do with this?

**Comment by sirkitree** [comment]
> Is that issue essentially starting a session from a world orb and it not clearing up the link? That could be fixed. Normally it should clear itself, but it's likely some link got broken.

Hrm, yeah I just tried to replicate it again and was unsuccessful... so disregard I suppose

**Comment by Frooxius** [comment]
@H3BO3 Ah, in that case it was likely queued packets in the world taking a while to propagate. That's not really much that can be done against, other than better host or switching to Steam Networking Sockets.

The world being invite-only would cause that. That's expected behavior too, because private worlds don't upload anything to the cloud server (even thumbnails), those are only local. Does it happen for Friends or Public worlds as well?

@sirkitree Hmm I tried replicating it myself and couldn't get it to happen either unfortunately. If you find a way to make it reliably happen let me know!

**Comment by H3BO3** [comment]
Okay, sounds like the rest can be explained - However, there was still the issue of not being able to join said private session through its session orb, it said the session had ended. Since it was a homeworld, it had no doubt been open for quite some time. Is that an access level related thing? I would expect it to say the session is private or something if it didn't allow joining off the orb.

**Comment by Frooxius** [comment]
I'm not sure about the specifics of that case I'd need to know a replication scenario.

However Private sessions will appear as sessions that do not exist to most parts of the system for security reasons, because they pretty much don't send anything to the cloud in the first place, except for beacons for NAT punchthrough when there are active invites.

**Comment by H3BO3** [comment]
Alright, I'll keep an eye out. It just seems like this issue comes up often with people not able to join new sessions conveniently. Perhaps instead of it saying the session has closed (which it obviously hasn't, it just isn't "up" yet, maybe it could queue it in for load and display the "loading..." message while it waits for the host to be ready? And it would have the potential to time out in case the connection doesn't go through after a while.

Hold on, why would kicking clear the user from being allowed back in? How long has this functionality been in place? Often people clear AFK users through kicking if they just don't want them to be around unless they decide to come back, I've done this on occasion. Having auto-kick do this as well seems like a bad idea, there needs to be a way to just remove users from a session without restricting them from coming back in, which auto-kick could also use. Will this be covered when UI panels are redesigned?

**Comment by Frooxius** [comment]
Yeah I could see about adding the loading indicator from the moment it's clicked so it's clearer what's going on. Timing out could be added too, question is how long it would be though? What if the user still wants to go through?

That functionality has been there from the beginning. It's not particularly intended, it's just that the system currently doesn't distinguish between user Kick and Auto-AFK-kick. From its perspective it's just Kick, which clears the user from the allowed list. Changing it needs extra work, it's not covered by UI redesign itself.

**Comment by H3BO3** [comment]
I don't imagine there's currently any way to communicate status like that if the world isn't "up" yet - Perhaps that could be expanded upon in the future? Whatever value it is, they could try again if it does time out. I just think communication needs to be clearer so people don't get confused.

It would be good with that kick rework to have more options for just removing someone from the session so they can get back in at anytime, vs. kicking and not letting them back into that particular session (optionally for a certain period of time), vs. an actual ban.

**Comment by Frooxius** [comment]
Ok I've reworked the loading indicator so it pops up the moment the world orb starts waiting on the host to open the world in 2020.6.12.785, that should help with some confusion.
