### ISSUE TITLE
Bug with UIX checkbox

### ISSUE THREAD

**Issue by Zyzyl** [Frooxius/NeosPublic#675]
State field does not update upon button press if the Target State field is filled. i.e. State bool remains fixed with the value it held before the Target State field was filled. Correct updating behaviour returns after Target State field is cleared. 

Checked/unchecked state is correctly passed to the target of the Target State field regardless.

**Comment by Frooxius** [comment]
This is intended behavior. When you use the "Target State" you essentially change where the check state is located, meaning the one on the component gets ignored to avoid redundant changes (and network traffic).

You can use either of those, but not both. If you need to use the one on Checkbox, drive other fields from it with ValueCopy.
