### ISSUE TITLE
Enable "FeetIgnoreOtherPlayers" by default on VRIKAvatar

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#676]
This tweak fixes some undesirable IK behaviors when users walk through each other, or stand near each other.

By default, with this setting disabled- whenever players are in close proximity, their feet will rise up into their chest, and jitter around.

Overall I think this tweak would be a net positive one as it stabilizes the IK in scenarios where players are in close proximity, with minimal cost to immersion or other benefits as the feet will still rise up on other colliders, etc. by default.

Preferably it could also be auto-updated on existing avatars.

**Comment by Frooxius** [comment]
I don't think this is a good idea, because I often see the feet being reactive to other players being one of the positives that people like about Neos, as it shows high level of interactivity. If it's hidden behind a setting, most people won't know about this functionality. 

What can instead be done is refine the reaction, so the feet will ignore the player under certain conditions that look weird, but not in others.

**Comment by TehTurk** [comment]
Won't lie I'd be sad if this is changed to be hidden. And I agree with Froox on the interactivity I find myself playing with people's feet when they just all dangly and sometimes can be quite fun for a joke or something goofy just happening. What makes the behavior undesirable?

**Comment by shiftyscales** [comment]
Mostly the times that it misfires when it doesn't make sense to/or doesn't look good to, @TehTurk. E.g. if players are close to each other/hugging, the feet can sometimes mess up/when users walk through each other on level ground, etc.

No real objection to it when it is in flight mode/places where the feet aren't grounded/it makes sense that the feet can be interacted with that way.

If it's possible to filter it from happening when both players are grounded, that should take care of most undesirable situations I've seen it come up in.

**Comment by shiftyscales** [comment]
I now believe the current default is fine.
