### ISSUE TITLE
TextureThumbnailSource component prevents the saving of an object if the Crop parameter is invalid

### ISSUE THREAD

**Issue by AMonsoonofBabies** [Frooxius/NeosPublic#677]
While utilizing the TextureThumbnailSource component on a slot, if the option for Crop is checked, then attempting to save the slot in your inventory will not work if the Crop values are invalid. By invalid, I mean that the X1, Y1, X2, and Y2 values do not exist between 0 and 1, or if X1 is greater or equal to X2, and likewise with the Y values. A quick and simple recreation can be done as follows:

1. Open Neos and enter a new empty world
2. Spawn a Developer's Tooltip and create a box
3. Inspect the box and add the TextureThumbnailSource component to it
4. Acquire any 2DTexture asset and fill the component's Texture field with it (I chose the white line texture from Neos Essentials > Textures & Sprites)
5. First observe the component working by saving the object to your inventory as it is
6. Set Crop to True, which initializes the Rect values with 0's, which is an invalid set
7. Attempt to save the object again, and observe that nothing occurs

The crop feature still does work as intended with valid values however, as putting in (0, 0, 1, 0.5) as an example will properly cut off the top half of the image for the thumbnail.

I imagine a better case for invalid values would be to simply ignore the component and generate a thumbnail automatically as per what usually happens. I wouldn't want people to start looking to this awkward side effect as some sort of save prevention method.

**Comment by Frooxius** [comment]
Should work correctly in 2020.6.14.978 now, thanks!
