### ISSUE TITLE
Unable to click friend link on nameplates

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#678]
In the 2020.6.12.785 build, a bugfix was made preventing users from clicking their own nameplate which had the unintended effect of making any nameplate un-clickable.

The friend link still works properly if placed on a quad.

Issue reported by LakeSheep through Coffee, SmolCookie, sleepingkaikai, jeana, and GalexY.

**Comment by Frooxius** [comment]
Should be fixed in 2020.6.14.978, thanks for the report!
