### ISSUE TITLE
Sprite provider addition

### ISSUE THREAD

**Issue by candypheonixIO** [Frooxius/NeosPublic#679]
For the sprite provider, would it be possible to add a feature that allows a user to specify bounds that shouldn't be effected by scaling, this would remove the need for several rounded images/buttons used in uix when only one can be used and rescaled without distorting rounded edges.

**Comment by Frooxius** [comment]
This is already supported, use the "Borders" property to setup 9-slice coordinates: https://en.wikipedia.org/wiki/9-slice_scaling

**Comment by candypheonixIO** [comment]
it dosnt work for me, are there any good examples or documentation on how to use it?

**Comment by candypheonixIO** [comment]
nvm, ive figured it out, the 'non-descript' scale slider helped

**Comment by Frooxius** [comment]
It's pretty simple, the values you provide there are normalized distances from individual edges. E.g. if you want the 10 % of the image from each side fo not scale, you'd input [0.1, 0.1, 0.1, 0.1] there.

Here's an older devlog which showed it in action. It's not particularly a tutorial, but should help: https://www.youtube.com/watch?v=v2QRzJGWJHU
