### ISSUE TITLE
Focus previously active world on login

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#680]
Pointed out by Abysmal on watching various streamers play Neos- users upon logging in are not returned to the previous session they had active prior to being moved to the local home when logging in.

For new users who might not know the interface, it is possible for them to get lost, and not find their way back to the MTC.

This would also greatly help users chaperone new users by not risking losing them upon login.

**Comment by Frooxius** [comment]
This could be added, but with the new UI the plan is to make the logging in process more at the forefront, this situation doesn't arise in the first place. It might be better to wait for that.

**Comment by Frooxius** [comment]
Implemented in 2020.7.11.1366, should help now! Thanks!
