### ISSUE TITLE
Clamp Slope Angle in Physical Locomotion to prevent exception

### ISSUE THREAD

**Issue by H3BO3** [Frooxius/NeosPublic#685]
As discovered by Nicoreda, setting the slope angle in physical locomotion to somewhere above 90 (might also include 90, because that's just a wall at that point) causes an out-of-range exception. I suggest clamping the input value to prevent that from happening.
![image](https://user-images.githubusercontent.com/62123804/84610312-6231e600-ae77-11ea-8657-a4fa2875f32d.png)

**Comment by Frooxius** [comment]
The value is already clamped, this is actually caused by it being calculated incorrectly afterwards. I'll have a fix soon!
