### ISSUE TITLE
WorldPermissions "AllowSwappingAvatars" configuration ignored for Spectators

### ISSUE THREAD

**Issue by ProbablePrime** [Frooxius/NeosPublic#686]
I have some worlds that set everyone forcibly to spectator when they are loaded.

Examples:
* Vigil
* Gemini

In these worlds Spectators are unable to swap their avatars. This is confusing because there's a worldpermissions property title "AllowSwappingAvatars" which is checked in all of these worlds.

To reproduce:
1. Create a new world from the default templates, any will do
2. Examine the WorldPermissions Component for spectators and see that "AllowSwappingAvatars" is checked by default:

![20200614200506_1](https://user-images.githubusercontent.com/8791132/84615693-86dd8c00-ae7e-11ea-82e0-cb071db02fed.jpg)

3. Get a spectator permissioned user to attempt to "Lightning Bolt" equip an avatar.
4. Observe that they will be unable to.

This is inconsistent with my expectations as in these cases I explicitly allow avatar swapping in the permission configuration for my world.

I thought it might have something to do with "AvatarObjectPermissions" which appears to be an Allow/Block list for avatars within the world. This by default is set to "Whitelist" so I tried with it set to both options here. It didn't appear to affect anything. 

![20200614200455_1](https://user-images.githubusercontent.com/8791132/84615862-fbb0c600-ae7e-11ea-907c-181bc3cb02e3.jpg)

Additionally I verified that the user spawner allows the loading of cloud avatars:
![20200614041134_1](https://user-images.githubusercontent.com/8791132/84615891-0f5c2c80-ae7f-11ea-9be4-0ab02114ca43.jpg)

**Comment by TehTurk** [comment]
Prime has shown me this and tested it. I can collaborate the bug.

**Comment by Enverex** [comment]
Noticed this yesterday when someone complained. I checked and as above, it was already set to allow them to swap but they're still prohibited.

**Comment by ProbablePrime** [comment]
I did some research here and believe I have found the issue. Spectator Permissions contains the "Avatar Object Permissions" component but Guest does not.

Removing the "Avatar Object Permissions" component from the spectator perms slot will enable spectators to swap avatars again.

As such this is a little puzzling, other permission related components that have a blacklist or whitelist only apply themselves if they are set up correctly. 

For example a "LocomotionPermissions" which is set to Blacklist but has no values in its list will not cause all locomotion modules to be blocked. I believe this behaviour is desirable. As a blacklist with no values doesn't really mean anything. To me it means "Block Nothing".

Does that make sense?

**Comment by shiftyscales** [comment]
It does appear to be working correctly, @ProbablePrime. The component is set to whitelist/allow list, but with no tags specified, so effectively, it's saying 'block all'.

I tried it out, and it will block swapping avatars for all roles if the permission is set to apply to those roles.

As for why it's there in the first place? I'm not entirely certain. I'm also not certain as to what the permission is exactly intended for/why it blocks avatar swapping in the first place considering 'Allow Swapping Avatars' is already a property on the WorldPermissions component.

From a limited amount of testing, it appears to be used to allow/disallow avatars with a certain tag?

**Comment by ProbablePrime** [comment]
Okay copying my personal suggestions and recommendations from Discord, these are specified to make this component and setup clearer and more understandable for users of Neos:
1. If AvatarObjectPermissions is present on spectators and set to an empty blacklist on spectators and the "AllowSwappingAvatars" is checked then Spectators should be able to swap to any avatar(This matches the pattern of other "*Permissions" components and makes "AllowSwappingAvatars" make sense. (This is what i found to not be working in testing, but Shift has not been able to replicate. We'll verify)
1. I also recommended that the default world template be setup as:
  1. AllowSwappingAvatars set to on for Spectators
  1. AvatarObjectPermissions set to and Empty blacklist matching the behaviour in 1. 

With both of these setup, "AllowSwappingAvatars" actually makes sense again as of right now its very confusing to navigate.

**Comment by ProbablePrime** [comment]
Here's a video with every permutation turk and I could think of. Thank you :) 

https://youtu.be/rVdNpcs-kLw

**Comment by Earthmark** [comment]
I found a user named Pants who was unable to equip an avatar in spectator even though other users were able to, it seemed  quite strange.

**Comment by H3BO3** [comment]
@Earthmark This was due to a short-term moderation action.

**Comment by Frooxius** [comment]
Modified the behavior in 2020.8.10.1195. When there are no Tags in the list and AllowSwappingAvatars is enabled, Specators will be able to change avatars. Thanks for the feedback!
