### ISSUE TITLE
Default "GridSpace" is too bright

### ISSUE THREAD

**Issue by ProbablePrime** [Frooxius/NeosPublic#687]
The default lighting in the GridSpace template is too bright at the horizon line. 

I would suggest decreasing the exposure, or the atmospheric thickness in the default skybox. 

![20200601184823_1](https://user-images.githubusercontent.com/8791132/84616044-93161900-ae7f-11ea-8b06-979813406d35.jpg)
![20200601184816_1](https://user-images.githubusercontent.com/8791132/84616046-93aeaf80-ae7f-11ea-9843-cf72eadb9c5e.jpg)

**Comment by Coffee-Maker** [comment]
Fixed and awaiting merge

**Comment by ProbablePrime** [comment]
Thanks Coffee :)
