### ISSUE TITLE
ToolShelves are unusable whilst in edit mode

### ISSUE THREAD

**Issue by ProbablePrime** [Frooxius/NeosPublic#688]
1. Enter Edit Mode.
1. Attempt to place a tool on your toolshelf
1. Observe you cannot.

**Comment by Coffee-Maker** [comment]
If you enter edit mode while holding a tooltip you can still place it on your toolshelf. I believe you can't place it on your toolshelf because of the grip pose reference editor making the bounding box of the tool too large

**Comment by shiftyscales** [comment]
This is highly likely to be the case I would imagine. It can be addressed by relocating tool editing to a facet as per #633 and #673.

**Comment by ProbablePrime** [comment]
Thanks for the responses.

Its unclear to me what the boundary between "Facet" and "Not a Facet" is. To me Facets are UI components which can be customised and moved/transferred around my play-space.

My toolshelves in my opinion don't qualify for that definition. They are a physical item within the world which are attached to my avatar which are vitally important for editing, within edit mode. 

Don't get me wrong, Facets are going to be great. I Just don't think they solve all of our problems and I'm unsure if this is one of the problems in which I see them fixing. 

As such I have logged it as a separate issue for the team to take a look solving as its actively affecting my ability to utilise edit mode for... editing.

It would be great to hear more about where this distinction lies.

**Comment by shiftyscales** [comment]
That is what I mean. If we relocate tool positioning to a facet as a toggle, we don't need to have it occupying the same space as edit mode. Using edit mode for repositioning tools was more a crutch to allow us to more easily modify tool positions without the use of inspectors.

And in doing so- it has hindered some of the functionality as you've previously noted. I wasn't talking specifically about the toolshelves, the toolshelves aren't a facet.

I had meant that if we have a mechanism to edit tool positions outside of the existing edit mode, e.g. as a toggle activated by a facet, it frees up edit mode of that association, and implicitly resolves this issue you are having.

**Comment by Frooxius** [comment]
It was the positioning visual as @Coffee-Maker has found, I've made tweaks in 2020.6.16.1053 that fix this. Thanks for the report!
