### ISSUE TITLE
Textbook proofreading

### ISSUE THREAD

**Issue by AlexanderPavlenko** [Frooxius/NeosPublic#689]
I would like to participate

**Comment by TehTurk** [comment]
I don't think this is appropriate for this github. If anyone wants to reopen this they can, but I'm going off the assumption it was an accidental post.

**Comment by AlexanderPavlenko** [comment]
Quoting patreon email:
> If you’re interested in helping out, reach out to a team member (ideally @Frooxius) and you will be given access to a private GitHub repository.
