### ISSUE TITLE
VirtualKeyboard dosnt work with custom UIX

### ISSUE THREAD

**Issue by candypheonixIO** [Frooxius/NeosPublic#690]
Ive now made another keyboard using uix and it still destroys it self when attempting to type in private fields, but works fine when typing in public fields.

If you need the keyboard(s), they are in my public folder.

**Comment by candypheonixIO** [comment]
here is a video of the keyboards not working like they should...
[https://youtu.be/kfHkCxsfnzg](url)

**Comment by LewisSnow** [comment]
I can say as I was there for both the UIX keyboards @candypheonixIO made that they are basically copies and has set them up properly as far as we can tell. Comparing both the current/default UIX keyboard to his custom UIX keyboard, they are setup identically aside from hierarchy organization. 

Its possibly an exception going on when attempting to type and/or edit text fields in a private UI.

**Comment by TehTurk** [comment]
Private UI? Now is this for LocalOnly text fields in your dash/localuserspace, or just something drivent o be local only to you.

**Comment by LewisSnow** [comment]
UserSpace UI so the Dash, Friends, ect

**Comment by Frooxius** [comment]
This was technically problem with the setup, the Button component you had on the keyboard had the "ClearFocusOnPress" enabled, which would clear the current userspace focus anytime you pressed a key, making the keyboard disappear.

In 2020.6.16.1053 I've made all the Virtual Key components automatically clear this property when they're present on the component, which fixes this behavior.

Thanks for the report!
