### ISSUE TITLE
Large items parenting to toolshelves

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#692]
The recent change in logic to toolshelf behavior in 2020.6.16.1053 has caused an issue in which snappers will attach to a toolshelf instead of the snaptarget they're associated to while the snaptarget is under a user.

It appears as if the snap target's collider somehow extends the effective range of the toolshelf.

This issue was reported to me by Zane, and investigated by him, Zyro, and myself.

https://cdn.discordapp.com/attachments/598212542938218506/722538027750129734/2020-06-16_12-45-29.mp4

**Comment by shiftyscales** [comment]
This was fixed in the 2020.6.16.1192 hotfix.

**Comment by shiftyscales** [comment]
This issue is still occuring on the latest patch 2020.6.18.1194. In particular it happens when grabbing the full-body avatar calibrator table.

**Comment by guillefix** [comment]
This also happens when grabbing the streaming camera.

**Comment by Frooxius** [comment]
I have a fix for it coming, but it's currently held up by the new Radiant Dash, sorry! Should be good once that comes out though.

**Comment by shiftyscales** [comment]
Fixed in 2020.7.1.26.
