### ISSUE TITLE
XiexeToon is transparent with ScreenSpaceReflections enabled

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#697]
Reported by Fenrir#8615, XiexeToon is transparent in forward-rendered cameras.
![2020-06-18 09 47 09](https://user-images.githubusercontent.com/54213390/85049281-51b88e80-b149-11ea-91a7-00490bd66ac3.png)

**Comment by Frooxius** [comment]
What exactly do you mean by forward rendered cameras? Xiexe should always be rendered in forward, as it doesn't support deferred.

**Comment by shiftyscales** [comment]
Nevermind- I was apparently off-base here. It is looking to be an implementation issue on the Neos Camera that is in the Neos Essentials. Something about the way it is setup compared to the normal streamer cam it would appear.

**Comment by shiftyscales** [comment]
I found it. On the MainCamera ScreenSpaceReflections are turned on. While they are on, it causes Xiexe to render transparent. So it is a rendering issue too. Photos captures of Xiexe while ScreenSpaceReflections are enabled exhibit this issue.

**Comment by shiftyscales** [comment]
Should be fixed in 2020.7.1.26.

**Comment by shiftyscales** [comment]
This is reportedly still an issue.
