### ISSUE TITLE
Default DynamicBoneChain IsGrabbable to Enabled

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#698]
For a large number of use-cases, IsGrabbable is preferable to have enabled as it enhances the degree of interactivity with dynamic bone chains. Setting this property to enabled by default will help speed up the setup time, and I believe would be a preferable default for a majority of use-cases where interactivity is preferred.

**Comment by Frooxius** [comment]
This can be done, but I've originally disabled it, because if you're setting it up on an object you want to grab, this will result in the object no longer being grabbable, because you end up grabbing the dynamic bone chain instead.

I can make it default on, as in most cases that shouldn't matter, but it will cause some confusion in  some cases.

**Comment by H3BO3** [comment]
It's funny cuz I initially made the request to switch it off default. Now that I've seen more applications for it I'm fine with this

**Comment by Frooxius** [comment]
Yeah, it was originally on by default, but caused some issues. There will be negatives with either case though, it just depends on which ones are more preferable.

**Comment by H3BO3** [comment]
Hey @shiftyscales do you have any further thoughts on this? I'm honestly on the fence about which is the better option.

**Comment by shiftyscales** [comment]
> 
> 
> Hey @shiftyscales do you have any further thoughts on this? I'm honestly on the fence about which is the better option.

Originally I considered it as a convenience option since I feel in a majority of cases that folks would want to enable it, it adds additional interactivity that people seem to enjoy about Neos' dynamic bones. E.g. whether on hair, ears, tails, or whatever else, being able to grab and hold onto them is pretty neat.

That said, it could also be potentially problematic in that sometimes dynamic bones being grabbed means you can't grab other things which I could see as potentially causing issues for those that just throw the components on without really taking the time to test or tweak them.

As Froox noted, there will be drawbacks and positives to it either way, @H3BO3. I don't think it's been a huge inconvenience not having the default changed since the creation of this issue, and others seemingly haven't brought it up/had issue with it either, so this issue could probably be closed out.

**Comment by H3BO3** [comment]
I will mention that if #1654 goes through then the grabbable issues would be much smaller
