### ISSUE TITLE
Undo/Redo

### ISSUE THREAD

**Issue by sirkitree** [Frooxius/NeosPublic#7]
Many times while editing a world I've done something undesirable or moved something by accident and wished there were a way to undo that action.

**Comment by pushstartvr** [comment]
yeah :)  I had to tell someone who came into my world randomly to "BE CAREFUL WITH THAT THING!!" when they equipped the texture gun :)

**Comment by Frooxius** [comment]
The Undo/Redo system is finally implemented as of 0.7.3! There's still lots of places to add the undo points, but the major ones have them and the framework is in there so it's easy to add, so I'm closing this now.

Feel free to open new issues for particular Undo/Redo features though!
