### ISSUE TITLE
Chirality node for Tooltips

### ISSUE THREAD

**Issue by H3BO3** [Frooxius/NeosPublic#700]
My multitool needs to access a standard controller node for the equipped hand. Currently, to get the equipped hand, I need to use a convoluted comparison setup with several nodes. If the multiplexer exposed the hand it was equipped to I could just feed that into the controller node.

**Comment by Frooxius** [comment]
Sorry, but this won't be added, it doesn't belong to Tooltip Multiplexer. It's just a component that forwards properties/actions to/from tooltips and those properties do not include chirality.

**Comment by H3BO3** [comment]
Edited to change request to a logix node to reference tooltips and get the chirality information that way.

**Comment by Frooxius** [comment]
Yes, I'll try to get those added soon! They would essentially accept ITooltip as an input and give you which hand has it equipped or if it's equipped at all. This way it's more general too, so it can be used with any tooltip.

**Comment by shiftyscales** [comment]
Added in 2020.7.1.26!
