### ISSUE TITLE
Default "use head direction for movement" to enabled

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#703]
For a majority of new users I've seen, those that have wanted this option enabled by default had really strongly disliked controller-relative movement. Head-relative movement could be more intuitive for users new to VR as well as you look where you want to go while holding forward.

The concept of controller-relative movement is better suited for users that are more advanced/used to moving around spatially I feel.

**Comment by Jeff07734** [comment]
While I agree with this for the purposes of walk mode, this makes fly mode unbearable. I don't know if anyone would want to use head direction for flying movement, and it's a common form of locomotion used.

**Comment by shiftyscales** [comment]
This issue has been made which could resolve that, @Jeff07734: #623.

I use head direction for flying too because again- you look where you want to go.

I've seen countless new users who think their controllers are broken because the concept of forward not being forward is foreign to them- especially if they've ever used any other controller in their life prior to that point. (Not that we need to adopt old conventions- but as a default setting, I think it will make things easier for a majority of new users than it inconveniences- especially if we allow setting it per locomotion type.)

**Comment by alexderpyfox** [comment]
I agree head movement needs to be default

**Comment by Frooxius** [comment]
Ok changed in 2020.7.4.755! The new welcome screen will have a selection when user first starts Neos in the future.
