### ISSUE TITLE
Add Particle Axis/Roll Locking

### ISSUE THREAD

**Issue by Enverex** [Frooxius/NeosPublic#704]
This is mostly a VR specific feature. It stops particles rotating with the user's head so that they maintain their orientation. It's implemented in Unity as such...

![image](https://user-images.githubusercontent.com/958670/85202772-be29be00-b300-11ea-8fc5-8fc6e4b179d4.png)

As it stands, if you're using it for smoke, clouds or other such objects, you'll see them rotate as you move your head which both looks and feels very strange.

**Comment by Frooxius** [comment]
Huh this is really weird, particles in Neos don't shouldn't rotate with your head by default, I certainly don't on my end. Do you have a sample particle system that's doing this in Neos?

There's a property called Alignment on the ParticleStyle in Neos, it should be set to "Facing", which will ignore the head roll. Can you verify it's set to this value for the problematic particle system? Perhaps it was changed by mistake.

In any case, this is already supported and should be the default.

**Comment by Enverex** [comment]
Both appear to exhibit the same problem.

https://discordapp.com/channels/402159838827905024/439422161657135106/725808168273182801

**Comment by Frooxius** [comment]
Fixed in 2020.7.2.150, thanks!
