### ISSUE TITLE
Nonuniformly-scaled parent slots causing incorrect/skewed global scaling on grab/release

### ISSUE THREAD

**Issue by H3BO3** [Frooxius/NeosPublic#707]
I'm not exactly sure what causes this but it seems very replicable. Just make a new box and scale it nonuniformly on one of the axes (Y axis in my tests), then parent another object under it and pick up/rotate the child object. Upon releasing and thus reparenting the bug usually occurs. It seems that the global position is not being maintained correctly when the reparenting happens, or similar.

This was initially reported by Sabby Life but we had thought it was something with the avatar.

![2020-06-19 23 22 34](https://user-images.githubusercontent.com/62123804/85212056-3a75ce80-b30c-11ea-9451-521e4bcb80da.jpg)
![2020-06-19 23 22 52](https://user-images.githubusercontent.com/62123804/85212057-3b0e6500-b30c-11ea-9a6a-2bb56b4590b0.jpg)
![2020-06-19 23 25 19](https://user-images.githubusercontent.com/62123804/85212058-3b0e6500-b30c-11ea-9382-8d87ad4beb0b.jpg)
![2020-06-19 23 25 38](https://user-images.githubusercontent.com/62123804/85212059-3ba6fb80-b30c-11ea-90c6-df4cc239970b.jpg)

**Comment by Frooxius** [comment]
This is normal behavior. Nonuniform scaling combined with rotations produces skewed transformation matrices in linear algebra. It's not something that's fixable, as it's a "problem" stemming from the mathematics itself. 

I'd strongly recommend to avoid using non-uniform scaling, it will lead to a lot of trouble. If you need to use it, only use it at the deepest level of the hierarchy with nothing underneath.
