### ISSUE TITLE
AND nodes breaking attached nodes and themselves when removing inputs

### ISSUE THREAD

**Issue by H3BO3** [Frooxius/NeosPublic#708]
As reported by Beaned, & nodes appear to cause exceptions in input nodes and even begin layering visuals when inputs are subtracted/added, even crashing people sometimes.

[https://discordapp.com/channels/402159838827905024/439422161657135106/724015796069728318](https://discordapp.com/channels/402159838827905024/439422161657135106/724015796069728318)

**Comment by shiftyscales** [comment]
It wasn't named the best, but this issue is a duplicate of #654. I've changed the title of that issue to this title, and will be closing out this issue, thanks for the report.
