### ISSUE TITLE
Unable to physically press buttons with the default avatar equipped.

### ISSUE THREAD

**Issue by Jeff07734** [Frooxius/NeosPublic#709]
The default avatar hands are unable to press any buttons by physically touching them with their index finger.

**Comment by shiftyscales** [comment]
In investigating this, I've discovered that the hands have no touch tip source. In investigating this, I've also observed that the hands have absolutely no colliders at all either.

**Comment by H3BO3** [comment]
I've noticed this before and communicated it a few times. I don't know if they need colliders but tip touch sources are pretty essential now with the laser tip touching being removed.

**Comment by Frooxius** [comment]
Thanks for logging this. This is because the physical touch is currently tied to VRIKAvatar, so it's not present correctly on the floating head and hands. I need to rework the system a bit so it's more general to fix this.

**Comment by H3BO3** [comment]
Could I get more priority on this? I have a head and hands avatar I'm trying to set up and the tiptouchsources don't work on it.

**Comment by Frooxius** [comment]
I'll try to fix it soon!

**Comment by Frooxius** [comment]
Fixed in 2020.7.5.788, should work well now!
