### ISSUE TITLE
Labels on Tooltips

### ISSUE THREAD

**Issue by sirkitree** [Frooxius/NeosPublic#71]
From Johansome in Discord:
> I am still learning all the tool tips by sight, but if they had a permanant small text label - sort of like the math tooltip has that division sign, it would be a big help.

Personally, I'm not sure about a permanent one, but maybe when you touch it, before you double grip.

**Comment by Frooxius** [comment]
Yeah, I was thinking about showing some kind of basic info when you pick up the tool for the first time. Like a quick description of functionality with basic controls.

**Comment by Simulacron3** [comment]
Maybe a permanent label that shows when a tool is not attached and is hidden when attached?

**Comment by Frooxius** [comment]
This is now done as part of the contextual tutorial system.
