### ISSUE TITLE
Deleting a demultiplexer with a display node freezes the game

### ISSUE THREAD

**Issue by art0007i** [Frooxius/NeosPublic#710]
Replication:
1. Create a demultiplexer of any type that can be displayed with a display node (I have tried using bool, int, float, string and int2)
2. Plug one of the outputs into a display node
3. Delete the demultiplexer
Example setup:
![image](https://user-images.githubusercontent.com/19620451/85223718-2e017c80-b3c5-11ea-81dc-46de8ccdbcd9.png)

**Comment by InsaneGrox** [comment]
Confirmed to happen both in desktop mode and VR

**Comment by Frooxius** [comment]
Thanks for the report. I've investigated this got a fix coming in the next build. I found out that this is actually the same cause as this issue: https://github.com/Frooxius/NeosPublic/issues/654, so I'm closing this one as duplicate, I'll close the other one when the fix comes out!
