### ISSUE TITLE
Integrate the MikktSpace tangent calculation

### ISSUE THREAD

**Issue by Frooxius** [Frooxius/NeosPublic#712]
Neos currently uses relatively simple algorithm to calculate tangents on meshes, which can lead to visual artifacts.

Integrating the MikktSpace algorithm instead should provide significantly more robust results, as this algorithm is adopted by many other tools and engines.

The reference implementation is available here in C code: https://github.com/tcoppex/ext-mikktspace

This could either be compiled to a native library with .NET wrapper, or ported over to C#. The second one is going to be a lot more laborious short term, but should be significantly more performant and portable, as the API relies on callbacks to return the data. A custom wrapper specific to Neos could work too, but the library would need to be compiled for different platforms that Neos needs to run on (although this should be relatively easy too, as it doesn't really have any sort of dependencies).

**Comment by Frooxius** [comment]
Added natively in 2020.7.15.1186! It's now default for newly imported models and can be applied to any mesh through the inspector by recalculating its tangents.

Since there wasn't a .NET wrapper available for the algorithm/library, I made one and made it opensource for others to use too: https://github.com/Frooxius/Mikktspace.NET

**Comment by Enverex** [comment]
> It's now default for newly imported models and can be applied to any mesh through the inspector by recalculating its tangents.

Would it be possible to get a "Recalculate all" option in the optimisation wizard to ensure all models in a world are correct? As doing this on a larger scale is almost impossible.

**Comment by Frooxius** [comment]
Yes, that's pretty quick to add, I'll add it in the next build.
