### ISSUE TITLE
IsCharacterOnGround node seems to not sync properly

### ISSUE THREAD

**Issue by Hayden-da-Serg** [Frooxius/NeosPublic#714]
While testing with Gearbell, I found out that the IsCharacterOnGround node under Physics doesn't seem to update properly for any user that's not the user it's looking at, an example is that I have my avatar set to curl the toes if I'm off the ground, however for every user except me the toes are constantly curled if I'm on the ground or not. The same also happens if the node is plugged into an Updating Relay.
According to Gearbell, this was fixed a while ago, but it still seems to be an issue.

**Comment by H3BO3** [comment]
This is because character physics are calculated locally. This value is one of the ones that doesn't sync to everyone else because it'd be unnecessary overhead, and a replication will likely have to be forced through impulse generation.

**Comment by shiftyscales** [comment]
GearBell fixed it by updating her Logix to include a boolean latch to make the value syncable, you can use a fire on true to set, and fire on true ! for reset.

**Comment by shiftyscales** [comment]
To quote Frooxius: "The character collider is only updated by the simulating user. And only the updating user ever populates the support data, which is used to check if the character is on the ground."
