### ISSUE TITLE
[Headless] Please prune hopefully unneeded dlls (such as UnityEngine.dll) from the headless payload

### ISSUE THREAD

**Issue by Earthmark** [Frooxius/NeosPublic#719]
So this is an awkward bug, but it has to do with getting GRPC working with Guillefix.

It turns out GRPC has [checks internally at `Grpc.Core.Internal.PlatformApis`](https://github.com/grpc/grpc/blob/master/src/csharp/Grpc.Core/Internal/PlatformApis.cs) to see if it's running under unity, that way it can prepare client and server code based on the environment. However this check forces a type lookup for `UnityEngine.Application` in the assembly `UnityEngine`. In normal Neos context this is fine, we're running in unity, but in headless mode the runtime takes this as a cue to load `UnityEngine.dll`. Then grpc reflects and invokes the unity 'external/free' property at `UnityEngine.Application.platform`. The headless isn't running in a unity context, so this explodes with `ECall methods must be packaged into a system module.`, causing the type constructor for `Grpc.Core.Internal.PlatformApis` to crash, causing GRPC to become unusable. 

The workaround for Guillifix: Delete UnityEngine.dll from the headless server folder, so the assembly lookup fails and the type check shows up as not being in a unity context.

Requested permanent workaround: Avoid distributing UnityEngine.dll (and related dlls).

This is also tracked in the [GRPC github](https://github.com/grpc/grpc/issues/23334).

[Guillefix's code, this may be different than fixed version](https://github.com/oxai/vrai/tree/master/environment/neos/TeachableNeos)

**Comment by Frooxius** [comment]
Should be cleaned up in 2020.7.2.150, thanks!
