### ISSUE TITLE
Attach Sprite node fails to detect existing duplicate components

### ISSUE THREAD

**Issue by Zyzyl** [Frooxius/NeosPublic#720]
New StaticTexture2D and SpriteProvider components are generated under the Target slot regardless of whether the GetExisting input is True/False. Easily replicated by firing the node twice with identical inputs. I assume this is a bug as the behaviour is inconsistent with the other Attach * nodes.

**Comment by Frooxius** [comment]
Fixed in 2020.7.2.150, thanks!
