### ISSUE TITLE
Add setting to opt-out of session thumbnail generation and upload

### ISSUE THREAD

**Issue by H3BO3** [Frooxius/NeosPublic#721]
Requested by Syri, a way to opt out of locally capturing images for sessions the user is in. This would relevant to security concerns regarding unreleased/proprietary projects that are only locally visible to the one user, for the purposes of field testing before release and preventing people making ripoffs of said projects if they happen to come across them in a thumbnail. This would likely be more relevant as Neos' userbase increases.

**Comment by Frooxius** [comment]
This is already done by setting the world to Private. When the world is set as Private, it won't upload any thumbnails to the cloud.

**Comment by shiftyscales** [comment]
If one wishes to work on a confidential project, they should only be doing so with users they are fine having access to it. Privacy can be taken care of either via setting their session to "Nobody/Invited users" or enabling "Don't show in session lists" as this won't transmit the thumbnails generated to the cloud servers.

**Comment by H3BO3** [comment]
Those were points I brought up, this would be for field testing scenarios of locally-visible items. I understand if there are other reasons but I don't want the initial context to be misunderstood
