### ISSUE TITLE
From Beta  DANGER build 

### ISSUE THREAD

**Issue by peterthethinker** [Frooxius/NeosPublic#722]
testing the new facets 
9/10  good to go  Cept  for a few small fatal flaws . 

If you Try to  make a dupe of the panel

IE   grab it and then use the wrist menu . It  will super-lag the game and then you have  2 of them  Z fighting .
I tried to  Delete one and It ended up  removing both and the only way  to  get out of neos was to  use  task manager to quit .

Perhaps IF its doable  you can block these items from getting dupped and removed till its mechinizum is more robust. 

part 2

you aldealy probley know this but the   facet  re -arrange is still buggy

Can that be stable  prior to main build. ?

I am aware of the roadmap and  I dont expect new UI facets on the  inital  Pub  release  but  What facets we DO have .It would be nice to  re arrange them  .  IE   stuff on the home  panel . 

and not have it break. 

Peter

**Comment by shiftyscales** [comment]
Facet rearranging will continue to be worked on, and will be released in a subsequent update once it is ready.

Duplicating the dash was fixed in the nightly. Thanks for the reports!
