### ISSUE TITLE
Creating a ValueEqualityDriver component of type Slot instantly crashes the program

### ISSUE THREAD

**Issue by AMonsoonofBabies** [Frooxius/NeosPublic#724]
I stumbled upon a situation where I tried making a ValueEqualityDriver component of the Slot type, and even though Slots are considered as references and not values, it provided an option to make one. Upon doing so, the program instantly freezes and is irrecoverable. The reproduction steps are simple enough: just go through the motions to attach a ValueEqualityDriver component to any slot, and put in FrooxEngine.Slot as the type. Selecting the prompt will crash the program.

I was informed by @ProbablePrime that this component type exists because of how it used to work a long time ago, or something like that. While I'm unsure as to the reason why this is possible to do, it seems rather dangerous as a consistent way to brick someone's program. It is unclear to me if it happens to only one user or not, but I assume it would happen to everyone in the world. (I discovered this bug while I was alone in a private world, not headless)

I will attach the log of the session, in case it holds relevant information.
[DESKTOP-MD1G9UR - 2020.6.19.941 - 2020-06-29 11_19_13.log](https://github.com/Frooxius/NeosPublic/files/4847663/DESKTOP-MD1G9UR.-.2020.6.19.941.-.2020-06-29.11_19_13.log)

**Comment by ProbablePrime** [comment]
Thanks for the tag.

So back in the day you could make a "ValueField<T>" with a type of FrooxEngine.Slot and it would crash Neos. 

I thought this might be a similar bug.

Here's the patch notes when ValueField was fixed: https://discordapp.com/channels/402159838827905024/469131434628612116/615459713605304330

**Comment by Frooxius** [comment]
Added a guard in 2020.7.2.150, thanks for the report!
