### ISSUE TITLE
Modification Request: Add a session Joiner to the MTC Avatar Creator Room

### ISSUE THREAD

**Issue by GearBell** [Frooxius/NeosPublic#726]
We've come across lots of new users at this point who went as far as that robot avatar creator room but then had no idea how to get to anyone else in the rest of the game. It has been defended too much that the new users just have to go back to spawn to find the menu - but that "common knowledge" doesnt occur to anyone. Can there just be a permanent session joiner in that room for them to openly see so they can join the rest of neos after they are done? no fancy menus over organized under fancy interfaces, just drop one in the world next to the mirror or something and save the world so the rest of the versions update. "How do i get out of here?" has become way too common in there and doesnt give neos a good impression.

**Comment by shiftyscales** [comment]
The MTC will undergo considerable revision once the new UI has been released, and the issue of session visibility will be resolved via rework of the world browser, and more prominent UIs for joining sessions on the dash.

**Comment by ProbablePrime** [comment]
Seems quite easy to add a session plate to that world. Im not sure who has "save" rights but should be quite easy :)

**Comment by shiftyscales** [comment]
It isn't actually just as simple as editing the existing world, and saving it. There is a versioning process, and the modified world also needs to be edited in the code/shipped as a new update, @ProbablePrime.

As such because we need @Frooxius's involvement, we also usually like to batch other changes together.

**Comment by ProbablePrime** [comment]
Hmm is the world and its assets shipped with the build? If that's the case I understand.

However, I thought it was just a record like all of my worlds. As for versioning, I understand versioning but make world changes all the time including to worlds owned by Neos' Group system which I assume the MTC is saved in. Therefore I'm not entirely sure what you mean.

**Comment by shiftyscales** [comment]
It's my understanding that is the case, yes- the worlds/assets are shipped with the builds, and the world itself is owned by an internal group for the team.

**Comment by TehTurk** [comment]
Then doesn't that mean when the world is loaded/accessed it loads from the cloud record? I thought this would be the typical case regardless.

**Comment by sirkitree** [comment]
Sidenote:
This may be another thread somewhere, but I'd be interested in seeing your versioning process. We've tried a few ways with various success/failures and recommended best practices for such things would be a boon (video/wiki).

**Comment by TehTurk** [comment]
Agreed. Plus with the new Influx, the Avatar World is the most common one people will access or use.

**Comment by mralext20** [comment]
I belive this can be closed now that the new tutorial goes over how to join other users, and the worlds menu is included in the dash more prominently.
