### ISSUE TITLE
Metaverse Training Center Update: The Radial Hand Menu

### ISSUE THREAD

**Issue by sirkitree** [Frooxius/NeosPublic#729]
The Radial Hand Menu guide is now out of date and needs an update.

![20200701081132_1](https://user-images.githubusercontent.com/28543/86262425-b544b200-bb74-11ea-889c-058a058d755b.jpg)

Suggested text:
"Use the Scroll action or rotate your wrist to navigate the radial menu"
could be
"Hover over an item and pull your trigger to select an option"

"By pressing the blue item (old icon) found on the radial menu you can change your locomotion mode"
could be
"My pressing the green item (new icon) found on the radial menu, you can change your locomotion mode."

**Comment by ProbablePrime** [comment]
With the new MTC out I think we can close this :)
