### ISSUE TITLE
General World Hyperlink component

### ISSUE THREAD

**Issue by Frooxius** [Frooxius/NeosPublic#73]
A component for entering new worlds without specifics of the WorldOrb, to allow creation of portals, teleporter pads and other means of entering new worlds.

Allow arbitrary methods of triggering - some common ones (such as entering certain region) and general one, so a custom method can be triggered by LogiX for example.

**Comment by shiftyscales** [comment]
Closing the issue as this work has been completed. A set of `World` components, and Logix has been developed, and have already been implemented in user-made, and Neos Team creations including the MTC teleporter.
