### ISSUE TITLE
Unused asset cleanup removes animations from imported objects.

### ISSUE THREAD

**Issue by DanteTucker** [Frooxius/NeosPublic#731]
**The problem**
If the world has the Cleanup Unused Assets setting on it will delete all but the first AnimationProvider as the rest are not referenced by anything. It's not clear to users why the animations are missing. While you can turn off the asset cleanup setting to solve this most people would not come to that solution on their own. 

**Solution?**
Perhaps the AnimationProviders could be placed in the object's slot along side the Animator instead of Assets. This would also make it easier for users to find them. As it is now they are kind of hidden.

I have included my testing object with two animations: [MultiAnimDemo.zip](https://github.com/Frooxius/NeosPublic/files/4866196/MultiAnimDemo.zip)

**Comment by Frooxius** [comment]
This is already supported. In the Advanced Import settings, check the "Place Assets on Object" option, which will place all assets on the object itself, rather than on shared asset list.
