### ISSUE TITLE
Possible bug with new Tooltip In Use node

### ISSUE THREAD

**Issue by Zyzyl** [Frooxius/NeosPublic#732]
The Tooltip In Use node only seems to output True when primary fire is pressed / held. 
It seems to always stay False even when secondary fire is pressed with tips where this should be relevant. (Tested with a RawDataTooltip where the UseSecondary field was checked, as well as with a standard LogiX tip).

I'm not 100% sure exactly what this node is intended to do, but this seems unlikely to be correct behaviour.

**Comment by Frooxius** [comment]
This is correct behavior. The node doesn't really do anything on itself, it just reports the "InUse" property of tooltips. They report this when the primary action is being used in some way (the logic is specific to each tooltip), it's used to block userspace interactions while the tooltip is currently doing something that shouldn't be interrupted.

**Comment by Zyzyl** [comment]
Thanks for clarifying. Added a note on the node's wiki page
