### ISSUE TITLE
Permission system bug

### ISSUE THREAD

**Issue by Zyro1331** [Frooxius/NeosPublic#734]
You can still spawn files from the file browser when you are spectator.

**Comment by shiftyscales** [comment]
You can open the import dialogue, but you shouldn't be able to interact with it. Is this not the case, @Zyro1331?

**Comment by Zyro1331** [comment]
You can't click the import dialogue, however things like audio and text files can be imported no problem.

**Comment by shiftyscales** [comment]
I see. Thanks for clarifying. I guess we can see what @Frooxius can come up with. There's probably some mechanism through which spectators could possibly be further restricted in what they can bring into the world. But that might also be more in the scope of the hard permissions system, as it should be able to reject changes to the datamodel like that I would think.

**Comment by Zyro1331** [comment]
Alright thanks!

**Comment by Frooxius** [comment]
Fixed in 2020.7.4.755! Thanks!
