### ISSUE TITLE
Twitch Panel Allows Any Neos Formatting

### ISSUE THREAD

**Issue by Enverex** [Frooxius/NeosPublic#735]
An example from a stream earlier today:
![image](https://user-images.githubusercontent.com/958670/86496841-01f7db00-bd77-11ea-8fd8-c5356bccdd0d.png)

"<size=9999> E </size>" is what produced that giant E (you can only see the top of it there). Before that was also some other oversized text from a size 999 instead.

**Comment by Frooxius** [comment]
Hmm looks like a corner case, when the Twitch chat message doesn't contain any emote sets, which skips the Neos-side parsing and just uses the raw message. Should have a fix in the next build!

**Comment by Frooxius** [comment]
Fixed in 2020.7.4.755!
