### ISSUE TITLE
TargetUser.LocalVolume no longer functions

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#742]
As initially reported by Jeana, and investigated by myself, and Coffee, the local user volume sliders on the session menu, and the streamer camera no longer function.

Additionally, it's been found that the 'mute' button sets the volume to 0 instead of performing a mute like the mute button on the streamer camera does.

The mute button on the streamer camera works, but the local volume sliders there also don't work.

It is believed this issue occurred as a result of the recent change to the mute behavior.

**Comment by Frooxius** [comment]
Fixed in a patch 2020.7.6.154 thanks!
