### ISSUE TITLE
Newly saved avatars disable TipTouchSource on dequip

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#743]
Avatars saved within the last day after the change to enable tiptouchsource on bodyless avatars have caused the TipTouchSource to disable on dequip. Avatars saved prior to the change are not affected, and will work as intended.

Steps to replicate:
- Save your current avatar with working/enabled TipTouchSource to your inventory

When the avatar is dequipped, like it is during saving, and while switching out of it and into another avatar, the TouchTipSource will disable, and remain disabled until the user respawns, or manually re-enables it.

It seems like it could be an exception- but it isn't shown in the log.

Issue reported by Ardes, and GearBell, and investigated by myself, ProbablePrime, and H3BO3.

**Comment by Frooxius** [comment]
Fixed in a patch 2020.7.6.154 thanks!
