### ISSUE TITLE
Idea for the new dash.

### ISSUE THREAD

**Issue by candypheonixIO** [Frooxius/NeosPublic#744]
So, I want to make the dash feel like it forms to the user, _somewhat keeping with the theme of why facets are being made for it_. The way I want to do that is to simply change how the dash is curved; instead of it being statically set by the user, it's instead dynamically changed based on distance [example](https://youtu.be/_awAvlZEntU), and a bias that determines how much it will curve once it's at the minimum distance to the user's head.

A good example can be found with how XSOverlay does its curved panels.

**Comment by Frooxius** [comment]
If you want to add this functionality to the userspace dash, you have most things you need for that already. The curvature can be driven with LogiX in arbitrary ways. However a key component that's missing is ability to save the customized dash itself, which is coming later on in the pipeline (saving workspaces and layouts is first). I'm not sure if that's the functionality you're requesting right now?

It could implemented as official feature too, probably as an optional toggle, but unlikely before the settings UI is redesigned. I have some plans to a quick way to adjust the curvature manually for each user, to better suit their preference.

**Comment by Frooxius** [comment]
2020.7.24.446 build now has everything necessary so anyone can build facets that provide this behavior. The AlwaysOnFacetModule lets you run any logic even when a different dash screen is selected and RadiantDashStateSync let you control the curvature of the dash.
