### ISSUE TITLE
Trigger haptics in hierarchy incompatible with nearest user hand

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#747]
With the recent change to nearest user hand to use the hand body nodes, trigger haptics in hierarchy no longer will fire the haptics on controllers.

Reported by Rukio, this has broken gadgets which made use of this node combination including the 'shocking Pikachu' made by GearBell.

Technically everything is working correctly, but the hand body node doesn't trigger haptics (which make sense.)

It can be worked around by switching it to Trigger Haptics On Controller utilizing the chirality output of the nearest user hand.

**Comment by Frooxius** [comment]
Should work in 2020.7.10.1281 now, thanks!
