### ISSUE TITLE
HTTP POST should allow empty content

### ISSUE THREAD

**Issue by mralext20** [Frooxius/NeosPublic#748]
Hello, as per this stackoverflow and IEFT mailing list, POST requests can have empty bodys
https://lists.w3.org/Archives/Public/ietf-http-wg/2010JulSep/0272.html , https://stackoverflow.com/questions/4191593/is-it-considered-bad-practice-to-perform-http-post-without-entity-body

however, the neos post request node does not work with nothing plugged into its bottom two (media type, content) inputs. can this be fixed?

**Comment by Frooxius** [comment]
This is strange. There's nothing in the code that would stop it from working with empty content. Do you have a log from when you tried to use it? There might be something else causing the problem there.

**Comment by mralext20** [comment]
https://this-is-a.stale-me.me/i/ymtw.png ; 
[ALEXDESKTOP - 2020.7.6.154 - 2020-07-06 21_54_25.log](https://github.com/Frooxius/NeosPublic/files/4882748/ALEXDESKTOP.-.2020.7.6.154.-.2020-07-06.21_54_25.log)

**Comment by Frooxius** [comment]
Thanks! Did you shutdown Neos before sending the log though? It just ends abruptly without anything relevant information.

**Comment by mralext20** [comment]
yep, uploaded log before sending. do you need to full log?

**Comment by mralext20** [comment]
[ALEXDESKTOP - 2020.7.6.154 - 2020-07-06 21_54_25.log](https://github.com/Frooxius/NeosPublic/files/4882841/ALEXDESKTOP.-.2020.7.6.154.-.2020-07-06.21_54_25.log)

**Comment by Frooxius** [comment]
Thanks! I found out what it is. The problem here is that by not having it plugged the body is not empty, but it's null (missing completely), which is not allowed. If you plug an empty string there it will work.

I have a fix coming in the next build which will default to empty body rather than null.

**Comment by Frooxius** [comment]
Should be fixed in 2020.7.9.1241, thanks!
