### ISSUE TITLE
Even if Postprocessing is turned off, AO is displayed on RenderTexture

### ISSUE THREAD

**Issue by orange3134** [Frooxius/NeosPublic#749]
Ambient Occlusion remains visible on RenderTexture even if I turn off Camera's Postprocessing.

Replication steps
1.Spawn NeosCamera and open Inspector.
2. Turn off Post processing of Main Camera.
3. AO is still displayed on the preview.

(Also, if Postprocessing is turned on/off repeatedly, AO will be drawn overlapping and FPS will drop.)

Video
https://youtu.be/w_2UE0qkeOI

It is a less urgent issue as there are no problems with the photos taken.
However, this is a problem if I want to shoot a video with Postprocessing off.

**Comment by Frooxius** [comment]
This is a good find, fixed in 2020.7.10.1281. Thank you!
