### ISSUE TITLE
Rename RigTransferTooltip to AvatarMeshTransferTooltip

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#750]
This name change would be more accurate to the functionality and intended use of the tip. When using it, the rig is not being transfered but rather the mesh. E.g. changed weights/different outfit, etc.

It would help avoid some confusion over how the tool works, and how to use it. E.g. secondary to copy the avatar mesh, primary to paste it.

**Comment by TehTurk** [comment]
Don't know if this is a github, wouldn't you be able to just rename the object in the essentials Shifty? There are a few tips that aren't one to one with their name scheme.

**Comment by shiftyscales** [comment]
The saved copy in the essential tools could be changed- but the tips are still named after their components, e.g. the RigTransferTip component.

**Comment by Frooxius** [comment]
I'm not sure about this name, because it's not quite accurate either. The tool isn't specifically for avatars for one. And it doesn't just transfer the mesh, but new parts of the rig as well. For meshes, it's specifically designed for rigged meshes, hence the name. Perhaps "RigMeshTransferTooltip"?

**Comment by shiftyscales** [comment]
That could potentially be a better option for now. Although if it's transferring parts of the rig too- that does make things a bit more complex than I had figured based on how I've seen it perform.

**Comment by Frooxius** [comment]
Yeah. Typically it won't transfer parts of rig that are already present, but any new additions (e.g. you have new attachments with bones, like glasses on the mesh) will get transferred.

There are also future improvements to consider, I'd like to expand it more as well so it could even transfer some alterations to the rig itself and such.

RiggedMeshTransferTooltip could work perhaps?

**Comment by shiftyscales** [comment]
That's definitely a lot more accurate I think. I did notice that it can grab other rigged meshes, and apply them even if it doesn't really make much sense because the hierarchy is entirely different. E.g. it could grab H3's multitool mesh and apply it.

Being able to transfer bone positions would be a pretty big improvement too in the longer-term for the tool, as it makes it much easier to re-rig pre-existing avatars by adjusting their bone positions e.g. in Blender, then importing the updated rig. Because in those cases, there actually isn't any newly added bones, etc. Just the positions are different.

**Comment by shiftyscales** [comment]
This tip was renamed recently to RigMeshTransferTip in 2020.7.11.1366.
