### ISSUE TITLE
ComponentCloneTip does not clear the name when "Clearing Template"

### ISSUE THREAD

**Issue by BlazeVR** [Frooxius/NeosPublic#751]
Hey Froox, just a minor issue that the ComponentCloneTip does not clear out the name to  **---**  when using the "Clear Template" hand menu option. (It does work on the RigTransferTip though.)

**Comment by shiftyscales** [comment]
Is it just the name that isn't cleared? If you try to add a component after clearing the template, does it still get added anyway, @BlazeVR?

**Comment by BlazeVR** [comment]
Yeah, just the name not clearing to --- again. Else it's empty so applying has no effect as intended.

**Comment by shiftyscales** [comment]
Nice. That should be an easy one then I would think. Thanks for reporting it!

**Comment by Frooxius** [comment]
Should be fixed in 2020.7.10.1281 now!
