### ISSUE TITLE
Login/registration screen not visible in non-local home worlds

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#752]
The underlying issue:
- Some new users have reported having a blank login/registration screen

Probable causes:
- The login/registration is pressed but the user switches to a new world
- While inside of the new world, e.g. the MTC, pressing the login/register button facet will shift focus to the login screen already opened (and blank) but not refocus the local home
- The login screen remains opened until 'cancel' is pressed

We've had a couple of cases of this issue occurring within the last couple of days. Perhaps the login screen will auto-cancel/close if the user switches to a different screen on their dash and/or switches worlds?

**Comment by Frooxius** [comment]
Fixed in 2020.7.11.1366, thanks!
