### ISSUE TITLE
Feature request: Locomotion height - active scaling to head height.

### ISSUE THREAD

**Issue by DeliriousJax** [Frooxius/NeosPublic#753]
I've been having issues going through doors because I have my avatar head tracking offset lowered and my avatar scaled back up to a more normal height to other players. However, this means that the top of my avatars physical locomotion pill collider is drastically high above my head and makes it impossible to travel through certain doors or easily in low ceiling areas.

It would be nice if the physical pill collider height automatically adjusted to the height if the head proxy automatically on spawn or dynamically adjusted on the fly via a driver so people with taller avatars can also duck under objects in order to travel through lower ceilings/doors. The driven height would add a ton more immersion opportunities, as well as let people have tall avatars but not the need to unlock their scale and scale down just to go through doors.

Hayden does this on his avatar by injecting a physical locomotion of his own making into his locomotion options and his example proves that driving the pill collider height works very well!

**Comment by shiftyscales** [comment]
This issue already exists via #585:

A relevant quote from Frooxius:

> Unfortunately this is actually pretty complicated. Changing the height of the character controller dynamically is very inefficient operation with the current physics library, which is why it's not done at the moment.
> 
> We plan on upgrading to BEPU v2, which should be more efficient in this regard. Even if it's not I want to look to some good compromise there, but it'll have to wait until then.

It might work well- but it's innefficient. So for now, at you could use that method- but it's not recommended, and won't be fixed until a proper solution can be implemented.

**Comment by DeliriousJax** [comment]
Was a method to add a one time/spawn in settings adjuster to ones self discussed?

**Comment by shiftyscales** [comment]
If I'm understanding you correctly, that is something that can be taken care of via workspaces: #586.

> -- Private UI loadout can also be tied to settings (e.g. default laser status or item shelf visibility) as suggested by @DeliriousJax before. This would replace the old "physical mode", allowing you to make an "immersion" loadout

So you could use that mechanism of changing settings to adjust whatever arbitrary things you wanted changed in a particular workspace.

**Comment by DeliriousJax** [comment]
No, that kind of content would edit workspace toggles based on what the world already allows. The setting I'm talking about is what the world installs onto each person and these settings are sources from the world, not what the work spaces would control.

**Comment by shiftyscales** [comment]
What sort of settings are you talking about, exactly, @DeliriousJax? It will also be possible to have world-bound facets, and with regards to locomotion modules- that's also something that can be done already via Logix either on a per-world or per-avatar basis. (Sorry- I'm still not entirely clear on what you're asking for exactly...)

**Comment by DeliriousJax** [comment]
https://www.youtube.com/watch?v=A5-Tf7a5S5c&feature=youtu.be
here we go, i go over the issue here
