### ISSUE TITLE
Logix ++/-- write seems to have some sort of race

### ISSUE THREAD

**Issue by Earthmark** [Frooxius/NeosPublic#754]
I'll add more context to this if needed, but I'm on my phone at the moment and forgot about this bug twice so far. Gonna get it written out before I forget again.

**Situation**
A large number of impulses invoke a write increment or decrement on the same variable.

In my exact case I was load testing the http node. 
I had a localhost server listening to a port, and logix firing on update to send a request to that server.
To track the number of in flight requests I had a long that was incremented (with the ++ version of write) when the request started, and then was decremented (with the --version of write) when the request was served.

**What was expected**
The counter represented the number of in flight requests, if I set it from 100 requests per tick, then 0 requests per tick, the counter should go to 100 or above, and then fall back to 0 as all of the requests are resolved.

**What happened**
When the requests per tick count was raised to 100 or 1000, then back down to 0, the counter would reliably get stuck at a number above zero (sometimes 10s above or more).
When the value was starting at a low number of requests per tick it would return to 0, but a high number would not.

I think that it would reliably fail to return to 0 is because it's reliably exercising whatever race condition (least it feels like a race condition), where as a low number of requests per tick isn't enough load to reliably cause the behavior. I don't recall seeing it under a low load situation but I can test that if requested.

I can attach a picture of my logix circuit if it helps, and the server outputs were ignored so I don't think that affected anything, all the server did was respond with a 200 and a short string as quickly as it could.

**Comment by Frooxius** [comment]
This is *very* unlikely to be a race condition or even something with the ++/-- write nodes, since it's very primitive and there's not really room for that to happen, there's not even multithreading involved. 

When  you did the requests, did you use OnError output to decrement as well? If any of the requests end with an error, that might be the cause.

Alternatively did you run this in multiplayer setting? If multiple people ran the requests and wrote to the target variable, they might've end up overwriting the counter.

I'd need to see the setup and do some testing to see where they're getting lost otherwise.

**Comment by Earthmark** [comment]
I can't replicate it in a singleplayer world it seems, so this may be related to multiple people being in the world during the test, however here is t he logix used for the test.
![image](https://user-images.githubusercontent.com/1251609/87260907-fd16e380-c468-11ea-9ac0-66a8fd3bb4f1.png)

The upper number should represent the number of in flight requests but in that multiplayer session it did not. I'll do more testing related to this once I'm alive again.

Thanks for your patience, I'll poke again with an update later in the week.

**Comment by Earthmark** [comment]
Tried to recreate as a guest in a multiplayer world and it did not show the described issue, I guess something strange was happening with the original world or somethin!
