### ISSUE TITLE
UIX: Sliders can't go Negative

### ISSUE THREAD

**Issue by TehTurk** [Frooxius/NeosPublic#758]
Was trying to do some offsetting and found out you can't really flip the min and max in terms of negative values, was trying to do some Negative offsetting and I couldn't do this natively with the Slider.

**Comment by Frooxius** [comment]
What exactly do you mean by this? Are you talking about the Min and Max parameters or the Rect transform offsets? What was the intended goal?

**Comment by TehTurk** [comment]
Min and Max :0, I wanted the slider behavior to act inversely. I even tried with Power and the behavior still wasn't suitable.

**Comment by Frooxius** [comment]
Ah I see thanks! I'll make some changes that will let you do this.

**Comment by TehTurk** [comment]
Thanks Appreciate it!

**Comment by Frooxius** [comment]
Ok pushed in 2020.7.10.1281, should work well now!

**Comment by TehTurk** [comment]
Sorry to reopen! The Intended behavior of sliders going from 0 to -1 is there, but if I want say -1 to 0 this the issue. Currently I use this in conjunction with a scrollrect and I need to unpack it, -n and ++ to get the intended effect.

**Comment by Frooxius** [comment]
I don't understand the issue. -1...0 should work perfectly, even before, it doesn't care that it's negative. What results are you expecting?

**Comment by Frooxius** [comment]
@TehTurk Any update on this?

**Comment by shiftyscales** [comment]
I pinged him about this issue this morning, I'm assuming he might be at work or something similar, as he's not gotten back to me in DM either.

**Comment by TehTurk** [comment]
Sorry! Slipped my mind! Heres a video. https://streamable.com/a05xi8 Basically any negative value will cause it to be an issue. But maybe I'm misidentifying the source of the issue. It could be ScrollRect as that's what I'm driving from the Slider.

**Comment by candypheonixIO** [comment]
@TehTurk 
A scrollRect uses normalized values `0...1` that is why your slider/scrollbar "breaks" when you try to use a negative value.

**Comment by candypheonixIO** [comment]
If you need a reference at to what im talking about, just dissect some of my UIX items that have a scrollbar slider. Im simply jist driving the 0 to 1 default value from that to the scrollRect since the scrollRect position is labeled, "normalizedPosition"

**Comment by Frooxius** [comment]
Yeah, this is not a bug, ScrollRect needs values that are between 0 and 1 to work correctly. The actual slider value is updating correctly in the inspector, but for the scrolling it's clamped, so it effectively stays 0.

**Comment by TehTurk** [comment]
Understood. Thanks for the clarification!
