### ISSUE TITLE
Facets: Dash Edit mode should have a dedicated button

### ISSUE THREAD

**Issue by TehTurk** [Frooxius/NeosPublic#759]
Some of the default behavior conflicts with alot of common custom setups for controllers. For Example, most people will rebind their custom configs on Index Quite often, where Double Press A is jump, or menu, or something else because Joystick clicks are avoided on Index. I know an exit button was added, but I do feel there should be a consideration for a dedicated button in some form. The exit button works, but enabling should be an option too.

**Comment by sirkitree** [comment]
I agree with this. While we can't really worry about custom setups or program for the almost infinite permutations, having buttons could easily solve for this.

We have a facet button for the dash freeform, and the leaving of edit mode, having an button for entering edit mode also makes sense. Then these could be placed like other facets where you want.

**Comment by Frooxius** [comment]
I'm intentionally avoiding a button for now, because I don't want new users pressing it and trashing their dash right away, so having it more hidden under a shortcut should help in this regard. It could be perhaps later put into settings somewhere, so they don't trigger it right away.

If you want, you can already make your own button for this though. The component UserInterfaceEditModeSync has "EditModeActive" field. If you set it to true (must be in Userspace) it will enable the dash edit mode.

**Comment by H3BO3** [comment]
Could the double-click detection interval at least be boosted some, maybe to 0.75 seconds? I use Turk's rebinds and while I can double-click just over the threshold for that, it's still not fast enough to toggle the dash edit mode from what I can tell.

**Comment by TehTurk** [comment]
Hmm I'll make an edit button for it, but if h3b0's suggestion were doable that'd be more realistic. I thought originally it was something with steam VR input overriding but being able to adjust the timing threshold would be wonderful imho.

**Comment by mralext20** [comment]
Does the setting for double click interval in settings not have an effect on this?

**Comment by H3BO3** [comment]
@mralext20 Turns out it's something with @TehTurk 's Neos bindings that are preventing Neos from detecting the dash menu button is being held, thus not watching the other for the double click. I will work on making a button that is able to switch edit mode off and on though.

**Comment by Frooxius** [comment]
I'll have it use the double click interval from settings, that's a good idea! Hopefully that'll make it easier to trigger.

**Comment by TehTurk** [comment]
Thanks Froox! Hopefully this will let me pass through the edit mode with the jump input still.

**Comment by shiftyscales** [comment]
Can this issue be considered resolved? Custom dash edit mode buttons can be made, and the double click interval was implemented.

**Comment by TehTurk** [comment]
Yes this can, while I would still want a dedicated button in some form or some easier way to introduce facets because I still get people confused about how to use them.
