### ISSUE TITLE
Automatically set the newly created avatar in the active worlds

### ISSUE THREAD

**Issue by Frooxius** [Frooxius/NeosPublic#76]
When a new avatar is set active, the old one remains in the already opened worlds, which can be quite confusing.

However some mechanism should prevent this in case the user has already equipped a different avatar or has been assigned one by the experience, it might not be desirable to replace those.

**Comment by Frooxius** [comment]
Make sure it is also set in Local.

**Comment by shiftyscales** [comment]
This issue no longer seems relevant.
