### ISSUE TITLE
Facets: Sync Indicator should default to top bar

### ISSUE THREAD

**Issue by TehTurk** [Frooxius/NeosPublic#760]
This is so users who are new can see when something is actually saved/synced vs not. Right now you need to go back to the dash if you are unfamiliar with facet editing to check and this is an extra behavior that should be simplfied.

**Comment by sirkitree** [comment]
This is one of the first things I customized :) I agree that it would make sense as a default.

**Comment by Frooxius** [comment]
I've added it to the top bar by default in 2020.7.10.1281, thanks!
