### ISSUE TITLE
Grabbing facet caused me to respawn

### ISSUE THREAD

**Issue by candypheonixIO** [Frooxius/NeosPublic#762]
_note to self: save every change like in blender :)_

Simply grabbing a facet I spent several hours on, caused me to get force respawned, losing the facet being it was under my user when I was respawned.

And I'll try to recreate it when I have several hours and nothing important that I need to save.

**Comment by mralext20** [comment]
i believe this happens when the facet component has a unset _canvas.

**Comment by Frooxius** [comment]
I'm sorry to hear about the data loss, it's definitely prudent in general to save working versions periodically.

Unfortunately there's not enough information for me to do anything. Do you have log from when this happened? Or a way to reproduce this?

**Comment by candypheonixIO** [comment]
Yea, I'll send the logs over to Shifty

**Comment by Frooxius** [comment]
Thanks! Added guards in the appropriate places in 2020.7.11.1366 to prevent any unexpected errors in the grabbing system from propagating and causing the user to respawn.

The _canvas field itself is mandatory though and shouldn't be tampered with, it Facet won't work correctly without it.
