### ISSUE TITLE
CharacterController doesn't respect user height, or tracking offsets

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#763]
As reported by DeliriousJax, and investigated by myself, the CharacterController doesn't utilize the player's height as set in the settings, but rather seems to always default to a value of 1.9m.

Additionally, this value remains 1.9 even if a tracking offset is applied to the avatar, further exaggerating this effect as demonstrated by Jax in a video on issue #753.

If the CharacterController set the user's height as based off of their height value in their settings, and any tracking offsets applied, it would make the CharacterController bounds much more accurate for users.

**Comment by Frooxius** [comment]
We already have issue for this here: https://github.com/Frooxius/NeosPublic/issues/585 The answer is still the same, until we upgrade to BEPUv2 it won't get resolved.
