### ISSUE TITLE
Switch to a different MP3 decoder

### ISSUE THREAD

**Issue by Frooxius** [Frooxius/NeosPublic#77]
The current one has a lot of problems - some files are unsupported, some produce weird noise and sometimes there's even crash.

**Comment by Frooxius** [comment]
Swapped to NLayer, but this is problematic as well. It gets randomly corrupted when seeking, Reported the issue to original author: https://github.com/naudio/NLayer/issues/7

For now, Neos decodes the whole MP3 into memory first. This is not optimal, but until a better solution is found will work. 

I highly recommend using OGG Vorbis or FLAC instead when encoding files, they have better quality, are open and their implementations are pretty bug free.

**Comment by kris-w-dev** [comment]
@Frooxius  hi , Do you have a better solution now?    Neos?
