### ISSUE TITLE
VideoTextureProvider component stops working if it receives an invalid address as its URL

### ISSUE THREAD

**Issue by AMonsoonofBabies** [Frooxius/NeosPublic#771]
I have noticed that every time the VideoTextureProvider component receives an address in its URL field that isn't a valid YouTube video, Twitch stream, or other acceptable media address, it breaks, and it no longer accepts any valid addresses after that. If this broken component is then saved and spawned again, the new version is also broken.

Results can be replicated with the following steps:

- Start Neos and open a new world
- Create an empty object and place a VideoTextureProvider component on it
- Insert any valid video URL in the field as an example
- Grab the component and pull trigger to create an example display. Wait for the video to begin playing to observe that the component is functional
- Go to the URL field and modify it in some arbitrary way that results in an invalid address (I suggest a simple backspace at the end of the string). Observe that the component no longer renders, as expected
- Either re-enter the same valid address for the example, or use a completely new one. Observe that the expected video never renders

I have followed these exact steps myself, and the logs attached to this issue reflect the session during which I performed the steps.

[Player.log](https://github.com/Frooxius/NeosPublic/files/4910780/Player.log)
[DESKTOP-MD1G9UR - 2020.7.11.1366 - 2020-07-12 23_12_32.log](https://github.com/Frooxius/NeosPublic/files/4910781/DESKTOP-MD1G9UR.-.2020.7.11.1366.-.2020-07-12.23_12_32.log)

As this is so easily replicated, I believe this breaking of the component attributes to many cases where video players seem to stop working at random. I've tested this on a few publicly available tools, such as community made video players and the ones under Neos Essentials, and entering invalid URLs consistently breaks all of them. I believe more beneficial behavior would be for the component to continue accepting valid URLs even after receiving invalid ones.

**Comment by shiftyscales** [comment]
It looks like youtube-dl is throwing exceptions by trying to parse the invalid URL and propagates all the way up to the VideoTextureProvider. Thanks for reporting this!

**Comment by AMonsoonofBabies** [comment]
No problem! It's definitely one of those things that you'd think would be noticed sooner.

**Comment by Frooxius** [comment]
Fixed in 2020.7.15.1186  thanks!
