### ISSUE TITLE
the Set Global Rotation and Set Global Scale nodes should have saner defaults

### ISSUE THREAD

**Issue by mralext20** [Frooxius/NeosPublic#775]
as of right now, the default rotation from the global rotation node is not actually a 0,0,0 rotation, but closer to a 0,12,0 rotation. 

as well, the Set Global Scale node sets the scale to 0,0,0, instead of a saner 1,1,1.

**Comment by shiftyscales** [comment]
I'm not sure I'm understanding the issue. From testing it- it appears that Set Global Rotation just doesn't apply any rotation at all unless you explicitly add an input to it. So it just appears that there is no default value for it.

**Comment by TehTurk** [comment]
I would like if possible have the defaults be 0,0,0 for Pos 1,1,1 for scale, and 0,0,0 for Rot? It seems sometimes if there isn't an input it actually doesn't pass the pulse.

**Comment by H3BO3** [comment]
Yeah, defaults would be nice. Also, I notice that quaternion input fields on most nodes default to [0,0,0,0] (an invalid quaternion) rather than [0,0,0,1], so changes to other nodes for quaternion default values would be nice too

**Comment by Frooxius** [comment]
Changed in 2020.7.15.1186 thanks! Both Local/Global Set Rotation/Scale will now use identity values when not plugged in (Identity rotation and 1,1,1 scale)
