### ISSUE TITLE
Voice mute caused by session permissions should not be persistent

### ISSUE THREAD

**Issue by H3BO3** [Frooxius/NeosPublic#776]
If role permissions in a world cause someone to enter muted, it should return to the previous global state when they exit the session or switch to another. This has caused some confusion in circumstances where this permission is used, since they end up getting globally muted once they enter the session. I think the most succinct and robust solution is to make permission-based mute more of an override on the current global mute status, rather than changing the global status itself.

Obviously no change should be made to the global mute status if the user attempts to unmute themselves while muted by their role, or they would end up toggling something they couldn't see the state of.

**Comment by Frooxius** [comment]
Huh this is odd, the permission shouldn't touch the global mute status at all and only do it within the session, the same way the broadcast/whisper/shout are now tied to the session itself. Is this confirmed to happen? Any repro steps?

**Comment by H3BO3** [comment]
Whoops, thought it was pretty consistently described based on a report I got. I'll do some repro testing soon

**Comment by shiftyscales** [comment]
In testing this I believe it's working correctly. If a user is forced to mute by the VoicePermissions role, the mute toggle isn't engaged. The voice meter is active, but it's also red, suggesting their voice isn't being transmitted. Similarly- the mute button isn't red/active.

If switching to another world, the mute is indeed off/the bar is green.
