### ISSUE TITLE
Headless Servers No-Longer Send Valid Initial Image

### ISSUE THREAD

**Issue by Enverex** [Frooxius/NeosPublic#778]
Since the most recent update (2020.7.15.1186) headless sessions no-longer generate an initial world image, just black. For example:

![image](https://user-images.githubusercontent.com/958670/87669270-9bef5880-c765-11ea-918d-30c324808ea8.png)
(the ones with images and red text are running the previous version, hence why they do have images)

**Comment by Frooxius** [comment]
Ooops. I know what it is, will fix in next update, thanks!

**Comment by Frooxius** [comment]
Fixed in 2020.7.17.1288 thanks!
