### ISSUE TITLE
Headless Behaviour After "Optimisation" Update

### ISSUE THREAD

**Issue by Enverex** [Frooxius/NeosPublic#779]
World on headless servers still appear to eat CPU time even when completely empty. To mitigate this, I put together some Logix that would check for users every few seconds and disable the world root (a slot that contains the whole world, minus the user spawn and assets folder) when it was empty and reenable it when someone entered (or was otherwise detected). This got idle CPU down on small worlds from 60% to 0% and on large worlds again down from 300-600% down to 0-2%.

Since the "- Headless will now skip most heavy updates in the gameloop if no users are present in the world, effectively treating it as a background world" update, ironically CPU usage has rocketed back to around 300-400% which implies that not only is my world disabling Logix not working anymore, but there are clearly still a lot of heavy updates running on empty/idle worlds.

**Comment by Frooxius** [comment]
This will depend heavily on the world itself and where the load in there comes from. Physics and per-frame updates should be stopped, but some systems will still run in the background, as they do in normal worlds. 

Doing the same level of disabling as you do is not safe to do generally, as that would need to assume certain things about the behaviors in the world.

I could add one more mechanism, which severely reduces the tick-rate of an unpopulated word, e.g. to something like 2.

**Comment by Enverex** [comment]
What is still running in your "sleep state" vs turning off the majority of the hierarchy? I'd have thought the physics were responsible for the majority of the load, but if you're saying they're disabled when it's sleeping then nothing immediately stands out for me as being the cause.

**Comment by shiftyscales** [comment]
It would need to be profiled in order to say with any certainty what it could be. Having a drastically reduced tickrate for inactive worlds sounds like it could be a potentially beneficial mechanic in any case, though.

**Comment by Frooxius** [comment]
Neos has a lot of event systems. Data model changes, synchronous tasks, coroutines and several other update systems. It will heavily depend on the world itself as well. 

Turning off majority of hierarchy de-registers everything, but this is a major functional change and it will break certain behaviors in some cases (your worlds likely don't have those so it doesn't matter).

**Comment by guillefix** [comment]
Following from my comment on discord (though perhaps I should make a new issue). It would be nice to have the option to disable this "world doesn't run while no user is on it" for headless. I sometimes want to use headless clients to train AI agents, to speed up fps as much as possible, so this change has made that not possible.

**Comment by shiftyscales** [comment]
The `autoSleep` property was added in 2020.7.19.1204 which should fulfill the needs of this issue. Closing it down.
