### ISSUE TITLE
Crash trying to import json file

### ISSUE THREAD

**Issue by Dung3onlord** [Frooxius/NeosPublic#78]
i was trying to import different json files coming from a Tiltbrush and the game consistently crash.
While trying to import MTL or obj i didn't experienced any problem.

**Comment by Frooxius** [comment]
This is not currently supported, Neos excepts the JSON files to be Neos objects.

It shouldn't crash though, I'll have a look at it, thanks for the report!

**Comment by Frooxius** [comment]
Fixed and pushed to Steam, shouldn't crash anymore. Tiltbrush JSON files aren't supported yet, if you'd like to import these, make a feature request (though not sure how soon I could add support, not sure if they're application specific, other formats might work better).
