### ISSUE TITLE
Avatars: Allow Un-Equipping of Avatars(Even in Spectator Mode)

### ISSUE THREAD

**Issue by GearBell** [Frooxius/NeosPublic#783]
when we are in a clustered world and in spectator, can we have an automatic allowance to switch to the generic vr headset avatar? ironically as spectator we cannot switch to lighter avatars, and we do not always have the ability to ask for permissions. A generic vrheadset avatar seems safe enough to have a menu Switch To option. (gesture switching is confusing, menu with a button seems easier)

**Comment by ProbablePrime** [comment]
Its actually a imo bug, detailed here: https://github.com/Frooxius/NeosPublic/issues/686

Spectators are meant to by default meant to be able to swap avatars.

**Comment by GearBell** [comment]
some worlds do not allow avatar swapping, im thinking of those situations

**Comment by ProbablePrime** [comment]
Sounds good, I wanted to ensure there was a distinction as ideally i still need 686 fixed in addition to this solution proposed here.

**Comment by TehTurk** [comment]
Going to close this as this is related to issue #686

**Comment by mralext20** [comment]
I belive this should be reopened, as the default headset should always be available as an avatar to swap to.

**Comment by TehTurk** [comment]
Ah, let me change in the wording then as to make it a bit more realistic. I may have misread and thought any headset vs THE default headset.

**Comment by shiftyscales** [comment]
It doesn't really seem like something that would be simple to implement, @mralext20 @TehTurk. There will be cases where a world has very explicitly set up what avatars are allowed, and letting a user unequip the avatar would break the experience.

For worlds where avatar switching is available in spectator (which should be significantly more now that #686 was addressed), a user could just choose to equip the headset avatar, or another similar lightweight one.

If a host/world isn't set-up to allow for avatar switching, it's on them to enable it.

**Comment by shiftyscales** [comment]
Issue was closed after some discussion in DM with GearBell. As noted- there isn't a simple mechanism that could be setup to allow unequipping an avatar from anywhere without potentially breaking experiences that rely on forcing an avatar on the user. For any other session, it's up to the world creator, or host to set up the world permissions accordingly, e.g. providing an avatar users could swap into for that purpose.
