### ISSUE TITLE
Component to get normalized voice volume from an avatar

### ISSUE THREAD

**Issue by H3BO3** [Frooxius/NeosPublic#787]
I would like a component that works much like the VolumeMeter, but provides the normalized voice volume automatically from the user of an avatar. It would help with visual effects that display consistently over the normalized range, rather than having to boost effects by an arbitrary amount to make up for less sensitive microphones.

The current VolumeMeter setups running off the voice stream seem to provide the volume of the raw microphone input, so it has proven difficult to work with consistently.

**Comment by Frooxius** [comment]
VolumeMeter doesn't handle any normalization or anything like that, it's not its responsibility. It takes an audio data in (whatever that is) and normalizes that.

The audio stream coming from the avatar is already normalized, the raw audio isn't sent at all, so as a result the VolumeMeter results you're getting are of normalized voice volume.

**Comment by H3BO3** [comment]
That's strange, I watch the output of the volumemeter and it never rises as high as the normalized volume. It always sticks around at around a quarter of the range (~0.25 max), matching the raw microphone input better. Is this a possible bug?

**Comment by Frooxius** [comment]
No. VolumeMeter is the raw average volume. Unless you have a high pitched noise at maximum amplitude it's not going to be too high.

The volume meters in the dash are non-linear, meaning they will rise much faster even for lower volumes. I can add more things to VolumeMeter to adjust how is it measured and give more control.

**Comment by H3BO3** [comment]
Huh, I see. Some more settings on VolumeMeter would be good! Thanks Froox
