### ISSUE TITLE
UI Edit mode allows for changing the grip pose of items held by other users.

### ISSUE THREAD

**Issue by Conduit384** [Frooxius/NeosPublic#788]
When I enabled UI edit mode to change the grip pose of the item I was holding, someone else holding an item noticed that the "Hand" that shows up when edit mode is on was also showing, I was also able to move the item around and change the grip pose. I was able to do the same thing in other sessions. 
Video: https://streamable.com/ni0coj

**Comment by Frooxius** [comment]
Should be fixed in 2020.7.24.446, thanks!
