### ISSUE TITLE
[Feature Request] Allow adding vertices to LogiX connections

### ISSUE THREAD

**Issue by ykgamma** [Frooxius/NeosPublic#789]
Currently, LogiX connections between two nodes are limited so that the shape is (what I'm assuming to be) a bezier curve between the two nodes. This has the problem that if there lies another node connection along the path of the connection, it will overlap. LogiX connections are most legible when they do not intersect (or intersect as minimally as possible).

This feature is supported by other visual programming languages such as LabVIEW: [Example](https://www.viewpointusa.com/wp-content/uploads/2020/03/labview-code-2020-2.jpg)

With this feature, vertices may be placed along the path of a connection so that the visual line can be re-routed around other nodes and connection, vastly improving legibility.

**Comment by shiftyscales** [comment]
You can use the relay node to do this for now. In the future, this functionality will be made easier to perform in some form, e.g. by adding a relay into any existing ribbon/splitting ribbons.

**Comment by ykgamma** [comment]
Is there a way to spawn a relay without the word relay in it? Currently, the relay is a fairly large rectangle for what otherwise would be a small vertex. Putting them in small places where a lot of connections flow by looks very crowded.

**Comment by shiftyscales** [comment]
That's one of the planned tweaks that will be made- the visuals will be minimized once that functionality is added to help keep things visually tidier. The visuals for the nodes are generated when unpacking, so there isn't any way to replace the visual for the node at this time.

**Comment by Frooxius** [comment]
This has now been added in 2020.8.18.447! You can shape the wires by simply pointing at them with the LogiX tool and using the grip, which will automatically insert a new relay.
