### ISSUE TITLE
When DuplicateBlock is placed on an avatar is disallows context menu duplications

### ISSUE THREAD

**Issue by ProbablePrime** [Frooxius/NeosPublic#792]
1. Add Duplicate Block to somewhere on an avatar hierarchy, In my case it was the avatar root. I also tested this with just adding it to the Hand Bone
1. Equip that avatar
1. Try to grab and then duplicate any object such as a basic cube
1. Observe that you cannot

I also tried this with DestroyBlock but the same occurrence did not occur.

**Comment by Hayden-da-Serg** [comment]
This is interesting, I have a duplicate block and destroy block on an object in my hierarchy that isn't anything the anchors are parented under, for instance it goes "Root > Left Anchors > Camera" and the anchors are under that same root, I've had this for a few months and never had an issue with it, so it must be that if the Block is set on an object that the anchors are under then it causes issues.

**Comment by shiftyscales** [comment]
I agree with Hayden this is likely the case. I'd imagine the nodes apply to/protect anything under their direct hierarchy. So if you place the block on the top of your avatar's hierarchy, it'll propagate all the way down to your holder slots, and thus, the objects you're trying to duplicate,

It's strange that it wouldn't occur for DestroyBlock then if that were the case, however.

**Comment by Frooxius** [comment]
Should be fixed in 2020.7.27.3, thanks!
