### ISSUE TITLE
Checking FlatShading on the GridMesh component breaks the mesh

### ISSUE THREAD

**Issue by AMonsoonofBabies** [Frooxius/NeosPublic#796]
When working with a GridMesh procedural mesh component, checking the FlatShading checkbox abruptly destroys the mesh, showing nothing as rendered from the component. Unchecking this box does not revert the issue, as I believe the entire component becomes broken through an exception. Steps to recreate are simple:

- In an empty world, create an empty object
- Place a GridMesh component on the object
- While the issue happens no matter what you do first, I recommend grabbing the component and pulling trigger to create a visual of the mesh to observe that the component works as expected
- Check the FlatShading checkbox and observe that the mesh generated is now gone, indicating that the component has broken.

I have attached a relevant log for the session in which I followed the aforementioned steps.
[DESKTOP-MD1G9UR - 2020.7.19.1204 - 2020-07-21 16_29_45.log](https://github.com/Frooxius/NeosPublic/files/4956761/DESKTOP-MD1G9UR.-.2020.7.19.1204.-.2020-07-21.16_29_45.log)

**Comment by shiftyscales** [comment]
A very clean log, and a very clean case. Thanks for the report, @AMonsoonofBabies.

**Comment by AMonsoonofBabies** [comment]
No problem. Clean reports make for easy fixes.

**Comment by Frooxius** [comment]
Fixed in 2020.7.24.446 thanks!
