### ISSUE TITLE
World Feature: Player Join Blacklist

### ISSUE THREAD

**Issue by GearBell** [Frooxius/NeosPublic#797]
There are situations where there are specific individuals that you do not want in your worlds. I understand a better banning system will be in place but for now I ask for something a bit sooner. This idea is specifically for unpublished worlds, and publishing them removes the blacklist. This idea is mainly for home map instances. We do not want to wait for these individuals to show up to ban them, we would like a world component of Player Blacklist that can be only edited by admins to ban them as soon as we hear of them. In putting a specific username will cause the player to be unable to join that world. We reeeeeeeeeeeeally dont want to put up with the situations of waiting for them to join, it leads to very awkward situations, and putting the world on "friends only" denies the chance of nonfriends that you dont mind joining. We would really just like a way to block selected individuals from joining *before* they show up, and never give them that chance. Its for peace of mind and security. Also hoping that its a soon quick addon, cause its unfortunately being needed sooner than later.

**Comment by Frooxius** [comment]
Is this just for a specific world or specific player? The fastest and easiest thing to do right now would be to add ability to ban a person from all your sessions through the Friends list. You'd search their username, click them and a button to ban that person from your sessions would appear. This would prevent them from joining any of your worlds.

A per-world ban list could be added as well, but that would take significantly longer to design and implement, so if you need something quick it won't be the best option.

**Comment by GearBell** [comment]
this would be world specific. most useful in home maps (i intend to use it for my garage so its safe for people to hide there)

**Comment by GearBell** [comment]
there are situations where you want specific maps to be "safe", but dont mind seeing those people in any other map.

**Comment by sauermon** [comment]
Chiming in, I believe a "pre-ban" system would be a useful feature, so that if there is - say - a known individual that is travelling around worlds causing grief, their damage can be minimized, as information travels quickly. As Gearbell mentioned, it would be per-world, like the ban system currently. 

It would act as a preemptive system to stall trouble, and for other reasons.

**Comment by Frooxius** [comment]
Hmm, unfortunately that will take longer. I don't have a proper mechanism for this, so it needs to be designed from scratch. I'll think about this and see what would be the best approach. 

@sauermon The ban system currently isn't per world, it's global. If you ban someone from your session, you ban them from all of them. Adding pre-ban for that would be possible to do quickly, but it'd be the global one.

**Comment by inzanesonikku** [comment]
a pre-ban thing would be fantastic

**Comment by sauermon** [comment]
Ahh I see. I've yet to utilize the ban system so far (thankfully), so I was unaware they were global. However if a pre-ban system is able to be implemented - yet global - I believe that is a suitable feature until per-world bans are possible, or something like that, in my opinion.

**Comment by GearBell** [comment]
perhaps for the time being a pre-ban, even if it is global, would be useful - at least until the "per-world" one is in place. (can you unban someone? is there a list? might forget about who you banned oops lol). a pre-ban would be useful either way at the very least for trolls. and i really hope it doesnt announce "you cannot join this world cause you are banned" but more like "Unable to join world" and they'll shrug it off and it avoids conflict.

**Comment by Frooxius** [comment]
Hmm, the main question that comes to mind, this would be specifically for preventing people from joining session of that particular world right? What if this is a public world and someone else hosts a session of that world? Maybe even those banned people? Would they be able to join?

Global pre-ban would be really quick addition. I don't like modifying the old UI too much, but this has a way to be added super quick so I could get that in the next build. 

You can un-ban the person anytime as well, so it can be on and off thing. 

However it does currently say that they were banned by the host. I could change the message, but it's also a question of what's the right thing to do or if it would help. Whenever there was a non-specific message like that people report it as a bug and they start asking around. Plus if it only shows up when banned, they would eventually figure out "World is locked out" == "Host has banned me".

**Comment by Frooxius** [comment]
One thing that could help with message is just completely hiding the world from them, so they don't see it in the first place, but that would be a bit more complicated to implement.

**Comment by GearBell** [comment]
hiding the world to banned people would be great!

**Comment by sauermon** [comment]
I second this, as it would generally make it inaccessible to banned players. If this is also merely temporary until a world-specific ban system, I think it's good until then.

**Comment by Frooxius** [comment]
Added this in 2020.7.24.446 through the friends list. You can simply search the person (you don't need them added as a friend), select them and then you'll have two buttons, to either ban them from all your sessions or from the world you're currently in. The world you're in needs to be a saved one, it won't be available for newly created sessions. 

Eventually this functionality will be superseded by the ability to customize join/deny rules for each session, but hopefully it helps for now!
