### ISSUE TITLE
World Catergory System

### ISSUE THREAD

**Issue by GearBell** [Frooxius/NeosPublic#801]
This will definatly be a long term thing, but the current world browser is a bit of a mess, can we have categories? Such as:
- Games - objective game worlds like tennis, racing maps, playable arcades. 
- Activity - movie maps, workout maps, exploring maps, etc. 
- Art - pretty maps just to display talent. 
- Social - snuggle maps, hangout maps, lounges, clubs. 
- Test - (maps that should not have been published) logix tests or demonstration maps. 
- Education - stuff Hamish likes. 
- Active - any active world atm with people in it. 
- Headless - self explainitory. 
- Uncategorized - any maps missing those keywords in its tags, mostly home maps mistakenly published.

**Comment by TehTurk** [comment]
I recall Froox wanting to make a tagging for something like this so users themselves could define the tags and then the catergories are somewhat made up around that.

**Comment by GearBell** [comment]
this is more for the browser menu. i dont want to manually search when i want to browse. those are the most common categories among neos. it really should be bunched up types cause itd be a mess to want to find a club type map but each person tagged differently under "club" "bar" "lounge" "eatery" or something. they are social maps, so theyll be bunched under it. vrchat overcategorized thier world browsing list and it became a mess.

**Comment by TehTurk** [comment]
Valid. But the tags would also have stuff like the most common tags being some of the more common groups. I guess having decent considerations for what should or shouldn't be a category can help too. Social, Game, Experience, Edu/Meeting, Showcase (This also splits up the art somewhat as art is a really broad topic) are the few generalized ones that come to mind.The issue with this also I think many many platforms have attempted this and always kinda had a good enough approach and always kinda was left to the wind but it also can pingeonhole alot of maps and have creators leaning towards making specific maps vs things they'd want to make for acclaim/others.

**Comment by H3BO3** [comment]
Not to mention people can put false tags just to have their world show up in most lists/searches, so I feel like there should be some kind of community redundancy at some point regarding tags and categories

**Comment by GearBell** [comment]
i feel that issue will only occur far far down the line. currently with a population of less than 100 it wont be an issue

**Comment by ProbablePrime** [comment]
Did you know that tags already exist and can be used? They're just presented, described and used poorly. 

When you name a world it breaks your world name into tags which are then searchable. To see this in action, select a world in the world browser and then click one of its tags. It will then search the world browser for those tags.

Tags should always be user specified but moderated slightly if they are completely false.

I think Froox is working on a lot of this area.

"Test - (maps that should not have been published) logix tests or demonstration maps." I have mixed feelings on this one. I publish a lot of maps that fall into this description and they most certainly should have been published. It is situational but though.

**Comment by Frooxius** [comment]
Yes, the tags system is designed for this, but it's not fully utilized in the UI yet. The new redesigned world browsing UI will have certain predefined categories for the most common ones, but they'll be based on tags as well (essentially certain common tags).

If people put false tags into their worlds then it'll become a moderation issue. It's not really different from them putting the world into false category, it's just details. 

For the headless, active and so on, those will be filtering criteria for active sessions, they'll be part of the new browser UI as well.

Big part of the new UI is also sorting. By default the system will sort the worlds so at the top are the most relevant active sessions (e.g. ones with more people in them or your friends in them) and worlds and at the bottom the least.

Hopefully this will help to improve the browsing experience significantly.

**Comment by shiftyscales** [comment]
Categories for worlds and sessions were added with the redesigned world browser as search presets.
