### ISSUE TITLE
Friend System

### ISSUE THREAD

**Issue by MR-Alex42** [Frooxius/NeosPublic#81]
With more and more people joining Neos it will be important to have tools at hand to find your friends.
Technically Neos could use the friend system of Steam. However it should be possible to make friends inside of Neos and propagate this to Steam. The friend system should give the user the capability to see in which worlds my friends are online and which worlds have been build by friends. A user should also be able to follow and locate friends inside the worlds.

**Comment by Frooxius** [comment]
Yes! I'm working on this one, plan to introduce it fairly soon. Will make joining specific people easier, prevent trolling if you only allow trusted friends and generally make things friendlier.

It's going to use Neos' infrastructure though, if it was through Steam, it would become unusable without it (for example on Oculus store or Android builds). I'll likely use Steam to import a friend list though.

Thanks!

**Comment by Frooxius** [comment]
Oh yeah this one is done.
