### ISSUE TITLE
Quad mesh tints partical systems blue

### ISSUE THREAD

**Issue by RueShejn** [Frooxius/NeosPublic#816]
Steps to replicate
1.Use dev tip to spawn a particle system
2.add procedural quad mesh to the particle system
3.apply that mesh into the mesh field of the particle system

Particles should now be blue

seems to be only the quad mesh that has this effect, other procedural meshes do not do this including grid mesh.

**Comment by H3BO3** [comment]
This has to do with the particle system using UseVertexColors, or whatever the option is. This is on by default for some reason, I think it should be false by default. Certain meshes seem to do it.

**Comment by shiftyscales** [comment]
A fix for this is coming. The particle system can't deal with vertex colors, so it will be possible to disable vertex colors for the quad in  the next build.

**Comment by Frooxius** [comment]
Added a property UseVertexColors for QuadMesh in 2020.7.29.725, disabling this will make it work well with particle system. THanks!
