### ISSUE TITLE
The settings dialogue edits everyone's settings in a session

### ISSUE THREAD

**Issue by Coffee-Maker** [Frooxius/NeosPublic#818]
Cyro managed to rip the settings dialogue from his dash, brought it into world space and changes on the dialogue propagated to all users. Editing private settings in the dash would also reflect on this world space dialogue and propagate to all users.

**Comment by Frooxius** [comment]
This is odd, the setting syncs are specifically tied to a particular user and they won't update the user's settings if they're in worldspace. Are you sure the actual settings for other users have been changed and it wasn't just a visual in the world? Or does it only happen with particular settings? There are a few that are using a different system.

**Comment by shiftyscales** [comment]
Yeah, this was an issue that had already come up prior and had been addressed(?) in 2020.6.14.978.
https://discordapp.com/channels/402159838827905024/469131434628612116/721763538619859005
`- Fixed settings being able to be synced from the worlds (reported by @sleepingkaikai through @Shifty | Quality Control Lead)`

**Comment by Frooxius** [comment]
I'm checking the code and so far only the audio volumes don't check if they're in userspace, because they use a different system, I patched those. The other mechanisms all bypass updating settings if they're not in userspace.

Which settings did you test? Was it the audio volumes? Or any others?

**Comment by Coffee-Maker** [comment]
We only saw it modifying audio. Though everyone was battling to use their audio settings and it got quite frustrating- the main issue was that I was trying to change my local settings in my dash and other's in the session had their audio changed too.

**Comment by Frooxius** [comment]
Ok that would make sense. Should be fixed in the next build. Every other setting should already be protected.

**Comment by RileyGuy** [comment]
It seems like the settings wrapper component actually doesn't have any sway over the values being synced but rather the AudioTypeGroupVolumeSlider component.

**Comment by Frooxius** [comment]
Fixed in 2020.7.29.725, thanks!
