### ISSUE TITLE
ConeMesh with FlatShading enabled appears to generate incorrect normals

### ISSUE THREAD

**Issue by AMonsoonofBabies** [Frooxius/NeosPublic#820]
I have noticed that the procedural ConeMesh component has inconsistent lighting when FlatShading is enabled, and is only fixed when the mesh is baked and the normals are recalculated. Viewing an example of this phenomenon can be done as follows:

- Open a new world, preferably the GridSpace option, as it has powerful and apparent lighting from one direction.
- Using the dev tip, create a cone object and open it in the inspector.
- Take note of how the light in the world affects the cone. Find the ConeMesh component on the object and toggle the FlatShading option. Nothing should change at this point.
- To see the visual effect, you can either grab the cone and turn it around in different ways, or simply enter 90 degrees into the Y rotation. These actions should change how the light looks on the surface of the cone with FlatShading enabled. Toggling FlatShading on and off should also make this more apparent, as the lighting stays consistent with smooth shading, but stays incorrect with flat.
- Optionally, you can bake the mesh in its flat shaded form, then recalculate the normals. Doing this very clearly corrects the lighting inconsistencies, indicating that this is a problem with the normals.

The logs of the reproducing session did not appear to contain anything useful in the way of errors or exceptions. Instead, I took two screenshots of the issue. On the left is the flat shaded cone in GridSpace as it immediately appears from the dev tip, and on the right is the same cone rotated 90 degrees on the Y axis. Both are taken from the exact same point of view with no lighting changes to the world.
![cones](https://user-images.githubusercontent.com/66186598/88639906-8984f100-d07a-11ea-8ca3-812f4624cc09.jpg)

**Comment by shiftyscales** [comment]
Hmm- not sure how to assess this one, as I'm not familiar enough with the rendering pipeline to know how a flat shaded object should function under dynamic light sources. I'd be curious to see how it would work in Unity itself- rotating a flat-shaded object around by a light source.

I can imagine how it **could** look- the gradient constantly shifting from one surface to the next, but I don't know if that's actually an issue on Neos' end or if it's just a Unity renderer thing.

**Comment by H3BO3** [comment]
Honestly this looks like the normal or tangent generation on the mesh is going wrong somewhere.

**Comment by AMonsoonofBabies** [comment]
I did mention that baking the flat shaded cone mesh and using the "recalculate tangents" button fixes this issue completely. Signs like this directly point to it being some sort of issue with normals, like H3 said, so I'd say it's the mesh itself being faulty somehow.

**Comment by Frooxius** [comment]
Fixed in 2020.7.29.725 thanks!
