### ISSUE TITLE
Capsule Procedural mesh addition?

### ISSUE THREAD

**Issue by AegisTheWolf** [Frooxius/NeosPublic#822]
Figured that there wasn't a Github post on this before, mainly its a request of a capsule procedural mesh to be added to also not only function as a new procedural mesh but to help visualize capsule colliders nothin really big importance just left it here for future reference.

**Comment by TehTurk** [comment]
This would also be really nice as we'd be able to some shapes we couldn't do currently with procedural meshes :)

**Comment by Frooxius** [comment]
Added in 2020.7.29.725!
