### ISSUE TITLE
Lighttip - Sun Mode Nonfunctional

### ISSUE THREAD

**Issue by Medravr** [Frooxius/NeosPublic#824]
When using the light tip in sun mode, changing from no, soft, or hard shadows will not change the directional light's shadow settings. The functionality of the tip in this area is currently broken.

**Comment by Frooxius** [comment]
This was actually disabled on purpose, as it would mess with the configuration of the light in the world, rather than just moving it, but I can re-add the functionality again.

**Comment by Frooxius** [comment]
I've made the change in 2020.7.29.725, it should set the shadowmode properly now!
