### ISSUE TITLE
Spawning a folder from inventory breaks UI

### ISSUE THREAD

**Issue by Vigilabo** [Frooxius/NeosPublic#825]
When I spawn a folder from my inventory into the world it breaks my UI. (The world I'm in does not seem make a difference or how long Neos has been running). I checked my logs, but there were no exceptions related to this.

**Comment by Frooxius** [comment]
What exactly do you mean by this? By spawning folder do you mean creating a link to it using the envelope button?

What exactly does "breaks my UI" mean? Does it stop responding? Or get visually corrupt? Does it affect all of UI or just specific parts?

Is there any way to reproduce this behavior?

**Comment by Vigilabo** [comment]
What happened for me was when creating a link using the envelope button the UI stops responding/updating. It affects all UI and stops them from responding/updating.

Here is a log: [DESKTOP-7Q9M270 - 2020.7.29.748 - 2020-07-30 17_55_11.log](https://github.com/Frooxius/NeosPublic/files/5004002/DESKTOP-7Q9M270.-.2020.7.29.748.-.2020-07-30.17_55_11.log)

**Comment by Frooxius** [comment]
Thank you for the extra information. This should hopefully be fixed in 2020.7.31.1099, let me know if it still occurs. Sorry for the inconvenience!
