### ISSUE TITLE
Exit & Save Homes causes Neos to lock up if a camera control panel is open on exiting

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#826]
Reported by Davwyn#6433.

Steps to replicate:
- Open the camera control panel
- Exit & Save Homes

Neos will lock up after the syncing is complete right while trying to exit, requiring it to be force-closed.
[SHIFTYWINDOWS - 2020.7.29.748 - 2020-07-30 11_27_42.log](https://github.com/Frooxius/NeosPublic/files/5003169/SHIFTYWINDOWS.-.2020.7.29.748.-.2020-07-30.11_27_42.log)
[Player.log](https://github.com/Frooxius/NeosPublic/files/5003171/Player.log)

It appears Unity is throwing a bunch of errors from the camera.

**Comment by Frooxius** [comment]
Fixed in 2020.7.31.1099, sorry for the issue!
