### ISSUE TITLE
[Bug] Xiexe Toon does not support OffsetUnits or OffsetFactor

### ISSUE THREAD

**Issue by Hayden-da-Serg** [Frooxius/NeosPublic#832]
When helping Zane with importing assets using Xiexe Toon I noticed z-fighting, my first thing to try was to change the OffsetFactor, but changing this did nothing, I next tried OffsetUnits, still nothing, so I tested in isolation and it does seem that Xiexe Toon does not support either settings.
To recreate; 
1: make two objects z-fight with each other (best done with two quads, one smaller than the other in the same coordinates)
2: Set both to separate instances of Xiexe Toon, one a different color than the other
3: attempt to change OffsetFactor or OffsetUnits at the bottom of the material settings

Havin this setting would be really useful for having intersecting geometry and not having to offset the Z axis of the object, as that could cause other unwanted issues.

**Comment by Frooxius** [comment]
Looks like the support was missing, added it in 2020.8.3.1234, thanks!
