### ISSUE TITLE
Enable highlighting / flashing only the active meshes on an object

### ISSUE THREAD

**Issue by Zyzyl** [Frooxius/NeosPublic#833]
I have two use cases where I would like to be able to temporarily flash / highlight only the currently visible meshes on a target.

1. 'monster capture balls' which are throwable and produce a red highlight with some transparency on a target after the ball collides with a valid collision target. Currently valid targets are non-avatar objects with skinned meshes, however I will want to make this work identically on user avatars in the future.

2. A similar situation where I would like to highlight only the visible meshes on a user's avatar in response to 'drinking' a virtual drink. This was mentioned by Rukio on the 31/07/20 showcase stream.

Currently the closest I'm able to get to the desired effect is using the Flash Highlight Hierarchy node and providing the object root slot / active user slot as the TargetHierarchy node input. This node would be sufficient for these use cases except for the fact that it also highlights additional things like colliders and inactive objects.

**Comment by Frooxius** [comment]
I've added "ExcludeColliders", "ExcludeMeshes" and "ExcludeDisabled" inputs to the node in 2020.8.1.782, hopefully this helps! Thanks for the suggestion!
