### ISSUE TITLE
Grid from "Create new -> 3D Model" should be turned 180° in Y

### ISSUE THREAD

**Issue by BlazeVR** [Frooxius/NeosPublic#834]
Can I suggest for the grid (from DevToolTip -> Create new -> 3D Model) to be turned 180° in Y axis as default (if I didn't mix up the axis)? It's confusing because it looks like nothing has spawned since it's facing the wrong direction of the user :P

**Comment by Frooxius** [comment]
Changed in 2020.8.13.259, all "Create New" objects are now aligned towards the user, which should fix the issue! Thanks!
