### ISSUE TITLE
Pre-set far clip value for AvatarRenderSettings component when enabled

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#836]
Presently when enabling the far clip value for an avatar with an AvatarRenderSettings component installed, the user will be blinded as the default value for the far clipping distance is near zero.

If while enabling the far clip it could pre-set a default value, it would prevent this from occurring.

**Comment by Frooxius** [comment]
The Far Clip there is only added for completeness right now, but you're not really supposed to override it unless you really REALLY need to. The Far Clipping should be controlled globally by the world or Neos default settings for consistency and tweaks, so setting this one to some default value would cause lots of problems and make it hard to adjust it for users later on.
