### ISSUE TITLE
Hierarchy flash broken for CharacterColliderSetterTip

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#837]
With the recent change to the FlashHierarchy node in 2020.8.1.782, the CharacterColliderSetterTip appears to no longer flash the hierarchy of the object it hits while adding/removing character colliders.

**Comment by TehTurk** [comment]
I can also attest for this as I was in the same session as well.

**Comment by Frooxius** [comment]
I can't replicate this, it seems to work correctly. I found that Sphere collider has broken flash highlight, which I'll fix in the next build. Was this the collider you tested with?

**Comment by TehTurk** [comment]
Yes, Yes it was :o

**Comment by Frooxius** [comment]
Ok, fixed in 2020.8.5.1178! Thanks!
