### ISSUE TITLE
Bug: Xiexe Shader messed up

### ISSUE THREAD

**Issue by GearBell** [Frooxius/NeosPublic#842]
xiexe shader no longer supports double sidedness, reacts badly to lighting, and is "messed up by default" according to Cyro. Im hoping it can be fixed so that i dont have to go back and fix my passed 63 avatars, some players even have more than that - its gonna be a headache to even reupload all those public avatars if we have to. The image included shows xiexe shader reacting to "nighttime" lighting, with cyro in the background as comparrison compared to pbs.
![2020-08-03 16 34 08](https://user-images.githubusercontent.com/30758182/89237373-dcddce80-d5a7-11ea-9295-36c508e4a300.jpg)

**Comment by H3BO3** [comment]
Froox is aware, he's recompiling the shaders for a potential lighting fix. The double-sidedness is hopefully something that gets fixed along with it too

**Comment by Frooxius** [comment]
I'm working on a fix, should have it out soon, sorry! No re-uploads are necessary at all (the way Neos is designed those are never needed for existing content, except in some cases where you re-save it after being broken, but this is not one of those cases).

What exactly does "messed up by default" mean?

**Comment by Frooxius** [comment]
Ok should be fixed in 2020.8.4.23 now, both the lighting and the culling. Not sure what "messed up by default" means though, so those are only two fixes, but it seems to be working normally now, so I'm closing the issue. Reopen if there are still issues. Sorry for the inconvenience!
