### ISSUE TITLE
Bug: Xie's Opaque Blend mode does not play nicely

### ISSUE THREAD

**Issue by TehTurk** [Frooxius/NeosPublic#846]
Some common visual occurrences are white flashing, or some weird ZWrite Issues as you can also notice these affects in certain skyboxes or in mirrors. I've been recommending people go back to Cutout until then.

**Comment by Frooxius** [comment]
What exactly do you mean by this? Do you have any screenshots or references? Any conditions under which this happens?

**Comment by TehTurk** [comment]
Ah, I figured there were some bugs still with Xies mainly with the blend modes, investigated but only found Opaque was causing the issues. This is happening on most Xies shaders most people I have met or saw tonight that were converted. It was originally a Cutout focused shader prior so going back to that blend mode made most sense. I meant to get some photos but it was late apologies. I'll get some in the morning or some other users can contribute them here. 

This will happen in some cases with lights in worlds, one repro is taking a model with converted xies, and using one of the more lighter skyboxes in NeosDefaults which then can cause some interesting transparencys with the ZWrite. Mirrors will compound the effect the affected model will just glow emissively and bright with intensity.

**Comment by Frooxius** [comment]
I've pushed a new build 2020.8.4.759 with some fixes, can you confirm if that fixes the issues?

**Comment by TehTurk** [comment]
Yup! All Cleared up, didn't think the ZTest would misbehave like that, thanks Froox!
