### ISSUE TITLE
XieToon Shader Shadows Utterly broken, lighting behaving improperly, random glitches

### ISSUE THREAD

**Issue by erosensei89** [Frooxius/NeosPublic#847]
Okay, with the recent XieToon Update the lighting doesnt behave properly anymore. 

- Shadows from Light Sources not displaying at all
- Random glitches and flickering 

I've tried out all the blendmodes, the shadows will not properly render on it. 
All cell shaded worlds look horribly flat now. Pls fix asap. 

![2020-08-04 11 12 58](https://user-images.githubusercontent.com/36775354/89277236-d9e4eb80-d644-11ea-9be0-ae73f61aabbb.jpg)
![2020-08-04 11 14 36](https://user-images.githubusercontent.com/36775354/89277243-dc474580-d644-11ea-8c38-126432ddd127.jpg)

**Comment by erosensei89** [comment]
![2020-08-04 11 29 55](https://user-images.githubusercontent.com/36775354/89278092-f0d80d80-d645-11ea-9874-1f2d58666341.jpg)

**Comment by Frooxius** [comment]
Should be fixed in 2020.8.4.759, sorry for the inconvenience!
