### ISSUE TITLE
Grabbable w/ driven Scale and Scalable enabled does not allow grab

### ISSUE THREAD

**Issue by H3BO3** [Frooxius/NeosPublic#851]
If a grabbable item's slot scale is being driven, and the grabbable's Scalable flag is true, the item cannot be picked up or grabbed at all. This can be replicated by creating a new cube model, driving the scale into itself just for the purposes of creating a drive, then attempting to grab it. If the Scalable flag is toggled false it can be grabbed again. I don't think the scale being driven should affect being able to grab an item with scalable on, even if trying to perform scaling won't be possible.

This bug was discovered by Ian Corvid.

**Comment by Frooxius** [comment]
This is intentional behavior. Grabbable needs control over all parameters, even if it's not scalable, because the local scale still needs to be changed when the object is parented to preserve its global scale.

**Comment by H3BO3** [comment]
But when I unchecked Scalable, I was still able to grab the object even when the scale drive was still active. The item didn't appear to change size when I did (holder global scale is probably 1), but even if it did maintain its local scale, wouldn't that just be something that happens when you drive the scale? I'm not sure what checking or unchecking the scalable flag has to do with that.

**Comment by Frooxius** [comment]
It depends on whether the Scalable field is hooked or not. Drives that hook can be assigned to and thus still scaled (although the value can be processed by the hook). But if it doesn't hook it can't be changed and thus rejects the grab, because the full required control is not available.

**Comment by H3BO3** [comment]
Alright, that makes better sense now.
