### ISSUE TITLE
Collections

### ISSUE THREAD

**Issue by sirkitree** [Frooxius/NeosPublic#860]
I know this is a planned feature, but there isn't really an issue for this though it's been talked about for a long time now so I thought I'd add it.

## Request
Have a way to work with arrays / collections in Neos, for components and/or LogiX.

## Motivation
Arrays are a standard way of working with sets of data in programming. Being able to have a data set and iterate over it has all kinds of implications and would save a lot of the hacks we've currently been putting into place to try to replicate this.

Related issues:
- #221 
- #260 
- #299 
- #365 
- #403 
- #460 
- #543 
- #561 
- #765 
- #770

**Comment by shiftyscales** [comment]
There actually is an issue about this already, @sirkitree, #256. Thank you for the time, and consideration, though.
