### ISSUE TITLE
User limit overrides for invited/specified users

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#865]
A common issue for popular sessions is that if someone wants to be invited into a session, but the session is already at its user limit, the user will be unable to join. Sometimes, even if the limit is raised, another user could join before the invited user if it is an open session.

If there was a mechanism for a host to invite a user anyway despite the user limit being met, it would help address this scenario.

The invited users could still count towards the overall usercount/user limit, so say the limit was already met at 10, and you invited 4 additional friends, it would be 14/10, and would require 5 users to leave before another could join the open session.

**Comment by Frooxius** [comment]
Yeah this could be pretty simple change. If you invite someone they simply bypass the user count limit. Will everyone be ok if this is the new default behavior? Not sure if it's worth having it configurable, at least not right now.

**Comment by BlazeVR** [comment]
I support this suggestion myself, I had the same issue for couple times now with raising up the user limit for someone else and then another friend joined instead :P

**Comment by shiftyscales** [comment]
I think this would be a great change to the default behavior. In pretty near any cases, if someone were to send out an invite, it is because they want that person in as soon as they're able- or at the very least, want that person to be able to drop in as they please.

**Comment by Frooxius** [comment]
Implemented in 2020.8.7.1059 thanks!
