### ISSUE TITLE
Set seated height does not seem to work in teleport locomotion

### ISSUE THREAD

**Issue by Earthmark** [Frooxius/NeosPublic#867]
Setting seated height in teleport locomotion makes the camera shimmy backwards slightly, but does not move the camera up to normal standing height it seems.

I'll validate this again tomorrow (today?) but I'm recording this before I forget it again (this is the third day I've been meaning to log it).

**Comment by Frooxius** [comment]
What exactly do you mean by this? Do you mean activating the "Seated Mode" in the dash? Or something else?

**Comment by Earthmark** [comment]
Seated mode in the dash, yes. Whenever I hit the button in teleport locomotion it moves me backwards, I end up going to physical and toggling the feature to get it to set the player height.

**Comment by shiftyscales** [comment]
Ah, this isn't actually a bug or anything of the sort that I can see. In teleportation locomotion, the only changes in a player's position are invoked when a player teleports, or if they are parented to something that is moving.

In testing this, I found while the initial height isn't changed, the player does properly stand at the full seated mode height as though they were standing after they first teleport, @Earthmark.

The teleport locomotion has no sense of physicality, as it is not a physical locomotion, so the player won't be moved. The same can be observed if activating seated mode while flying. Their view stays in the same place.

I don't know what you mean when you say "makes the camera shimmy backwards slightly" I was not able to replicate this.

**Comment by Earthmark** [comment]
Hmm, that makes more sense now as to why it wouldn't cause any movement, thank you for verifying. My apologies for the red herring bug.

**Comment by H3BO3** [comment]
In this case wouldn't a sudden jump as the mode is set be more suitable? Ground-projected height is still detectable in teleport mode, and I think avatars have a height value associated with them. Either way I think this should still be looked into so behavior is consistent
