### ISSUE TITLE
Deleting a Button Events logix node breaks the physical button the node is attached to

### ISSUE THREAD

**Issue by Earthmark** [Frooxius/NeosPublic#868]
Deleting the logix node for getting button events when it's hooked up to a physical button breaks the physical button. When broken the button no longer responds to press events, while onHover will be set to true when interacted with, the physical button will not move, and will not enter the pressed state.

This occurred in tutorial world a few times where I accidentally deleted the button events node and the physical button would break. Re-opening the world may fix this, I'll validate tomorrow (this is another "I've forgotten this for two days now" bug).

**Comment by Frooxius** [comment]
Do you have a log for this? It's probably some exception being thrown.

**Comment by shiftyscales** [comment]
This also occurs on the UIX button component as well.

Just replicated it by spawning the UIX canvas template, attaching button events to various buttons and deleting the nodes.
[SHIFTYWINDOWS - 2020.8.5.1184 - 2020-08-07 09_47_48.log](https://github.com/Frooxius/NeosPublic/files/5042660/SHIFTYWINDOWS.-.2020.8.5.1184.-.2020-08-07.09_47_48.log)

**Comment by Frooxius** [comment]
Fixed in 2020.8.7.1059 thanks!
