### ISSUE TITLE
Expose joystick position in standard controller node (Or alternatively, Index binds the wrong x/y output for it)

### ISSUE THREAD

**Issue by Earthmark** [Frooxius/NeosPublic#869]
Currently this seems to not be the case at least for the index, where the trackpad is what is parsed for the index instead of the joystick position.
It seems like every controller has some kind of joystick (or circular track pad), it would be nice if that positional data was exposed.

This was found while creating a local user viewing display that showed your stick positions, instead of using the standard controller I ended up needing to make a different node for every kind of controller.

On a side note I did need to end up doing a user reference override hack in the input nodes as well, it seems the nodes really dislike their input user changing (or at least seem to ignore the changes on occasion). Even when not using local user, it would sometimes bind to seemingly random users and stick to them, even when using a closest user style approach.

**Comment by mralext20** [comment]
i believe the purpose of having axis on standard controller output for index as the touchpad position is that the joystick is reserved for locomotion

**Comment by Earthmark** [comment]
If my goal is to have an abstraction of the movement stick, I feel like I would want to get the outputs in a way that makes them normalized (positive Y always means forward and positive X always means right for instance), otherwise every time I use that output in a logix solution I'd need to add extra controller nodes to go "Well for this controller movement forward is negative X unlike everything else, so detect it and have special logic to normalize it", it feels like that kind of removes the point of a standard controller interface if I need extra bits to make it a normalized piece of data, at least to me?

I did do this on the joystick gui in the tutorial world, and it was kinda funky. Every output was the same direction as far as I know, forward was always reliably forward, but I did have to do a merge of the joystick from every flavor of controller node. I haven't had anyone say it was backwards yet, so I think it's right at least for the controllers that have run into it.

Prime did come up with a good solution by doing a single massive + operation, because the disconnected state of the controller is [0,0]. Adding negates for specific axis would still work in that case, but it feels like that kind of removes the point of having a normalized way to get axis. If I need to use a more complex way to get a piece of info that exists on every controller (I don't know of any that are missing a movement input), then I'm confused as to what I should use the axis of the standard for.

**Comment by Frooxius** [comment]
I'm sorry, but this won't be added. The purpose of Standard Controller is to provide a subset of common inputs that nearly all controllers can be mapped to, that provide guaranteed set of actions for interaction. For Index, the touchpad is what gets mapped to the secondary, not the joystick, which is considered "extra".

Adding inputs that can't be mapped for other controllers would defeat the purpose of Standard Controller. If you need specific inputs of particular controller, use the node for that controller.
