### ISSUE TITLE
General improvement suggestions to the Neos UI objects

### ISSUE THREAD

**Issue by sirkitree** [Frooxius/NeosPublic#87]
Through the red developer tooltip, we have access to a 'Create new' option. This brings up a dialog box, and under the Objects option, you have Neos UI. This gives you the following options to use in your world.
![20180509140728_1](https://user-images.githubusercontent.com/28543/39837013-6fe22f22-5392-11e8-9cc8-17ff46454680.jpg)

I've tried a few times to utilize these, and there are a few things that I do all of the time that would be nice if they were setup already for me.

1. I have to attach a Grabbable component so that I can place them into the world where I want.
1. The progress indicator doesn't have a collider by default so I have to add that component, resize it, and then add grabbable so that I can place it.
1. Text, within the text component: when it's long enough it starts to shrink and get's hard to read with anything longer than a few lines. I can increase the size of the object overall, but it would be nice it the parent mesh could resize as you type with a configurable default of 80 characters per line before wrapping. Maybe some formatting options in the future (alignment, treatment, etc).

Additionally, just a few thoughts about others:
1. I feel like the inspector panel should be a part of this list. I know it's fairly complex object, but maybe a slimmed down version of it where we could place things within it that would then cause it to scroll once there is enough content.
1. Horizontal choice bar: I have a feeling this is to be used in conjunction with Radios or something, but when you create one, there is no visual so it's very unclear as to what it's for currently.

Thank for your time and consideration - and good luck with the workshops this week!

**Comment by MR-Alex42** [comment]
You were looking for comments regarding your suggestions.
I think that these enhancements make a lot of sense.

**Comment by wel97459** [comment]
Think there should be a button like we have for adding new components. But on the left side at the bottom for adding new objects, inside the inspector that opens the current object menu.

It would be better to have new object spawn with collider and Grabbable.

**Comment by Frooxius** [comment]
Thanks for the suggestions! I have added grabbable to the Neos UI elements and collider to the progress bar so far. I'll do some handling for the longer text later, likely a multi-line text editor that you could pop out with a button.

I'm not sure what exactly do you mean by the inspector panel being part of the list? It's tied to a specific object that you have open, do you mean spawning an empty one?

The horizontal choice bar needs some options yeah. I've only used it from code so far, so it doesn't initialize itself with some dummy options, so I've added some when spawning it with the wizard.

**Comment by sirkitree** [comment]
> I'm not sure what exactly do you mean by the inspector panel being part of the list? It's tied to a specific object that you have open, do you mean spawning an empty one?

Correct!

**Comment by Frooxius** [comment]
@sirkitree Hmm, I don't understand what would you expect the empty inspector to do though? You can open one for the whole scene by having nothing selected and selecting the "Open inspector" in the contextual menu.

**Comment by sirkitree** [comment]
Most of these elements are just UI which you can then customize. The idea of an empty panel would be that you could use it as a container for arbitrary data. Just the container would appear when you create one and you could put content within it. Maybe text, maybe images, maybe use JSON to populate it with key value pairs. But the purpose would be to have just the panel UI element and then do something further with it after it's created, just like when you create a button, or other UI element.

**Comment by sirkitree** [comment]
- [x] 1 was taken care of.
- [x] 2 was also taken care of.
- [x] 3 has sorta been addressed with the addition of the text above the keyboard. I'd still love to see a more fully featured text editor at some point, but I have a feeling that is planned and doesn't need to be tracked in this issue any longer.
- [x] 4 was added to the list
- [x] 5 has a visual now so counting that as addressed too.

closing this out!
