### ISSUE TITLE
Decimal data type doesn't support math operators, instead chooses to cast

### ISSUE THREAD

**Issue by RileyGuy** [Frooxius/NeosPublic#875]
Basically self-explanatory with the title. The decimal datatype doesn't seem to natively support any math operators and instead chooses a cast to float. On a similar note, floating-point types don't seem to like connecting to bit shift operators either.

**Comment by Frooxius** [comment]
I'll add math operator overloads for the decimal datatype in the next build. However floating point types not working with bit shift is normal, it's not a valid operation for those datatypes, you'll have to use integers for those.

**Comment by Frooxius** [comment]
2020.8.10.1195 now has overloads of operators for decimal datatype, thanks!
