### ISSUE TITLE
UIX Canvas null reference Exception

### ISSUE THREAD

**Issue by mralext20** [Frooxius/NeosPublic#876]
Hello, i have found an execption that causes the RawImage component to stop scaling its UVRect to stop functioning. 

i am driving the uvrect based on some math. 
somtimes, when this gets updated, it fails, throwing the following exception to the logs: 
```
2:09:20 AM.322 ( 53 FPS)	Exception when running synchronous action (Stage: UpdatingPhysics):
System.NullReferenceException: Object reference not set to an instance of an object
  at FrooxEngine.UIX.GraphicsChunk+RenderData.UploadMesh (System.Boolean highPriority) [0x0005f] in <924fcad58c664428bffa1c7f6c890ed4>:0 
  at FrooxEngine.UIX.GraphicsChunk.UploadMesh (System.Boolean highPriority) [0x00022] in <924fcad58c664428bffa1c7f6c890ed4>:0 
  at FrooxEngine.UIX.Canvas.SubmitGraphics () [0x00113] in <924fcad58c664428bffa1c7f6c890ed4>:0 
  at FrooxEngine.UIX.Canvas.FinishCanvasUpdate () [0x0003b] in <924fcad58c664428bffa1c7f6c890ed4>:0 
  at FrooxEngine.World.RunSynchronousActions () [0x0007b] in <924fcad58c664428bffa1c7f6c890ed4>:0 

```

https://this-is-a.stale-me.me/i/40rg.png < setup of the raw iamge that breaks; logix setup driving the rect: https://this-is-a.stale-me.me/i/a55e.jpg 
the parse is plugged into a tag.

Thanks!

**Comment by mralext20** [comment]
on second thought, this may also be related to how i am changing out the image on the texture.

i am driving the URL param of the raw image's texture aswell, perhaps when it changes there is a chance for the image to go null?

**Comment by Frooxius** [comment]
Hmm, this is a bit strange, it could be either thing. Do you have the whole log for this?

The excerpt you posted seems to be more of an aftermath of the bug, rather than the cause (essentially the mesh data is missing when it tries to send them to the GPU, so I can't really tell what could be causing this.

**Comment by Frooxius** [comment]
Could you send me the setup that reproduces this in-game so I can do testing on it please? I've got a few other logs from people, but nothing conclusive yet.

**Comment by mralext20** [comment]
full logs from the session: [ALEXDESKTOP - 2020.8.7.1059 - 2020-08-09 01_30_05.log](https://github.com/Frooxius/NeosPublic/files/5048526/ALEXDESKTOP.-.2020.8.7.1059.-.2020-08-09.01_30_05.log)

i have sent you the setups in game. the specific tool is a card viewer, and the reproduction case is when selecting a new card somtimes the uv rect stops updating. 

i have send the card viewer and a few cards, for testing. 

i have also reproduced the bug in a fresh enviroment, here are the logs from that:  
[ALEXDESKTOP - 2020.8.7.1059 - 2020-08-09 14_22_42.log](https://github.com/Frooxius/NeosPublic/files/5048551/ALEXDESKTOP.-.2020.8.7.1059.-.2020-08-09.14_22_42.log)

**Comment by Frooxius** [comment]
Thanks! Unfortunately nothing in the log, I'll definitely need to instrument and replicate to see where it's coming from.

**Comment by Frooxius** [comment]
Thanks! I found what it is, looks like you enabled the DebugVisuals mode on Canvas. That's an old thing used during UIX development, I'm just going to remove it in the next build. You can fix it in the meanwhile by disabling that option on Canvas, but the build should be out in a few hours.

**Comment by Frooxius** [comment]
Removed the option in 2020.8.10.1195, should work well now, thanks for all the info!
