### ISSUE TITLE
Controller input values don't persist on ToolTip Equip. 

### ISSUE THREAD

**Issue by Enkiko** [Frooxius/NeosPublic#877]
Bug: I have an object with the RawDataToolTip component. When I click on it and then press trigger to equip, and then keep the trigger partially pressed down, the "PrimaryStrength" of the trigger remains 0, rather than adjusting based on the trigger position. It also fails to register when I press the trigger. Next, after fully releasing the trigger, or somewhere around 98% releasing it, it of course is at zero (it seems to react for an instant and jump to 0.02 before I reach 0). After this point, if I pull the trigger behaviour is normal, and it tracks the trigger position and whether it is pressed.
I have vive controllers, and I get the same problem on both. My controller type shows as FrooxEngine.ViveController.
I also get an unresponsive grabbable tooltip primary button unless I fully release which might be related.
Alex says Gearmark had the same issue, even though he uses an Index controller.
I've had 2 other people with Vive controllers test and they didn't have this bug.
I get this issue with the default avatar as well, so its not my avatar.
My controller operates fine on the steamvr "test controller" program

**Comment by Enkiko** [comment]
If I put the tooltip on the toolshelf "Primary Strength" remains around 0.8 or 0.9, but when I take it off, Primary strength immediately goes to 0 until I fully release.

**Comment by Enkiko** [comment]
Gourry seems to have the same bug

**Comment by TehTurk** [comment]
Headsup I would recommend editing the Post vs adding on typically if new updates are found Enkiko. As for the Bug itself, I think that might be intended as before when the Drag Clicking was a thing, you didn't want the input to carry over typically or stuff can bug or wig out for other types of tips/tools/toys.

**Comment by Enkiko** [comment]
Oh? I'm not sure what drag clicking is, but does it have something to do with Primary Strength values like 0 and numbers less than 1? Because I only care if the Primary value is 1 or not 1. Other values should never be accounted for. It caused me hours of confusion to figure out my Neos tooltip actually cares about Primary Strength numbers other than 1. I had to conscientiously remove my finger from the trigger, which seemed unnatural. If intentional, my tests with various people have been showing inconsistency.

**Comment by ukilop** [comment]
the specific use case of this was resolved fyi
but this ""bug"" still persists and is 100% repeatable just not common to come by

**Comment by Frooxius** [comment]
The first behavior is not a bug, that's intentionally designed that way. It prevents the tools from activating immediately when being equipped. It requires you to fully release the trigger, before it registers next click.

Without this behavior tools would misbehave. A brush would draw a small line, weapons would shoot and so on, which is undesirable behavior.

For the primary strength remaining at last value that can be changed to always reset.

**Comment by ukilop** [comment]
ive noticed this exact problem with brushes tho, ill see if i can recreate

**Comment by Frooxius** [comment]
Fix done in 2020.8.10.1195, the values will now reset back to defaults on dequip.
