### ISSUE TITLE
UIUX System.NullReferenceException on mouse over events (and the whole canvas is unresponsive)

### ISSUE THREAD

**Issue by Earthmark** [Frooxius/NeosPublic#878]
Happened earlier in the tutorial world, one of the canvas's no longer accepts inputs and the laser is now a dashed line instead of blue. All buttons are unresponsive (as it seems the canvas is unresponsive).

What happened when the error occurred: was working on a UIUX canvas, and I think it was related to me moving an image element from one canvas to another, where the tint of the image was logix stored in the first canvas. That's the only strange UIUX'y thing I had happening, the particular canvas set is somewhat complex in the number of layers and amount of cross element drives going on (the whole thing is a multi level menu with lots of slow pulses and such). 

Currently the buttons do not fix themselves through duplication or server restarts, it seems the buttons are broke and I'll need to rebuild the screen these were inside of.
As the object is still not working correctly, if you want to inspect it manually or such I can provide the world or take ya to the object in question.

The error where this happened: 
[DESKTOP-5HFQ42U - 2020.8.7.1059 - 2020-08-09 15_40_12.log.zip](https://github.com/Frooxius/NeosPublic/files/5048761/DESKTOP-5HFQ42U.-.2020.8.7.1059.-.2020-08-09.15_40_12.log.zip)
It's 10mb of pretty much the same string again and again, so have fun with that. The event happens near the top and just spams the heck out of the log.

**Comment by Earthmark** [comment]
Creating a new canvas and transplanting all of the slots under the old one into the new one worked, so I think it was a problem with the canvas

**Comment by Frooxius** [comment]
Fixed in 2020.8.10.1195, thanks!
