### ISSUE TITLE
Mask for color does not work properly

### ISSUE THREAD

**Issue by Earthmark** [Frooxius/NeosPublic#879]
The Logix Mask node when done with a color input does not filter the different color channels, instead it acts like a ?: node where the first bool chooses the output and the rest are ignored.

See this picture, the output color should only have a red channel set but instead all channels are set.
![image](https://user-images.githubusercontent.com/1251609/89749574-2719f080-da7d-11ea-89eb-3fde5dbb5638.png)

**Comment by Frooxius** [comment]
Thanks fix coming in the next build!

**Comment by Frooxius** [comment]
Fixed in 2020.8.10.1195 thanks!
