### ISSUE TITLE
No PBS Specular Material

### ISSUE THREAD

**Issue by MR-Alex42** [Frooxius/NeosPublic#88]
When creating a new material with the developer tool I found that if you want to create a PBS specular material your are actually creating a PBS metallic material.

**Comment by sirkitree** [comment]
Ah yes, I tried this today too! Thanks for making a ticket @MR-Alex42 

Steps to replicate:
1. equip devel tip
1. context menu > Create new
1. Material > PBS Specular

Note that the material panel that comes up says PBS Metallic instead.

**Comment by MR-Alex42** [comment]
Thanks for adding the steps. I liked the 'devel' tip a lot. ;-)

**Comment by MR-Alex42** [comment]
Thanks for the steps to reproduce.

**Comment by Frooxius** [comment]
Ooops! I copied the button definition and forgot to change it to PBS_Specular. Rewrote it to use reflection and spawn the material buttons dynamically instead, will be much more robust and automatically pick up any new material types. Thanks for report!

Fix should be pushed to Steam today.
