### ISSUE TITLE
Trying to open a world you don't have access to leads to persistent Loading... text

### ISSUE THREAD

**Issue by ProbablePrime** [Frooxius/NeosPublic#892]
1. Get another user to spawn a world orb of an unpublished world you dont have open access on
1. Try to open it
1. A message appears above the orb letting you know that you dont have permission to open that world (this is good :D)
1. In some cases (Try, Patreon Only worlds, Group Member only Worlds etc) the "Loading" text will still appear. In these cases it will persist itself and never leave the view of the user who tries to open it. This can be confusing and cause issues.

**Comment by Frooxius** [comment]
Fixed in 2020.8.13.259, thanks!
