### ISSUE TITLE
Viewpoint delayed by a frame on some Vive HMDs

### ISSUE THREAD

**Issue by Hayden-da-Serg** [Frooxius/NeosPublic#899]
Someone on Discord (I can't remember who sorry) was also reporting this issue, and I definitely see it myself now, my view point position appears to be delayed by a frame for some reason, I notice this with Motion Smoothing both disabled and enabled, so far this is only reported to happen with a Vive Pro and an original Vive on different GPUs as well, an RX 580 and an RTX 2060 mobile respectively.

I haven't personally noticed this happing in other applications yet but I'll go around to test and see if I can find anything.

This effect is also exponentially worse the lower the frame rate is, and it's very motion sickness inducing.

I would record a video however I have no idea how well it would transfer, as there's no real point of reference to compare to.

**Comment by Hayden-da-Serg** [comment]
Not sure how well this is visible in the video, but I recorded the Neos window in comparison to XS Overlay and Passthrough on the Vive, the effect is VERY apparent in VR and is pretty off-putting
https://streamable.com/jrihwm

**Comment by shiftyscales** [comment]
I'm wondering if this could be a video driver issue. Can you check inside of your Nvidia Control Panel > Manage 3D Settings > Virtual reality pre-rendered frames, and see what the value is set to? If you set it to 1 (if it isn't already) does it improve this?

What happens if you drastically drop the supersampling resolution both in the global settings, and per-application settings for Neos? E.g. set it to 20% for each to lower your GPU utilization/try to impose a CPU bottleneck.

**Comment by RileyGuy** [comment]
I can attest to the 'frame behind' issue as well. I have an RTX 2070 and this happens to me with motion smoothing disabled. It's especially visible with fewer than or equal to 45 frames, and gets exponentially worse the lower the frames get.

**Comment by shiftyscales** [comment]
On investigating this, I'm fairly certain that what this is is a combination of reprojection, and low framerate. This happens most noticeably during rapid accelerations, e.g. sudden movements of your head.

I don't believe this is a fixable issue as it is inherent to how reprojection works on SteamVR. If the framerate is too low, there is no way to properly generate the in-between frames.

To mitigate this issue, you will need to lower your resolution in SteamVR to improve framerates, and decrease overall latency too.

**Comment by Hayden-da-Serg** [comment]
I still find it strange how only some people see this, maybe it's a GPU specific thing? Coffee said that he's never seen this effect before on both his original Vive and his Vive Pro Eye, the only thing that remained the same was his actual computer hardware, I tried to enable legacy reprojection but then it tied the effect to both position and rotation and made everything worse, I also tried with SteamVR Beta 1.14 and SteamVR 1.13 but it still persisted between the two.
