### ISSUE TITLE
Models lost?

### ISSUE THREAD

**Issue by sirkitree** [Frooxius/NeosPublic#90]
I've created a world called DiscWorld. Within it there is an animated turtle fbx, elephant, and the session joiner. It was very difficult to move the turtle so I glued it to the elephants and the session joiner on top of that as in this video: https://www.youtube.com/edit?o=U&video_id=5LZpCIDNuLs

After texturing the turtle, I saved the world and closed it. When I went back in, all of the models were gone. The world orbs still spawn, and I think the particle effects above the plate are still there, but the plate, the elephants, and the turtle are no longer in-world.

The assets are still part of the scene, as you can see if you open up an inspector and look under Assets, but the actual models that were placed into the world and glue to the session joiner are not visible.

Is there a way to get them back?

Does this have something to do with gluing them to the session joiner?

It wasn't a terrible lot of work, but was pretty disheartening. The world is submitted and should be able to be found in the New section of the Content Hub if you'd like to go inspect it.

The only other thing I'll say is that the textures are fairly large and take a bit to load.

**Comment by Frooxius** [comment]
I think I know what it might be. Part of the hierarchy  of the plate is marked as non-persistent (so the orbs don't get saved) and it's possible that gluing patented it under that part.

Not sure though, will have to check when I get home (in car now)

**Comment by sirkitree** [comment]
Thanks, that makes sense if that's what happened. Not sure how one would avoid such a thing in the future, but is there a way to get them back? Since they're still listed under Assets, should I remove them and then re-import? or is there a way for me to retrieve them from the Assets and put them back into the world?

**Comment by Frooxius** [comment]
Hmm, I'm still not entirely sure what has happened. I have tried gluing something to the plate, but that wouldn't put it under the "Root" hierarchy (which is nonpersistent) and I can't think of a scenario in which that would happen. How exactly did you attach them there?

Unfortunately there isn't a way to get them back easily. Under assets are just components which provide the mesh, texture and material data, but none of the hierarchy, transforms and other stuff is there.

You can delete those and import them again. If they're the same assets, you could leave them in there, Neos' asset loader will load the same asset only once, even if referenced multiple times from a scene.

I'll also have some optimization/cleanup routines you could run over worlds, which will find unused assets and clean up things like this.

Sorry for the work loss though :( It looked really beautiful in the video.

**Comment by sirkitree** [comment]
> How exactly did you attach them there?

I imported the turtle, then the elephant, duplicated elephant and placed above turtle. I then imported the session joiner from my local and placed it on top. I then pulled out the glue gun and glued them all together.

Today I redid this, but instead I only glued the elephants and the turtle together, not the session joiner, and everything seems to persist.
