### ISSUE TITLE
Hitting save current avatar on headset deletes self

### ISSUE THREAD

**Issue by Earthmark** [Frooxius/NeosPublic#906]
It turns out you can attempt to save the default headset to your inventory with the blue down arrow, however that respawns you into an avatar that doesn't exist, resulting on no hands or audio output.

If possible, please disable the save current avatar button when the user is in the default headset, or make it do nothing if they hit it!

I had a new user encounter this as they were attempting to save a shared folder, so it's a bit dangerous of a trap in their inventory, the user would probably not have recognized what happened.

I think this has happened to a friend of mine as well a while ago, but I didn't realize what happened and their first time experience was kind of ruined by that (they have not returned since, and they quite without audio and unable to do anything).

**Comment by Frooxius** [comment]
There's already topic for this one here: https://github.com/Frooxius/NeosPublic/issues/725

It's actually a bit more complicated fix. Either we can disable saving default avatar (which needs some way to communicate that it's default) or make the default avatar be saveable, but it's not really designed to be equitable as avatar.
