### ISSUE TITLE
The ability to transfer "ownersip" of a session

### ISSUE THREAD

**Issue by foxy-1423** [Frooxius/NeosPublic#909]
This is mostly to allow people with potato PCs to Transfer all the data handling of a large session to a different user, in case the session Blows up. or if a user has to log off but some of his international friends still wanna keep going.

**Comment by foxy-1423** [comment]
nvm you can just swap sessions xD

**Comment by Enverex** [comment]
For the record there is also an existing issue for transferring hosts - https://github.com/Frooxius/NeosPublic/issues/258
