### ISSUE TITLE
Creating a relay on a cast node wire respawns user

### ISSUE THREAD

**Issue by GunnarO0** [Frooxius/NeosPublic#911]
The sound failed during the recording but the issue is still shown by me (Gunnar0) and a DovahDoVolum
Basically what happens is that when you try to add a relay node using the new feature (grab on wire), the player is immediately destroyed or force re-spawned. Currently I have only experienced this on a wire between a string-parameter conversion and parameter node. I'm not sure if there are other types of wire that this also applies to.
https://youtu.be/RWa0OV9MAhM

**Comment by shiftyscales** [comment]
This bug appears to occur with other cast nodes. E.g. I tried with int to float.

**Comment by shiftyscales** [comment]
[SHIFTYWINDOWS - 2020.8.18.447 - 2020-08-18 19_59_52.log](https://github.com/Frooxius/NeosPublic/files/5093810/SHIFTYWINDOWS.-.2020.8.18.447.-.2020-08-18.19_59_52.log)

**Comment by Frooxius** [comment]
Should be good in 2020.8.20.234 thanks!
