### ISSUE TITLE
Small typos

### ISSUE THREAD

**Issue by BlazeVR** [Frooxius/NeosPublic#912]
Hey Froox, just two typos I have noticed in Neos. 

One with the Body Node Slot, where it should be RightPinky_Tip instead of RIGHT_FINGER_END:

![pic](https://i.imgur.com/i5tcdrr.png)

And when getting (KFC) credits by other players, it says "Recieved" instead of "Received":

![pic](https://i.imgur.com/4r73rmF.png)

**Comment by Frooxius** [comment]
Thanks, fixed the Recieved typo in 2020.8.20.234!

RIGHT_FINGER_END is correct, it's an alias for RightPinky_Tip. We'll need a different enum editing system for that.
