### ISSUE TITLE
Grabbing multiple pictures creates a Save as Screenshot button for each

### ISSUE THREAD

**Issue by H3BO3** [Frooxius/NeosPublic#919]
There is no way to tell which picture refers to which button, so I think when multiple pictures are grabbed it should change the button to indicate it will export multiple pictures ("save as screenshots"?), and then subsequently do so on activation.
![2020-08-21_02 18 25](https://user-images.githubusercontent.com/62123804/90867640-f24a4b00-e352-11ea-9841-8bfa953c1538.jpg)

**Comment by Frooxius** [comment]
Hmm that's a bit odd, they should've been de-duplicated and all share the single button. Is this for newly captured screenshots?

**Comment by H3BO3** [comment]
These are for old pictures I was looking through from my inventory.

**Comment by Frooxius** [comment]
Fixed in 2020.8.25.934, turns out there was a tag mismatch, which didn't make it find the right button! Thanks!
