### ISSUE TITLE
Creating a relay on a driving wire respawns user

### ISSUE THREAD

**Issue by GunnarO0** [Frooxius/NeosPublic#925]
Similarly to a previous issue with creating relays on cast nodes (https://github.com/Frooxius/NeosPublic/issues/911) creating a relay node on a wire between a driver and reference card will respawn the user.
https://youtu.be/Z9MWam6JvRA
![image](https://user-images.githubusercontent.com/69883423/90972315-9a8c1b00-e4dd-11ea-8123-41247cb44491.png)

**Comment by shiftyscales** [comment]
[SHIFTYWINDOWS - 2020.8.25.934 - 2020-08-25 13_03_31.log](https://github.com/Frooxius/NeosPublic/files/5126019/SHIFTYWINDOWS.-.2020.8.25.934.-.2020-08-25.13_03_31.log)
