### ISSUE TITLE
Avatar setup: Feet and Hips on by default

### ISSUE THREAD

**Issue by DeliriousJax** [Frooxius/NeosPublic#926]
The biggest issue and most inconvenient thing to fix is when people don't know to tick the "setup hips and feet" check boxes when importing and setting up avatars. It'd be nice if these were ticked by default as the situations where full body or hips/feet would not be used are rarer for setup such as avatars with no legs at all.

The trade off of this being done ahead of time rather than after the avatar is made is that it is far more inconvenient to try figuring out or explain the setup via inspector. While I also know that the avatar importer is subject for improvement soon, it would still close the gap of time where in until it is updated, we can keep running into this issue.

**Comment by shiftyscales** [comment]
It's not actually all that necessary to set them up at all ahead of time. If a user runs the "Reset Mapping" option on the full-body calibrator, it will automatically place the targets in their appropriate places. This could be a good issue to revisit once the UI for the avatar creator is eventually reworked, however.

Thanks for the input though, @DeliriousJax.

**Comment by Frooxius** [comment]
Closing this as hips and feet were removed in the Avatar Creator and no longer should be calibrated through it.
