### ISSUE TITLE
UV-Free Triplanar Shader

### ISSUE THREAD

**Issue by MR-Alex42** [Frooxius/NeosPublic#93]
One of the most complicated steps in 3D modeling is the required UV-unwrapping for textures.
Actually I think this step can hold back many creators to texture their models appropriately.
With the use of triplanar materials with triplaner shaders this step could be avoided for static meshes including terrains which would ease the texturing for beginners.
Example: https://assetstore.unity.com/packages/vfx/shaders/uv-free-triplanar-shader-pack-23425

**Comment by sirkitree** [comment]
I'm not totally sure what triplanar shaders are, but anything to ease the usability of importing and changing models is welcome indeed imho.

**Comment by sirkitree** [comment]
related to #63

**Comment by wel97459** [comment]
I think in this case, if it was just added to the list of shaders that neos support its not a problem.
And issue #63 is about dynamically importing shaders into neos.

**Comment by Frooxius** [comment]
Done and pushed to nightly-patreon channel. You can now create PBS Triplanar Metallic and PBS Triplanar Specular materials.
