### ISSUE TITLE
Add OnChildDestroyed to Slot Children Events node

### ISSUE THREAD

**Issue by Toxic-Cookie** [Frooxius/NeosPublic#930]
It would be quite helpful to have a separate impulse for OnChildDestroyed on the Slot Children Events node.

Alternatively, the OnChildRemoved impulse could be tweaked to fire an impulse if a child is removed or destroyed.

However, I believe the first solution would make more sense and be more general and flexible.

![2020-08-24 10 03 33](https://user-images.githubusercontent.com/66691163/91074915-1b3c3b80-e5f2-11ea-9f0e-6236a7996a8a.jpg)

**Comment by Frooxius** [comment]
Hmm this is a bit problematic, the system doesn't really track this event and it can't do that without some potentially brittle hackery. When slot is being destroyed, it's actually removed as a child first, so by the time it's actually destroyed, it's no longer a child so the parent doesn't know.

What is your usecase for this? Can't you add LogiX on the children themselves to check if they're destroyed?

**Comment by Toxic-Cookie** [comment]
When a child is moved under a new parent the child removed event fires as expected. When a child is destroyed it's also technically being removed from its parent but not firing off the child removed event which is unexpected and something I would consider to be a bug.

**Comment by Frooxius** [comment]
I'm not sure I understand. Are you saying that the child removed event isn't being fired? My understanding was that you want another type of event added, but the system should fire ChildRemoved even if the child is destroyed.

I have tested this and it seems to work as it's supposed to.

**Comment by Toxic-Cookie** [comment]
A separate event specific to the child being destroyed was an idea of how to fix this but not necessary as fixing the ChildRemoved event would work too. In my testing I've found that ChildRemoved does not fire if the child in question gets destroyed instead of getting parented to another slot.

**Comment by Toxic-Cookie** [comment]
I tested this once again and strangely enough it seems to be working. It may have been a fluke in testing.

**Comment by Frooxius** [comment]
Ah ok! Let me know if it comes up in some setup. One thing, if you save the deleted Slot into variable and use it later, it will act like it's gone (null), so if that was part of your setup, that might've been a potential cause.
