### ISSUE TITLE
Improve description of the Discord invite request prompt

### ISSUE THREAD

**Issue by mralext20** [Frooxius/NeosPublic#932]
eg. the existing prompt has no description that its comes from discord.

https://this-is-a.stale-me.me/i/tp2y.jpg

**Comment by Frooxius** [comment]
Ah yeah, that's pretty old thing! I can just add a bit more text describing that they're trying to join through the invite.

**Comment by Frooxius** [comment]
Tweaked the message in 2020.8.25.934 to include that it's coming from Discord. Thanks!
