### ISSUE TITLE
streamer camer does not respect no spawn objects permissions like finger photo does

### ISSUE THREAD

**Issue by mralext20** [Frooxius/NeosPublic#934]
this is specificly related to the 'spawn photo in world' camera setting.

**Comment by Frooxius** [comment]
It seems like I fixed this a while back and forgot to close this, but I've changed the behavior a bit in 2020.10.5.476. Now you can use the finger photo camera, but the photo just won't spawn in the world. It'll save to normal screenshot locations.

**Comment by mralext20** [comment]
this is a much better solution than blocking it! thanks froox!
