### ISSUE TITLE
Support niconico streams with Video Player

### ISSUE THREAD

**Issue by Enkiko** [Frooxius/NeosPublic#935]
You should be able to play streams/videos from nicovideo.jp with the Video Player
This is a massively popular video website in Japan.
It is supported by ytdl https://github.com/ytdl-org/youtube-dl/blob/master/docs/supportedsites.md

A streamer requested this so they can keep an eye on the state of their stream and everyone can see if they're on screen etc, by looking at the video player during the stream.

**Comment by Enverex** [comment]
Unfortunately this still doesn't work as YTDL can't download from that site without authentication anymore. Not a Neos specific issue though so not sure anything can be done our side.
![image](https://user-images.githubusercontent.com/958670/91844392-473d6980-ec4f-11ea-8fe0-ad25ca03696f.png)

**Comment by Frooxius** [comment]
Yeah, unfortunately if the video can't be loaded without logging in, we can't support this on our end, as there's no way to get the actual video.
