### ISSUE TITLE
Double Sided Translucent Material

### ISSUE THREAD

**Issue by MR-Alex42** [Frooxius/NeosPublic#94]
I wanted to import some plant models with translucency that require a shader that renders on both sides.
None of the available material types was fitting for my purpose.

**Comment by wel97459** [comment]
I also have some models in the same boat.

**Comment by sirkitree** [comment]
This might be better attached to #63 - generally, shader support is not implemented yet. If you think this could be consolidated, please close this one out and we'll have a reference to this at least.

**Comment by wel97459** [comment]
I think in this case, if it was just added to the list of shaders that neos support its not a problem.
And issue #63 is about dynamically importing shaders into neos.

**Comment by Frooxius** [comment]
Done and pushed to nightly-patreon channel on Steam. You can now use PBS Dual Sided Specular and PBS Dual Sided Metallic materials.

They have a "Transparent" property, which allows you to use the transparent variant. The non-transparent variant also supports all culling modes (Off, Front and Back). 


Not sure when adding own shaders will become possible with Neos, so for now I'll add them manually as you need them.
