### ISSUE TITLE
Avatar heuristics tweak for Eye bone detection

### ISSUE THREAD

**Issue by H3BO3** [Frooxius/NeosPublic#941]
If the avatar creator heuristics can find "eye" && "ball" first, use that instead of the first "eye" mention. Had to fix an avatar where the eyebrows got set up as eyes, plus I've seen it before in yet another avatar. Please disregard if this behavior is already implemented, must have been fluke cases if so.

**Comment by Frooxius** [comment]
Hmm, if there's "brow" in the name of the bone then it should already be excluded from being considered an eye, so it's a bit strange that it didn't.

Do you have the exact naming of the bones or a sample model?

**Comment by H3BO3** [comment]
I will get details and get back to you when I can. Another question, will it ignore "lid" as well?

**Comment by Frooxius** [comment]
No, "lid" is not ignore, I'll add it to the list, thanks!

**Comment by Enverex** [comment]
In the same vein, would it be possible to have a "Rerun eye manager setup" somewhere in the same way you can rerun the hand setup? Having to set up the eye manager manually was quite time consuming.

**Comment by Frooxius** [comment]
It's possible, but that would be a separate feature, it's not part of the heuristics detection.

**Comment by shiftyscales** [comment]
As of 2020.8.31.1203: `- Biped Rig heuristics will now ignore bones containing "eye" and "lid" (e.g. "eyelid") as eye bones (based on feedback from @H3BO3)`
