### ISSUE TITLE
Add an Absolute Fill mode to the TextureSizeDriver

### ISSUE THREAD

**Issue by H3BO3** [Frooxius/NeosPublic#942]
I have a video screen in my homeworld. I use the TextureSizeDriver to size the screen to the correct aspect ratio of the video. However, I have limited area on the wall. In my tests with videos involving extreme aspect ratios, the video screen would end up too large on one axis and go past the wall area. I would like a mode for the TextureSizeDriver where you provide the maximum dimensions the output can be on X and Y axes, and it uses the closest axis to limit the other axis, filling the video within the bounds while maintaining the correct aspect ratio.

**Comment by shiftyscales** [comment]
2020.9.5.1190:
`- Added "MaxSize" to TextureSizeDriver, which allows clamping the maximum size of the driven value (aspect ratio is preserved) (requested by @H3BO3)`
