### ISSUE TITLE
Particle Collision

### ISSUE THREAD

**Issue by wel97459** [Frooxius/NeosPublic#95]
It seems that particle collision only works if the particle emit was spawn with the world.
If you try and take the particle emit tool from the hub to some other world, the collision will stop working.

**Comment by Frooxius** [comment]
Hmm this is odd. Do you mean the red particle emitting tool? Or custom built particle emitters? Will the collision work when you  save the world, exit Neos and load it again?

There was an issue in the particle collision thread worker, which stopped it from working randomly, it's possible it wasn't fully fixed.

**Comment by wel97459** [comment]
The particle emitting tool, But I also think it's a problem with any emitter.  and yes if you save the world and load it back it will work.

**Comment by Frooxius** [comment]
Oh! It's the same issue. It has been plaguing me since early alphas, it always seemed to happen very randomly. But you noticing that it happens when transferring it between worlds has helped a lot, it's now fixed for good! Thank you!

Updated build will be pushed to Steam within a few hours.
