### ISSUE TITLE
Set Character Gravity/Set Character Velocity Logix Nodes Crash

### ISSUE THREAD

**Issue by Vigilabo** [Frooxius/NeosPublic#950]
Using NaN or Infinity as inputs for Set Character Gravity or Set Character Velocity nodes causes Neos to lock up due to the values not being numbers.

**Comment by shiftyscales** [comment]
This makes sense as those would cause things in the physics engine to corrupt. I imagine it should be possible to put protections in place to prevent that.

**Comment by Frooxius** [comment]
Added a guard for invalid values being fed into the CharacterController in 2020.9.2.10, that should prevent any issues like this. Thanks!
