### ISSUE TITLE
Suggestion: When batch importing a folder, name the "Folder Import" slot after the folder name

### ISSUE THREAD

**Issue by ProbablePrime** [Frooxius/NeosPublic#951]
Hey,

I recently had to do a lot of processing of volumetric data using the batch import button of the file manager. with 20ish folders of data to process it quickly became impossible to see what I was looking at and relate it back to the original folder.

When using the batch import button everything that's setup get's placed under a "Folder Import" slot, it would be useful if this Folder Import Slot's Name was the name of the folder that you were batch importing.

Thanks

**Comment by shiftyscales** [comment]
This issue already exists via #406.

Also relevant is #252.

**Comment by ProbablePrime** [comment]
I disagree, that is for nested folders, this is a singular folder.

**Comment by shiftyscales** [comment]
Sure, this issue is much smaller in scope/more manageable, definitely. I just figured that if the other issues were implemented it would implicitly satisfy this one, but not the other way around.

**Comment by Frooxius** [comment]
Made the change in 2020.9.3.56 thanks!
