### ISSUE TITLE
Enhancement: Context Menu Screenshots should save to Pictures/NeosVR not the Steam Screenshots

### ISSUE THREAD

**Issue by TehTurk** [Frooxius/NeosPublic#957]
It's a bit easier and a bit more natural when looking for photos. Most will not dig through their Steam install.

**Comment by Frooxius** [comment]
They already are saving to both. However there's a bug that marks the files as "Hidden" if you have the "Keep original screenshot format" on: https://github.com/Frooxius/NeosPublic/issues/952

**Comment by TehTurk** [comment]
Understood, Sorry for the duplicate.

**Comment by Frooxius** [comment]
It's ok, it's not immediately obvious that it's the same thing. Should be fixed soon!
