### ISSUE TITLE
Top-left alignment for Inventory and Logix node selector

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#959]
Perhaps these were missed in the recent change of the latest build to move ScrollRect to top-left by default?

Top-left alignment would make a lot of sense for these UIs in placing certain buttons like the back buttons in a consistent position.

Change requested by A Monsoon of Babies, and others.

**Comment by Frooxius** [comment]
Changed in 2020.9.2.10 thanks!
