### ISSUE TITLE
Issue/Fix: VRIK Height Compensation needs a clamp

### ISSUE THREAD

**Issue by TehTurk** [Frooxius/NeosPublic#962]
Currently if your typing in a value and setting Height Compensation on an Avatar, you'll set it to a 0 which causes a NaN or Infinity in the IK data and corrupt it, as coming back from that doesn't truly "fix" the IK's data. This has been a common bug for awhile, but I realized I never reported untill I remembered I should after interacting with Enkiko's Avatar Issues today.

**Comment by Frooxius** [comment]
Added clamp in 2020.9.2.10 thanks!
