### ISSUE TITLE
"Private Worlds" checkbox breaks search while filtered by owner

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#963]
Steps to replicate:
- Filter the world list to worlds from a particular owner, e.g. `gearbell`
- Press the "Private Worlds" checkbox

The search bar will get stuck in a searching state, and no search queries will update until Neos is restarted.

Issue reported by Cyro.
[SHIFTYWINDOWS - 2020.8.31.1203 - 2020-09-01 00_27_28.log](https://github.com/Frooxius/NeosPublic/files/5154588/SHIFTYWINDOWS.-.2020.8.31.1203.-.2020-09-01.00_27_28.log)

**Comment by Frooxius** [comment]
Fixed in 2020.9.2.10 thanks!
