### ISSUE TITLE
Adding a dynamic variable space over an existing dynamic variable freezes the game

### ISSUE THREAD

**Issue by Earthmark** [Frooxius/NeosPublic#964]
Seems like adding the component alone does fine, but adding the component over an existing value field does not. There were no other value spaces over the world as far as I'm aware, so this may be a no variable space -> some variable space bug.

Here's a log:
[DESKTOP-5HFQ42U - 2020.8.31.1203 - 2020-09-01 01_40_58.log](https://github.com/Frooxius/NeosPublic/files/5154980/DESKTOP-5HFQ42U.-.2020.8.31.1203.-.2020-09-01.01_40_58.log)

**Comment by Frooxius** [comment]
Fixed in 2020.9.2.10 thanks!
