### ISSUE TITLE
To HSL and From HSL do not seem to match with some inputs

### ISSUE THREAD

**Issue by mralext20** [Frooxius/NeosPublic#967]
https://this-is-a.stale-me.me/i/gykd.jpg 

discovered by Azavit#2360 
https://cdn.discordapp.com/attachments/439422161657135106/750285575105282069/20200901022335_1.jpg

of note, the Hue output seems to be negative, atleast in my example.

**Comment by Frooxius** [comment]
Fixed in 2020.9.2.10 thanks!
