### ISSUE TITLE
Bug: WorldListManager Runs Locally, and you can't specify a user

### ISSUE THREAD

**Issue by TehTurk** [Frooxius/NeosPublic#968]
Went to play with some of the new components today, found out an issue with the WorldListManager. All updates coming from it are intended to be local, so when brought into a session to tweak or show worlds in a similar manner to how the world orbs did, it updates for every user. Would it be possible to specify a user, or have it update only on host?

**Comment by Frooxius** [comment]
This is not a bug, it's currently only designed to work properly in the Userspace. Ability to run it in-world with specified user is coming.

**Comment by Frooxius** [comment]
2020.9.16.596 now allows specifying  user and will run only on host if none is specified. Let me know if there are any trouble with it!
