### ISSUE TITLE
Remember `Freeform Dash` state

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#969]
Requested by Cyro, and others.

Remembering the freeform dash state improves the behavior of the dash when it is left above or below the player between sessions.
![image](https://user-images.githubusercontent.com/54213390/91897791-aac79700-ec4f-11ea-8c9e-11508ffc726a.png)
![image](https://user-images.githubusercontent.com/54213390/91897818-b450ff00-ec4f-11ea-925e-6c939048dfd4.png)

**Comment by mralext20** [comment]
> Yeah the seated mode and freeform are not persistent on purpose right now.

> I could make them save, but it can lead to some problematic scenarios. E.g. if you forget it's on, you'll have weird offset next time you run Neos and you'll have to toggle it on and off. Similarly the freeform dash can make it appear at weird angle on startup.

> It depends on what would everyone generally prefer?

https://discord.com/channels/402159838827905024/439422161657135106/729609276808495175

**Comment by Frooxius** [comment]
Ok I've added it in 2020.9.3.56. Usually I end up wishing for it myself anyways, so I think it'll be better that way. Thanks!
