### ISSUE TITLE
[LogiX node] Get Grabbable from Slot

### ISSUE THREAD

**Issue by ukilop** [Frooxius/NeosPublic#970]
One of the occasional struggles with LogiX I'm coming across is how to detect which hand an object is being grabbed by,
this can be solved with a grabbable component reference but that requires direct access to said component.

What I suggest is a LogiX node that takes a slot reference and returns the grabbable component on that slot if any.
This _somewhat_ already exists for tooltips, albeit without a slot reference.

**Comment by ProbablePrime** [comment]
This is not likely until component access. See: #265

**Comment by TehTurk** [comment]
There is currently a GrabberBodyNode that does kinda help with knowing which hand is grabbing something by using BodyNodes which have Enums.

**Comment by H3BO3** [comment]
Apparently they want it from outside the object @TehTurk . Still not sure what application can't be done from the inside

**Comment by TehTurk** [comment]
I know, but with the hierarchy of how it works it goes Grabber <- Grabbabble where it needs to climb up not down knowing which *Grabbable* to grab is tricky in that context if you grab multiple things.

**Comment by H3BO3** [comment]
Closing this issue as component access falls under a specific planned feature, and there may be a more general solution for this problem.
