### ISSUE TITLE
Close World modal scaled incorrectly on Friends screen

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#975]
Open a new world, and press the Close World button while on the Friends screen, and the resultant modal isn't scaled correctly:
![image](https://user-images.githubusercontent.com/54213390/92029253-242bbc00-ed1a-11ea-87d8-7de08c54f0a6.png)

It appears that the modal is scaled differently depending on the screen. Most scale normally, the only other outlier is the Session screen in which the text is tiny:
![image](https://user-images.githubusercontent.com/54213390/92029368-47ef0200-ed1a-11ea-84da-923474c96dd5.png)

To compare- this is how the modal looks while on the dash:
![image](https://user-images.githubusercontent.com/54213390/92029423-5a693b80-ed1a-11ea-8ef8-c491c432d24a.png)

**Comment by Frooxius** [comment]
Added workaround in 2020.9.5.1190, will switch to the  Home screen if you're on the older legacy screen. Thanks!
