### ISSUE TITLE
When joining sessions, default size is larger than expected.

### ISSUE THREAD

**Issue by candypheonixIO** [Frooxius/NeosPublic#976]
When joining a session, I have to reset my scale back to normal.

**Comment by shiftyscales** [comment]
Do you have a DefaultUserScale component on your avatar anywhere? Does it have `SetOnEquip` checked or unchecked?

What scale are you starting at/what is the expected scale/'normal'?

**Comment by candypheonixIO** [comment]
Noe, just randomly scaled up when joining sessions, I believe when loading into my fav avatar. You can ask a few players on right now and you'll get the same or similar answer.

**Comment by shiftyscales** [comment]
What are some examples of worlds/sessions you've seen this behavior in?

And I'm still curious (if you happen to know/when it happens again)- what scale do/did you start at?

**Comment by candypheonixIO** [comment]
all

**Comment by candypheonixIO** [comment]
There is also an issue that even Ren is having were things are locally firing or defaulting to true on their favorite avatar when they are meant to be off or false.

This is happening to all worlds where players are allowed to spawn in as their Default avatar, but when you spawn in as the world set default avatar or no default avatar / favorite avatar, this issue does not occur, and when switching into your regular avatar after being spawned in as a world default avatar / neos headset avatar, this issue does not occur.

**Comment by AMonsoonofBabies** [comment]
I've experienced the "larger than normal" issue just now, using screen mode. Booting up Neos and appearing in my default home world in a simple default avatar resulted in me being much larger. I have seen comments from others in the Discord server who have experienced the same issue across numerous worlds with varying avatars.

**Comment by Electronus** [comment]
I just had this happen in a basically new grid space world that kier is hosting. I have no default scale on my avatar and the spawn area has not been touched.

**Comment by shiftyscales** [comment]
I believe this is tied to the recent change to clamp the AvatarHeightCompensation value between 0.25-2.

I just loaded into my local home, and was defaulted to a scale of 2.

The default VR headset avatar doesn't have an AvatarHeightCompensation value. I believe these factors are related.

**Comment by Frooxius** [comment]
This was because of changes to some low level functions in Neos, which changed how were vector streams initialized, which in turn messed up some calculations. Should be good on 2020.9.3.357 now, thanks!
