### ISSUE TITLE
manually entered malformed neosdb:// (missing one /) causes errors when attempting to save the world

### ISSUE THREAD

**Issue by mralext20** [Frooxius/NeosPublic#981]
replication: 

open new empty world
create new empty, with ValueField<Uri>
type somthing like `neosdb://fail.webp`
note that the URL gets changed to `neosdb://fail.webp/`
save the world to the cloud

at this point, attempting to close neos will prevent you from properly closing neos completely, instead getting stuck on syncing n items (0%), alt-F4 required

[ALEXDESKTOP - 2020.9.3.357 - 2020-09-03 15_10_02.log](https://github.com/Frooxius/NeosPublic/files/5171829/ALEXDESKTOP.-.2020.9.3.357.-.2020-09-03.15_10_02.log)

**Comment by Frooxius** [comment]
Fixed in 2020.9.5.1190, thanks for report!
