### ISSUE TITLE
Highlighted message doesn't show Twitch emotes

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#988]
On stream, a user had highlighted a message containing the basic smiley emote ":)". On the highlight this message did not appear.
![2020-09-04 15 23 53](https://user-images.githubusercontent.com/54213390/92288786-06e62180-eec3-11ea-9c9d-cb34eb85184d.png)

**Comment by Frooxius** [comment]
Should be fixed in 2020.9.5.1190!
