### ISSUE TITLE
Cosmetic issue - increase line spacing in login / logout / user info facet

### ISSUE THREAD

**Issue by Zyzyl** [Frooxius/NeosPublic#989]
![Text issue](https://user-images.githubusercontent.com/66165438/92299298-15771c00-ef49-11ea-976f-ad253243a096.jpg)

See picture - the Patreon info is very close / overlapped by the y's in my username.

**Comment by Frooxius** [comment]
Did tweaks in 2020.9.5.1190, hopefully it's better now. Thanks!
