### ISSUE TITLE
Avatar Creator Bone Names - Prefer Longer Chains

### ISSUE THREAD

**Issue by Earthmark** [Frooxius/NeosPublic#993]
I've seen an avatar with two sets of bones named arms and wrist, one for a 'twist' and the other for the actual arm or wrist. The avatar setup system preferred the first slot though, which was the 'twist' bone instead of the actual bone.

If possible, could the avatar creator, when faced with two or more possible candidates, take the candidate with the longer child bone chain? That would cause the creator to bind to the correct bones in this case (as the arm would take the one with a wrist bone, and the wrist bone would take the one with fingers).

I may have more findings related to interesting bone naming schemes (such as some fingers having the root finger bone named "hand" instead of the finger name [this is how my yote avatar originally came]), but that's later.

**Comment by shiftyscales** [comment]
Any chance that you could provide the avatar, and/or its hierarchy/bone names directly? It can help Frooxius in adjusting the heuristics/testing if it imports correctly by having a sample model to use, @Earthmark.

**Comment by Frooxius** [comment]
Can you provide me with an example rig that had issues? Preferring longer chains doesn't really make too much sense in the context, because the correct chain will always be the same length. The system already looks for chains that contain the full expected list of the bones, so the tweaks to heuristics probably need to differentiate differently.

**Comment by Earthmark** [comment]
I don't have it on me anymore, it was something I saw a new player experiencing. I'll try to find the avatar, and next time I'll get a copy to have as context.

**Comment by Earthmark** [comment]
I don't have the model and I haven't run into this again, closing until I run into this again if I do.
