### ISSUE TITLE
Enable use of 'bendy laser' instead of direct raycast on RawDataTooltip

### ISSUE THREAD

**Issue by mralext20** [Frooxius/NeosPublic#994]
atleast when use laser is turned on in the rawdatatooltip component.

**Comment by Frooxius** [comment]
RawDataTooltip doesn't do any raycasting on itself, but I can expose the current bendy laser hit as a property.

**Comment by Frooxius** [comment]
2020.9.9.214 now has node GetRawDataTooltipHit which will give you the current bendy laser hit if present. Make sure to check from the tool update event, it won't work for other users and can produce incorrect result in other contexts.
