### ISSUE TITLE
Unity+FrooxEngine connector broken

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#995]
Discovered by Jeana, and confirmed by Enverex and myself, it appears that Neos currently cannot run under Linux.
[Player.log](https://github.com/Frooxius/NeosPublic/files/5184211/Player.log)

It appears that Unity is not properly initializing FrooxEngine, as no log is generated by Neos, only Unity.
```
 TypeLoadException: VTable setup of type SystemInfoConnector failed
   at UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) [0x00026] in <11c3ef05f0294860a73da09e45414fab>:0 
```

**Comment by Frooxius** [comment]
Looks like a corrupt binary. I'll recompile it, hopefully that fixes things.

**Comment by Frooxius** [comment]
Pushed recompiled binary in 2020.9.9.214, please let me know if this fixes the issue.

**Comment by shiftyscales** [comment]
This appears to have fixed the issue. Everything appears to be working properly now, thanks!
